(function(root){'use strict';
const H=root&&root.FLRPG_FINAL_MATCH_RARE_SCENARIOS;if(!H||H.__v37PresentationPatched)return;
const originalRun=H.run.bind(H),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function cloneFrame(f){return{...f,ball:f?.ball?{...f.ball}:f?.ball,players:Array.isArray(f?.players)?f.players.map(p=>({...p})):f?.players};}
function inspectCrossContact(result){if(!result||!['CROSS_LEFT','CROSS_RIGHT'].includes(result.key)||!Array.isArray(result.frames)||result.frames.length<2)return result;let contactIndex=-1,contactPlayerId=null,contactGap=null;for(let i=1;i<result.frames.length;i++){const prev=result.frames[i-1],cur=result.frames[i];if(prev?.ball?.kind!=='CROSS'||cur?.ball?.kind==='CROSS'||!cur?.ball)continue;const changedTouch=cur.ball.lastTouchPlayer&&cur.ball.lastTouchPlayer!==prev.ball.lastTouchPlayer,pid=cur.ball.ownerId||(changedTouch?cur.ball.lastTouchPlayer:null),p=pid?(cur.players||[]).find(x=>x.id===pid)||null:null;contactIndex=i;contactPlayerId=p?.id||pid||null;if(p)contactGap=Math.hypot(Number(p.x)-Number(cur.ball.x),Number(p.y)-Number(cur.ball.y));break;}return{...result,presentationContact:{applied:false,policy:'ENGINE_TRAJECTORY_ONLY_V37',contactIndex,contactPlayerId,observedGap:Number.isFinite(contactGap)?Number(contactGap.toFixed(3)):null,engineOutcomeUnchanged:true,futureOutcomePrecomputed:false}};}
function lockGkDiveAim(result){if(!result||!['GK_SHOT_LONG','GK_SHOT_BOX','GK_SHOT_CLOSE'].includes(result.key)||!Array.isArray(result.frames)||!result.frames.length)return result;const frames=result.frames.map(cloneFrame);let committedSide=0,shotTargetY=null;for(const f of frames){const gk=(f.players||[]).find(p=>p.id==='H-GK'||(p.team==='HOME'&&p.role==='GK'));if(!gk||f?.ball?.kind!=='SHOT')continue;const intent=f.ball.v37DiveIntent,ty=Number.isFinite(intent?.shotTargetY)?Number(intent.shotTargetY):Number.isFinite(f.ball.shotTargetY)?Number(f.ball.shotTargetY):null;if(ty==null)continue;shotTargetY=ty;committedSide=Number(intent?.side)||Math.sign(ty-Number(gk.y))||1;break;}if(!committedSide)return{...result,frames};let applied=0;for(const f of frames){const gk=(f.players||[]).find(p=>p.id==='H-GK'||(p.team==='HOME'&&p.role==='GK')),task=String(gk?.action||gk?.tacticalTask||'');if(!gk||f?.ball?.kind!=='SHOT'||!/GK_(SAVE|RUSH_BLOCK)/.test(task))continue;gk.tx=Number(gk.x);gk.ty=clamp(Number(gk.y)+committedSide*1.0,.8,67.2);f.presentationOnly={...(f.presentationOnly||{}),gkDiveAimCommitted:true};applied++;}return{...result,frames,presentationGkAim:{applied:applied>0,frameCount:applied,shotTargetY,side:committedSide,policy:'INITIAL_SHOT_DIRECTION_ONLY_V37',engineOutcomeUnchanged:true,futureOutcomePrecomputed:false}};}
function repair(result){return lockGkDiveAim(inspectCrossContact(result));}
H.run=function(key,seed,opts){return repair(originalRun(key,seed,opts));};
H.__v37PresentationPatched=true;
})(typeof globalThis!=='undefined'?globalThis:this);
