(function(){'use strict';
const $=id=>document.getElementById(id),dockId='finalMatchTestDock';let current=null,last=null,seedSerial=1,replayRaf=0;
function harness(){return window.FLRPG_FINAL_MATCH_RARE_SCENARIOS}
function rows(h){return(h?.KEYS||[]).map(key=>({key,label:h.SCENARIOS?.[key]?.label||key}))}
function summary(h,r){try{return h.summary(r)}catch(_){return null}}
function nextSeed(s){const m=String(s||'FINAL-MATCH-TEST').match(/^(.*?)-(\d+)$/);return m?`${m[1]}-${Number(m[2])+1}`:`${s||'FINAL-MATCH-TEST'}-${seedSerial++}`}
function draw(s){const c=$('heroPitch');if(!c||!s)return;const x=c.getContext('2d'),W=c.width,H=c.height,px=v=>28+(Number(v)||0)/105*(W-56),py=v=>24+(Number(v)||0)/68*(H-48);x.clearRect(0,0,W,H);x.fillStyle='#315b37';x.fillRect(0,0,W,H);x.strokeStyle='rgba(240,255,242,.78)';x.lineWidth=3;x.strokeRect(28,24,W-56,H-48);x.beginPath();x.moveTo(px(52.5),24);x.lineTo(px(52.5),H-24);x.stroke();const ball=s.ball,hero=$('heroPlayer')?.value;for(const p of s.players||[]){const cx=px(p.x),cy=py(p.y),r=p.id===hero?14:11,gk=p.role==='GK',dive=gk&&/GK_(DIVE|SAVE|RUSH_BLOCK)/.test(String(p.action||p.tacticalTask||''));x.fillStyle=p.team==='HOME'?(gk?'#7dd3fc':'#2563eb'):(gk?'#fca5a5':'#dc2626');x.strokeStyle=p.id===hero?'#fff':'rgba(255,255,255,.88)';x.beginPath();if(dive){x.save();x.translate(cx,cy);x.rotate(Number.isFinite(p.bodyAngle)?p.bodyAngle:Math.atan2(p.vy||0,p.vx||1));x.ellipse(0,0,r*1.65,r*.72,0,0,Math.PI*2);x.restore()}else x.arc(cx,cy,r,0,Math.PI*2);x.fill();x.stroke();x.fillStyle='#fff';x.font='bold 8px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(p.slot||p.role||'',cx,cy)}if(ball){x.beginPath();x.fillStyle='#fff';x.arc(px(ball.x),py(ball.y),7,0,Math.PI*2);x.fill()}if($('heroState'))$('heroState').textContent=`FINAL MATCH TEST · ${s.phase||'-'} · ${ball?.mode||'-'}`}
function cancel(){if(replayRaf)cancelAnimationFrame(replayRaf);replayRaf=0}
function replay(r,status){cancel();const fs=r?.frames||[];if(fs.length<2){draw(r?.snapshot||r?.entrySnapshot);return}let i=0;const tick=()=>{draw(fs[i]);if(i++<fs.length-1)replayRaf=requestAnimationFrame(tick);else{replayRaf=0;status.textContent=r.pending?'검증 실행 완료 · 사용자 선택 경계 · 자동 행동 없음':`${r.label||r.key} · ${(summary(harness(),r)?.events||[]).join(' → ')||'이벤트 없음'}`}};replayRaf=requestAnimationFrame(tick)}
function evidence(h,r){return{schemaVersion:'FLR_FINAL_MATCH_FORCED_REPORT_1.0',scenarioKey:r.key,label:r.label,seed:r.seed,forcedSetup:r.forcedSetup,stopReason:r.stopReason,futureOutcomePrecomputed:r.futureOutcomePrecomputed===false?false:null,summary:summary(h,r),boundary:r.boundary,entrySnapshot:r.entrySnapshot,frames:r.frames||[],snapshot:r.snapshot,actualEvents:r.actualEvents||[],pending:r.pending||null}}
function mount(){const h=harness(),pitch=$('heroPitch');if(!h||!pitch)return;let root=$(dockId);if(!root){root=document.createElement('aside');root.id=dockId;root.className='final-match-test-dock';pitch.closest('.pitch-card')?.insertAdjacentElement('afterend',root)}root.innerHTML='<strong>FINAL MATCH TEST</strong><label>시나리오<select data-field="scenario"></select></label><label>SEED<input data-field="seed" value="FINAL-MATCH-TEST-1"></label><button data-action="run">실행</button><button data-action="replay" disabled>다시보기</button><button data-action="bug" disabled>버그 리포트</button><p data-status>하니스를 실행하세요.</p>';const sel=root.querySelector('[data-field=scenario]'),seed=root.querySelector('[data-field=seed]'),status=root.querySelector('[data-status]'),btn=a=>root.querySelector(`[data-action=${a}]`);rows(h).forEach(r=>{const o=document.createElement('option');o.value=r.key;o.textContent=r.label;sel.appendChild(o)});root.addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(a==='run'){try{const r=h.run(sel.value,seed.value.trim()||'FINAL-MATCH-TEST-1',{});if(r.futureOutcomePrecomputed!==false)throw Error('precompute');current=last=r;status.textContent=r.pending?'사용자 선택 경계 · 자동 행동 없음':`${r.label||r.key} · ${(summary(h,r)?.events||[]).join(' → ')||'이벤트 없음'}`;btn('replay').disabled=false;btn('bug').disabled=false;draw(r.entrySnapshot||r.snapshot)}catch(err){status.textContent=`실행 실패 · ${err.message||err}`}}else if(a==='replay')replay(current||last,status);else if(a==='bug'){window.FLR_FINAL_MATCH_FORCED_REPORT=evidence(h,current||last);$('heroBugReport')?.click()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();})();
