(function(root){'use strict';
const H=root&&root.FLRPG_FINAL_MATCH_RARE_SCENARIOS;if(!H||root.__FLR_V37_INTERACTIVE_DOCK_PATCH__)return;root.__FLR_V37_INTERACTIVE_DOCK_PATCH__=true;
function mount(){const dock=document.getElementById('finalMatchTestDock');if(!dock)return;let bar=dock.querySelector('[data-v37-forced-choice]');if(!bar){bar=document.createElement('div');bar.dataset.v37ForcedChoice='1';bar.style.display='none';bar.style.gap='6px';bar.style.flexWrap='wrap';bar.style.marginTop='8px';const status=dock.querySelector('.final-match-test-dock__status');status?.insertAdjacentElement('afterend',bar);}const replay=dock.querySelector('[data-action="replay"]'),status=dock.querySelector('.final-match-test-dock__status');
 function render(){const ctx=H.__v37Interactive,result=ctx?.result,pending=result?.pending;if(result?.key!=='ST_BREAKAWAY'||!pending||!Array.isArray(pending.options)||!pending.options.length){bar.style.display='none';bar.innerHTML='';return;}bar.style.display='flex';bar.innerHTML='';const label=document.createElement('strong');label.textContent='단독 돌파 다음 행동 선택:';label.style.width='100%';bar.appendChild(label);for(const o of pending.options){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=o.label||`${o.id}${o.targetId?` → ${o.targetId}`:''}`;b.dataset.choiceId=o.id||'';b.dataset.targetId=o.targetId||'';bar.appendChild(b);}}
 bar.addEventListener('click',ev=>{const b=ev.target.closest('button[data-choice-id]');if(!b)return;try{const out=H.applyForcedChoice?.(b.dataset.choiceId,b.dataset.targetId||null);if(!out?.ok)throw new Error(out?.reason||'FORCED_CHOICE_FAILED');if(status)status.textContent=out.continuation?'선택 적용 완료 · 연계 선택이 이어집니다.':'선택 적용 완료 · 실제 엔진 결과를 재생합니다.';render();const replayContinuation=root.FLR_FINAL_MATCH_TEST_DOCK?.replayContinuation;if(typeof replayContinuation==='function')replayContinuation(out.result);else if(replay&&!replay.disabled)replay.click();}catch(err){if(status){status.textContent=`선택 적용 실패 · ${err.message||err}`;status.classList.add('is-error');}}});
 dock.addEventListener('click',ev=>{const action=ev.target.closest('button')?.dataset.action;if(action==='run'||action==='rerun')setTimeout(render,0);});
 if(status)new MutationObserver(()=>render()).observe(status,{childList:true,characterData:true,subtree:true});render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(typeof globalThis!=='undefined'?globalThis:this);
