(function(root,factory){const ge=(typeof globalThis!=='undefined'&&globalThis.FLRPG_CONTINUOUS_CORE)||null,gp=(typeof globalThis!=='undefined'&&globalThis.FLRPG_PROTAGONIST_MATCH_CONTROLLER)||null,api=factory(ge,gp);if(typeof module==='object'&&module.exports)module.exports=api;else root.FLRPG_LIVE_V06_SCENE_AUTHORITY=api;})(typeof globalThis!=='undefined'?globalThis:this,function(GLOBAL_E,GLOBAL_P){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const deep=v=>v==null?v:JSON.parse(JSON.stringify(v));
const SLOT_Y={GK:34,LB:9,LCB:25,RCB:43,RB:59,LCM:20,CM:34,RCM:48,LW:8,ST:34,RW:60};
function localToWorld(team,x,y){return team==='HOME'?{x,y}:{x:105-x,y:68-y};}
function localBase(p,ctx){const poss=ctx.possession===p.team,pr=ctx.ball.progress*100,s=ctx.structure[p.team]||{lineHeight:50,width:50,transitionDebt:0},zone=ctx.zone||'MIDFIELD',phase=ctx.phase||'BUILD_UP';let bx={GK:6,FB:25,CB:22,CM:45,WF:65,ST:70}[p.role]||45;bx+=(poss?1:-1)*clamp((pr-50)*.20,-9,11);bx+=(Number(s.lineHeight||50)-50)*.10;if(poss&&p.role==='CM'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE')){const high=zone==='BOX'||phase==='CHANCE';bx=Math.max(bx,p.slot==='CM'?(high?63:58):(high?73:67));}if(poss&&p.role==='WF'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE'))bx=Math.max(bx,zone==='BOX'||phase==='CHANCE'?78:74);if(poss&&p.role==='ST'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE'))bx=Math.max(bx,zone==='BOX'||phase==='CHANCE'?84:80);const width=clamp(Number(s.width||50)/50,.72,1.30);let y=34+(SLOT_Y[p.slot]-34)*width;if(p.role==='ST'&&poss)bx+=4;if(p.role==='FB'&&poss)bx+=Math.max(0,Number(s.transitionDebt||0)-.25)*5;return{x:clamp(bx,4,101),y:clamp(y,4,64)};}
function ballXY(ctx){
 const pr=clamp(Number(ctx.ball.progress)||0.5,0.02,0.99),zone=ctx.zone||'MIDFIELD',phase=ctx.phase||'BUILD_UP';let x;
 if(zone==='OWN_THIRD')x=clamp(12+pr*22,12,34);
 else if(zone==='MIDFIELD')x=clamp(30+pr*35,32,62);
 else if(zone==='FINAL_THIRD')x=clamp(60+(pr-0.60)*62,64,84.5);
 else{const wide=ctx.ball.lane==='LEFT'||ctx.ball.lane==='RIGHT';x=clamp(78+(pr-0.78)*(wide?55:42),80,wide?94.2:91.8);}
 if(phase==='CHANCE'&&zone!=='BOX')x=Math.max(x,76);
 const y=ctx.ball.lane==='LEFT'?18:ctx.ball.lane==='RIGHT'?50:34;return localToWorld(ctx.possession,x,y);
}
function safeHeroAttackPosition(m,hp,bxy){
 const team=hp.team,attackDir=team==='HOME'?1:-1,opp=m.players.filter(p=>p.team!==team&&p.role!=='GK').map(p=>p.x).sort((a,b)=>a-b);
 const secondLast=team==='HOME'?(opp.at(-2)??96):(opp[1]??9),ballRef=bxy.x;
 const line=team==='HOME'?Math.max(secondLast,ballRef):Math.min(secondLast,ballRef);
 let x=line-attackDir*0.65;
 const targetY=34+(bxy.y-34)*.35,gk=m.players.find(p=>p.team!==team&&p.role==='GK');
 if(gk&&Math.hypot(x-gk.x,targetY-gk.y)<7.0)x=gk.x-attackDir*7.0;
 return clamp(x,5,96.2);
}
function runtime(runtimeDir){if(GLOBAL_E&&GLOBAL_P)return{E:GLOBAL_E,P:GLOBAL_P};if(typeof require==='function'&&runtimeDir){const path=require('path');return{E:require(path.join(runtimeDir,'continuous_match_core.js')),P:require(path.join(runtimeDir,'protagonist_match_controller.js'))};}throw new Error('V0.6 runtime unavailable');}
function seedMatch(boundary,opts={}){const {E,P}=runtime(opts.runtimeDir),hero=boundary.heroPlayerId,state=P.create(opts.seed||`STEP67-${boundary.sceneId}`,{heroPlayerId:hero,mode:'FULL_SKIP',replaySeconds:10,appearanceStatus:opts.appearanceStatus||'STARTER',managerProfiles:opts.managerProfiles||{HOME:'BALANCED',AWAY:'BALANCED'}}),m=state.m,ctx=boundary.stateSnapshot,bxy=ballXY(ctx);m.time=Number(ctx.second);m.score={...ctx.score};m.possession=ctx.possession;m.phase=ctx.phase==='TRANSITION'?'TRANSITION':'OPEN_PLAY';m.restart=null;m.completed=false;m.nextShape=m.time;m.transitionUntil=ctx.phase==='TRANSITION'?m.time+2.2:0;m.events=[];m.stats.currentPossessionTeam=ctx.possession;m.stats.currentPossessionStartedAt=m.time;m.protagonistExplicitActionRequired=opts.explicitHeroChoiceRequired===true;
 for(const p of m.players){const l=localBase(p,ctx),w=localToWorld(p.team,l.x,l.y);p.x=w.x;p.y=w.y;p.vx=p.vy=0;p.tx=p.x;p.ty=p.y;p.hasBall=false;p.action='HYBRID_ENTRY_SHAPE';p.tacticalTask='HYBRID_ENTRY_SHAPE';p.nextThink=m.time+.18+(Math.abs((p.id.charCodeAt(0)||1)*17+(p.slot?.length||1)*13)%24)/100;p.lockTargetUntil=0;p.markTargetId=null;p.runUntil=0;p.sprint=false;}
 let owner=m.players.find(p=>p.id===ctx.ball.ownerId);if(!owner||owner.team!==ctx.possession)owner=m.players.find(p=>p.team===ctx.possession&&p.role==='CM')||m.players.find(p=>p.team===ctx.possession&&p.role!=='GK');owner.x=bxy.x;owner.y=bxy.y;owner.tx=owner.x;owner.ty=owner.y;owner.hasBall=true;owner.controlledSince=m.time;owner.nextThink=m.time+.35;const hp=m.players.find(p=>p.id===hero);if(hp&&hp.id!==owner.id){const ht=hp.team,dir=ht==='HOME'?1:-1;if(boundary.reason==='ATTACKING_INVOLVEMENT'){hp.x=hp.role==='ST'?safeHeroAttackPosition(m,hp,bxy):clamp(bxy.x+dir*5.5,5,96);hp.y=clamp(34+(bxy.y-34)*.35,8,60);hp.tx=hp.x;hp.ty=hp.y;}else if(boundary.reason==='MIDFIELD_INVOLVEMENT'){hp.x=clamp(bxy.x-dir*4.5,6,99);hp.y=clamp(bxy.y+(hp.slot==='LCM'?-5:hp.slot==='RCM'?5:3),8,60);hp.tx=hp.x;hp.ty=hp.y;}else if(boundary.reason==='DEFENSIVE_TRANSITION'){const goalSide=ht==='HOME'?-1:1;hp.x=clamp(bxy.x+goalSide*6.0,5,100);hp.y=clamp(bxy.y+(hp.y>=bxy.y?3:-3),7,61);hp.tx=bxy.x;hp.ty=bxy.y;hp.action='RECOVER_GOAL_SIDE';hp.tacticalTask='RECOVER_GOAL_SIDE';}}m.ball={...m.ball,mode:'CONTROLLED',x:owner.x,y:owner.y,z:0,vx:0,vy:0,vz:0,ownerId:owner.id,intendedReceiverId:null,kind:'CONTROL',lastTouchTeam:owner.team,lastTouchPlayer:owner.id,age:0};m.ballOwner=owner.id;m.lastTouchTeam=owner.team;m.lastTouchPlayer=owner.id;m.playersById=Object.fromEntries(m.players.map(p=>[p.id,p]));if(boundary.setPiece){const br=E.choiceActionBridge(),sp=boundary.setPiece,team=sp.team||ctx.possession;let rx=bxy.x,ry=bxy.y;if(sp.kind==='CORNER'){rx=team==='HOME'?103.8:1.2;ry=sp.lane==='LEFT'?1.2:66.8;}br.startDeadRestart(m,sp.kind,team,rx,ry);}state.history=[];state.pending=null;state.resultTracker=null;state.currentScene=null;state.scenes=[];state.pauses=[];state.lastPauseAt=-999;state.lastPauseControlledSince=-999;state.forceNextChoice=false;return{E,P,state,entrySnapshot:E.snapshot(m)};}
function tryHeroOwnerCheckpoint(P,state){const q=P.inspect(state);if(!q||q.frame?.kind!=='ON_BALL'||!q.options?.length)return false;state.mode='PLAYER_ALL';P.maybeCheckpoint(state);if(state.pending)return true;state.mode='FULL_SKIP';return false;}
function roleRelevant(boundary,q){if(!q||!q.options?.length)return false;const kind=q.frame?.kind,role=boundary.heroRole||'CM';if(role==='ST')return kind==='ON_BALL'&&q.importance>=.16;if(role==='CB')return(kind==='DEFENDING'&&q.importance>=.18)||(kind==='ON_BALL'&&boundary.reason==='BUILDUP_INVOLVEMENT'&&q.importance>=.12);if(role==='CM')return(kind==='ON_BALL'&&q.importance>=.14)||(kind==='DEFENDING'&&boundary.reason==='DEFENSIVE_TRANSITION'&&q.importance>=.22);if(role==='GK')return(kind==='ON_BALL'&&q.frame?.role==='GK')||(kind==='DEFENDING'&&q.frame?.role==='GK'&&(q.frame?.threatShot?.inBox||q.frame?.distance<=11.5));return kind==='ON_BALL';}
function runToChoice(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,dt=.10,minPre=clamp(Number(opts.minPreSeconds)||5,5,7),maxSearch=clamp(Number(opts.maxSearchSeconds)||35,minPre,60),frames=[deep(env.entrySnapshot)],start=state.m.time;
 if(tryHeroOwnerCheckpoint(P,state))return{...env,frames,pending:deep(state.pending),scene:state.currentScene?deep(state.currentScene):null,searchSeconds:0,preSpan:0,hadChoice:true,futureOutcomePrecomputed:false};
 while(!state.m.completed&&!state.pending&&state.m.time<start+minPre-.001){P.step(state,dt);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;}
 while(!state.m.completed&&!state.pending&&state.m.time<start+maxSearch-.001){if(tryHeroOwnerCheckpoint(P,state))break;const q=P.inspect(state);if(roleRelevant(boundary,q)){state.mode='PLAYER_ALL';P.maybeCheckpoint(state);if(state.pending)break;state.mode='FULL_SKIP';}P.step(state,dt);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;}
 const pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null,preSpan=pending&&scene?.preFrames?.length?scene.preFrames.at(-1).time-scene.preFrames[0].time:Math.min(10,frames.at(-1).time-frames[0].time);return{...env,frames,pending,scene,searchSeconds:Number((state.m.time-start).toFixed(3)),preSpan:Number(preSpan.toFixed(3)),hadChoice:!!pending,futureOutcomePrecomputed:false};}
function applyChoiceAndAdvance(opened,choiceId,targetId=null,opts={}){const {E,P,state}=opened;if(!state.pending)throw new Error('NO_PENDING_CHOICE');const pendingBefore=deep(state.pending),same=state.pending.options.filter(o=>o.id===choiceId),chosen=targetId!=null?same.find(o=>o.targetId===targetId):(same.length===1?same[0]:same.find(o=>o.targetId==null));if(!chosen)throw new Error(targetId!=null?'CHOICE_TARGET_NOT_AVAILABLE':'CHOICE_NOT_AVAILABLE');const activeSceneId=state.currentScene?.sceneId,activeEpisodeId=state.currentScene?.episodeId||pendingBefore.episodeId||activeSceneId,applied=P.applyChoice(state,chosen.id,chosen.targetId||null,{source:'TEST_HARNESS'});if(!applied.ok)throw new Error(applied.reason||'CHOICE_APPLY_FAILED');if(applied.futureOutcomePrecomputed===true)throw new Error('CHOICE_PRECOMPUTED_OUTCOME_FORBIDDEN');const choiceLog=(state.m.userChoiceLog||[]).at(-1);if(choiceLog&&choiceLog.futureOutcomePrecomputed===true)throw new Error('CHOICE_LOG_PRECOMPUTED_OUTCOME_FORBIDDEN');const postFrames=[],start=state.m.time,maxPost=Number(opts.maxPostSeconds)||12;let guard=0;while(!state.m.completed&&guard++<4000&&state.m.time<start+maxPost){P.step(state,.10);postFrames.push(deep(E.snapshot(state.m)));if(typeof opts.debugStepHook==='function')opts.debugStepHook({state,E,P,postFrames});if(!state.resultTracker)break;}if(!state.resultTracker&&!state.pending&&!state.m.completed){P.maybeCheckpoint(state);let chainGuard=0;const chainStart=state.m.time;while(!state.pending&&!state.m.completed&&state.forceNextChoice&&state.m.ball?.mode==='CONTROLLED'&&state.m.ball?.ownerId===state.heroPlayerId&&state.m.time<chainStart+2.4&&chainGuard++<40){P.step(state,.10);postFrames.push(deep(E.snapshot(state.m)));P.maybeCheckpoint(state);}if(state.forceNextChoice&&state.m.ball?.mode==='CONTROLLED'&&state.m.ball?.ownerId===state.heroPlayerId&&!state.pending)throw new Error('PROTAGONIST_REPOSSESSION_CHECKPOINT_MISSING');}const scene=P.sceneById(state,activeSceneId),result=scene?.result||state.lastResult||null,nextPending=state.pending?deep(state.pending):null,continuation=!!nextPending&&(nextPending.episodeId===activeEpisodeId||nextPending.chained),actualEvents=(scene?.postEvents||[]).map(deep);return{state,snapshot:E.snapshot(state.m),sceneId:activeSceneId,episodeId:activeEpisodeId,hadChoice:true,selectedChoice:deep(chosen),applyReceipt:deep(applied),result:deep(result),actualEvents,postFrames,nextPending,continuation,futureOutcomePrecomputed:false};}
function runSetPieceWindow(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,frames=[deep(E.snapshot(state.m))],start=state.m.time,duration=clamp(Number(opts.durationSeconds)||8,5,12);state.mode='FULL_SKIP';let guard=0;
 while(!state.m.completed&&!state.pending&&state.m.time<start+duration-.001&&guard++<2000){
  if(tryHeroOwnerCheckpoint(P,state))break;P.step(state,.10);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;if(!state.m.restart&&state.m.time>start+5.0&&state.m.ball.mode==='CONTROLLED')break;
 }
 const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep),pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null;if(!pending){const bad=events.find(e=>e.actorId===state.heroPlayerId&&['SHOT','HEADER_SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_SETPIECE_ACTION_FORBIDDEN:${bad.type}:${state.heroPlayerId}`);}return{...env,frames,snapshot,actualEvents:events,pending,scene,hadChoice:!!pending,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function runNonHeroShotWindow(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,frames=[deep(E.snapshot(state.m))],start=state.m.time,duration=clamp(Number(opts.durationSeconds)||8,5,10),hero=state.heroPlayerId,shotter=boundary.shot?.shooterId||boundary.stateSnapshot?.ball?.ownerId;state.mode='FULL_SKIP';const sp=state.m.playersById?.[shotter]||state.m.players.find(p=>p.id===shotter);if(sp){sp.nextThink=state.m.time+.02;sp.controlledSince=Math.min(Number(sp.controlledSince||state.m.time),state.m.time-.6);}let guard=0,shotSeen=false,resolved=false;while(!state.m.completed&&!state.pending&&state.m.time<start+duration-.001&&guard++<2200){if(tryHeroOwnerCheckpoint(P,state))break;P.step(state,.10);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;const ev=(state.m.events||[]).filter(e=>e.t>=start-.001);shotSeen=shotSeen||ev.some(e=>['SHOT','HEADER_SHOT'].includes(e.type));resolved=ev.some(e=>['GOAL','SAVE','CHIP_SAVE','SHOT_MISSED','BLOCK','CORNER','GOAL_KICK'].includes(e.type));if(shotSeen&&resolved&&state.m.time>start+1.0)break;}const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep),pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null;if(!pending){const bad=events.find(e=>e.actorId===hero&&['SHOT','HEADER_SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_NON_HERO_SHOT_ACTION_FORBIDDEN:${bad.type}:${hero}`);}return{...env,frames,snapshot,actualEvents:events,pending,scene,hadChoice:!!pending,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function runFinalWindow(boundary,opts={}){const env=seedMatch(boundary,opts),{E,P,state}=env,frames=[deep(env.entrySnapshot)],start=state.m.time,target=Number(opts.targetSecond)||5400;state.mode='FULL_SKIP';let guard=0;while(!state.m.completed&&state.m.time<target+8.2&&guard++<2200){P.step(state,.10);frames.push(deep(E.snapshot(state.m)));}const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep);return{...env,frames,snapshot,actualEvents:events,hadChoice:false,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function finalizeEpisode(opened,steps){const {E,P,state}=opened,first=steps[0],episodeId=first?.episodeId||state.currentScene?.episodeId||null,episodeFrames=episodeId?P.episodeReplay(state,episodeId):[],debug=episodeId?P.episodeDebug(state,episodeId):null,actualEvents=(state.m.events||[]).filter(e=>e.type!=='USER_CHOICE').map(deep),results=steps.map(x=>x.result).filter(Boolean);return{state,snapshot:E.snapshot(state.m),hadChoice:steps.length>0,choiceSteps:steps.map(deep),selectedChoice:steps.at(-1)?.selectedChoice||null,result:results.at(-1)||null,results:deep(results),actualEvents:deep(actualEvents),postFrames:steps.flatMap(x=>x.postFrames||[]).map(deep),episodeFrames:deep(episodeFrames),debug:deep(debug),nextPending:state.pending?deep(state.pending):null,futureOutcomePrecomputed:false};}
function autoResolveEpisode(opened,picker,opts={}){const steps=[];let guard=0;while(opened.state.pending&&guard++<(opts.maxChoices||5)){const p=deep(opened.state.pending),c=picker(p,guard);if(!c)throw new Error('PICKER_RETURNED_NO_CHOICE');const r=applyChoiceAndAdvance(opened,c.id,c.targetId||null,opts);steps.push(r);if(!r.continuation)break;}return finalizeEpisode(opened,steps);}
function finishWithoutChoice(opened){const hero=opened.state?.heroPlayerId,events=(opened.state.m.events||[]).map(deep),bad=events.find(e=>e.actorId===hero&&['SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_ACTION_FORBIDDEN:${bad.type}:${hero}`);return{state:opened.state,snapshot:opened.E.snapshot(opened.state.m),hadChoice:false,selectedChoice:null,result:null,actualEvents:events,postFrames:[],episodeFrames:opened.frames.map(deep),debug:{schemaVersion:'FLR_HIGH_RES_NO_CHOICE_0.1',frames:opened.frames.map(deep)},futureOutcomePrecomputed:false};}
function choiceAudit(opened,resolved=null){const issues=[];if(opened.preSpan<4.8)issues.push('PRE_ACTION_TOO_SHORT');if(opened.pending&&opened.pending.futureOutcomePrecomputed!==false)issues.push('PENDING_PRECOMPUTED');if(resolved){if(resolved.futureOutcomePrecomputed!==false)issues.push('RESOLUTION_PRECOMPUTED_FLAG');if(resolved.applyReceipt?.futureOutcomePrecomputed===true)issues.push('APPLY_PRECOMPUTED');const code=resolved.result?.code;if(code==='BLOCKED'||code==='CORNER'){const ev=(resolved.actualEvents||[]).find(e=>e.type==='BLOCK');if(!ev)issues.push('BLOCK_RESULT_WITHOUT_BLOCK_EVENT');}if(code==='GOAL'&&!(resolved.actualEvents||[]).some(e=>e.type==='GOAL'))issues.push('GOAL_WITHOUT_GOAL_EVENT');if(code==='SAVED'&&!(resolved.actualEvents||[]).some(e=>['SAVE','CHIP_SAVE'].includes(e.type)))issues.push('SAVE_WITHOUT_SAVE_EVENT');}
 return{ok:!issues.length,issues};}
return{seedMatch,runToChoice,runSetPieceWindow,runNonHeroShotWindow,runFinalWindow,applyChoiceAndAdvance,autoResolveEpisode,finalizeEpisode,finishWithoutChoice,choiceAudit};
});