(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FLRPG_LIVE_HYBRID_SESSION_V02=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hashSeed(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function nextRandom(session){let x=session.rngState>>>0;x^=(x<<13);x^=(x>>>17);x^=(x<<5);session.rngState=x>>>0;return (session.rngState>>>0)/4294967296;}
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v));
const SLOT_ROLE={GK:'GK',LB:'FB',LCB:'CB',RCB:'CB',RB:'FB',LCM:'CM',CM:'CM',RCM:'CM',LW:'WF',ST:'ST',RW:'WF'};
const SLOTS=['GK','LB','LCB','RCB','RB','LCM','CM','RCM','LW','ST','RW'];
const SLOT_Y={GK:34,LB:9,LCB:25,RCB:43,RB:59,LCM:20,CM:34,RCM:48,LW:8,ST:34,RW:60};
function slotOf(id){return String(id||'').split('-').slice(1).join('-');}
function roleOf(id){return SLOT_ROLE[slotOf(id)]||'CM';}
function other(team){return team==='HOME'?'AWAY':'HOME';}
function defaultTeam(id,name,attackDirection){return{id,name,attackDirection,shape:{formation:'4-3-3',lineHeight:50,width:50,compactness:62,midfieldOccupancy:3,backLineOccupancy:4,frontOccupancy:3},intent:{tempo:50,press:50,directness:45,fullbackRisk:42},fatigue:0,score:0};}
function lanePool(team,lane,phase){const p=team==='HOME'?'H':'A';if(phase==='BUILD_UP')return[`${p}-LCB`,`${p}-RCB`,`${p}-LB`,`${p}-RB`,`${p}-LCM`,`${p}-RCM`];if(lane==='LEFT')return[`${p}-LW`,`${p}-LB`,`${p}-LCM`,`${p}-ST`];if(lane==='RIGHT')return[`${p}-RW`,`${p}-RB`,`${p}-RCM`,`${p}-ST`];return[`${p}-CM`,`${p}-LCM`,`${p}-RCM`,`${p}-ST`];}
function pick(session,arr){return arr[Math.floor(nextRandom(session)*arr.length)];}
function pickActor(session,team,state,kind){const p=team==='HOME'?'H':'A';if(kind==='SHOT'){const pool=state.ball.lane==='LEFT'?[`${p}-LW`,`${p}-ST`,`${p}-LCM`]:state.ball.lane==='RIGHT'?[`${p}-RW`,`${p}-ST`,`${p}-RCM`]:[`${p}-ST`,`${p}-CM`,`${p}-LCM`,`${p}-RCM`];return pick(session,pool);}return pick(session,lanePool(team,state.ball.lane,state.phase));}
function pickTarget(session,team,state,actor){const p=team==='HOME'?'H':'A';let pool=state.ball.lane==='LEFT'?[`${p}-LW`,`${p}-ST`,`${p}-LCM`,`${p}-LB`]:state.ball.lane==='RIGHT'?[`${p}-RW`,`${p}-ST`,`${p}-RCM`,`${p}-RB`]:[`${p}-ST`,`${p}-CM`,`${p}-LCM`,`${p}-RCM`];pool=pool.filter(x=>x!==actor);return pick(session,pool)||`${p}-ST`;}
function phaseFromProgress(p){if(p<0.32)return'BUILD_UP';if(p<0.62)return'PROGRESSION';if(p<0.82)return'FINAL_THIRD';return'CHANCE';}
function zoneFromProgress(p){if(p<0.28)return'OWN_THIRD';if(p<0.62)return'MIDFIELD';if(p<0.88)return'FINAL_THIRD';return'BOX';}
function toWorld(team,x,y){return team==='HOME'?{x,y}:{x:105-x,y:68-y};}
function spatialBall(s){const y=s.ball.lane==='LEFT'?18:s.ball.lane==='RIGHT'?50:34;return toWorld(s.possession,clamp(Number(s.ball.progress||.5)*105,3,102),y);}
function initialSpatial(){const players=[];for(const team of['HOME','AWAY'])for(const slot of SLOTS){const role=SLOT_ROLE[slot],lx={GK:6,FB:23,CB:21,CM:43,WF:61,ST:68}[role],w=toWorld(team,lx,SLOT_Y[slot]);players.push({id:`${team==='HOME'?'H':'A'}-${slot}`,x:w.x,y:w.y,vx:0,vy:0,tx:w.x,ty:w.y,action:'MATCH_START_SHAPE',tacticalTask:'MATCH_START_SHAPE',markTargetId:null,responsibilityReason:'MATCH_START'});}return{schemaVersion:'HYBRID_CURRENT_SPATIAL_1.0',time:0,boundaryId:null,players,ball:{mode:'CONTROLLED',x:50.4,y:34,vx:0,vy:0,ownerId:'H-CM'},futureOutcomePrecomputed:false};}
function advanceSpatial(session,e){const s=session.state,sp=s.spatial,dt=Math.max(.1,s.second-Number(sp.time||0)),bp=spatialBall(s),byId=Object.fromEntries(sp.players.map(p=>[p.id,p])),owner=byId[s.ball.ownerId],attackLocal=clamp(Number(s.ball.progress||.5)*105,3,102);for(const p of sp.players){const team=p.id.startsWith('H-')?'HOME':'AWAY',slot=slotOf(p.id),role=roleOf(p.id),inPoss=team===s.possession,lane=SLOT_Y[slot],shape=s.structure[team],ballLocalY=team==='HOME'?bp.y:68-bp.y;let lx={GK:6,FB:inPoss?29:24,CB:inPoss?25:22,CM:inPoss?49:42,WF:inPoss?68:55,ST:inPoss?74:57}[role]+clamp((attackLocal-52)*.16,-8,10),ly=lane,task=inPoss?'CURRENT_SUPPORT':'CURRENT_DEFENSIVE_SHAPE',reason='ORDINARY_MATCH_PROGRESSION',mark=null;if(role==='GK'){lx=clamp(6+attackLocal*.025,5,9);ly=34+(ballLocalY-34)*.08;task='CURRENT_GK_COVER';}else if(p.id===s.ball.ownerId){const q=team===s.possession?bp:toWorld(team,attackLocal,ballLocalY);lx=team==='HOME'?q.x:105-q.x;ly=team==='HOME'?q.y:68-q.y;task='CURRENT_BALL_OWNER';reason=e?.id||'CURRENT_POSSESSION';}else if(role==='ST'&&inPoss){lx=Math.max(lx,clamp(attackLocal+5,58,91));ly=34+(ballLocalY-34)*.10;task='CURRENT_PIN_CENTRE_BACKS';reason='CENTRAL_FORWARD_THREAT';}else if(role==='FB'){const same=(lane<34)===(ballLocalY<34),overlap=inPoss&&same&&attackLocal>57;if(overlap){lx=Math.max(lx,Math.min(attackLocal-4,78));task='CURRENT_SUPPORTED_OVERLAP';reason='BALL_SIDE_OVERLAP';}else{lx=Math.min(lx,inPoss?47:36);task='CURRENT_REST_DEFENCE';reason='FULLBACK_REST_BALANCE';}}else if(role==='CM'){ly=lane+(ballLocalY-lane)*(inPoss?.14:.08);}const oppSt=byId[`${team==='HOME'?'A':'H'}-ST`];if(role==='CB'&&!inPoss&&oppSt){const mate=byId[`${team==='HOME'?'H':'A'}-${slot==='LCB'?'RCB':'LCB'}`],d=Math.hypot(p.x-oppSt.x,p.y-oppSt.y),md=mate?Math.hypot(mate.x-oppSt.x,mate.y-oppSt.y):999;if(d<=md){const ol=team==='HOME'?{x:oppSt.x-2,y:oppSt.y}:{x:107-oppSt.x,y:68-oppSt.y};lx=clamp(ol.x,14,88);ly=clamp(ol.y,18,50);task='CURRENT_MARK_CENTRAL_THREAT';reason='DANGEROUS_ST_GOAL_SIDE';mark=oppSt.id;}else{task='CURRENT_CENTRAL_COVER';reason='CENTRAL_THREAT_HANDOFF_COVER';mark=oppSt.id;}}lx=clamp(lx+(Number(shape.lineHeight||50)-50)*.06,4,101);ly=clamp(34+(ly-34)*clamp(Number(shape.width||50)/50,.72,1.3),4,64);const w=toWorld(team,lx,ly),max=role==='GK'?10:role==='CB'?18:role==='FB'?25:role==='ST'?27:23,dx=w.x-p.x,dy=w.y-p.y,d=Math.hypot(dx,dy),travel=Math.min(d,max*Math.min(dt,4)/4),nx=d?p.x+dx*travel/d:p.x,ny=d?p.y+dy*travel/d:p.y;p.vx=(nx-p.x)/dt;p.vy=(ny-p.y)/dt;p.x=nx;p.y=ny;p.tx=w.x;p.ty=w.y;p.action=task;p.tacticalTask=task;p.markTargetId=mark;p.responsibilityReason=reason;}if(owner){owner.x=bp.x;owner.y=bp.y;owner.tx=clamp(bp.x+(owner.id.startsWith('H-')?2:-2),3,102);owner.ty=bp.y;owner.vx=(owner.tx-owner.x)/1.2;owner.vy=0;}sp.time=s.second;sp.ball={mode:'CONTROLLED',x:bp.x,y:bp.y,vx:owner?.vx||0,vy:owner?.vy||0,ownerId:s.ball.ownerId||null};}
function createState(opts={}){const home=opts.home||defaultTeam('HOME','블루팀',1),away=opts.away||defaultTeam('AWAY','레드팀',-1);return{schemaVersion:'HYBRID_LIVE_STATE_0.4',second:0,minute:0,score:{HOME:0,AWAY:0},possession:'HOME',zone:'MIDFIELD',phase:'BUILD_UP',danger:.12,ball:{team:'HOME',lane:'CENTER',progress:.48,ownerId:'H-CM'},spatial:initialSpatial(),teams:{HOME:deep(home),AWAY:deep(away)},structure:{HOME:{midfieldOccupancy:3,backLineOccupancy:4,width:home.shape.width,lineHeight:home.shape.lineHeight,transitionDebt:0},AWAY:{midfieldOccupancy:3,backLineOccupancy:4,width:away.shape.width,lineHeight:away.shape.lineHeight,transitionDebt:0}},chain:[],resolvedEvents:[],sceneCandidates:[],counters:{actions:0,turnovers:0,shots:0,goals:0,heroWindows:0,highResChoices:0},lastHighRes:null};}
function createSession(opts={}){const state=createState(opts);return{schemaVersion:'HYBRID_LIVE_SESSION_0.3',status:'RUNNING',opts:deep(opts),durationSeconds:opts.durationSeconds||5400,stepMin:opts.stepMin||4,stepMax:opts.stepMax||12,rngState:hashSeed(opts.seed||'FLR-LIVE-HYBRID-02')||0x9e3779b9,state,initialSpatial:deep(state.spatial),boundary:null,handledBoundaryIds:[],resumeCount:0,lastHeroWindowAt:-999,highResHistory:[],finalWindowDone:false,lastSetPieceAt:-999,fineStepUntil:-999,_promotionHistory:[]};}
// Read-only export for the setup canvas.  It is captured with the one live
// session and never advances its clock, RNG, or current causal state.
function initialSpatialSnapshot(session){if(!session?.initialSpatial)throw new Error('HYBRID_INITIAL_SPATIAL_MISSING');return deep(session.initialSpatial);}
function structureIntegrity(state){const issues=[];for(const team of['HOME','AWAY']){const s=state.structure[team];if(s.midfieldOccupancy<1&&s.transitionDebt<.55)issues.push(`${team}:MIDFIELD_EMPTY_WITHOUT_CAUSE`);if(s.backLineOccupancy<2&&s.transitionDebt<.65)issues.push(`${team}:BACKLINE_EMPTY_WITHOUT_CAUSE`);if(s.width<28||s.width>78)issues.push(`${team}:WIDTH_OUT_OF_RANGE`);if(s.lineHeight<20||s.lineHeight>82)issues.push(`${team}:LINE_OUT_OF_RANGE`);}return{ok:!issues.length,issues};}
function updateStructure(session){const s=session.state;for(const team of['HOME','AWAY']){const ts=s.teams[team],x=s.structure[team],inPoss=s.possession===team,risk=ts.intent.fullbackRisk/100*(inPoss?1:.35),trans=s.phase==='TRANSITION'?.18:0;x.transitionDebt=clamp(x.transitionDebt*.72+trans+risk*.06,0,1);x.midfieldOccupancy=clamp(Math.round(ts.shape.midfieldOccupancy-(x.transitionDebt>.62?1:0)),1,4);x.backLineOccupancy=clamp(Math.round(ts.shape.backLineOccupancy-(risk>.55?1:0)-(x.transitionDebt>.75?1:0)),2,5);x.width=clamp(ts.shape.width+(inPoss?6:-3)+(nextRandom(session)-.5)*3,30,75);x.lineHeight=clamp(ts.shape.lineHeight+(inPoss?5:-5)+(s.phase==='TRANSITION'?(nextRandom(session)-.5)*8:0),22,80);}}
function addEvent(session,kind,team,detail={}){const s=session.state,e={id:`E${String(s.resolvedEvents.length+1).padStart(5,'0')}`,t:s.second,minute:Number((s.second/60).toFixed(2)),kind,team,zone:s.zone,phase:s.phase,detail:deep(detail),context:{possession:s.possession,danger:Number(s.danger.toFixed(3)),ball:{...s.ball},structure:deep(s.structure)}};s.resolvedEvents.push(e);s.chain.push(e);if(s.chain.length>12)s.chain.shift();advanceSpatial(session,e);return e;}
function causalContext(state,max=8){return state.chain.slice(-max).map(e=>deep(e));}
function heroId(session){const t=session.opts.heroTeam||'HOME',r=session.opts.heroRole||'CM',p=t==='HOME'?'H':'A';return session.opts.heroPlayerId||`${p}-${r==='ST'?'ST':r==='CB'?'LCB':r==='GK'?'GK':'CM'}`;}
function boundarySnapshot(s,id){const spatial=deep(s.spatial);spatial.boundaryId=id;spatial.time=s.second;return{second:s.second,score:{...s.score},possession:s.possession,zone:s.zone,phase:s.phase,danger:s.danger,ball:{...s.ball},structure:deep(s.structure),spatial};}
function makeWindow(session,sourceEvent,reason){const s=session.state,id=`HW${String(s.counters.heroWindows+1).padStart(4,'0')}`;s.counters.heroWindows++;session.lastHeroWindowAt=s.second;const b={id,type:'PROTAGONIST_2D_WINDOW',sceneId:id,atSecond:s.second,sourceEventId:sourceEvent.id,reason,heroPlayerId:heroId(session),heroRole:session.opts.heroRole||'CM',heroTeam:session.opts.heroTeam||'HOME',stateSnapshot:boundarySnapshot(s,id),preContext:causalContext(s,8),futureOutcomePrecomputed:false,choicePrecomputed:false};s.sceneCandidates.push(deep(b));return b;}
function capturePromotionState(session){const s=session.state;return{second:s.second,minute:s.minute,score:deep(s.score),possession:s.possession,zone:s.zone,phase:s.phase,danger:s.danger,ball:deep(s.ball),spatial:deep(s.spatial),structure:deep(s.structure),chain:deep(s.chain),counters:deep(s.counters),resolvedEventLen:s.resolvedEvents.length,sceneCandidateLen:s.sceneCandidates.length,teamScores:{HOME:s.teams.HOME.score,AWAY:s.teams.AWAY.score},lastHeroWindowAt:session.lastHeroWindowAt,lastSetPieceAt:session.lastSetPieceAt};}
function restorePromotionState(session,cap){const s=session.state;s.second=cap.second;s.minute=cap.minute;s.score=deep(cap.score);s.possession=cap.possession;s.zone=cap.zone;s.phase=cap.phase;s.danger=cap.danger;s.ball=deep(cap.ball);s.spatial=deep(cap.spatial);s.structure=deep(cap.structure);s.chain=deep(cap.chain);s.counters=deep(cap.counters);s.resolvedEvents.splice(cap.resolvedEventLen);s.sceneCandidates.splice(cap.sceneCandidateLen);s.teams.HOME.score=cap.teamScores.HOME;s.teams.AWAY.score=cap.teamScores.AWAY;session.lastHeroWindowAt=cap.lastHeroWindowAt;session.lastSetPieceAt=cap.lastSetPieceAt;}
function promoteFromStepStart(session,pre,sourceEvent,reason){const triggerT=Number(sourceEvent?.t??session.state.second),history=session._promotionHistory||[],eligible=history.filter(x=>x.second<=triggerT-10.5&&x.second>=triggerT-20.0),chosen=eligible.length?eligible.at(-1):(pre||history.at(-1));if(chosen)restorePromotionState(session,chosen);const trigger={id:`PROMOTE-${sourceEvent?.id||'EVENT'}`,kind:sourceEvent?.kind||'ATTACKING_TRIGGER',detail:deep(sourceEvent?.detail||{}),previewOnly:true};return makeWindow(session,trigger,reason);}
function makeSetPieceWindow(session,sourceEvent,kind,team){const s=session.state,id=`SP${String((s.counters.setPieceWindows||0)+1).padStart(4,'0')}`;s.counters.setPieceWindows=(s.counters.setPieceWindows||0)+1;const stateSnapshot=boundarySnapshot(s,id);stateSnapshot.possession=team;stateSnapshot.ball.team=team;return{id,type:'SET_PIECE_2D_WINDOW',sceneId:id,atSecond:s.second,sourceEventId:sourceEvent.id,reason:`SET_PIECE_${kind}`,setPiece:{kind,team,lane:s.ball.lane,progress:s.ball.progress},heroPlayerId:heroId(session),heroRole:session.opts.heroRole||'CM',heroTeam:session.opts.heroTeam||'HOME',stateSnapshot,preContext:causalContext(s,8),futureOutcomePrecomputed:false,choicePrecomputed:false};}
function makeNonHeroShotWindow(session,team,shooter,quality){const s=session.state,id=`NS${String((s.counters.nonHeroShotWindows||0)+1).padStart(4,'0')}`;s.counters.nonHeroShotWindows=(s.counters.nonHeroShotWindows||0)+1;const stateSnapshot=boundarySnapshot(s,id);stateSnapshot.possession=team;stateSnapshot.danger=Math.max(s.danger,quality);stateSnapshot.ball={...stateSnapshot.ball,team,ownerId:shooter};return{id,type:'NON_HERO_SHOT_2D_WINDOW',sceneId:id,atSecond:s.second,sourceEventId:null,reason:'NON_HERO_SHOT',shot:{team,shooterId:shooter,quality,fromZone:s.zone},heroPlayerId:heroId(session),heroRole:session.opts.heroRole||'CM',heroTeam:session.opts.heroTeam||'HOME',stateSnapshot,preContext:causalContext(s,8),futureOutcomePrecomputed:false,choicePrecomputed:false};}
function makeFinalWindow(session){const s=session.state,id='FINAL-WINDOW';return{id,type:'FINAL_2D_WINDOW',sceneId:id,atSecond:s.second,sourceEventId:null,reason:'FINAL_WHISTLE_WINDOW',heroPlayerId:heroId(session),heroRole:session.opts.heroRole||'CM',heroTeam:session.opts.heroTeam||'HOME',stateSnapshot:boundarySnapshot(s,id),preContext:causalContext(s,8),futureOutcomePrecomputed:false,choicePrecomputed:false};}
function maybeHeroWindow(session,e){const s=session.state,ht=session.opts.heroTeam||'HOME',role=session.opts.heroRole||'CM',hid=heroId(session),age=s.second-session.lastHeroWindowAt,actorInvolved=e.detail?.actorId===hid,targetInvolved=e.detail?.targetId===hid,heroInvolved=actorInvolved||targetInvolved,urgentHero=heroInvolved&&s.danger>=.80&&['DANGEROUS_PASS','BOX_ENTRY','TURNOVER_DANGER'].includes(e.kind),roleGap=role==='ST'?105:role==='CM'?72:role==='CB'?80:110,minGap=urgentHero?(role==='ST'?55:42):roleGap;if(age<minGap||session.durationSeconds-s.second<15)return null;let reason=null;
 if(s.possession===ht){
   if(role==='ST'&&['FINAL_THIRD','BOX'].includes(s.zone)&&heroInvolved){const direct=['DANGEROUS_PASS','BOX_ENTRY'].includes(e.kind),actorThreat=actorInvolved&&(direct||(e.kind==='PROGRESS'&&s.zone==='BOX'&&s.danger>=.68)),targetThreat=targetInvolved&&direct&&s.danger>=.50;if(actorThreat||targetThreat)reason='ATTACKING_INVOLVEMENT';}
   else if(role==='CM'&&['PROGRESSION','FINAL_THIRD'].includes(s.phase)&&heroInvolved)reason='MIDFIELD_INVOLVEMENT';
   else if(role==='CB'&&s.phase==='BUILD_UP'&&heroInvolved)reason='BUILDUP_INVOLVEMENT';
 }
 else if(role==='CM'&&e.kind.startsWith('TURNOVER')&&s.danger>=.66&&s.ball.lane==='CENTER')reason='DEFENSIVE_TRANSITION';
 else if(role==='CB'&&e.kind.startsWith('TURNOVER')&&s.danger>=.58&&['FINAL_THIRD','BOX'].includes(s.zone))reason='DEFENSIVE_TRANSITION';
 else if(role==='GK'&&s.possession!==ht&&['FINAL_THIRD','BOX'].includes(s.zone)&&s.danger>=.60&&['PROGRESS','DANGEROUS_PASS','BOX_ENTRY'].includes(e.kind))reason='GK_GOALKEEPING';
 return reason?makeWindow(session,e,reason):null;}
function doAction(session,policy={},prePromotion=null){const s=session.state,team=s.possession,opp=other(team),tempo=s.teams[team].intent.tempo/100,direct=s.teams[team].intent.directness/100,press=s.teams[opp].intent.press/100;s.counters.actions++;
 if(s.second-session.lastSetPieceAt>95&&s.ball.progress>.28&&s.ball.progress<.88&&nextRandom(session)<(.0045+press*.0055)){const fouled=pickActor(session,team,s,'FOUL'),fe=addEvent(session,'FOUL',team,{actorId:fouled,actorRole:roleOf(fouled),fouledByTeam:opp,progress:s.ball.progress,lane:s.ball.lane}),fk=addEvent(session,'FREE_KICK',team,{actorId:fouled,actorRole:roleOf(fouled),fromFoul:fe.id,progress:s.ball.progress,lane:s.ball.lane});session.lastSetPieceAt=s.second;return makeSetPieceWindow(session,fk,'FREE_KICK',team);}
 const baseTurnover=clamp(.075+press*.08+s.danger*.035,.025,.30);if(nextRandom(session)<baseTurnover){s.counters.turnovers++;const prev=s.ball.progress;s.possession=opp;s.ball.team=opp;s.ball.progress=clamp(1-prev+(nextRandom(session)-.5)*.08,.08,.92);s.phase='TRANSITION';s.zone=zoneFromProgress(s.ball.progress);s.danger=clamp(.22+Math.abs(prev-.5)*.55+nextRandom(session)*.18,0,1);const actor=pickActor(session,opp,s,'TURNOVER');s.ball.ownerId=actor;const e=addEvent(session,s.danger>.55?'TURNOVER_DANGER':'TURNOVER',opp,{actorId:actor,actorRole:roleOf(actor),wonFrom:team,progress:s.ball.progress,danger:s.danger});const w=maybeHeroWindow(session,e);if(w)return(w.reason==='ATTACKING_INVOLVEMENT'?promoteFromStepStart(session,prePromotion,e,w.reason):w);return null;}
 if(nextRandom(session)<.14)s.ball.lane=pick(session,['LEFT','CENTER','RIGHT']);let delta=.018+tempo*.025+(nextRandom(session)-.4)*.025,kind='RECYCLE';if(nextRandom(session)<.18+direct*.34){delta+=.08+direct*.08;kind='PROGRESS';}if(nextRandom(session)<.09+direct*.12){delta+=.11;kind='DANGEROUS_PASS';}s.ball.progress=clamp(s.ball.progress+delta,.06,.99);s.zone=zoneFromProgress(s.ball.progress);s.phase=phaseFromProgress(s.ball.progress);s.danger=clamp((s.ball.progress-.5)*1.2+(kind==='DANGEROUS_PASS'?.18:0)+nextRandom(session)*.16,.05,.95);if(s.zone==='FINAL_THIRD'&&kind==='PROGRESS')kind='BOX_ENTRY';const actor=pickActor(session,team,s,kind),target=['PROGRESS','DANGEROUS_PASS','BOX_ENTRY'].includes(kind)?pickTarget(session,team,s,actor):null;s.ball.ownerId=target||actor;const e=addEvent(session,kind,team,{actorId:actor,actorRole:roleOf(actor),targetId:target,targetRole:target?roleOf(target):null,progress:s.ball.progress,lane:s.ball.lane,danger:s.danger});const w=maybeHeroWindow(session,e);if(w)return(w.reason==='ATTACKING_INVOLVEMENT'?promoteFromStepStart(session,prePromotion,e,w.reason):w);
 // A non-hero shot is never resolved in low resolution. V0.6 computes the real outcome; UI only replays it when it becomes a goal.
 if(s.ball.progress>.84&&nextRandom(session)<.04+s.danger*.07){const q=clamp(.2+s.danger*.62+(nextRandom(session)-.5)*.22,.05,.95),priorOwner=s.ball.ownerId,shooter=pickActor(session,team,s,'SHOT');if(shooter===heroId(session)){s.ball.ownerId=priorOwner;const trigger={id:`HERO-FINISH-${String((s.counters.heroFinishingWindows||0)+1).padStart(4,'0')}`,t:s.second,kind:'HERO_FINISHING_WINDOW'};s.counters.heroFinishingWindows=(s.counters.heroFinishingWindows||0)+1;s.danger=Math.max(s.danger,q);return promoteFromStepStart(session,prePromotion,trigger,'ATTACKING_INVOLVEMENT');}s.ball.ownerId=shooter;s.danger=Math.max(s.danger,q);return makeNonHeroShotWindow(session,team,shooter,q);}
 return null;}
function advanceUntilBoundary(session,policy={}){if(session.status==='FINISHED')return{status:'FINISHED',boundary:null,state:session.state};if(session.status==='PAUSED')return{status:'PAUSED',boundary:session.boundary,state:session.state};let n=0,max=policy.maxActions||20000;while(session.state.second<session.durationSeconds&&n++<max){const finalAt=Math.max(0,session.durationSeconds-5);if(!session.finalWindowDone&&session.state.second>=finalAt-.001){session.state.second=finalAt;session.state.minute=session.state.second/60;session.status='PAUSED';session.boundary=makeFinalWindow(session);return{status:'PAUSED',boundary:session.boundary,state:session.state,actionsAdvanced:n};}const fineStep=session.state.second<Number(session.fineStepUntil||-999);const prePromotion=capturePromotionState(session);session._promotionHistory=session._promotionHistory||[];session._promotionHistory.push(prePromotion);if(session._promotionHistory.length>8)session._promotionHistory.shift();let dt=fineStep?Math.floor(2+nextRandom(session)*3):Math.floor(session.stepMin+nextRandom(session)*(session.stepMax-session.stepMin+1));if(!session.finalWindowDone&&session.state.second<finalAt&&session.state.second+dt>finalAt)dt=finalAt-session.state.second;session.state.second=Math.min(session.durationSeconds,session.state.second+dt);session.state.minute=session.state.second/60;updateStructure(session);const integ=structureIntegrity(session.state);if(!integ.ok)addEvent(session,'STRUCTURE_INTEGRITY_FAIL','SYSTEM',{issues:integ.issues});if(!session.finalWindowDone&&session.state.second>=finalAt-.001){session.status='PAUSED';session.boundary=makeFinalWindow(session);return{status:'PAUSED',boundary:session.boundary,state:session.state,actionsAdvanced:n};}const b=doAction(session,policy,prePromotion);if(b){session.status='PAUSED';session.boundary=b;return{status:'PAUSED',boundary:b,state:session.state,actionsAdvanced:n};}}
 if(session.state.second>=session.durationSeconds){session.status='FINISHED';session.boundary={type:'MATCH_END',atSecond:session.state.second};return{status:'FINISHED',boundary:session.boundary,state:session.state,actionsAdvanced:n};}throw new Error('advance safety limit exceeded');}
function localProgress(team,x){return clamp(team==='HOME'?x/105:(105-x)/105,.02,.98);}function localY(team,y){return team==='HOME'?y:68-y;}function laneFor(team,y){const ly=localY(team,y);return ly<25?'LEFT':ly>43?'RIGHT':'CENTER';}
function deriveStructure(snapshot,team){const ps=snapshot.players.filter(p=>p.team===team),dir=team==='HOME'?1:-1,local=p=>({x:team==='HOME'?p.x:105-p.x,y:localY(team,p.y)}),out=ps.filter(p=>p.role!=='GK'),xs=out.map(p=>local(p).x),ys=out.map(p=>local(p).y),backs=out.filter(p=>['CB','FB'].includes(p.role)).map(p=>local(p).x),cms=out.filter(p=>p.role==='CM').map(p=>local(p).x);return{midfieldOccupancy:Math.max(1,cms.filter(x=>x>22&&x<78).length),backLineOccupancy:Math.max(2,backs.filter(x=>x<68).length),width:clamp(Math.max(...ys)-Math.min(...ys),30,75),lineHeight:clamp(backs.reduce((a,b)=>a+b,0)/Math.max(1,backs.length),22,80),transitionDebt:clamp(snapshot.phase==='TRANSITION'?.65:.18,0,1)};}
function highResEventFrame(handback,eventT){const rows=[...(handback.episodeFrames||[]),...(handback.postFrames||[])].filter(f=>f&&Number.isFinite(Number(f.time))&&f.ball&&f.score&&Array.isArray(f.players));if(!rows.length)return handback.snapshot||null;rows.sort((a,b)=>Number(a.time)-Number(b.time));let best=rows[0],bestD=Math.abs(Number(best.time)-eventT);for(const f of rows){const d=Math.abs(Number(f.time)-eventT);if(d<bestD-.0001||(Math.abs(d-bestD)<.0001&&Number(f.time)<=eventT)){best=f;bestD=d;}}return best;}
function highResEventContext(handback,e,fallbackTeam,fallbackState){const f=highResEventFrame(handback,Number(e.t));if(!f)return{zone:fallbackState.zone,phase:fallbackState.phase,context:{possession:fallbackTeam,danger:fallbackState.danger,ball:{...fallbackState.ball},structure:deep(fallbackState.structure)},score:{...fallbackState.score}};const possession=f.possession||e.team||fallbackTeam,progress=localProgress(possession,Number(f.ball.x)||0),ball={team:possession,lane:laneFor(possession,Number(f.ball.y)||34),progress,ownerId:f.ball.ownerId||null},zone=zoneFromProgress(progress),phase=phaseFromProgress(progress),danger=clamp((progress-.5)*1.15+(e.type==='GOAL'?.25:0),.05,.95),structure={HOME:deriveStructure(f,'HOME'),AWAY:deriveStructure(f,'AWAY')};return{zone,phase,context:{possession,danger,ball,structure},score:{...(f.score||fallbackState.score)}};}
function resumeFromHighRes(session,handback){if(session.status!=='PAUSED'||!['PROTAGONIST_2D_WINDOW','SET_PIECE_2D_WINDOW','NON_HERO_SHOT_2D_WINDOW','FINAL_2D_WINDOW'].includes(session.boundary?.type))throw new Error('session not waiting for high-res handback');const boundaryType=session.boundary?.type;const finalWindow=boundaryType==='FINAL_2D_WINDOW';const snap=handback.snapshot,team=snap.possession||session.state.possession,owner=snap.ball.ownerId||null,progress=localProgress(team,snap.ball.x);session.state.second=Number(snap.time);session.state.minute=session.state.second/60;session.state.score={...snap.score};session.state.possession=team;session.state.ball={team,lane:laneFor(team,snap.ball.y),progress,ownerId:owner};session.state.spatial={schemaVersion:'HYBRID_CURRENT_SPATIAL_1.0',time:Number(snap.time),boundaryId:null,players:snap.players.map(p=>({id:p.id,x:p.x,y:p.y,vx:p.vx,vy:p.vy,tx:p.tx,ty:p.ty,action:p.action,tacticalTask:p.tacticalTask,markTargetId:p.markTargetId||null,responsibilityReason:p.responsibilityReason||'HIGH_RES_HANDBACK'})),ball:{mode:snap.ball.mode,x:snap.ball.x,y:snap.ball.y,vx:snap.ball.vx||0,vy:snap.ball.vy||0,ownerId:owner},futureOutcomePrecomputed:false};session.state.zone=zoneFromProgress(progress);session.state.phase=phaseFromProgress(progress);session.state.danger=clamp((progress-.5)*1.15+(handback.result?.code==='GOAL'?.25:0),.05,.95);session.state.structure.HOME=deriveStructure(snap,'HOME');session.state.structure.AWAY=deriveStructure(snap,'AWAY');session.state.teams.HOME.score=snap.score.HOME;session.state.teams.AWAY.score=snap.score.AWAY;
 const mapped=(handback.actualEvents||[]).map((e,i)=>{const causal=highResEventContext(handback,e,team,session.state);return{id:`HR-${session.highResHistory.length+1}-${i+1}`,t:Number(e.t),minute:Number((e.t/60).toFixed(2)),kind:`HIGH_RES_${e.type}`,team:e.team||null,zone:causal.zone,phase:causal.phase,detail:{text:e.text||'',sourceType:e.type,actorId:e.actorId||null,targetId:e.targetId||null,score:causal.score,causalFrame:true},context:causal.context};});for(const e of mapped){session.state.resolvedEvents.push(e);session.state.chain.push(e);if(session.state.chain.length>12)session.state.chain.shift();}if(handback.hadChoice)session.state.counters.highResChoices++;session.state.lastHighRes={sceneId:session.boundary.sceneId,hadChoice:!!handback.hadChoice,result:deep(handback.result||null),atSecond:session.state.second};session.highResHistory.push(deep({boundary:session.boundary,handback:{hadChoice:!!handback.hadChoice,result:handback.result||null,atSecond:session.state.second}}));session.handledBoundaryIds.push(session.boundary.id);if(finalWindow)session.finalWindowDone=true;if(!finalWindow){const volatileLead=boundaryType==='SET_PIECE_2D_WINDOW'?18:boundaryType==='NON_HERO_SHOT_2D_WINDOW'?8:12;session.fineStepUntil=Math.max(Number(session.fineStepUntil||-999),session.state.second+volatileLead);}session._promotionHistory=[];session.boundary=null;session.status='RUNNING';session.resumeCount++;return session;}
function snapshot(session){const out=deep(session);delete out._promotionHistory;return out;}function futureEventCount(session){return session.status==='PAUSED'?session.state.resolvedEvents.filter(e=>e.t>session.boundary.atSecond).length:0;}
return{createSession,initialSpatialSnapshot,advanceUntilBoundary,resumeFromHighRes,snapshot,structureIntegrity,futureEventCount,roleOf,zoneFromProgress,phaseFromProgress};
});
