(function(root,factory){const ge=(typeof globalThis!=='undefined'&&globalThis.FLRPG_CONTINUOUS_CORE)||null,gp=(typeof globalThis!=='undefined'&&globalThis.FLRPG_PROTAGONIST_MATCH_CONTROLLER)||null,api=factory(ge,gp);if(typeof module==='object'&&module.exports)module.exports=api;else root.FLRPG_LIVE_V06_SCENE_AUTHORITY=api;})(typeof globalThis!=='undefined'?globalThis:this,function(GLOBAL_E,GLOBAL_P){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const deep=v=>v==null?v:JSON.parse(JSON.stringify(v));
const SLOT_Y={GK:34,LB:9,LCB:25,RCB:43,RB:59,LCM:20,CM:34,RCM:48,LW:8,ST:34,RW:60};
function localToWorld(team,x,y){return team==='HOME'?{x,y}:{x:105-x,y:68-y};}
function localBase(p,ctx){const poss=ctx.possession===p.team,pr=ctx.ball.progress*100,s=ctx.structure[p.team]||{lineHeight:50,width:50,transitionDebt:0},zone=ctx.zone||'MIDFIELD',phase=ctx.phase||'BUILD_UP';let bx={GK:6,FB:25,CB:22,CM:45,WF:65,ST:70}[p.role]||45;bx+=(poss?1:-1)*clamp((pr-50)*.20,-9,11);bx+=(Number(s.lineHeight||50)-50)*.10;if(poss&&p.role==='CM'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE')){const high=zone==='BOX'||phase==='CHANCE';bx=Math.max(bx,p.slot==='CM'?(high?63:58):(high?73:67));}if(poss&&p.role==='WF'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE'))bx=Math.max(bx,zone==='BOX'||phase==='CHANCE'?78:74);if(poss&&p.role==='ST'&&(zone==='FINAL_THIRD'||zone==='BOX'||phase==='CHANCE'))bx=Math.max(bx,zone==='BOX'||phase==='CHANCE'?84:80);const width=clamp(Number(s.width||50)/50,.72,1.30);let y=34+(SLOT_Y[p.slot]-34)*width;if(p.role==='ST'&&poss)bx+=4;if(p.role==='FB'&&poss)bx+=Math.max(0,Number(s.transitionDebt||0)-.25)*5;return{x:clamp(bx,4,101),y:clamp(y,4,64)};}
function ballXY(ctx){
 const pr=clamp(Number(ctx.ball.progress)||0.5,0.02,0.99),zone=ctx.zone||'MIDFIELD',phase=ctx.phase||'BUILD_UP';let x;
 if(zone==='OWN_THIRD')x=clamp(12+pr*22,12,34);
 else if(zone==='MIDFIELD')x=clamp(30+pr*35,32,62);
 else if(zone==='FINAL_THIRD')x=clamp(60+(pr-0.60)*62,64,84.5);
 else{const wide=ctx.ball.lane==='LEFT'||ctx.ball.lane==='RIGHT';x=clamp(78+(pr-0.78)*(wide?55:42),80,wide?94.2:91.8);}
 if(phase==='CHANCE'&&zone!=='BOX')x=Math.max(x,76);
 const y=ctx.ball.lane==='LEFT'?18:ctx.ball.lane==='RIGHT'?50:34;return localToWorld(ctx.possession,x,y);
}
function safeHeroAttackPosition(m,hp,bxy){
 const team=hp.team,attackDir=team==='HOME'?1:-1,opp=m.players.filter(p=>p.team!==team).map(p=>p.x).sort((a,b)=>a-b);
 const secondLast=team==='HOME'?(opp.at(-2)??96):(opp[1]??9),ballRef=bxy.x;
 const line=team==='HOME'?Math.max(secondLast,ballRef):Math.min(secondLast,ballRef);
 let x=line-attackDir*0.65;
 const targetY=34+(bxy.y-34)*.35,gk=m.players.find(p=>p.team!==team&&p.role==='GK');
 if(gk&&Math.hypot(x-gk.x,targetY-gk.y)<7.0)x=gk.x-attackDir*7.0;
 return clamp(x,5,96.2);
}
function entryHash(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function entryNoise(key,salt){let x=entryHash(`${key}|${salt}`);x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)/4294967296)*2-1;}
function worldToLocal(team,x,y){return team==='HOME'?{x,y}:{x:105-x,y:68-y};}
function contextualEntry(p,ctx,bxy,boundary){const base=localBase(p,ctx),bl=worldToLocal(p.team,bxy.x,bxy.y),key=`${boundary.sceneId}|${p.id}`,n1=entryNoise(key,'x'),n2=entryNoise(key,'y'),n3=entryNoise(key,'run'),inPoss=ctx.possession===p.team,trans=ctx.phase==='TRANSITION',recent=(boundary.preContext||[]).slice(-5),actor=recent.some(e=>e?.detail?.actorId===p.id),target=recent.some(e=>e?.detail?.targetId===p.id);let x=base.x+n1*(trans?4.6:2.8),y=base.y+n2*(trans?3.8:2.5);if(inPoss){const pull=p.role==='CM'?.11:p.role==='WF'||p.role==='ST'?.075:p.role==='FB'?.055:.025;x+=clamp((bl.x-x)*pull,-4.2,4.2);y+=clamp((bl.y-y)*pull,-3.8,3.8);}else{x+=clamp((bl.x-x)*.035,-2.2,2.2);y+=clamp((bl.y-y)*.075,-3.2,3.2);if(trans)x-=2.2+Math.max(0,n3)*2.4;}if(actor){x+=clamp((bl.x-x)*.14,-4.8,4.8);y+=clamp((bl.y-y)*.14,-4.2,4.2);}if(target&&inPoss){x+=1.4+Math.max(0,n3)*2.4;y+=clamp((bl.y-y)*.08,-2.5,2.5);}x=clamp(x,4,101);y=clamp(y,4,64);let runX=inPoss?(p.role==='ST'||p.role==='WF'?3.6:p.role==='CM'?2.3:1.5):(trans?-3.3:-1.2),runY=clamp((bl.y-y)*.10,-2.8,2.8)+n2*.7;if(target&&inPoss)runX+=1.8;if(actor)runY*=.45;const w=localToWorld(p.team,x,y),wt=localToWorld(p.team,clamp(x+runX,4,101),clamp(y+runY,4,64)),vx=clamp((wt.x-w.x)/1.4,-5.5,5.5),vy=clamp((wt.y-w.y)/1.4,-4.5,4.5);return{x:w.x,y:w.y,tx:wt.x,ty:wt.y,vx,vy,action:trans&&!inPoss?'RECOVER_LIVE':inPoss?'SUPPORT_LIVE':'HOLD_LIVE'};}

function continuousEntry(p,ctx,bxy,boundary){const q=ctx?.spatial?.players?.[p.id];if(!q||!Number.isFinite(Number(q.x))||!Number.isFinite(Number(q.y)))return contextualEntry(p,ctx,bxy,boundary);const vx=Number.isFinite(Number(q.vx))?Number(q.vx):0,vy=Number.isFinite(Number(q.vy))?Number(q.vy):0,speed=Math.hypot(vx,vy),lead=clamp(.8+speed*.12,.8,1.6),tx=clamp(Number(q.x)+vx*lead,3,102),ty=clamp(Number(q.y)+vy*lead,3,65);return{x:clamp(Number(q.x),3,102),y:clamp(Number(q.y),3,65),tx,ty,vx:clamp(vx,-7.8,7.8),vy:clamp(vy,-7.8,7.8),action:ctx.phase==='TRANSITION'&&ctx.possession!==p.team?'RECOVER_LIVE':ctx.possession===p.team?'SUPPORT_LIVE':'HOLD_LIVE',source:'HYBRID_SPATIAL_CONTINUITY'};}
function runtime(runtimeDir){if(GLOBAL_E&&GLOBAL_P)return{E:GLOBAL_E,P:GLOBAL_P};if(typeof require==='function'&&runtimeDir){const path=require('path');return{E:require(path.join(runtimeDir,'continuous_match_core.js')),P:require(path.join(runtimeDir,'protagonist_match_controller.js'))};}throw new Error('V0.6 runtime unavailable');}
function seedMatch(boundary,opts={}){const {E,P}=runtime(opts.runtimeDir),hero=boundary.heroPlayerId,state=P.create(opts.seed||`STEP67-${boundary.sceneId}`,{heroPlayerId:hero,mode:'FULL_SKIP',replaySeconds:10,appearanceStatus:opts.appearanceStatus||'STARTER',managerProfiles:opts.managerProfiles||{HOME:'BALANCED',AWAY:'BALANCED'}}),m=state.m,ctx=boundary.stateSnapshot,bxy=ballXY(ctx);m.time=Number(ctx.second);m.score={...ctx.score};m.possession=ctx.possession;m.phase=ctx.phase==='TRANSITION'?'TRANSITION':'OPEN_PLAY';m.restart=null;m.completed=false;m.nextShape=m.time;m.transitionUntil=ctx.phase==='TRANSITION'?m.time+2.2:0;m.events=[];m.stats.currentPossessionTeam=ctx.possession;m.stats.currentPossessionStartedAt=m.time;m.protagonistExplicitActionRequired=opts.explicitHeroChoiceRequired===true;
 for(const p of m.players){const e=continuousEntry(p,ctx,bxy,boundary);p.x=e.x;p.y=e.y;p.vx=e.vx;p.vy=e.vy;p.tx=e.tx;p.ty=e.ty;p.hasBall=false;p.action=e.action;p.tacticalTask='HYBRID_ENTRY_LIVE';p.nextThink=m.time+.12+(Math.abs((p.id.charCodeAt(0)||1)*17+(p.slot?.length||1)*13)%24)/100;p.lockTargetUntil=0;p.markTargetId=null;p.runUntil=m.time+1.4+Math.abs(entryNoise(`${boundary.sceneId}|${p.id}`,'hold'))*.9;p.sprint=Math.hypot(p.vx,p.vy)>2.5;}
 let owner=m.players.find(p=>p.id===ctx.ball.ownerId);if(!owner||owner.team!==ctx.possession)owner=m.players.find(p=>p.team===ctx.possession&&p.role==='CM')||m.players.find(p=>p.team===ctx.possession&&p.role!=='GK');const sb=ctx?.spatial?.ball;if(sb&&Number.isFinite(Number(sb.x))&&Number.isFinite(Number(sb.y))){owner.x=clamp(Number(sb.x),3,102);owner.y=clamp(Number(sb.y),3,65);}else{owner.x=bxy.x;owner.y=bxy.y;}const od=owner.team==='HOME'?1:-1;owner.tx=clamp(owner.x+od*2.2,3,102);owner.ty=clamp(owner.y+entryNoise(`${boundary.sceneId}|${owner.id}`,'owner-y')*.8,3,65);owner.vx=clamp((owner.tx-owner.x)/1.3,-4.2,4.2);owner.vy=clamp((owner.ty-owner.y)/1.3,-2.5,2.5);owner.hasBall=true;owner.controlledSince=m.time;owner.nextThink=m.time+.35;const hp=m.players.find(p=>p.id===hero);if(hp&&hp.id!==owner.id){const dir=hp.team==='HOME'?1:-1;if(boundary.reason==='ATTACKING_INVOLVEMENT'){hp.tx=clamp(hp.x+dir*(3.2+Math.max(0,entryNoise(boundary.sceneId,'hero-run'))*2.0),5,100);hp.ty=clamp(hp.y+(bxy.y-hp.y)*.10,6,62);hp.runUntil=Math.max(hp.runUntil,m.time+2.2);hp.sprint=true;hp.action='ATTACKING_RUN_LIVE';hp.tacticalTask='HYBRID_ENTRY_LIVE';}else if(boundary.reason==='DEFENSIVE_TRANSITION'){hp.tx=clamp(hp.x-dir*3.0,5,100);hp.ty=clamp(hp.y+(bxy.y-hp.y)*.16,6,62);hp.action='RECOVER_GOAL_SIDE';hp.tacticalTask='HYBRID_ENTRY_LIVE';}}m.ball={...m.ball,mode:'CONTROLLED',x:owner.x,y:owner.y,z:0,vx:0,vy:0,vz:0,ownerId:owner.id,intendedReceiverId:null,kind:'CONTROL',lastTouchTeam:owner.team,lastTouchPlayer:owner.id,age:0};m.ballOwner=owner.id;m.lastTouchTeam=owner.team;m.lastTouchPlayer=owner.id;m.playersById=Object.fromEntries(m.players.map(p=>[p.id,p]));if(boundary.setPiece){const br=E.choiceActionBridge(),sp=boundary.setPiece,team=sp.team||ctx.possession;let rx=bxy.x,ry=bxy.y;if(sp.kind==='CORNER'){rx=team==='HOME'?103.8:1.2;ry=sp.lane==='LEFT'?1.2:66.8;}br.startDeadRestart(m,sp.kind,team,rx,ry);}if(boundary.protagonistPerformance)state.performance=deep(boundary.protagonistPerformance);state.history=[];state.pending=null;state.resultTracker=null;state.currentScene=null;state.scenes=[];state.pauses=[];state.lastPauseAt=-999;state.lastPauseControlledSince=-999;state.forceNextChoice=false;return{E,P,state,entrySnapshot:E.snapshot(m)};}
function tryHeroOwnerCheckpoint(P,state){const q=P.inspect(state);if(!q||q.frame?.kind!=='ON_BALL'||!q.options?.length)return false;state.mode='PLAYER_ALL';P.maybeCheckpoint(state);if(state.pending)return true;state.mode='FULL_SKIP';return false;}
function roleRelevant(boundary,q){if(!q||!q.options?.length)return false;const kind=q.frame?.kind,role=boundary.heroRole||'CM';if(role==='ST')return kind==='ON_BALL'&&q.importance>=.16;if(role==='CB')return(kind==='DEFENDING'&&q.importance>=.18)||(kind==='ON_BALL'&&boundary.reason==='BUILDUP_INVOLVEMENT'&&q.importance>=.12);if(role==='CM')return(kind==='ON_BALL'&&q.importance>=.14)||(kind==='DEFENDING'&&boundary.reason==='DEFENSIVE_TRANSITION'&&q.importance>=.22);if(role==='GK')return(kind==='ON_BALL'&&q.frame?.role==='GK')||(kind==='DEFENDING'&&q.frame?.role==='GK'&&(q.frame?.threatShot?.inBox||q.frame?.distance<=11.5));return kind==='ON_BALL';}
function runToChoice(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,dt=.10,fastGoalkeeper=boundary.heroRole==='GK'&&boundary.reason==='GK_GOALKEEPING',fastCbDefense=boundary.heroRole==='CB'&&boundary.reason==='DEFENSIVE_TRANSITION',fastDeveloperOffside=boundary.developerScenario?.key==='OFFSIDE_INVOLVEMENT',minPre=fastDeveloperOffside?.80:fastGoalkeeper?.70:fastCbDefense?1.20:clamp(Number(opts.minPreSeconds)||5,5,7),contextLead=fastDeveloperOffside?.45:fastGoalkeeper?.55:fastCbDefense?.65:clamp(Number(opts.contextLeadSeconds)||1.6,1.2,2.4),maxSearch=clamp(Number(opts.maxSearchSeconds)||35,minPre,60),frames=[deep(env.entrySnapshot)],start=state.m.time;
 const tryRelevant=()=>{const q=P.inspect(state);if(!roleRelevant(boundary,q))return false;state.mode='PLAYER_ALL';P.maybeCheckpoint(state);if(state.pending)return true;state.mode='FULL_SKIP';return false;};
 while(!state.m.completed&&!state.pending&&state.m.time<start+contextLead-.001){P.step(state,dt);frames.push(deep(E.snapshot(state.m)));if((fastGoalkeeper||fastCbDefense||fastDeveloperOffside)&&tryRelevant())break;}
 if(!state.m.completed&&!state.pending){if(fastGoalkeeper||fastCbDefense||fastDeveloperOffside)tryRelevant();if(!state.pending)tryHeroOwnerCheckpoint(P,state);}
 while(!state.m.completed&&!state.pending&&state.m.time<start+minPre-.001){P.step(state,dt);frames.push(deep(E.snapshot(state.m)));if((fastGoalkeeper||fastCbDefense||fastDeveloperOffside)&&tryRelevant())break;if(tryHeroOwnerCheckpoint(P,state))break;}
 while(!state.m.completed&&!state.pending&&state.m.time<start+maxSearch-.001){if(tryHeroOwnerCheckpoint(P,state))break;const q=P.inspect(state);if(roleRelevant(boundary,q)){state.mode='PLAYER_ALL';P.maybeCheckpoint(state);if(state.pending)break;state.mode='FULL_SKIP';}P.step(state,dt);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;}
 const pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null,preSpan=pending&&scene?.preFrames?.length?scene.preFrames.at(-1).time-scene.preFrames[0].time:Math.min(10,frames.at(-1).time-frames[0].time);return{...env,frames,pending,scene,searchSeconds:Number((state.m.time-start).toFixed(3)),preSpan:Number(preSpan.toFixed(3)),hadChoice:!!pending,futureOutcomePrecomputed:false};}
function applyChoiceAndAdvance(opened,choiceId,targetId=null,opts={}){const {E,P,state}=opened;if(!state.pending)throw new Error('NO_PENDING_CHOICE');const pendingBefore=deep(state.pending),same=state.pending.options.filter(o=>o.id===choiceId),chosen=targetId!=null?same.find(o=>o.targetId===targetId):(same.length===1?same[0]:same.find(o=>o.targetId==null));if(!chosen)throw new Error(targetId!=null?'CHOICE_TARGET_NOT_AVAILABLE':'CHOICE_NOT_AVAILABLE');const activeSceneId=state.currentScene?.sceneId,activeEpisodeId=state.currentScene?.episodeId||pendingBefore.episodeId||activeSceneId,applied=P.applyChoice(state,chosen.id,chosen.targetId||null,{source:'TEST_HARNESS'});if(!applied.ok)throw new Error(applied.reason||'CHOICE_APPLY_FAILED');if(applied.futureOutcomePrecomputed===true)throw new Error('CHOICE_PRECOMPUTED_OUTCOME_FORBIDDEN');const choiceLog=(state.m.userChoiceLog||[]).at(-1);if(choiceLog&&choiceLog.futureOutcomePrecomputed===true)throw new Error('CHOICE_LOG_PRECOMPUTED_OUTCOME_FORBIDDEN');const postFrames=[],start=state.m.time,maxPost=Number(opts.maxPostSeconds)||12;let guard=0,visiblePostSeconds=0;while(!state.m.completed&&guard++<4000&&visiblePostSeconds<maxPost-.0001){P.step(state,.10);visiblePostSeconds+=.10;postFrames.push(deep(E.snapshot(state.m)));if(typeof opts.debugStepHook==='function')opts.debugStepHook({state,E,P,postFrames});if(!state.resultTracker)break;}if(!state.resultTracker&&!state.pending&&!state.m.completed){P.maybeCheckpoint(state);let chainGuard=0;const chainStart=state.m.time;while(!state.pending&&!state.m.completed&&state.forceNextChoice&&state.m.ball?.mode==='CONTROLLED'&&state.m.ball?.ownerId===state.heroPlayerId&&state.m.time<chainStart+2.4&&chainGuard++<40){P.step(state,.10);postFrames.push(deep(E.snapshot(state.m)));P.maybeCheckpoint(state);}if(state.forceNextChoice&&state.m.ball?.mode==='CONTROLLED'&&state.m.ball?.ownerId===state.heroPlayerId&&!state.pending)throw new Error('PROTAGONIST_REPOSSESSION_CHECKPOINT_MISSING');}const scene=P.sceneById(state,activeSceneId),result=scene?.result||state.lastResult||null,nextPending=state.pending?deep(state.pending):null,continuation=!!nextPending&&(nextPending.episodeId===activeEpisodeId||nextPending.chained),actualEvents=(scene?.postEvents||[]).map(deep);return{state,snapshot:E.snapshot(state.m),sceneId:activeSceneId,episodeId:activeEpisodeId,hadChoice:true,selectedChoice:deep(chosen),applyReceipt:deep(applied),result:deep(result),actualEvents,postFrames,nextPending,continuation,futureOutcomePrecomputed:false};}
function runSetPieceWindow(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,frames=[deep(E.snapshot(state.m))],start=state.m.time,duration=clamp(Number(opts.durationSeconds)||8,5,12);state.mode='FULL_SKIP';let guard=0;
 while(!state.m.completed&&!state.pending&&state.m.time<start+duration-.001&&guard++<2000){
  if(tryHeroOwnerCheckpoint(P,state))break;P.step(state,.10);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;if(!state.m.restart&&state.m.time>start+5.0&&state.m.ball.mode==='CONTROLLED')break;
 }
 const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep),pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null;if(!pending){const bad=events.find(e=>e.actorId===state.heroPlayerId&&['SHOT','HEADER_SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_SETPIECE_ACTION_FORBIDDEN:${bad.type}:${state.heroPlayerId}`);}return{...env,frames,snapshot,actualEvents:events,pending,scene,hadChoice:!!pending,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function runNonHeroShotWindow(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:true}),{E,P,state}=env,frames=[deep(E.snapshot(state.m))],start=state.m.time,duration=clamp(Number(opts.durationSeconds)||8,5,10),hero=state.heroPlayerId,shotter=boundary.shot?.shooterId||boundary.stateSnapshot?.ball?.ownerId;state.mode='FULL_SKIP';const sp=state.m.playersById?.[shotter]||state.m.players.find(p=>p.id===shotter);if(sp){sp.nextThink=state.m.time+.02;sp.controlledSince=Math.min(Number(sp.controlledSince||state.m.time),state.m.time-.6);}let guard=0,shotSeen=false,resolved=false;while(!state.m.completed&&!state.pending&&state.m.time<start+duration-.001&&guard++<2200){if(tryHeroOwnerCheckpoint(P,state))break;P.step(state,.10);frames.push(deep(E.snapshot(state.m)));if(tryHeroOwnerCheckpoint(P,state))break;const ev=(state.m.events||[]).filter(e=>e.t>=start-.001);shotSeen=shotSeen||ev.some(e=>['SHOT','HEADER_SHOT'].includes(e.type));resolved=ev.some(e=>['GOAL','SAVE','CHIP_SAVE','SHOT_MISSED','BLOCK','CORNER','GOAL_KICK'].includes(e.type));if(shotSeen&&resolved&&state.m.time>start+1.0)break;}const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep),pending=state.pending?deep(state.pending):null,scene=state.currentScene?deep(state.currentScene):null;if(!pending){const bad=events.find(e=>e.actorId===hero&&['SHOT','HEADER_SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_NON_HERO_SHOT_ACTION_FORBIDDEN:${bad.type}:${hero}`);}return{...env,frames,snapshot,actualEvents:events,pending,scene,hadChoice:!!pending,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function runDeveloperVisualWindow(boundary,opts={}){const env=seedMatch(boundary,{...opts,explicitHeroChoiceRequired:false}),{E,state}=env,frames=[deep(env.entrySnapshot)],start=state.m.time,duration=clamp(Number(opts.durationSeconds)||9,4,12);state.mode='FULL_SKIP';let guard=0;while(!state.m.completed&&state.m.time<start+duration-.001&&guard++<2400){E.step(state.m,.10);frames.push(deep(E.snapshot(state.m)));}const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep);return{...env,frames,snapshot,actualEvents:events,hadChoice:false,result:null,developerVisualOnly:true,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function runFinalWindow(boundary,opts={}){const env=seedMatch(boundary,opts),{E,P,state}=env,frames=[deep(env.entrySnapshot)],start=state.m.time,target=Number(opts.targetSecond)||5400;state.mode='FULL_SKIP';let guard=0;while(!state.m.completed&&state.m.time<target+8.2&&guard++<2200){P.step(state,.10);frames.push(deep(E.snapshot(state.m)));}const snapshot=E.snapshot(state.m),events=(state.m.events||[]).filter(e=>e.t>=start-.001).map(deep);return{...env,frames,snapshot,actualEvents:events,hadChoice:false,result:null,searchSeconds:Number((snapshot.time-start).toFixed(3)),preSpan:Number((snapshot.time-start).toFixed(3)),futureOutcomePrecomputed:false};}
function finalizeEpisode(opened,steps){const {E,P,state}=opened,first=steps[0],episodeId=first?.episodeId||state.currentScene?.episodeId||null,episodeFrames=episodeId?P.episodeReplay(state,episodeId):[],debug=episodeId?P.episodeDebug(state,episodeId):null,actualEvents=(state.m.events||[]).filter(e=>e.type!=='USER_CHOICE').map(deep),results=steps.map(x=>x.result).filter(Boolean);return{state,snapshot:E.snapshot(state.m),hadChoice:steps.length>0,choiceSteps:steps.map(deep),selectedChoice:steps.at(-1)?.selectedChoice||null,result:results.at(-1)||null,results:deep(results),actualEvents:deep(actualEvents),postFrames:steps.flatMap(x=>x.postFrames||[]).map(deep),episodeFrames:deep(episodeFrames),debug:deep(debug),nextPending:state.pending?deep(state.pending):null,futureOutcomePrecomputed:false};}
function autoResolveEpisode(opened,picker,opts={}){const steps=[];let guard=0;while(opened.state.pending&&guard++<(opts.maxChoices||5)){const p=deep(opened.state.pending),c=picker(p,guard);if(!c)throw new Error('PICKER_RETURNED_NO_CHOICE');const r=applyChoiceAndAdvance(opened,c.id,c.targetId||null,opts);steps.push(r);if(!r.continuation)break;}return finalizeEpisode(opened,steps);}
function finishWithoutChoice(opened){const hero=opened.state?.heroPlayerId,events=(opened.state.m.events||[]).map(deep),bad=events.find(e=>e.actorId===hero&&['SHOT','GOAL','PASS','TAKE_ON'].includes(e.type));if(bad)throw new Error(`UNCHOSEN_PROTAGONIST_ACTION_FORBIDDEN:${bad.type}:${hero}`);return{state:opened.state,snapshot:opened.E.snapshot(opened.state.m),hadChoice:false,selectedChoice:null,result:null,actualEvents:events,postFrames:[],episodeFrames:opened.frames.map(deep),debug:{schemaVersion:'FLR_HIGH_RES_NO_CHOICE_0.1',frames:opened.frames.map(deep)},futureOutcomePrecomputed:false};}
function choiceAudit(opened,resolved=null){const issues=[];if(opened.preSpan<4.8)issues.push('PRE_ACTION_TOO_SHORT');if(opened.pending&&opened.pending.futureOutcomePrecomputed!==false)issues.push('PENDING_PRECOMPUTED');if(resolved){if(resolved.futureOutcomePrecomputed!==false)issues.push('RESOLUTION_PRECOMPUTED_FLAG');if(resolved.applyReceipt?.futureOutcomePrecomputed===true)issues.push('APPLY_PRECOMPUTED');const code=resolved.result?.code;if(code==='BLOCKED'||code==='CORNER'){const ev=(resolved.actualEvents||[]).find(e=>e.type==='BLOCK');if(!ev)issues.push('BLOCK_RESULT_WITHOUT_BLOCK_EVENT');}if(code==='GOAL'&&!(resolved.actualEvents||[]).some(e=>e.type==='GOAL'))issues.push('GOAL_WITHOUT_GOAL_EVENT');if(code==='SAVED'&&!(resolved.actualEvents||[]).some(e=>['SAVE','CHIP_SAVE'].includes(e.type)))issues.push('SAVE_WITHOUT_SAVE_EVENT');}
 return{ok:!issues.length,issues};}
return{seedMatch,runToChoice,runSetPieceWindow,runNonHeroShotWindow,runDeveloperVisualWindow,runFinalWindow,applyChoiceAndAdvance,autoResolveEpisode,finalizeEpisode,finishWithoutChoice,choiceAudit};
});