(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FLRPG_HYBRID_SCENE_DEBUG=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v)),num=v=>Number.isFinite(Number(v))?Number(v):0,q=(v,n=4)=>Number(num(v).toFixed(n));
function build(beforeSession,boundary,opened,resolved,afterSession){const scene=resolved?.debug||opened?.scene||null,pending=opened?.pending||null,preFrames=scene?.scenes?.[0]?.preFrames||opened?.scene?.preFrames||[],postFrames=scene?.scenes?.flatMap(s=>s.postFrames||[])||resolved?.postFrames||[];return{schemaVersion:'FLR_HYBRID_LIVE_SCENE_DEBUG_0.3',canonicalContract:{hybridPrecomputesChoice:false,hybridPrecomputesOutcome:false,v06OwnsLiveChoiceDiscovery:true,v06OwnsPostChoiceResolution:true,replayRequiresCausalPreAction:true},hybridBefore:{status:beforeSession.status,boundary:deep(boundary),state:deep(boundary.stateSnapshot),preContext:deep(boundary.preContext)},highResolution:{legacyVersion:opened?.state?.version||null,entrySnapshot:deep(opened?.entrySnapshot||null),searchSeconds:opened?.searchSeconds??null,preActionSpan:opened?.preSpan??null,preActionFrames:deep(preFrames),decision:pending?{at:pending.at,kind:pending.kind,importance:pending.importance,options:deep(pending.options),state:deep(pending.state),futureOutcomePrecomputed:pending.futureOutcomePrecomputed}:null,selectedChoice:deep(resolved?.selectedChoice||null),choiceSteps:deep(resolved?.choiceSteps||[]),applyReceipt:deep(resolved?.applyReceipt||resolved?.choiceSteps?.at?.(-1)?.applyReceipt||null),postActionFrames:deep(postFrames),actualEvents:deep(resolved?.actualEvents||[]),actualResult:deep(resolved?.result||null),actualResults:deep(resolved?.results||[]),episodeFrames:deep(resolved?.episodeFrames||opened?.frames||[])},hybridAfter:afterSession?{status:afterSession.status,state:deep(afterSession.state),lastHighRes:deep(afterSession.state.lastHighRes)}:null,futureOutcomePrecomputed:false};}
function uniqueFrames(hr){
 const rows=[],seen=new Set();for(const group of [hr?.preActionFrames,hr?.episodeFrames,hr?.postActionFrames])for(const f of(group||[])){if(!f||!Array.isArray(f.players))continue;const k=`${q(f.time,5)}|${f.ball?.ownerId||''}|${q(f.ball?.x,3)}|${q(f.ball?.y,3)}`;if(seen.has(k))continue;seen.add(k);rows.push(f);}rows.sort((a,b)=>num(a.time)-num(b.time));return rows;
}
function ballDyn(b={}){return[b.mode||null,q(b.x),q(b.y),q(b.z),q(b.vx),q(b.vy),q(b.vz),b.ownerId||null,b.intendedReceiverId||null,b.kind||null,q(b.attachBlend),b.lastTouchTeam||null,b.lastTouchPlayer||null,q(b.age)];}
function playerDyn(p={}){return[q(p.x),q(p.y),q(p.vx),q(p.vy),q(p.tx),q(p.ty),p.action||null,p.tacticalTask||null,p.markTargetId||null,p.hasBall?1:0,q(p.bodyAngle),q(p.faceTargetAngle)];}
function frameState(f,order){const map=Object.fromEntries((f?.players||[]).map(p=>[p.id,p]));return{t:q(f?.time,5),score:[num(f?.score?.HOME),num(f?.score?.AWAY)],phase:f?.phase||null,possession:f?.possession||null,ball:ballDyn(f?.ball),players:order.map(id=>playerDyn(map[id]||{})),completed:!!f?.completed};}
function diffBall(a,b){return b.map((v,i)=>typeof v==='number'&&typeof a[i]==='number'?q(v-a[i],5):(v===a[i]?0:v));}
function applyBallDelta(a,d){return d.map((v,i)=>typeof a[i]==='number'&&typeof v==='number'?q(a[i]+v,5):(v===0?a[i]:v));}
function diffPlayer(a,b){return b.map((v,i)=>i<=5||i>=10?q(num(v)-num(a[i]),5):(v===a[i]?0:v));}
function applyPlayerDelta(a,d){return d.map((v,i)=>i<=5||i>=10?q(num(a[i])+num(v),5):(v===0?a[i]:v));}
function compactEvents(events){return(events||[]).filter(Boolean).map(e=>[q(e.t??e.time,4),e.type||e.kind||null,e.team||null,e.actorId||e.detail?.actorId||null,e.targetId||e.detail?.targetId||null,e.text||e.detail?.text||null]);}
function intentSummary(frames,order){const prev=new Map(),out=[];for(const f of frames){const map=Object.fromEntries((f.players||[]).map(p=>[p.id,p]));for(const id of order){const p=map[id];if(!p)continue;const sig=`${p.tacticalTask||p.action||''}|${p.markTargetId||''}`,old=prev.get(id);if(sig!==old){out.push([q(f.time,4),id,p.tacticalTask||p.action||null,p.markTargetId||null]);prev.set(id,sig);}}}return out;}
function compactCurrentMotion(frames){
 if(!frames.length)return null;const first=frames[0],order=(first.players||[]).map(p=>p.id),staticPlayers=(first.players||[]).map(p=>[p.id,p.name||null,p.team||null,p.role||null,p.slot||null]),base=frameState(first,order),deltas=[];let prev=base;
 for(const f of frames.slice(1)){const cur=frameState(f,order),pds=[];for(let i=0;i<cur.players.length;i++){const d=diffPlayer(prev.players[i],cur.players[i]);if(d.some(v=>v!==0))pds.push([i,...d]);}deltas.push([q(cur.t-prev.t,5),cur.score[0]===prev.score[0]&&cur.score[1]===prev.score[1]?0:cur.score,cur.phase===prev.phase?0:cur.phase,cur.possession===prev.possession?0:cur.possession,diffBall(prev.ball,cur.ball),pds,cur.completed===prev.completed?0:(cur.completed?1:-1),compactEvents(f.events)]);prev=cur;}
 const last=frames.at(-1),tele=last?.telemetry||first?.telemetry||{},stats=last?.stats||{};
 return{encoding:'DELTA_MOTION_V1',mode:'CURRENT_FULL_MOTION',frameCount:frames.length,playerStatic:staticPlayers,base,deltas,intentChanges:intentSummary(frames,order),finalSummary:{stats:deep(stats),telemetry:{futureOutcomePrecomputed:tele.futureOutcomePrecomputed,focusPlayerId:tele.focusPlayerId,totalDecisions:tele.totalDecisions,focusVisibleDecisions:tele.focusVisibleDecisions,shotsByTeam:deep(tele.shotsByTeam||null),focusStats:deep(tele.focusStats||null)}}};
}
function compactPreviousMotion(frames){
 if(!frames.length)return null;const first=frames[0],last=frames.at(-1),order=(first.players||[]).map(p=>p.id),staticPlayers=(first.players||[]).map(p=>[p.id,p.name||null,p.team||null,p.role||null,p.slot||null]);
 const frameEvents=[];for(const f of frames)frameEvents.push(...compactEvents(f.events));
 return{encoding:'START_END_INTENT_V1',mode:'PREVIOUS_START_END',frameCountOriginal:frames.length,playerStatic:staticPlayers,start:frameState(first,order),end:frameState(last,order),intentChanges:intentSummary(frames,order),frameEvents};
}
function compactEntry(f){if(!f||!Array.isArray(f.players))return null;const order=f.players.map(p=>p.id);return{playerStatic:f.players.map(p=>[p.id,p.name||null,p.team||null,p.role||null,p.slot||null]),state:frameState(f,order),actionCandidates:deep(f.actionCandidates||[]),userDirectedPassTrace:deep(f.userDirectedPassTrace||null)};}
function compactDecision(d){if(!d)return null;return{at:d.at,kind:d.kind,importance:d.importance,options:deep(d.options||[]),futureOutcomePrecomputed:!!d.futureOutcomePrecomputed,state:d.state&&Array.isArray(d.state.players)?compactEntry(d.state):deep(d.state||null)};}
function slimForBugReport(debug,mode='current'){
 if(!debug)return null;const hr=debug.highResolution||{},frames=uniqueFrames(hr),isPrev=mode==='previous',motion=isPrev?compactPreviousMotion(frames):compactCurrentMotion(frames),out={schemaVersion:'FLR_HYBRID_LIVE_SCENE_DEBUG_0.4_SLIM',canonicalContract:deep(debug.canonicalContract||{}),hybridBefore:deep(debug.hybridBefore||null),highResolution:{legacyVersion:hr.legacyVersion??null,entrySnapshot:compactEntry(hr.entrySnapshot),searchSeconds:hr.searchSeconds??null,preActionSpan:hr.preActionSpan??null,decision:compactDecision(hr.decision),selectedChoice:deep(hr.selectedChoice||null),choiceSteps:deep(hr.choiceSteps||[]),applyReceipt:deep(hr.applyReceipt||null),actualEvents:deep(hr.actualEvents||[]),actualResult:deep(hr.actualResult||null),actualResults:deep(hr.actualResults||[]),motion},hybridAfter:deep(debug.hybridAfter||null),futureOutcomePrecomputed:!!debug.futureOutcomePrecomputed,reportScope:{...(deep(debug.reportScope||{})),keepsFullSituationFrames:false,motionEncoding:motion?.encoding||null,bugReportMode:isPrev?'PREVIOUS_START_END':'CURRENT_DELTA_MOTION'}};
 return out;
}
function expandCurrentMotion(m){
 if(!m||m.encoding!=='DELTA_MOTION_V1')return[];const out=[],order=(m.playerStatic||[]).map(x=>x[0]),toFrame=s=>({time:s.t,score:{HOME:s.score[0],AWAY:s.score[1]},phase:s.phase,possession:s.possession,ball:{mode:s.ball[0],x:s.ball[1],y:s.ball[2],z:s.ball[3],vx:s.ball[4],vy:s.ball[5],vz:s.ball[6],ownerId:s.ball[7],intendedReceiverId:s.ball[8],kind:s.ball[9],attachBlend:s.ball[10],lastTouchTeam:s.ball[11],lastTouchPlayer:s.ball[12],age:s.ball[13]},players:s.players.map((a,i)=>({id:order[i],x:a[0],y:a[1],vx:a[2],vy:a[3],tx:a[4],ty:a[5],action:a[6],tacticalTask:a[7],markTargetId:a[8],hasBall:!!a[9],bodyAngle:a[10],faceTargetAngle:a[11]})),completed:s.completed});
 let cur=deep(m.base);out.push(toFrame(cur));for(const d of m.deltas||[]){const next={t:q(cur.t+d[0],5),score:d[1]===0?deep(cur.score):deep(d[1]),phase:d[2]===0?cur.phase:d[2],possession:d[3]===0?cur.possession:d[3],ball:applyBallDelta(cur.ball,d[4]),players:cur.players.map(a=>deep(a)),completed:d[6]===0?cur.completed:d[6]===1};for(const pd of d[5]||[]){const i=pd[0];next.players[i]=applyPlayerDelta(cur.players[i],pd.slice(1));}cur=next;out.push(toFrame(cur));}return out;
}
return{build,slimForBugReport,expandCurrentMotion};
});
