(function(){'use strict';
const E=window.FLRPG_CONTINUOUS_CORE,P=window.FLRPG_PROTAGONIST_MATCH_CONTROLLER,H=window.FLRPG_LIVE_HYBRID_SESSION_V02,A=window.FLRPG_LIVE_V06_SCENE_AUTHORITY,X=window.FLRPG_HYBRID_SCENE_DEBUG,F=window.FLRPG_FULL_TIME_PRESENTATION,I=window.FLRPG_IN_PITCH_CHOICE_UI,$=id=>document.getElementById(id),canvas=$('heroPitch'),ctx=canvas.getContext('2d');
let trial=1,world=null,session=null,opened=null,beforeHybrid=null,activeBoundary=null,phase='IDLE',last=performance.now(),acc=0,prev=null,curr=null,replayList=[],replayCursor=0,replayReturn='CHOICE',longPressTimer=null,latestIntegratedDebug=null,episodeHistory=[],selectedStepResults=[],finalHighRes=null,hybridEventCursor=0,deferredHandback=null,goalAlertTimer=null,pitchChoice=null,autoAdvanceTimer=null,autoAdvanceInterval=null,sceneNoticeTimer=null,replayResumePhase=null,notableSeen=new Set(),lastFeedEventKey=null,bugDebugOverride=null;const STEP=.10,REPLAY_SPEED=2;
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v)),lerp=(a,b,t)=>a+(b-a)*t;
function projectPitchPlayer(p){const stage=canvas.closest('.pitch-stage'),cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),padX=28,padY=24,fw=canvas.width-padX*2,fh=canvas.height-padY*2,cx=padX+(p.x/105)*fw,cy=padY+(p.y/68)*fh;return{x:(cr.left-sr.left)+(cx/canvas.width)*cr.width,y:(cr.top-sr.top)+(cy/canvas.height)*cr.height}}
function ensurePitchChoice(){if(pitchChoice||!I)return pitchChoice;pitchChoice=I.createController({stageElement:canvas.closest('.pitch-stage'),canvas,getHeroId:()=>$('heroPlayer').value,projectPlayer:projectPitchPlayer,onChoose:(id,targetId,meta)=>choose(id,targetId,meta)});return pitchChoice}
function angleLerp(a,b,t){if(!Number.isFinite(a))return b;if(!Number.isFinite(b))return a;let d=(b-a)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return a+d*t;}function interp(a,b,t){if(!a)return b;const pm=Object.fromEntries((a.players||[]).map(p=>[p.id,p]));return{...b,ball:{...b.ball,x:lerp(a.ball.x,b.ball.x,t),y:lerp(a.ball.y,b.ball.y,t),z:lerp(a.ball.z||0,b.ball.z||0,t)},players:(b.players||[]).map(p=>{const q=pm[p.id]||p;return{...p,x:lerp(q.x,p.x,t),y:lerp(q.y,p.y,t),bodyAngle:angleLerp(q.bodyAngle,p.bodyAngle,t),faceTargetAngle:angleLerp(q.faceTargetAngle,p.faceTargetAngle,t)}})}}
function offsideLine(s,team,includeGK){const opp=(s.players||[]).filter(p=>p.team!==team&&(includeGK||p.role!=='GK')).map(p=>p.x).sort((a,b)=>a-b);if(opp.length<2)return null;return team==='HOME'?opp[opp.length-2]:opp[1]}
function drawLineX(px,padY,fh,x,label,stroke){ctx.save();ctx.strokeStyle=stroke;ctx.fillStyle=stroke;ctx.setLineDash([8,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px(x),padY);ctx.lineTo(px(x),padY+fh);ctx.stroke();ctx.setLineDash([]);ctx.font='11px system-ui';ctx.fillText(label,Math.min(canvas.width-90,px(x)+5),padY+15);ctx.restore()}
function draw(s){if(!s)return;const W=canvas.width,Hh=canvas.height,padX=28,padY=24,fw=W-padX*2,fh=Hh-padY*2,px=v=>padX+v/105*fw,py=v=>padY+v/68*fh;ctx.clearRect(0,0,W,Hh);ctx.fillStyle='#315b37';ctx.fillRect(0,0,W,Hh);ctx.strokeStyle='rgba(240,255,242,.78)';ctx.lineWidth=3;ctx.strokeRect(padX,padY,fw,fh);ctx.beginPath();ctx.moveTo(px(52.5),padY);ctx.lineTo(px(52.5),padY+fh);ctx.stroke();ctx.beginPath();ctx.arc(px(52.5),py(34),9.15/105*fw,0,Math.PI*2);ctx.stroke();ctx.strokeRect(px(0),py(13.84),px(16.5)-px(0),py(54.16)-py(13.84));ctx.strokeRect(px(88.5),py(13.84),px(105)-px(88.5),py(54.16)-py(13.84));
  // Goal frames are a permanent pitch feature, never conditional on scene/version.
  const gy1=py(E.FIELD?.GOAL_Y1??30.34),gy2=py(E.FIELD?.GOAL_Y2??37.66),depth=15;
  ctx.save();ctx.strokeStyle='rgba(250,255,250,.95)';ctx.lineWidth=3;ctx.strokeRect(padX-depth,gy1,depth,gy2-gy1);ctx.strokeRect(padX+fw,gy1,depth,gy2-gy1);ctx.lineWidth=1;ctx.globalAlpha=.42;for(let k=1;k<4;k++){const xx=padX-depth+k*depth/4;ctx.beginPath();ctx.moveTo(xx,gy1);ctx.lineTo(xx,gy2);ctx.stroke();const xr=padX+fw+k*depth/4;ctx.beginPath();ctx.moveTo(xr,gy1);ctx.lineTo(xr,gy2);ctx.stroke();}ctx.restore();
  if($('heroShowOffside').checked){const atk=s.ball?.lastTouchTeam||s.possession||'HOME',en=offsideLine(s,atk,false),rf=offsideLine(s,atk,true);if(en!=null)drawLineX(px,padY,fh,en,'ENGINE OFFSIDE','#ff9b85');if(rf!=null&&Math.abs(rf-en)>.12)drawLineX(px,padY,fh,rf,'2ND OPPONENT','#7dd3fc');}const mobileView=typeof window!=='undefined'&&window.matchMedia&&window.matchMedia('(max-width:760px)').matches;for(const p of s.players||[]){const focus=p.id===$('heroPlayer').value,isGK=p.role==='GK',a=Number.isFinite(p.bodyAngle)?p.bodyAngle:(p.team==='HOME'?0:Math.PI),cx=px(p.x),cy=py(p.y),r=mobileView?(focus?18:14.25):(focus?14:11);ctx.save();if(focus){const rr=mobileView?41:42,spread=.56;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,rr,a-spread,a+spread);ctx.closePath();ctx.fillStyle='rgba(99,214,255,.12)';ctx.fill();ctx.strokeStyle='rgba(99,214,255,.46)';ctx.lineWidth=1.5;ctx.stroke();}ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*(mobileView?(focus?24:19):(focus?22:14)),cy+Math.sin(a)*(mobileView?(focus?24:19):(focus?22:14)));ctx.strokeStyle=focus?'rgba(99,214,255,.95)':'rgba(255,255,255,.58)';ctx.lineWidth=focus?3:2;ctx.stroke();ctx.restore();ctx.beginPath();ctx.fillStyle=p.team==='HOME'?(isGK?'#7dd3fc':'#2563eb'):(isGK?'#fca5a5':'#dc2626');ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();if(focus){ctx.strokeStyle='rgba(0,0,0,.95)';ctx.lineWidth=mobileView?7:7;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.98)';ctx.lineWidth=mobileView?4:4;ctx.stroke();}else{ctx.strokeStyle='rgba(255,255,255,.88)';ctx.lineWidth=mobileView?2.3:2;ctx.stroke();}ctx.fillStyle='#fff';ctx.font=`bold ${mobileView?(focus?13:11):(focus?10:8)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.slot||p.role,cx,cy+.5)}const b=s.ball;ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#1c252b';ctx.lineWidth=2;ctx.arc(px(b.x),py(b.y),7+Math.min(4,(b.z||0)*1.5),0,Math.PI*2);ctx.fill();ctx.stroke()}

function roleInfo(){const id=$('heroPlayer').value;return{id,role:id==='H-ST'?'ST':id==='H-GK'?'GK':id==='H-LCB'?'CB':'CM'}}function seed(){return`LIVE-V03-${trial}-${$('heroPlayer').value}`}
function clearAutoAdvance(){clearTimeout(autoAdvanceTimer);clearInterval(autoAdvanceInterval);autoAdvanceTimer=autoAdvanceInterval=null;const x=$('heroAutoNext');if(x)x.textContent='';const n=$('heroSceneNotice');if(n?.classList.contains('end-countdown')){n.hidden=true;n.classList.remove('end-countdown');}}
function periodMinute(t){const sec=Math.max(0,Number(t)||0),m=Math.floor(sec/60)+1;return sec<2700?`전반 ${Math.min(45,m)}분`:`후반 ${Math.max(1,Math.min(45,m-45))}분`;}
function pushLiveFeed(text,kind=''){const box=$('heroLiveFeed');if(!box||!text)return;const row=document.createElement('div');row.className=`live-feed-row ${kind}`.trim();row.textContent=text;box.appendChild(row);while(box.children.length>3)box.removeChild(box.firstChild);}
function showSceneNotice(text,done=null,duration=1100){const box=$('heroSceneNotice');clearTimeout(sceneNoticeTimer);if(!box){if(done)setTimeout(done,0);return;}box.textContent=text;box.hidden=false;pushLiveFeed(text,'scene');sceneNoticeTimer=setTimeout(()=>{box.hidden=true;if(done)done();},duration);}
function scheduleAutoAdvance(text,seconds=3,next=null){clearAutoAdvance();let left=Math.max(1,Math.floor(seconds)),notice=$('heroSceneNotice'),box=$('heroAutoNext');const render=()=>{const msg=`${text}\n${left}초 후 다음 플레이로 이동합니다.`;if(notice){notice.textContent=msg;notice.classList.add('end-countdown');notice.hidden=false;}if(box)box.textContent='자동으로 다음 플레이로 이동합니다.';};render();autoAdvanceInterval=setInterval(()=>{left--;if(left>0){render();return;}clearAutoAdvance();if(next)next();},1000);}
function setup(){ensurePitchChoice()?.hide();clearAutoAdvance();clearTimeout(sceneNoticeTimer);notableSeen=new Set();lastFeedEventKey=null;const h=roleInfo();world=H.createSession({seed:seed(),heroTeam:'HOME',heroRole:h.role,heroPlayerId:h.id});session=null;opened=null;activeBoundary=null;beforeHybrid=null;selectedStepResults=[];finalHighRes=null;deferredHandback=null;phase='IDLE';latestIntegratedDebug=null;episodeHistory=[];$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;$('heroClock').textContent="0'";$('heroScore').textContent='0 - 0';$('heroPlayback').textContent='대기 · Hybrid';$('heroState').textContent=`${h.role} · 저해상도 경기 시작 전`;$('heroEventLog').textContent='경기 시작 대기';$('heroPauseCount').textContent='선택 0회';$('heroSceneHistory').innerHTML='<div class="muted">아직 선택 장면이 없습니다.</div>';$('heroDownloadScene').disabled=true;$('heroBugReport').disabled=true;$('heroCopyDebug').disabled=true;$('heroDebugSummary').textContent='아직 선택 장면 없음';$('heroCommentary').textContent='경기 시작을 기다리고 있습니다.';if($('heroLiveFeed'))$('heroLiveFeed').innerHTML='<div class="live-feed-row">경기 시작을 기다리고 있습니다.</div>';if($('heroSceneNotice')){$('heroSceneNotice').hidden=true;$('heroSceneNotice').classList.remove('end-countdown');}if($('heroReturnLatest'))$('heroReturnLatest').hidden=true;const ars=$('heroActionResult');if(ars)ars.hidden=true;if($('heroActionResultText'))$('heroActionResultText').textContent='-';hybridEventCursor=0;clearTimeout(goalAlertTimer);const ga=$('heroGoalAlert');if(ga){ga.hidden=true;ga.classList.remove('show','conceded','scored');}draw(E.snapshot(E.createMatch(`${seed()}-KICKOFF-PREVIEW`,{})))}
function pressureText(v){return v<1.4?'강한 압박':v<2.6?'압박 있음':'여유 있음'}function situationText(q){if(!q)return'현재 장면';const f=q.frame;if(f.kind==='ON_BALL'){const z=f.shot?.inBox?'페널티박스 안':f.localX>=80?'최종 3분의 1':f.localX>=55?'공격 전개 구간':'후방 전개';return`${z} · ${pressureText(f.pressure)}${f.shot?.openWindow?' · 슈팅 길 보임':''}${f.shot?.oneVOne?' · GK와 1대1':''}`;}if(f.kind==='DEFENDING')return`상대 볼 소유 · ${f.distance<2.2?'바로 경합 가능한 거리':f.distance<4?'근접 거리':'커버 거리'}`;return'오프더볼'}
function clearTips(){document.querySelectorAll('.choice-option.tooltip-open').forEach(x=>x.classList.remove('tooltip-open'))}function buildChoice(p){const box=$('heroChoiceButtons');box.innerHTML='';let fam='';for(const o of p.options){if(o.family!==fam){const l=document.createElement('span');l.className='choice-family';l.textContent=o.family;box.appendChild(l);fam=o.family;}const b=document.createElement('button');b.className='choice-option';b.dataset.tooltip=o.tooltip||o.hint||'';const st=document.createElement('b');st.textContent=o.label;b.appendChild(st);let held=false;b.addEventListener('pointerdown',()=>{held=false;clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{held=true;clearTips();b.classList.add('tooltip-open')},480)});b.onclick=e=>{if(held||b.classList.contains('tooltip-open')){e.preventDefault();held=false;b.classList.remove('tooltip-open');return}choose(o.id,o.targetId,{source:'USER_UI_CLICK'})};box.appendChild(b)}}
function renderMeta(s){if(!s)return;const min=Math.min(90,Math.floor((s.time||0)/60)+1);$('heroClock').textContent=`${min}'`;$('heroScore').textContent=`${s.score.HOME} - ${s.score.AWAY}`;$('heroPauseCount').textContent=`선택 ${episodeHistory.reduce((n,e)=>n+(e.choiceCount||0),0)+(session?.choiceHistory?.length||0)}회`;$('heroState').textContent=`${s.phase||'-'} · 공 ${s.ball?.mode||'-'}${s.ball?.ownerId===$('heroPlayer').value?' · 주인공 소유':''}`;const ev=s.lastEvent||[...(s.events||[])].reverse().find(e=>e&&e.type!=='USER_CHOICE'&&e.text);if(ev){$('heroCommentary').textContent=ev.text;const key=`${ev.t??''}|${ev.type??''}|${ev.text}`;if(key!==lastFeedEventKey){lastFeedEventKey=key;pushLiveFeed(`${periodMinute(ev.t??s.time)} · ${ev.text}`,ev.type==='GOAL'?'goal':'');}}}
function restoreLatestAfterReplay(){const btn=$('heroReturnLatest');if(btn)btn.hidden=true;replayList=[];const resume=replayResumePhase;replayResumePhase=null;if(session?.pending){showPending();return}if(session?.lastResult){showResult();return}phase=resume&&resume!=='PRE_REPLAY'?resume:'SEARCHING';if(phase==='SEARCHING'){$('heroPlayback').textContent='최신 상황 복귀 · Hybrid 경기 진행';setTimeout(searchHybrid,0);}}
function startReplay(frames,ret='CHOICE',title='다시보기'){if(!frames?.length){if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='CHOICE')showPending();else showResult();return}clearAutoAdvance();clearTimeout(sceneNoticeTimer);const notice=$('heroSceneNotice');if(notice){notice.hidden=true;notice.classList.remove('end-countdown');}if(ret==='HISTORY')replayResumePhase=phase;const latest=$('heroReturnLatest');if(latest)latest.hidden=ret!=='HISTORY';replayList=frames;replayCursor=0;replayReturn=ret;phase='PRE_REPLAY';ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;const dur=(frames.at(-1).time-frames[0].time).toFixed(1);$('heroPlayback').textContent=`${title} · ${dur}초 · 2×`;draw(frames[0]);renderMeta(frames[0]);last=performance.now()}
function processReplay(real){replayCursor+=real*REPLAY_SPEED;const start=replayList[0].time,end=replayList.at(-1).time,target=Math.min(end,start+replayCursor);let i=0;while(i<replayList.length-1&&replayList[i+1].time<=target)i++;const a=replayList[i],b=replayList[Math.min(i+1,replayList.length-1)],t=Math.min(1,Math.max(0,(target-a.time)/Math.max(.001,b.time-a.time)));const v=interp(a,b,t);draw(v);renderMeta(v);if(target>=end-.001){replayList=[];const ret=replayReturn;if(ret==='CHOICE')showPending();else if(ret==='RESULT')showResult();else if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='SETPIECE_HANDOFF')finishSetPieceHighRes();else if(ret==='NOCHOICE_HANDOFF')finishNoChoiceHighRes();else if(ret==='FINAL_HANDOFF')finishFinalHighRes();else if(ret==='FINAL_COMPLETE')completeMatchPresentation();else{phase='IDLE';}}}
function updateDebugAvailability(){const active=!!session&&!!activeBoundary;$('heroDownloadScene').disabled=!(active||latestIntegratedDebug);$('heroBugReport').disabled=!(active||latestIntegratedDebug);$('heroCopyDebug').disabled=!(active||latestIntegratedDebug);if(active){const d=makeIntegratedDebug();$('heroDebugSummary').textContent=`LIVE V0.6 EPISODE\nscene=${activeBoundary.sceneId}\nphase=${phase}\nresult=${d.highResolution.actualResult?.code||'PENDING'}\nfuturePrecomputed=false`;} }
function mobileFlowTo(id){if(typeof window==='undefined'||!window.matchMedia||!window.matchMedia('(max-width:760px)').matches)return;requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'nearest'}));}
function nonHeroBrief(){return $('heroNonHeroMode')?.value==='BRIEF'}
function showActionResult(r){const box=$('heroActionResult'),txt=$('heroActionResultText');if(!box||!txt||!r)return;txt.textContent=`${r.label||r.choiceId} → ${r.headline}`;box.hidden=false;}
function episodeActualEvents(){return session?.m?.events?session.m.events.map(deep):[]}
function ensureScoreEventIntegrity(entryScore,hb){if(!hb?.snapshot?.score)return hb;hb.actualEvents=(hb.actualEvents||[]).map(deep);const score0=entryScore||{HOME:0,AWAY:0},score1=hb.snapshot.score;for(const team of ['HOME','AWAY']){const delta=Math.max(0,(score1[team]||0)-(score0[team]||0)),have=hb.actualEvents.filter(e=>e.type==='GOAL'&&e.team===team).length;for(let i=have;i<delta;i++){const label=team==='HOME'?'블루팀':'레드팀';hb.actualEvents.push({t:Number(hb.snapshot.time||0)-0.001*(delta-i),type:'GOAL',team,actorId:null,scoreLedgerRecovered:true,text:`${label}의 득점이 실제 2D 종료 점수에서 확인됐습니다. ${score1.HOME}-${score1.AWAY}`});}}hb.actualEvents.sort((a,b)=>(a.t||0)-(b.t||0));return hb;}
function showPending(){const q=P.inspect(session);$('heroResultPanel').hidden=true;$('heroChoicePanel').hidden=false;$('heroChoicePrompt').textContent=situationText(q);$('heroImportanceLabel').textContent=`V0.6 actual state · 중요도 ${Math.round((session.pending?.importance||0)*100)}${session.pending?.chained?' · 연계':''}`;buildChoice(session.pending);$('heroPlayback').textContent=session.pending?.chained?'연계된 다음 선택 · V0.6 계속':'선택 대기 · V0.6 state 정지';$('heroCommentary').textContent=session.pending?.chained?'선택 가능한 선수를 눌러 다음 플레이를 고르세요.':'강조된 선수를 눌러 가능한 행동을 선택하세요.';phase='CHOICE';const s=E.snapshot(session.m);draw(s);renderMeta(s);ensurePitchChoice()?.show(session.pending,s);updateDebugAvailability();mobileFlowTo('heroPitch')}
function choose(id,targetId,inputMeta={source:'USER_UI_CLICK'}){const same=session.pending.options.filter(o=>o.id===id),opt=targetId!=null?same.find(o=>o.targetId===targetId):(same.length===1?same[0]:same.find(o=>o.targetId==null));if(!opt)return;const r=P.applyChoice(session,id,targetId,inputMeta);if(!r.ok)return;ensurePitchChoice()?.hide();$('heroChoiceReceipt').hidden=false;$('heroChoiceReceiptText').textContent=opt.label;selectedStepResults.push({sceneId:session.currentScene?.sceneId,episodeId:session.currentScene?.episodeId,selectedChoice:deep(opt)});$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;if($('heroActionResult'))$('heroActionResult').hidden=true;phase='RESULT_PLAYBACK';acc=0;prev=curr=E.snapshot(session.m);$('heroPlayback').textContent=`내 선택 실행 중 · ${opt.label}`;$('heroCommentary').textContent=`${opt.label}을 실행합니다.`;mobileFlowTo('heroPitch');last=performance.now()}
function resultReceipt(){const r=session?.lastResult;if(!r)return;$('heroChoiceReceipt').hidden=false;$('heroChoiceReceiptText').textContent=`${r.label||r.choiceId} → ${r.headline}`;showActionResult(r);$('heroEventLog').innerHTML+=`<div class="choice-flow-event"><strong>↳ ${r.headline}</strong> · ${r.detail}</div>`;}
function processResult(real){acc+=real*2;let g=0;while(acc>=STEP&&g++<100){prev=curr||E.snapshot(session.m);P.step(session,STEP);curr=E.snapshot(session.m);acc-=STEP;if(!session.resultTracker){draw(curr);renderMeta(curr);resultReceipt();if(session.pending?.chained){showPending();return}if(session.activeEpisode){phase='EPISODE_CONTINUATION';$('heroPlayback').textContent='내 선택 결과 이후 같은 공격 상황 계속 재생';acc=0;prev=curr;return}showResult();return}}draw(interp(prev,curr,Math.min(1,acc/STEP)));renderMeta(curr)}
function processEpisodeContinuation(real){acc+=real*2;let g=0;while(acc>=STEP&&g++<100){prev=curr||E.snapshot(session.m);P.step(session,STEP);curr=E.snapshot(session.m);acc-=STEP;draw(curr);renderMeta(curr);if(session.pending){showPending();return}if(!session.activeEpisode||session.m.completed){sceneBreakThenHandback();return}}draw(interp(prev,curr,Math.min(1,acc/STEP)));renderMeta(curr)}
function resultEventsHtml(r){return(r?.events||[]).map(e=>`<div><span>${Math.round(e.t||0)}s</span> ${e.text||e.type}</div>`).join('')}
function showResult(){ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=false;const r=session?.lastResult;if(!r){$('heroResultHeadline').textContent='상황 종료';$('heroResultDetail').textContent='선택 결과를 정리 중입니다.';$('heroResultEvents').innerHTML='';phase='RESULT';return}$('heroResultHeadline').textContent=r.headline;$('heroResultChoice').textContent=`내 선택: ${r.label||r.choiceId}`;$('heroResultDetail').textContent=r.detail;$('heroResultEvents').innerHTML=resultEventsHtml(r);$('heroPlayback').textContent='실제 선택 결과 · 다음 진행 대기';phase='RESULT';updateDebugAvailability();mobileFlowTo('heroPitch');scheduleAutoAdvance(`${r.headline}으로 상황이 종료되었습니다.`,3,continueAfterResult)}
function continueAfterResult(){clearAutoAdvance();if(!session)return;const pending=session.pending;if(pending){showPending();return}if(session.activeEpisode){phase='EPISODE_CONTINUATION';$('heroResultPanel').hidden=true;last=performance.now();return}sceneBreakThenHandback()}
function activeEpisodeId(){return session?.currentScene?.episodeId||session?.lastResult?.episodeId||null}
function handbackSnapshot(){return session?P.handBack(session):null}
function sceneBreakThenHandback(){ensurePitchChoice()?.hide();clearAutoAdvance();const hb=handbackSnapshot();if(!hb){phase='IDLE';return}const entryScore=beforeHybrid?.score?deep(beforeHybrid.score):null;ensureScoreEventIntegrity(entryScore,hb);finalHighRes=hb;phase='SCENE_BREAK';$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;showSceneNotice('상황이 종료되었습니다.',()=>finishHighResHandback(),900)}
function finishHighResHandback(){const hb=finalHighRes;if(!hb){phase='IDLE';return}latestIntegratedDebug=makeIntegratedDebug(hb);episodeHistory.push({sceneId:activeBoundary?.sceneId,episodeId:activeBoundary?.episodeId||activeEpisodeId(),choiceCount:session?.choiceHistory?.length||0,summary:session?.lastResult?.headline||activeBoundary?.reason||'상황 종료',debug:deep(latestIntegratedDebug)});renderEpisodeHistory();const actual=hb.actualEvents||[];for(const e of actual){if(e.type==='GOAL')showGoalAlert(e,hb.snapshot);appendEvent(e)}world=H.handBack(world,hb);session=null;activeBoundary=null;beforeHybrid=null;selectedStepResults=[];finalHighRes=null;deferredHandback=null;$('heroChoiceReceipt').hidden=true;$('heroActionResult').hidden=true;phase='SEARCHING';$('heroPlayback').textContent='Hybrid 경기 재개';draw(world.snapshot);renderMeta(world.snapshot);updateDebugAvailability();setTimeout(searchHybrid,0)}
function appendEvent(e){if(!e)return;const box=$('heroEventLog');const d=document.createElement('div');d.className=e.type==='GOAL'?'major-match-event':e.type?.includes('SET_PIECE')?'setpiece-event':'';d.textContent=`${periodMinute(e.t)} · ${e.text||e.type}`;box.appendChild(d);while(box.children.length>80)box.removeChild(box.firstChild)}
function showGoalAlert(e,s){const box=$('heroGoalAlert');if(!box)return;clearTimeout(goalAlertTimer);const scored=e.team==='HOME',score=s?.score||world?.snapshot?.score||{HOME:0,AWAY:0};$('heroGoalAlertKicker').textContent=scored?'⚽ 블루팀 득점':'⚽ 레드팀 득점';$('heroGoalAlertScore').textContent=`${periodMinute(e.t)} · ${score.HOME}-${score.AWAY}`;$('heroGoalAlertDetail').textContent=e.text||'득점이 발생했습니다.';box.hidden=false;box.classList.toggle('scored',scored);box.classList.toggle('conceded',!scored);goalAlertTimer=setTimeout(()=>{box.hidden=true},3000)}
function renderEpisodeHistory(){const box=$('heroSceneHistory');box.innerHTML='';if(!episodeHistory.length){box.innerHTML='<div class="muted">아직 선택 장면이 없습니다.</div>';return}for(const [i,e] of episodeHistory.entries()){const row=document.createElement('div');row.className='scene-history-row';const txt=document.createElement('span');txt.textContent=`${i+1}. ${e.summary}`;const b=document.createElement('button');b.className='secondary';b.textContent='다시보기';b.onclick=()=>replayHistory(i);row.append(txt,b);box.appendChild(row)}}
function replayHistory(i){const e=episodeHistory[i];if(!e?.debug)return;clearAutoAdvance();const frames=e.debug.highResolution?.fullReplayFrames||[];startReplay(frames,'HISTORY',`이전 상황 ${i+1}`)}
function inspectHybridBoundary(){if(!world)return null;return H.findNextBoundary(world)}
function searchHybrid(){if(phase!=='SEARCHING'||!world)return;let guard=0;while(guard++<12){const b=inspectHybridBoundary();if(!b){if(world.completed){completeMatchPresentation();return}world=H.advance(world,8);draw(world.snapshot);renderMeta(world.snapshot);continue}activeBoundary=b;beforeHybrid=deep(world.snapshot);opened=H.openBoundary(world,b);if(!opened?.ok){world=H.advance(world,2);continue}session=opened.session;phase='PRE_REPLAY';$('heroPlayback').textContent='선택 직전 실제 경기 재생';startReplay(P.latestReplay(session),'CHOICE','선택 직전 실제 경기');return}setTimeout(searchHybrid,0)}
function start(){if(!world)setup();$('heroStart').disabled=true;phase='SEARCHING';$('heroPlayback').textContent='Hybrid 경기 진행';$('heroEventLog').textContent='';showSceneNotice('전반 1분 · 경기가 시작됩니다.',()=>{last=performance.now();searchHybrid()},800)}
function completeMatchPresentation(){clearAutoAdvance();ensurePitchChoice()?.hide();phase='FULL_TIME';const s=world?.snapshot||curr;if(s){draw(s);renderMeta(s)}$('heroPlayback').textContent='경기 종료';$('heroState').textContent='FULL TIME';if(F?.render){F.render({target:$('heroEventLog'),snapshot:s,heroId:$('heroPlayer').value})}}
function finishSetPieceHighRes(){finishHighResHandback()}
function finishNoChoiceHighRes(){finishHighResHandback()}
function finishFinalHighRes(){finishHighResHandback()}
function makeIntegratedDebug(handbackOverride=null){const hb=handbackOverride||finalHighRes||handbackSnapshot(),h=beforeHybrid||{},r=session?.lastResult||null;return{schemaVersion:'FLR_HYBRID_SCENE_DEBUG_0.6',generatedAt:new Date().toISOString(),futurePrecomputed:false,hybridBefore:deep(h),boundary:deep(activeBoundary),highResolution:{selectedChoice:selectedStepResults.at(-1)?.selectedChoice||r?.selectedChoice||null,actualResult:r?deep(r):null,decision:session?.pending?deep(session.pending):null,preActionFrames:session?P.latestReplay(session):[],postActionFrames:session?.replayFrames?deep(session.replayFrames):[],fullReplayFrames:session?.replayFrames?deep(session.replayFrames):[],actualEvents:hb?.actualEvents?deep(hb.actualEvents):[]},hybridAfter:hb?deep(hb.snapshot):null}}
function download(obj,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function currentDebugForBug(){return bugDebugOverride||((session&&activeBoundary)?makeIntegratedDebug():latestIntegratedDebug)}
function compactBugSnapshot(d){if(!d)return null;const hr=d.highResolution||{},hb=d.hybridBefore||{},frames=hr.postActionFrames?.length?hr.postActionFrames:hr.preActionFrames||[],last=frames.at?.(-1)||hr.entrySnapshot||null,hero=hb.boundary?.heroPlayerId||$('heroPlayer').value,ball=last?.ball||{},selected=hr.selectedChoice||null,ps=last?.players||[],anchor=ps.find(p=>p.id===hero)||{x:ball.x||0,y:ball.y||0},need=new Set([hero,ball.ownerId,selected?.targetId].filter(Boolean));ps.slice().sort((a,b)=>Math.min(Math.hypot(a.x-anchor.x,a.y-anchor.y),Math.hypot(a.x-(ball.x||0),a.y-(ball.y||0)))-Math.min(Math.hypot(b.x-anchor.x,b.y-anchor.y),Math.hypot(b.x-(ball.x||0),b.y-(ball.y||0)))).slice(0,9).forEach(p=>need.add(p.id));const players=ps.filter(p=>need.has(p.id)).map(p=>[p.id,p.team,p.slot,Number(p.x.toFixed(1)),Number(p.y.toFixed(1)),Number((p.vx||0).toFixed(1)),Number((p.vy||0).toFixed(1)),p.tacticalTask||p.action||null,p.markTargetId||null]);return{sv:'FLR_BUG_0.2',b:'TT-0.48',step:78,seed:world?.seed||seed(),bd:[hb.boundary?.id||null,hb.boundary?.atSecond!=null?Number(hb.boundary.atSecond.toFixed(1)):null,hb.boundary?.reason||null,hero],c:[selected?.id||null,selected?.targetId||null],r:[hr.actualResult?.code||null,hr.actualResult?.headline||null],o:(hr.decision?.options||[]).map(o=>[o.id,o.targetId||null,o.label]),s:last?[Number(last.time.toFixed(1)),last.score,last.phase,last.possession,[ball.mode,Number((ball.x||0).toFixed(1)),Number((ball.y||0).toFixed(1)),ball.ownerId||null],players]:null,e:(hr.actualEvents||[]).slice(-8).map(e=>[Number(e.t.toFixed(1)),e.type,e.actorId||null,e.targetId||null]),canon:{fp:false,exactTarget:true}}}
function openBugModal(debugOverride=null){bugDebugOverride=debugOverride||null;const d=currentDebugForBug();if(!d)return;const m=$('heroBugModal');$('heroBugDescription').value='';m.hidden=false;setTimeout(()=>$('heroBugDescription').focus(),0)}
function closeBugModal(){bugDebugOverride=null;$('heroBugModal').hidden=true}
function openGitHubBugIssue(){const d=currentDebugForBug();if(!d)return;const desc=$('heroBugDescription').value.trim();if(!desc){$('heroBugDescription').focus();return;}const cat=$('heroBugCategory').value,prio=$('heroBugPriority').value,snap=compactBugSnapshot(d),sec=snap?.s?.[0],minute=Number.isFinite(sec)?Math.floor(sec/60)+1:'?',choiceId=snap?.c?.[0]||'-',targetId=snap?.c?.[1]||'-',short=desc.replace(/\s+/g,' ').slice(0,64),title=`[TT-0.48][P${prio}][${cat}] ${short}`,fullReport=`### 사용자 설명
${desc}

### 자동 첨부
- 버전: TT-0.48 TEST_ONLY
- 경기 시각: ${minute}분
- 분류: ${cat}
- 중요도: P${prio}
- 선택: ${choiceId} → ${targetId}

<details><summary>자동 디버그 스냅샷</summary>

\`\`\`json
${JSON.stringify(snap,null,2)}
\`\`\`
</details>

> 필요하면 동일 장면의 '전체 JSON 저장'도 사용할 수 있습니다.`,preview=desc.length>500?`${desc.slice(0,500)}…` : desc,body=`### 사용자 설명
${preview}

### 자동 첨부
- 버전: TT-0.48 TEST_ONLY
- 경기 시각: ${minute}분
- 분류: ${cat}
- 중요도: P${prio}
- 선택: ${choiceId} → ${targetId}

> 상세 디버그 스냅샷은 클립보드에 복사했습니다. 필요하면 이 아래에 Ctrl+V로 붙여넣으세요.`;navigator.clipboard?.writeText(fullReport).catch(()=>{});const u=`https://github.com/1Lisam/FLR_TEST/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;window.open(u,'_blank','noopener');closeBugModal()}
function loop(ts){const real=Math.min(.08,(ts-last)/1000);last=ts;if(phase==='PRE_REPLAY'&&replayList.length)processReplay(real);else if(phase==='RESULT_PLAYBACK'&&session)processResult(real);else if(phase==='EPISODE_CONTINUATION'&&session)processEpisodeContinuation(real);requestAnimationFrame(loop)}
if($('heroReturnLatest'))$('heroReturnLatest').onclick=()=>{if(replayReturn==='HISTORY'&&phase==='PRE_REPLAY')restoreLatestAfterReplay();};$('heroStart').onclick=start;$('heroReset').onclick=setup;$('heroNewSeed').onclick=()=>{trial++;setup()};$('heroPlayer').onchange=setup;$('heroReplayBefore').onclick=()=>session&&startReplay(P.latestReplay(session),'CHOICE','선택 직전 실제 경기');$('heroReplayEpisode').onclick=()=>{if(!session)return;const ep=activeEpisodeId(),f=ep?P.episodeReplay(session,ep):[];if(f.length)startReplay(f,'RESULT','전체 상황 다시보기')};$('heroContinue').onclick=continueAfterResult;$('heroBugReport').onclick=()=>openBugModal();$('heroBugCancel').onclick=closeBugModal;$('heroBugOpenIssue').onclick=openGitHubBugIssue;$('heroBugModal').onclick=e=>{if(e.target===$('heroBugModal'))closeBugModal()};$('heroDownloadScene').onclick=()=>{const d=session&&activeBoundary?makeIntegratedDebug():latestIntegratedDebug;if(d)download(d,session&&activeBoundary?'FLR_HYBRID_CURRENT_EPISODE.json':'FLR_HYBRID_LATEST.json')};$('heroCopyDebug').onclick=()=>navigator.clipboard?.writeText($('heroDebugSummary').textContent);$('heroShowOffside').onchange=()=>session&&draw(E.snapshot(session.m));setup();requestAnimationFrame(loop);
})();