(function(){'use strict';
const E=window.FLRPG_CONTINUOUS_CORE,P=window.FLRPG_PROTAGONIST_MATCH_CONTROLLER,H=window.FLRPG_LIVE_HYBRID_SESSION_V02,A=window.FLRPG_LIVE_V06_SCENE_AUTHORITY,X=window.FLRPG_HYBRID_SCENE_DEBUG,F=window.FLRPG_FULL_TIME_PRESENTATION,I=window.FLRPG_IN_PITCH_CHOICE_UI,$=id=>document.getElementById(id),canvas=$('heroPitch'),ctx=canvas.getContext('2d');
let trial=1,world=null,session=null,opened=null,beforeHybrid=null,activeBoundary=null,phase='IDLE',last=performance.now(),acc=0,prev=null,curr=null,replayList=[],replayCursor=0,replayReturn='CHOICE',longPressTimer=null,latestIntegratedDebug=null,episodeHistory=[],selectedStepResults=[],finalHighRes=null,hybridEventCursor=0,deferredHandback=null,goalAlertTimer=null,pitchChoice=null,autoAdvanceTimer=null,autoAdvanceInterval=null,sceneNoticeTimer=null,replayResumePhase=null,notableSeen=new Set(),lastFeedEventKey=null;const STEP=.10,REPLAY_SPEED=2;
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v)),lerp=(a,b,t)=>a+(b-a)*t;
function projectPitchPlayer(p){const stage=canvas.closest('.pitch-stage'),cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),padX=28,padY=24,fw=canvas.width-padX*2,fh=canvas.height-padY*2,cx=padX+(p.x/105)*fw,cy=padY+(p.y/68)*fh;return{x:(cr.left-sr.left)+(cx/canvas.width)*cr.width,y:(cr.top-sr.top)+(cy/canvas.height)*cr.height}}
function ensurePitchChoice(){if(pitchChoice||!I)return pitchChoice;pitchChoice=I.createController({stageElement:canvas.closest('.pitch-stage'),canvas,getHeroId:()=>$('heroPlayer').value,projectPlayer:projectPitchPlayer,onChoose:(id,targetId,meta)=>choose(id,targetId,meta)});return pitchChoice}
function angleLerp(a,b,t){if(!Number.isFinite(a))return b;if(!Number.isFinite(b))return a;let d=(b-a)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return a+d*t;}function interp(a,b,t){if(!a)return b;const pm=Object.fromEntries((a.players||[]).map(p=>[p.id,p]));return{...b,ball:{...b.ball,x:lerp(a.ball.x,b.ball.x,t),y:lerp(a.ball.y,b.ball.y,t),z:lerp(a.ball.z||0,b.ball.z||0,t)},players:(b.players||[]).map(p=>{const q=pm[p.id]||p;return{...p,x:lerp(q.x,p.x,t),y:lerp(q.y,p.y,t),bodyAngle:angleLerp(q.bodyAngle,p.bodyAngle,t),faceTargetAngle:angleLerp(q.faceTargetAngle,p.faceTargetAngle,t)}})}}
function offsideLine(s,team,includeGK){const opp=(s.players||[]).filter(p=>p.team!==team&&(includeGK||p.role!=='GK')).map(p=>p.x).sort((a,b)=>a-b);if(opp.length<2)return null;return team==='HOME'?opp[opp.length-2]:opp[1]}
function drawLineX(px,padY,fh,x,label,stroke){ctx.save();ctx.strokeStyle=stroke;ctx.fillStyle=stroke;ctx.setLineDash([8,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px(x),padY);ctx.lineTo(px(x),padY+fh);ctx.stroke();ctx.setLineDash([]);ctx.font='11px system-ui';ctx.fillText(label,Math.min(canvas.width-90,px(x)+5),padY+15);ctx.restore()}
function draw(s){if(!s)return;const W=canvas.width,Hh=canvas.height,padX=28,padY=24,fw=W-padX*2,fh=Hh-padY*2,px=v=>padX+v/105*fw,py=v=>padY+v/68*fh;ctx.clearRect(0,0,W,Hh);ctx.fillStyle='#315b37';ctx.fillRect(0,0,W,Hh);ctx.strokeStyle='rgba(240,255,242,.78)';ctx.lineWidth=3;ctx.strokeRect(padX,padY,fw,fh);ctx.beginPath();ctx.moveTo(px(52.5),padY);ctx.lineTo(px(52.5),padY+fh);ctx.stroke();ctx.beginPath();ctx.arc(px(52.5),py(34),9.15/105*fw,0,Math.PI*2);ctx.stroke();ctx.strokeRect(px(0),py(13.84),px(16.5)-px(0),py(54.16)-py(13.84));ctx.strokeRect(px(88.5),py(13.84),px(105)-px(88.5),py(54.16)-py(13.84));
  // Goal frames are a permanent pitch feature, never conditional on scene/version.
  const gy1=py(E.FIELD?.GOAL_Y1??30.34),gy2=py(E.FIELD?.GOAL_Y2??37.66),depth=15;
  ctx.save();ctx.strokeStyle='rgba(250,255,250,.95)';ctx.lineWidth=3;ctx.strokeRect(padX-depth,gy1,depth,gy2-gy1);ctx.strokeRect(padX+fw,gy1,depth,gy2-gy1);ctx.lineWidth=1;ctx.globalAlpha=.42;for(let k=1;k<4;k++){const xx=padX-depth+k*depth/4;ctx.beginPath();ctx.moveTo(xx,gy1);ctx.lineTo(xx,gy2);ctx.stroke();const xr=padX+fw+k*depth/4;ctx.beginPath();ctx.moveTo(xr,gy1);ctx.lineTo(xr,gy2);ctx.stroke();}ctx.restore();
  if($('heroShowOffside').checked){const atk=s.ball?.lastTouchTeam||s.possession||'HOME',en=offsideLine(s,atk,false),rf=offsideLine(s,atk,true);if(en!=null)drawLineX(px,padY,fh,en,'ENGINE OFFSIDE','#ff9b85');if(rf!=null&&Math.abs(rf-en)>.12)drawLineX(px,padY,fh,rf,'2ND OPPONENT','#7dd3fc');}const mobileView=typeof window!=='undefined'&&window.matchMedia&&window.matchMedia('(max-width:760px)').matches;for(const p of s.players||[]){const focus=p.id===$('heroPlayer').value,isGK=p.role==='GK',a=Number.isFinite(p.bodyAngle)?p.bodyAngle:(p.team==='HOME'?0:Math.PI),cx=px(p.x),cy=py(p.y),r=mobileView?(focus?18:14.25):(focus?14:11);ctx.save();if(focus){const rr=mobileView?41:42,spread=.56;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,rr,a-spread,a+spread);ctx.closePath();ctx.fillStyle='rgba(99,214,255,.12)';ctx.fill();ctx.strokeStyle='rgba(99,214,255,.46)';ctx.lineWidth=1.5;ctx.stroke();}ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*(mobileView?(focus?24:19):(focus?22:14)),cy+Math.sin(a)*(mobileView?(focus?24:19):(focus?22:14)));ctx.strokeStyle=focus?'rgba(99,214,255,.95)':'rgba(255,255,255,.58)';ctx.lineWidth=focus?3:2;ctx.stroke();ctx.restore();ctx.beginPath();ctx.fillStyle=p.team==='HOME'?(isGK?'#7dd3fc':'#2563eb'):(isGK?'#fca5a5':'#dc2626');ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();if(focus){ctx.strokeStyle='rgba(0,0,0,.95)';ctx.lineWidth=mobileView?7:7;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.98)';ctx.lineWidth=mobileView?4:4;ctx.stroke();}else{ctx.strokeStyle='rgba(255,255,255,.88)';ctx.lineWidth=mobileView?2.3:2;ctx.stroke();}ctx.fillStyle='#fff';ctx.font=`bold ${mobileView?(focus?13:11):(focus?10:8)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.slot||p.role,cx,cy+.5)}const b=s.ball;ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#1c252b';ctx.lineWidth=2;ctx.arc(px(b.x),py(b.y),7+Math.min(4,(b.z||0)*1.5),0,Math.PI*2);ctx.fill();ctx.stroke()}

function roleInfo(){const id=$('heroPlayer').value;return{id,role:id==='H-ST'?'ST':id==='H-GK'?'GK':id==='H-LCB'?'CB':'CM'}}function seed(){return`LIVE-V03-${trial}-${$('heroPlayer').value}`}
function clearAutoAdvance(){clearTimeout(autoAdvanceTimer);clearInterval(autoAdvanceInterval);autoAdvanceTimer=autoAdvanceInterval=null;const x=$('heroAutoNext');if(x)x.textContent='';const n=$('heroSceneNotice');if(n?.classList.contains('end-countdown')){n.hidden=true;n.classList.remove('end-countdown');}}
function periodMinute(t){const sec=Math.max(0,Number(t)||0),m=Math.floor(sec/60)+1;return sec<2700?`전반 ${Math.min(45,m)}분`:`후반 ${Math.max(1,Math.min(45,m-45))}분`;}
function pushLiveFeed(text,kind=''){const box=$('heroLiveFeed');if(!box||!text)return;const row=document.createElement('div');row.className=`live-feed-row ${kind}`.trim();row.textContent=text;box.appendChild(row);while(box.children.length>3)box.removeChild(box.firstChild);}
function showSceneNotice(text,done=null,duration=1100){const box=$('heroSceneNotice');clearTimeout(sceneNoticeTimer);if(!box){if(done)setTimeout(done,0);return;}box.textContent=text;box.hidden=false;pushLiveFeed(text,'scene');sceneNoticeTimer=setTimeout(()=>{box.hidden=true;if(done)done();},duration);}
function scheduleAutoAdvance(text,seconds=3,next=null){clearAutoAdvance();let left=Math.max(1,Math.floor(seconds)),notice=$('heroSceneNotice'),box=$('heroAutoNext');const render=()=>{const msg=`${text}\n${left}초 후 다음 플레이로 이동합니다.`;if(notice){notice.textContent=msg;notice.classList.add('end-countdown');notice.hidden=false;}if(box)box.textContent='자동으로 다음 플레이로 이동합니다.';};render();autoAdvanceInterval=setInterval(()=>{left--;if(left>0){render();return;}clearAutoAdvance();if(next)next();},1000);}
function setup(){ensurePitchChoice()?.hide();clearAutoAdvance();clearTimeout(sceneNoticeTimer);notableSeen=new Set();lastFeedEventKey=null;const h=roleInfo();world=H.createSession({seed:seed(),heroTeam:'HOME',heroRole:h.role,heroPlayerId:h.id});session=null;opened=null;activeBoundary=null;beforeHybrid=null;selectedStepResults=[];finalHighRes=null;deferredHandback=null;phase='IDLE';latestIntegratedDebug=null;episodeHistory=[];$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;$('heroClock').textContent="0'";$('heroScore').textContent='0 - 0';$('heroPlayback').textContent='대기 · Hybrid';$('heroState').textContent=`${h.role} · 저해상도 경기 시작 전`;$('heroEventLog').textContent='경기 시작 대기';$('heroPauseCount').textContent='선택 0회';$('heroSceneHistory').innerHTML='<div class="muted">아직 선택 장면이 없습니다.</div>';$('heroDownloadScene').disabled=true;$('heroCopyDebug').disabled=true;$('heroDebugSummary').textContent='아직 선택 장면 없음';$('heroCommentary').textContent='경기 시작을 기다리고 있습니다.';if($('heroLiveFeed'))$('heroLiveFeed').innerHTML='<div class="live-feed-row">경기 시작을 기다리고 있습니다.</div>';if($('heroSceneNotice')){$('heroSceneNotice').hidden=true;$('heroSceneNotice').classList.remove('end-countdown');}if($('heroReturnLatest'))$('heroReturnLatest').hidden=true;const ars=$('heroActionResult');if(ars)ars.hidden=true;if($('heroActionResultText'))$('heroActionResultText').textContent='-';hybridEventCursor=0;clearTimeout(goalAlertTimer);const ga=$('heroGoalAlert');if(ga){ga.hidden=true;ga.classList.remove('show','conceded','scored');}draw(E.snapshot(E.createMatch(`${seed()}-KICKOFF-PREVIEW`,{})))}
function pressureText(v){return v<1.4?'강한 압박':v<2.6?'압박 있음':'여유 있음'}function situationText(q){if(!q)return'현재 장면';const f=q.frame;if(f.kind==='ON_BALL'){const z=f.shot?.inBox?'페널티박스 안':f.localX>=80?'최종 3분의 1':f.localX>=55?'공격 전개 구간':'후방 전개';return`${z} · ${pressureText(f.pressure)}${f.shot?.openWindow?' · 슈팅 길 보임':''}${f.shot?.oneVOne?' · GK와 1대1':''}`;}if(f.kind==='DEFENDING')return`상대 볼 소유 · ${f.distance<2.2?'바로 경합 가능한 거리':f.distance<4?'근접 거리':'커버 거리'}`;return'오프더볼'}
function clearTips(){document.querySelectorAll('.choice-option.tooltip-open').forEach(x=>x.classList.remove('tooltip-open'))}function buildChoice(p){const box=$('heroChoiceButtons');box.innerHTML='';let fam='';for(const o of p.options){if(o.family!==fam){const l=document.createElement('span');l.className='choice-family';l.textContent=o.family;box.appendChild(l);fam=o.family;}const b=document.createElement('button');b.className='choice-option';b.dataset.tooltip=o.tooltip||o.hint||'';const st=document.createElement('b');st.textContent=o.label;b.appendChild(st);let held=false;b.addEventListener('pointerdown',()=>{held=false;clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{held=true;clearTips();b.classList.add('tooltip-open')},480)});b.onclick=e=>{if(held||b.classList.contains('tooltip-open')){e.preventDefault();held=false;b.classList.remove('tooltip-open');return}choose(o.id,o.targetId,{source:'USER_UI_CLICK'})};box.appendChild(b)}}
function renderMeta(s){if(!s)return;const min=Math.min(90,Math.floor((s.time||0)/60)+1);$('heroClock').textContent=`${min}'`;$('heroScore').textContent=`${s.score.HOME} - ${s.score.AWAY}`;$('heroPauseCount').textContent=`선택 ${episodeHistory.reduce((n,e)=>n+(e.choiceCount||0),0)+(session?.choiceHistory?.length||0)}회`;$('heroState').textContent=`${s.phase||'-'} · 공 ${s.ball?.mode||'-'}${s.ball?.ownerId===$('heroPlayer').value?' · 주인공 소유':''}`;const ev=s.lastEvent||[...(s.events||[])].reverse().find(e=>e&&e.type!=='USER_CHOICE'&&e.text);if(ev){$('heroCommentary').textContent=ev.text;const key=`${ev.t??''}|${ev.type??''}|${ev.text}`;if(key!==lastFeedEventKey){lastFeedEventKey=key;pushLiveFeed(`${periodMinute(ev.t??s.time)} · ${ev.text}`,ev.type==='GOAL'?'goal':'');}}}
function restoreLatestAfterReplay(){const btn=$('heroReturnLatest');if(btn)btn.hidden=true;replayList=[];const resume=replayResumePhase;replayResumePhase=null;if(session?.pending){showPending();return}if(session?.lastResult){showResult();return}phase=resume&&resume!=='PRE_REPLAY'?resume:'SEARCHING';if(phase==='SEARCHING'){$('heroPlayback').textContent='최신 상황 복귀 · Hybrid 경기 진행';setTimeout(searchHybrid,0);}}
function startReplay(frames,ret='CHOICE',title='다시보기'){if(!frames?.length){if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='CHOICE')showPending();else showResult();return}clearAutoAdvance();clearTimeout(sceneNoticeTimer);const notice=$('heroSceneNotice');if(notice){notice.hidden=true;notice.classList.remove('end-countdown');}if(ret==='HISTORY')replayResumePhase=phase;const latest=$('heroReturnLatest');if(latest)latest.hidden=ret!=='HISTORY';replayList=frames;replayCursor=0;replayReturn=ret;phase='PRE_REPLAY';ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;const dur=(frames.at(-1).time-frames[0].time).toFixed(1);$('heroPlayback').textContent=`${title} · ${dur}초 · 2×`;draw(frames[0]);renderMeta(frames[0]);last=performance.now()}
function processReplay(real){replayCursor+=real*REPLAY_SPEED;const start=replayList[0].time,end=replayList.at(-1).time,target=Math.min(end,start+replayCursor);let i=0;while(i<replayList.length-1&&replayList[i+1].time<=target)i++;const a=replayList[i],b=replayList[Math.min(i+1,replayList.length-1)],t=Math.min(1,Math.max(0,(target-a.time)/Math.max(.001,b.time-a.time)));const v=interp(a,b,t);draw(v);renderMeta(v);if(target>=end-.001){replayList=[];const ret=replayReturn;if(ret==='CHOICE')showPending();else if(ret==='RESULT')showResult();else if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='SETPIECE_HANDOFF')finishSetPieceHighRes();else if(ret==='NOCHOICE_HANDOFF')finishNoChoiceHighRes();else if(ret==='FINAL_HANDOFF')finishFinalHighRes();else if(ret==='FINAL_COMPLETE')completeMatchPresentation();else{phase='IDLE';}}}
function updateDebugAvailability(){const active=!!session&&!!activeBoundary;$('heroDownloadScene').disabled=!(active||latestIntegratedDebug);$('heroCopyDebug').disabled=!(active||latestIntegratedDebug);if(active){const d=makeIntegratedDebug();$('heroDebugSummary').textContent=`LIVE V0.6 EPISODE\nscene=${activeBoundary.sceneId}\nphase=${phase}\nresult=${d.highResolution.actualResult?.code||'PENDING'}\nfuturePrecomputed=false`;} }
function mobileFlowTo(id){if(typeof window==='undefined'||!window.matchMedia||!window.matchMedia('(max-width:760px)').matches)return;requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'nearest'}));}
function nonHeroBrief(){return $('heroNonHeroMode')?.value==='BRIEF'}
function showActionResult(r){const box=$('heroActionResult'),txt=$('heroActionResultText');if(!box||!txt||!r)return;txt.textContent=`${r.label||r.choiceId} → ${r.headline}`;box.hidden=false;}
function episodeActualEvents(){return session?.m?.events?session.m.events.map(deep):[]}
function ensureScoreEventIntegrity(entryScore,hb){if(!hb?.snapshot?.score)return hb;hb.actualEvents=(hb.actualEvents||[]).map(deep);const score0=entryScore||{HOME:0,AWAY:0},score1=hb.snapshot.score;for(const team of ['HOME','AWAY']){const delta=Math.max(0,(score1[team]||0)-(score0[team]||0)),have=hb.actualEvents.filter(e=>e.type==='GOAL'&&e.team===team).length;for(let i=have;i<delta;i++){const label=team==='HOME'?'블루팀':'레드팀';hb.actualEvents.push({t:Number(hb.snapshot.time||0)-0.001*(delta-i),type:'GOAL',team,actorId:null,scoreLedgerRecovered:true,text:`${label}의 득점이 실제 2D 종료 점수에서 확인됐습니다. ${score1.HOME}-${score1.AWAY}`});}}hb.actualEvents.sort((a,b)=>(a.t||0)-(b.t||0));return hb;}
function showPending(){const q=P.inspect(session);$('heroResultPanel').hidden=true;$('heroChoicePanel').hidden=false;$('heroChoicePrompt').textContent=situationText(q);$('heroImportanceLabel').textContent=`V0.6 actual state · 중요도 ${Math.round((session.pending?.importance||0)*100)}${session.pending?.chained?' · 연계':''}`;buildChoice(session.pending);$('heroPlayback').textContent=session.pending?.chained?'연계된 다음 선택 · V0.6 계속':'선택 대기 · V0.6 state 정지';$('heroCommentary').textContent=session.pending?.chained?'선택 가능한 선수를 눌러 다음 플레이를 고르세요.':'강조된 선수를 눌러 가능한 행동을 선택하세요.';phase='CHOICE';const s=E.snapshot(session.m);draw(s);renderMeta(s);ensurePitchChoice()?.show(session.pending,s);updateDebugAvailability();mobileFlowTo('heroPitch')}
function choose(id,targetId,inputMeta={source:'USER_UI_CLICK'}){const same=session.pending.options.filter(o=>o.id===id),opt=targetId!=null?same.find(o=>o.targetId===targetId):(same.length===1?same[0]:same.find(o=>o.targetId==null));if(!opt)return;const r=P.applyChoice(session,id,targetId,inputMeta);if(!r.ok)return;ensurePitchChoice()?.hide();$('heroChoiceReceipt').hidden=false;$('heroChoiceReceiptText').textContent=opt.label;selectedStepResults.push({sceneId:session.currentScene?.sceneId,episodeId:session.currentScene?.episodeId,selectedChoice:deep(opt)});$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;if($('heroActionResult'))$('heroActionResult').hidden=true;phase='RESULT_PLAYBACK';acc=0;prev=curr=E.snapshot(session.m);$('heroPlayback').textContent=`내 선택 실행 중 · ${opt.label}`;$('heroCommentary').textContent=`${opt.label}을 실행합니다.`;mobileFlowTo('heroPitch');last=performance.now()}
function resultReceipt(){const r=session?.lastResult;if(!r)return;$('heroChoiceReceipt').hidden=false;$('heroChoiceReceiptText').textContent=`${r.label||r.choiceId} → ${r.headline}`;showActionResult(r);$('heroEventLog').innerHTML+=`<div class="choice-flow-event"><strong>↳ ${r.headline}</strong> · ${r.detail}</div>`;}
function processResult(real){acc+=real*2;let g=0;while(acc>=STEP&&g++<100){prev=curr||E.snapshot(session.m);P.step(session,STEP);curr=E.snapshot(session.m);acc-=STEP;if(!session.resultTracker){draw(curr);renderMeta(curr);resultReceipt();if(session.pending?.chained){showPending();return}if(session.activeEpisode){phase='EPISODE_CONTINUATION';$('heroPlayback').textContent='내 선택 결과 이후 같은 공격 상황 계속 재생';acc=0;prev=curr;return}showResult();return}}draw(interp(prev,curr,Math.min(1,acc/STEP)));renderMeta(curr)}
function processEpisodeContinuation(real){acc+=real*2;let g=0;while(acc>=STEP&&g++<100){prev=curr||E.snapshot(session.m);P.step(session,STEP);curr=E.snapshot(session.m);acc-=STEP;draw(curr);renderMeta(curr);if(session.pending){showPending();return}if(!session.activeEpisode||session.m.completed){sceneBreakThenHandback();return}}draw(interp(prev,curr,Math.min(1,acc/STEP)));renderMeta(curr)}
function resultEventsHtml(r){return(r?.events||[]).filter(e=>e.type!=='USER_CHOICE').map(e=>`<div class="result-event">${Math.max(1,Math.floor(e.t/60)+1)}' · ${e.text}</div>`).join('')}
function activeEpisodeId(){return session?.lastResult?.sceneId?P.sceneById(session,session.lastResult.sceneId)?.episodeId:null}function showResult(){const r=session.lastResult;if(!r)return;clearAutoAdvance();ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=false;$('heroResultHeadline').textContent=r.headline;$('heroResultChoice').textContent=`내 선택: ${r.label||r.choiceId}`;$('heroResultDetail').textContent=r.detail;$('heroResultEvents').innerHTML=resultEventsHtml(r);$('heroContinue').textContent=session.pending?.chained?'연계된 다음 선택으로':'즉시 다음 플레이';$('heroReplayEpisode').disabled=false;$('heroPlayback').textContent='실제 결과 확인 · V0.6 일시정지';showActionResult(r);phase='RESULT_REVIEW';const s=E.snapshot(session.m);draw(s);renderMeta(s);updateDebugAvailability();if(!session.pending?.chained)scheduleAutoAdvance(`${r.headline}\n상황이 종료되었습니다.`,3,()=>sceneBreakThenHandback(true))}
function makeIntegratedDebug(){const ep=activeEpisodeId(),scenes=ep?P.episodeScenes(session,ep):[],resolved={selectedChoice:selectedStepResults.at(-1)?.selectedChoice||null,choiceSteps:scenes.map(sc=>({sceneId:sc.sceneId,selectedChoice:sc.choice,result:sc.result})),actualEvents:episodeActualEvents(),result:session.lastResult,results:scenes.map(sc=>sc.result).filter(Boolean),episodeFrames:ep?P.episodeReplay(session,ep):[],debug:ep?P.episodeDebug(session,ep):null};return X.build(beforeHybrid,activeBoundary,opened,resolved,world)}
function sceneBreakThenHandback(fromResultCountdown=false){if(!session)return;clearAutoAdvance();ensurePitchChoice()?.hide();phase='SCENE_BREAK';$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;const headline=session.lastResult?.headline||'플레이';$('heroPlayback').textContent='상황 종료 · 이 공격/수비 흐름이 정리되었습니다';$('heroEventLog').innerHTML+='<div class="scene-break-event"><strong>— 상황 종료 —</strong> · 경기 전체 흐름으로 돌아갑니다.</div>';pushLiveFeed(`${headline} 플레이가 일어나 상황이 종료되었습니다.`,'end');const s=E.snapshot(session.m);draw(s);renderMeta(s);if(fromResultCountdown)setTimeout(()=>{if(phase==='SCENE_BREAK'&&session)handback()},450);else scheduleAutoAdvance(`${headline} 플레이가 일어나 상황 종료`,3,()=>{if(phase==='SCENE_BREAK'&&session)handback()})}
function handback(){ensurePitchChoice()?.hide();const ep=activeEpisodeId(),scenes=ep?P.episodeScenes(session,ep):[],events=episodeActualEvents(),frames=ep?P.episodeReplay(session,ep):[],dbgPre=makeIntegratedDebug(),hb=ensureScoreEventIntegrity(opened?.entrySnapshot?.score||activeBoundary?.stateSnapshot?.score,{snapshot:E.snapshot(session.m),hadChoice:true,result:session.lastResult,results:scenes.map(sc=>sc.result).filter(Boolean),actualEvents:events,episodeFrames:frames,debug:ep?P.episodeDebug(session,ep):null});appendHighResNotables(hb.actualEvents);H.resumeFromHighRes(world,hb);flushHybridNotables();latestIntegratedDebug=X.build(beforeHybrid,activeBoundary,opened,{...hb,selectedChoice:selectedStepResults.at(-1)?.selectedChoice||null,choiceSteps:scenes.map(sc=>({sceneId:sc.sceneId,selectedChoice:sc.choice,result:sc.result}))},world);episodeHistory.push({minute:Math.floor(activeBoundary.atSecond/60)+1,choiceCount:scenes.length,headline:session.lastResult?.headline||'선택 Episode',frames:deep(frames),debug:deep(latestIntegratedDebug)});renderHistory();session=null;opened=null;selectedStepResults=[];phase='SEARCHING';$('heroResultPanel').hidden=true;$('heroPlayback').textContent='Hybrid 경기 재개 · 다음 실제 관여 구간 탐색';$('heroDownloadScene').disabled=false;$('heroCopyDebug').disabled=false;$('heroDebugSummary').textContent=`HYBRID→V0.6→HYBRID\nscene=${activeBoundary.sceneId}\nresult=${latestIntegratedDebug.highResolution.actualResult?.code||'-'}\nfuturePrecomputed=false`;activeBoundary=null;beforeHybrid=null;setTimeout(searchHybrid,0)}
function continueAfterResult(){clearAutoAdvance();if(session.pending?.chained){showPending();return}sceneBreakThenHandback(true)}
function renderHistory(){const box=$('heroSceneHistory');if(!episodeHistory.length){box.innerHTML='<div class="muted">아직 선택 장면이 없습니다.</div>';return}box.innerHTML='';episodeHistory.forEach((e,i)=>{const row=document.createElement('div');row.className='scene-row';row.innerHTML=`<div class="scene-row-main"><strong>${e.minute}' · 선택 ${e.choiceCount}회</strong><small>${e.headline}</small></div><div class="scene-actions"></div>`;const a=row.querySelector('.scene-actions'),r=document.createElement('button');r.className='secondary';r.textContent='다시보기';r.onclick=()=>startReplay(e.frames,'HISTORY',`${e.minute}' 전체 Episode`);a.appendChild(r);const j=document.createElement('button');j.className='secondary';j.textContent='JSON';j.onclick=()=>download(e.debug,`FLR_HYBRID_${e.minute}m.json`);a.appendChild(j);box.appendChild(row)})}
function causalFramesForEvent(frames,eventT,pre=8,post=3.5){if(!frames?.length||!Number.isFinite(eventT))return frames||[];const a=eventT-pre,b=eventT+post,rows=frames.filter(f=>f.time>=a&&f.time<=b);return rows.length>=2?rows:frames;}
function heroNameFrom(openedLike){return openedLike?.entrySnapshot?.players?.find(p=>p.id===$('heroPlayer').value)?.name||'';}function eventMentionsHero(events,openedLike){const hid=$('heroPlayer').value,n=heroNameFrom(openedLike);return(events||[]).some(e=>e.actorId===hid||((!e.actorId&&n)?String(e.text||'').includes(n):false));}
function setPieceReplayDecision(o,b){const ev=o?.actualEvents||[],goal=ev.find(e=>e.type==='GOAL'),shot=ev.find(e=>['SHOT','HEADER_SHOT'].includes(e.type)),save=ev.find(e=>['SAVE','CHIP_SAVE'].includes(e.type)),heroInvolved=eventMentionsHero(ev,o);return{show:!!goal,goal,shot,save,heroInvolved,eventT:goal?.t??null};}
function setPieceSummary(o,b){const ev=o?.actualEvents||[],kind=b?.setPiece?.kind==='CORNER'?'코너킥':'프리킥',shot=ev.find(e=>['SHOT','HEADER_SHOT'].includes(e.type)),save=ev.find(e=>['SAVE','CHIP_SAVE'].includes(e.type)),goal=ev.find(e=>e.type==='GOAL');if(goal)return`${kind} → 득점`;if(shot&&save)return`${kind} → ${shot.type==='HEADER_SHOT'?'헤더':'슈팅'} → 골키퍼 선방`;if(shot)return`${kind} → ${shot.type==='HEADER_SHOT'?'헤더':'슈팅'}`;return`${kind} → 공격 정리`;}
function scoreDeltaTeam(entry,snap){if(!entry?.score||!snap?.score)return null;if(snap.score.HOME>entry.score.HOME)return'HOME';if(snap.score.AWAY>entry.score.AWAY)return'AWAY';return null;}
function showGoalAlert({minute,team,score,scorer=null,detail=null},duration=2300,done=null){const box=$('heroGoalAlert');if(!box){if(done)setTimeout(done,duration);return;}clearTimeout(goalAlertTimer);const heroTeam=world?.opts?.heroTeam||'HOME',ours=team===heroTeam;box.classList.remove('scored','conceded');box.classList.add(ours?'scored':'conceded');$('heroGoalAlertKicker').textContent=ours?'⚽ 우리 팀 득점':'⚠ 상대 팀 득점';$('heroGoalAlertScore').textContent=`${minute}' · ${score.HOME}-${score.AWAY}`;$('heroGoalAlertDetail').textContent=detail||(scorer?`${scorer} 득점`:'득점 장면이 발생했습니다.');box.hidden=false;requestAnimationFrame(()=>box.classList.add('show'));$('heroScore').classList.add('goal-score-pulse');goalAlertTimer=setTimeout(()=>{box.classList.remove('show');$('heroScore').classList.remove('goal-score-pulse');setTimeout(()=>{box.hidden=true;if(done)done();},180)},duration);}
function finishNoChoiceHighRes(){if(!deferredHandback||!activeBoundary)return;const entry=opened?.entrySnapshot||deferredHandback.entrySnapshot||activeBoundary?.stateSnapshot||null,out=ensureScoreEventIntegrity(entry?.score,deferredHandback),goal=(out.actualEvents||[]).find(e=>e.type==='GOAL'),heroInvolved=eventMentionsHero(out.actualEvents||[],opened),brief=nonHeroBrief()&&!heroInvolved;appendHighResNotables(out.actualEvents||[]);H.resumeFromHighRes(world,out);flushHybridNotables();const team=goal?(goal.team||scoreDeltaTeam(entry,out.snapshot)):null,score=out.snapshot?.score||world.state.score,detail=goal?.text||null;deferredHandback=null;opened=null;activeBoundary=null;beforeHybrid=null;if(goal){phase='GOAL_NOTICE';$('heroPlayback').textContent=heroInvolved?'주인공 관여 득점 확인':(brief?'비관여 득점 · 간략 보기':'비관여 득점 확인');showGoalAlert({minute:Math.floor(goal.t/60)+1,team:team||'HOME',score,detail},brief?1500:2100,()=>{if(phase==='GOAL_NOTICE'){phase='SEARCHING';searchHybrid();}});return;}phase='SCENE_BREAK';$('heroPlayback').textContent='비관여 중요 장면 종료 · 경기 전체 흐름으로 복귀';setTimeout(()=>{if(phase==='SCENE_BREAK'){phase='SEARCHING';searchHybrid()}},900)}
function finishSetPieceHighRes(){if(!opened||!activeBoundary)return;const hb=ensureScoreEventIntegrity(opened?.entrySnapshot?.score||activeBoundary?.stateSnapshot?.score,{snapshot:opened.snapshot,hadChoice:false,result:null,actualEvents:opened.actualEvents||[],episodeFrames:opened.frames||[]});if(!opened.suppressNotables)appendHighResNotables(hb.actualEvents);H.resumeFromHighRes(world,hb);flushHybridNotables();$('heroPlayback').textContent='세트피스 종료 · Hybrid 경기 재개';opened=null;activeBoundary=null;beforeHybrid=null;phase='SCENE_BREAK';setTimeout(()=>{if(phase==='SCENE_BREAK'){phase='SEARCHING';searchHybrid()}},900)}
function finishFinalHighRes(){if(!finalHighRes||!activeBoundary)return;const hb=ensureScoreEventIntegrity(finalHighRes?.entrySnapshot?.score||activeBoundary?.stateSnapshot?.score,{snapshot:finalHighRes.snapshot,hadChoice:false,result:null,actualEvents:finalHighRes.actualEvents||[],episodeFrames:finalHighRes.frames||[]});H.resumeFromHighRes(world,hb);appendHighResNotables(hb.actualEvents);const walk=F&&typeof F.walkoffFrames==='function'?F.walkoffFrames(finalHighRes.snapshot,{duration:4.5,dt:.10}):[];$('heroEventLog').innerHTML+=`<div class="scene-break-event"><strong>90' · 주심이 경기 종료를 선언합니다.</strong><br>선수들이 경기장을 빠져나가 락커룸으로 향합니다.</div>`;$('heroPlayback').textContent='경기 종료 · 선수단 퇴장';if(walk.length)startReplay(walk,'FINAL_COMPLETE','경기 종료 · 락커룸 복귀');else completeMatchPresentation();}
function completeMatchPresentation(){phase='COMPLETE';const sc=finalHighRes?.snapshot?.score||world?.state?.score||{HOME:0,AWAY:0};$('heroClock').textContent="90'";$('heroScore').textContent=`${sc.HOME} - ${sc.AWAY}`;$('heroPlayback').textContent='경기 종료 · 선수단 락커룸 복귀';$('heroState').textContent='FULL_TIME';$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;activeBoundary=null;beforeHybrid=null;opened=null;finalHighRes=null;}
let hybridPlayerNames=null;function hybridName(id){if(!id)return'선수';if(!hybridPlayerNames){try{hybridPlayerNames=Object.fromEntries((E.createMatch('HYBRID-NAME-MAP').players||[]).map(p=>[p.id,p.name]));}catch(_){hybridPlayerNames={};}}return hybridPlayerNames[id]||id;}function subjectName(name){const t=String(name||'선수'),c=t.charCodeAt(t.length-1);if(c>=0xAC00&&c<=0xD7A3)return t+(((c-0xAC00)%28)?'이':'가');return t+'이';}
function describeHybridGoal(goal,all){const sc=goal.detail?.score||world.state.score,who=goal.team===(world.opts?.heroTeam||'HOME')?'우리 팀':'상대 팀',shotId=goal.detail?.fromShot||null;let shot=shotId?all.find(x=>x.id===shotId):null;if(!shot)shot=[...all].reverse().find(x=>x.t<=goal.t&&x.t>=goal.t-8&&x.team===goal.team&&x.kind==='SHOT');const build=[...all].filter(x=>x.t<(shot?.t??goal.t)&&x.t>=goal.t-22&&x.team===goal.team&&['DANGEROUS_PASS','BOX_ENTRY','PROGRESS'].includes(x.kind)).slice(-2);const parts=[];for(const x of build){const a=hybridName(x.detail?.actorId),b=hybridName(x.detail?.targetId);if(x.kind==='DANGEROUS_PASS')parts.push(`${a}의 위험한 패스${x.detail?.targetId?` → ${b}`:''}`);else if(x.kind==='BOX_ENTRY')parts.push(`${subjectName(a)} 페널티 지역으로 공격 전개`);else parts.push(`${subjectName(a)} 전진`);}if(shot){const a=hybridName(shot.detail?.actorId),zone=shot.detail?.fromZone==='BOX'?'박스 안':shot.detail?.fromZone==='FINAL_THIRD'?'최종 3분의 1':'공격 지역';parts.push(`${subjectName(a)} ${zone}에서 슈팅`);}parts.push(`${who} 득점`);return`<div class="major-match-event"><strong>⚽ ${Math.floor(goal.t/60)+1}' · ${parts.join(' → ')}</strong> · ${sc.HOME}:${sc.AWAY} <span>(내 선택 장면 아님)</span></div>`;}
function flushHybridNotables(){if(!world?.state?.resolvedEvents)return[];const all=world.state.resolvedEvents,rows=all.slice(hybridEventCursor),goals=[];hybridEventCursor=all.length;for(const e of rows){if(e.kind==='GOAL'){goals.push(e);$('heroEventLog').innerHTML+=describeHybridGoal(e,all);}}return goals;}
function appendHighResNotables(events=[]){for(const e of events){const key=`${e.type}|${Number(e.t||0).toFixed(2)}|${e.text||''}`;if(notableSeen.has(key))continue;notableSeen.add(key);if(e.type==='GOAL'){$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>⚽ ${Math.floor(e.t/60)+1}' · ${e.text}</strong> <span>(실제 2D 장면)</span></div>`;pushLiveFeed(`${periodMinute(e.t)} · ⚽ ${e.text}`,'goal');}else if(['FOUL','CORNER','FREE_KICK','OFFSIDE'].includes(e.type)){$('heroEventLog').innerHTML+=`<div class="setpiece-event"><strong>${Math.floor(e.t/60)+1}' · ${e.text}</strong></div>`;pushLiveFeed(`${periodMinute(e.t)} · ${e.text}`);}}}
function handleSearchBoundary(r){
  if(r.status==='FINISHED'){completeMatchPresentation();return true}
  beforeHybrid=H.snapshot(world);activeBoundary=deep(r.boundary);
  if(r.boundary?.type==='SET_PIECE_2D_WINDOW'){
    opened=A.runSetPieceWindow(r.boundary,{seed:`${seed()}-${r.boundary.sceneId}-SETPIECE`,durationSeconds:12});
    const d=setPieceReplayDecision(opened,r.boundary),who=r.boundary.setPiece?.team===(world.opts?.heroTeam||'HOME')?'우리 팀':'상대 팀',kind=r.boundary.setPiece?.kind==='CORNER'?'코너킥':'프리킥',min=Math.floor(r.boundary.atSecond/60)+1,summary=setPieceSummary(opened,r.boundary);
    if(opened.pending){session=opened.state;selectedStepResults=[];const rep=P.latestReplay(session);$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>${min}' · ${kind} 이후 주인공이 공을 소유</strong> · AI 행동 전에 사용자 선택으로 전환</div>`;phase='SCENE_NOTICE';showSceneNotice(`${periodMinute(session.m.time)} · 세트피스 이후 주인공 선택 상황`,()=>{if(phase==='SCENE_NOTICE')startReplay(rep,'CHOICE','세트피스 → 선택 직전 실제 경기')});return true}
    if(!d.show){$('heroEventLog').innerHTML+=`<div class="setpiece-event"><strong>${min}' · ${who} ${summary}</strong> · 자동 진행</div>`;opened.suppressNotables=true;finishSetPieceHighRes();return true}
    const frames=causalFramesForEvent(opened.frames,d.eventT,9,4);$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>⚽ ${min}' · ${who} ${kind}</strong> · 득점으로 이어져 실제 2D 표시</div>`;startReplay(frames,'SETPIECE_HANDOFF',`${kind} → 득점 실제 장면`);return true
  }
  if(r.boundary?.type==='FINAL_2D_WINDOW'){finalHighRes=A.runFinalWindow(r.boundary,{seed:`${seed()}-FINAL`,targetSecond:world.durationSeconds||5400});opened=finalHighRes;startReplay(finalHighRes.frames,'FINAL_HANDOFF','경기 종료 직전 실제 흐름');return true}
  opened=A.runToChoice(r.boundary,{seed:`${seed()}-${r.boundary.sceneId}`,minPreSeconds:5,maxSearchSeconds:35});
  if(opened.pending){session=opened.state;selectedStepResults=[];const rep=P.latestReplay(session),since=Number(opened.entrySnapshot?.time??r.boundary.atSecond)-.001,preEvents=(session.m.events||[]).filter(e=>e.t>=since);appendHighResNotables(preEvents);$('heroEventLog').innerHTML+=`<div>${Math.floor(r.boundary.atSecond/60)+1}' · Hybrid가 ${r.boundary.reason} 구간을 V0.6에 인계<br>${Math.floor(session.m.time/60)+1}' · V0.6이 실제 선택 상태 발견</div>`;const notice=`${periodMinute(session.m.time)} · ${r.boundary.reason==='ATTACKING_INVOLVEMENT'?'공격 전개에서 주인공 선택 상황':r.boundary.reason==='DEFENSIVE_TRANSITION'?'수비 전환에서 주인공 선택 상황':'주인공이 개입할 선택 상황'}`;phase='SCENE_NOTICE';showSceneNotice(notice,()=>{if(phase==='SCENE_NOTICE')startReplay(rep,'CHOICE','선택 직전 실제 경기')});return true}
  const out=A.finishWithoutChoice(opened),goal=(out.actualEvents||[]).find(e=>e.type==='GOAL');
  if(goal){deferredHandback=out;out.entrySnapshot=deep(opened.entrySnapshot);const heroInvolved=eventMentionsHero(out.actualEvents||[],opened),brief=nonHeroBrief()&&!heroInvolved,frames=causalFramesForEvent(out.episodeFrames||opened.frames,goal.t,8,3.5),label=heroInvolved?'주인공 관여 득점 장면':'주인공 비관여 득점 장면';if(brief){$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>⚽ ${Math.floor(goal.t/60)+1}' · ${label}</strong> · 간략 보기</div>`;finishNoChoiceHighRes();return true}$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>⚽ ${Math.floor(goal.t/60)+1}' · ${label}</strong> · 실제 원인부터 2D 표시</div>`;startReplay(frames,'NOCHOICE_HANDOFF',`${heroInvolved?'주인공 관여':'비관여'} 득점 · 실제 원인 장면`);return true}
  appendHighResNotables(out.actualEvents||[]);H.resumeFromHighRes(world,out);flushHybridNotables();beforeHybrid=null;activeBoundary=null;opened=null;return false;
}
function showGoalNoticeQueue(goals,r,ix=0){if(ix>=goals.length){phase='SEARCHING';if(!handleSearchBoundary(r))searchHybrid();return}phase='GOAL_NOTICE';const g=goals[ix],sc=g.detail?.score||world.state.score,who=g.team===(world.opts?.heroTeam||'HOME')?'우리 팀 득점':'상대 팀 득점',scorer=hybridName(g.detail?.actorId);$('heroPlayback').textContent=`⚽ ${Math.floor(g.t/60)+1}' · ${who} · ${sc.HOME}-${sc.AWAY} · 경기 진행 일시 강조`;$('heroState').textContent='GOAL NOTICE · 득실점 확인';showGoalAlert({minute:Math.floor(g.t/60)+1,team:g.team,score:sc,scorer,detail:`${scorer} · ${who}`},2400,()=>{if(phase==='GOAL_NOTICE')showGoalNoticeQueue(goals,r,ix+1)});}
function searchHybrid(){if(phase!=='SEARCHING')return;let guard=0;while(guard++<12){const r=H.advanceUntilBoundary(world),goals=flushHybridNotables();if(goals.length){showGoalNoticeQueue(goals,r);return}if(handleSearchBoundary(r))return}setTimeout(searchHybrid,0)}
function start(){if(['CHOICE','RESULT_PLAYBACK','EPISODE_CONTINUATION','RESULT_REVIEW','PRE_REPLAY','SCENE_BREAK','GOAL_NOTICE','SCENE_NOTICE'].includes(phase))return;phase='SEARCHING';$('heroPlayback').textContent='Hybrid 경기 진행 · 실제 관여 구간 탐색';searchHybrid()}
function download(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
function loop(ts){const real=Math.min(.08,(ts-last)/1000);last=ts;if(phase==='PRE_REPLAY'&&replayList.length)processReplay(real);else if(phase==='RESULT_PLAYBACK'&&session)processResult(real);else if(phase==='EPISODE_CONTINUATION'&&session)processEpisodeContinuation(real);requestAnimationFrame(loop)}
if($('heroReturnLatest'))$('heroReturnLatest').onclick=()=>{if(replayReturn==='HISTORY'&&phase==='PRE_REPLAY')restoreLatestAfterReplay();};$('heroStart').onclick=start;$('heroReset').onclick=setup;$('heroNewSeed').onclick=()=>{trial++;setup()};$('heroPlayer').onchange=setup;$('heroReplayBefore').onclick=()=>session&&startReplay(P.latestReplay(session),'CHOICE','선택 직전 실제 경기');$('heroReplayEpisode').onclick=()=>{if(!session)return;const ep=activeEpisodeId(),f=ep?P.episodeReplay(session,ep):[];if(f.length)startReplay(f,'RESULT','전체 상황 다시보기')};$('heroContinue').onclick=continueAfterResult;$('heroDownloadScene').onclick=()=>{const d=session&&activeBoundary?makeIntegratedDebug():latestIntegratedDebug;if(d)download(d,session&&activeBoundary?'FLR_HYBRID_CURRENT_EPISODE.json':'FLR_HYBRID_LATEST.json')};$('heroCopyDebug').onclick=()=>navigator.clipboard?.writeText($('heroDebugSummary').textContent);$('heroShowOffside').onchange=()=>session&&draw(E.snapshot(session.m));setup();requestAnimationFrame(loop);
})();
