(function(){'use strict';
const E=window.FLRPG_CONTINUOUS_CORE,P=window.FLRPG_PROTAGONIST_MATCH_CONTROLLER,H=window.FLRPG_LIVE_HYBRID_SESSION_V02,A=window.FLRPG_LIVE_V06_SCENE_AUTHORITY,X=window.FLRPG_HYBRID_SCENE_DEBUG,F=window.FLRPG_FULL_TIME_PRESENTATION,I=window.FLRPG_IN_PITCH_CHOICE_UI,$=id=>document.getElementById(id),canvas=$('heroPitch'),ctx=canvas.getContext('2d');
let trial=1,world=null,session=null,opened=null,beforeHybrid=null,activeBoundary=null,phase='IDLE',last=performance.now(),acc=0,prev=null,curr=null,replayList=[],replayCursor=0,replayReturn='CHOICE',longPressTimer=null,latestIntegratedDebug=null,episodeHistory=[],selectedStepResults=[],finalHighRes=null,hybridEventCursor=0,deferredHandback=null,goalAlertTimer=null,pitchChoice=null,autoAdvanceTimer=null,autoAdvanceInterval=null,sceneNoticeTimer=null,replayResumePhase=null,notableSeen=new Set(),lastFeedEventKey=null,bugDebugOverride=null,recentCompletedSituations=[],offsideReview=null,developerScenarioActive=null,developerScenarioLast=null,developerSeedByKey={};const STEP=.10,REPLAY_SPEED=2;let replayRate=REPLAY_SPEED;
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v)),lerp=(a,b,t)=>a+(b-a)*t;
function projectPitchPlayer(p){const stage=canvas.closest('.pitch-stage'),cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect(),padX=28,padY=24,fw=canvas.width-padX*2,fh=canvas.height-padY*2,cx=padX+(p.x/105)*fw,cy=padY+(p.y/68)*fh;return{x:(cr.left-sr.left)+(cx/canvas.width)*cr.width,y:(cr.top-sr.top)+(cy/canvas.height)*cr.height}}
function ensurePitchChoice(){if(pitchChoice||!I)return pitchChoice;pitchChoice=I.createController({stageElement:canvas.closest('.pitch-stage'),canvas,getHeroId:()=>$('heroPlayer').value,projectPlayer:projectPitchPlayer,onChoose:(id,targetId,meta)=>choose(id,targetId,meta)});return pitchChoice}
function angleLerp(a,b,t){if(!Number.isFinite(a))return b;if(!Number.isFinite(b))return a;let d=(b-a)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return a+d*t;}/* FLR_DISCONTINUITY_SNAP_V1: compressed restart/setup relocation is a scene cut, never a 600m/s sprint. */function interp(a,b,t){if(!a)return b;const pm=Object.fromEntries((a.players||[]).map(p=>[p.id,p])),jump=(q,p)=>Math.hypot((p.x||0)-(q.x||0),(p.y||0)-(q.y||0))>3.2,ballJump=Math.hypot((b.ball?.x||0)-(a.ball?.x||0),(b.ball?.y||0)-(a.ball?.y||0))>4.0;return{...b,ball:ballJump?{...b.ball}:{...b.ball,x:lerp(a.ball.x,b.ball.x,t),y:lerp(a.ball.y,b.ball.y,t),z:lerp(a.ball.z||0,b.ball.z||0,t)},players:(b.players||[]).map(p=>{const q=pm[p.id]||p;if(jump(q,p))return{...p};return{...p,x:lerp(q.x,p.x,t),y:lerp(q.y,p.y,t),bodyAngle:angleLerp(q.bodyAngle,p.bodyAngle,t),faceTargetAngle:angleLerp(q.faceTargetAngle,p.faceTargetAngle,t)}})}}
function offsideLine(s,team,includeGK=true){const opp=(s.players||[]).filter(p=>p.team!==team&&(includeGK||p.role!=='GK')).map(p=>p.x).sort((a,b)=>a-b);if(opp.length<2)return null;return team==='HOME'?opp[opp.length-2]:opp[1]}
function offsideThreshold(s,team){const second=offsideLine(s,team,true),bx=Number(s?.ball?.x);if(second==null||!Number.isFinite(bx))return second;return team==='HOME'?Math.max(52.5,bx,second):Math.min(52.5,bx,second);}
function drawLineX(px,padY,fh,x,label,stroke){ctx.save();ctx.strokeStyle=stroke;ctx.fillStyle=stroke;ctx.setLineDash([8,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px(x),padY);ctx.lineTo(px(x),padY+fh);ctx.stroke();ctx.setLineDash([]);ctx.font='11px system-ui';ctx.fillText(label,Math.min(canvas.width-90,px(x)+5),padY+15);ctx.restore()}
function offsideEvidenceFromScene(sc){const releases=sc?.passReleases||[];const rel=[...releases].reverse().find(x=>x.engineWouldFlag)||releases.at(-1);if(!rel||!Number.isFinite(Number(rel.engineOffsideLine)))return null;const team=rel.attackingTeam||'HOME',ballX=Number(rel.ballX),second=Number(rel.engineOffsideLine),line=Number.isFinite(ballX)&&Number.isFinite(second)?(team==='HOME'?Math.max(52.5,ballX,second):Math.min(52.5,ballX,second)):second;return{line,reference:Number.isFinite(Number(rel.referenceSecondLastOpponentLine))?Number(rel.referenceSecondLastOpponentLine):null,attackingTeam:team,releaseAt:Number(rel.at||0),targetId:rel.targetId||null};}
function sceneOffsideEvidence(){return offsideEvidenceFromScene(session?.currentScene||null);}
function resultOffsideEvidence(){if(!session?.lastResult||session.lastResult.code!=='OFFSIDE')return null;const sc=session.lastResult.sceneId?P.sceneById(session,session.lastResult.sceneId):session.currentScene;return offsideEvidenceFromScene(sc);}
function resultReplayFrames(){if(!session?.lastResult)return[];const ep=activeEpisodeId();let rows=ep?P.episodeReplay(session,ep):[];if(rows?.length)return rows;const sc=session.lastResult.sceneId?P.sceneById(session,session.lastResult.sceneId):null;rows=[...(sc?.preFrames||[]),...(sc?.postFrames||[])];const seen=new Set();return rows.filter(f=>{const k=Number(f?.time).toFixed(3);if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>Number(a.time)-Number(b.time));}
function clearOffsideReview(){offsideReview=null;}
function draw(s){if(!s)return;const W=canvas.width,Hh=canvas.height,padX=28,padY=24,fw=W-padX*2,fh=Hh-padY*2,px=v=>padX+v/105*fw,py=v=>padY+v/68*fh;ctx.clearRect(0,0,W,Hh);ctx.fillStyle='#315b37';ctx.fillRect(0,0,W,Hh);ctx.strokeStyle='rgba(240,255,242,.78)';ctx.lineWidth=3;ctx.strokeRect(padX,padY,fw,fh);ctx.beginPath();ctx.moveTo(px(52.5),padY);ctx.lineTo(px(52.5),padY+fh);ctx.stroke();ctx.beginPath();ctx.arc(px(52.5),py(34),9.15/105*fw,0,Math.PI*2);ctx.stroke();ctx.strokeRect(px(0),py(13.84),px(16.5)-px(0),py(54.16)-py(13.84));ctx.strokeRect(px(88.5),py(13.84),px(105)-px(88.5),py(54.16)-py(13.84));
  const gy1=py(E.FIELD?.GOAL_Y1??30.34),gy2=py(E.FIELD?.GOAL_Y2??37.66),depth=15;ctx.save();ctx.strokeStyle='rgba(250,255,250,.95)';ctx.lineWidth=3;ctx.strokeRect(padX-depth,gy1,depth,gy2-gy1);ctx.strokeRect(padX+fw,gy1,depth,gy2-gy1);ctx.lineWidth=1;ctx.globalAlpha=.42;for(let k=1;k<4;k++){const xx=padX-depth+k*depth/4;ctx.beginPath();ctx.moveTo(xx,gy1);ctx.lineTo(xx,gy2);ctx.stroke();const xr=padX+fw+k*depth/4;ctx.beginPath();ctx.moveTo(xr,gy1);ctx.lineTo(xr,gy2);ctx.stroke();}ctx.restore();
  const forcedOffside=offsideReview&&((phase==='RESULT_PLAYBACK')||(phase==='RESULT_REVIEW')||(phase==='PRE_REPLAY'&&Number(s.time)>=Number(offsideReview.releaseAt||0)-.15));if(forcedOffside){drawLineX(px,padY,fh,offsideReview.line,'OFFSIDE THRESHOLD','#ff9b85');if(offsideReview.reference!=null&&Math.abs(offsideReview.reference-offsideReview.line)>.12)drawLineX(px,padY,fh,offsideReview.reference,'2ND OPPONENT','#7dd3fc');}else if($('heroShowOffside').checked){const atk=s.ball?.lastTouchTeam||s.possession||'HOME',en=offsideThreshold(s,atk),rf=offsideLine(s,atk,true);if(en!=null)drawLineX(px,padY,fh,en,'OFFSIDE THRESHOLD','#ff9b85');if(rf!=null&&Math.abs(rf-en)>.12)drawLineX(px,padY,fh,rf,'2ND OPPONENT','#7dd3fc');}const mobileView=typeof window!=='undefined'&&window.matchMedia&&window.matchMedia('(max-width:760px)').matches;for(const p of s.players||[]){const focus=p.id===$('heroPlayer').value,isGK=p.role==='GK',a=Number.isFinite(p.bodyAngle)?p.bodyAngle:(p.team==='HOME'?0:Math.PI),cx=px(p.x),cy=py(p.y),r=mobileView?(focus?18:14.25):(focus?14:11);ctx.save();if(focus){const rr=mobileView?41:42,spread=.56;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,rr,a-spread,a+spread);ctx.closePath();ctx.fillStyle='rgba(99,214,255,.12)';ctx.fill();ctx.strokeStyle='rgba(99,214,255,.46)';ctx.lineWidth=1.5;ctx.stroke();}ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*(mobileView?(focus?24:19):(focus?22:14)),cy+Math.sin(a)*(mobileView?(focus?24:19):(focus?22:14)));ctx.strokeStyle=focus?'rgba(99,214,255,.95)':'rgba(255,255,255,.58)';ctx.lineWidth=focus?3:2;ctx.stroke();ctx.restore();ctx.beginPath();ctx.fillStyle=p.team==='HOME'?(isGK?'#7dd3fc':'#2563eb'):(isGK?'#fca5a5':'#dc2626');ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();if(focus){ctx.strokeStyle='rgba(0,0,0,.95)';ctx.lineWidth=mobileView?7:7;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.98)';ctx.lineWidth=mobileView?4:4;ctx.stroke();}else{ctx.strokeStyle='rgba(255,255,255,.88)';ctx.lineWidth=mobileView?2.3:2;ctx.stroke();}ctx.fillStyle='#fff';ctx.font=`bold ${mobileView?(focus?13:11):(focus?10:8)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.slot||p.role,cx,cy+.5)}const b=s.ball,bx=px(b.x),by=py(b.y),br=7+Math.min(4,(b.z||0)*1.5);ctx.save();ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#0b1116';ctx.lineWidth=2.4;ctx.arc(bx,by,br,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#101820';ctx.beginPath();ctx.arc(bx,by,Math.max(2.2,br*.31),0,Math.PI*2);ctx.fill();for(let k=0;k<5;k++){const a=-Math.PI/2+k*Math.PI*2/5;ctx.beginPath();ctx.arc(bx+Math.cos(a)*br*.61,by+Math.sin(a)*br*.61,Math.max(1.15,br*.13),0,Math.PI*2);ctx.fill();}ctx.restore()}
function roleInfo(){const id=$('heroPlayer').value;return{id,role:id==='H-ST'?'ST':id==='H-GK'?'GK':id==='H-LCB'?'CB':'CM'}}function seed(){return`LIVE-V03-${trial}-${$('heroPlayer').value}`}
const DEV_RECENT_GUIDES={
 FORMATION_CONTINUITY:{label:'선택 장면 공간·포메이션 연속성',watch:'지공인데 ST만 CM선에 고립되거나, 상대 ST/WF가 장면 시작 뒤늦게 수비 위치를 찾아가거나, 달리는 방향과 몸 방향이 반대로 보이는지 봅니다.',normal:'정상: 22명의 위치·속도·몸 방향이 같은 경기 시간축에서 이어집니다. ST가 중원에 있으면 역습·윙어·상대 수비라인 등 전체 상황이 이유를 설명하고, 수비 중 공격진도 장면 시작 전에 이미 블록에 연결됩니다.'},
 DEFENSIVE_ROLE_STABILITY:{label:'선택 시작 전 측면 마킹·압박',watch:'풀백이 같은 측면 윙어를 두고 갑자기 다른 공 소유자를 압박하러 나가거나, 추적 중 공격수 바깥쪽으로 교차해 넘어가는지 봅니다.',normal:'정상: 풀백은 실제 위협 윙어의 책임을 유지하면서 goal-side/inside-side에서 함께 움직입니다. 공 소유자가 바뀌었다는 이유만으로 살아 있는 측면 위협을 버리지 않습니다.'},
 MARK_TARGET_STABILITY:{label:'CB 마킹·커버 전환 안정성',watch:'CB가 짧은 시간에 MARK/COVER/RECOVERY 같은 책임을 계속 갈아타며 중앙을 버리거나 좌우로 헤매는지 봅니다.',normal:'정상: 일반 패스 한 번마다 책임을 초기화하지 않고 마킹 CB와 커버 CB의 역할이 의미 있는 상황 변화 전까지 이어집니다. 실제 침투·박스 진입·인계가 필요할 때만 자연스럽게 전환합니다.'},
 CARRY_CONTINUITY:{label:'공 운반 속도 맥동 방지',watch:'전진 드리블 중 짧은 내부 목표점마다 달리기 속도가 툭툭 줄었다가 다시 올라가는 톱니형 움직임이 보이는지 봅니다.',normal:'정상: 같은 전진 의도와 비슷한 방향이 유지되면 공 터치 주기와 별개로 신체 이동 속도는 연속적으로 이어지고, 접촉·급회전·실제 운반 종료에서만 크게 감속합니다.'},
 ST_SHOT_VISIBILITY:{label:'노마크 ST 러닝 슈팅·골문 앞 전진',watch:'러닝 슈팅이 늦게 열리거나, GK와 아주 가까워 실제 전진 공간이 없는데 공간으로 전진이 뜨거나 그 선택이 뒤로 움직이는지 봅니다.',normal:'정상: 명백한 찬스에서는 달리는 흐름 그대로 SHOT이 열리고, 골문 바로 앞 중앙에서 의미 없는 CARRY는 숨겨집니다. 어떤 경로의 CARRY도 공격 방향 반대로 목표를 만들지 않습니다.'},
 PASS_FLIGHT_WIDE_TRACK:{label:'패스 비행 중 풀백 측면 추적',watch:'측면 전진 패스를 선택한 뒤 공이 비행하는 동안 담당 풀백이 침투자를 놓고 멈추거나 중앙으로 풀리는지 봅니다.',normal:'정상: 공 소유자가 사라지는 FLIGHT 순간에도 intended receiver를 위협으로 이어 받아 추적합니다.'},
 STRIKER_RUN_LANE:{label:'ST 침투 레인 연속성',watch:'측면 전개 중 ST가 중앙·니어·파포스트 목표를 너무 자주 바꾸며 좌우 왕복하는지 봅니다.',normal:'정상: 공격 의도는 잠깐 유지되고, 실제 전개 변화가 있을 때만 새 레인으로 전환합니다.'},
 CARRIER_SHIELD_FLOW:{label:'공격수 멈칫 반복 방지',watch:'ST가 공을 지킨 뒤 같은 자리에서 SHIELD_SCAN/멈춤을 반복하는지 봅니다.',normal:'정상: 짧게 스캔한 뒤 패스·드리블·보호 등 다음 실제 판단으로 이어집니다.'},
 GK_PHASE2_PLAUSIBILITY_CATCH:{label:'GK Phase2 · 쉬운 슛 캐칭',watch:'멀리서 비교적 느리고 중앙으로 오는 명백히 쉬운 슛을 골키퍼가 괜히 펀칭하거나 옆으로 쳐내지 않는지 봅니다.',normal:'정상: 준비된 골키퍼가 공을 안정적으로 CATCH하고 소유권을 확보합니다. 이 항목은 TEST_ONLY 고정 상황에서 실제 Phase2 resolver를 실행합니다.'},
 GK_PHASE2_PLAUSIBILITY_SAFE:{label:'GK Phase2 · 측면 안전 패링',watch:'잡기에는 까다로운 슛을 막았을 때 공이 골문 중앙 앞으로 떨어지지 않고 측면·바깥쪽으로 빠지는지 봅니다.',normal:'정상: PARRY_SAFE 후 공이 측면 안전지대로 빠집니다. 선방 이후 소유권은 미리 정하지 않습니다.'},
 GK_PHASE2_PLAUSIBILITY_DANGER:{label:'GK Phase2 · 위험한 세컨드볼',watch:'강하고 가까운 어려운 슛에서 가끔 완전히 처리하지 못해 공이 전방·중앙으로 흘러 실제 세컨드볼이 되는지 봅니다.',normal:'정상: PARRY_DANGER 후 LOOSE BALL이 실제로 계속 움직입니다. 누가 세컨드볼을 차지할지는 선결정하지 않습니다.'},
 OFFSIDE_INVOLVEMENT:{label:'오프사이드 실제 관여 시점',watch:'오프사이드 위치는 패스가 출발한 순간 기준인지, 판정 연출은 실제 공 관여 시점에 나타나는지 봅니다.',normal:'정상: 위치 판정 기준은 release 순간에 고정되고, 휘슬은 실제 관여가 확인될 때 표시됩니다.'}
};
const DEV_RECENT_VISIBLE_KEYS=['DEFENSIVE_ROLE_STABILITY','MARK_TARGET_STABILITY','FORMATION_CONTINUITY','GK_PHASE2_PLAUSIBILITY_CATCH','GK_PHASE2_PLAUSIBILITY_SAFE','GK_PHASE2_PLAUSIBILITY_DANGER'];
function selectedRecentFixKey(){const sel=$('heroRecentFixSelect');return sel?.value||'FORMATION_CONTINUITY';}
function renderRecentFixGuide(){const key=selectedRecentFixKey(),g=DEV_RECENT_GUIDES[key]||DEV_RECENT_GUIDES.FORMATION_CONTINUITY,box=$('heroRecentFixGuide');if(box)box.innerHTML=`<strong>${g.label}</strong><br><span>무엇을 볼지: ${g.watch}</span><br><span class="muted">${g.normal}</span>`;}
const GK_PHASE2_DEBUG_CASES={
 GK_PHASE2_PLAUSIBILITY_CATCH:{seed:'GKDBG-CATCH-1',label:'GK Phase2 · 쉬운 슛 캐칭',expected:'CATCH',distance:22,speed:18,offset:0,gk:60,handling:60,instruction:'슈팅이 실제로 날아온 뒤 쉬운 공을 안정적으로 잡는지 확인합니다.'},
 GK_PHASE2_PLAUSIBILITY_SAFE:{seed:'GKDBG-SAFE-1',label:'GK Phase2 · 측면 안전 패링',expected:'PARRY_SAFE',distance:19,speed:23,offset:3.0,gk:60,handling:50,instruction:'슈팅을 막은 뒤 공이 실제로 측면 안전지대로 빠지는지 확인합니다.'},
 GK_PHASE2_PLAUSIBILITY_DANGER:{seed:'GKDBG-DANGER-5',label:'GK Phase2 · 위험한 세컨드볼',expected:'PARRY_DANGER',distance:14,speed:27,offset:2.0,gk:42,handling:55,instruction:'어려운 슛을 쳐낸 뒤 공이 실제 전방·중앙 세컨드볼로 계속 움직이는지 확인합니다.'}
};
function runGkPhase2DebugScenario(key){
 const c=GK_PHASE2_DEBUG_CASES[key];if(!c)return false;
 clearAutoAdvance();clearTimeout(sceneNoticeTimer);clearOffsideReview();ensurePitchChoice()?.hide();focusPitch();
 const m=E.createMatch(c.seed,{dt:.05}),B=E.choiceActionBridge();m.time=100;m.restart=null;m.phase='OPEN_PLAY';m.nextShape=9999;m.events=[];m.score={HOME:0,AWAY:0};m.possession='HOME';m.playerAbilityProfiles={};
 const st=m.playersById['H-ST'],gk=m.playersById['A-GK'];if(!st||!gk){if($('heroRecentFixStatus'))$('heroRecentFixStatus').textContent='GK 강제 검증 준비 실패 · 필요한 ST/GK를 찾지 못했습니다.';return true;}
 for(const p of m.players){p.hasBall=false;p.nextThink=9999;p.vx=p.vy=0;if(p.role!=='GK'){p.x=70+(p.slot.includes('L')?0:1);p.y=p.slot.includes('L')?7:p.slot.includes('R')?61:54;p.tx=p.x;p.ty=p.y;}}
 const shotX=105-c.distance;Object.assign(st,{x:shotX,y:34,tx:shotX,ty:34,bodyAngle:0,faceTargetAngle:0,nextThink:9999});
 const gkY=34+(c.offset?Math.sign(c.offset)*Math.min(1.8,Math.abs(c.offset)*.45):0);Object.assign(gk,{x:99.5,y:gkY,tx:99.5,ty:gkY,vx:0,vy:0,bodyAngle:Math.PI,action:'GK_SAVE_SET',tacticalTask:'GK_SAVE_SET',nextThink:9999});
 m.playerAbilityProfiles[gk.id]={reaction:c.gk,gk_positioning:c.gk,diving:c.gk,handling:c.handling};
 B.setControlled(m,st,true);const frames=[deep(E.snapshot(m))];
 B.executeShot(m,st,'DEV_GK_PHASE2',{releaseNow:true,decisionOrientation:{turningRequired:false,backToGoal:false,facingAlignment:1,bodyAngleDiff:0}});
 const tx=105,ty=34+c.offset,dx=tx-m.ball.x,dy=ty-m.ball.y,n=Math.hypot(dx,dy)||1;Object.assign(m.ball,{kind:'SHOT',mode:'FLIGHT',ownerId:null,z:.08,vx:dx/n*c.speed,vy:dy/n*c.speed,vz:0,age:0,originX:shotX,originY:34,targetX:tx,targetY:ty,shotTargetY:ty,shotTeam:'HOME',lastTouchTeam:'HOME',lastTouchPlayer:'H-ST',onTarget:true,shotDistance:c.distance,shotOneVOne:false,shotClearKeeperChance:false,airborne:false,strikeStyle:'POWER',arcProfile:null,npcGkResolved:null});m.lastTouchTeam='HOME';m.lastTouchPlayer='H-ST';frames.push(deep(E.snapshot(m)));
 let outcomeEvent=null,tail=0;for(let i=0;i<100;i++){E.step(m,.05);frames.push(deep(E.snapshot(m)));if(!outcomeEvent)outcomeEvent=[...(m.events||[])].reverse().find(e=>e?.npcGkOutcome);if(outcomeEvent){tail++;const need=outcomeEvent.npcGkOutcome==='CATCH'?12:30;if(tail>=need)break;}}
 const actual=outcomeEvent?.npcGkOutcome||null;developerScenarioActive={key,label:c.label,instruction:c.instruction,seed:c.seed};developerScenarioLast={key,label:c.label,instruction:c.instruction,seed:c.seed,highResSeed:c.seed,frames:deep(frames),debug:null};latestIntegratedDebug=null;session=null;opened=null;activeBoundary=null;beforeHybrid=null;world=null;selectedStepResults=[];phase='SEARCHING';
 $('heroPlayer').value='H-ST';if($('heroRecentFixSelect'))$('heroRecentFixSelect').value=key;renderRecentFixGuide();$('heroPlayback').textContent=`개발자 강제 검증 · ${c.label}`;$('heroState').textContent='V34 GK Phase2 TEST_ONLY · 슈팅부터 실제 resolver 재생';
 const status=actual===c.expected?`이번 검증: ${c.label} · 실제 결과 ${actual} · ${c.instruction}`:`강제 검증 불일치 · 기대 ${c.expected} / 실제 ${actual||'NONE'} · 이 장면은 정상 판정에 사용하지 마세요.`;if($('heroRecentFixStatus'))$('heroRecentFixStatus').textContent=status;
 $('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>GK Phase2 강제 검증 · ${c.label}</strong> · 기대 ${c.expected} / 실제 ${actual||'NONE'}<br><small>TEST_ONLY 고정 QA seed=${c.seed} · 슈팅 시작 → GK 처리 → 후속 공 움직임까지 runtime 직접 실행</small></div>`;$('heroDebugSummary').textContent=`DEV ${key}\nseed=${c.seed}\nexpected=${c.expected}\nactual=${actual||'NONE'}\nvisualReplay=SHOT_TO_GK_OUTCOME\nTEST_ONLY=true`;if($('heroRecentFixReplay'))$('heroRecentFixReplay').disabled=!frames.length;
 if(actual!==c.expected){developerScenarioActive=null;phase='IDLE';draw(frames.at(-1));renderMeta(frames.at(-1));return true;}startReplay(frames,'DEV_SCENARIO',`${c.label} · 슈팅부터 강제 재현`,1);return true;
}
function clearAutoAdvance(){clearTimeout(autoAdvanceTimer);clearInterval(autoAdvanceInterval);autoAdvanceTimer=autoAdvanceInterval=null;const x=$('heroAutoNext');if(x)x.textContent='';const n=$('heroSceneNotice');if(n?.classList.contains('end-countdown')){n.hidden=true;n.classList.remove('end-countdown');}}
function periodMinute(t){const sec=Math.max(0,Number(t)||0),m=Math.floor(sec/60)+1;return sec<2700?`전반 ${Math.min(45,m)}분`:`후반 ${Math.max(1,Math.min(45,m-45))}분`;}
function pushLiveFeed(text,kind=''){const box=$('heroLiveFeed');if(!box||!text)return;const row=document.createElement('div');row.className=`live-feed-row ${kind}`.trim();row.textContent=text;box.appendChild(row);while(box.children.length>3)box.removeChild(box.firstChild);}
function showSceneNotice(text,done=null,duration=1100){const box=$('heroSceneNotice');clearTimeout(sceneNoticeTimer);if(!box){if(done)setTimeout(done,0);return;}box.textContent=text;box.hidden=false;pushLiveFeed(text,'scene');sceneNoticeTimer=setTimeout(()=>{box.hidden=true;if(done)done();},duration);}
function scheduleAutoAdvance(text,seconds=3,next=null){clearAutoAdvance();let left=Math.max(1,Math.floor(seconds)),notice=$('heroSceneNotice'),box=$('heroAutoNext');const render=()=>{const msg=`${text}\n${left}초 후 다음 플레이로 이동합니다.`;if(notice){notice.textContent=msg;notice.classList.add('end-countdown');notice.hidden=false;}if(box)box.textContent='자동으로 다음 플레이로 이동합니다.';};render();autoAdvanceInterval=setInterval(()=>{left--;if(left>0){render();return;}clearAutoAdvance();if(next)next();},1000);}
function setup(){ensurePitchChoice()?.hide();clearAutoAdvance();clearTimeout(sceneNoticeTimer);clearOffsideReview();developerScenarioActive=null;notableSeen=new Set();lastFeedEventKey=null;const h=roleInfo();world=H.createSession({seed:seed(),heroTeam:'HOME',heroRole:h.role,heroPlayerId:h.id});session=null;opened=null;activeBoundary=null;beforeHybrid=null;selectedStepResults=[];finalHighRes=null;deferredHandback=null;phase='IDLE';latestIntegratedDebug=null;episodeHistory=[];recentCompletedSituations=[];$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;$('heroClock').textContent="0'";$('heroScore').textContent='0 - 0';$('heroPlayback').textContent='대기 · Hybrid';$('heroState').textContent=`${h.role} · 저해상도 경기 시작 전`;$('heroEventLog').textContent='경기 시작 대기';$('heroPauseCount').textContent='선택 0회';$('heroSceneHistory').innerHTML='<div class="muted">아직 선택 장면이 없습니다.</div>';$('heroDownloadScene').disabled=true;$('heroBugReport').disabled=true;$('heroCopyDebug').disabled=true;$('heroDebugSummary').textContent='아직 선택 장면 없음';$('heroCommentary').textContent='경기 시작을 기다리고 있습니다.';if($('heroLiveFeed'))$('heroLiveFeed').innerHTML='<div class="live-feed-row">경기 시작을 기다리고 있습니다.</div>';if($('heroSceneNotice')){$('heroSceneNotice').hidden=true;$('heroSceneNotice').classList.remove('end-countdown');}if($('heroReturnLatest'))$('heroReturnLatest').hidden=true;if($('heroRecentFixStatus'))$('heroRecentFixStatus').textContent='검사할 항목을 선택한 뒤 강제 검증을 시작하세요. 시작 맥락만 강제하며 결과는 선계산하지 않습니다.';if($('heroRecentFixReplay'))$('heroRecentFixReplay').disabled=!developerScenarioLast;renderRecentFixGuide();const ars=$('heroActionResult');if(ars)ars.hidden=true;if($('heroActionResultText'))$('heroActionResultText').textContent='-';hybridEventCursor=0;clearTimeout(goalAlertTimer);const ga=$('heroGoalAlert');if(ga){ga.hidden=true;ga.classList.remove('show','conceded','scored');}draw(E.snapshot(E.createMatch(`${seed()}-KICKOFF-PREVIEW`,{})))}
function renderMeta(s){if(!s)return;const min=Math.min(90,Math.floor((s.time||0)/60)+1);$('heroClock').textContent=`${min}'`;$('heroScore').textContent=`${s.score.HOME} - ${s.score.AWAY}`;$('heroPauseCount').textContent=`선택 ${episodeHistory.reduce((n,e)=>n+(e.choiceCount||0),0)+(session?.choiceHistory?.length||0)}회`;$('heroState').textContent=`${s.phase||'-'} · 공 ${s.ball?.mode||'-'}${s.ball?.ownerId===$('heroPlayer').value?' · 주인공 소유':''}`;const ev=s.lastEvent||[...(s.events||[])].reverse().find(e=>e&&e.type!=='USER_CHOICE'&&e.text);if(ev){$('heroCommentary').textContent=ev.text;const key=`${ev.t??''}|${ev.type??''}|${ev.text}`;if(key!==lastFeedEventKey){lastFeedEventKey=key;pushLiveFeed(`${periodMinute(ev.t??s.time)} · ${ev.text}`,ev.type==='GOAL'?'goal':'');}}}
function focusPitch(){canvas.closest('.pitch-card')?.scrollIntoView({behavior:'smooth',block:'center'});}
function startReplay(frames,ret='CHOICE',title='다시보기',speed=REPLAY_SPEED){if(!frames?.length){if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='CHOICE')showPending();else showResult();return}clearAutoAdvance();clearTimeout(sceneNoticeTimer);const notice=$('heroSceneNotice');if(notice){notice.hidden=true;notice.classList.remove('end-countdown');}if(ret==='HISTORY')replayResumePhase=phase;const latest=$('heroReturnLatest');if(latest)latest.hidden=ret!=='HISTORY';replayList=frames;replayCursor=0;replayReturn=ret;replayRate=Math.max(.5,Number(speed)||REPLAY_SPEED);phase='PRE_REPLAY';ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;$('heroResultPanel').hidden=true;const dur=(frames.at(-1).time-frames[0].time).toFixed(1);$('heroPlayback').textContent=`${title} · ${dur}초 · ${replayRate}×`;draw(frames[0]);renderMeta(frames[0]);last=performance.now()}
function processReplay(real){replayCursor+=real*replayRate;const start=replayList[0].time,end=replayList.at(-1).time,target=Math.min(end,start+replayCursor);let i=0;while(i<replayList.length-1&&replayList[i+1].time<=target)i++;const a=replayList[i],b=replayList[Math.min(i+1,replayList.length-1)],t=Math.min(1,Math.max(0,(target-a.time)/Math.max(.001,b.time-a.time)));const v=interp(a,b,t);draw(v);renderMeta(v);if(target>=end-.001){replayList=[];const ret=replayReturn;if(ret==='CHOICE')showPending();else if(ret==='RESULT')showResult();else if(ret==='HISTORY')restoreLatestAfterReplay();else if(ret==='SETPIECE_HANDOFF')finishSetPieceHighRes();else if(ret==='NOCHOICE_HANDOFF')finishNoChoiceHighRes();else if(ret==='FINAL_HANDOFF')finishFinalHighRes();else if(ret==='FINAL_COMPLETE')completeMatchPresentation();else if(ret==='DEV_SCENARIO')finishDeveloperVisual();else{phase='IDLE';}}}
function clearGoalAlert(){clearTimeout(goalAlertTimer);const box=$('heroGoalAlert');if(box){box.hidden=true;box.classList.remove('show','scored','conceded');}}
function showGoalAlert(ev,s){const box=$('heroGoalAlert');if(!box)return;clearGoalAlert();const scorer=(s.players||[]).find(p=>p.id===ev.actorId),heroTeam=($('heroPlayer').value||'H-ST').startsWith('A-')?'AWAY':'HOME',score=s.score||{},forHero=ev.team===heroTeam;box.classList.add(forHero?'scored':'conceded');$('heroGoalAlertKicker').textContent=forHero?'⚽ 득점!':'⚽ 실점';$('heroGoalAlertScore').textContent=`${periodMinute(ev.t??s.time)} · ${score.HOME??0}-${score.AWAY??0}`;$('heroGoalAlertDetail').textContent=scorer?`${scorer.name}의 골입니다.`:(ev.text||'득점 장면이 발생했습니다.');box.hidden=false;requestAnimationFrame(()=>box.classList.add('show'));goalAlertTimer=setTimeout(clearGoalAlert,4100);}
function eventKey(ev){return`${ev?.t??''}|${ev?.type??''}|${ev?.actorId??''}|${ev?.text??''}`;}
function isMajorEvent(ev){return['GOAL','RED_CARD','PENALTY_AWARDED','PENALTY_GOAL','PENALTY_SAVE'].includes(ev?.type)}
function isSetPieceEvent(ev){return ['CORNER','CORNER_KICK','FREE_KICK','FREE_KICK_TAKEN','THROW_IN','THROW_IN_TAKEN','GOAL_KICK','GOAL_KICK_TAKEN','OFFSIDE','OFFSIDE_RESTART'].includes(ev?.type)}
function rememberCompletedSituation(debugObj,kind='CHOICE'){if(!debugObj)return;recentCompletedSituations.push({kind,at:new Date().toISOString(),debug:deep(debugObj)});if(recentCompletedSituations.length>8)recentCompletedSituations.splice(0,recentCompletedSituations.length-8);}
function previousCompletedSituation(){return recentCompletedSituations.length>1?recentCompletedSituations[recentCompletedSituations.length-2]:null;}
function relevantEvents(s){return(s?.events||[]).filter(e=>!['USER_CHOICE'].includes(e.type));}
function updateNotableEvents(s){for(const ev of relevantEvents(s)){const k=eventKey(ev);if(notableSeen.has(k))continue;notableSeen.add(k);if(isMajorEvent(ev)){showGoalAlert(ev,s);$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>${ev.type}</strong> · ${ev.text}</div>`;}else if(isSetPieceEvent(ev))$('heroEventLog').innerHTML+=`<div class="setpiece-event"><strong>${ev.type}</strong> · ${ev.text}</div>`;}}
function makeFrame(s){return deep(s)}
function processResult(real){acc+=real;while(acc>=STEP&&phase==='RESULT_PLAYBACK'){acc-=STEP;const t=performance.now();const advanced=P.advanceHighRes(session,STEP);if(!advanced)break;const snap=P.currentSnapshot(session),prior=curr;prev=prior||snap;curr=snap;selectedStepResults.push(makeFrame(snap));draw(curr);renderMeta(curr);updateNotableEvents(curr);if(P.resultReady(session)){showResult();break;}if(t-last>100)last=t;}}
function processEpisodeContinuation(real){acc+=real;while(acc>=STEP&&phase==='EPISODE_CONTINUATION'){acc-=STEP;const advanced=P.advanceHighRes(session,STEP);if(!advanced){finishEpisodeContinuation();break;}const snap=P.currentSnapshot(session);prev=curr||snap;curr=snap;selectedStepResults.push(makeFrame(snap));draw(curr);renderMeta(curr);updateNotableEvents(curr);if(P.nextChoiceReady(session)){openNextEpisodeChoice();break;}if(P.resultReady(session)){showResult();break;}}}
function activeEpisodeId(){return session?.activeEpisode?.id||session?.currentScene?.episodeId||session?.lastResult?.episodeId||null;}
function showPending(){phase='CHOICE';$('heroChoicePanel').hidden=false;ensurePitchChoice()?.show(session?.currentDecision||null);renderChoiceButtons();}
function renderChoiceButtons(){const box=$('heroChoiceButtons');box.innerHTML='';const d=session?.currentDecision;if(!d)return;const choices=d.choices||[];for(const c of choices){const b=document.createElement('button');b.textContent=c.label||c.id;b.onclick=()=>choose(c.id,c.targetId||null,{source:'BUTTON'});box.appendChild(b);}}
function choose(id,targetId,meta={}){if(phase!=='CHOICE'||!session)return;const res=P.choose(session,id,targetId,{inputSource:meta.source||'UI'});if(!res?.ok){$('heroPlayback').textContent=`선택 적용 실패 · ${res?.reason||'UNKNOWN'}`;return;}ensurePitchChoice()?.hide();$('heroChoicePanel').hidden=true;phase='RESULT_PLAYBACK';acc=0;selectedStepResults=[];$('heroChoiceReceipt').hidden=false;$('heroChoiceReceiptText').textContent=`${id}${targetId?` → ${targetId}`:''}`;$('heroPlayback').textContent='선택 실행 중 · 실제 2D 결과 생성';}
function showResult(){if(!session?.lastResult)return;phase='RESULT_REVIEW';const r=session.lastResult;$('heroResultPanel').hidden=false;$('heroChoicePanel').hidden=true;ensurePitchChoice()?.hide();$('heroResultHeadline').textContent=r.headline||r.code||'결과';$('heroResultChoice').textContent=`내 선택: ${r.choiceId||'-'}${r.targetId?` → ${r.targetId}`:''}`;$('heroResultDetail').textContent=r.detail||'';$('heroResultEvents').innerHTML=(r.events||[]).map(e=>`<div><strong>${e.type}</strong> · ${e.text||''}</div>`).join('');$('heroPlayback').textContent='선택 결과 확인';latestIntegratedDebug=makeIntegratedDebug();rememberCompletedSituation(latestIntegratedDebug,'CHOICE');$('heroDownloadScene').disabled=false;$('heroBugReport').disabled=false;$('heroCopyDebug').disabled=false;$('heroDebugSummary').textContent=JSON.stringify({result:r.code,choice:r.choiceId,target:r.targetId,episodeId:r.episodeId,futurePrecomputed:false},null,2);}
function continueAfterResult(){if(!session)return;const next=P.continueAfterResult(session);$('heroResultPanel').hidden=true;if(next?.choiceReady){showPending();return;}phase='EPISODE_CONTINUATION';acc=0;$('heroPlayback').textContent='연계 상황 진행';}
function finishEpisodeContinuation(){phase='IDLE';if(session){const hand=P.handBack(session);if(hand?.done){finishHighResAndReturn();return;}}searchHybrid();}
function openNextEpisodeChoice(){if(!session)return;phase='CHOICE';showPending();}
function makeIntegratedDebug(){if(!session)return latestIntegratedDebug;const hb=beforeHybrid?deep(beforeHybrid):null;return X?.build?X.build(hb,activeBoundary,{entrySnapshot:opened?.entrySnapshot||null,frames:selectedStepResults,actualEvents:session?.m?.events?.slice(-30)||[]},{selectedChoice:session?.lastResult?.choiceId||null,choiceSteps:selectedStepResults,actualEvents:session?.lastResult?.events||[],result:session?.lastResult||null,results:session?.resultHistory||[],episodeFrames:resultReplayFrames()},world):{schemaVersion:'FLR_HYBRID_LIVE_SCENE_DEBUG_0.3',futureOutcomePrecomputed:false};}
function searchHybrid(){if(!world)return;for(let i=0;i<900;i++){const r=H.step(world,.25);if(r?.status==='PAUSED'&&r.boundary){handleSearchBoundary(r);return;}if(r?.status==='FULL_TIME'){completeMatchPresentation();return;}}setTimeout(searchHybrid,0);}
function handleSearchBoundary(r){beforeHybrid=H.snapshot(world);activeBoundary=deep(r.boundary);opened=A.open(activeBoundary,{seed:`${seed()}-${activeBoundary.id||Date.now()}`});if(!opened)return false;session=P.create(opened,{heroPlayerId:$('heroPlayer').value});curr=P.currentSnapshot(session);prev=curr;draw(curr);renderMeta(curr);if(P.choiceReady(session)){const pre=P.latestReplay(session);startReplay(pre,'CHOICE','선택 직전 실제 경기');return true;}phase='NOCHOICE_HANDOFF';finishNoChoiceHighRes();return true;}
function finishHighResAndReturn(){if(!session)return;latestIntegratedDebug=makeIntegratedDebug();rememberCompletedSituation(latestIntegratedDebug,'HIGH_RES');const hand=A.handBack(session,world);session=null;opened=null;activeBoundary=null;beforeHybrid=null;phase='IDLE';if(hand?.done){completeMatchPresentation();return;}searchHybrid();}
function finishNoChoiceHighRes(){if(!session){phase='IDLE';return;}const f=P.episodeReplay(session,activeEpisodeId());if(f?.length){startReplay(f,'NOCHOICE_HANDOFF','중요 장면');return;}finishHighResAndReturn();}
function finishSetPieceHighRes(){finishHighResAndReturn();}
function finishFinalHighRes(){finishHighResAndReturn();}
function completeMatchPresentation(){phase='IDLE';$('heroPlayback').textContent='경기 종료';if(world?.state){$('heroScore').textContent=`${world.state.score.HOME} - ${world.state.score.AWAY}`;}}
function restoreLatestAfterReplay(){replayResumePhase=replayResumePhase||'IDLE';phase=replayResumePhase;replayResumePhase=null;if(curr){draw(curr);renderMeta(curr);}if($('heroReturnLatest'))$('heroReturnLatest').hidden=true;if(phase==='CHOICE')showPending();else if(phase==='RESULT_REVIEW')showResult();}
function runDeveloperVisualScenario(d){beforeHybrid=H.snapshot(d.session);activeBoundary=deep(d.boundary);const env=A.runDeveloperVisualWindow(d.boundary,{seed:d.seed,durationSeconds:9}),frames=(env.frames||[]).map(deep);env.frames=frames;const devResolved={selectedChoice:null,choiceSteps:[],actualEvents:deep(env.actualEvents||[]),result:null,results:[],episodeFrames:frames};latestIntegratedDebug=X?.build?X.build(beforeHybrid,activeBoundary,env,devResolved,d.session):{schemaVersion:'FLR_HYBRID_LIVE_SCENE_DEBUG_0.3',hybridBefore:{status:beforeHybrid.status,boundary:deep(activeBoundary),state:deep(activeBoundary.stateSnapshot),preContext:deep(activeBoundary.preContext)},highResolution:{entrySnapshot:deep(env.entrySnapshot),decision:null,selectedChoice:null,choiceSteps:[],postActionFrames:[],actualEvents:deep(env.actualEvents||[]),actualResult:null,actualResults:[],episodeFrames:deep(frames)},hybridAfter:{status:d.session.status,state:deep(d.session.state),lastHighRes:deep(d.session.state.lastHighRes)},futureOutcomePrecomputed:false};rememberCompletedSituation(latestIntegratedDebug,'DEV_VISUAL');developerScenarioLast={key:d.key,label:d.label,instruction:d.instruction,seed:d.seed,highResSeed:d.seed,frames:deep(frames),debug:deep(latestIntegratedDebug)};$('heroDownloadScene').disabled=false;$('heroBugReport').disabled=false;$('heroCopyDebug').disabled=false;$('heroDebugSummary').textContent=`DEV ${d.key}\nseed=${d.seed}\nreportable=true\nfuturePrecomputed=false`;if($('heroRecentFixReplay'))$('heroRecentFixReplay').disabled=false;$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>개발자 시각 검증 · ${d.label}</strong> · ${d.instruction}</div>`;startReplay(frames,'DEV_SCENARIO',`${d.label} · 강제 재현`);}
function finishDeveloperVisual(){const done=developerScenarioActive;developerScenarioActive=null;phase='IDLE';clearOffsideReview();if(done){$('heroPlayback').textContent=`강제 검증 완료 · ${done.label}`;if($('heroRecentFixStatus')&&!String(done.key||'').startsWith('GK_PHASE2_PLAUSIBILITY_'))$('heroRecentFixStatus').textContent=`검증 완료: ${done.label} · seed=${done.seed}`;if($('heroRecentFixReplay'))$('heroRecentFixReplay').disabled=!developerScenarioLast?.frames?.length;$('heroDownloadScene').disabled=!latestIntegratedDebug;$('heroBugReport').disabled=!latestIntegratedDebug;$('heroCopyDebug').disabled=!latestIntegratedDebug;}}
function runRecentFixScenario(key=selectedRecentFixKey(),opts={}){clearAutoAdvance();clearTimeout(sceneNoticeTimer);clearOffsideReview();ensurePitchChoice()?.hide();focusPitch();if(GK_PHASE2_DEBUG_CASES[key]){runGkPhase2DebugScenario(key);return;}const forceNew=opts.newSeed===true,devSeed=forceNew||!developerSeedByKey[key]?`DEV-RECENT-${Date.now()}-${trial++}`:developerSeedByKey[key],d=H.createDeveloperScenario({seed:devSeed,key});developerSeedByKey[key]=d.seed;developerScenarioActive={key:d.key,label:d.label,instruction:d.instruction,seed:d.seed};if($('heroRecentFixSelect'))$('heroRecentFixSelect').value=d.key;renderRecentFixGuide();$('heroPlayer').value=d.boundary.heroPlayerId;world=d.session;session=null;opened=null;activeBoundary=null;beforeHybrid=null;selectedStepResults=[];phase='SEARCHING';if($('heroRecentFixStatus'))$('heroRecentFixStatus').textContent=`이번 검증: ${d.label} · seed=${d.seed} · ${d.instruction}`;$('heroPlayback').textContent=`개발자 강제 검증 · ${d.label}`;$('heroState').textContent='최근 수정 항목 강제 재현 · 결과 선계산 없음';$('heroEventLog').innerHTML+=`<div class="major-match-event"><strong>개발자 검증 · ${d.label}</strong> · ${d.instruction}<br><small>seed=${d.seed} · 시작 맥락만 강제, 이후 V0.6 실제 실행</small></div>`;if(!['PASS_FLIGHT_WIDE_TRACK','OFFSIDE_INVOLVEMENT','ST_SHOT_VISIBILITY'].includes(d.key)){runDeveloperVisualScenario(d);return;}const held=handleSearchBoundary({status:'PAUSED',boundary:d.boundary,state:d.session.state});if(!held&&developerScenarioActive){finishDeveloperVisual();}}
function replayRecentFixScenario(){if(!developerScenarioLast?.frames?.length)return;focusPitch();const gk=String(developerScenarioLast.key||'').startsWith('GK_PHASE2_PLAUSIBILITY_');startReplay(developerScenarioLast.frames,'DEV_SCENARIO',`${developerScenarioLast.label} · 현재 검증 다시보기`,gk?1:REPLAY_SPEED);}
function selectRandomRecentFix(){const keys=DEV_RECENT_VISIBLE_KEYS,key=keys[Math.floor(Math.random()*keys.length)],sel=$('heroRecentFixSelect');if(sel)sel.value=key;renderRecentFixGuide();if($('heroRecentFixStatus'))$('heroRecentFixStatus').textContent=`랜덤 선택: ${DEV_RECENT_GUIDES[key].label} · 내용을 확인한 뒤 강제 검증을 시작하세요.`;}
function download(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function currentDebugForBug(){return latestIntegratedDebug;}
function openBugModal(){if(!latestIntegratedDebug)return;$('heroBugModal').hidden=false;}
function closeBugModal(){$('heroBugModal').hidden=true;}
async function openGitHubBugIssue(){const d=currentDebugForBug(),desc=$('heroBugDescription').value.trim(),cat=$('heroBugCategory').value,prio=$('heroBugPriority').value,attachJson=$('heroBugAttachJson').checked;if(!desc)return;const endpoint=window.FLR_BUG_REPORT_ENDPOINT||window.FLRPG_BUG_REPORT_ENDPOINT||'',snap={category:cat,priority:prio,description:desc};const button=$('heroBugOpenIssue');if(button){button.disabled=true;button.textContent='등록 중...';}try{if(!endpoint)throw new Error('BUG_REPORT_ENDPOINT_MISSING');const rid=`umt053h3-${crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}`,reportBundle=attachJson?makeBugReportBundle(d,{reportId:rid,description:desc,category:cat,priority:prio}):null,payload={reportId:rid,build:'USER-MATCH-TEST-V0.5.4-R25',step:78,category:cat,priority:Number(prio),description:desc,summary:snap,debug:reportBundle,client:{userAgent:navigator.userAgent,href:location.href}},r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);closeBugModal();const scope=attachJson?`현재 상황${reportBundle?.previousSituation?' + 직전 상황':''} 저장됨`:'경기 상황 JSON 미첨부',issueOk=j.issueCreated!==false,msg=issueOk?`버그 등록 완료 · ${j.reportId||rid} · ${scope} · GitHub 로그인 불필요`:`JSON 저장 완료 · ${j.reportId||rid} · GitHub 이슈 자동 생성 실패(리포트 ID 보존됨)`;$('heroPlayback').textContent=msg;pushLiveFeed(msg,'scene');return;}catch(err){console.warn('FLR anonymous bug report failed',err);$('heroPlayback').textContent='자동 등록 실패';}finally{if(button){button.disabled=false;button.textContent='버그 등록';}}}
function makeBugReportBundle(d,meta={}){return{schemaVersion:'FLR_BUG_REPORT_1',meta,debug:deep(d),previousSituation:deep(previousCompletedSituation()?.debug||null)}}
function loop(ts){const real=Math.min(.08,(ts-last)/1000);last=ts;if(phase==='PRE_REPLAY'&&replayList.length)processReplay(real);else if(phase==='RESULT_PLAYBACK'&&session)processResult(real);else if(phase==='EPISODE_CONTINUATION'&&session)processEpisodeContinuation(real);requestAnimationFrame(loop)}
if($('heroReturnLatest'))$('heroReturnLatest').onclick=()=>{if(replayReturn==='HISTORY'&&phase==='PRE_REPLAY')restoreLatestAfterReplay();};$('heroStart').onclick=start;$('heroReset').onclick=setup;$('heroNewSeed').onclick=()=>{trial++;setup()};$('heroPlayer').onchange=setup;$('heroReplayBefore').onclick=()=>session&&startReplay(P.latestReplay(session),'CHOICE','선택 직전 실제 경기');$('heroReplayEpisode').onclick=()=>{if(!session)return;const f=resultReplayFrames();if(f.length)startReplay(f,'RESULT','전체 상황 다시보기');else{$('heroPlayback').textContent='다시보기 프레임을 찾지 못했습니다.';pushLiveFeed('다시보기 프레임을 찾지 못했습니다.','scene');}};$('heroContinue').onclick=continueAfterResult;$('heroBugReport').onclick=()=>openBugModal();{const b=$('heroBugClose')||$('heroBugCancel');if(b)b.onclick=closeBugModal}{const b=$('heroBugSubmit')||$('heroBugOpenIssue');if(b)b.onclick=openGitHubBugIssue;}if($('heroBugDownload'))$('heroBugDownload').onclick=()=>{const d=currentDebugForBug();if(d)download(d,'FLR_HYBRID_BUG_REPORT.json')};if($('heroBugModal'))$('heroBugModal').onclick=e=>{if(e.target===$('heroBugModal'))e.stopPropagation()};$('heroDownloadScene').onclick=()=>{const d=session&&activeBoundary?makeIntegratedDebug():latestIntegratedDebug;if(d)download(d,session&&activeBoundary?'FLR_HYBRID_CURRENT_EPISODE.json':'FLR_HYBRID_LATEST.json')};$('heroCopyDebug').onclick=()=>navigator.clipboard?.writeText($('heroDebugSummary').textContent);$('heroShowOffside').onchange=()=>session&&draw(E.snapshot(session.m));if($('heroRecentFixSelect'))$('heroRecentFixSelect').onchange=renderRecentFixGuide;if($('heroRecentFixRun'))$('heroRecentFixRun').onclick=()=>runRecentFixScenario(selectedRecentFixKey(),{newSeed:false});if($('heroRecentFixNewSeed'))$('heroRecentFixNewSeed').onclick=()=>runRecentFixScenario(selectedRecentFixKey(),{newSeed:true});if($('heroRecentFixReplay'))$('heroRecentFixReplay').onclick=replayRecentFixScenario;if($('heroRecentFixRandom'))$('heroRecentFixRandom').onclick=selectRandomRecentFix;setup();requestAnimationFrame(loop);
})();
