(function(root){'use strict';
const R=root&&root.FLRPG_RESTART_MOVEMENT;if(!R||R.__v36PublicShapePatch)return;if(String(R.VERSION||'').startsWith('V36-RESTART-MOVEMENT-1.0')){R.__v36PublicShapePatch=true;return;}
const HOME='HOME',AWAY='AWAY',clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),other=t=>t===HOME?AWAY:HOME,worldToLocal=(t,x,y)=>t===HOME?{x,y}:{x:105-x,y:68-y},localToWorld=(t,x,y)=>t===HOME?{x,y}:{x:105-x,y:68-y};
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function stable(m,id,axis,span){const h=hash32(`${m.seed}|SET_PIECE_STAGGER|${id}|${axis}|${Math.floor((m.restart?.setupStartedAt||m.time)*10)}`);return((h%10001)/10000-.5)*2*span;}
function set(setup,id,w,task,required=true,sprint=true){if(!id||!w)return;setup.targets[id]={x:w.x,y:w.y,task,required:!!required,sprint:!!sprint};if(required&&!setup.requiredIds.includes(id))setup.requiredIds.push(id);}
function local(team,lx,ly){return localToWorld(team,clamp(lx,1,104),clamp(ly,1,67));}
function opp(restartTeam,p,lx,ly){return localToWorld(p.team,clamp(105-lx,1,104),clamp(ly,1,67));}
function apply(m,setup){for(const [id,t] of Object.entries(setup?.targets||{})){const p=m.playersById?.[id]||m.players.find(q=>q.id===id);if(!p)continue;p.tx=t.x;p.ty=t.y;p.action=t.task;p.tacticalTask=t.task;p.sprint=!!t.sprint&&Math.hypot(p.x-t.x,p.y-t.y)>2.4;p.markTargetId=null;}}
function repairCorner(m,s){const r=m.restart,team=r.team,oppTeam=other(team),atk=m.players.filter(p=>p.team===team),def=m.players.filter(p=>p.team===oppTeam),kicker=m.playersById?.[s.kickerId];if(!kicker)return;const lp=worldToLocal(team,r.x,r.y),top=lp.y<34,runup=localToWorld(team,Math.max(105.45,lp.x+1.55),top?-0.72:68.72);s.targets={};s.requiredIds=[];set(s,kicker.id,runup,'CORNER_KICKER_RUNUP_START',true,true);s.cornerRunup={start:runup,ball:{x:r.x,y:r.y}};const attack={ST:[99,34],LW:[98,28.8],RW:[98,39.2],CM:[90.8,34],LCM:[92,25.2],RCM:[92,42.8],LB:[79,17.5],RB:[79,50.5],LCB:[72.5,28],RCB:[72.5,40],GK:[7,34]};for(const p of atk){if(p.id===kicker.id)continue;const q=attack[p.slot]||[86,34];set(s,p.id,local(team,q[0]+stable(m,p.id,'CORNER_ATK_X',.55),q[1]+stable(m,p.id,'CORNER_ATK_Y',.75)),'CORNER_ATTACK_SETUP',['ST','WF','CM'].includes(p.role),true);}const defend={GK:[102.3,34],LB:[98,25.5],LCB:[99,30.6],RCB:[99,37.4],RB:[98,42.5],LCM:[93.4,25],CM:[94,34],RCM:[93.4,43],LW:[83.5,16.5],ST:[81.5,34],RW:[83.5,51.5]};for(const p of def){const q=defend[p.slot]||[94,34];set(s,p.id,opp(team,p,q[0]+stable(m,p.id,'CORNER_DEF_X',.45),q[1]+stable(m,p.id,'CORNER_DEF_Y',.65)),'CORNER_DEFENCE_SETUP',['GK','CB','FB','CM'].includes(p.role),true);}}
function repairFreeKick(m,s){const r=m.restart,team=r.team,oppTeam=other(team),atk=m.players.filter(p=>p.team===team),def=m.players.filter(p=>p.team===oppTeam),kicker=m.playersById?.[s.kickerId];if(!kicker)return;const lp=worldToLocal(team,r.x,r.y),advanced=lp.x>67,approach=localToWorld(team,Math.max(1,lp.x-1.45),lp.y);s.targets={};s.requiredIds=[];set(s,kicker.id,approach,'FREE_KICK_KICKER_READY',true,true);s.restartApproach={start:approach,ball:{x:r.x,y:r.y}};for(const p of atk){if(p.id===kicker.id)continue;let lx,ly;if(p.role==='ST'){lx=advanced?clamp(lp.x+11,78,96):clamp(lp.x+18,54,76);ly=34;}else if(p.role==='WF'){lx=advanced?clamp(lp.x+8,75,94):clamp(lp.x+15,52,74);ly=p.slot==='LW'?17:51;}else if(p.role==='CM'){const d=p.slot==='CM'?(advanced?0:-3):(advanced?-4:-7);lx=clamp(lp.x+d,32,84);ly=p.slot==='LCM'?23:p.slot==='RCM'?45:34;}else if(p.role==='FB'){lx=clamp(lp.x-(advanced?21:18),24,54);ly=p.slot==='LB'?10:58;}else if(p.role==='CB'){lx=clamp(lp.x-(advanced?30:26),18,46);ly=p.slot==='LCB'?28:40;}else{lx=7;ly=34;}set(s,p.id,local(team,lx+(p.role==='GK'?0:stable(m,p.id,'FK_ATK_X',.45)),ly+(p.role==='GK'?0:stable(m,p.id,'FK_ATK_Y',.65))),'FREE_KICK_ATTACK_SETUP',['ST','WF','CM'].includes(p.role),true);}if(advanced){const point={x:r.x,y:r.y},wall=def.filter(p=>p.role!=='GK').slice().sort((a,b)=>Math.hypot(a.x-point.x,a.y-point.y)-Math.hypot(b.x-point.x,b.y-point.y)).slice(0,3),ids=new Set(wall.map(p=>p.id)),wallX=clamp(lp.x+9.15,4,100),ys=[31.2,34,36.8];wall.forEach((p,i)=>set(s,p.id,local(team,wallX,ys[i]),'FREE_KICK_WALL',true,true));for(const p of def){if(ids.has(p.id))continue;let q;if(p.role==='GK')q=[102.2,34];else if(p.role==='CB'||p.role==='FB')q=[96,p.slot==='LB'?18:p.slot==='RB'?50:p.slot==='LCB'?29:39];else if(p.role==='CM')q=[89.5,p.slot==='LCM'?23:p.slot==='RCM'?45:34];else if(p.role==='ST')q=[54,34];else q=[59,p.slot==='LW'?14:p.slot==='RW'?54:34];set(s,p.id,opp(team,p,q[0]+(p.role==='GK'?0:stable(m,p.id,'FK_DEF_ADV_X',.35)),q[1]+(p.role==='GK'?0:stable(m,p.id,'FK_DEF_ADV_Y',.55))),'FREE_KICK_DEFENCE_SETUP',['GK','CB','FB','CM'].includes(p.role),true);}}else{const backX=clamp(lp.x+13,60,84),midX=clamp(lp.x+7,54,78);for(const p of def){let q;if(p.role==='GK')q=[102.2,34];else if(p.role==='CB'||p.role==='FB')q=[backX,p.slot==='LB'?16:p.slot==='RB'?52:p.slot==='LCB'?28.5:39.5];else if(p.role==='CM')q=[midX,p.slot==='LCM'?22:p.slot==='RCM'?46:34];else if(p.role==='ST')q=[54,34];else q=[59,p.slot==='LW'?14:p.slot==='RW'?54:34];set(s,p.id,opp(team,p,q[0]+(p.role==='GK'?0:stable(m,p.id,'FK_DEF_STD_X',.35)),q[1]+(p.role==='GK'?0:stable(m,p.id,'FK_DEF_STD_Y',.55))),'FREE_KICK_DEFENCE_SETUP',['GK','CB','FB','CM'].includes(p.role),true);}}}
function repair(m,s){if(!m?.restart||!s)return s;if(m.restart.kind==='CORNER')repairCorner(m,s);else if(m.restart.kind==='FREE_KICK')repairFreeKick(m,s);else return s;apply(m,s);return s;}
const begin=R.begin.bind(R),assign=R.assign.bind(R);R.begin=m=>repair(m,begin(m));R.assign=m=>{const ok=assign(m);if(m?.restart?.setup)repair(m,m.restart.setup);return ok;};R.__v36PublicShapePatch=true;
})(typeof globalThis!=='undefined'?globalThis:this);