'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(process.argv[2]||'.');
const req=p=>require(path.join(ROOT,p));
const core=req('runtime/continuous_match_core.js'),controller=req('runtime/protagonist_match_controller.js');
const B=core.choiceActionBridge();
const failures=[];const check=(ok,msg)=>{if(!ok)failures.push(msg);return ok;};const round=(v,n=4)=>Number(v.toFixed(n));
function localReferences(){const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),refs=[];for(const re of [/\bsrc="([^"]+)"/g,/\bhref="([^"]+)"/g]){let m;while((m=re.exec(html)))if(!/^(?:https?:|data:|#)/.test(m[1]))refs.push(m[1]);}const missing=[...new Set(refs)].filter(p=>!fs.existsSync(path.join(ROOT,p)));check(!missing.length,`missing local references ${missing.join(',')}`);return{count:[...new Set(refs)].length,missing};}
function startup(){const rows=[];for(const hero of ['H-ST','H-CM','H-LCB','H-GK']){try{const s=controller.create(`TT049-START-${hero}`,{heroPlayerId:hero,mode:'PLAYER_ALL'});let steps=0;while(!s.m.completed&&s.m.time<45&&steps++<1200){controller.step(s,.10);if(s.pending){const p=controller.autoPick(s)||s.pending.options[0];if(p)controller.applyChoice(s,p.id,p.targetId||null,{source:'TT049_STARTUP'});}}const snap=core.snapshot(s.m);check(Number.isFinite(snap.time)&&Array.isArray(snap.players)&&snap.players.length===22,`startup snapshot invalid ${hero}`);rows.push({hero,time:round(s.m.time,1),pending:!!s.pending,score:snap.score});}catch(e){check(false,`startup ${hero}: ${e.message}`);rows.push({hero,error:e.message});}}return rows;}
function choiceReplay(){const s=controller.create('TT049-CHOICE-REPLAY',{heroPlayerId:'H-ST',mode:'PLAYER_ALL'});let guard=0;while(!s.pending&&!s.m.completed&&guard++<24000)controller.step(s,.10);check(!!s.pending,'no protagonist pending choice found');if(!s.pending)return{found:false};const pending=s.pending,withTarget=pending.options.find(o=>o.targetId)||pending.options[0],beforeReplay=controller.latestReplay(s);check(beforeReplay.length>0,'pre-choice replay empty');const requestedTarget=withTarget.targetId||null,r=controller.applyChoice(s,withTarget.id,requestedTarget,{source:'TT049_REPLAY'});check(r.ok,'choice apply failed');if(requestedTarget)check(r.targetId===requestedTarget,'choice exact target mismatch');check(r.futureOutcomePrecomputed===false,'choice result precomputed flag true');let post=0;while(!s.m.completed&&!s.pending&&post++<160)controller.step(s,.10);const latest=controller.latestReplay(s);check(latest.length>0,'post-choice replay empty');const hist=controller.sceneHistory(s);check(hist.length>0,'scene history empty');const last=hist[hist.length-1];if(last?.choice?.targetId)check(last.choice.targetId===requestedTarget,'scene history target mismatch');return{found:true,choiceId:withTarget.id,requestedTargetId:requestedTarget,resolvedTargetId:r.targetId||null,preFrames:beforeReplay.length,latestFrames:latest.length,sceneCount:hist.length,futureOutcomePrecomputed:r.futureOutcomePrecomputed};}
function place(p,x,y,vx=0,vy=0,tx=x,ty=y,task='HOLD_SHAPE'){p.x=x;p.y=y;p.vx=vx;p.vy=vy;p.tx=tx;p.ty=ty;p.action=task;p.tacticalTask=task;p.sprint=Math.hypot(vx,vy)>1.15;}
function mfDecision(trials=160){let forwardPass=0,shot=0,carry=0,farBackward=0,other=0;const samples=[];for(let i=0;i<trials;i++){const m=core.createMatch(`TT049-MF-${i}`);m.restart=null;m.phase='OPEN_PLAY';m.time=100;m.transitionUntil=0;m.lastChallengeAt=100;const cm=B.playerById(m,'H-CM'),st=B.playerById(m,'H-ST'),lw=B.playerById(m,'H-LW'),rw=B.playerById(m,'H-RW'),lcm=B.playerById(m,'H-LCM'),rcm=B.playerById(m,'H-RCM');place(cm,81.5,36.5,.35,0,82,36.5,'HOLD_BALL');place(st,90,34.5,1.2,0,92,34.5,'ATTACK_CENTRAL_CHANNEL');place(lw,86,18.5,1.0,.1,88,19,'FAR_SIDE_RUN');place(rw,86,51,1.1,-.1,88,50.5,'FAR_SIDE_RUN');place(lcm,67,25);place(rcm,68,47);let k=0;const ds=[[87,31],[88,42],[92,25],[93,49],[83,55],[79,15],[75,36],[72,28],[70,47],[68,60]];for(const p of m.players.filter(p=>p.team==='AWAY'&&p.role!=='GK')){const q=ds[k++%ds.length];place(p,q[0],q[1],-.25,0,q[0]-1,q[1],'DEF_BLOCK');}place(B.playerById(m,'A-GK'),101.5,34,0,0,101.5,34,'GK_SET');B.setControlled(m,cm);cm.bodyAngle=0;cm.controlledSince=m.time-.7;cm.nextThink=m.time;cm.lockTargetUntil=0;m.nextShape=m.time;const start=m.events.length;let g=0;while(cm.lastDecision==='NONE'&&g++<100)core.step(m,.05);const ev=m.events.slice(start),pe=ev.find(e=>e.type==='PASS'&&e.actorId==='H-CM');let cls='OTHER';if(cm.lastDecision==='SHOT'){shot++;cls='SHOT';}else if(cm.lastDecision==='CARRY'){carry++;cls='CARRY';}else if(cm.lastDecision==='PASS'&&pe){const t=B.playerById(m,pe.targetId),dx=t? t.x-cm.x:0;if(dx>=-2){forwardPass++;cls='ATTACK_PASS';}else if(dx<=-14){farBackward++;cls='FAR_BACKWARD';}else{other++;cls='OTHER_PASS';}}else other++;if(i<10)samples.push({decision:cm.lastDecision,class:cls,targetId:pe?.targetId||null});}const meaningful=(forwardPass+shot+carry)/trials,backRate=farBackward/trials;check(meaningful>=.70,`MF meaningful attacking decision rate ${meaningful}`);check(backRate<=.08,`MF purposeless distant backward rate ${backRate}`);return{trials,forwardPass,shot,carry,farBackward,other,meaningfulRate:round(meaningful),farBackwardRate:round(backRate),samples};}
const result={schemaVersion:'FLR_TT049_SUPPLEMENTAL_VALIDATION_0.1',build:'TT-0.49 TEST_ONLY',step79Started:false,canonical:{hybridPrecomputesChoice:false,hybridPrecomputesOutcome:false,v06OwnsLiveChoiceDiscovery:true,v06OwnsPostChoiceResolution:true,protagonistUnchosenMaterialActionForbidden:true,choiceIdAndExactTargetIdImmutable:true},workerDeploymentDeferred:true};result.localReferences=localReferences();result.startup=startup();result.choiceReplay=choiceReplay();result.mfDecision=mfDecision();result.failures=failures;result.status=failures.length?'FAIL':'PASS';console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
