'use strict';
const path=require('path');const root=path.resolve(process.argv[2]||'.');
const E=require(path.join(root,'runtime/continuous_match_core.js'));
const P=require(path.join(root,'runtime/protagonist_match_controller.js'));
const B=E.choiceActionBridge();
function place(p,x,y){p.x=x;p.y=y;p.tx=x;p.ty=y;p.vx=0;p.vy=0;p.hasBall=false;p.nextThink=99999;p.lockTargetUntil=0;p.runUntil=0;p.action='HOLD_SHAPE';p.tacticalTask='HOLD_SHAPE';p.markTargetId=null;}
function metrics(rows){const under=x=>rows.filter(r=>r.d<x),span=a=>a.length>1?a.at(-1).t-a[0].t:0;let path=0,net=0,xRev=0,yRev=0,lastDx=0,lastDy=0;for(let i=1;i<rows.length;i++){const dx=rows[i].rcb[0]-rows[i-1].rcb[0],dy=rows[i].rcb[1]-rows[i-1].rcb[1];path+=Math.hypot(dx,dy);if(lastDx&&dx&&Math.sign(dx)!==Math.sign(lastDx))xRev++;if(lastDy&&dy&&Math.sign(dy)!==Math.sign(lastDy))yRev++;if(Math.abs(dx)>.01)lastDx=dx;if(Math.abs(dy)>.01)lastDy=dy;}if(rows.length>1)net=Math.hypot(rows.at(-1).rcb[0]-rows[0].rcb[0],rows.at(-1).rcb[1]-rows[0].rcb[1]);const a12=under(1.2),a16=under(1.6);return{samples:rows.length,minD:Math.min(...rows.map(r=>r.d)),under12:{n:a12.length,span:span(a12)},under16:{n:a16.length,span:span(a16)},path,net,pathToNet:path/Math.max(.1,net),xRev,yRev,taskSwitches:rows.reduce((n,r,i)=>n+(i&&r.task!==rows[i-1].task?1:0),0),markSwitches:rows.reduce((n,r,i)=>n+(i&&(r.mark||null)!==(rows[i-1].mark||null)?1:0),0),taskSet:[...new Set(rows.map(r=>r.task))],markSet:[...new Set(rows.map(r=>r.mark))],last:rows.at(-1)};}
function runConflict(seed,ownerId,ownerX,ownerY){const s=P.create(seed,{heroPlayerId:ownerId,mode:'FULL_SKIP',managerProfiles:{HOME:'BALANCED',AWAY:'ATTACKING_PRESS'}}),m=s.m,ps=m.playersById;m.time=1698.5;m.phase='OPEN_PLAY';m.restart=null;m.completed=false;m.possession='HOME';m.transitionUntil=0;m.protagonistExplicitActionRequired=true;m.nextShape=m.time;
 for(const p of m.players){if(p.team==='HOME')place(p,58,p.slot==='ST'?34:p.slot?.includes('L')?18:p.slot?.includes('R')?50:34);else place(p,90,p.slot==='ST'?34:p.slot?.includes('L')?48:p.slot?.includes('R')?20:34);}
 const owner=ps[ownerId],st=ps['H-ST'],rcb=ps['A-RCB'],lcb=ps['A-LCB'];place(owner,ownerX,ownerY);place(st,79,31);place(rcb,79.8,30.3);place(lcb,84,40);
 // Keep non-CB defenders capable of core press/cover but not sitting on top of the ST.
 place(ps['A-LCM'],70,39);place(ps['A-CM'],68,34);place(ps['A-RCM'],70,47);place(ps['A-LB'],82,53);place(ps['A-RB'],78,17);
 B.setControlled(m,owner,true);owner.controlledSince=m.time-2;owner.nextThink=m.time;owner.tx=owner.x;owner.ty=owner.y;owner.action='HOLD_BALL';owner.tacticalTask='HOLD_BALL';
 const rows=[];for(let i=0;i<125;i++){P.step(s,.1);const d=Math.hypot(st.x-rcb.x,st.y-rcb.y);rows.push({t:m.time,d,st:[st.x,st.y],rcb:[rcb.x,rcb.y],task:rcb.tacticalTask,mark:rcb.markTargetId||null,owner:[owner.x,owner.y],possession:m.possession});if(m.possession!=='HOME')break;}return{seed,ownerId,...metrics(rows)};}
const specs=[['H-LCM',72,23],['H-RCM',72,45],['H-LW',74,14],['H-RW',74,52]];const cases=[];for(const [id,x,y] of specs)for(const suffix of ['A','B'])cases.push(runConflict(`MARK-CONFLICT-${id}-${suffix}`,id,x,y));
const worst=cases.slice().sort((a,b)=>(b.taskSwitches+b.xRev)-(a.taskSwitches+a.xRev)||b.pathToNet-a.pathToNet)[0];
// Reported failure had 10+ role switches, 26 x reversals and ~9.9 path/net in ~15 sec.
const issue=worst.taskSwitches>=7&&worst.xRev>=8&&worst.pathToNet>=4.0;const out={schemaVersion:'FLR_TT051_OFFBALL_MARK_JITTER_DIAG_1.1',issueReproduced:issue,pass:!issue,cases,worst,criteria:{issue:'CB repeatedly alternates marking/press/cover roles while shadowing an off-ball ST'}};console.log(JSON.stringify(out,null,2));process.exit(issue?1:0);
