'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(process.argv[2]||'.'),RUNTIME=path.join(ROOT,'runtime');
const req=p=>require(path.join(ROOT,p));
const E=req('runtime/continuous_match_core.js'),P=req('runtime/protagonist_match_controller.js'),H=req('live_hybrid_session_v02.js'),A=req('live_v06_scene_authority_browser.js');
const B=E.choiceActionBridge(),C=E.choiceStateBridge(),failures=[],watch=[];
const check=(ok,msg)=>{if(!ok)failures.push(msg);return ok},round=(x,n=3)=>Number(x.toFixed(n));
function place(p,x,y,vx=0,vy=0,task='HOLD_SHAPE'){p.x=x;p.y=y;p.vx=vx;p.vy=vy;p.tx=x;p.ty=y;p.action=task;p.tacticalTask=task;p.sprint=Math.hypot(vx,vy)>1.2;}
function prep(seed){const m=E.createMatch(seed);m.restart=null;m.phase='OPEN_PLAY';m.time=100;m.transitionUntil=0;m.lastChallengeAt=100;return m;}
function spreadAway(m){let i=0;for(const p of m.players.filter(p=>p.team==='AWAY'&&p.role!=='GK')){place(p,58-(i%4)*3,5+(i*7)%58);i++;}const g=B.playerById(m,'A-GK');place(g,101,34,0,0,'GK_SET');}

function throughTrajectory(){
  const m=prep('TT050-THROUGH-VECTOR');spreadAway(m);const st=B.playerById(m,'H-ST'),lw=B.playerById(m,'H-LW'),alc=B.playerById(m,'A-LCB'),arc=B.playerById(m,'A-RCB');
  // Keep the runner ONSIDE at release while leaving the diagonal lane physically open.
  place(alc,89,5,0,0,'REST_DEFENCE');place(arc,91,63,0,0,'REST_DEFENCE');
  place(st,75.5,34,0,0,'HOLD_BALL');place(lw,77.0,18.0,3.2,2.0,'FAR_SIDE_RUN');lw.tx=86.0;lw.ty=23.7;B.setControlled(m,st);st.bodyAngle=0;st.controlledSince=m.time-.8;m.nextShape=1e9;
  const f=C.inspect(m,'H-ST'),opt=f.candidates.find(x=>x.id==='THROUGH_PASS'&&x.targetId==='H-LW');check(!!opt,'moving onside diagonal LW THROUGH_PASS missing');
  if(!opt)return{availableCandidates:f.candidates.map(x=>({id:x.id,targetId:x.targetId,reason:x.reason}))};
  const sx=st.x,sy=st.y,tx0=lw.x,ty0=lw.y,vx=lw.vx,vy=lw.vy,sp=Math.hypot(vx,vy),r=C.applyCandidate(m,'H-ST','THROUGH_PASS','H-LW','TT050_VALIDATION');check(r.ok,'through apply failed');check(r.targetId==='H-LW','through exact target changed');check(m.ball.intendedReceiverId==='H-LW','through intended receiver changed');
  const px=m.ball.targetX,py=m.ball.targetY,lvx=px-tx0,lvy=py-ty0,ld=Math.hypot(lvx,lvy),cos=sp>0&&ld>0?(lvx*vx+lvy*vy)/(ld*sp):0,ballSpeed=Math.hypot(m.ball.vx,m.ball.vy),ballTime=Math.hypot(px-sx,py-sy)/Math.max(.1,ballSpeed),runnerTime=ld/Math.max(.1,sp);
  check(cos>.82,`through lead does not follow runner vector cosine=${cos}`);check(Math.abs(py-ty0)>1.0,`diagonal through lost lateral lead yDelta=${py-ty0}`);check(Math.abs(ballTime-runnerTime)<.48,`through arrival mismatch ball=${ballTime} runner=${runnerTime}`);
  return{target:{x:round(px),y:round(py)},leadDistance:round(ld),runnerSpeed:round(sp),vectorCosine:round(cos),ballArrival:round(ballTime),runnerArrival:round(runnerTime),arrivalDelta:round(Math.abs(ballTime-runnerTime))};
}

function finalThirdDecision(trials=120){let backward=0,forwardPass=0,shot=0,carry=0,takeOn=0,other=0;const samples=[];
  for(let i=0;i<trials;i++){const m=prep(`TT050-FT-${i}`);spreadAway(m);const rw=B.playerById(m,'H-RW'),st=B.playerById(m,'H-ST'),cm=B.playerById(m,'H-RCM');place(rw,89.2,46.5,1.0,-.2,'FIRST_TOUCH_FLOW');place(st,93.0,36.0,.5,0,'PIN_AND_RUN');place(cm,79.5,43.0,.2,0,'SECOND_WAVE_8');const lb=B.playerById(m,'A-LB'),lcb=B.playerById(m,'A-LCB');place(lb,95.8,54.5,-.4,-.2,'RECOVERY');place(lcb,95.4,31.0,-.2,.1,'SHOT_LANE_COVER');B.setControlled(m,rw);rw.controlledSince=m.time-.75;rw.lastReceivedAt=m.time-.75;rw.nextThink=m.time;rw.lockTargetUntil=0;m.nextShape=1e9;const before=m.events.length;let g=0;while(g++<30&&rw.lastDecision==='NONE')E.step(m,.05);const ev=m.events.slice(before).find(e=>e.actorId==='H-RW'&&['PASS','SHOT','TAKE_ON'].includes(e.type));if(ev?.type==='PASS'){const target=B.playerById(m,ev.targetId),fw=target?target.x-rw.x:0;if(fw<-2)backward++;else forwardPass++;}else if(ev?.type==='SHOT')shot++;else if(ev?.type==='TAKE_ON')takeOn++;else if(rw.lastDecision==='CARRY')carry++;else other++;if(i<8)samples.push({decision:rw.lastDecision,event:ev?{type:ev.type,targetId:ev.targetId||null}:null});}
  const backwardRate=backward/trials,attackRate=(forwardPass+shot+carry+takeOn)/trials;check(backwardRate<=.18,`final-third backward pass rate ${backwardRate}`);check(attackRate>=.72,`final-third attack continuation rate ${attackRate}`);return{trials,backward,forwardPass,shot,carry,takeOn,other,backwardRate:round(backwardRate),attackContinuationRate:round(attackRate),samples};}

function maxBurst(times,w=5){let best=0;for(let i=0,j=0;i<times.length;i++){while(times[i]-times[j]>w)j++;best=Math.max(best,i-j+1);}return best;}
function highResStress(matches=1){const roles=[['ST','H-ST'],['CM','H-CM'],['CB','H-LCB'],['GK','H-GK']],out={};for(const [role,id] of roles){const rows=[];for(let i=0;i<matches;i++){const s=P.create(`TT050-STRESS-${role}-${i}`,{heroPlayerId:id,mode:'PLAYER_ALL'});P.runAuto(s,5400);const times=(s.m.userChoiceLog||[]).map(x=>Number(x.at)),diffs=times.slice(1).map((t,k)=>t-times[k]),sc=P.sceneHistory(s),eps=new Map();for(const x of sc)eps.set(x.episodeId||x.sceneId,(eps.get(x.episodeId||x.sceneId)||0)+1);rows.push({choices:times.length,episodes:eps.size,maxBurst5s:maxBurst(times),sub2s:diffs.filter(x=>x<2).length,sub3s:diffs.filter(x=>x<3).length,maxEpisodeChoices:Math.max(0,...eps.values())});}out[role]=rows[0];}return out;}

function chooseForHarness(pending,index){const opts=pending?.options||[];if(!opts.length)return null;const preferred=['PROGRESSIVE_PASS','THROUGH_PASS','AVAILABLE_PASS','CARRY','SAFE_PASS','HOLD','DELAY','BLOCK_LANE','TACKLE','SHORT_DISTRIBUTION','LONG_DISTRIBUTION'];for(const id of preferred){const rows=opts.filter(o=>o.id===id);if(rows.length)return rows[index%rows.length];}return opts[index%opts.length];}
function runHighResBoundary(boundary,role,seedIndex){
  let opened;if(boundary.type==='FINAL_2D_WINDOW')opened=A.runFinalWindow(boundary,{runtimeDir:RUNTIME,targetSecond:5400,seed:`TT050-HYB-FINAL-${role}-${seedIndex}`});else if(boundary.type==='SET_PIECE_2D_WINDOW')opened=A.runSetPieceWindow(boundary,{runtimeDir:RUNTIME,seed:`TT050-HYB-SP-${role}-${seedIndex}`});else opened=A.runToChoice(boundary,{runtimeDir:RUNTIME,seed:`TT050-HYB-${role}-${seedIndex}-${boundary.sceneId}`});
  const times=[];let guard=0,choiceIndex=0;
  if(boundary.type!=='FINAL_2D_WINDOW')while(opened.state&&!opened.state.m.completed&&guard++<900){
    if(opened.state.pending){const o=chooseForHarness(opened.state.pending,choiceIndex++);if(!o)break;times.push(Number(opened.state.m.time.toFixed(3)));A.applyChoiceAndAdvance(opened,o.id,o.targetId||null,{maxPostSeconds:12});continue;}
    if(!opened.state.activeEpisode)break;
    opened.P.step(opened.state,.10);
  }
  const snapshot=opened.snapshot||opened.E.snapshot(opened.state.m),events=(opened.state?.m?.events||opened.actualEvents||[]).filter(e=>Number(e.t)>=Number(boundary.atSecond)-.001),result=opened.state?.lastResult||opened.result||null;
  return{snapshot,actualEvents:events,result,hadChoice:times.length>0,choiceTimes:times};
}
function hybridCadence(matches=2){
  const defs=[['ST','H-ST'],['CM','H-CM'],['CB','H-LCB'],['GK','H-GK']],out={};
  for(const [role,id] of defs){const rows=[];for(let mi=0;mi<matches;mi++){const world=H.createSession({seed:`TT050-HYBRID-CAD-${role}-${mi}`,heroTeam:'HOME',heroRole:role,heroPlayerId:id}),times=[],episodeChoices=[];let heroWindows=0,choiceEpisodes=0,first30Choices=0,guard=0;
      while(world.status!=='FINISHED'&&guard++<500){const adv=H.advanceUntilBoundary(world);if(adv.status==='FINISHED')break;const b=adv.boundary;if(!b||b.type==='MATCH_END')break;if(b.type==='PROTAGONIST_2D_WINDOW')heroWindows++;const hr=runHighResBoundary(b,role,mi);if(hr.choiceTimes.length){choiceEpisodes++;episodeChoices.push(hr.choiceTimes.length);times.push(...hr.choiceTimes);first30Choices+=hr.choiceTimes.filter(t=>t<1800).length;}H.resumeFromHighRes(world,{snapshot:hr.snapshot,hadChoice:hr.hadChoice,result:hr.result,actualEvents:hr.actualEvents});}
      rows.push({heroWindows,choiceEpisodes,totalChoices:times.length,first30Choices,maxBurst5s:maxBurst(times),maxEpisodeChoices:Math.max(0,...episodeChoices),avgChoicesPerEpisode:choiceEpisodes?round(times.length/choiceEpisodes,2):0,score:{...world.state.score}});
    }
    const avg=k=>round(rows.reduce((a,r)=>a+r[k],0)/rows.length,2);out[role]={rows,avgHeroWindows:avg('heroWindows'),avgChoiceEpisodes:avg('choiceEpisodes'),avgTotalChoices:avg('totalChoices'),avgFirst30Choices:avg('first30Choices'),maxBurst5s:Math.max(...rows.map(r=>r.maxBurst5s)),maxEpisodeChoices:Math.max(...rows.map(r=>r.maxEpisodeChoices))};
  }
  const limits={ST:{avg:26,first30:11,single:34},CM:{avg:30,first30:12,single:38},CB:{avg:24,first30:10,single:32},GK:{avg:12,first30:6,single:16}};
  for(const role of Object.keys(limits)){const q=out[role],lim=limits[role];check(q.avgTotalChoices<=lim.avg,`${role} Hybrid avg choices excessive ${q.avgTotalChoices}`);check(q.avgFirst30Choices<=lim.first30,`${role} Hybrid first30 choices excessive ${q.avgFirst30Choices}`);check(Math.max(...q.rows.map(r=>r.totalChoices))<=lim.single,`${role} Hybrid single-match choices excessive`);check(q.maxBurst5s<=3,`${role} Hybrid choice burst excessive ${q.maxBurst5s}/5s`);}
  return out;
}

function overlapMeasure(matches=4){let frames=0,overlaps=0,separations=0;for(let i=0;i<matches;i++){const m=E.createMatch(`TT050-OVERLAP-${i}`);let g=0;while(!m.completed&&g++<70000){E.step(m,.10);const st=B.playerById(m,'H-ST'),rcm=B.playerById(m,'H-RCM');if(m.possession==='HOME'&&st&&rcm&&st.x>78){frames++;if(Math.hypot(st.x-rcm.x,st.y-rcm.y)<4.0&&Math.abs(st.y-rcm.y)<2.6)overlaps++;}separations=m.stats.midfieldStrikerLaneSeparations||separations;}}const rate=frames?overlaps/frames:0;if(rate>.025)watch.push(`RCM/ST overlap rate WATCH ${rate}`);return{matches,frames,overlaps,overlapRate:round(rate,4),laneSeparationCorrections:separations};}

async function workerRoundTrip(){const src=fs.readFileSync(path.join(ROOT,'bug-report-worker/worker.js'),'utf8').replace('export default ','globalThis.__worker=');const store=new Map(),ctx={Response,Request,URL,TextEncoder,console,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);const env={ALLOWED_ORIGIN:'https://1lisam.github.io',BUG_REPORTS:{get:async k=>{if(!store.has(k))return null;const body=store.get(k);return{body,json:async()=>JSON.parse(body)}},put:async(k,v)=>{store.set(k,v)},delete:async k=>store.delete(k)}};const debug={schemaVersion:'TEST_FULL_DEBUG',frames:Array.from({length:80},(_,i)=>({t:i/10,players:[{id:'H-ST',x:i,y:34}]})),nested:{choiceId:'THROUGH_PASS',targetId:'H-LW'}};const req=new Request('https://worker.example/report',{method:'POST',headers:{origin:'https://1lisam.github.io','content-type':'application/json'},body:JSON.stringify({reportId:'tt050-123456789012',build:'TT-0.50',step:78,category:'패스/공격',priority:4,description:'full json test',summary:{c:['THROUGH_PASS','H-LW'],s:[100]},debug})});const res=await ctx.__worker.fetch(req,env),j=await res.json();check(res.ok&&j.ok,'worker POST failed');const key=[...store.keys()].find(k=>k.startsWith('reports/'));check(!!key,'worker report key missing');if(key)check(JSON.stringify(JSON.parse(store.get(key)))===JSON.stringify(debug),'worker did not store exact debug object');check(String(j.jsonUrl||'').includes('/reports/'),'worker json URL missing');return{status:res.status,jsonUrl:j.jsonUrl||null,sizeBytes:j.sizeBytes||null,storedKey:key||null,exactDebug:key?JSON.stringify(JSON.parse(store.get(key)))===JSON.stringify(debug):false};}
function staticBugUi(){const ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8'),idx=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),cfg=fs.readFileSync(path.join(ROOT,'bug_report_config.js'),'utf8');check(ui.includes('debug:d'),'browser does not POST full integrated debug');check(ui.includes('FLR_BUG_REPORT_ENDPOINT'),'browser endpoint config missing');check(idx.includes('bug_report_config.js'),'index does not load bug config');check(cfg.includes('FLR_BUG_REPORT_ENDPOINT'),'public bug config missing');check(ui.includes('bugFallbackUrl'),'manual bug fallback missing');return{postsFullDebug:ui.includes('debug:d'),configLoaded:idx.includes('bug_report_config.js'),fallbackPresent:ui.includes('bugFallbackUrl')};}
function authority(samples=2){const violations=[];let tested=0;for(let si=0;si<8&&tested<samples;si++){const s=P.create(`TT050-AUTH-${si}`,{heroPlayerId:'H-ST',mode:'PLAYER_ALL'});let g=0;while(!s.m.completed&&g++<30000&&tested<samples){P.step(s,.10);if(!s.pending)continue;const c=s.pending.options.find(o=>o.id==='CARRY');if(!c){const a=P.autoPick(s)||s.pending.options[0];if(a)P.applyChoice(s,a.id,a.targetId||null,{source:'AUTO_SIMULATION'});continue;}const at=s.m.time,before=s.m.events.length,r=P.applyChoice(s,'CARRY',null,{source:'TT050_AUTH'});if(!r.ok)continue;tested++;let k=0;while(!s.m.completed&&!s.pending&&k++<80)P.step(s,.10);const bad=s.m.events.slice(before).filter(e=>e.t>at+.001&&e.actorId==='H-ST'&&['PASS','SHOT','TAKE_ON'].includes(e.type));if(bad.length)violations.push({at,events:bad});}}check(tested>=samples,`authority samples ${tested}/${samples}`);check(!violations.length,`authority violations ${JSON.stringify(violations)}`);return{tested,violations,futureOutcomePrecomputed:false};}

(async()=>{const result={schemaVersion:'FLR_TT050_VALIDATION_0.2',build:'TT-0.50 TEST_ONLY',step79Started:false,canonical:{futureChoicePrecomputed:false,futureOutcomePrecomputed:false,v06OwnsLiveChoiceDiscovery:true,v06OwnsPostChoiceResolution:true,choiceIdAndExactTargetIdImmutable:true,protagonistUnchosenMaterialActionForbidden:true}};result.throughTrajectory=throughTrajectory();result.finalThirdDecision=finalThirdDecision();result.hybridCadence=hybridCadence();result.highResStress=highResStress();result.midfieldStrikerOverlap=overlapMeasure();result.bugReportStatic=staticBugUi();result.bugReportWorker=await workerRoundTrip();result.authority=authority();result.watch=watch;result.failures=failures;result.status=failures.length?'FAIL':'PASS_CANDIDATE_INTERNAL';console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
