'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(process.argv[2]||'.');
const E=require(path.join(root,'runtime/continuous_match_core.js'));const P=require(path.join(root,'runtime/protagonist_match_controller.js'));const B=E.choiceActionBridge();
const core=fs.readFileSync(path.join(root,'runtime/continuous_match_core.js'),'utf8'),tac=fs.readFileSync(path.join(root,'runtime/tactical_movement.js'),'utf8'),mgr=fs.readFileSync(path.join(root,'runtime/manager_tendency_adapter.js'),'utf8');
const checks=[];const add=(name,ok,detail={})=>checks.push({name,ok:!!ok,detail});
add('offball-physical-floor-raised-only-nonduel',core.includes("same?(bothBox?1.18:0.88):(duel?1.02:1.30)"));
add('active-owner-duel-floor-preserved',core.includes('(duel?1.02:1.30)'));
add('cb-mark-role-not-renamed-midfield',tac.includes("z.p.role==='CM'?'MIDFIELD_LANE_SCREEN':'MARK_LANE_SCREEN'"));
add('manager-respects-existing-cb-offball-mark',mgr.includes("p.role==='CB'&&p.markTargetId&&p.markTargetId!==owner.id")&&mgr.includes('penalty+=8.5'));
function place(p,x,y){p.x=x;p.y=y;p.tx=x;p.ty=y;p.vx=0;p.vy=0;p.hasBall=false;p.nextThink=99999;p.lockTargetUntil=0;p.runUntil=0;p.action='HOLD_SHAPE';p.tacticalTask='HOLD_SHAPE';p.markTargetId=null;}
function metric(rows){if(!rows.length)return{samples:0,minD:99,under12:0,under16:0,pathToNet:0,taskSwitches:0,markSwitches:0,markSeen:false};let path=0,net=0,taskSwitches=0,markSwitches=0;for(let i=1;i<rows.length;i++){path+=Math.hypot(rows[i].rcb[0]-rows[i-1].rcb[0],rows[i].rcb[1]-rows[i-1].rcb[1]);if(rows[i].task!==rows[i-1].task)taskSwitches++;if((rows[i].mark||null)!==(rows[i-1].mark||null))markSwitches++;}if(rows.length>1)net=Math.hypot(rows.at(-1).rcb[0]-rows[0].rcb[0],rows.at(-1).rcb[1]-rows[0].rcb[1]);return{samples:rows.length,minD:Math.min(...rows.map(r=>r.d)),under12:rows.filter(r=>r.d<1.2).length,under16:rows.filter(r=>r.d<1.6).length,pathToNet:path/Math.max(.1,net),taskSwitches,markSwitches,markSeen:rows.some(r=>r.mark==='H-ST')};}
function run(seed,ownerId,ownerX,ownerY){const s=P.create(seed,{heroPlayerId:ownerId,mode:'FULL_SKIP',managerProfiles:{HOME:'BALANCED',AWAY:'ATTACKING_PRESS'}}),m=s.m,ps=m.playersById;m.time=1698.5;m.phase='OPEN_PLAY';m.restart=null;m.completed=false;m.possession='HOME';m.transitionUntil=0;m.protagonistExplicitActionRequired=true;m.nextShape=m.time;for(const p of m.players){if(p.team==='HOME')place(p,58,p.slot==='ST'?34:p.slot?.includes('L')?18:p.slot?.includes('R')?50:34);else place(p,90,p.slot==='ST'?34:p.slot?.includes('L')?48:p.slot?.includes('R')?20:34);}const owner=ps[ownerId],st=ps['H-ST'],rcb=ps['A-RCB'],lcb=ps['A-LCB'];place(owner,ownerX,ownerY);place(st,79,31);place(rcb,79.8,30.3);place(lcb,84,40);place(ps['A-LCM'],70,39);place(ps['A-CM'],68,34);place(ps['A-RCM'],70,47);place(ps['A-LB'],82,53);place(ps['A-RB'],78,17);B.setControlled(m,owner,true);owner.controlledSince=m.time-2;owner.nextThink=m.time;owner.tx=owner.x;owner.ty=owner.y;owner.action='HOLD_BALL';owner.tacticalTask='HOLD_BALL';const rows=[];for(let i=0;i<125;i++){P.step(s,.1);rows.push({d:Math.hypot(st.x-rcb.x,st.y-rcb.y),rcb:[rcb.x,rcb.y],task:rcb.tacticalTask,mark:rcb.markTargetId||null,possession:m.possession,ballOwnerId:m.ball.ownerId||null,ballMode:m.ball.mode});if(m.possession!=='HOME'&&m.ball.ownerId!=='H-ST')break;}const off=rows.filter(r=>r.ballOwnerId!=='H-ST'),on=rows.filter(r=>r.ballOwnerId==='H-ST');return{seed,ownerId,offball:metric(off),heroOwnerDuel:metric(on),totalSamples:rows.length};}
const specs=[['H-LCM',72,23],['H-RCM',72,45],['H-LW',74,14],['H-RW',74,52]],cases=[];for(const [id,x,y] of specs)for(const suffix of ['A','B'])cases.push(run(`MARK-CONFLICT-${id}-${suffix}`,id,x,y));
const offCases=cases.filter(c=>c.offball.samples>=3),marked=offCases.filter(c=>c.offball.markSeen);const minOffD=Math.min(...offCases.map(c=>c.offball.minD)),maxOffUnder12=Math.max(...offCases.map(c=>c.offball.under12),0),maxMarkedPath=Math.max(0,...marked.map(c=>c.offball.pathToNet)),maxMarkedTask=Math.max(0,...marked.map(c=>c.offball.taskSwitches)),maxMarkedSwitch=Math.max(0,...marked.map(c=>c.offball.markSwitches));const duelCases=cases.filter(c=>c.heroOwnerDuel.samples>0),minDuel=duelCases.length?Math.min(...duelCases.map(c=>c.heroOwnerDuel.minD)):99;
add('dynamic-offball-body-floor',minOffD>=1.27,{minOffD,offCases});
add('dynamic-no-sub-1.2m-offball-overlap',maxOffUnder12===0,{maxOffUnder12});
add('dynamic-marked-cb-offball-path-bounded',maxMarkedPath<=9.5,{maxMarkedPath,marked});
add('dynamic-marked-cb-offball-role-switches-bounded',maxMarkedTask<=9,{maxMarkedTask,marked});
add('dynamic-mark-ownership-switches-bounded',maxMarkedSwitch<=3,{maxMarkedSwitch,marked});
// Do not require a duel in every synthetic seed, but if one occurs it must remain allowed below the off-ball 1.30m floor.
add('dynamic-active-duel-remains-tighter-than-offball',duelCases.length===0||minDuel<1.30,{duelCases:duelCases.length,minDuel});
add('future-outcome-still-runtime',cases.length===8);
const failures=checks.filter(x=>!x.ok);console.log(JSON.stringify({schemaVersion:'FLR_TT051_OFFBALL_MARK_JITTER_VALIDATION_1.1',pass:failures.length===0,checks,failures,cases},null,2));process.exit(failures.length?1:0);
