'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(process.argv[2]||'.'),RUNTIME=path.join(ROOT,'runtime'),req=p=>require(path.join(ROOT,p));
const E=req('runtime/continuous_match_core.js'),P=req('runtime/protagonist_match_controller.js'),T=req('runtime/tactical_movement.js'),H=req('live_hybrid_session_v02.js'),A=req('live_v06_scene_authority_browser.js');
const B=E.choiceActionBridge(),C=E.choiceStateBridge(),failures=[],watch=[];
const check=(v,msg)=>{if(!v)failures.push(msg);return!!v},round=(v,n=3)=>Number(Number(v||0).toFixed(n));
function place(p,x,y,vx=0,vy=0,task='HOLD_SHAPE'){p.x=x;p.y=y;p.vx=vx;p.vy=vy;p.tx=x;p.ty=y;p.action=task;p.tacticalTask=task;p.sprint=Math.hypot(vx,vy)>1.2;p.lockTargetUntil=0;p.nextThink=0;}
function prep(seed){const m=E.createMatch(seed);m.restart=null;m.phase='OPEN_PLAY';m.time=100;m.transitionUntil=0;m.lastChallengeAt=100;m.nextShape=1e9;return m;}
function spreadAway(m,xBase=97){let i=0;for(const p of m.players.filter(p=>p.team==='AWAY'&&p.role!=='GK')){place(p,xBase-(i%3)*2,5+(i*6)%58);i++;}const g=B.playerById(m,'A-GK');place(g,102,34,0,0,'GK_SET');}
function eventAfter(m,t,types,actor=null){return(m.events||[]).find(e=>e.t>=t-.001&&types.includes(e.type)&&(!actor||e.actorId===actor))||null;}

function staticChecks(){
 const core=fs.readFileSync(path.join(ROOT,'runtime/continuous_match_core.js'),'utf8'),pc=fs.readFileSync(path.join(ROOT,'runtime/protagonist_match_controller.js'),'utf8'),tac=fs.readFileSync(path.join(ROOT,'runtime/tactical_movement.js'),'utf8'),hyb=fs.readFileSync(path.join(ROOT,'live_hybrid_session_v02.js'),'utf8'),auth=fs.readFileSync(path.join(ROOT,'live_v06_scene_authority_browser.js'),'utf8'),ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');
 const rows={receivingState:core.includes("kind:'RECEIVING'"),openBody:core.includes("receiveMode=openBody?'OPEN_BODY':'SECURE'"),incomingChoice:core.includes('protagonistIncomingChoice'),headerContact:core.includes('executeHeaderPassAtContact')&&core.includes("executeIncomingChoiceAtContact(m,p,sourceId,'CROSS'"),carryFloor:pc.includes('physicalAvailability:true'),singleChoiceSuppressed:pc.includes('q.options.length<2'),noMeaningfulChoice:auth.includes('noMeaningfulChoice'),farRun:tac.includes('persistentFarSideRunTarget'),carrierLane:tac.includes('ST_CLEAR_CARRIER_LANE'),wallRecovery:tac.includes('SET_PIECE_RECOVERY'),importantWindow:hyb.includes('IMPORTANT_2D_WINDOW')&&auth.includes('runImportantWindow')&&ui.includes("type==='IMPORTANT_2D_WINDOW'"),noLowResGoalResolution:!hyb.includes('s.score[team]++')};
 for(const [k,v] of Object.entries(rows))check(v,`static marker missing ${k}`);return rows;
}

function throughTrajectory(){
 const m=prep('TT051-THROUGH');spreadAway(m);const st=B.playerById(m,'H-ST'),lw=B.playerById(m,'H-LW'),alc=B.playerById(m,'A-LCB'),arc=B.playerById(m,'A-RCB');place(alc,89,5);place(arc,91,63);place(st,75.5,34);place(lw,77,18,3.2,2,'FAR_SIDE_RUN');lw.tx=86;lw.ty=23.7;B.setControlled(m,st);st.controlledSince=m.time-.8;m.protagonistControllerId='H-ST';m.protagonistExplicitActionRequired=true;
 const f=C.inspect(m,'H-ST'),opt=f?.candidates?.find(x=>x.id==='THROUGH_PASS'&&x.targetId==='H-LW');check(!!opt,'TT0.50 regression: diagonal THROUGH_PASS missing');if(!opt)return{};const sx=st.x,sy=st.y,tx=lw.x,ty=lw.y,vx=lw.vx,vy=lw.vy,sp=Math.hypot(vx,vy),r=C.applyCandidate(m,'H-ST','THROUGH_PASS','H-LW','TT051_VALIDATION',opt);check(r.ok&&r.targetId==='H-LW','TT0.50 regression: through exact target failed');const px=m.ball.targetX,py=m.ball.targetY,ld=Math.hypot(px-tx,py-ty),cos=ld&&sp?((px-tx)*vx+(py-ty)*vy)/(ld*sp):0,bs=Math.hypot(m.ball.vx,m.ball.vy),bt=Math.hypot(px-sx,py-sy)/Math.max(.1,bs),rt=ld/Math.max(.1,sp);check(cos>.82,`through runner vector regressed ${cos}`);check(Math.abs(bt-rt)<.55,`through arrival regressed ball=${bt} runner=${rt}`);return{vectorCosine:round(cos),ballArrival:round(bt),runnerArrival:round(rt),arrivalDelta:round(Math.abs(bt-rt))};
}

function waitReceiving(m,heroId,max=160,dt=.05,want=null){for(let i=0;i<max;i++){const f=C.inspect(m,heroId);if(f?.kind==='RECEIVING'&&(!want||f.candidates.some(c=>c.id===want)))return f;E.step(m,dt);}return null;}
function directionalReception(){
 const m=prep('TT051-RECEIVE-DIRECTIONAL');spreadAway(m);const src=B.playerById(m,'H-LCB'),hero=B.playerById(m,'H-LW');place(src,45,15);place(hero,69,16,4.2,.25,'FAR_SIDE_RUN');m.protagonistControllerId=hero.id;m.protagonistExplicitActionRequired=true;B.setControlled(m,src);src.controlledSince=m.time-.7;B.executePass(m,src,hero,'LONG_PASS',{block:0,open:6,forward:24,d:24,running:true},'TT051_LONG_RECEIVE');
 const f=waitReceiving(m,hero.id,180,.05,'DIRECTIONAL_TOUCH');check(!!f,'RECEIVING/DIRECTIONAL_TOUCH state not found on long pass');if(!f)return{};const opt=f.candidates.find(c=>c.id==='DIRECTIONAL_TOUCH'),armed=C.applyCandidate(m,hero.id,opt.id,null,'TT051_VALIDATION',opt);check(armed.ok&&armed.kind==='RECEIVING','directional first-touch arm failed');const start=m.time;let contact=null,speeds=[];for(let i=0;i<100;i++){E.step(m,.05);const ev=eventAfter(m,start,['DIRECTIONAL_FIRST_TOUCH'],hero.id);if(ev&&!contact)contact=ev.t;if(contact!=null&&m.time-contact<=.55)speeds.push(Math.hypot(hero.vx,hero.vy));if(contact!=null&&m.time-contact>.60)break;}check(contact!=null,'directional first touch never executed at physical contact');check((m.stats.openBodyReceives||0)>0,'open-body receive stat not recorded');check((m.stats.directionalFirstTouches||0)>0,'directional first-touch stat not recorded');const minSpeed=speeds.length?Math.min(...speeds):0;check(minSpeed>.65,`1_8 regression: receiver braked to near-zero immediately after directional touch minSpeed=${minSpeed}`);const localAdvance=hero.team==='HOME'?hero.tx-hero.x:hero.x-hero.tx;check(localAdvance>1.0,`directional first touch did not carry into attack txDelta=${localAdvance}`);return{delivery:f.deliveryMode,eta:round(f.eta),contactAt:contact,minSpeedFirst055:round(minSpeed),openBodyReceives:m.stats.openBodyReceives||0,directionalFirstTouches:m.stats.directionalFirstTouches||0,targetAdvance:round(localAdvance)};
}

function oneTouchPass(){
 const m=prep('TT051-ONE-TOUCH');spreadAway(m);const src=B.playerById(m,'H-CM'),hero=B.playerById(m,'H-ST');place(src,61,34);place(hero,74,34,2.2,0,'ATTACK_OPEN_CHANNEL');place(B.playerById(m,'H-RW'),81,50,2.4,-.3,'FAR_SIDE_RUN');place(B.playerById(m,'H-LW'),80,17,2.1,.2,'FAR_SIDE_RUN');m.protagonistControllerId=hero.id;m.protagonistExplicitActionRequired=true;B.setControlled(m,src);B.executePass(m,src,hero,'PASS',{block:0,open:5,forward:13,d:13,running:true},'TT051_DIRECT_FEED');const f=waitReceiving(m,hero.id,100,.04,'ONE_TOUCH_PASS');check(!!f,'ground ONE_TOUCH_PASS receiving state missing');if(!f)return{};const opt=f.candidates.find(c=>c.id==='ONE_TOUCH_PASS'&&c.targetId)||null;check(!!opt,'one-touch target missing');if(!opt)return{};const armed=C.applyCandidate(m,hero.id,opt.id,opt.targetId,'TT051_VALIDATION',opt);check(armed.ok&&armed.targetId===opt.targetId,'one-touch exact target arm failed');const start=m.time;let ev=null;for(let i=0;i<100&&!ev;i++){E.step(m,.04);ev=eventAfter(m,start,['PASS'],hero.id);}check(!!ev,'one-touch pass was not executed at contact');check(ev?.targetId===opt.targetId,`one-touch exact target changed ${ev?.targetId} != ${opt.targetId}`);check((m.stats.oneTouchPasses||0)>0,'one-touch pass stat missing');return{targetId:opt.targetId,eventTargetId:ev?.targetId||null,oneTouchPasses:m.stats.oneTouchPasses||0};
}

function aerialHeaderChoice(){
 let sample=null;for(let k=0;k<10&&!sample;k++){const m=prep(`TT051-HEADER-${k}`);spreadAway(m,100);const src=B.playerById(m,'H-RW'),hero=B.playerById(m,'H-ST');place(src,84,60);place(hero,93,34,1.0,0,'ATTACK_NEAR_POST');m.protagonistControllerId=hero.id;m.protagonistExplicitActionRequired=true;B.setControlled(m,src);B.executePass(m,src,hero,'CROSS',{block:0,open:6,forward:9,d:27,running:true},'TT051_CROSS');const f=waitReceiving(m,hero.id,180,.04,'HEADER_SHOT');if(!f)continue;const opt=f.candidates.find(c=>c.id==='HEADER_SHOT');const arm=C.applyCandidate(m,hero.id,'HEADER_SHOT',null,'TT051_VALIDATION',opt);if(!arm.ok)continue;const start=m.time;let ev=null;for(let i=0;i<140&&!ev;i++){E.step(m,.04);ev=eventAfter(m,start,['HEADER_SHOT'],hero.id);}if(ev)sample={seed:k,at:round(ev.t),headerShots:m.stats.userHeaderShots||0,crossHeaderAttempts:m.stats.crossHeaderAttempts||0};}
 check(!!sample,'user HEADER_SHOT never reached physical cross contact in 10 clean trials');return sample||{};
}

function carryVisibility(){
 const s=P.create('TT051-CARRY-FLOOR',{heroPlayerId:'H-ST',mode:'PLAYER_ALL'}),m=s.m;spreadAway(m);m.restart=null;m.phase='OPEN_PLAY';m.time=300;m.nextShape=1e9;const st=B.playerById(m,'H-ST');place(st,76.5,34);B.setControlled(m,st);st.controlledSince=m.time-.8;st.nextThink=m.time;const q=P.inspect(s),has=q?.options?.some(o=>o.id==='CARRY');check(has,`1_2 regression: physically open CARRY absent options=${JSON.stringify(q?.options?.map(o=>o.id)||[])}`);return{space:round(q?.frame?.space||0),pressure:round(q?.frame?.pressure||0),options:q?.options?.map(o=>({id:o.id,targetId:o.targetId||null}))||[]};
}

function tacticalLane(){
 const m=prep('TT051-CARRIER-LANE');spreadAway(m);const cm=B.playerById(m,'H-CM'),st=B.playerById(m,'H-ST');place(cm,79,34);place(st,81.2,34.4);B.setControlled(m,cm);cm.tx=88;cm.ty=34;m.protagonistControllerId=cm.id;m.protagonistExplicitActionRequired=true;T.assign(m);const sl={x:st.tx,y:st.ty},lateral=Math.abs(st.ty-cm.ty);check(st.tacticalTask==='ST_CLEAR_CARRIER_LANE'||lateral>=4.5,`1_7 regression: ST did not clear CM carrier lane task=${st.tacticalTask} lateral=${lateral}`);return{task:st.tacticalTask,target:{x:round(sl.x),y:round(sl.y)},carrierTarget:{x:round(cm.tx),y:round(cm.ty)},lateral:round(lateral)};
}
function farSideRun(){
 const m=prep('TT051-FAR-RUN');spreadAway(m);const owner=B.playerById(m,'H-RCM'),lw=B.playerById(m,'H-LW');place(owner,74,50);place(lw,78,15);B.setControlled(m,owner);m.ball.x=owner.x;m.ball.y=owner.y;T.assign(m);const first={task:lw.tacticalTask,until:lw.farSideRunUntil,y:lw.farSideRunY,tx:lw.tx,ty:lw.ty};m.time+=.45;m.ball.x+=1.2;T.assign(m);const second={task:lw.tacticalTask,until:lw.farSideRunUntil,y:lw.farSideRunY,tx:lw.tx,ty:lw.ty};check(first.task==='FAR_SIDE_RUN'&&second.task==='FAR_SIDE_RUN','1_5 regression: far-side runner not committed');check(Number.isFinite(first.until)&&Math.abs(first.until-second.until)<.01,'far-side run commitment reset every tactical tick');check(Math.abs((first.y??99)-(second.y??-99))<.2,'far-side run lane redrawn during commitment');return{first,second};
}
function freeKickRecovery(){
 const m=E.createMatch('TT051-FK-RECOVERY');m.time=500;m.phase='OPEN_PLAY';B.startDeadRestart(m,'FREE_KICK','HOME',74,34);let seen=null;for(let i=0;i<140&&!seen;i++){E.step(m,.10);if(m.restartRecovery?.kind==='FREE_KICK')seen={...m.restartRecovery};}check(!!seen,'1_3 regression: FREE_KICK wall recovery state never created');check((seen?.wallIds||[]).length===3,`free-kick wall IDs not preserved ${JSON.stringify(seen?.wallIds||[])}`);if(seen){T.assign(m);const tasks=seen.wallIds.map(id=>B.playerById(m,id)?.tacticalTask);check(tasks.some(x=>x==='SET_PIECE_RECOVERY')||m.time>=seen.until,'free-kick wall did not begin shape recovery');return{wallIds:seen.wallIds,tasks};}return{};
}

function importantWindow(){
 const boundary={id:'IW-VALID',type:'IMPORTANT_2D_WINDOW',sceneId:'IW-VALID',atSecond:1200,sourceEventId:'VALID-SHOT',reason:'NON_HERO_SHOT',focusPlayerId:'H-RW',focusTeam:'HOME',heroPlayerId:'H-ST',heroRole:'ST',heroTeam:'HOME',stateSnapshot:{second:1200,score:{HOME:1,AWAY:1},possession:'HOME',zone:'BOX',phase:'CHANCE',danger:.82,ball:{team:'HOME',lane:'RIGHT',progress:.93,ownerId:'H-RW'},structure:{HOME:{midfieldOccupancy:3,backLineOccupancy:4,width:54,lineHeight:55,transitionDebt:.1},AWAY:{midfieldOccupancy:3,backLineOccupancy:4,width:48,lineHeight:45,transitionDebt:.1}}},preContext:[],futureOutcomePrecomputed:false,choicePrecomputed:false};
 const out=A.runImportantWindow(boundary,{runtimeDir:RUNTIME,seed:'TT051-IMPORTANT-SMOKE',durationSeconds:10});check(out.futureOutcomePrecomputed===false,'important window precomputed outcome');check(out.pending?.futureOutcomePrecomputed!==true,'important window pending precomputed');const heroBad=(out.actualEvents||[]).find(e=>e.actorId==='H-ST'&&['PASS','SHOT','HEADER_SHOT','TAKE_ON'].includes(e.type)&&!out.hadChoice);check(!heroBad,`important window produced unchosen protagonist action ${heroBad?.type}`);return{hadChoice:!!out.pending,eventTypes:(out.actualEvents||[]).map(e=>e.type),score:out.snapshot?.score||null,noMeaningfulChoice:out.noMeaningfulChoice||null};
}

function exactTargetFrozen(){
 const m=prep('TT051-EXACT-TARGET');spreadAway(m);const st=B.playerById(m,'H-ST');place(st,68,34);B.setControlled(m,st);m.protagonistControllerId=st.id;m.protagonistExplicitActionRequired=true;const f=C.inspect(m,st.id),c=(f?.candidates||[]).find(x=>x.targetId&&['AVAILABLE_PASS','PROGRESSIVE_PASS','SAFE_PASS','THROUGH_PASS'].includes(x.id));check(!!c,'exact-target validation candidate missing');if(!c)return{};const r=C.applyCandidate(m,st.id,c.id,c.targetId,'TT051_FROZEN',c);check(r.ok&&r.targetId===c.targetId,`exact target regression ${c.targetId} -> ${r.targetId}`);check(m.ball.intendedReceiverId===c.targetId,`ball intended target regression ${m.ball.intendedReceiverId} != ${c.targetId}`);return{choiceId:c.id,targetId:c.targetId,resolved:r.targetId,intended:m.ball.intendedReceiverId};
}

function maxBurst(times,w=5){let best=0;for(let i=0,j=0;i<times.length;i++){while(times[i]-times[j]>w)j++;best=Math.max(best,i-j+1);}return best;}
function choose(p,index){const pref=['DIRECTIONAL_TOUCH','ONE_TOUCH_PASS','HEADER_PASS','PROGRESSIVE_PASS','THROUGH_PASS','AVAILABLE_PASS','CARRY','SAFE_PASS','SECURE_TOUCH','HOLD','DELAY','BLOCK_LANE','TACKLE','SHORT_DISTRIBUTION','LONG_DISTRIBUTION'];for(const id of pref){const a=(p?.options||[]).filter(o=>o.id===id);if(a.length)return a[index%a.length];}return p?.options?.[0]||null;}
function resolveBoundary(b,role,mi){let o;if(b.type==='IMPORTANT_2D_WINDOW')o=A.runImportantWindow(b,{runtimeDir:RUNTIME,seed:`TT051-IMP-${role}-${mi}-${b.sceneId}`});else if(b.type==='SET_PIECE_2D_WINDOW')o=A.runSetPieceWindow(b,{runtimeDir:RUNTIME,seed:`TT051-SP-${role}-${mi}`});else if(b.type==='FINAL_2D_WINDOW')return A.runFinalWindow(b,{runtimeDir:RUNTIME,seed:`TT051-FINAL-${role}-${mi}`,targetSecond:5400});else o=A.runToChoice(b,{runtimeDir:RUNTIME,seed:`TT051-HR-${role}-${mi}-${b.sceneId}`});let count=0,guard=0;while(o.state?.pending&&guard++<8){const c=choose(o.state.pending,count);if(!c)break;try{A.applyChoiceAndAdvance(o,c.id,c.targetId||null,{maxPostSeconds:12});count++;}catch(e){failures.push(`visible choice apply failure ${role} ${b.type} ${c.id}->${c.targetId||'-'} ${e.message}`);o.state.pending=null;break;}}const snap=o.snapshot||o.E.snapshot(o.state.m),events=(o.state?.m?.events||o.actualEvents||[]).filter(e=>Number(e.t)>=Number(b.atSecond)-.001);return{...o,snapshot:snap,actualEvents:events,hadChoice:count>0||!!o.hadChoice,choiceCount:count};}
function hybridRegression(){
 const defs=[['ST','H-ST'],['CM','H-CM'],['CB','H-LCB'],['GK','H-GK']],out={};for(const [role,id] of defs){const world=H.createSession({seed:`TT051-HYBRID-${role}`,heroTeam:'HOME',heroRole:role,heroPlayerId:id}),times=[],episodeCounts=[],important=0;let guard=0;while(world.status!=='FINISHED'&&guard++<700){const adv=H.advanceUntilBoundary(world);if(adv.status==='FINISHED')break;const b=adv.boundary;if(!b||b.type==='MATCH_END')break;if(b.type==='IMPORTANT_2D_WINDOW')important++;const r=resolveBoundary(b,role,0);if(r.choiceCount){episodeCounts.push(r.choiceCount);for(let i=0;i<r.choiceCount;i++)times.push(Number(r.state?.m?.time||b.atSecond));}H.resumeFromHighRes(world,{snapshot:r.snapshot,hadChoice:r.hadChoice,result:r.result||r.state?.lastResult||null,actualEvents:r.actualEvents||[]});}
   const lowResGoals=(world.state.resolvedEvents||[]).filter(e=>e.kind==='GOAL').length,maxEp=Math.max(0,...episodeCounts),burst=maxBurst(times);check(lowResGoals===0,`${role}: low-resolution GOAL remained after important-shot promotion`);check(burst<=3,`${role}: choice burst regression ${burst}/5s`);const limits={ST:40,CM:42,CB:34,GK:22};check(times.length<=limits[role],`${role}: TT0.51 choice count excessive ${times.length}`);if(important>30)watch.push(`${role}: important 2D windows high ${important}`);out[role]={choices:times.length,maxBurst5s:burst,maxEpisodeChoices:maxEp,importantWindows:important,score:{...world.state.score},lowResGoals};}
 return out;
}

(async()=>{const result={schemaVersion:'TT051_VALIDATION_1.0',version:'TT-0.51',static:staticChecks(),through:throughTrajectory(),directionalReception:directionalReception(),oneTouchPass:oneTouchPass(),aerialHeader:aerialHeaderChoice(),carryVisibility:carryVisibility(),carrierLane:tacticalLane(),farSideRun:farSideRun(),freeKickRecovery:freeKickRecovery(),importantWindow:importantWindow(),exactTarget:exactTargetFrozen()};result.hybridRegression=hybridRegression();result.canonical={futureChoicePrecomputed:false,futureOutcomePrecomputed:false,exactTargetImmutable:failures.every(x=>!x.includes('exact target')),unchosenProtagonistActionForbidden:failures.every(x=>!x.includes('unchosen protagonist'))};result.watch=watch;result.failures=failures;result.status=failures.length?'FAIL':'PASS';console.log(JSON.stringify(result));process.exit(failures.length?1:0);})().catch(e=>{console.log(JSON.stringify({schemaVersion:'TT051_VALIDATION_1.0',version:'TT-0.51',status:'FAIL',failures:[String(e.stack||e)]}));process.exit(1);});
