'use strict';
const path=require('path');const root=path.resolve(process.argv[2]||'.');
const E=require(path.join(root,'runtime/continuous_match_core.js'));
const B=E.choiceActionBridge();
function place(p,x,y){p.x=x;p.y=y;p.tx=x;p.ty=y;p.vx=0;p.vy=0;p.hasBall=false;p.nextThink=99999;p.lockTargetUntil=0;p.runUntil=0;p.action='HOLD_SHAPE';p.tacticalTask='HOLD_SHAPE';p.markTargetId=null;}
function run(seed){const m=E.createMatch(seed,{});m.time=1700;m.phase='OPEN_PLAY';m.restart=null;m.completed=false;m.possession='HOME';m.transitionUntil=0;m.nextShape=m.time;
 const ps=m.playersById;for(const p of m.players){if(p.team==='HOME')place(p,58,8+((p.slot||'').length%7)*8);else place(p,82,8+((p.slot||'').length%7)*8);}
 const owner=ps['H-RW'],st=ps['H-ST'],rcb=ps['A-RCB'];place(owner,80,51);place(st,86,34);place(rcb,84.8,35.0);m.protagonistControllerId=owner.id;m.protagonistExplicitActionRequired=true;B.setControlled(m,owner,true);owner.controlledSince=m.time-2;owner.nextThink=m.time;
 // keep the wide carrier away from the striker-marker pair so this remains an off-ball marking test.
 owner.tx=80;owner.ty=51;owner.action='HOLD_BALL';owner.tacticalTask='HOLD_BALL';
 const rows=[];let lastTask=null,lastMark=null,taskSwitches=0,markSwitches=0,sideFlips=0,lastSide=0;
 for(let i=0;i<140;i++){E.step(m,.1);const d=Math.hypot(st.x-rcb.x,st.y-rcb.y),side=Math.sign(rcb.y-st.y);if(lastSide&&side&&side!==lastSide)sideFlips++;if(side)lastSide=side;if(lastTask!==null&&rcb.tacticalTask!==lastTask)taskSwitches++;if(lastMark!==null&&(rcb.markTargetId||null)!==lastMark)markSwitches++;lastTask=rcb.tacticalTask;lastMark=rcb.markTargetId||null;rows.push({t:m.time,d,st:[st.x,st.y],rcb:[rcb.x,rcb.y],stV:Math.hypot(st.vx,st.vy),rcbV:Math.hypot(rcb.vx,rcb.vy),task:rcb.tacticalTask,mark:rcb.markTargetId||null,targetD:Math.hypot((st.tx??st.x)-(rcb.tx??rcb.x),(st.ty??st.y)-(rcb.ty??rcb.y))});if(m.possession!=='HOME')break;}
 const under=x=>rows.filter(r=>r.d<x);const span=a=>a.length>1?a.at(-1).t-a[0].t:0;const a12=under(1.2),a14=under(1.4),a16=under(1.6);let path=0,net=0;for(let i=1;i<rows.length;i++)path+=Math.hypot(rows[i].rcb[0]-rows[i-1].rcb[0],rows[i].rcb[1]-rows[i-1].rcb[1]);if(rows.length>1)net=Math.hypot(rows.at(-1).rcb[0]-rows[0].rcb[0],rows.at(-1).rcb[1]-rows[0].rcb[1]);return{seed,samples:rows.length,minD:Math.min(...rows.map(r=>r.d)),under12:{n:a12.length,span:span(a12)},under14:{n:a14.length,span:span(a14)},under16:{n:a16.length,span:span(a16)},sideFlips,taskSwitches,markSwitches,rcbPath:path,rcbNet:net,pathToNet:path/Math.max(.1,net),last:rows.at(-1),taskSet:[...new Set(rows.map(r=>r.task))],markSet:[...new Set(rows.map(r=>r.mark))]};}
const cases=['MARK-JITTER-A','MARK-JITTER-B','MARK-JITTER-C','MARK-JITTER-D'].map(run);const worst=cases.slice().sort((a,b)=>b.under16.span-a.under16.span||b.sideFlips-a.sideFlips)[0];const issue=worst.under16.span>=5&&worst.minD<=1.08;const out={schemaVersion:'FLR_TT051_OFFBALL_MARK_JITTER_DIAG_1.0',issueReproduced:issue,pass:!issue,cases,worst,criteria:{issue:'off-ball ST/CB stay <1.6m for >=5s and hit ~1.05m physical collision floor'}};console.log(JSON.stringify(out,null,2));process.exit(issue?1:0);
