'use strict';
const assert=require('assert');
const restart=require('../runtime/restart_movement.js');
globalThis.FLRPG_RESTART_MOVEMENT=restart;
require('../runtime/free_kick_wall_model.js');
const R=globalThis.FLRPG_RESTART_MOVEMENT;
const slots=[['GK','GK',5.5,34],['LB','FB',20,10],['LCB','CB',18.5,27],['RCB','CB',18.5,41],['RB','FB',20,58],['LCM','CM',39,21],['CM','CM',43,34],['RCM','CM',39,47],['LW','WF',66,11],['ST','ST',68,34],['RW','WF',66,57]];
function makePlayers(){const out=[];for(const team of ['HOME','AWAY'])for(const [slot,role,lx,ly] of slots)out.push({id:`${team[0]}-${slot}`,team,slot,role,x:team==='HOME'?lx:105-lx,y:team==='HOME'?ly:68-ly,tx:0,ty:0,action:'HOLD_SHAPE',tacticalTask:'HOLD_SHAPE',sprint:false,markTargetId:null});return out;}
function makeMatch(x,y,team='HOME',indirect=false,seed='V36-FK-WALL-QA'){const players=makePlayers(),m={seed,time:100,players,restart:{kind:'FREE_KICK',team,x:team==='HOME'?x:105-x,y:team==='HOME'?y:68-y,setupStartedAt:100,indirect}};m.playersById=Object.fromEntries(players.map(p=>[p.id,p]));return m;}
function inspect(x,y,team='HOME',indirect=false){const m=makeMatch(x,y,team,indirect,`QA-${x}-${y}-${team}-${indirect}`),s=R.begin(m),w=s.freeKickWall,wallTargets=w.wallPlayerIds.map(id=>s.targets[id]),ball={x:m.restart.x,y:m.restart.y},minWallDistance=wallTargets.length?Math.min(...wallTargets.map(t=>Math.hypot(t.x-ball.x,t.y-ball.y))):Infinity,wallSet=new Set(w.wallPlayerIds),nonWallCore=m.players.filter(p=>p.team!==team&&['CB','FB','CM'].includes(p.role)&&!wallSet.has(p.id));let minAttackerDistance=Infinity;if(w.count>=3){for(const p of m.players.filter(p=>p.team===team&&p.id!==s.kickerId)){const t=s.targets[p.id];if(!t)continue;for(const wt of wallTargets)minAttackerDistance=Math.min(minAttackerDistance,Math.hypot(t.x-wt.x,t.y-wt.y));}}const ids=[...w.wallPlayerIds];R.assign(m);assert.deepStrictEqual(m.restart.setup.freeKickWall.wallPlayerIds,ids,'wall membership changed during setup');assert.ok(w.count===0||minWallDistance>=9.15-1e-9,`wall too close: ${minWallDistance}`);assert.ok(nonWallCore.length>=3,`insufficient box/second-ball core: ${nonWallCore.length}`);if(w.count>=3)assert.ok(minAttackerDistance>=1-1e-9,`attacker too close to wall: ${minAttackerDistance}`);const gk=m.players.find(p=>p.team!==team&&p.role==='GK');assert.equal(s.targets[gk.id].task,'FREE_KICK_GK_COMPLEMENT');return{count:w.count,minWallDistance,nonWallCore:nonWallCore.length,gkTarget:w.gkTarget};}
const directCases=[[88,34,5],[82,34,4],[76,34,3],[70,34,2],[63,34,1],[82,10,1],[88,10,1],[82,58,1],[88,58,1]];
for(const [x,y,expected] of directCases)assert.equal(inspect(x,y).count,expected,`unexpected wall count at ${x},${y}`);
assert.equal(inspect(88,34,'HOME',true).count,2,'close indirect wall count');assert.equal(inspect(76,34,'HOME',true).count,1,'medium indirect wall count');
const left=inspect(82,20),right=inspect(82,48);assert.equal(left.count,right.count,'left/right count asymmetry');assert.ok(Math.abs(left.gkTarget.y+right.gkTarget.y-68)<0.05,'GK complement not mirrored');
const readyMatch=makeMatch(82,34),readySetup=R.begin(readyMatch),first=R.readiness(readyMatch);assert.equal(first.wallReady,false,'wall incorrectly ready at setup start');for(const id of readySetup.freeKickWall.wallPlayerIds){const p=readyMatch.playersById[id],t=readySetup.targets[id];p.x=t.x;p.y=t.y;}const second=R.readiness(readyMatch);assert.equal(second.wallReady,true,'wall did not become ready after arriving');
const clearanceMatch=makeMatch(82,34),clearanceSetup=R.begin(clearanceMatch),wallId=clearanceSetup.freeKickWall.wallPlayerIds[0],wallTarget=clearanceSetup.targets[wallId],attacker=clearanceMatch.players.find(p=>p.team==='HOME'&&p.id!==clearanceSetup.kickerId&&p.role==='CM');clearanceSetup.targets[attacker.id]={x:wallTarget.x,y:wallTarget.y,task:'QA_INTRUSION',required:true,sprint:false};R.assign(clearanceMatch);const moved=clearanceSetup.targets[attacker.id],minClear=Math.min(...clearanceSetup.freeKickWall.wallPlayerIds.map(id=>{const t=clearanceSetup.targets[id];return Math.hypot(moved.x-t.x,moved.y-t.y);}));assert.ok(minClear>=1,'attacker 1m wall exclusion failed');
console.log(JSON.stringify({verdict:'PASS_V36_FREE_KICK_WALL_BOUNDED',version:R.FREE_KICK_WALL_VERSION,directCases:directCases.length,checks:['distance>=9.15m','variable-count','left-right-mirror','GK-complement','box-core>=3','membership-stable','wall-readiness','attacker-clearance>=1m']},null,2));
