'use strict';

/* Snapshot-only V37 movement gate. It clones input and never calls engine/RNG. */
const DEAD=new Set(['SET_PIECE_SETUP','GOAL_CELEBRATION','KICKOFF','RESTART','DEAD_BALL']);
const RULE_IDS=Object.freeze(['A1','A2','A3','A4','A5','A6','B1','B2','B3','B4','C1','C2','C3','C4','D1','D2','D3','D4','E1','E2','E3','F1','F2','F3','F4']);
const FAMILY_RULES=Object.freeze({DEFENCE:['A1','A2','A3','A4','A5','A6','E1','E2','E3','F1','F2','F3','F4'],MIDFIELD:['B1','B2','B3','B4'],ATTACK:['C1','C2','C3','C4'],TRANSITION:['D1','D2','D3','D4']});
const SEVERITY_POLICY=Object.freeze({A1:'MANDATORY_HARD_FAIL',A2:'WATCH_ONLY',A3:'MANDATORY_HARD_FAIL',A4:'MANDATORY_HARD_FAIL',A5:'MANDATORY_HARD_FAIL',A6:'WATCH_ONLY',B1:'WATCH_ONLY',B2:'WATCH_ONLY',B3:'WATCH_ONLY',B4:'TARGETED_ONLY',C1:'WATCH_ONLY',C2:'MANDATORY_HARD_FAIL',C3:'WATCH_ONLY',C4:'WATCH_ONLY',D1:'MANDATORY_HARD_FAIL',D2:'MANDATORY_HARD_FAIL',D3:'MANDATORY_HARD_FAIL',D4:'MANDATORY_HARD_FAIL',E1:'WATCH_ONLY',E2:'MANDATORY_HARD_FAIL',E3:'WATCH_ONLY',F1:'WATCH_ONLY',F2:'TARGETED_ONLY',F3:'TARGETED_ONLY',F4:'TARGETED_ONLY'});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d, clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const laneSide=p=>{const s=`${p?.slot||''}|${p?.id||''}`.toUpperCase();return s.includes('LB')||s.includes('LW')||s.includes('LCM')||s.includes('LCB')?-1:s.includes('RB')||s.includes('RW')||s.includes('RCM')||s.includes('RCB')?1:0;};
const dist=(a,b)=>Math.hypot(n(a?.x)-n(b?.x),n(a?.y)-n(b?.y)), task=p=>String(p?.tacticalTask||p?.action||'HOLD').toUpperCase();
const phase=f=>String(f?.phase||f?.context||'OPEN_PLAY').toUpperCase(), isDead=f=>DEAD.has(phase(f))||String(f?.ball?.mode||'').toUpperCase()==='DEAD'||!!f?.restart;
const localX=(p,t)=>t==='AWAY'?105-n(p.x):n(p.x), localY=p=>n(p.y), ball=f=>f?.ball||{x:52.5,y:34};
const players=(f,t)=> (f?.players||[]).filter(p=>!t||p.team===t), other=t=>t==='HOME'?'AWAY':'HOME';
const role=p=>String(p?.slot||p?.role||'').toUpperCase();
function roleGroup(p){const r=role(p);if(r==='GK'||r.includes('KEEPER'))return'GK';if(/^(LB|RB|FB|LWB|RWB|LCB|RCB|CB|BACK)/.test(r))return'BACK';if(/^(LCM|RCM|CM|DM|AM|MF|MID)/.test(r))return'MID';if(/^(LW|RW|WF|W|ST|CF|SS|FRONT)/.test(r))return'FRONT';return'';}
function intent(p){return[p?.intentCategory,p?.responsibility,p?.assignedZone,p?.zoneLabel,p?.tacticalTask,p?.action].filter(Boolean).join('|').toUpperCase();}
function has(p,re){return re.test(intent(p));} function team(f,t,g){return players(f,t).filter(p=>roleGroup(p)===g);}
function lane(y){return y<=27?'LEFT':y>=41?'RIGHT':'CENTRE';} function opposite(y,by){const a=lane(y),b=lane(by);return b!=='CENTRE'&&a!=='CENTRE'&&a!==b;}
function setPieceCover(p,threat,f){
  if(!setPiece(f)||!p||!threat)return false;
  const t=task(p),explicit=/^(CORNER|FREE_KICK)_/.test(t)&&/(MARK|ZONE|POST|EDGE|REST|COUNTER|WALL|SECOND_BALL|TRACK|CHANNEL)/.test(t);
  if(!explicit)return false;
  // A set-piece zone is valid cover only for the channel it actually owns;
  // this keeps malformed/static set-piece controls distinguishable.
  return Math.abs(localY(p)-localY(threat))<=14;
}
function cover(p,threat,f){if(!p||!threat)return false;return p.markTargetId===threat.id||p.targetId===threat.id||setPieceCover(p,threat,f)||(has(p,/MARK|COVER|TUCK|WEAK|FAR|REST|BALANCE|SCREEN|SECOND_BALL/)&&((p.assignedZone||p.zoneLabel||'').toUpperCase().includes(lane(threat.y))||has(p,/WEAK|FAR|TUCK|REST|BALANCE/)));}
function setPiece(f){return/CORNER|FREE_KICK|SET_PIECE/.test(phase(f))||!!f?.setPieceStage||!!f?.setPiece;}
function attacking(f){return f?.possession||f?.ball?.ownerTeam||f?.ball?.team||null;}
function interval(fs,pred,min=.55){const out=[];let rows=[];const flush=()=>{if(rows.length&&n(rows.at(-1).time)-n(rows[0].time)>=min)out.push(rows);rows=[];};for(const f of fs)pred(f)?rows.push(f):flush();flush();return out;}
function finding(id,fam,severity,t,ps,rows,why,context){const f=rows[0]||{};return{ruleId:id,family:fam,severity,team:t,players:ps.map(p=>p.id||p),startTime:n(f.time),endTime:n(rows.at(-1)?.time,f.time),evidence:{positions:ps.map(p=>({id:p.id,role:role(p),roleGroup:roleGroup(p),x:n(p.x),y:n(p.y),tx:n(p.tx,n(p.x)),ty:n(p.ty,n(p.y)),targetId:p.targetId||p.markTargetId||null,intent:intent(p)})),samples:rows.map(x=>({time:n(x.time),phase:phase(x),boundaryId:x.boundaryId||null,ball:{x:n(ball(x).x),y:n(ball(x).y),mode:ball(x).mode||null,ownerId:ball(x).ownerId||null}}))},context,explanation:why};}
function sev(id,seconds,immediate=false){const p=SEVERITY_POLICY[id];if(p==='WATCH_ONLY'||p==='TARGETED_ONLY')return seconds>=.4?'WATCH':null;return immediate||seconds>=.65?'HARD_FAIL':seconds>=.4?'WATCH':null;}

function analyze(input){
  const frames=clone(Array.isArray(input)?input:(input?.frames||[])),findings=[];
  const teams=[...new Set(frames.flatMap(f=>players(f).map(p=>p.team)).filter(Boolean))];
  const add=(id,fam,t,ps,rows,why,ctx={},immediate=false)=>{const s=sev(id,n(rows.at(-1)?.time)-n(rows[0]?.time),immediate);if(s)findings.push(finding(id,fam,s,t,ps,rows,why,ctx));};
  for(const t of teams){const fs=frames.filter(f=>!isDead(f));
    for(const id of ['A1'])for(const rows of interval(fs,f=>{const ps=[...team(f,t,'BACK'),...team(f,t,'MID')],c=ps.filter(p=>dist(p,ball(f))<9);return c.length>=3&&!c.some(p=>has(p,/COVER|SCREEN|BALANCE|SECOND|REST|LANE/));}))add(id,'DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,'Multiple defenders press the ball without a distinct cover/screen layer.',{requiresSpatialPrimaryAndCover:true});
    for(const rows of interval(fs,f=>[...team(f,t,'BACK'),...team(f,t,'MID')].filter(p=>Math.abs(localY(p)-34)<11&&localX(p,t)<78).length===0,.7))add('A2','DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,'Central protection is absent; threat-relative metadata is not yet sufficient for blocking.',{status:'WATCH_ONLY'});
    for(const id of ['A3','A4'])for(const rows of interval(fs,f=>{const bs=team(f,t,'BACK'),hi=bs.filter(p=>/^(LB|RB|FB|LWB|RWB)$/.test(role(p))&&localX(p,t)>72);if(!hi.length)return false;const rest=bs.filter(p=>!hi.includes(p)),cm=team(f,t,'MID');const comp=rest.filter(p=>/^(CB|LCB|RCB)$/.test(role(p))&&localX(p,t)>45).length>=2||rest.some(p=>/^(LB|RB|FB|LWB|RWB)$/.test(role(p))&&localX(p,t)<35)||cm.some(p=>localX(p,t)<55&&Math.abs(localY(p)-34)>5);return id==='A3'?!comp:!comp&&bs.length>=4&&Math.max(...bs.map(p=>localX(p,t)))-Math.min(...bs.map(p=>localX(p,t)))>24&&bs.filter(p=>has(p,/HOLD|BALANCE/)).length>=3;}))add(id,'DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,id==='A3'?'High fullback has no positional rest-defence compensation.':'High fullback leaves a frozen nominal back line.',{positionEvidenceRequired:true});
    for(const rows of interval(fs,f=>{const b=ball(f),th=players(f,other(t)).find(p=>roleGroup(p)==='FRONT'&&opposite(p.y,b.y)&&localX(p,other(t))>55);if(!th)return false;const ds=[...team(f,t,'BACK'),...team(f,t,'MID')],compression=ds.filter(p=>!opposite(p.y,b.y)&&dist(p,b)<18).length>=2;return compression&&(localX(th,other(t))>65||dist(th,b)<28)&&!ds.some(p=>cover(p,th,f))&&!ds.filter(p=>opposite(p.y,b.y)).some(p=>has(p,/COVER|TUCK|REST|BALANCE|MARK|WEAK|FAR/));}))add('A5','DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,'True opposite channel is threatened after ball-side compression, with no spatial cover, mark, tuck, or rest ownership.',{centralNeutralBand:'y=27..41',requires:['threat/lane','compression','no spatial cover','no markTargetId/zone ownership'],setPieceRule:'explicit marker/zone/rest/channel responsibility counts only when spatially aligned'});
    for(const rows of interval(fs,f=>{const ds=[...team(f,t,'BACK'),...team(f,t,'MID')],ids=ds.filter(p=>dist(p,ball(f))<11).map(p=>p.targetId||p.markTargetId).filter(Boolean),danger=players(f,other(t)).filter(p=>roleGroup(p)==='FRONT'&&localX(p,other(t))>65);return ids.length>=3&&new Set(ids).size===1&&danger.some(p=>!ds.some(d=>dist(d,p)<12));}))add('A6','DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,'Three defenders duplicate one explicit target while another attacker is unowned.',{status:'WATCH_ONLY'});
    for(const id of ['B1','B2'])for(const rows of interval(fs,f=>{const ps=team(f,t,'MID');return ps.length>=2&&ps.every(p=>dist(p,ball(f))<9)&&!ps.some(p=>has(p,/SCREEN|SECOND|LANE|BALANCE|COVER|DROP/));}))add(id,'MIDFIELD',t,team(fs[0],t,'MID'),rows,id==='B1'?'Midfielders have no depth stagger.':'All available midfielders duplicate pressure.',{allowAsymmetricMidfield:true});
    for(const rows of interval(fs,f=>{const ms=team(f,t,'MID'),bs=team(f,t,'BACK'),fr=team(f,t,'FRONT');return ms.length>=2&&bs.length>=2&&fr.length>=1&&ms.every(p=>localX(p,t)>58&&localX(p,t)<70)&&Math.min(...bs.map(p=>localX(p,t)))<42&&Math.max(...fr.map(p=>localX(p,t)))>82&&!f.transitionCause&&!f.previousPhase;}))add('B3','MIDFIELD',t,team(fs[0],t,'MID'),rows,'Midfield is detached from both lines without a transition rationale.',{threatRelativeFollowup:'required before promotion'});
    for(const rows of interval(fs,f=>!setPiece(f)&&team(f,t,'MID').length>=2&&team(f,t,'MID').every(p=>dist(p,ball(f))<9)&&Math.max(...team(f,t,'MID').map(p=>localY(p)))-Math.min(...team(f,t,'MID').map(p=>localY(p)))<4))add('B4','MIDFIELD',t,team(fs[0],t,'MID'),rows,'Open-play convergence lacks a handoff; set-piece clusters use the relational subrule.',{status:'TARGETED_ONLY'});
    for(const rows of interval(fs,f=>setPiece(f)&&attacking(f)===t&&team(f,t,'FRONT').filter(p=>dist(p,ball(f))<14).length>=2&&team(f,t,'FRONT').every(p=>!has(p,/RUN|WIDTH|FAR|NEAR|DEPTH|SECOND|REST|BLOCK/))&&team(f,t,'MID').length>=2&&team(f,t,'MID').every(p=>has(p,/HOLD|LINE|SETUP/))&&!team(f,t,'MID').some(p=>has(p,/SECOND_BALL|EDGE|REST|COVER|MARK|ZONE/))))add('B4','MIDFIELD',t,[...team(fs[0],t,'MID'),...team(fs[0],t,'FRONT')],rows,'Set-piece attackers idle near the taker while midfield/defence retain a nominal line with no differentiated role.',{setPieceRelationalSubrule:'STATIC_STRUCTURE',requiresStageAndIntent:true});
    for(const rows of interval(fs,f=>{const w=team(f,t,'FRONT').filter(p=>/^(LW|RW|WF)$/.test(role(p)));return w.length>=2&&Math.abs(localY(w[0])-localY(w[1]))<7&&!w.some(p=>has(p,/WIDTH|SWITCH|HANDOFF|REOCCUPY|FAR_SIDE/));}))add('C1','ATTACK',t,team(fs[0],t,'FRONT'),rows,'Wide attackers abandoned both channels without a handoff.',{normalizedWingerRoles:true});
    for(const rows of interval(fs,f=>{if(attacking(f)!==t)return false;const fr=team(f,t,'FRONT'),st=fr.find(p=>/^(ST|CF|SS)$/.test(role(p)));return!!st&&localX(st,t)<58&&dist(st,ball(f))<10&&fr.length>=2&&!fr.some(p=>p!==st&&localX(p,t)>68)&&!fr.some(p=>p!==st&&has(p,/PIN|FORWARD|OUTLET|RELEASE|HIGH|RUN|WIDTH/));}))add('C2','ATTACK',t,team(fs[0],t,'FRONT'),rows,'In-possession ST joined a deep ball swarm and no forward occupation or valid rotation remains.',{onlyAttackingTeam:true,emptyFrontCollectionDoesNotPass:true,requiresForwardOccupation:true});
    for(const id of ['C3','C4'])for(const rows of interval(fs,f=>{const ps=team(f,t,'FRONT');return ps.length>=2&&ps.filter(p=>dist(p,ball(f))<9).length>=2&&new Set(ps.map(p=>Math.round(localX(p,t)/5))).size===1;}))add(id,'ATTACK',t,team(fs[0],t,'FRONT'),rows,id==='C3'?'Attack lacks support depth.':'Attackers converge without differentiated intent.',{status:'WATCH_ONLY'});
    // Relational audit layer: these controls deliberately remain WATCH/TARGETED
    // until a paired football-valid/invalid corpus proves a universal block.
    for(const rows of interval(fs,f=>{const b=ball(f),opp=other(t),th=players(f,opp).find(p=>role(p)==='WF'&&localX(p,opp)>55&&Math.abs(localY(p)-b.y)>10);if(!th)return false;const side=laneSide(th)|| (localY(th)<34?-1:1),fb=team(f,t,'BACK').find(p=>/^(LB|RB|FB)$/.test(role(p))&&laneSide(p)===side);if(!fb)return false;const fl=localY(fb),abandoned=Math.abs(fl-34)<12||dist(fb,th)>24;const coverers=[...team(f,t,'BACK'),...team(f,t,'MID')].filter(p=>p.id!==fb.id&&Math.abs(localY(p)-localY(th))<10&&dist(p,th)<16);return abandoned&&!cover(fb,th)&&!coverers.some(p=>has(p,/COVER|MARK|CHANNEL|TUCK|WIDE/));}))add('F1','DEFENCE',t,team(fs[0],t,'BACK'),rows,'Dangerous wide opponent has no same-side fullback channel owner or compensating cover.',{status:'WATCH_ONLY',pairedControlRequired:true});
    for(const rows of interval(fs,f=>{if(!setPiece(f))return false;const ps=[...team(f,t,'BACK'),...team(f,t,'MID'),...team(f,t,'FRONT')],keys=ps.map(p=>`${Math.round(n(p.tx,n(p.x))*2)/2},${Math.round(n(p.ty,n(p.y))*2)/2}`),counts=new Map(keys.map(k=>[k,keys.filter(x=>x===k).length]));return [...counts.values()].some(v=>v>=3)&&!ps.filter(p=>counts.get(`${Math.round(n(p.tx,n(p.x))*2)/2},${Math.round(n(p.ty,n(p.y))*2)/2}`)>=3).every(p=>has(p,/WALL|AERIAL|DUEL|NEAR_POST|OVERLOAD/));}))add('F2','DEFENCE',t,players(fs[0],t),rows,'Three or more players converge on one target without a live contest/overload justification.',{status:'TARGETED_ONLY',proximityIsNotEnough:true});
    for(const rows of interval(fs,f=>{const ps=[...team(f,t,'BACK'),...team(f,t,'MID')].filter(p=>p.targetId||p.markTargetId);const groups=new Map();for(const p of ps){const k=`${p.targetId||p.markTargetId}|${roleGroup(p)}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p);}return [...groups.values()].some(g=>g.length>=2&&g.every(p=>Math.abs(localY(p)-34)<8));}))add('F3','DEFENCE',t,[...team(fs[0],t,'BACK'),...team(fs[0],t,'MID')],rows,'Same-line defenders duplicate a target/responsibility instead of splitting channel and second-ball duties.',{status:'TARGETED_ONLY',requiresRoleSplit:true});
    for(const rows of interval(fs,f=>{if(!setPiece(f))return false;const roles=[...team(f,t,'BACK'),...team(f,t,'MID'),...team(f,t,'FRONT')].map(p=>String(p.responsibility||p.assignedRole||p.intentCategory||'').toUpperCase()).filter(Boolean);const distinct=new Set(roles);return roles.length>=3&&distinct.size<3;}))add('F4','DEFENCE',t,players(fs[0],t),rows,'Set-piece roles do not expose distinct marker/zone/edge/outlet/rest layers.',{status:'TARGETED_ONLY',requires:['marker/zone','edge/second-ball','outlet/rest']});
  }
  const live=frames.filter(f=>!isDead(f));
  for(const t of teams){const fs=live.filter(f=>players(f,t).length),addT=(id,pred,ps,why,ctx={},imm=false)=>interval(fs,pred,imm?0:.55).forEach(r=>add(id,'TRANSITION',t,ps(r[0]),r,why,ctx,imm));const bi=fs.findIndex(f=>!!f.boundaryId||!!f.boundaryKind||!!f.choiceBoundary||!!f.sceneBoundary);if(bi>=1){const prev=fs[bi-1],entry=fs[bi],next=fs[bi+1],bs=team(prev,t,'BACK'),now=team(entry,t,'BACK');if(entry.precedingLiveFrameId&&entry.precedingLiveFrameId!==prev.frameId)continue;if(bs.length>=4&&now.length>=4&&bs.filter(p=>{const q=now.find(x=>x.id===p.id);return q&&dist(p,q)>12;}).length>=4&&now.every(p=>Math.abs(localY(p)-34)<18)&&!setPiece(entry))add('D1','TRANSITION',t,now,[prev,entry],'Live shape snaps to a neat line at the actual scene-entry boundary.',{boundaryId:entry.boundaryId,compared:'precedingLiveFrameId -> entry frame'},true);if(next&&team(entry,t,'FRONT').some(p=>localX(p,t)>78)&&now.length>=4&&now.every(p=>localX(p,t)<48)&&now.every(p=>!has(p,/RECOVER|TRACK|COVER|TRANSITION|REST/)))add('D2','TRANSITION',t,now,[entry,next],'Advanced attacker present but defenders reset without recovery responsibility.',{boundaryId:entry.boundaryId,deadBallExemption:true});}
    addT('D3',f=>players(f,t).filter(p=>n(p.vx)===0&&n(p.vy)===0&&Math.abs(n(p.tx,n(p.x))-n(p.x))>18).length>=4,f=>players(f,t),'Several players require impossible travel; target metadata alone is insufficient.',{requiresActualPrecedingFrame:true},true);
    addT('D4',f=>!!(f.previousPhase||f.lastPhase)&&String(f.previousPhase||f.lastPhase).toUpperCase()!==phase(f)&&!!f.ball?.ownerId&&players(f,t).filter(p=>/^(CHASE|PRESS|TRACK)/.test(task(p))).length>=3,f=>players(f,t),'Chase/press roles persist after a possession or phase handoff.',{requiresTransitionCause:true});
    addT('E1',f=>{const p=[...team(f,t,'BACK'),...team(f,t,'MID'),...team(f,t,'FRONT')].find(x=>Number.isFinite(Number(x.nominalX))&&Math.abs(Number(x.nominalX)-localX(x,t))>15);return!!p&&!players(f,t).some(q=>has(q,/COVER|TUCK|REST|REOCCUPY|HANDOFF|BALANCE/));},f=>players(f,t),'A structural zone was vacated without a responsible handoff.',{status:'WATCH_ONLY'});
    addT('E2',f=>{const groups=new Map();for(const p of players(f,t).filter(p=>(p.targetId||p.markTargetId)&&p.intentCategory)){const k=`${p.targetId||p.markTargetId}|${String(p.intentCategory).toUpperCase()}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p);}return[...groups.values()].some(g=>g.length>=3&&g.every(p=>dist(p,ball(f))<12));},f=>players(f,t),'Three players share an explicit non-null target and intent category with spatial convergence.',{nullTargetsExcluded:true,genericTasksDoNotCollapse:true});
    addT('E3',f=>[...team(f,t,'BACK'),...team(f,t,'MID')].filter(p=>Math.abs(localY(p)-34)<9&&localX(p,t)<78).length===0&&team(f,t,'BACK').length>=2,f=>[...team(f,t,'BACK'),...team(f,t,'MID')],'Central connection zone is unowned; not strong enough for blocking.',{status:'WATCH_ONLY'});
  }
  const rules=RULE_IDS.map(id=>({ruleId:id,policy:SEVERITY_POLICY[id],status:findings.some(f=>f.ruleId===id&&f.severity==='HARD_FAIL')?'HARD_FAIL':findings.some(f=>f.ruleId===id)?'WATCH':'PASS'}));
  return{verdict:findings.some(f=>f.severity==='HARD_FAIL')?'FAIL':findings.length?'WATCH':'PASS',rules,findings,ruleIds:RULE_IDS.slice(),severityPolicy:{...SEVERITY_POLICY},metadataContract:['boundaryId','boundaryKind','frameId','precedingLiveFrameId','transitionCause','previousPhase','roleGroup/slot','structuralZone/zoneLabel','intentCategory','assignedZone/markTargetId','setPieceStage','assignedRoleIntent']};
}
function p(id,team,slot,x,y,extra={}){return{id,team,slot,role:slot,x,y,tx:x,ty:y,vx:0,vy:0,tacticalTask:'HOLD',...extra};} function fr(time,ps,extra={}){return{time,phase:'OPEN_PLAY',ball:{mode:'CONTROLLED',x:70,y:34},players:ps,...extra};}
function sequence(kind){const base=[p('LW','HOME','LW',82,10),p('RW','HOME','RW',82,58),p('ST','HOME','ST',84,34),p('LCM','HOME','LCM',60,24),p('CM','HOME','CM',58,34),p('RCM','HOME','RCM',60,44),p('LB','HOME','FB',42,10),p('LCB','HOME','CB',38,25),p('RCB','HOME','CB',38,43),p('RB','HOME','FB',42,58),p('GK','HOME','GK',8,34)],fs=Array.from({length:5},(_,i)=>fr(i*.2,base.map(x=>({...x}))));if(kind==='valid_winger_swap')fs.forEach(f=>{f.players.find(p=>p.id==='LW').y=57;f.players.find(p=>p.id==='RW').y=11;f.players.find(p=>p.id==='LW').responsibility='SWITCH_HANDOFF';f.players.find(p=>p.id==='RW').responsibility='REOCCUPY_WIDTH';});if(kind==='invalid_winger_vacancy')fs.forEach(f=>['LW','RW'].forEach(id=>{const p=f.players.find(x=>x.id===id);p.y=34;p.responsibility='CHASE_BALL';}));if(kind==='valid_high_lb')fs.forEach(f=>{f.players.find(p=>p.id==='LB').x=82;f.players.find(p=>p.id==='LCB').x=52;f.players.find(p=>p.id==='RCB').x=48;});if(kind==='invalid_high_lb')fs.forEach(f=>f.players.find(p=>p.id==='LB').x=82);if(kind==='valid_mid_split')fs.forEach(f=>{f.players.find(p=>p.id==='LCM').x=65;f.players.find(p=>p.id==='LCM').responsibility='PRESS';f.players.find(p=>p.id==='CM').x=55;f.players.find(p=>p.id==='CM').responsibility='SCREEN';f.players.find(p=>p.id==='RCM').x=48;f.players.find(p=>p.id==='RCM').responsibility='SECOND_BALL';});if(kind==='invalid_mid_collapse')fs.forEach(f=>['LCM','CM','RCM'].forEach(id=>{const p=f.players.find(x=>x.id===id);p.x=70;p.y=34;p.targetId='ST';p.tacticalTask='CHASE_LOOSE';}));if(kind==='formation_snap'){const pre=fr(-.2,base.map(x=>({...x})),{frameId:'pre'});fs[0].boundaryId='S1';fs[0].boundaryKind='CHOICE';fs[0].frameId='entry';fs[0].precedingLiveFrameId='pre';fs[0].players.forEach(p=>{p.x+=22;p.y+=8;});return[pre,...fs];}return fs;}
function pairedControls(){const expected={valid_winger_swap:'PASS',invalid_winger_vacancy:'WATCH',valid_high_lb:'PASS',invalid_high_lb:'FAIL',valid_mid_split:'PASS',invalid_mid_collapse:'FAIL',formation_snap:'FAIL'};return Object.entries(expected).map(([name,want])=>{const got=analyze(sequence(name)).verdict;return{name,expected:want,got,ok:got===want};});}
function runSelfTest(){const checks=pairedControls(),input=sequence('valid_mid_split'),before=JSON.stringify(input),a=analyze(input),b=analyze(input);checks.push({name:'READ_ONLY_IDEMPOTENT',ok:before===JSON.stringify(input)&&JSON.stringify(a)===JSON.stringify(b)});return{verdict:checks.every(x=>x.ok)?'PASS':'FAIL',checks};}
if(require.main===module){const r=runSelfTest();console.log(JSON.stringify({module:'V37_WHOLE_TEAM_MOVEMENT_SANITY_GATE',synthetic:r},null,2));process.exitCode=r.verdict==='PASS'?0:1;}
module.exports={analyze,runSelfTest,pairedControls,sequence,constants:{DEAD,RULE_IDS,FAMILY_RULES,SEVERITY_POLICY,roleGroup}};
