'use strict';
const path=require('path');
const R=require('../runtime/restart_movement.js');global.FLRPG_RESTART_MOVEMENT=R;
require('../runtime/free_kick_templates.js');require('../runtime/free_kick_wall_model.js');require('../runtime/v37_set_piece_liveliness_patch.js');require('../runtime/corner_templates.js');
const E=require('../runtime/continuous_match_core.js'),P=require('../runtime/protagonist_match_controller.js'),A=require('../live_v06_scene_authority_browser.js'),H=require('../final_match_rare_scenario_harness.js');
const runtimeDir=path.join(__dirname,'..','runtime'),seed='FINAL-MATCH-TEST-7';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
function fixture(key,profiles){const b=H.boundary(key,seed),env=A.seedMatch(b,{seed:`${seed}|SETPIECE`,runtimeDir,explicitHeroChoiceRequired:true,managerProfiles:profiles});return{b,env,m:env.state.m};}
function setupChecks(){for(const key of ['CORNER_ATTACK_RIGHT','CORNER_ATTACK_LEFT','CORNER_DEFEND_RIGHT']){const {m}=fixture(key),s=m.restart.setup,p=s.cornerPlan,lp=m.restart.team==='HOME'?{x:m.restart.x,y:m.restart.y}:{x:105-m.restart.x,y:68-m.restart.y};assert(s.cornerSemantic&&p,`${key}:CORNER_PLAN_MISSING`);const expected=lp.y<34?'LW':'RW';assert(s.cornerSemantic.nearSide===expected,`${key}:LOCAL_NEAR_MISMATCH`);for(const id of ['ST','LW','RW','LCM','CM','RCM']){const q=m.players.find(x=>x.team===m.restart.team&&x.slot===id);assert(q&&p.roles[q.id],`${key}:${id}:ROLE_MISSING`);}assert(Object.values(p.roles).includes('SECOND_BALL_EDGE'),`${key}:EDGE_MISSING`);assert(Object.values(p.roles).some(x=>String(x).startsWith('REST_DEFENCE')),`${key}:REST_MISSING`);console.log('SETUP',key,{near:p.nearSlot,far:p.farSlot,attack:p.attackTemplate,defence:p.defenceTemplate});}}
function windowChecks(){for(const key of ['CORNER_ATTACK_RIGHT','CORNER_ATTACK_LEFT','CORNER_DEFEND_RIGHT','CORNER_DEFEND_LEFT']){const b=H.boundary(key,seed),o=A.runSetPieceWindow(b,{seed:`${seed}|SETPIECE`,runtimeDir});const kick=o.actualEvents.find(e=>e.type==='CORNER_KICK')?.t;assert(kick,`${key}:NO_KICK`);assert(o.futureOutcomePrecomputed===false,`${key}:PRECOMPUTED`);assert(o.snapshot.time-kick>=1.5,`${key}:SHORT_POST_WINDOW`);const frames=o.frames.filter(f=>f.time>=kick-.001),relevant=f=>Object.fromEntries(f.players.filter(p=>p.team===b.setPiece.team&&['ST','LW','RW','LCM','CM','RCM'].includes(p.slot)).map(p=>[p.slot,p.tacticalTask])),tasks=frames.map(relevant);assert(tasks.some(t=>Object.values(t).some(v=>/CORNER_.*_(RUN|RESPONSE|EDGE)/.test(v))),`${key}:NO_LAUNCH_TASKS`);assert(!tasks.some(t=>Object.values(t).includes('CORNER_ATTACK_JOSTLE')),`${key}:SINE_JOSTLE_ACTIVE`);const post=frames.find(f=>f.time>=kick+1.0)||frames.at(-1);console.log('WINDOW',key,{kick:+kick.toFixed(2),post:+(o.snapshot.time-kick).toFixed(2),events:o.actualEvents.map(e=>e.type),pending:!!o.pending,launchTasks:relevant(frames[0]),postTasks:relevant(post)});}}
function tendencyChecks(){const seen=new Set();for(const profile of ['BALANCED','DEFENSIVE_COUNTER','ATTACKING_PRESS']){const {m}=fixture('CORNER_ATTACK_RIGHT',{HOME:profile,AWAY:'BALANCED'});seen.add(m.restart.setup.cornerPlan.attackTemplate);console.log('PROFILE',profile,m.restart.setup.cornerPlan.attackTemplate,m.restart.setup.cornerPlan.defenceTemplate);}assert(seen.size>=2,'TEMPLATE_DIFFERENTIATION_TOO_NARROW');}
function fkChecks(){for(const key of ['FREE_KICK_ATTACK_LEFT','FREE_KICK_ATTACK_RIGHT','FREE_KICK_DEFEND_LEFT','FREE_KICK_DEFEND_RIGHT']){const b=H.boundary(key,'13'),o=A.runSetPieceWindow(b,{seed:'13|SETPIECE',runtimeDir,durationSeconds:8});assert(o.actualEvents.some(e=>e.type==='FREE_KICK_TAKEN'),`${key}:FK_NOT_TAKEN`);assert(o.futureOutcomePrecomputed===false,`${key}:PRECOMPUTED`);console.log('FK',key,o.actualEvents.map(e=>e.type));}}
setupChecks();windowChecks();tendencyChecks();fkChecks();console.log('V37_CORNER_PHASE2_LUNA_QA_PASS');
