'use strict';
const path=require('path');
const G=require('./v37_whole_team_movement_sanity_gate.js');
const root=path.resolve(__dirname,'..'),runtimeDir=path.join(root,'runtime');
global.FLRPG_RESTART_MOVEMENT=require('../runtime/restart_movement.js');
require('../runtime/free_kick_templates.js');require('../runtime/free_kick_wall_model.js');require('../runtime/v37_set_piece_liveliness_patch.js');require('../runtime/corner_templates.js');
const E=require('../runtime/continuous_match_core.js');global.FLRPG_CONTINUOUS_CORE=E;
// Match the authoritative browser/index.html loader order: the V37 presentation
// patch must wrap the core before the scene authority/harness is loaded.
require('../runtime/v37_match_feel_patch.js');
const A=require('../live_v06_scene_authority_browser.js');global.FLRPG_LIVE_V06_SCENE_AUTHORITY=A;
const H=require('../final_match_rare_scenario_harness.js');
// Read-only harness serialization seam: preserve actual frame order and add
// linkage metadata; this never writes to the simulation object.
function serializeFrames(frames,b){return(frames||[]).map((f,i)=>({...f,frameId:`${b?.id||'scenario'}:${i}`,...(i===0?{boundaryId:b?.id||null,boundaryKind:b?.type||null,transitionCause:b?.reason||null}:{ }),...(i>0?{precedingLiveFrameId:`${b?.id||'scenario'}:${i-1}`,previousPhase:frames[i-1]?.phase||null}:{})}));}
const p=(id,team,slot,x,y,extra={})=>({id,team,slot,role:slot,x,y,tx:x,ty:y,vx:0,vy:0,tacticalTask:'HOLD',...extra});
const mk=(phase='OPEN_PLAY',extra={})=>{const home=[p('H-LW','HOME','WF',82,10),p('H-RW','HOME','WF',82,58),p('H-ST','HOME','ST',84,34),p('H-LCM','HOME','CM',60,24),p('H-CM','HOME','CM',58,34),p('H-RCM','HOME','CM',60,44),p('H-LB','HOME','FB',42,10),p('H-LCB','HOME','CB',38,25),p('H-RCB','HOME','CB',38,43),p('H-RB','HOME','FB',42,58),p('H-GK','HOME','GK',8,34)];const away=[p('A-LW','AWAY','WF',23,10),p('A-RW','AWAY','WF',23,58),p('A-ST','AWAY','ST',21,34),p('A-LCM','AWAY','CM',45,24),p('A-CM','AWAY','CM',47,34),p('A-RCM','AWAY','CM',45,44),p('A-LB','AWAY','FB',63,10),p('A-LCB','AWAY','CB',67,25),p('A-RCB','AWAY','CB',67,43),p('A-RB','AWAY','FB',63,58),p('A-GK','AWAY','GK',97,34)];return Array.from({length:5},(_,i)=>({time:i*.2,phase,ball:{mode:'CONTROLLED',x:70,y:34},possession:'HOME',players:[...home,...away].map(x=>({...x})),...extra}));};
function controls(){
  const out=[];
  let fs=mk();fs.forEach(f=>{f.ball.y=10;f.players.filter(p=>p.team==='HOME'&&['CB','FB'].includes(p.role)).forEach(p=>{p.y=10;p.x=Math.max(p.x,55);});f.players.find(p=>p.id==='A-RW').x=27;f.players.find(p=>p.id==='A-RW').y=55;});out.push({name:'A5_TRUE_WEAK_SIDE_ABANDONMENT',expected:'FAIL',result:G.analyze(fs)});
  fs=mk();fs.forEach(f=>{f.ball.y=10;f.players.filter(p=>p.team==='HOME'&&['CB','FB'].includes(p.role)).forEach(p=>{p.y=10;p.x=Math.max(p.x,55);});const a=f.players.find(p=>p.id==='A-RW');a.x=27;a.y=55;const cover=f.players.find(p=>p.id==='H-RB');cover.y=52;cover.x=70;cover.markTargetId='A-RW';const awayCover=f.players.find(p=>p.id==='A-RB');awayCover.y=52;awayCover.x=35;awayCover.markTargetId='H-RW';});out.push({name:'A5_COMPACT_FAR_SIDE_MARK',expected:'PASS',result:G.analyze(fs)});
  fs=mk('SET_PIECE_LIVE',{setPieceStage:'LIVE'});fs.forEach(f=>{f.ball.x=78;f.ball.y=34;f.players.filter(p=>p.team==='HOME'&&['WF','ST'].includes(p.role)).forEach(p=>{p.x=76;p.y=34;});f.players.filter(p=>p.team==='HOME'&&p.role==='CM').forEach(p=>p.responsibility='HOLD_LINE');});out.push({name:'STATIC_SET_PIECE_IDLE_ATTACK',expected:'WATCH',result:G.analyze(fs)});
  fs=mk('SET_PIECE_LIVE',{setPieceStage:'LIVE'});fs.forEach(f=>{f.ball.x=78;f.players.find(p=>p.id==='H-LW').responsibility='RUN_NEAR_POST';f.players.find(p=>p.id==='H-RW').responsibility='SECOND_BALL_EDGE';f.players.find(p=>p.id==='H-ST').responsibility='FAR_POST_DEPTH';f.players.find(p=>p.id==='H-CM').responsibility='REST_DEFENCE';});out.push({name:'VALID_SET_PIECE_RUN_EDGE_REST',expected:'PASS',result:G.analyze(fs)});
  fs=mk('SET_PIECE_LIVE',{setPieceStage:'LIVE'});fs.forEach(f=>{f.ball.x=70;f.ball.y=10;f.players.filter(p=>p.team==='AWAY'&&['CB','FB'].includes(p.role)).forEach((p,i)=>{p.x=i<2?70:50;p.y=10;p.tacticalTask='CORNER_ZONE_HOLD';});f.players.filter(p=>p.team==='AWAY'&&p.role==='CM').forEach((p,i)=>{p.x=50;p.y=24+i*10;p.tacticalTask='CORNER_CLEARANCE_EDGE_HOLD';});const cover=f.players.find(p=>p.id==='A-RB');cover.x=70;cover.y=58;cover.tacticalTask='CORNER_ZONE_HOLD';});out.push({name:'A5_SET_PIECE_VALID_CHANNEL_ZONE',expected:'PASS',result:G.analyze(fs)});
  fs=mk('SET_PIECE_LIVE',{setPieceStage:'LIVE'});fs.forEach(f=>{f.ball.x=70;f.ball.y=10;f.players.filter(p=>p.team==='AWAY'&&['CB','FB','CM'].includes(p.role)).forEach(p=>{p.x=Math.max(p.x,55);p.y=10;p.tacticalTask='HOLD';});});out.push({name:'A5_SET_PIECE_INVALID_NO_CHANNEL_OWNER',expected:'FAIL',result:G.analyze(fs)});
  out.push({name:'HIGH_FB_COMPENSATED',expected:'PASS',result:G.analyze(G.sequence('valid_high_lb'))},{name:'HIGH_FB_FROZEN',expected:'FAIL',result:G.analyze(G.sequence('invalid_high_lb'))});
  fs=mk();fs.forEach(f=>{f.possession='HOME';f.ball.x=50;const st=f.players.find(p=>p.id==='H-ST');st.x=50;f.players.filter(p=>p.team==='HOME'&&p.role==='WF').forEach(p=>p.x=55);});out.push({name:'C2_GENERIC_DEEP_SWARM',expected:'FAIL',result:G.analyze(fs)});
  fs=mk();fs.forEach(f=>{f.possession='HOME';f.ball.x=50;const st=f.players.find(p=>p.id==='H-ST');st.x=50;const w=f.players.find(p=>p.id==='H-LW');w.x=75;w.responsibility='FORWARD_RUN';});out.push({name:'C2_VALID_ST_DROP_ROTATION',expected:'PASS',result:G.analyze(fs)});
  fs=mk();fs.forEach(f=>f.players.filter(p=>p.team==='HOME'&&p.role==='CM').forEach(p=>{p.targetId=null;p.markTargetId=null;p.intentCategory='PRESS';}));out.push({name:'E2_NULL_TARGETS_NOT_SHARED',expected:'PASS',result:G.analyze(fs)});
  return out;
}
function sample(key,seed){const r=H.run(key,seed,{runtimeDir}),frames=serializeFrames(r.frames||[],r.boundary),a=G.analyze(frames);return{scenario:key,seed,verdict:a.verdict,hardFailRules:a.findings.filter(f=>f.severity==='HARD_FAIL').map(f=>f.ruleId),watchRules:a.findings.filter(f=>f.severity==='WATCH').map(f=>f.ruleId),events:(r.actualEvents||[]).map(e=>e.type),futureOutcomePrecomputed:r.futureOutcomePrecomputed};}
function main(){const paired=controls().map(x=>({name:x.name,expected:x.expected,got:x.result.verdict,ruleIds:x.result.findings.map(f=>f.ruleId),ok:x.expected==='FAIL'?x.result.verdict==='FAIL':x.expected==='WATCH'?x.result.verdict==='WATCH':x.result.verdict==='PASS'}));const scenarios=[['CROSS_LEFT','13'],['CROSS_RIGHT','13'],['ST_BREAKAWAY','13'],['CORNER_ATTACK_RIGHT','7'],['FREE_KICK_ATTACK_LEFT','13'],['FREE_KICK_ATTACK_RIGHT','13'],['FREE_KICK_DEFEND_LEFT','13'],['FREE_KICK_DEFEND_RIGHT','13'],['FREE_KICK_ATTACK_LEFT','7'],['GK_SHOT_CLOSE','13']].map(([k,s])=>sample(k,s));const read=G.runSelfTest();const result={module:'V37_MOVEMENT_GATE_LUNA_CALIBRATION',pairedControls:paired,syntheticSelfTest:read,acceptedScenarios:scenarios,mandatorySafe:paired.every(x=>x.ok)&&read.verdict==='PASS'&&scenarios.every(x=>!x.hardFailRules.length)};console.log(JSON.stringify(result,null,2));if(!result.mandatorySafe)process.exitCode=1;}
if(require.main===module)main();
module.exports={controls,sample,main};
