'use strict';
const path=require('path');
const root=path.resolve(__dirname,'..'),runtime=path.join(root,'runtime');
function req(p){return require(path.join(root,p));}
const R=req('runtime/restart_movement.js');global.FLRPG_RESTART_MOVEMENT=R;req('runtime/free_kick_wall_model.js');req('runtime/v37_set_piece_liveliness_patch.js');
const E=req('runtime/continuous_match_core.js');global.FLRPG_CONTINUOUS_CORE=E;req('runtime/v37_match_feel_patch.js');
const P=req('runtime/protagonist_match_controller.js');global.FLRPG_PROTAGONIST_MATCH_CONTROLLER=P;
const A=req('live_v06_scene_authority_browser.js');global.FLRPG_LIVE_V06_SCENE_AUTHORITY=A;
const H=req('final_match_rare_scenario_harness.js');global.FLRPG_FINAL_MATCH_RARE_SCENARIOS=H;req('final_match_forced_presentation_patch.js');req('final_match_v37_forced_harness_patch.js');
const checks=[],metrics={};
function check(name,ok,detail=''){checks.push({name,ok:!!ok,detail});if(!ok)process.exitCode=1;}
function events(r,type){return(r.actualEvents||[]).filter(e=>e.type===type);}
function speed(p){return Math.hypot(Number(p?.vx)||0,Number(p?.vy)||0);}
function localX(p){return p?.team==='AWAY'?105-Number(p.x):Number(p.x);}
function localTx(p){return p?.team==='AWAY'?105-Number(p.tx):Number(p.tx);}
function touchIntervals(frames){const out=[];let last=null;for(const f of frames||[]){const id=f?.ball?.lastTouchPlayer||null,t=Number(f?.time);if(!id||!Number.isFinite(t))continue;if(last&&id!==last.id)out.push({from:last.id,to:id,dt:t-last.t,time:t});if(!last||id!==last.id)last={id,t};}return out;}
function frameBallSpeed(a,b){const dt=Number(b?.time)-Number(a?.time);if(!(dt>0))return null;return Math.hypot(Number(b.ball?.x)-Number(a.ball?.x),Number(b.ball?.y)-Number(a.ball?.y))/dt;}
function crossMetrics(key,seed){const r=H.run(key,seed,{runtimeDir:runtime}),frames=r.frames||[],touches=touchIntervals(frames);let maxBall=0,maxReverseChase=0,minTouch=99,maxStDeepSpeed=0;for(let i=1;i<frames.length;i++){const v=frameBallSpeed(frames[i-1],frames[i]);if(Number.isFinite(v))maxBall=Math.max(maxBall,v);for(const p of frames[i].players||[]){const dx=Number(p.tx)-Number(p.x),dy=Number(p.ty)-Number(p.y),d=Math.hypot(dx,dy),s=speed(p);if(d>.01&&['CHASE_LOOSE','GK_RUSH'].includes(String(p.tacticalTask||p.action||''))){const dot=((Number(p.vx)||0)*dx+(Number(p.vy)||0)*dy)/d;if(dot<0)maxReverseChase=Math.max(maxReverseChase,s);}if(p.role==='ST'&&p.team==='HOME'&&localTx(p)<58)maxStDeepSpeed=Math.max(maxStDeepSpeed,s);}}
 for(const x of touches)minTouch=Math.min(minTouch,x.dt);return{result:r,maxBallSpeed:Number(maxBall.toFixed(2)),minTouchInterval:minTouch===99?null:Number(minTouch.toFixed(3)),touches,maxReverseChaseSpeed:Number(maxReverseChase.toFixed(2)),maxStSpeedWithDeepTarget:Number(maxStDeepSpeed.toFixed(2)),presentation:r.presentationContact||null};}
// Corners: all four forced variants must reach an actual kick inside the bounded window.
for(const key of ['CORNER_ATTACK_LEFT','CORNER_ATTACK_RIGHT','CORNER_DEFEND_LEFT','CORNER_DEFEND_RIGHT']){const r=H.run(key,'V37-CORNER-QA',{runtimeDir:runtime});check(`${key}:CORNER_KICK`,events(r,'CORNER_KICK').length>0,`events=${(r.actualEvents||[]).map(e=>e.type).join(',')}`);const lively=(r.frames||[]).some(f=>(f.players||[]).some(p=>['CORNER_ATTACK_JOSTLE','CORNER_MARK_JOSTLE'].includes(p.action||p.tacticalTask)));check(`${key}:LIVELY_SETUP`,lively);check(`${key}:NO_PRECOMPUTE`,r.futureOutcomePrecomputed===false);}
// Free kicks: setup should show run-ready/tracking motion while the wall remains a distinct task.
for(const key of ['FREE_KICK_ATTACK_LEFT','FREE_KICK_ATTACK_RIGHT','FREE_KICK_DEFEND_LEFT','FREE_KICK_DEFEND_RIGHT']){const r=H.run(key,'V37-FK-QA',{runtimeDir:runtime});const lively=(r.frames||[]).some(f=>(f.players||[]).some(p=>['FREE_KICK_RUN_READY','FREE_KICK_TRACK_RUNNER','FREE_KICK_SECOND_BALL_READY'].includes(p.action||p.tacticalTask)));const wall=(r.frames||[]).some(f=>(f.players||[]).some(p=>String(p.action||p.tacticalTask||'').includes('FREE_KICK_WALL')));check(`${key}:LIVELY_SETUP`,lively);check(`${key}:WALL_PRESENT`,wall);check(`${key}:NO_PRECOMPUTE`,r.futureOutcomePrecomputed===false);}
// User seeds from the report batch.
metrics.cross57=crossMetrics('CROSS_LEFT','FINAL-MATCH-TEST-57');metrics.cross64=crossMetrics('CROSS_LEFT','FINAL-MATCH-TEST-64');metrics.cross73=crossMetrics('CROSS_LEFT','FINAL-MATCH-TEST-73');metrics.crossRight=crossMetrics('CROSS_RIGHT','FINAL-MATCH-TEST-57');
for(const [name,m] of Object.entries(metrics)){if(!name.startsWith('cross'))continue;check(`${name}:ENGINE_TRAJECTORY_ONLY`,m.presentation?.applied===false&&m.presentation?.policy==='ENGINE_TRAJECTORY_ONLY_V37');check(`${name}:LOOSE_CHASER_REVERSE_SPEED`,m.maxReverseChaseSpeed<=3.6,`max=${m.maxReverseChaseSpeed}`);}
check('cross73:ST_DEEP_RECOVERY_SPEED',metrics.cross73.maxStSpeedWithDeepTarget<=4.8,`max=${metrics.cross73.maxStSpeedWithDeepTarget}`);
// ST breakaway must retain the live pending choice and continue only after an explicit choice.
const br=H.run('ST_BREAKAWAY','V37-BREAKAWAY-QA',{runtimeDir:runtime});check('ST_BREAKAWAY:PENDING',!!br.pending&&(br.pending.options||[]).length>0);check('ST_BREAKAWAY:NO_PRECOMPUTE',br.futureOutcomePrecomputed===false);const opt=br.pending?.options?.[0];if(opt){const before=(br.frames||[]).length,out=H.applyForcedChoice(opt.id,opt.targetId||null);check('ST_BREAKAWAY:CHOICE_APPLIED',out?.ok===true);check('ST_BREAKAWAY:POST_FRAMES',(out?.result?.frames||[]).length>before);check('ST_BREAKAWAY:APPLY_NO_PRECOMPUTE',out?.futureOutcomePrecomputed===false&&out?.result?.futureOutcomePrecomputed===false);}
// GK forced scenes: no instant >=8m/s impulse; when V37 reach appears it must retain the strike target intent.
for(const key of ['GK_SHOT_LONG','GK_SHOT_BOX','GK_SHOT_CLOSE']){const r=H.run(key,`V37-${key}`,{runtimeDir:runtime}),frames=r.frames||[];let max=0,locked=0,badIntent=0;for(const f of frames){const g=(f.players||[]).find(p=>p.id==='H-GK');max=Math.max(max,speed(g));const reach=f.ball?.gkParryReach;if(reach?.v37LockedIntent){locked++;if(Number(reach.v37ShotTargetY)!==Number(f.ball?.shotTargetY))badIntent++;}}metrics[key]={maxGkSpeed:Number(max.toFixed(2)),lockedReachFrames:locked,badIntent};check(`${key}:NO_8_IMPULSE`,max<7.95,`max=${max.toFixed(2)}`);check(`${key}:LOCKED_INTENT_MATCH`,badIntent===0,`locked=${locked}, bad=${badIntent}`);check(`${key}:NO_PRECOMPUTE`,r.futureOutcomePrecomputed===false);}
const failed=checks.filter(c=>!c.ok),summary={verdict:failed.length?'FAIL':'PASS',checks,metrics};console.log(JSON.stringify(summary,null,2));if(failed.length)process.exit(1);
