'use strict';
const TRUTH=require('./v39_validation_truth_guards.js');
const REL=require('./v39_relational_detectors.js');
const G=TRUTH.guards;

const p=(id,team,role,slot,x,y,task,extra={})=>({id,team,role,slot,x,y,tx:x,ty:y,tacticalTask:task,vx:0,vy:0,...extra});
const sp=(team='HOME',kind='CORNER')=>({boundary:{type:'SET_PIECE_2D_WINDOW',setPiece:{kind,team,lane:'RIGHT'}},actualEvents:[{type:`${kind}_KICK`,t:0}],frames:[]});
const frame=(time,players,ball={x:52.5,y:34,mode:'FLIGHT',kind:'CROSS',ownerTeam:'HOME'},possession='HOME')=>({time,players,ball,possession});
const times=(count=6,step=.1)=>Array.from({length:count},(_,i)=>+(i*step).toFixed(2));
const has=(rows,id)=>Array.isArray(rows)&&rows.some(x=>x.id===id);
const row=(id,bad,good,note)=>({id,badDetected:bad,goodDetected:good,ok:bad===true&&good===false,note});

function midfieldPair(marked=false){const r=sp('AWAY','FREE_KICK'),ys=[[28,40],[31,37],[33,35],[35,33],[37,31],[40,28]];r.frames=ys.map(([ly,ry],i)=>frame(i*.1,[p('H-LCM','HOME','CM','LCM',55,ly,'FREE_KICK_SECOND_BALL_LEFT_HOLD',marked?{markTargetId:'A-RW'}:{}),p('H-RCM','HOME','CM','RCM',55,ry,'FREE_KICK_SECOND_BALL_RIGHT_HOLD'),p('A-RW','AWAY','WF','RW',70,56,'WIDE_OUTLET')],{x:62,y:34,mode:'FLIGHT',kind:'FREE_KICK',ownerTeam:'AWAY'},'AWAY'));return r;}
function wideOutlet(covered=false){const r=sp('HOME','CORNER');r.frames=times(5).map(t=>frame(t,[p('H-RW','HOME','WF','RW',60,58,'COUNTER_OUTLET'),p('A-RB','AWAY','FB','RB',covered?63:82,covered?55:45,'CORNER_REST_DEFENCE_1',covered?{markTargetId:'H-RW'}:{}),p('A-RCB','AWAY','CB','RCB',78,32,'CORNER_REST_DEFENCE_2')],{x:90,y:60,mode:'LOOSE',kind:'CORNER',ownerTeam:'HOME'},'HOME'));return r;}
function duplicateWide(withCentralCover=false){const r=sp('HOME','FREE_KICK');r.frames=times(4).map(t=>frame(t,[p('H-ST','HOME','ST','ST',88,34,'BOX_ATTACK'),p('H-RW','HOME','WF','RW',84,56,'WIDE_RECEIVER'),p('A-LB','AWAY','FB','LB',80,52,'MARK',{markTargetId:'H-RW'}),p('A-LCB','AWAY','CB','LCB',81,48,'MARK',{markTargetId:'H-RW'}),p('A-RCB','AWAY','CB','RCB',withCentralCover?85:75,withCentralCover?34:26,'CENTRAL_COVER',withCentralCover?{markTargetId:'H-ST'}:{})],{x:80,y:50,mode:'FLIGHT',kind:'FREE_KICK',ownerTeam:'HOME'},'HOME'));return r;}
function centralST(owned=false){const r=sp('HOME','FREE_KICK');r.frames=times(4).map(t=>frame(t,[p('H-ST','HOME','ST','ST',90,34,'BOX_ATTACK'),p('A-RCB','AWAY','CB','RCB',84,30,'LINE_COVER',owned?{markTargetId:'H-ST'}:{}),p('A-LCB','AWAY','CB','LCB',81,45,'LINE_COVER')],{x:86,y:40,mode:'LOOSE',kind:'FREE_KICK',ownerTeam:'HOME'},'HOME'));return r;}
function deepForward(explained=false){return {frames:times(7).map(t=>frame(t,[p('H-ST','HOME','ST','ST',42,34,'SHOT_LANE_COVER',explained?{markTargetId:'A-CM'}:{}),p('H-LW','HOME','WF','LW',57,10,'HOLD_BLOCK'),p('H-RW','HOME','WF','RW',59,58,'HOLD_BLOCK'),p('A-CM','AWAY','CM','CM',66,34,'CARRY')],{x:68,y:34,mode:'CONTROLLED',kind:'DRIBBLE',ownerTeam:'AWAY'},'AWAY'))};}
function gkDive(rendered=false){const diveTask=rendered?'GK_DIVE_PUSH_OFF_TRAVEL':'DIVE_PUSH_OFF_TRAVEL';return {actualEvents:[{type:'GOAL',t:.4}],frames:[frame(0,[p('H-GK','HOME','GK','GK',4,34,'GK_REACT_WAIT')],{x:12,y:35,mode:'FLIGHT',kind:'SHOT',ownerTeam:'AWAY'},'AWAY'),frame(.2,[p('H-GK','HOME','GK','GK',4,34.5,diveTask)],{x:5,y:36,mode:'FLIGHT',kind:'SHOT',ownerTeam:'AWAY'},'AWAY'),frame(.4,[p('H-GK','HOME','GK','GK',4,35,diveTask)],{x:0,y:36,mode:'FLIGHT',kind:'SHOT',ownerTeam:'AWAY'},'AWAY')]};}
function crossEntry(covered=false){const lb=p('A-LB','AWAY','FB','LB',88,48,covered?'CROSS_CHANNEL_OWNER':'HYBRID_ENTRY_LIVE',covered?{markTargetId:'H-RW',tx:81,ty:56}:{});return {frames:[frame(10,[p('H-RW','HOME','WF','RW',79,56,'HYBRID_ENTRY_LIVE'),lb,p('A-LCM','AWAY','CM','LCM',65,46,'HYBRID_ENTRY_LIVE')],{x:80,y:56,mode:'FLIGHT',kind:'CROSS',ownerTeam:'HOME'},'HOME')]};}
function forwardShadow(shadowed=false){const r={replayStartFrameIndex:0,frames:times(7,.1).map(t=>{const f=frame(t,[p('H-ST','HOME','ST','ST',90+t*1.2,34,'CARRY_FORWARD',{}),p('H-RCM','HOME','CM','RCM',shadowed?88+t*1.2:84+t*.3,shadowed?34:42,shadowed?'LATE_BOX_ARRIVAL':'SUPPORT',shadowed?{}:{tx:90,ty:42}),p('H-LW','HOME','WF','LW',70,8,'WIDE_OUTLET',{tx:80,ty:8}),p('A-LB','AWAY','FB','LB',86,50,'MARK',{markTargetId:'H-LW'})],{x:90+t,y:34,mode:'CONTROLLED',kind:'CONTROL',ownerTeam:'HOME'},'HOME');f.ball.ownerId='H-ST';return f;})};return r;}
function cornerPassive(control=false){const r=sp('HOME','CORNER');r.frames=times(7,.1).map(t=>frame(t,[p('H-ST','HOME','ST','ST',94,34,'CENTRAL_RUNNER',control?{tx:98,ty:34}:{}),p('H-RW','HOME','WF','RW',96,26,'NEAR_RUNNER',control?{tx:99,ty:28}:{}),p('A-LB','AWAY','FB','LB',96,50,'REST_DEFENCE',control?{markTargetId:'H-RW'}:{}),p('A-ST','AWAY','ST','ST',37,34,'COUNTER_OUTLET',control?{tx:30,ty:34}:{})],{x:96,y:34,mode:'CONTROLLED',kind:'CONTROL',ownerTeam:'HOME'},'HOME'));return r;}

function run(){
  const checks=[];
  checks.push(row('SET_PIECE_MIDFIELD_CHANNEL_CROSS',has(G.midfieldChannelCross(midfieldPair(false)),'SET_PIECE_MIDFIELD_CHANNEL_CROSS'),has(G.midfieldChannelCross(midfieldPair(true)),'SET_PIECE_MIDFIELD_CHANNEL_CROSS'),'Fixed lane holders crossing without ownership must fail; explicit marking rotation is control.'));
  checks.push(row('SET_PIECE_LIVE_WIDE_THREAT_UNOWNED',has(G.uncoveredLiveWideThreat(wideOutlet(false)),'SET_PIECE_LIVE_WIDE_THREAT_UNOWNED'),has(G.uncoveredLiveWideThreat(wideOutlet(true)),'SET_PIECE_LIVE_WIDE_THREAT_UNOWNED'),'A live counter outlet needs an owner or compensating cover.'));
  checks.push(row('SET_PIECE_POST_KICK_OWNERSHIP_COLLAPSE',has(G.duplicateWideOwnershipFreesST(duplicateWide(false)),'SET_PIECE_POST_KICK_OWNERSHIP_COLLAPSE'),has(G.duplicateWideOwnershipFreesST(duplicateWide(true)),'SET_PIECE_POST_KICK_OWNERSHIP_COLLAPSE'),'Duplicate wide ownership only fails when central ST responsibility is simultaneously released.'));
  checks.push(row('SET_PIECE_CENTRAL_FORWARD_UNOWNED',has(G.centralForwardUnowned(centralST(false)),'SET_PIECE_CENTRAL_FORWARD_UNOWNED'),has(G.centralForwardUnowned(centralST(true)),'SET_PIECE_CENTRAL_FORWARD_UNOWNED'),'Central striker exposure fails only when both ownership and compensating proximity are absent.'));
  checks.push(row('FORWARD_LAYER_UNEXPLAINED_ABANDONMENT',has(G.forwardLayerAbandonment(deepForward(false)),'FORWARD_LAYER_UNEXPLAINED_ABANDONMENT'),has(G.forwardLayerAbandonment(deepForward(true)),'FORWARD_LAYER_UNEXPLAINED_ABANDONMENT'),'Deep ST defending requires a local/explicit responsibility.'));
  checks.push(row('GK_RENDERER_ENGINE_DIVE_SEMANTIC_MISMATCH',has(G.goalkeeperPresentationTruth(gkDive(false)),'GK_RENDERER_ENGINE_DIVE_SEMANTIC_MISMATCH'),has(G.goalkeeperPresentationTruth(gkDive(true)),'GK_RENDERER_ENGINE_DIVE_SEMANTIC_MISMATCH'),'Live GK push-off travel is valid only when it matches the renderer-visible GK_DIVE_PUSH_OFF_TRAVEL convention.'));
  const badCross=REL.DETECTORS.OPEN_PLAY_WIDE_OWNER(crossEntry(false)),goodCross=REL.DETECTORS.OPEN_PLAY_WIDE_OWNER(crossEntry(true));checks.push(row('OPEN_PLAY_FIRST_VISIBLE_FRAME_OWNER',badCross.detected===true,goodCross.detected===true,'The first frame shown by Test Dock is authoritative; HYBRID_ENTRY_LIVE cannot be ignored merely because it is fixture entry.'));
  checks.push(row('BREAKAWAY_SAME_TEAM_FORWARD_SUPPORT_SHADOW',has(G.sameTeamForwardSupportShadow(forwardShadow(true)),'BREAKAWAY_SAME_TEAM_FORWARD_SUPPORT_SHADOW'),has(G.sameTeamForwardSupportShadow(forwardShadow(false)),'BREAKAWAY_SAME_TEAM_FORWARD_SUPPORT_SHADOW'),'Trailing same-team occupation fails only without a distinct support/receiver target.'));
  checks.push(row('CORNER_LIVE_MULTI_PLAYER_UNOWNED_PASSIVITY',has(G.cornerLiveUnownedPassivity(cornerPassive(false)),'CORNER_LIVE_MULTI_PLAYER_UNOWNED_PASSIVITY'),has(G.cornerLiveUnownedPassivity(cornerPassive(true)),'CORNER_LIVE_MULTI_PLAYER_UNOWNED_PASSIVITY'),'Live multi-player passivity fails without causal responsibility; explicit outlet/mark/next-space controls remain valid.'));
  return {module:'V39_VALIDATION_TRUTH_SELFTEST',verdict:checks.every(x=>x.ok)?'PASS':'FAIL',checks,policy:{actualDetectorExecutionRequired:true,syntheticBadAndNearbyControlRequired:true,noLiteralPairedControlBooleansForNewTruthGuards:true,firstVisibleFrameIsAuthoritative:true}};
}
if(require.main===module){const out=run();console.log(JSON.stringify(out,null,2));if(out.verdict!=='PASS')process.exitCode=7;}
module.exports={run};
