'use strict';
const path=require('path');
require('./v39_runtime_candidate_loader.js');
const H=require('../final_match_rare_scenario_harness.js');
global.FLRPG_FINAL_MATCH_RARE_SCENARIOS=H;
require('../final_match_v37_forced_harness_patch.js');
const G=require('./v39_validation_truth_guards.js').guards;
const runtimeDir=path.resolve(__dirname,'../runtime');
const round=v=>Number(Number(v||0).toFixed(3));
const snap=p=>p&&{id:p.id,x:round(p.x),y:round(p.y),tx:round(p.tx),ty:round(p.ty),vx:round(p.vx),vy:round(p.vy),task:p.tacticalTask||p.action||null,targetId:p.targetId||null,markTargetId:p.markTargetId||null,slot:p.slot||null,role:p.role||null};
function st98(){let r=H.run('ST_BREAKAWAY','FINAL-MATCH-TEST-98',{runtimeDir}),choices=[];for(let i=0;i<2;i++){const o=(r.pending?.options||[]).find(x=>x.id==='CARRY');if(!o)throw new Error(`CARRY_UNAVAILABLE_${i+1}`);const before=r.frames.length;r=H.applyForcedChoice(o.id,o.targetId||null).result;choices.push({choiceId:o.id,targetId:o.targetId||null,beforeFrames:before,afterFrames:r.frames.length,replayStartFrameIndex:r.replayStartFrameIndex});}const fs=r.frames.slice(r.replayStartFrameIndex),trace=fs.map(f=>({time:round(f.time),ball:{mode:f.ball?.mode||null,ownerId:f.ball?.ownerId||null,x:round(f.ball?.x),y:round(f.ball?.y)},players:['H-ST','H-RCM','H-LW','A-LB'].map(id=>snap((f.players||[]).find(p=>p.id===id)))}));let min=Infinity;for(const f of fs){const a=(f.players||[]).find(p=>p.id==='H-ST'),b=(f.players||[]).find(p=>p.id==='H-RCM');if(a&&b)min=Math.min(min,Math.hypot(a.x-b.x,a.y-b.y));}return{choices,continuationCursor:r.replayStartFrameIndex,traceSampleIntervalSeconds:.05,trace,minimumST_RCMSeparation:round(min),detector:G.sameTeamForwardSupportShadow(r),classification:G.sameTeamForwardSupportShadow(r).length?'REAL_RUNTIME_FAILURE_REMAINS':'CURRENT_RUNTIME_ALREADY_REPAIRED_BUT_REGRESSION_BLIND'};}
function corner13(){const r=H.run('CORNER_ATTACK_RIGHT','FINAL-MATCH-TEST-13',{runtimeDir}),kick=(r.actualEvents||[]).find(e=>e.type==='CORNER_KICK')?.t,fs=(r.frames||[]).filter(f=>f.time>=kick-.001&&f.ball?.mode!=='DEAD'),contact=fs.find(f=>f.ball?.mode==='LOOSE'||(f.ball?.mode==='CONTROLLED'&&f.ball?.ownerId)),ids=['H-LB','H-LCB','H-RCB','H-RB','H-LCM','H-CM','H-RCM','H-LW','H-ST','H-RW','A-LB','A-LCB','A-RCB','A-RB','A-LCM','A-CM','A-RCM','A-LW','A-ST','A-RW'];return{kickTime:round(kick),firstLive:fs[0]&&{time:round(fs[0].time),mode:fs[0].ball?.mode,kind:fs[0].ball?.kind},firstContact:contact&&{time:round(contact.time),mode:contact.ball?.mode,kind:contact.ball?.kind,ownerId:contact.ball?.ownerId||null,ballX:round(contact.ball?.x),ballY:round(contact.ball?.y),players:ids.map(id=>snap((contact.players||[]).find(p=>p.id===id)))},detector:G.cornerLiveUnownedPassivity(r),classification:G.cornerLiveUnownedPassivity(r).length?'REAL_RUNTIME_FAILURE_REMAINS':'CURRENT_RUNTIME_ALREADY_REPAIRED_BUT_REGRESSION_BLIND'};}
console.log(JSON.stringify({module:'V40_FINAL_TWO_TRUTH_BLOCKERS_RETRY',st98:st98(),corner13:corner13()},null,2));
