'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
function gitHead(){const h=fs.readFileSync(path.join(ROOT,'.git','HEAD'),'utf8').trim();return h.startsWith('ref: ')?fs.readFileSync(path.join(ROOT,'.git',h.slice(5)),'utf8').trim():h;}
const HEAD=gitHead();
const parity=require('./v40_runtime_parity_contract.js'),L0=require('./v40_l0_invariant_framework.js'),mut=require('./v40_mutation_challenge_harness.js'),proof=require('./v40_same_head_proof_contract.js'),P0=require('./v40_p0_set_piece_wrong_end_detector.js'),replays=require('./v40_captured_boundary_replay.js'),contract=require('./v40_persistent_regression_contract.js'),freeKick=require('./v40_free_kick_causal_geometry_gate.js');
const manifest=require('./v40_known_bug_challenge_manifest.json');
function timed(name,fn){const t=process.hrtime.bigint();let value,error;try{value=fn();}catch(e){error=String(e&&e.stack||e);}return{name,wallClockMs:Number(process.hrtime.bigint()-t)/1e6,value,error};}
function requireQuiet(file){const log=console.log;console.log=()=>{};try{return require(file);}finally{console.log=log;}}
function run({tier='FAST',filter=null}={}){
 const timings=[];const measure=(name,fn)=>{const x=timed(name,fn);timings.push({name,wallClockMs:+x.wallClockMs.toFixed(3),error:x.error||null});if(x.error)throw new Error(x.error);return x.value;};const persistent=measure('persistentRegressionContract',()=>contract.run({runActiveChecks:tier!=='FAST'}));const sameHead=measure('crossRepoProofContract',()=>proof.selftest());
 const infra=measure('runtimeParity',()=>parity.run()),l0=measure('l0',()=>L0.run()),m=tier==='FAST'?measure('mutationsSelftest',()=>mut.selftest()):measure('mutations',()=>mut.run({currentHead:HEAD}));
 const activeManifest=manifest.incidents.filter(x=>x.status==='ACTIVE_REPLAY'),manifestInfra=activeManifest.every(replays.validateDefinition);
 const sections={persistentRegression:persistent,infraParity:infra,l0,sameHead,mutations:m,incidents:{schemaVersion:manifest.schemaVersion,total:manifest.incidents.length,activeReplay:activeManifest.length,extractNeeded:manifest.incidents.filter(x=>x.status==='EXTRACT_NEEDED').length,rows:manifest.incidents,manifestInfra},incidentReplays:null};
 if(tier!=='FAST')sections.incidentReplays=measure('incidentReplays',()=>replays.run({filter}));
 if(tier!=='FAST')sections.freeKickCausalGeometry=measure('freeKickCausalGeometry',()=>freeKick.run());
 if(tier!=='FAST'){sections.p0=measure('p0Current',()=>P0.selftest());sections.v39TruthSelftest=measure('v39TruthSelftest',()=>require('./v39_validation_truth_selftest.js').run());sections.currentTruthGate=measure('currentTruthGate',()=>require('./v39_recent_user_truth_gate.js').run());}
 if(tier==='INTEGRATION'||tier==='PREDEPLOY'){sections.coordinateFrame=measure('coordinateFrame',()=>requireQuiet('./v39_coordinate_frame_contract.js').run());const smokeQueue=requireQuiet('./v39_predeploy_visual_queue.js');sections.truthSmoke=measure('boundedWiderSmoke',()=>smokeQueue.smokeInventory());sections.legacyPredeployNote='The legacy queue remains separately authoritative; existing unrelated corner blockers are not suppressed by this gate.';}
 const p0Ok=sections.p0?sections.p0.selftest==='PASS':infra.verdict==='PASS'&&l0.verdict==='PASS';
 const infraOk=infra.verdict==='PASS',l0Ok=l0.verdict==='PASS',persistentOk=persistent.verdict==='PASS',headOk=sameHead.selftest==='PASS',mutOk=(m.verdict==='PASS'||(tier==='FAST'&&m.selftest==='PASS'));
 const smokeOk=!sections.truthSmoke||sections.truthSmoke.blockedCount===0;
 const truthOk=!sections.currentTruthGate||sections.currentTruthGate.verdict==='READY_FOR_USER_VISUAL_RETEST_CANDIDATE';
 const replayOk=manifestInfra&&(!sections.incidentReplays||sections.incidentReplays.counts.blocked===0);
 const freeKickOk=!sections.freeKickCausalGeometry||sections.freeKickCausalGeometry.verdict==='PASS';
 const overall=infraOk&&l0Ok&&persistentOk&&headOk&&mutOk&&p0Ok&&smokeOk&&truthOk&&replayOk&&freeKickOk?'GREEN':'RED';
 return{module:'V40_VALIDATION_CONFIDENCE_GATE',schemaVersion:'V40_CONFIDENCE_GATE_1.0',tier,filter,overallVerdict:overall,sourceHead:HEAD,sections,timings,coverage:{runtimeModuleCoverage:{entrypoint:infra.entrypoint.runtimeModules.length,loaded:infra.integrationLoader.loadedModules.length,missing:infra.missing.length},stateEventCoverage:{l0Invariants:l0.coverage.registered,events:['GOAL','CORNER_KICK','FREE_KICK_KICK','SAVE','PARRY','CHOICE']},homeAwayLeftRightSymmetry:{p0Cases:8,roleChecks:p0Ok?24:0,axes:['HOME','AWAY','LEFT','RIGHT']},incidentReplayCoverage:{active:sections.incidents.activeReplay,total:sections.incidents.total,executed:sections.incidentReplays?.counts?.active||0},mutationKillRatio:m.killRatio??1,mandatoryP0Count:7},policy:{legacyTruthCountsCannotOverrideRed:true,extractNeededCannotBeCalledClean:true,userPassNotGranted:true,noProductionMutation:true,activeReplayMissingRunnerFixtureOracleBlocks:true},recommendedCadence:{FAST:'every change',FOCUSED:'affected feature/incident',INTEGRATION:'before merge or runtime-stack changes',PREDEPLOY:'approved release candidate only'}};
}
function selftest(){const out=run({tier:'FAST'});assert.equal(out.overallVerdict,'GREEN');assert.equal(replays.validateDefinition({id:'X',runner:null,fixture:'f',oracle:'o'}),false);assert.equal(proof.validate({}, {mode:'single-repo',currentHead:HEAD}).verdict,'BLOCKED');assert.equal(proof.validate({mode:'cross-repo',sourceRepo:proof.SOURCE_REPO,sourceSHA:'STALE',targetRepo:proof.TARGET_REPO,targetBaseSHA:proof.TARGET_BASE_SHA},{}).verdict,'BLOCKED');return{module:out.module,selftest:'PASS',tier:out.tier,overallVerdict:out.overallVerdict,sourceHead:out.sourceHead,coverage:out.coverage};}
if(require.main===module){const tier=(process.argv.find(x=>/^--tier=/.test(x))||'--tier=FAST').split('=')[1],a=process.argv.find(x=>/^--filter=/.test(x));const out=process.argv.includes('--selftest')?selftest():run({tier,filter:a?.split('=').slice(1).join('=')||null});console.log(JSON.stringify(out,null,2));if(out.overallVerdict&&out.overallVerdict!=='GREEN')process.exitCode=15;}
module.exports={run,selftest};
