'use strict';
const assert=require('assert'),path=require('path');
const runtimeDir=path.resolve(__dirname,'../runtime');
require('./v39_runtime_candidate_loader.js');
const H=require('../final_match_rare_scenario_harness.js');
const CASES=Object.freeze([
  ['HC-05','FREE_KICK_ATTACK_LEFT','FINAL-MATCH-TEST-21'],['HC-08','FREE_KICK_DEFEND_RIGHT','FINAL-MATCH-TEST-27'],
  ['CTRL-DEF-L27','FREE_KICK_DEFEND_LEFT','FINAL-MATCH-TEST-27'],['CTRL-ATK-R27','FREE_KICK_ATTACK_RIGHT','FINAL-MATCH-TEST-27'],
  ['CTRL-ATK-L27','FREE_KICK_ATTACK_LEFT','FINAL-MATCH-TEST-27'],['CTRL-ATK-L15','FREE_KICK_ATTACK_LEFT','FINAL-MATCH-TEST-15']
]);
const OBS=Object.freeze(['FULLBACK_LANE_PLAUSIBILITY','CB_FB_ORDERING','MIDFIELD_ROTATION_REASON_LINK','FORWARD_LAYER_DEPTH','SETUP_TO_LIVE_RESPONSIBILITY_CONTINUITY']);
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d, lx=p=>p.team==='AWAY'?105-n(p.x):n(p.x), ly=p=>p.team==='AWAY'?68-n(p.y):n(p.y);
const task=p=>String(p?.tacticalTask||p?.action||'').toUpperCase(), reason=p=>String(p?.responsibilityReason||p?.reasonLink||p?.handoffReason||'').toUpperCase(), kickTime=r=>(r.actualEvents||[]).find(e=>e.type==='FREE_KICK_TAKEN')?.t;
const liveFrames=r=>{const k=kickTime(r);return Number.isFinite(k)?(r.frames||[]).filter(f=>n(f.time)>=k+1.5&&String(f.ball?.mode||'').toUpperCase()!=='DEAD'):[];};
const setupFrames=r=>{const k=kickTime(r);return(r.frames||[]).filter(f=>n(f.time)<n(k)-.001&&String(f.ball?.mode||'').toUpperCase()==='DEAD');};
function fullback(r){for(const f of liveFrames(r))for(const p of f.players||[])if(p.role==='FB'&&!p.markTargetId&&Math.abs(ly(p)-(p.slot==='LB'?12:56))>23)return{implemented:true,detected:true,reason:'UNEXPLAINED_FULLBACK_CROSS_LANE',time:f.time,player:p.id,localY:ly(p)};return{implemented:true,detected:false};}
function ordering(r){for(const f of liveFrames(r)){const groups={};for(const p of f.players||[])if(['LB','LCB','RCB','RB'].includes(p.slot))(groups[p.team]??=[]).push(p);for(const [team,ps] of Object.entries(groups)){const q=id=>ps.find(p=>p.slot===id),v=p=>p.team==='AWAY'?68-n(p.ty):n(p.ty),causal=p=>!!p&&(p.markTargetId||/TRACK|CENTRAL_FORWARD|FREE_KICK_(?:REST_DEFENCE|LINE_ZONE|TRACK_RUNNER)|^REST_DEFENCE$/.test(task(p))||/INVERT|BALANCE|COVERAGE|HANDOFF/.test(reason(p)));const a=q('LB'),b=q('LCB'),c=q('RCB'),d=q('RB');const bad=(a&&!causal(a)&&b&&!causal(b)&&!(v(a)<v(b)))||(d&&!causal(d)&&c&&!causal(c)&&!(v(c)<v(d)))||(b&&c&&!causal(b)&&!causal(c)&&!(v(b)<v(c)));if(bad)return{implemented:true,detected:true,reason:'CB_FB_ORDER_INVERSION',time:f.time,team,localY:{LB:a&&v(a),LCB:b&&v(b),RCB:c&&v(c),RB:d&&v(d)}};}}return{implemented:true,detected:false};}
function midfield(r){const baseline={HOME:null,AWAY:null},seen={HOME:false,AWAY:false};for(const f of liveFrames(r))for(const team of ['HOME','AWAY']){const ps=(f.players||[]).filter(p=>p.team===team&&['LCM','RCM'].includes(p.slot)),a=ps.find(p=>p.slot==='LCM'),b=ps.find(p=>p.slot==='RCM');if(!a||!b)continue;const s=Math.sign(ly(a)-ly(b));if(!baseline[team]&&s)baseline[team]=s;if(baseline[team])seen[team]=true;if(s&&s!==baseline[team]&&!a.markTargetId&&!b.markTargetId)return{implemented:true,detected:true,reason:'PURPOSELESS_CM_ORDER_FLIP',time:f.time,team,baseline:baseline[team],observed:s,teamsSeen:Object.keys(seen).filter(k=>seen[k])};}return{implemented:true,detected:false,baseline,teamsSeen:Object.keys(seen).filter(k=>seen[k])};}
function forward(r){for(const f of liveFrames(r))for(const p of f.players||[])if(['ST','WF'].includes(p.role)&&p.team===(r.boundary?.setPiece?.team||'HOME')&&!p.markTargetId&&!p.targetId&&lx(p)<55&&!/FREE_KICK_FORWARD_LAYER|RUNNER|OUTLET|ATTACK|RECEIVE|CARRY/.test(task(p)))return{implemented:true,detected:true,reason:'FORWARD_LAYER_TOO_DEEP',time:f.time,player:p.id,localX:lx(p),task:task(p)};return{implemented:true,detected:false};}
const roleSlots=['LB','LCB','RCB','RB','LCM','CM','RCM','ST','LW','RW'];
const knownHandoff=(s,l)=>s===l||(/RUNNER/.test(s)&&/^ATTACK_(CROSS|WIDE|CENTRAL)_ZONE$/.test(l));
function continuity(r){const setup=setupFrames(r),k=kickTime(r),live=(r.frames||[]).filter(f=>n(f.time)>=n(k)+.25&&String(f.ball?.mode||'').toUpperCase()!=='DEAD');if(!setup.length||!live.length)return{implemented:true,detected:true,reason:'MISSING_PHASE_FRAMES'};const s=setup.at(-1),l=live[0],problems=[];for(const slot of roleSlots){const a=(s.players||[]).find(p=>p.slot===slot),b=(l.players||[]).find(p=>p.slot===slot);if(!a||!b)continue;const explicit=b.responsibilityReason||b.responsibilityId||b.reasonLink||b.handoffReason||b.markTargetId||b.targetId;if(!knownHandoff(task(a),task(b))&&!explicit)problems.push({slot,setupTask:task(a),liveTask:task(b)});}return{implemented:true,detected:problems.length>0,reason:problems.length?'RESPONSIBILITY_REASON_LINK_BROKEN':'SETUP_LIVE_RESPONSIBILITY_LINKED',problems,setupTime:s.time,liveTime:l.time};}
const EVALUATORS=Object.freeze({FULLBACK_LANE_PLAUSIBILITY:fullback,CB_FB_ORDERING:ordering,MIDFIELD_ROTATION_REASON_LINK:midfield,FORWARD_LAYER_DEPTH:forward,SETUP_TO_LIVE_RESPONSIBILITY_CONTINUITY:continuity});
function evaluate(r){return Object.fromEntries(OBS.map(k=>[k,typeof EVALUATORS[k]==='function'?EVALUATORS[k](r):null]));}
function runCase(id,scenario,seed){const r=H.run(scenario,seed,{runtimeDir}),results=evaluate(r),missing=OBS.filter(k=>typeof EVALUATORS[k]!=='function'||!results[k]||results[k].implemented!==true);return{id,scenario,seed,coverage:{status:missing.length?'QA_INFRA_BLOCKED':'COVERED',required:OBS,missingEvaluators:missing,implementedEvaluators:OBS.filter(k=>!missing.includes(k))},verdict:missing.length?'RED':Object.values(results).every(x=>!x.detected)?'PASS':'RED',results};}
function fixtureFrame(time,flip=false){const players=[];for(const team of ['HOME','AWAY']){const aw=team==='AWAY',w=(x,y)=>({x:aw?105-x:x,y:aw?68-y:y}),add=(slot,role,x,y,tacticalTask)=>{const q=w(x,y);players.push({id:(aw?'A-':'H-')+slot,team,role,slot,x:q.x,y:q.y,tx:q.x,ty:q.y,tacticalTask});};add('LB','FB',50,flip?40:12,'FREE_KICK_LANE_COVER_HOLD');add('LCB','CB',50,flip?20:27,'FREE_KICK_CB_LINE_HOLD');add('RCB','CB',50,flip?42:41,'FREE_KICK_CB_LINE_HOLD');add('RB','FB',50,56,'FREE_KICK_LANE_COVER_HOLD');add('LCM','CM',50,flip?45:22,'FREE_KICK_SECOND_BALL_LANE_HOLD');add('RCM','CM',50,flip?20:46,'FREE_KICK_SECOND_BALL_LANE_HOLD');add('ST','ST',20,34,'FREE_KICK_FORWARD_LAYER_HOLD');}return{time,ball:{mode:'FLIGHT'},players};}
function mutate(){const good=fixtureFrame(2,false),bad=fixtureFrame(3,true),base={frames:[good,bad],actualEvents:[{type:'FREE_KICK_TAKEN',t:0}],boundary:{setPiece:{team:'HOME'}}},one=(frame,extra={})=>({...base,frames:[frame],...extra});const setup={time:-1,ball:{mode:'DEAD'},players:[{id:'H-ST',team:'HOME',role:'ST',slot:'ST',tacticalTask:'FREE_KICK_PRIMARY_RUNNER_RUN'}]},rewrite={time:2,ball:{mode:'FLIGHT'},players:[{id:'H-ST',team:'HOME',role:'ST',slot:'ST',tacticalTask:'GENERIC_OPEN_PLAY_SUPPORT'}]};return{causelessFullbackSwap:fullback(one(good,{frames:[{...good,players:good.players.map(p=>p.slot==='LB'?{...p,y:40,ty:40}:p)}]})).detected,cbFbInversion:ordering(one(bad)).detected,purposelessCmSwap:midfield(base).detected,forwardTooDeep:forward(one({...good,players:good.players.map(p=>p.slot==='ST'?{...p,x:20,tacticalTask:'SHOT_LANE_COVER'}:p)})).detected,setupToLiveResponsibilityRewrite:continuity({frames:[setup,rewrite],actualEvents:[{type:'FREE_KICK_TAKEN',t:0}]}).detected,coverage:{midfieldTeams:['HOME','AWAY'],midfieldBothBaseline:midfield(base).teamsSeen?.length===2,continuitySyntheticRewrite:'RED'}};}
function mirrorHorizontal(r){const swaps={LB:'RB',RB:'LB',LCB:'RCB',RCB:'LCB',LCM:'RCM',RCM:'LCM',LW:'RW',RW:'LW'};return{...r,frames:(r.frames||[]).map(f=>({...f,players:(f.players||[]).map(p=>({...p,slot:swaps[p.slot]||p.slot,y:68-n(p.y),ty:68-n(p.ty)}))}))};}
function mirrorAway(r){return{...r,frames:(r.frames||[]).map(f=>({...f,players:(f.players||[]).map(p=>({...p,team:p.team==='HOME'?'AWAY':'HOME',x:105-n(p.x),y:68-n(p.y),tx:105-n(p.tx),ty:68-n(p.ty),id:p.id.replace(/^H-/,'A-').replace(/^A-/,'H-')}))}))};}
const statusVector=r=>OBS.map(k=>evaluate(r)[k]?.detected===true);
function metamorphic(){const base={frames:[fixtureFrame(2,false)],actualEvents:[{type:'FREE_KICK_TAKEN',t:0}],boundary:{setPiece:{team:'HOME'}}},lr=mirrorHorizontal(base),ha=mirrorAway(base),a=statusVector(base),b=statusVector(lr),c=statusVector(ha);return{homeAwayEquivalent:JSON.stringify(a)===JSON.stringify(c),leftRightEquivalent:JSON.stringify(a)===JSON.stringify(b),comparisons:{base:a,leftRight:b,homeAway:c},executed:true};}
function run(){const cases=CASES.map(x=>runCase(...x)),mutations=mutate(),symmetry=metamorphic(),coverage={requiredObservables:OBS,evaluatorMap:Object.fromEntries(OBS.map(k=>[k,typeof EVALUATORS[k]==='function'?EVALUATORS[k].name:null])),cases:cases.map(x=>({id:x.id,status:x.coverage.status,missing:x.coverage.missingEvaluators})),status:cases.every(x=>x.coverage.status==='COVERED')?'COVERED':'QA_INFRA_BLOCKED'};const primary=cases.filter(x=>x.id==='HC-05'||x.id==='HC-08');return{module:'V40_FREE_KICK_CAUSAL_GEOMETRY_GATE',schemaVersion:'V40_FK_CAUSAL_GEOMETRY_1.1',verdict:coverage.status==='COVERED'&&Object.keys(mutations).filter(k=>k!=='coverage').every(k=>mutations[k]===true)&&symmetry.homeAwayEquivalent&&symmetry.leftRightEquivalent&&primary.every(x=>x.verdict==='PASS')?'PASS':'RED',cases:cases.map(x=>({...x,verdict:(x.id.startsWith('CTRL-')&&x.verdict==='RED')?'WATCH':x.verdict})),mutations,metamorphic:symmetry,coverage};}
function selftest(){const x=run();assert.equal(x.coverage.status,'COVERED');assert(Object.keys(x.mutations).filter(k=>k!=='coverage').every(k=>x.mutations[k]===true));assert.equal(x.mutations.coverage.midfieldBothBaseline,true);assert.equal(x.mutations.coverage.continuitySyntheticRewrite,'RED');assert(x.metamorphic.executed&&x.metamorphic.leftRightEquivalent&&x.metamorphic.homeAwayEquivalent);return{module:x.module,selftest:'PASS',mutationResults:x.mutations,metamorphic:x.metamorphic,coverage:x.coverage};}
if(require.main===module)console.log(JSON.stringify(run(),null,2));
module.exports={CASES,OBS,run,selftest,mutate,metamorphic,EVALUATORS};
