'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
const REGISTRY_PATH=path.join(__dirname,'v40_persistent_regression_registry.json');
function readRegistry(){return JSON.parse(fs.readFileSync(REGISTRY_PATH,'utf8'));}
function rel(p){return path.relative(ROOT,path.resolve(ROOT,p)).replaceAll(path.sep,'/');}
function loadCheck(check){const file=path.resolve(ROOT,check.path);if(!fs.existsSync(file))return{ok:false,reason:'MISSING_FILE'};try{const mod=require(file),fn=mod?.[check.export];if(typeof fn!=='function')return{ok:false,reason:'MISSING_EXPORT'};return{ok:true,module:mod,fn};}catch(error){return{ok:false,reason:'LOAD_ERROR',error:String(error.message||error)};}}
function validateSchema(reg){const errors=[];if(!reg||!Array.isArray(reg.contracts))return['contracts must be an array'];const ids=new Set();for(const c of reg.contracts){if(!/^FLR-[A-Z0-9-]+$/.test(c.id)||ids.has(c.id))errors.push(`invalid/duplicate id ${c.id}`);ids.add(c.id);if(!['ACTIVE','REVISED','SUPERSEDED','RETIRED'].includes(c.status))errors.push(`${c.id}: invalid status`);if(!['canonical','repeated-regression','user-visual-pass','temporary'].includes(c.protectionClass))errors.push(`${c.id}: invalid protectionClass`);for(const key of ['behaviorIntent','scope','revisionPolicy'])if(typeof c[key]!=='string'||!c[key])errors.push(`${c.id}: missing ${key}`);if(!Array.isArray(c.checks))errors.push(`${c.id}: checks must be an array`);if(c.status==='ACTIVE'&&c.checks.length===0&&c.protectionClass!=='user-visual-pass')errors.push(`${c.id}: active executable contract has no checks`);for(const h of c.history||[])if(!h.event||!h.ref)errors.push(`${c.id}: malformed history`);if(c.status==='REVISED'&&!(c.revision&&c.revision.reason&&c.revision.replacementBehavior&&Array.isArray(c.revision.affectedChecks)&&c.revision.decisionRef))errors.push(`${c.id}: revision record required`);}return errors;}
function checkAvailability(reg){const rows=[],errors=[];for(const c of reg.contracts.filter(x=>x.status==='ACTIVE')){const checks=(c.checks||[]).map(check=>{const loaded=loadCheck(check);if(!loaded.ok)errors.push({id:c.id,check,reason:loaded.reason,error:loaded.error||null});return{path:check.path,export:check.export,available:loaded.ok,reason:loaded.reason||null};});rows.push({id:c.id,status:c.status,checks});}return{ok:errors.length===0,errors,rows};}
function matches(file,pattern){return file===pattern||file.startsWith(pattern.endsWith('/')?pattern:pattern+'/')||file.includes(pattern);}
function impact(reg,changedFiles=[]){const files=changedFiles.map(rel),rows=reg.contracts.filter(c=>c.status==='ACTIVE').map(c=>{const hits=files.filter(f=>(c.affectedModules||[]).some(p=>matches(f,p))||(c.entrypoints||[]).some(p=>matches(f,p))||(c.dependencyTags||[]).some(tag=>f.toLowerCase().includes(tag.toLowerCase())));return{id:c.id,impacted:hits.length>0,changedFiles:hits,requiredChecks:c.checks||[]};}).filter(x=>x.impacted);return{changedFiles:files,impacted:rows};}
function runChecks(reg){const rows=[],errors=[];for(const c of reg.contracts.filter(x=>x.status==='ACTIVE'))for(const check of c.checks||[]){const loaded=loadCheck(check);if(!loaded.ok){errors.push({id:c.id,check,reason:loaded.reason});continue;}try{const value=loaded.fn();const verdict=value?.verdict||value?.selftest;const pass=verdict==='PASS'||value?.selftest==='PASS'||value?.overallVerdict==='GREEN';rows.push({id:c.id,check:check.path,export:check.export,pass,verdict:verdict||null});if(!pass)errors.push({id:c.id,check,reason:'CHECK_FAILED',verdict:verdict||null});}catch(error){errors.push({id:c.id,check,reason:'CHECK_ERROR',error:String(error.message||error)});}}return{ok:errors.length===0,rows,errors};}
function run({changedFiles=[],executedChecks=[],runActiveChecks=false,registry=null}={}){const reg=registry||readRegistry(),schemaErrors=validateSchema(reg),availability=checkAvailability(reg),impactReport=impact(reg,changedFiles),executed=new Set(executedChecks.map(String)),missingRequired=impactReport.impacted.flatMap(c=>c.requiredChecks.filter(x=>!executed.has(x.path)&&!executed.has(`${x.path}#${x.export}`)).map(x=>({id:c.id,check:x}))),checks=runActiveChecks?runChecks(reg):{ok:true,rows:[],errors:[]};const verdict=schemaErrors.length||!availability.ok||missingRequired.length||!checks.ok?'QA_INFRA_BLOCKED': 'PASS';return{module:'V40_PERSISTENT_REGRESSION_CONTRACT',schemaVersion:reg.schemaVersion,verdict,policy:{passIsRevisionAllowed:true,activeIsProtectedNotImmutable:true,missingActiveCheckIsQaInfraBlocked:true,impactedRuntimeRequiresChecks:true,explicitRevisionCanReplaceCheck:true,silentDeletionIsNotAllowed:true},schemaErrors,availability,impact:impactReport,missingRequiredChecks:missingRequired,checks};}
function selftest(){const reg=readRegistry(),good=run({runActiveChecks:false}),rewrite=JSON.parse(JSON.stringify(reg));rewrite.contracts[0].behaviorIntent='Same acceptance intent, different implementation wording';const rewriteResult=run({registry:rewrite});const mutation=(()=>{const copy=JSON.parse(JSON.stringify(reg));copy.contracts.find(c=>c.id==='FLR-RENDER-037').checks[0].path='QA/does-not-exist.js';return{schema:validateSchema(copy),availability:checkAvailability(copy)};})();assert.equal(good.verdict,'PASS');assert.equal(rewriteResult.verdict,'PASS');assert.equal(mutation.availability.ok,false);const impacted=run({changedFiles:['final_match_test_dock.js'],executedChecks:[]});assert.equal(impacted.verdict,'QA_INFRA_BLOCKED');assert(impacted.impact.impacted.some(x=>x.id==='FLR-RENDER-037'));const revised=JSON.parse(JSON.stringify(reg));const c=revised.contracts[0];c.status='REVISED';c.revision={reason:'intentional product revision',replacementBehavior:'same causal boundary with new presentation',affectedChecks:['QA/new.js'],decisionRef:'docs/decisions/DEC-TEST'};assert.deepEqual(validateSchema(revised),[]);return{module:'V40_PERSISTENT_REGRESSION_CONTRACT',selftest:'PASS',activeContracts:reg.contracts.filter(c=>c.status==='ACTIVE').length,implementationRewrite:'PASS',mutationMissingCheck:'QA_INFRA_BLOCKED',impactMutation:impacted.impact.impacted.map(x=>x.id),revisionTransition:'VALID'};}
if(require.main===module){const changed=process.argv.filter(x=>x.startsWith('--changed-file=')).map(x=>x.slice(15));const runChecksFlag=process.argv.includes('--run-active-checks');const out=process.argv.includes('--selftest')?selftest():run({changedFiles:changed,runActiveChecks:runChecksFlag});console.log(JSON.stringify(out,null,2));if(out.verdict&&out.verdict!=='PASS'&&out.selftest!=='PASS')process.exitCode=14;}
module.exports={readRegistry,validateSchema,checkAvailability,impact,runChecks,run,selftest};
