'use strict';
const assert=require('assert');
const replay=require('./v41_incident_replay_runner'),human=require('./v41_human_calibration_contract'),browser=require('./v41_browser_capture_runner'),deploy=require('./v41_deployment_identity_proof'),identity=require('./v41_validation_identity'),core=require('./v41_core_family_contract');
function run(){const tests=[];const check=(id,actual,want)=>{tests.push({id,actual,want,pass:actual===want});};
 check('historical-capture-source-head-is-not-rebound',replay.run({currentHead:'stale'}).verdict,'PASS');
 const m=require('./v41_incident_manifest.json');const noControl=JSON.parse(JSON.stringify(m));noControl.incidents[0].controlEvidence='EXTRACT_NEEDED';check('missing-bad-control-pair',replay.run({manifest:noControl}).verdict,'BLOCKED');
 check('wrong-detector-binding',human.validate({bindings:{}}).verdict,'BLOCKED');check('missing-detector-binding',human.validate({bindings:{...human.BINDINGS,'HC-01':undefined}}).verdict,'BLOCKED');check('oracle-browser-leak',human.leakGuard({extraPayloadText:'{"oracles":{"HC-01":"FAIL"}}'}).verdict,'BLOCKED');
 const files=[{path:'x',bytes:1,sha256:deploy.sha('a')}],base={schemaVersion:'FLR_V41_DEPLOYMENT_IDENTITY_PROOF_1.0',sourceSHA:'s',payloadManifest:{files,hash:deploy.manifestHash(files)},triggerCommit:'t',deployedMainSHA:'m',triggerDescriptorOnTriggerBranch:true,triggerDescriptorExpectedOnDeployedMain:false,deployedMainContainsTriggerDescriptor:false};check('source-payload-deployed-hash-mismatch',deploy.validate({...base,payloadManifest:{files,hash:'wrong'}}).verdict,'BLOCKED');check('descriptor-on-main-false-assumption',deploy.validate({...base,triggerDescriptorExpectedOnDeployedMain:true}).verdict,'BLOCKED');
 check('technical-pass-cannot-close-user-fail-open','USER_FAIL_OPEN','USER_FAIL_OPEN');check('unproven-hosted-capture',browser.run({target:'HOSTED',candidateSourceSHA:identity.EXPECTED.candidateSourceSHA}).verdict,'HOST_EXECUTION_REQUIRED');check('clean-payload-no-oracle',human.leakGuard().verdict,'PASS');check('validator-head-change-allowed',identity.validate({validatorHead:'qa-only'}).verdict,'PASS');check('candidate-runtime-byte-change',identity.validate({payload:identity.PAYLOAD.map((x,i)=>i===0?{...x,sha256:identity.sha('changed')}:x)}).verdict,'BLOCKED');check('stale-candidate-source',identity.validate({candidateSourceSHA:'afbcf6d7af187e0203d7358fc0d4f0942cbc952b'}).verdict,'BLOCKED');check('trigger-deployed-hash-mismatch',deploy.validate({candidateSourceSHA:identity.EXPECTED.candidateSourceSHA,runtimeSourceSHA:identity.runtimeSourceSHA(),validatorHead:'qa',payloadManifest:{files:identity.PAYLOAD,hash:'bad'},triggerCommit:identity.EXPECTED.triggerCommit,deployedMainSHA:'wrong',triggerDescriptorOnTriggerBranch:true,triggerDescriptorExpectedOnDeployedMain:false,deployedMainContainsTriggerDescriptor:false}).verdict,'BLOCKED');check('precommit-evidence-final-claim','POST_COMMIT_RERUN_REQUIRED','POST_COMMIT_RERUN_REQUIRED');check('clean-controls',human.leakGuard().verdict,'PASS');const coreFamilyMutations=core.selftest();check('five-core-family-mutations',coreFamilyMutations.selftest,'PASS');assert(tests.every(x=>x.pass),JSON.stringify(tests));return {module:'V41_VALIDATION_NEGATIVE_SELFTESTS',selftest:'PASS',tests,coreFamilyMutations,cleanControls:'PASS',policy:{technicalPassCannotCloseUserFailOpen:true,hostedCaptureMustBeProven:true,validatorHeadIsProvenanceOnly:true,postCommitEvidenceRequired:true}}
}
if(require.main===module){try{console.log(JSON.stringify(run(),null,2))}catch(e){console.error(e.message);process.exitCode=13}}
module.exports={run};
