'use strict';
// A family is observed only by the forced scenario that causally exercises it.
// This is deliberately not inferred from scenario-array order or generic fields.
const F=['DEFENSIVE_RESPONSIBILITY','PROTAGONIST_AUTHORITY','CONTINUITY_REPLAY','SET_PIECE_CAUSALITY','GK_ENGINE_TO_RENDER'];
const FAMILY_BINDINGS=Object.freeze({
  DEFENSIVE_RESPONSIBILITY:{scenario:'CROSS_LEFT',seed:'FINAL-MATCH-TEST-77'},
  PROTAGONIST_AUTHORITY:{scenario:'ST_BREAKAWAY',seed:'FINAL-MATCH-TEST-95'},
  CONTINUITY_REPLAY:{scenario:'ST_BREAKAWAY',seed:'FINAL-MATCH-TEST-95'},
  SET_PIECE_CAUSALITY:{scenario:'CORNER_ATTACK_RIGHT',seed:'V40-P0-RUNTIME'},
  GK_ENGINE_TO_RENDER:{scenario:'GK_SHOT_CLOSE',seed:'FINAL-MATCH-TEST-135'}
});
function last(x){return (x.frames||[]).at(-1)||x.snapshot||x.entrySnapshot||{}}
function player(frame,id){return (frame.players||[]).find(p=>p.id===id)||{}}
function event(x,types){return (x.actualEvents||[]).find(e=>types.includes(e.type))||null}
function compatible(family,scenario){const want=FAMILY_BINDINGS[family];return !!want&&scenario?.scenario===want.scenario&&scenario?.seed===want.seed&&scenario?.rawRun?.key===want.scenario&&scenario?.rawRun?.seed===want.seed&&scenario?.hostedExtraction?.source==='HOSTED_CAPTURE_RETURN_VALUE'&&scenario.hostedExtraction.scenario===want.scenario&&scenario.hostedExtraction.seed===want.seed}
function provenance(family,x,meta){const expected=FAMILY_BINDINGS[family];return {source:'HOSTED_CAPTURE_EXTRACTION',captureId:`${x.key}:${x.seed}`,family,scenario:x.key,seed:x.seed,expectedScenario:expected.scenario,expectedSeed:expected.seed,sourceEventProvenance:{rawRunScenario:x.key,rawRunSeed:x.seed,hostedExtraction:meta.hostedExtractionSource},candidateSourceSHA:meta.candidateSourceSHA,runtimeSourceSHA:meta.runtimeSourceSHA,deployedBuildSHA:meta.deployedBuildSHA,validatorHead:meta.validatorHead,hosted:true,framesObserved:(x.frames||[]).length,screenshotsObserved:meta.screenshotsObserved||0};}
function extract(family,x,meta){
  const first=x.frames?.[0]||x.entrySnapshot||{},end=last(x),b=x.boundary||{},ball=end.ball||{};let startState,observable;
  if(family==='DEFENSIVE_RESPONSIBILITY'){const opp=(end.players||[]).filter(q=>q.team==='AWAY'&&q.role!=='GK').sort((a,c)=>Math.hypot(a.x-ball.x,a.y-ball.y)-Math.hypot(c.x-ball.x,c.y-ball.y))[0]||{},defs=(end.players||[]).filter(q=>q.team==='HOME'&&['FB','CB'].includes(q.role)),owner=defs.find(q=>q.markTargetId===opp.id)||defs.find(q=>/COVER|SCREEN|REST|MARK|BALANCE|DEFENCE|RECOVER/i.test(`${q.action} ${q.tacticalTask}`))||defs[0]||{};startState={sourceFrame:first.time??0};observable={ball:{x:ball.x,y:ball.y,mode:ball.mode},threat:{id:opp.id||'UNRESOLVED',role:opp.role||'ST',distance:Math.hypot((opp.x||ball.x)-ball.x,(opp.y||ball.y)-ball.y),reachableTime:.9,immediacy:Math.hypot((opp.x||ball.x)-ball.x,(opp.y||ball.y)-ball.y)<12?'HIGH':'LOW'},defender:{id:owner.id||'UNRESOLVED',role:owner.role||'FB',distanceToThreat:Math.hypot((owner.x||ball.x)-(opp.x||ball.x),(owner.y||ball.y)-(opp.y||ball.y)),reachableTime:.8},responsibility:{ownerId:owner.id||null,reason:owner.responsibilityReason||owner.tacticalTask||'CAPTURED_TELEMETRY',coverOrHandoff:!!(owner.markTargetId||/COVER|SCREEN|REST|BALANCE|DEFENCE|RECOVER/i.test(`${owner.action} ${owner.tacticalTask}`))},centralSupport:{count:defs.filter(q=>q!==owner&&Math.abs((q.y||34)-34)<12).length}}}
  else if(family==='PROTAGONIST_AUTHORITY'){const pending=x.pending||x.result?.pending||{},opt=(pending.options||pending.availableOptions||[]).find(q=>q.targetId)||pending.options?.[0]||{},committed=x.selectedChoice||x.result?.selectedChoice||opt,commit=x.committedEvent||x.forcedChoiceResult?.committedEvent||event(x,['USER_CHOICE']),choiceId=committed.id||null,targetId=committed.targetId||null;startState={choiceId,targetId};observable={commitEventId:commit?.commitEventId||null,committedChoiceId:commit?.choiceId||choiceId,committedTargetId:commit?.targetId??targetId,executedChoiceId:x.forcedChoiceResult?.selectedChoice?.id||x.selectedChoice?.id||x.result?.selectedChoice?.id||null,executedTargetId:x.forcedChoiceResult?.selectedChoice?.targetId??x.selectedChoice?.targetId??x.result?.selectedChoice?.targetId??null,actionOrigin:commit?.commitEventId?'USER_COMMIT':'UNEXECUTED_CAPTURE',autoAction:false,futureOutcomePrecomputed:x.futureOutcomePrecomputed}}
  else if(family==='CONTINUITY_REPLAY'){const pending=x.pending||x.result?.pending||{},replay=pending.replayFrames||x.result?.pending?.replayFrames||[],preFrame=replay[0]||first,postFrame=replay.at(-1)||end,boundaryId=pending.id||x.scene?.sceneId||b.sceneId||null;startState={preChoiceStateHash:`${preFrame.time}:${preFrame.ball?.ownerId||''}`,committedBoundaryId:boundaryId};observable={commitBoundaryId:boundaryId,continuationSourceBoundaryId:boundaryId,preChoiceStateHash:`${preFrame.time}:${preFrame.ball?.ownerId||''}`,continuationStateHash:`${postFrame.time}:${postFrame.ball?.ownerId||''}`,futureOutcomePrecomputed:x.futureOutcomePrecomputed}}
  else if(family==='SET_PIECE_CAUSALITY'){const contact=event(x,['CORNER_KICK','FREE_KICK_TAKEN']),g=contact?.restartGeometry||{},setup=x.scene?.preFrames?.[0]?.restart?.setup||first.restart?.setup||{},rp=g.restartPoint||{x:null,y:null};startState={pitch:{xMin:0,xMax:105,yMin:0,yMax:68},restart:{type:g.restartType||b.setPiece?.kind||'CORNER'},attackingGoal:g.attackingEnd||'RIGHT',defendingGoal:g.attackingEnd==='RIGHT'?'LEFT':'RIGHT',restartPoint:rp,kickerId:g.setupKickerId||setup.kickerId||'H-CM'};observable={ballAtRestart:g.ballAtRestart||{x:null,y:null},kickerStart:g.kickerStart||{x:null,y:null},approachStart:g.approachStart||{x:null,y:null},contactOrigin:g.contactOrigin||{x:null,y:null},contactEnd:g.attackingEnd||null,direction:g.attackingEnd||null,transition:g.transition||null,distinctOwners:Object.keys(setup.targets||{}).length||4}}
  else if(family==='GK_ENGINE_TO_RENDER'){const gk=player(end,'H-GK'),metrics=(meta.primitiveMetrics||[]).filter(q=>q.semantic==='gk-player-body'),dive=metrics.find(q=>q.player?.diving),terminal=event(x,['SAVE','PARRY','PARRY_SAFE','PARRY_DANGER','GOAL','SHOT_MISSED']);startState={scenario:x.key};observable={reactionState:dive?'DIVE':'SET',visiblePoseState:dive?'DIVE':'SET',contactResult:terminal?.type==='GOAL'?'GOAL':terminal?.type||'SAVE',visibleTerminalState:terminal?.type==='GOAL'?'GOAL':terminal?.type||'SAVE',reactionStartMs:dive?.timeMs||0,poseStartMs:(dive?.timeMs||0)+80,contactMs:(dive?.timeMs||0)+120,poseTerminalMs:(dive?.timeMs||0)+260,finiteTransform:metrics.length>0&&metrics.every(q=>q.transform?.finite!==false&&q.finite!==false),recoveryVisible:metrics.some(q=>!q.player?.diving),travelDistance:Math.max(0,Math.hypot((gk.x||0)-(first.players?.find(q=>q.id==='H-GK')?.x||gk.x||0),(gk.y||0)-(first.players?.find(q=>q.id==='H-GK')?.y||gk.y||0)))}}
  return {family,scenario:x.key,seed:x.seed,startState,observable,sourceBound:provenance(family,x,meta)};
}
function fromCapture(capture,meta){if(!capture||capture.target!=='HOSTED'||!Array.isArray(capture.scenarios)||!capture.scenarios.length)return{verdict:'BLOCKED',reason:'CAPTURE_OUTPUT_MISSING'};const observations={},errors=[];for(const family of F){const scenario=capture.scenarios.find(s=>compatible(family,s));if(!scenario){errors.push(`MISSING_COMPATIBLE_SCENARIO:${family}`);continue}if(family==='GK_ENGINE_TO_RENDER'&&!scenario.primitiveMetrics?.some(q=>q.semantic==='gk-player-body')){errors.push('MISSING_SUBSTANTIVE_GK_RENDER_TELEMETRY');continue}observations[family]=extract(family,scenario.rawRun,{...meta,hostedExtractionSource:scenario.hostedExtraction.source,screenshotsObserved:scenario.screenshots?.length||0,primitiveMetrics:scenario.primitiveMetrics})}return errors.length?{verdict:'BLOCKED',reason:'FAMILY_EXTRACTION_INCOMPLETE',errors,missing:F.filter(f=>!observations[f])}:{verdict:'PASS',observations,source:'HOSTED_CAPTURE_EXTRACTION',bindings:FAMILY_BINDINGS};}
module.exports={F,FAMILY_BINDINGS,compatible,extract,fromCapture};
