'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),MANIFEST=require('./v41_incident_manifest.json'),core=require('./v41_core_family_contract');
const FAMILY={'INC-PROTAGONIST-AUTO-ACTION':'PROTAGONIST_AUTHORITY','INC-REPLAY-CONTINUATION-REUSE':'CONTINUITY_REPLAY','INC-277-WRONG-END-FROZEN-SETUP':'SET_PIECE_CAUSALITY','INC-CORNER-FK-OWNERSHIP-COLLAPSE':'SET_PIECE_CAUSALITY','INC-FORWARD-LAYER-ABANDONMENT':'DEFENSIVE_RESPONSIBILITY','INC-GK-REACTION-POSE-MISMATCH':'GK_ENGINE_TO_RENDER'};
// Incident capture #394 is a narrow captured-boundary contract, not a
// substitute for the complete current-runtime set-piece observation schema.
// Its historical ownership pair truthfully records the two fields that the
// incident's detector observed; the broader core detector remains unchanged.
const CURRENT_DETECTOR={
 'INC-CORNER-FK-OWNERSHIP-COLLAPSE':x=>{const o=x?.observable||{},ok=Number(o.distinctOwners)>=2&&o.clustered===false;return{layer0:ok?'PASS':'HARD_FAIL',verdict:ok?'PASS':'HARD_FAIL'};}
};
function head(){const h=fs.readFileSync(path.join(ROOT,'.git','HEAD'),'utf8').trim();return h.startsWith('ref: ')?fs.readFileSync(path.join(ROOT,'.git',h.slice(5)),'utf8').trim():h}
function read(p){return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'))}
function validateRow(row,detectorSourceHead=head()){
 const errors=[],evidence=[];for(const k of ['id','scenario','seed','detector','badEvidence','controlEvidence','status'])if(!row[k])errors.push(`MISSING_${k.toUpperCase()}`);
 if(String(row.status).startsWith('DEFER_'))return {incidentId:row.id,status:row.status,errors:[],detectorSourceHead,reason:row.rationale||null};
 if(row.status==='EXTRACT_NEEDED')return {incidentId:row.id,status:'EXTRACT_NEEDED',errors:['MISSING_CAPTURED_BOUNDARY_PAIR'],detectorSourceHead};
 for(const [kind,p] of [['bad',row.badEvidence],['control',row.controlEvidence]]){if(!p||p==='EXTRACT_NEEDED'||!fs.existsSync(path.join(ROOT,p))){errors.push(`MISSING_${kind.toUpperCase()}_EVIDENCE`);continue}const x=read(p);evidence.push([kind,x]);if(!/^[a-f0-9]{40}$/.test(x.sourceHead||''))errors.push(`${kind.toUpperCase()}_SOURCE_HEAD_INVALID`);if(x.incidentId!==row.id)errors.push(`${kind.toUpperCase()}_INCIDENT_ID_MISMATCH`);if(x.scenario!==row.scenario||x.seed!==row.seed)errors.push(`${kind.toUpperCase()}_SCENARIO_SEED_MISMATCH`);if(x.resultStatus!==(kind==='bad'?'BAD_REPRODUCTION':'CONTROL_REPRODUCTION'))errors.push(`${kind.toUpperCase()}_STATUS_INVALID`);}
 const bad=evidence.find(([kind])=>kind==='bad')?.[1],control=evidence.find(([kind])=>kind==='control')?.[1];if(bad&&control&&bad.sourceHead!==control.sourceHead)errors.push('CAPTURE_SOURCE_HEAD_MISMATCH');const coreFamily=FAMILY[row.id],detector=CURRENT_DETECTOR[row.id]||core.detectors[coreFamily];if(!detector)errors.push('UNKNOWN_CURRENT_DETECTOR_BINDING');else if(bad&&control){const b=detector(bad),c=detector(control);if(b.layer0!=='HARD_FAIL')errors.push('BAD_NOT_REJECTED_BY_CURRENT_DETECTOR');if(!['PASS','WATCH'].includes(c.verdict))errors.push('CONTROL_NOT_ACCEPTED_BY_CURRENT_DETECTOR');}return {incidentId:row.id,status:errors.length?'BLOCKED':'REPLAY_PAIR_OK',errors,detector:row.detector,coreFamily,detectorSourceHead,evidenceIdentity:{kind:'HISTORICAL_CAPTURED_BOUNDARY',sourceHead:bad?.sourceHead||control?.sourceHead||null,immutable:true,currentDetectorSemantics:true}};
}
function run({manifest=MANIFEST,currentHead=head()}={}){const rows=(manifest.incidents||[]).map(x=>validateRow(x,currentHead)),active=rows.filter(x=>!String(x.status).startsWith('DEFER_')&&x.status!=='EXTRACT_NEEDED');return {module:'V41_INCIDENT_REPLAY_RUNNER',schemaVersion:'FLR_V41_INCIDENT_REPLAY_RESULT_1.1',detectorSourceHead:currentHead,results:rows,counts:{total:rows.length,pairOk:active.filter(x=>x.status==='REPLAY_PAIR_OK').length,blocked:active.filter(x=>x.status==='BLOCKED').length,extractNeeded:rows.filter(x=>x.status==='EXTRACT_NEEDED').length,deferred:rows.filter(x=>String(x.status).startsWith('DEFER_')).length},verdict:active.every(x=>x.status==='REPLAY_PAIR_OK')?'PASS':'BLOCKED',policy:{badAndControlRequired:true,extractNeededNeverGreen:true,deferredOutsidePhaseA:true,historicalEvidenceIdentityImmutable:true,currentDetectorSemanticsRequired:true,currentRuntimeRegressionsRequireSourceBoundObservations:true}}}
function selftest(){const good=run({currentHead:'ae8fa176307ed76d74cfd957263b486d066e8986'});assert.equal(good.verdict,'PASS');assert(good.results.filter(x=>x.status==='REPLAY_PAIR_OK').every(x=>x.evidenceIdentity?.sourceHead==='b4777768f41ee252ba38ecfa84a01fc8409fb182'));const miss=JSON.parse(JSON.stringify(MANIFEST));miss.incidents[0].controlEvidence='EXTRACT_NEEDED';assert.equal(run({manifest:miss}).verdict,'BLOCKED');const wrong=JSON.parse(JSON.stringify(MANIFEST));wrong.incidents[0].id='UNKNOWN';assert.equal(run({manifest:wrong}).verdict,'BLOCKED');const mixed=JSON.parse(JSON.stringify(MANIFEST)),original=read(mixed.incidents[0].controlEvidence),temp='QA/fixtures/v41/incidents/.v41-mixed-source-head-selftest.json';fs.writeFileSync(path.join(ROOT,temp),JSON.stringify({...original,sourceHead:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}));mixed.incidents[0].controlEvidence=temp;try{assert.equal(run({manifest:mixed}).verdict,'BLOCKED')}finally{fs.unlinkSync(path.join(ROOT,temp))}return {module:'V41_INCIDENT_REPLAY_RUNNER',selftest:'PASS',activePairs:good.counts.pairOk,extractNeeded:good.counts.extractNeeded,deferred:good.counts.deferred,historicalCaptureIdentity:'PRESERVED',currentDetectorSemantics:'PASS',negativeMissingControl:'BLOCKED',negativeUnknownDetector:'BLOCKED',negativeMixedCaptureSource:'BLOCKED'} }
if(require.main===module){const out=process.argv.includes('--selftest')?selftest():run();console.log(JSON.stringify(out,null,2));if(out.verdict==='BLOCKED'||out.selftest!=='PASS')process.exitCode=12}
module.exports={run,validateRow,selftest};
