'use strict';
const crypto=require('crypto'),assert=require('assert'),identity=require('./v41_validation_identity');
function sha(v){return crypto.createHash('sha256').update(v).digest('hex')}
function canonical(files){return (files||[]).map(x=>({path:x.path,bytes:x.bytes,sha256:x.sha256})).sort((a,b)=>a.path.localeCompare(b.path))}
function manifestHash(files){return sha(JSON.stringify(canonical(files)))}
function validate(m){const e=[];if(!m||m.schemaVersion!=='FLR_V41_DEPLOYMENT_IDENTITY_PROOF_1.0')e.push('SCHEMA_INVALID');if(!m.candidateSourceSHA)e.push('CANDIDATE_SOURCE_SHA_MISSING');if(!m.runtimeSourceSHA)e.push('RUNTIME_SOURCE_SHA_MISSING');if(!m.validatorHead)e.push('VALIDATOR_HEAD_MISSING');if(!m.payloadManifest||!Array.isArray(m.payloadManifest.files))e.push('PAYLOAD_MANIFEST_MISSING');if(!m.triggerCommit)e.push('TRIGGER_COMMIT_MISSING');if(!m.deployedMainSHA)e.push('DEPLOYED_MAIN_SHA_MISSING');if(m.payloadManifest&&m.payloadManifest.hash!==manifestHash(m.payloadManifest.files))e.push('PAYLOAD_MANIFEST_HASH_MISMATCH');if(m.deployedMainSHA===m.triggerCommit)e.push('TRIGGER_AND_DEPLOYED_MAIN_MUST_BE_DISTINCT');if(m.triggerDescriptorExpectedOnDeployedMain!==false)e.push('INVALID_TRIGGER_DESCRIPTOR_SEMANTICS');if(m.triggerDescriptorOnTriggerBranch!==true)e.push('TRIGGER_DESCRIPTOR_NOT_ON_TRIGGER_BRANCH');if(m.deployedMainContainsTriggerDescriptor!==false)e.push('DESCRIPTOR_MUST_NOT_BE_REQUIRED_ON_DEPLOYED_MAIN');if(m.payloadManifest?.files.some(x=>!x.path||!x.sha256||!Number.isInteger(x.bytes)))e.push('PAYLOAD_FILE_DECLARATION_INVALID');if(!e.length){const p=identity.validate({candidateSourceSHA:m.candidateSourceSHA,runtimeSHA:m.runtimeSourceSHA,validatorHead:m.validatorHead,payload:m.payloadManifest.files});if(p.verdict==='BLOCKED')e.push(...p.errors);if(m.candidateSourceSHA!==identity.EXPECTED.candidateSourceSHA)e.push('CANDIDATE_SOURCE_SHA_NOT_CURRENT_V42_TRUTH');if(m.triggerCommit!==identity.EXPECTED.triggerCommit)e.push('TRIGGER_HASH_MISMATCH');if(m.deployedMainSHA!==identity.EXPECTED.deployedMainSHA)e.push('DEPLOYED_MAIN_HASH_MISMATCH')}return {verdict:e.length?'BLOCKED':'PASS',errors:e,identity:{candidateSourceSHA:m?.candidateSourceSHA||null,runtimeSourceSHA:m?.runtimeSourceSHA||null,validatorHead:m?.validatorHead||null,payloadManifestHash:m?.payloadManifest?.hash||null,triggerCommit:m?.triggerCommit||null,deployedMainSHA:m?.deployedMainSHA||null},contract:{triggerDescriptor:'trigger branch .flr/deploy.json',deployedMain:'changedFiles only; descriptor not expected',validatorHead:'provenance only; never runtime identity'}}}
function selftest(){const files=[{path:'x',bytes:1,sha256:sha('a')}],base={schemaVersion:'FLR_V41_DEPLOYMENT_IDENTITY_PROOF_1.0',candidateSourceSHA:identity.EXPECTED.candidateSourceSHA,runtimeSourceSHA:identity.runtimeSourceSHA(),validatorHead:'validator',payloadManifest:{files,hash:manifestHash(files)},triggerCommit:identity.EXPECTED.triggerCommit,deployedMainSHA:identity.EXPECTED.deployedMainSHA,triggerDescriptorOnTriggerBranch:true,triggerDescriptorExpectedOnDeployedMain:false,deployedMainContainsTriggerDescriptor:false};const cases=[['missing live proof',base,'BLOCKED'],['wrong descriptor assumption',{...base,triggerDescriptorExpectedOnDeployedMain:true},'BLOCKED'],['trigger mismatch',{...base,triggerCommit:'wrong'},'BLOCKED']];const results=cases.map(([name,m,want])=>({name,want,actual:validate(m).verdict,pass:validate(m).verdict===want}));assert(results.every(x=>x.pass));return {module:'V41_DEPLOYMENT_IDENTITY_PROOF',selftest:'PASS',cases:results,contract:validate(base).contract}}
if(require.main===module){const out=process.argv.includes('--selftest')?selftest():validate(JSON.parse(process.argv[2]||'{}'));console.log(JSON.stringify(out,null,2));if(out.verdict==='BLOCKED')process.exitCode=12}
module.exports={sha,canonical,manifestHash,validate,selftest};
