'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
const CASES=require('./v40_human_calibration_manifest.json'),PRECOMMIT=require('./v41_human_calibration_oracles.json');
const BINDINGS={"HC-01":"choice-boundary-and-cursor","HC-02":"live-corner-responsibility","HC-03":"gk-visible-pose-travel","HC-04":"central-st-wide-responsibility","HC-05":"central-st-wide-responsibility","HC-06":"corner-ownership-cluster","HC-07":"current-state-replay-continuation","HC-08":"set-piece-kicker-approach-contact","HC-09":"central-st-wide-responsibility","HC-10":"current-state-replay-continuation","HC-11":"gk-visible-pose-travel","HC-12":"corner-ownership-cluster"};
const ORACLES=PRECOMMIT.oracles;
function oracleHash(){return crypto.createHash('sha256').update(JSON.stringify(ORACLES)).digest('hex')}
function validate({cases=CASES.cases,bindings=BINDINGS,oracles=ORACLES}={}){const errors=[];for(const c of cases){if(!bindings[c.id])errors.push(`${c.id}:MISSING_DETECTOR_BINDING`);if(!oracles[c.id])errors.push(`${c.id}:MISSING_PRECOMMITTED_ORACLE`)}for(const id of Object.keys(bindings))if(!cases.some(x=>x.id===id))errors.push(`${id}:ORPHAN_BINDING`);return {verdict:errors.length?'BLOCKED':'PASS',errors,caseCount:cases.length,oracleHash:oracleHash(),policy:{detectorBindingRequired:true,oraclePrecommitted:true,oracleValidatorOnly:true,userJudgmentDoesNotAutoPass:true}}}
function leakGuard({extraPayloadText=''}={}){const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');const browserRefs=[...index.matchAll(/(?:src|href)=["']([^"']+)["']/g)].map(x=>x[1]).filter(x=>!x.startsWith('http'));const payloadText=browserRefs.map(p=>fs.existsSync(path.join(ROOT,p))?fs.readFileSync(path.join(ROOT,p),'utf8'):'').join('\n')+extraPayloadText;const leaks=[];if(/v(?:40|41)_human_calibration_oracles\.json/i.test(payloadText))leaks.push('ORACLE_FILE_REFERENCE');if(/\"oracles\"\s*:\s*\{[\s\S]*HC-0[1-9]/i.test(payloadText))leaks.push('ORACLE_DATA_SHAPE');return {verdict:leaks.length?'BLOCKED':'PASS',browserRefs,leaks,policy:'validator-only oracle material is excluded from browser payload'} }
function selftest(){assert.equal(validate().verdict,'PASS');assert.equal(validate({bindings:{}}).verdict,'BLOCKED');assert.equal(validate({oracles:{}}).verdict,'BLOCKED');assert.equal(leakGuard().verdict,'PASS');assert.equal(leakGuard({extraPayloadText:'{"oracles":{"HC-01":"FAIL"}}'}).verdict,'BLOCKED');return {module:'V41_HUMAN_CALIBRATION_CONTRACT',selftest:'PASS',detectorBinding:'PASS',missingBinding:'BLOCKED',missingOracle:'BLOCKED',oracleLeak:'PASS',mutatedOraclePayload:'BLOCKED'} }
if(require.main===module){const out=process.argv.includes('--selftest')?selftest():{contract:validate(),leakGuard:leakGuard()};console.log(JSON.stringify(out,null,2));if(out.selftest!=='PASS'&&out.contract?.verdict!=='PASS')process.exitCode=12}
module.exports={validate,leakGuard,selftest,BINDINGS,ORACLES};
