'use strict';
const assert=require('assert'),path=require('path');
const core=require('./v41_core_family_contract'),negative=require('./v41_validation_negative_selftests'),replay=require('./v41_incident_replay_runner'),identity=require('./v41_validation_identity'),browser=require('./v41_browser_capture_runner');
function readEvidence(e){if(!e)return null;try{return typeof e==='string'?JSON.parse(require('fs').readFileSync(path.resolve(e),'utf8')):e}catch{return null}}
function hostedEvidence(bundle){if(!bundle)return null;if(bundle.hostedEvidence)return bundle.hostedEvidence;if(!bundle.captureManifest)return null;return {...bundle.captureManifest,candidateSourceSHA:bundle.candidateSourceSHA,runtimeSourceSHA:bundle.runtimeSourceSHA,deployedBuildSHA:bundle.deployedBuildSHA,validatorHead:bundle.validatorHead,futureOutcomePrecomputed:bundle.futureOutcomePrecomputed};}
function run({evidence=null}={}){const bundle=readEvidence(evidence),capture=hostedEvidence(bundle),sid={candidateSourceSHA:identity.EXPECTED.candidateSourceSHA,runtimeSourceSHA:identity.runtimeSourceSHA(),deployedBuildSHA:identity.EXPECTED.deployedMainSHA,validatorHead:bundle?.validatorHead||identity.validatorHead()},h=browser.run({target:'HOSTED',candidateSourceSHA:sid.candidateSourceSHA,runtimeSourceSHA:sid.runtimeSourceSHA,validatorHead:sid.validatorHead,hostedEvidence:capture}),c=core.evaluate({currentCandidateObservations:bundle?.observations||null,sourceIdentity:sid}),n=negative.run(),r=replay.run({currentHead:identity.EXPECTED.candidateSourceSHA}),i=identity.validate({validatorHead:sid.validatorHead});const executed=c.results.every(x=>x.variants.length>0&&x.variants.every(v=>v.executed&&v.seed&&v.verdict)),covered=c.results.every(x=>x.sourceBoundObservation.status==='CURRENT_CANDIDATE_OBSERVED'),currentGreen=covered&&c.results.every(x=>['PASS','WATCH'].includes(x.sourceBoundObservation.detectorVerdict));const checks={layer0HardControls:c.results.every(x=>x.detectorUnit.badDetected&&x.detectorUnit.bad.layer0==='HARD_FAIL'),layer1CausalityDiscrimination:c.detectorUnitVerdict==='PASS',realVariantExecution:executed,sourceBoundCurrentCandidateObservation:covered,hostedEvidenceContract:h.verdict==='PASS',identityPublicPayloadBinding:i.verdict==='PASS',diversityPreservationFalsePositiveGuard:c.diversityPreservationFalsePositiveGuard.accepted,currentCandidateObservationsGreen:currentGreen,userFailOpen:true};const substance=checks.layer0HardControls&&checks.layer1CausalityDiscrimination&&executed&&checks.diversityPreservationFalsePositiveGuard,validatorGap=!bundle||h.verdict!=='PASS'||!covered;const verdict=checks.identityPublicPayloadBinding&&substance&&checks.hostedEvidenceContract&&currentGreen?'READY_FOR_FINAL_HOST_FREEZE_VALIDATION':validatorGap?'BLOCKED_VALIDATOR_GAP':substance?'VALIDATOR_READY_RUNTIME_FINDINGS':'BLOCKED_VALIDATOR_GAP';return {module:'V41_VALIDATION_FREEZE_GATE',schemaVersion:'FLR_V41_VALIDATION_FREEZE_GATE_2.2',checks,coreFamilies:c,incidentReplay:r,hostBoundary:h,identity:i,verdict,validatorGap,hostedExecution:bundle?'CAPTURED_AND_EVALUATED':'NOT_EXECUTED',userFailOpen:'OPEN',step79:'NOT_STARTED',postCommitDisposition:'READY_FOR_HOST_OBSERVATION_EXECUTION',freezePolicy:'VALIDATOR_FREEZE_POLICY'};}
function selftest(){const x=run();assert.equal(x.coreFamilies.detectorUnitVerdict,'PASS');assert.equal(x.checks.realVariantExecution,true);assert.equal(x.checks.diversityPreservationFalsePositiveGuard,true);assert.equal(x.verdict,'BLOCKED_VALIDATOR_GAP');assert.equal(x.hostedExecution,'NOT_EXECUTED');assert.equal(run({evidence:{}}).verdict,'BLOCKED_VALIDATOR_GAP');return {module:x.module,selftest:'PASS',noObservationBundle:'BLOCKED_VALIDATOR_GAP',unitFixtureCannotInferRuntime:true,verdict:x.verdict,checks:x.checks,hostedExecution:x.hostedExecution};}
if(require.main===module){const x=process.argv.includes('--selftest')?selftest():run({evidence:process.argv.find(a=>a.startsWith('--evidence='))?.slice(11)});const out=process.argv.find(a=>a.startsWith('--output='));if(out)require('fs').writeFileSync(path.resolve(__dirname,'..',out.slice(9)),JSON.stringify(x,null,2)+'\n');console.log(JSON.stringify(x,null,2));if(x.verdict==='BLOCKED_VALIDATOR_GAP'||x.verdict==='VALIDATOR_READY_RUNTIME_FINDINGS')process.exitCode=12;}
module.exports={run,selftest,hostedEvidence};
