#!/usr/bin/env node
'use strict';
/* V42 evidence-only runner: authoritative loaded path plus bounded production APIs. */
const fs=require('fs'),path=require('path'),cp=require('child_process');
const ROOT=path.resolve(__dirname,'..'),H=require('../live_hybrid_session_v02'),A=require('../live_v06_scene_authority_browser'),E=require('../runtime/continuous_match_core.js'),P=require('../runtime/protagonist_match_controller.js');
const deep=x=>x==null?x:JSON.parse(JSON.stringify(x)),d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),row=(contractId,status,detail,evidence={})=>({contractId,status,detail,evidence}),B=()=>E.choiceActionBridge();
function scripts(){return[...fs.readFileSync(path.join(ROOT,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]);}
function boundary(seed){const s=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:1800});for(let i=0;i<10;i++){const r=H.advanceUntilBoundary(s,{maxActions:20000});if(r.boundary?.type==='PROTAGONIST_2D_WINDOW')return{session:s,boundary:r.boundary};if(!r.boundary)break;const q=r.state.spatial;H.resumeFromHighRes(s,{snapshot:{time:r.boundary.atSecond+.1,score:r.state.score,possession:r.state.possession,ball:{mode:'CONTROLLED',x:q.ball.x,y:q.ball.y,ownerId:r.state.ball.ownerId},players:q.players.map(p=>({...p,team:p.id.startsWith('H-')?'HOME':'AWAY'}))},actualEvents:[],hadChoice:false,futureOutcomePrecomputed:false});}throw Error(`NO_LIVE_BOUNDARY:${seed}`);}
function live(seed){const x=boundary(seed),opened=A.runToChoice(x.boundary,{seed:`${seed}|HR`,runtimeDir:path.join(ROOT,'runtime'),minPreSeconds:5,maxSearchSeconds:30});if(!opened.pending)throw Error('NO_LIVE_CHOICE');return{x,opened};}
function optionTarget(o){return o?.targetId&&['THROUGH_PASS','AVAILABLE_PASS','PROGRESSIVE_PASS','SWITCH_PASS'].includes(o.id);}
function compactLifecycle(p){return(p.candidateLifecycle||[]).filter(x=>['GENERATION_LEGALITY','LEAD_GEOMETRY','MEANINGFUL_TARGET','TARGET_VARIANT_SELECTION','VISIBLE_OPTION_SELECTION'].includes(x.stage)).map(x=>({stage:x.stage||null,candidateId:x.candidateId||null,targetId:x.targetId||null,included:x.included===true,reason:x.reason||null,geometry:x.geometry||null}));}
function liveChoiceEpisodes(){return['V42-SOL1-LIVE','V42-SOL1-LIVE-2','V42-SOL1-LIVE-3'].map(seed=>{try{const q=live(seed),p=q.opened.pending,options=p.options||[],pass=options.filter(optionTarget),feet=pass.filter(o=>o.id!=='THROUGH_PASS'),lead=pass.filter(o=>o.id==='THROUGH_PASS');return{seed,q,p,summary:{seed,boundary:q.x.boundary.sceneId,options:options.map(o=>({id:o.id,targetId:o.targetId||null,lead:o.id==='THROUGH_PASS'?{x:o.meta?.leadX??null,y:o.meta?.leadY??null}:null})),passTargets:[...new Set(pass.map(o=>o.targetId))],causallyAffordedPassTarget:pass.length>0,causallyAffordedDistinctLead:lead.some(o=>Number.isFinite(o.meta?.leadX)&&Number.isFinite(o.meta?.leadY)&&feet.some(f=>f.targetId===o.targetId)),candidateLifecycle:compactLifecycle(p)}};}catch(e){return{seed,error:e.message,summary:{seed,error:e.message}};}});}
function choose(p){return p.options.find(o=>o.targetId&&['THROUGH_PASS','AVAILABLE_PASS','PROGRESSIVE_PASS','SWITCH_PASS'].includes(o.id))||p.options.find(o=>o.targetId)||p.options[0];}
function place(m,id,x,y){const p=B().playerById(m,id);p.x=p.tx=x;p.y=p.ty=y;p.vx=p.vy=0;return p;}
function incoming(){const m=E.createMatch('V42-INCOMING'),h=m.players.find(p=>p.id==='H-ST');m.time=10;m.ball={mode:'FLIGHT',x:55,y:34,z:.35,vx:14,vy:0,vz:0,ownerId:null,intendedReceiverId:h.id,lastTouchTeam:'HOME',lastTouchPlayer:'H-CM',kind:'LONG_PASS',airborne:true};h.x=72;h.y=34;for(const p of m.players.filter(p=>p.team==='AWAY'))p.x=25;const n=(m.userChoiceLog||[]).length,f=E.choiceStateBridge().inspect(m,h.id);return{f,precommit:n!==(m.userChoiceLog||[]).length||m.userIncomingIntent!==undefined};}
function attack(){const b=B(),g=E.createMatch('V42-OPEN'),st=place(g,'H-ST',96,34);for(const p of g.players.filter(p=>p.team==='AWAY'&&p.role!=='GK'))place(g,p.id,70,8+(p.id.charCodeAt(2)%50));place(g,'A-GK',103,34);b.setControlled(g,st);st.controlledSince=g.time-.8;st.nextThink=g.time;const open=b.chooseOwnerAction(g,st);
 const x=E.createMatch('V42-BAD'),lw=place(x,'H-LW',92,7);for(const p of x.players.filter(p=>p.team==='AWAY'&&p.role!=='GK'))place(x,p.id,94+(p.id.charCodeAt(2)%3),9+(p.id.charCodeAt(2)%5));place(x,'A-GK',103,34);b.setControlled(x,lw);lw.controlledSince=x.time-.8;lw.nextThink=x.time;lw.bodyAngle=Math.atan2(34-lw.y,105-lw.x);const bad=b.chooseOwnerAction(x,lw);
 const t=E.createMatch('V42-TURN'),ts=place(t,'H-ST',96,34);b.setControlled(t,ts);ts.bodyAngle=Math.PI;const start=t.time,pend=b.executeShot(t,ts,'V42');const frames=[];for(let i=0;i<12&&t.ball.kind!=='SHOT';i++){E.step(t,.1);frames.push(E.snapshot(t));}
 const goal=E.createMatch('V42-GOAL'),sc=place(goal,'H-ST',100,34);b.setControlled(goal,sc);goal.ball={...goal.ball,mode:'FLIGHT',kind:'SHOT',shotTeam:'HOME',lastTouchTeam:'HOME',lastTouchPlayer:sc.id,shotTargetY:34,onTarget:true,x:104.9,y:34,vx:24,vy:0,vz:0,z:0};b.handleOut(goal,{side:'GOAL_RIGHT',x:105,y:34});const phases=[E.snapshot(goal).phase];for(let i=0;i<65;i++){E.step(goal,.1);phases.push(E.snapshot(goal).phase);}const ge=goal.events.find(e=>e.type==='GOAL'),n=P.__test.resultNarrative({m:goal,currentScene:{postFrames:[],checkpointInspect:{team:'HOME'}}},{choiceId:'AVAILABLE_PASS',targetId:'H-ST',newEvents:[{type:'PASS'},ge]});return{open,bad,pend,turnFrames:frames,turnEvents:t.events.filter(e=>e.t>=start),ge,phases,n};}
function corner(){const b=B(),m=E.createMatch('V42-CORNER-TEAM'),start=m.time;b.event(m,'CORNER','shot out');b.startDeadRestart(m,'CORNER','HOME',103.8,1.2,{side:'GOAL_RIGHT',x:105,y:4});for(let i=0;i<150&&!m.events.some(e=>e.type==='CORNER_KICK');i++)E.step(m,.1);const kick=m.events.find(e=>e.type==='CORNER_KICK');for(let i=0;i<6&&kick;i++)E.step(m,.1);const h=E.createMatch('V42-CORNER-HERO');b.startDeadRestart(h,'CORNER','HOME',103.8,1.2);const id=h.restart?.setup?.kickerId;h.protagonistControllerId=id;let choice=E.choiceStateBridge().restartChoiceState(h,id);for(let i=0;i<90&&!choice;i++){E.step(h,.1);choice=E.choiceStateBridge().restartChoiceState(h,id);}return{team:m.events.filter(e=>e.t>=start),kick,hero:h.events,id,choice};}
function anchor(){return['v42_choice_boundary_spatial_continuity.js','v42_sol2_choice_pipeline.js','v42_sol3_attack_goal_lifecycle.js','v42_sol4_1_defensive_responsibility.js','v42_sol4_2_defensive_movement.js','v42_sol1_4_consolidated_validation.js'].map(file=>{const r=cp.spawnSync(process.execPath,[path.join(ROOT,'QA',file)],{encoding:'utf8',timeout:30000});return{file,status:r.status===0?'PASS':'FAIL',classification:file.includes('consolidated')?'COMPACT_CONSOLIDATED_ANCHOR':'COMPACT_SOL_ANCHOR'};});}
function evaluate(){const s=scripts(),need=['runtime/tactical_movement.js','runtime/action_candidate_engine.js','runtime/continuous_match_core.js','runtime/protagonist_match_controller.js','live_hybrid_session_v02.js','live_v06_scene_authority_browser.js','in_pitch_choice_ui.js','step71_hybrid_v06_ui.js'],r=[row('V42-PATH-LOADED',need.every(f=>s.includes(f))?'PASS':'FAIL','index.html loads authoritative live chain',{scripts:need.map(f=>[f,s.indexOf(f)])})],samples=liveChoiceEpisodes(),q=samples.find(x=>x.q);if(!q){r.push(row('V42-LIVE-EPISODE','FAIL',samples.map(x=>x.summary)));return{results:r,anchors:anchor(),episodes:samples.map(x=>x.summary)};}const p=q.p,t=q.q.opened.state.choiceBoundarySpatial,A0=t.A,C=t.C||q.q.opened.E.snapshot(q.q.opened.state.m),sel=choose(p),before=(q.q.opened.state.m.userChoiceLog||[]).length,noCommit=before===0&&q.q.opened.state.m.events.every(e=>e.type!=='USER_CHOICE'),moves=[];const out=A.applyChoiceAndAdvance(q.q.opened,sel.id,sel.targetId||null,{maxPostSeconds:10,debugStepHook:({state})=>{const z=state.m.defensiveResponsibility||state.m.tactical?.defensiveResponsibility;if(z?.records)moves.push({at:state.m.time,responsibility:deep(z),players:Object.fromEntries(state.m.players.map(p=>[p.id,{tx:p.tx,ty:p.ty,intent:deep(p._defensivePursuitIntent)}]))});}}),B0=t.B,ids=x=>x.players.map(p=>p.id),cont=A0?.players?.length===22&&B0?.players?.length===22&&C?.players?.length===22&&JSON.stringify(ids(A0))===JSON.stringify(ids(B0))&&A0.players.every((v,i)=>d(v,B0.players[i])<.021)&&d(A0.ball,B0.ball)<.021,afforded=samples.filter(x=>x.summary.causallyAffordedPassTarget),leadAfforded=samples.filter(x=>x.summary.causallyAffordedDistinctLead),liveTarget=afforded[0],liveLead=leadAfforded[0];
 r.push(row('V42-L0-LIVE-STATE-CONTINUITY',cont?'PASS':'FAIL','actual low-res boundary reaches seedMatch A/B/C without rematerialization',{boundary:q.q.x.boundary.sceneId,APlayers:A0?.players?.length,BPlayers:B0?.players?.length,CPlayers:C?.players?.length,ballDelta:Number(d(A0.ball,B0.ball).toFixed(4)),materialization:t.materialization}));
 r.push(row('V42-L1-MEANINGFUL-TARGET-PRESERVATION',liveTarget?'PASS':'NOT_AFFORDED/WATCH',liveTarget?'bounded actual live sample proves an afforded pass target survives visibly':'no bounded actual live choice afforded a pass target; self-action-only options are not silent-loss evidence',{episodes:samples.map(x=>x.summary),affordedEpisode:liveTarget?.summary||null,previousClassification:liveTarget?null:'PREVIOUS_FALSE_FAIL'}));
 const leadOptions=liveLead?.p.options||[],lead=leadOptions.find(o=>optionTarget(o)&&o.id==='THROUGH_PASS'&&Number.isFinite(o.meta?.leadX)&&Number.isFinite(o.meta?.leadY)),feet=lead&&leadOptions.find(o=>optionTarget(o)&&o.id!=='THROUGH_PASS'&&o.targetId===lead.targetId),sol2Control=(anchor().find(x=>x.file==='v42_sol2_choice_pipeline.js')||{}).status;
 r.push(row('V42-L1-FEET-SPACE-DISTINCTION',liveLead?(feet?'PASS':'FAIL'):'NOT_AFFORDED/WATCH',liveLead?(feet?'actual afforded lead target retains separate reachable feet variant':'actual materially distinct reachable lead lacks feet variant'):'no bounded actual episode afforded a materially distinct reachable lead; existing Sol2 production candidate/controller fixture is the control',{episodes:samples.map(x=>x.summary),affordedEpisode:liveLead?.summary||null,feet:feet?{id:feet.id,targetId:feet.targetId}:null,lead:lead?{targetId:lead.targetId,x:lead.meta.leadX,y:lead.meta.leadY}:null,sol2ProductionCandidateControllerFixture:sol2Control,previousClassification:liveLead?null:'PREVIOUS_FALSE_FAIL'}));
 r.push(row('V42-L1-RECOMMENDATION-INERT',p.options.some(o=>o.recommended)&&noCommit?'PASS':'FAIL','recommendation remains annotation before any USER_CHOICE',{recommended:p.options.filter(o=>o.recommended).map(o=>[o.id,o.targetId||null]),userChoicesBefore:before}));
 const a=out.applyReceipt||{},e=out.committedEvent||{};r.push(row('V42-L0-CHOICE-AUTHORITY',a.ok&&a.choice===sel.id&&a.targetId===(sel.targetId||null)&&e.choiceId===sel.id&&e.targetId===(sel.targetId||null)?'PASS':'FAIL','exact choiceId + targetId survives apply and committed event',{selected:[sel.id,sel.targetId||null],receipt:[a.choice,a.targetId||null],event:[e.choiceId,e.targetId||null]}));
 r.push(row('V42-L0-PROTAGONIST-NO-PRECOMPUTE',p.futureOutcomePrecomputed===false&&a.futureOutcomePrecomputed!==true&&out.futureOutcomePrecomputed===false?'PASS':'FAIL','protagonist only acts after selection and no future outcome is stored',{pending:p.futureOutcomePrecomputed,receipt:a.futureOutcomePrecomputed,out:out.futureOutcomePrecomputed}));
 const bindings=[];for(const frame of moves)for(const [defenderId,record] of Object.entries(frame.responsibility.records||{})){if(!record.motion)continue;const player=frame.players[defenderId]||{},intent=player.intent||{},actual=record.motion.actualTarget||{},identity=intent.epoch===record.epoch&&intent.type===record.type&&(intent.targetId||null)===(record.targetId||null),finalTarget=Number.isFinite(actual.x)&&Number.isFinite(actual.y)&&actual.x===player.tx&&actual.y===player.ty;bindings.push({at:frame.at,defenderId,epoch:record.epoch,type:record.type,targetId:record.targetId||null,intent,actualTarget:actual,finalTx:player.tx,finalTy:player.ty,identity,finalTarget,mode:record.motion.mode,rewrite:record.motion.rewriteReason||null,emergency:!!frame.responsibility.motionEmergencyCompaction});}const pressCover=b=>{const press=b.find(x=>x.type==='PRESS'),cover=b.find(x=>x.type==='COVER');return!press||!cover||press.emergency||Math.hypot(press.actualTarget.x-cover.actualTarget.x,press.actualTarget.y-cover.actualTarget.y)>0.01;},byFrame=moves.map(frame=>bindings.filter(b=>b.at===frame.at));const bindingFails=bindings.filter(b=>!b.identity||!b.finalTarget),motionPass=bindings.length>0&&bindingFails.length===0&&byFrame.every(pressCover);r.push(row('V42-L1-RESPONSIBILITY-MOTION',motionPass?'PASS':'FAIL','outer responsibility identity binds current defender pursuit intent; motion actualTarget remains final tx/ty after tactical writers',{frames:moves.length,bindingCount:bindings.length,pressCoverDifferentiated:byFrame.every(pressCover),samples:bindings.filter((x,i)=>i<8),mismatches:bindingFails,previousClassification:'PREVIOUS_FALSE_FAIL',realFailureDisposition:bindingFails.length?'LIVE_BINDING_IMPLEMENTATION_REQUIRED_NEXT':null}));
 const inc=incoming();r.push(row('V42-L1-INCOMING-ONE-TOUCH-FLIGHT',inc.f?.kind==='INCOMING_BALL'&&inc.f.eta>0&&!inc.precommit?'PASS':'FAIL','loaded controller exposes choice during FLIGHT at positive ETA without precommit',{kind:inc.f?.kind||null,eta:inc.f?.eta||null,precommit:inc.precommit,futureOutcomePrecomputed:inc.f?.futureOutcomePrecomputed}));
 const k=attack(),cele=k.phases.indexOf('GOAL_CELEBRATION'),after=k.phases.findIndex((x,i)=>i>cele&&x!=='GOAL_CELEBRATION');r.push(row('V42-L1-OPEN-AI-GOAL-LIFECYCLE-NARRATIVE',k.open?.type==='SHOT'&&k.bad?.type!=='SHOT'&&k.pend?.pending&&k.turnFrames.filter(f=>f.players.find(x=>x.id==='H-ST')?.action==='TURNING_SHOT_PREP').length>=2&&k.turnEvents.some(x=>x.type==='SHOT_PREP')&&!!k.ge&&cele>=0&&after>cele&&k.n?.code==='GOAL'&&k.n?.terminalEvent?.type==='GOAL'?'PASS':'FAIL','open 1v1 vs bad-angle, turning prep, GOAL/score/celebration/aftermath/kickoff and truthful narrative',{open:k.open?.type||null,badAngle:k.bad?.type||null,turnEvents:k.turnEvents.map(x=>x.type),goal:!!k.ge,celebrationFrames:k.phases.filter(x=>x==='GOAL_CELEBRATION').length,aftermath:k.phases[after]||null,narrative:[k.n?.code,k.n?.terminalEvent?.type]}));
 const c=corner(),heroAuto=c.hero.some(x=>x.type==='CORNER_KICK');r.push(row('V42-L1-CORNER-HERO-EXPLICIT-TEAMMATE-AUTONOMOUS',!!c.kick&&c.team.some(x=>x.type==='CORNER')&&!!c.choice&&!heroAuto?'PASS':'FAIL','shot-out CORNER holds protagonist for explicit choice yet permits teammate autonomous CORNER_KICK continuation',{teamEvents:c.team.map(x=>x.type),teamKicker:c.kick?.actorId||null,heroKicker:c.id||null,heroCandidates:c.choice?.candidates?.length||0,heroAutoKick:heroAuto}));
 const loaded=Object.fromEntries([...need,'runtime/v39_open_play_responsibility_patch.js','final_match_v37_forced_harness_patch.js'].map(f=>[f,{loaded:s.includes(f),classification:s.includes(f)?'ACTUAL_USER_PATH':f.includes('v39')?'SHADOW_LEGACY_NOT_LOADED':'SHADOW_OR_HARNESS_NOT_LOADED'}]));return{results:r,episodes:samples.map(x=>x.summary),loadedPath:loaded,anchors:anchor(),futureOutcomePrecomputed:false};}
function run(){const x=evaluate(),hard=x.results.filter(z=>z.status==='FAIL'),af=(x.anchors||[]).filter(z=>z.status!=='PASS');return{module:'V42_SOL1_4_LIVE_E2E_VALIDATION',head:'593626e8d9d7086f89b98f102800ecabb35a2381+SOL4_FINAL_WRITER_FIX_WORKTREE',overall:hard.length||af.length?'FAIL':'PASS',hardFails:hard,contractResults:x.results,episodes:x.episodes||[],loadedPath:x.loadedPath||{},anchors:x.anchors||[],futureOutcomePrecomputed:false,classification:hard.length||af.length?'LIVE_BINDING_IMPLEMENTATION_REQUIRED_NEXT':'LIVE_E2E_BASELINE_READY_FOR_REPORTER_IDENTITY_STAGE'};}
if(require.main===module){const x=run();console.log(JSON.stringify(x,null,2));process.exitCode=x.overall==='PASS'?0:1;}module.exports={run,evaluate};
