#!/usr/bin/env node
'use strict';

/* V42 QA-only smoke: every observation comes from the production Hybrid/V0.6 imports. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {captureActualPath}=require('./v42_oracle_observation_adapter');
const {evaluate}=require('./v42_football_plausibility_oracle_runner');
const {capsule}=require('./v42_oracle_failure_capsule');

const ROOT=path.resolve(__dirname,'..');
const OUT=path.join(ROOT,'evidence/v42');
const EPISODES=[
  ...['01','02','03','04','05'].map(n=>({seed:`V42-UNSEEN-ST-${n}`,heroRole:'ST',heroPlayerId:'H-ST',requestedRole:'ST'})),
  ...['01','05','06','08','11'].map(n=>({seed:`V42-UNSEEN-WF-${n}`,heroRole:'WF',heroPlayerId:'H-LW',requestedRole:'wide attacker'})),
  ...['01','02','03','04','05'].slice(0,5).map(n=>({seed:`V42-UNSEEN-CM-${n}`,heroRole:'CM',heroPlayerId:'H-CM',requestedRole:'CM'})),
  ...['01','02','03','04','05'].map(n=>({seed:`V42-UNSEEN-CB-${n}`,heroRole:'CB',heroPlayerId:'H-LCB',requestedRole:'FB/CB',roleSubstitution:'FB unsupported by actual Hybrid protagonist selector; CB used in the FB/CB defensive bucket'}))
];
const d=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
const finite=n=>Number.isFinite(Number(n));
const nonGKs=f=>(f?.players||[]).filter(p=>p.role!=='GK');
function local(p){return p.team==='HOME'?{x:p.x,y:p.y}:{x:105-p.x,y:68-p.y};}
function frameMetrics(f){
  const ps=nonGKs(f), radii=[1,2.2,4,6], density={};
  for(const r of radii)density[`r${r}`]=Math.max(0,...ps.map(p=>ps.filter(q=>d(p,q)<=r).length));
  const teams={};
  for(const t of ['HOME','AWAY']){const q=ps.filter(p=>p.team===t).map(local),xs=q.map(p=>p.x),ys=q.map(p=>p.y);teams[t]={width:Number((Math.max(...ys)-Math.min(...ys)).toFixed(3)),depth:Number((Math.max(...xs)-Math.min(...xs)).toFixed(3))};}
  const roles={};
  for(const r of ['ST','WF','CM','FB','CB']){const q=ps.filter(p=>p.role===r).map(local);if(q.length)roles[r]={count:q.length,width:Number((Math.max(...q.map(p=>p.y))-Math.min(...q.map(p=>p.y))).toFixed(3)),depth:Number((Math.max(...q.map(p=>p.x))-Math.min(...q.map(p=>p.x))).toFixed(3))};}
  const carrier=f?.ball?.ownerId?f.players.find(p=>p.id===f.ball.ownerId):null;
  let converge=0,vectorConverge=0,uncovered=0,duplicateOwnership=0;
  if(carrier){for(const p of ps.filter(x=>x.team!==carrier.team)){if(d(p,carrier)<10)converge++;const v={x:(carrier.x-p.x),y:(carrier.y-p.y)},vl=Math.hypot(v.x,v.y),sl=Math.hypot(p.vx||0,p.vy||0);if(vl&&sl&&((p.vx*v.x+p.vy*v.y)/(vl*sl))>.7)vectorConverge++;}}
  for(const t of ['HOME','AWAY']){const threats=ps.filter(p=>p.team===t&&['ST','WF'].includes(p.role)&&local(p).x>55);for(const x of threats){const owners=ps.filter(p=>p.team!==t&&((p.markTargetId===x.id)||d(p,x)<15));if(!owners.length)uncovered++;if(owners.length>1)duplicateOwnership++;}}
  return{time:f?.time,phase:f?.phase,openPlay:!/(CORNER|RESTART|GOAL|SET)/.test(f?.phase||''),density,teams,roles,carrierConvergence:converge,teamVectorConvergence:vectorConverge,uncoveredMaterialThreats:uncovered,duplicateThreatOwnership:duplicateOwnership};
}
function aggregateMetrics(observation){
  const rows=(observation.frames||[]).map(frameMetrics), max=(key)=>Math.max(0,...rows.map(x=>typeof x[key]==='number'?x[key]:0));
  const roleExtremes={};for(const r of ['ST','WF','CM','FB','CB']){const q=rows.map(x=>x.roles[r]).filter(Boolean);if(q.length)roleExtremes[r]={maxWidth:Math.max(...q.map(x=>x.width)),minWidth:Math.min(...q.map(x=>x.width)),maxDepth:Math.max(...q.map(x=>x.depth)),minDepth:Math.min(...q.map(x=>x.depth))};}
  const displacements=[];let synchronousMax=0;for(let i=1;i<(observation.frames||[]).length;i++){const a=observation.frames[i-1],b=observation.frames[i],moves=(b.players||[]).map(p=>{const q=(a.players||[]).find(x=>x.id===p.id);return q?{id:p.id,dist:Number(d(p,q).toFixed(3))}:null}).filter(Boolean);displacements.push(...moves.map(x=>x.dist));synchronousMax=Math.max(synchronousMax,moves.filter(x=>x.dist>3).length);}
  const boundary=observation.boundary?.lowRes,first=observation.firstVisibleChoiceFrame;const deltas=boundary&&first?(first.players||[]).map(p=>{const q=(boundary.players||[]).find(x=>x.id===p.id);return q?Number(d(p,q).toFixed(3)):null}).filter(finite):[];
  const densityMax={};for(const r of ['r1','r2.2','r4','r6'])densityMax[r]=Math.max(0,...rows.map(x=>x.density[r]||0));
  return{frames:rows.length,maxLocalDensity:densityMax,maxCarrierConvergence:max('carrierConvergence'),maxTeamVectorConvergence:max('teamVectorConvergence'),maxUncoveredMaterialThreats:max('uncoveredMaterialThreats'),maxDuplicateThreatOwnership:max('duplicateThreatOwnership'),maxSuddenDisplacement:displacements.length?Math.max(...displacements):0,maxSynchronousRelocation:synchronousMax,roleExtremes,boundaryGeometry:{maxPlayerDelta:deltas.length?Math.max(...deltas):null,meanPlayerDelta:deltas.length?Number((deltas.reduce((a,b)=>a+b,0)/deltas.length).toFixed(3)):null}};
}
function sha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function main(){
  if(EPISODES.length!==20||new Set(EPISODES.map(x=>`${x.seed}|${x.heroRole}`)).size!==20)throw Error('EPISODE_MATRIX_NOT_UNIQUE_20');
  const episodes=[],allCapsules=[];
  for(const spec of EPISODES){
    let observation,error=null;try{observation=captureActualPath({...spec,durationSeconds:1800});}catch(e){error={name:e.name,message:e.message};observation={seed:spec.seed,sessionId:null,frames:[],current:null,missing:['CAPTURE_ERROR']};}
    const oracle=evaluate(observation);const metrics=aggregateMetrics(observation);const results=oracle.results;
    for(const result of results)if(result.status!=='PASS')allCapsules.push({...capsule(observation,result),smokeMetrics:metrics});
    episodes.push({episodeId:`E${String(episodes.length+1).padStart(2,'0')}`,seed:spec.seed,heroRole:spec.heroRole,requestedRole:spec.requestedRole,heroPlayerId:spec.heroPlayerId,roleSubstitution:spec.roleSubstitution||null,boundaryReached:!!observation.boundary,captureError:error,missing:observation.missing||[],boundaryTime:observation.boundary?.time??null,phase:observation.phase||null,frameCount:observation.frames?.length||0,choiceCount:observation.choices?.length||0,metrics,verdicts:results.map(x=>({contractId:x.contractId,status:x.status,detail:x.detail,candidateBlocking:x.candidateBlocking}))});
  }
  fs.mkdirSync(path.join(OUT,'failures'),{recursive:true});for(const f of allCapsules)fs.writeFileSync(path.join(OUT,'failures',`${f.seed||'unknown'}__${f.detectorId}.json`),JSON.stringify(f,null,2)+'\n');
  const statuses=['HARD_FAIL','FAIL','WATCH','BLOCKED'];const byContract={},byStatus=Object.fromEntries(statuses.map(x=>[x,0]));for(const ep of episodes)for(const r of ep.verdicts){if(r.status==='PASS')continue;byStatus[r.status]=(byStatus[r.status]||0)+1;byContract[r.contractId]??={status:r.status,occurrences:0,episodes:[]};byContract[r.contractId].occurrences++;byContract[r.contractId].episodes.push(ep.episodeId);}
  for(const x of Object.values(byContract))x.episodes=[...new Set(x.episodes)];
  const hard=Object.fromEntries(Object.entries(byContract).filter(([,x])=>x.status==='HARD_FAIL')),fail=Object.fromEntries(Object.entries(byContract).filter(([,x])=>x.status==='FAIL'));
  const out={schemaVersion:'V42_ORACLE_MULTI_SEED_SMOKE_1.0',result:(Object.keys(hard).length||Object.keys(fail).length)?'V42_ORACLE_SMOKE_FOUND_BLOCKING_FAILURES':'V42_ORACLE_SMOKE_NO_BLOCKING_FAILURES_BROWSER_STILL_REQUIRED',generatedAt:new Date().toISOString(),source:{head:'0fd6a46f3bb4899f5de623ba4980c8bf357dfdf2',oracleRunnerSha256:sha(path.join(__dirname,'v42_football_plausibility_oracle_runner.js')),adapterSha256:sha(path.join(__dirname,'v42_oracle_observation_adapter.js'))},truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',deploymentPerformed:false,userPass:false,browserOracle:'OPEN/BLOCKED_MANAGED_WORKER_CHROMIUM'},matrix:{requestedEpisodes:20,completedEpisodes:episodes.length,uniqueCombinations:new Set(EPISODES.map(x=>`${x.seed}|${x.heroRole}`)).size,roleCounts:EPISODES.reduce((a,x)=>(a[x.heroRole]=(a[x.heroRole]||0)+1,a),{}),substitutions:['FB role had no protagonist boundary in deterministic production Hybrid selector; five CB episodes cover the supported FB/CB bucket.']},aggregate:{hardFailByContract:hard,hardFailTotal:Object.values(hard).reduce((n,x)=>n+x.occurrences,0),hardFailAffectedEpisodes:[...new Set(Object.values(hard).flatMap(x=>x.episodes))],failByContract:fail,failTotal:Object.values(fail).reduce((n,x)=>n+x.occurrences,0),failAffectedEpisodes:[...new Set(Object.values(fail).flatMap(x=>x.episodes))],watchCount:byStatus.WATCH||0,blockedCount:byStatus.BLOCKED||0,blockedAffectedEpisodes:[...new Set(Object.values(byContract).filter(x=>x.status==='BLOCKED').flatMap(x=>x.episodes))],nonPassVerdictCount:Object.values(byStatus).reduce((a,b)=>a+b,0),cleanEpisodeCount:episodes.filter(e=>e.verdicts.every(x=>!['HARD_FAIL','FAIL'].includes(x.status))).length,affectedEpisodesByContract:byContract},episodes,capsules:allCapsules.map(x=>({seed:x.seed,sessionId:x.sessionId,detectorId:x.detectorId,severity:x.severity,path:`failures/${x.seed}__${x.detectorId}.json`})),rootCauseClusters:cluster(episodes),topOutlierCapsules:topOutliers(episodes)};
  fs.writeFileSync(path.join(OUT,'V42_ORACLE_MULTI_SEED_SMOKE.json'),JSON.stringify(out,null,2)+'\n');
  const md=renderMarkdown(out);fs.writeFileSync(path.join(OUT,'V42_ORACLE_MULTI_SEED_SMOKE.md'),md);
  console.log(JSON.stringify({episodes:episodes.length,clean:out.aggregate.cleanEpisodeCount,hardFail:Object.keys(out.aggregate.hardFailByContract),fail:Object.keys(out.aggregate.failByContract),watch:out.aggregate.watchCount,blocked:out.aggregate.blockedCount,capsules:allCapsules.length},null,2));
}
function cluster(episodes){const groups={};for(const e of episodes)for(const r of e.verdicts.filter(x=>['HARD_FAIL','FAIL'].includes(x.status))){const owner=r.contractId==='CON-005'?'handoff/first-V0.6 boundary':r.contractId==='RSP-002'?'handoff/first-V0.6 boundary or later movement/final tx/ty writer (unresolved)':r.contractId==='DCA-003'?'tactical responsibility':'later movement/final tx/ty writer';groups[owner]??={likelyOwner:owner,confidence:'LOW',contracts:[],episodes:[]};groups[owner].contracts.push(r.contractId);groups[owner].episodes.push(e.episodeId);}return Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,{likelyOwner:v.likelyOwner,confidence:v.confidence,evidence:'Repeated independent contract symptoms only; no root cause claimed from a single episode.',contracts:[...new Set(v.contracts)],episodes:[...new Set(v.episodes)]}]));}
function topOutliers(episodes){const out=[];for(const e of episodes){const m=e.metrics;out.push({value:m.maxLocalDensity?.['r2.2']||0,seed:e.seed,episodeId:e.episodeId,metric:'max local density r2.2',phase:e.phase,time:e.boundaryTime});out.push({value:m.maxSuddenDisplacement,seed:e.seed,episodeId:e.episodeId,metric:'max sudden displacement',phase:e.phase,time:e.boundaryTime});out.push({value:m.maxCarrierConvergence,seed:e.seed,episodeId:e.episodeId,metric:'carrier convergence',phase:e.phase,time:e.boundaryTime});out.push({value:m.maxUncoveredMaterialThreats,seed:e.seed,episodeId:e.episodeId,metric:'uncovered material threats',phase:e.phase,time:e.boundaryTime});}return out.sort((a,b)=>b.value-a.value).slice(0,10);}
function renderMarkdown(o){const a=o.aggregate;const lines=['# V42 Oracle Multi-Seed Actual Hybrid Smoke','','Result: `'+(a.failTotal||a.hardFailTotal?'V42_ORACLE_SMOKE_FOUND_BLOCKING_FAILURES':'V42_ORACLE_SMOKE_NO_BLOCKING_FAILURES_BROWSER_STILL_REQUIRED')+'`','','This is 20 unique production-imported Hybrid → protagonist-boundary → V0.6 observations. No browser, deployment, user-PASS, or gameplay repair was performed. FB was substituted by supported CB in the FB/CB bucket.','',`Aggregate: ${a.cleanEpisodeCount}/20 football-contract-clean episodes; HARD_FAIL ${a.hardFailTotal} (${a.hardFailAffectedEpisodes.length} episodes); FAIL ${a.failTotal} (${a.failAffectedEpisodes.length} episodes); WATCH ${a.watchCount}; BLOCKED ${a.blockedCount} (${a.blockedAffectedEpisodes.length} episodes).`,'','## Contract counts','', '| Contract | Status | Occurrences | Affected episodes |','|---|---:|---:|---:|'];for(const [id,x] of Object.entries(a.affectedEpisodesByContract))lines.push(`| ${id} | ${x.status} | ${x.occurrences} | ${x.episodes.length} |`);lines.push('','## Earliest blocking boundary / episode seeds','');for(const e of o.episodes.filter(e=>e.verdicts.some(x=>['HARD_FAIL','FAIL'].includes(x.status))))lines.push(`- ${e.episodeId}: ${e.seed} (${e.heroRole}), earliest observed protagonist boundary ${e.boundaryTime??'unreached'}s; blocking contracts: ${e.verdicts.filter(x=>['HARD_FAIL','FAIL'].includes(x.status)).map(x=>x.contractId).join(', ')}`);lines.push('','## Root-cause preparation','');for(const [k,v] of Object.entries(o.rootCauseClusters))lines.push(`- ${k}: confidence ${v.confidence}; contracts ${v.contracts.join(', ')}; episodes ${v.episodes.join(', ')}. ${v.evidence}`);lines.push('','## Top 10 outlier capsules (raw metrics; below-threshold values retained)','', '| Rank | Episode seed | Metric | Value | Phase/time |','|---:|---|---|---:|---|');for(const [i,x] of o.topOutlierCapsules.entries())lines.push(`| ${i+1} | ${x.seed} | ${x.metric} | ${x.value} | ${x.phase||'-'} / ${x.time??'-'}s |`);lines.push('','Compact capsule files for every non-PASS verdict are listed in the JSON. Raw per-episode role spreads, team width/depth, pair density, convergence, displacement, synchronous relocation, and boundary A/B deltas are also in the JSON. Thresholds were not retuned.','', '## Browser-only contracts','', 'CHO-009, SES-010, DEP-012 and AUT-006 remain BLOCKED where exact browser/user commit evidence is unavailable; this smoke does not convert missing evidence into PASS.');return lines.join('\n')+'\n';}
if(require.main===module)main();
module.exports={EPISODES,frameMetrics,aggregateMetrics,main};
