#!/usr/bin/env node
'use strict';

/* QA-only exploration.  The adapter is the real production Hybrid -> V0.6 path;
 * this file does not mutate runtime state or production gameplay. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {captureActualPath}=require('./v42_oracle_observation_adapter');
const {evaluate}=require('./v42_football_plausibility_oracle_runner');
const {capsule}=require('./v42_oracle_failure_capsule');
const {adjudicate}=require('./v42_oracle_watch_adjudication');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v42');
const roles=[
  ['ST','H-ST','ST'],['WF','H-LW','wide attacker'],['CM','H-CM','CM'],['CB','H-LCB','FB/CB']
];
const ROLE_COUNTS={ST:13,WF:13,CM:12,CB:12};
const ROLE_SEEDS={
  ST:Array.from({length:13},(_,i)=>`V42-ORACLE-50-ST-${String(i+1).padStart(2,'0')}`),
  WF:['05','10','11','15','16','18','19','20','26','27','32','33','36'].map(n=>`V42-ORACLE-50B-WF-${n}`),
  CM:Array.from({length:12},(_,i)=>`V42-ORACLE-50-CM-${String(i+1).padStart(2,'0')}`),
  CB:['02','03','04','05','07','08','09','10','11','12','13','14'].map(n=>`V42-ORACLE-50B-CB-${n}`)
};
const EPISODES=roles.flatMap(([heroRole,heroPlayerId,requestedRole])=>ROLE_SEEDS[heroRole].map(seed=>({
  seed,heroRole,heroPlayerId,requestedRole,
  roleSubstitution:heroRole==='CB'?'FB has no natural protagonist boundary in the production Hybrid selector; supported CB covers the FB/CB defensive bucket.':null
})));
const d=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
const finite=x=>Number.isFinite(Number(x));
const nonGKs=f=>(f?.players||[]).filter(p=>p.role!=='GK');
function local(p){return p.team==='HOME'?{x:Number(p.x),y:Number(p.y)}:{x:105-Number(p.x),y:68-Number(p.y)};}
function frameMetrics(f){
  const ps=nonGKs(f),density={};
  for(const r of [1,2.2,4,6]) density[`r${r}`]=Math.max(0,...ps.map(p=>ps.filter(q=>d(p,q)<=r).length));
  const teams={},roles={};
  for(const t of ['HOME','AWAY']){const q=ps.filter(p=>p.team===t).map(local),xs=q.map(p=>p.x),ys=q.map(p=>p.y);teams[t]={width:+(Math.max(...ys)-Math.min(...ys)).toFixed(3),depth:+(Math.max(...xs)-Math.min(...xs)).toFixed(3)};}
  for(const r of ['ST','WF','CM','FB','CB']){const q=ps.filter(p=>p.role===r).map(local);if(q.length)roles[r]={count:q.length,width:+(Math.max(...q.map(p=>p.y))-Math.min(...q.map(p=>p.y))).toFixed(3),depth:+(Math.max(...q.map(p=>p.x))-Math.min(...q.map(p=>p.x))).toFixed(3)};}
  const carrier=f?.ball?.ownerId?f.players.find(p=>p.id===f.ball.ownerId):null;let convergence=0,vector=0;
  if(carrier)for(const p of ps.filter(x=>x.team!==carrier.team)){if(d(p,carrier)<10)convergence++;const v={x:carrier.x-p.x,y:carrier.y-p.y},vl=Math.hypot(v.x,v.y),sl=Math.hypot(p.vx||0,p.vy||0);if(vl&&sl&&(p.vx*v.x+p.vy*v.y)/(vl*sl)>.7)vector++;}
  let uncovered=0,duplicate=0;for(const t of ['HOME','AWAY'])for(const threat of ps.filter(p=>p.team===t&&['ST','WF'].includes(p.role)&&local(p).x>55)){const owners=ps.filter(p=>p.team!==t&&(p.markTargetId===threat.id||d(p,threat)<15));if(!owners.length)uncovered++;if(owners.length>1)duplicate++;}
  return{time:f?.time,phase:f?.phase,openPlay:!/(CORNER|RESTART|GOAL|SET)/.test(f?.phase||''),density,teams,roles,carrierConvergence:convergence,teamVectorConvergence:vector,uncoveredMaterialThreats:uncovered,duplicateThreatOwnership:duplicate};
}
function aggregate(o){
  const rows=(o.frames||[]).map(frameMetrics),max=k=>Math.max(0,...rows.map(x=>typeof x[k]==='number'?x[k]:0));
  const roleExtremes={};for(const r of ['ST','WF','CM','FB','CB']){const q=rows.map(x=>x.roles[r]).filter(Boolean);if(q.length)roleExtremes[r]={maxWidth:Math.max(...q.map(x=>x.width)),minWidth:Math.min(...q.map(x=>x.width)),maxDepth:Math.max(...q.map(x=>x.depth)),minDepth:Math.min(...q.map(x=>x.depth))};}
  const moves=[];let synchronous=0,oscillation=0;for(let i=1;i<(o.frames||[]).length;i++){const a=o.frames[i-1],b=o.frames[i],m=(b.players||[]).map(p=>{const q=(a.players||[]).find(x=>x.id===p.id);return q?{id:p.id,dist:+d(p,q).toFixed(3)}:null}).filter(Boolean);moves.push(...m);synchronous=Math.max(synchronous,m.filter(x=>x.dist>3).length);}
  for(const p of o.current?.players||[]){const ts=(o.frames||[]).map(f=>(f.players||[]).find(x=>x.id===p.id)).filter(Boolean);for(let i=2;i<ts.length;i++)if(ts[i].epoch===ts[i-1].epoch&&ts[i].epoch===ts[i-2].epoch&&d(ts[i],ts[i-2])<.1&&d(ts[i],ts[i-1])>3)oscillation++;}
  const a=o.boundary?.lowRes,b=o.firstVisibleChoiceFrame,deltas=a&&b?(b.players||[]).map(p=>{const q=(a.players||[]).find(x=>x.id===p.id);return q? +d(p,q).toFixed(3):null}).filter(finite):[];
  return{frameCount:rows.length,perFrame:rows,maxLocalDensity:Object.fromEntries([1,2.2,4,6].map(r=>[`r${r}`,Math.max(0,...rows.map(x=>x.density[`r${r}`]||0))])),maxCarrierConvergence:max('carrierConvergence'),maxTeamVectorConvergence:max('teamVectorConvergence'),maxUncoveredMaterialThreats:max('uncoveredMaterialThreats'),maxDuplicateThreatOwnership:max('duplicateThreatOwnership'),maxSuddenDisplacement:moves.length?Math.max(...moves.map(x=>x.dist)):0,maxSynchronousRelocation:synchronous,oscillationCount:oscillation,roleExtremes,boundaryABDelta:{max:deltas.length?Math.max(...deltas):null,mean:deltas.length? +(deltas.reduce((x,y)=>x+y,0)/deltas.length).toFixed(3):null}};
}
function nearWatch(m){const hits=[];if(m.maxLocalDensity?.['r2.2']>=4)hits.push('local-density');if(m.maxCarrierConvergence>=3)hits.push('carrier-convergence');if(m.maxTeamVectorConvergence>=3)hits.push('team-vector-convergence');if(m.maxUncoveredMaterialThreats>=1)hits.push('uncovered-threat');if(m.maxDuplicateThreatOwnership>=1)hits.push('duplicate-ownership');if(m.maxSuddenDisplacement>=8)hits.push('sudden-displacement');if(m.maxSynchronousRelocation>=2)hits.push('synchronous-relocation');return hits.length>=2?{status:'WATCH',detail:'near-threshold multi-metric outlier; no oracle threshold retuned',metrics:hits}:null;}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');}
function dist(values){const v=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!v.length)return null;const q=p=>v[Math.min(v.length-1,Math.floor((v.length-1)*p))];return{n:v.length,min:v[0],p50:q(.5),p95:q(.95),max:v[v.length-1],mean:+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(3)};}
function main(){
  if(EPISODES.length!==50||new Set(EPISODES.map(x=>`${x.seed}|${x.heroRole}`)).size!==50)throw Error('EPISODE_MATRIX_NOT_UNIQUE_50');
  const episodes=[],capsules=[];
  for(const spec of EPISODES){let o,error=null;try{o=captureActualPath({...spec,durationSeconds:1800});}catch(e){error={name:e.name,message:e.message};o={seed:spec.seed,sessionId:null,frames:[],current:null,missing:['CAPTURE_ERROR']};}
    const oracle=evaluate(o),metrics=aggregate(o),adjudication=adjudicate(o),watch=adjudication.watch;if(watch)capsules.push({...capsule(o,{contractId:'EXPLORATION-WATCH',status:'WATCH',evidence:watch}),explorationMetrics:metrics,watchAdjudication:adjudication});
    for(const r of oracle.results)if(r.status!=='PASS')capsules.push({...capsule(o,r),explorationMetrics:metrics});
    episodes.push({episodeId:`E${String(episodes.length+1).padStart(2,'0')}`,seed:spec.seed,heroRole:spec.heroRole,requestedRole:spec.requestedRole,heroPlayerId:spec.heroPlayerId,roleSubstitution:spec.roleSubstitution,boundaryReached:!!o.boundary,boundaryTime:o.boundary?.time??null,phase:o.phase||o.current?.phase||null,time:o.current?.time??null,frameCount:o.frames?.length||0,lowResPreBoundaryFrameCount:o.lowResPreFrames?.length||0,shortTemporalWindow:(o.frames||[]).map(f=>f.time).slice(0,12),missing:o.missing||[],captureError:error,metrics,watch,watchAdjudication:adjudication,verdicts:oracle.results.map(x=>({contractId:x.contractId,status:x.status,detail:x.detail,candidateBlocking:x.candidateBlocking}))});
  }
  fs.mkdirSync(path.join(OUT,'failures'),{recursive:true});for(const c of capsules){const safe=`${c.seed}__${c.detectorId}`;fs.writeFileSync(path.join(OUT,'failures',`${safe}.json`),JSON.stringify(c,null,2)+'\n');}
  const allResults=episodes.flatMap(e=>e.verdicts),statuses=['HARD_FAIL','FAIL','WATCH','BLOCKED'],byContract={},byStatus=Object.fromEntries(statuses.map(s=>[s,0]));for(const x of allResults)if(x.status!=='PASS'){byStatus[x.status]=(byStatus[x.status]||0)+1;byContract[x.contractId]??={status:x.status,occurrences:0,episodes:[]};byContract[x.contractId].occurrences++;byContract[x.contractId].episodes.push(episodes.find(e=>e.verdicts.includes(x))?.episodeId);}
  for(const x of Object.values(byContract))x.episodes=[...new Set(x.episodes.filter(Boolean))];
  const blocking=allResults.filter(x=>['HARD_FAIL','FAIL'].includes(x.status));const watches=episodes.flatMap(e=>e.watch?[{episodeId:e.episodeId,seed:e.seed,status:'WATCH',detail:e.watch.detail,metrics:e.watch.metrics}]:[]);byStatus.WATCH=watches.length;if(watches.length)byContract['EXPLORATION-WATCH']={status:'WATCH',occurrences:watches.length,episodes:watches.map(x=>x.episodeId)};
  const values=k=>episodes.map(e=>e.metrics[k]).filter(finite),prior=JSON.parse(fs.readFileSync(path.join(OUT,'V42_ORACLE_MULTI_SEED_SMOKE.json'),'utf8'));
  const priorMetrics=prior.episodes.map(e=>e.metrics||{}),metricKeys=['maxCarrierConvergence','maxTeamVectorConvergence','maxUncoveredMaterialThreats','maxDuplicateThreatOwnership','maxSuddenDisplacement','maxSynchronousRelocation'];
  const comparison=Object.fromEntries(metricKeys.map(k=>[k,{current:dist(values(k)),prior20:dist(priorMetrics.map(x=>x[k]).filter(finite))}]));
  const outlierRows=[];for(const e of episodes){const m=e.metrics;const add=(metric,value)=>outlierRows.push({episodeId:e.episodeId,seed:e.seed,heroRole:e.heroRole,phase:e.phase,time:e.time,boundaryTime:e.boundaryTime,metric,value,clean:e.verdicts.every(x=>!['HARD_FAIL','FAIL'].includes(x.status))});add('local density r2.2',m.maxLocalDensity?.['r2.2']);add('local density r6',m.maxLocalDensity?.['r6']);add('team width min',Math.min(...e.metrics.perFrame.map(x=>Math.min(x.teams.HOME?.width??Infinity,x.teams.AWAY?.width??Infinity))));add('team depth min',Math.min(...e.metrics.perFrame.map(x=>Math.min(x.teams.HOME?.depth??Infinity,x.teams.AWAY?.depth??Infinity))));add('carrier convergence',m.maxCarrierConvergence);add('team-vector convergence',m.maxTeamVectorConvergence);add('uncovered material threats',m.maxUncoveredMaterialThreats);add('duplicate threat ownership',m.maxDuplicateThreatOwnership);add('sudden displacement',m.maxSuddenDisplacement);add('synchronous relocation',m.maxSynchronousRelocation);add('role depth extreme',Math.max(...Object.values(m.roleExtremes).flatMap(x=>[x.maxDepth,-x.minDepth]),0));add('role width extreme',Math.max(...Object.values(m.roleExtremes).flatMap(x=>[x.maxWidth,-x.minWidth]),0));add('boundary A/B max delta',m.boundaryABDelta.max??0);}
  outlierRows.sort((a,b)=>(b.value??-Infinity)-(a.value??-Infinity));
  const hardFail=allResults.filter(x=>x.status==='HARD_FAIL'),fail=allResults.filter(x=>x.status==='FAIL');
  const disposition=blocking.length?'V42_ORACLE_50_FOUND_BLOCKING_FAILURES':watches.length?'V42_ORACLE_50_ONLY_WATCH_OUTLIERS':'V42_ORACLE_50_CLEAN_BROWSER_STILL_REQUIRED';
  const result={schemaVersion:'V42_ORACLE_50_EPISODE_EXPLORATION_1.0',disposition,generatedAt:new Date().toISOString(),source:{head:'598ce3a208c99144412f71c6382d900c26d54f47',runnerSha256:sha(path.join(__dirname,'v42_football_plausibility_oracle_runner.js')),adapterSha256:sha(path.join(__dirname,'v42_oracle_observation_adapter.js')),watchAdjudicatorSha256:sha(path.join(__dirname,'v42_oracle_watch_adjudication.js'))},truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',deploymentPerformed:false,userPass:false,browserOracle:'OPEN/BLOCKED_MANAGED_WORKER_CHROMIUM',productionGameplayChanged:false},matrix:{requestedEpisodes:50,completedEpisodes:episodes.length,uniqueSeedRoleCombinations:new Set(EPISODES.map(x=>`${x.seed}|${x.heroRole}`)).size,roleCounts:Object.fromEntries(roles.map(([r])=>[r,EPISODES.filter(x=>x.heroRole===r).length])),fbRole:'unsupported by natural protagonist boundary; CB covers supported FB/CB bucket',newSeedNamespace:'V42-ORACLE-50-*',excludedPriorNamespace:'V42-UNSEEN-*'},aggregate:{byStatus:byStatus,byContract,hardFail:{count:hardFail.length,episodes:[...new Set(hardFail.map(x=>episodes.find(e=>e.verdicts.includes(x))?.episodeId).filter(Boolean))]},fail:{count:fail.length,episodes:[...new Set(fail.map(x=>episodes.find(e=>e.verdicts.includes(x))?.episodeId).filter(Boolean))]},watch:{count:watches.length,episodes:watches.map(x=>x.episodeId)},blocked:{count:byStatus.BLOCKED,episodes:[...new Set(Object.values(byContract).filter(x=>x.status==='BLOCKED').flatMap(x=>x.episodes))]},cleanEpisodeCount:episodes.filter(e=>e.verdicts.every(x=>!['HARD_FAIL','FAIL'].includes(x.status))).length,blockingGroups:byContract,metricDistributionComparison:comparison},episodes,capsules:capsules.map(c=>({seed:c.seed,sessionId:c.sessionId,detectorId:c.detectorId,severity:c.severity,path:`failures/${c.seed}__${c.detectorId}.json`})),top20Outliers:outlierRows.slice(0,20),nearThresholdMultiMetricEpisodes:watches,rootCauseClusters:rootCause(episodes,watches),prior20Source:{file:'V42_ORACLE_MULTI_SEED_SMOKE.json',head:prior.source?.head||null}};
  fs.writeFileSync(path.join(OUT,'V42_ORACLE_50_EPISODE_EXPLORATION.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(OUT,'V42_ORACLE_50_EPISODE_EXPLORATION.md'),markdown(result));console.log(JSON.stringify({disposition,episodes:episodes.length,clean:result.aggregate.cleanEpisodeCount,hardFail:hardFail.length,fail:fail.length,watch:watches.length,blocked:byStatus.BLOCKED,capsules:capsules.length},null,2));return result;
}
function rootCause(es,watches=[]){const groups={};for(const e of es)for(const r of e.verdicts.filter(x=>['HARD_FAIL','FAIL'].includes(x.status))){const key=['SPI-001','DCA-003','MOT-004','RSP-002'].includes(r.contractId)?'observable geometry/tactical continuity':r.contractId==='CON-005'?'boundary continuity': 'event/authority/lifecycle';groups[key]??={confidence:'LOW',contracts:[],episodes:[],reason:'Repeated contract symptoms only; no production root cause inferred from exploration.'};groups[key].contracts.push(r.contractId);groups[key].episodes.push(e.episodeId);}if(watches.length)groups['WATCH recurring vector convergence plus duplicate ownership']={confidence:'MEDIUM',contracts:['EXPLORATION-WATCH'],episodes:watches.map(x=>x.episodeId),reason:'Raw distributions show team-vector convergence and duplicate threat ownership recurring together; this is an oracle-sensitivity/tactical-model adjudication lead, not a gameplay diagnosis.'};return Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,{...v,contracts:[...new Set(v.contracts)],episodes:[...new Set(v.episodes)]}]));}
function markdown(o){const a=o.aggregate,l=['# V42 50-episode unseen football plausibility exploration','',`Disposition: \`${o.disposition}\``, '',`Exactly ${o.matrix.completedEpisodes} new deterministic production Hybrid → protagonist-boundary → V0.6 episodes were captured (${Object.entries(o.matrix.roleCounts).map(([k,v])=>`${k} ${v}`).join(', ')}). No gameplay, browser, deployment, user-PASS, or STEP79 work was performed.`, '',`Clean episodes: ${a.cleanEpisodeCount}/50. HARD_FAIL ${a.hardFail.count}; FAIL ${a.fail.count}; WATCH ${a.watch.count}; BLOCKED ${a.blocked.count}.`,'','## Contract counts','','| Contract | Status | Occurrences | Affected episodes |','|---|---|---:|---:|'];for(const [k,v] of Object.entries(a.byContract))l.push(`| ${k} | ${v.status} | ${v.occurrences} | ${v.episodes.join(', ')||'-'} |`);l.push('','## Blocking/WATCH episode coordinates','');for(const e of o.episodes.filter(e=>e.verdicts.some(x=>['HARD_FAIL','FAIL'].includes(x.status))||e.watch))l.push(`- ${e.episodeId}: ${e.seed} / ${e.heroRole} / ${e.phase||'-'} / ${e.time??e.boundaryTime??'-'}s — ${[...e.verdicts.filter(x=>['HARD_FAIL','FAIL'].includes(x.status)).map(x=>x.contractId),...(e.watch?['WATCH']:[])].join(', ')}`);l.push('','## Top 20 outliers (raw, including clean episodes)','', '| Rank | Episode | Role | Metric | Value | Phase/time | Clean |','|---:|---|---|---|---:|---|---|');o.top20Outliers.forEach((x,i)=>l.push(`| ${i+1} | ${x.seed} | ${x.heroRole} | ${x.metric} | ${x.value} | ${x.phase||'-'} / ${x.time??'-'}s | ${x.clean?'yes':'no'} |`));l.push('','## Root-cause clusters','');for(const [k,v] of Object.entries(o.rootCauseClusters))l.push(`- ${k}: ${v.confidence}; ${v.contracts.join(', ')}; episodes ${v.episodes.join(', ')}. ${v.reason}`);l.push('','## Prior 20 comparison','','Distributions are reported in JSON for the same raw metrics; thresholds were unchanged. Browser-only contracts remain BLOCKED by managed Chromium observability limits.');return l.join('\n')+'\n';}
if(require.main===module)main();
module.exports={EPISODES,frameMetrics,aggregate,main};
