#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const {closure,compare}=require('./v42_production_closure');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v42');
const HEAD='c8a4bbb64b94feb896b22ad7de73741898da06a2',OLD='6b3fd3ee40af657178a193436350b4f62f2d0f05',FROZEN='d3a8131484f9c06b99e6ee506baf788c7ab34b2a';
const current={...closure(),sourceHead:HEAD},old=closure(OLD),frozen=closure(FROZEN),oracle=require('../evidence/v42/V42_100_EPISODE_ORACLE.json'),mutation=require('../evidence/v42/V42_ORACLE_MUTATION_RESULTS.json'),draw=require('../evidence/v42/V42_ORACLE_DRAW_INPUT_BINDING.json'),kickoff=require('../evidence/v42/V42_KICKOFF_PREVIEW_LIVE_STATE_REPAIR.json');
const cmpOld=compare(current,old),cmpFrozen=compare(current,frozen), css=current.files.find(x=>x.path==='runtime/technical_test.css');
const repo={attempted:true,flrTestCheckoutPresent:false,mainBefore:null,mainAfter:null,writePerformed:false,commit:null,push:null,reason:'FLR_TEST absent locally; git ls-remote https://github.com/1Lisam/FLR_TEST.git refs/heads/main failed: Could not resolve host: github.com'};
const hosted={status:'BLOCKED_NETWORK',mismatchCount:null,notFoundCount:null,mimeFailureCount:null,checked:0,reason:'Deployment did not produce a committed target SHA; public HTTP validation cannot be performed.'};
const disposition='V42_FINAL_DEPLOYMENT_BLOCKED_AFTER_PROVENANCE_REBIND';
const evidence={schemaVersion:'V42_FINAL_PROVENANCE_REBIND_1.0',disposition,productionFingerprintSemantics:{authoritativeValidatedProductionClosureFingerprint:current.closureFingerprint,repoHeadIsInformational:true,qaEvidenceNotInFingerprint:true,actualVisibleClosure:{entry:'index.html',counts:current.counts},canonicalFields:current.canonicalFields},phaseA:{current,validated438Source:old,interveningFrozenSource:frozen,oldProductionFingerprintEqualsCurrent:cmpOld.equal,frozenProductionFingerprintEqualsCurrent:cmpFrozen.equal,requiredExactClosureEquality:cmpOld.equal&&cmpFrozen.equal,fullRepoHeadsDifferOnlyByQAEvidence:'6b3fd3e -> d3a8131 -> c8a4bbb contains QA/evidence additions only; production closure rows and hashes are identical.'},phaseB:{repoHeadAtExecution:HEAD,validatedProductionClosureFingerprint:current.closureFingerprint,matrix:{total:oracle.summary.total,ST:oracle.matrix.roleDistribution.ST,CM:oracle.matrix.roleDistribution.CM,CB:oracle.matrix.roleDistribution.CB,HARD_FAIL:oracle.summary.HARD_FAIL,FAIL:oracle.summary.FAIL,TRUE_WATCH:oracle.summary.TRUE_WATCH,CLEAN:oracle.summary.CLEAN,grossRunawayOrDuplicateScoringSignal:oracle.summary.scoreEcology.grossRunawayOrDuplicateScoringSignal},hash436:draw.verdict,hash437:kickoff.verdict,mutationAllNamedCoreKilled:mutation.allCoreKilled,mutationResults:mutation.results.map(x=>({contractId:x.contractId,status:x.status,killed:x.killed}))},phaseC:{frozenClosureFingerprint:current.closureFingerprint,productionVisibleBytesChanged:false,productionFilesModified:[],validationFilesMayAdvanceAfterFreeze:true},phaseD:{repo:repo,payloadCount:current.counts.total,payloadBreakdown:current.counts},phaseE:{repositoryMismatchCount:null,omissionCount:null,staleShadowCount:null,runtimeTechnicalTestCss:{...css,exact:null,reason:'FLR_TEST commit unavailable'}},phaseF:hosted,truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',userPass:false,newFeaturesFrozen:true,nextWorkerStarted:false,unproven:['canvas rasterization/pixels','CSS/layout rendering','browser event timing','FLR_TEST committed byte identity','hosted HTTP identity']}};
fs.writeFileSync(path.join(OUT,'V42_FINAL_VISIBLE_CLOSURE.json'),JSON.stringify(current,null,2)+'\n');
fs.writeFileSync(path.join(OUT,'V42_FINAL_PROVENANCE_REBIND.json'),JSON.stringify(evidence,null,2)+'\n');
const md=`# V42 Final Provenance Rebind\n\nDisposition: **${disposition}**\n\n## Production identity\n\nThe authoritative validated production closure fingerprint is \`${current.closureFingerprint}\`. It is SHA-256 over canonical ordered \`{path,kind,bytes,sha256,required,load}\` records reached from the actual \`index.html\`; repository HEAD is informational only.\n\nPhase A found exact equality with #438 source \`${OLD}\` and frozen source \`${FROZEN}\`: 42 files, HTML 1 / CSS 4 / JS 37 / assets 0 / dynamic 0. Every closure file SHA-256 matched. The full repository HEADs differ only because QA/evidence commits advanced.\n\n## Revalidation\n\nThe exact current-candidate matrix passed: 100 total (ST 34 / CM 33 / CB 33), HARD_FAIL 0, FAIL 0, TRUE_WATCH 0, CLEAN 100. No gross runaway/duplicate scoring signal occurred. #436: **${draw.verdict}**. #437: **${kickoff.verdict}**. All named core mutations were killed (12/12).\n\n## Deployment\n\nFLR_TEST was absent locally. The independent remote main lookup was attempted but blocked by DNS/network: \`Could not resolve host: github.com\`. No payload was written, committed, or pushed. Therefore repository byte identity and hosted HTTP identity remain unproven; hosted validation is separately marked **BLOCKED_NETWORK**.\n\nClosure count remains 42: HTML 1 / CSS 4 / JS 37 / assets 0 / dynamic 0. \`runtime/technical_test.css\` is included exactly (${css.bytes} bytes, SHA-256 \`${css.sha256}\`); target identity was not proven because deployment was blocked.\n\nUSER_FAIL_OPEN=OPEN; STEP79=NOT_STARTED; no user PASS, no manual pass/manual shot, and no new Worker. Remaining browser-only boundaries: canvas rasterization/pixels, CSS/layout rendering, browser event timing, plus target repository and hosted HTTP byte identity.\n\nFull structured evidence: \`V42_FINAL_PROVENANCE_REBIND.json\`.\n`;
fs.writeFileSync(path.join(OUT,'V42_FINAL_PROVENANCE_REBIND.md'),md);
fs.writeFileSync(path.join(OUT,'V42_FINAL_HOSTED_VALIDATION.json'),JSON.stringify({schemaVersion:'V42_FINAL_HOSTED_VALIDATION_2.0',...evidence},null,2)+'\n');
fs.writeFileSync(path.join(OUT,'V42_FINAL_HOSTED_VALIDATION.md'),md.replace('# V42 Final Provenance Rebind','# V42 Final Hosted Validation'));
console.log(JSON.stringify({disposition,closureFingerprint:current.closureFingerprint,counts:current.counts,oracle:{total:oracle.summary.total,HARD_FAIL:oracle.summary.HARD_FAIL,FAIL:oracle.summary.FAIL,TRUE_WATCH:oracle.summary.TRUE_WATCH,CLEAN:oracle.summary.CLEAN},flrTest:repo,hosted},null,2));
