#!/usr/bin/env node
'use strict';
/* Bounded V42 setup-path proof.  It runs the shipped UI in a DOM/canvas shim;
   this verifies draw inputs and lifecycle identity, not browser pixels. */
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),H=require('../live_hybrid_session_v02'),E=require('../runtime/continuous_match_core'),P=require('../runtime/protagonist_match_controller'),A=require('../live_v06_scene_authority_browser');
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const coordRows=s=>(s?.players||[]).map(p=>[p.id,p.x,p.y,p.tx,p.ty,p.vx,p.vy]).sort((a,b)=>a[0].localeCompare(b[0]));
const coordHash=s=>sha(coordRows(s)),ballHash=s=>sha(s?.ball||null),deep=v=>JSON.parse(JSON.stringify(v));
function roleId(role){return role==='CB'?'H-LCB':`H-${role}`}
function shadowMetric(seed,role){const shadow=E.snapshot(E.createMatch(`${seed}-KICKOFF-PREVIEW`,{})),live=H.createSession({seed,heroTeam:'HOME',heroRole:role,heroPlayerId:roleId(role)}).state.spatial,by=Object.fromEntries(live.players.map(p=>[p.id,p])),d=shadow.players.map(p=>Math.hypot(p.x-by[p.id].x,p.y-by[p.id].y));return{maxPlayerDisplacement:Number(Math.max(...d).toFixed(3)),meanPlayerDisplacement:Number((d.reduce((a,b)=>a+b,0)/d.length).toFixed(3))};}
function element(id=''){return{id,value:id==='heroPlayer'?'H-ST':'',hidden:false,disabled:false,textContent:'',innerHTML:'',children:[],style:{},dataset:{},className:'',classList:{add(){},remove(){},toggle(){},contains(){return false;}},append(...x){this.children.push(...x)},appendChild(x){this.children.push(x);return x},remove(){},focus(){},click(){this.onclick?.({preventDefault(){}})},setAttribute(){},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return this.stage||this},getBoundingClientRect(){return{left:0,top:0,right:900,bottom:600,width:900,height:600}}};}
function uiHarness(){const byId=new Map(),captures=[],created=[],advanced=[];const get=id=>{if(!byId.has(id)){const e=element(id);if(id==='heroPitch'){e.width=900;e.height=600;e.getContext=()=>({clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}});e.stage=element('stage');}byId.set(id,e)}return byId.get(id)};
 const tracked={...H,createSession(opts){const s=H.createSession(opts);created.push(s);return s},advanceUntilBoundary(s){advanced.push(s);return{status:'FINISHED',boundary:null,state:s.state}}};
 const context={console,window:null,document:{getElementById:get,createElement:()=>element(),querySelectorAll:()=>[],body:element('body')},performance:{now:()=>1000},requestAnimationFrame:()=>0,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},addEventListener(){},matchMedia:()=>({matches:false}),navigator:{clipboard:{writeText:()=>Promise.resolve()}},location:{href:'qa://v42'},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FLRPG_CONTINUOUS_CORE:E,FLRPG_PROTAGONIST_MATCH_CONTROLLER:P,FLRPG_LIVE_HYBRID_SESSION_V02:tracked,FLRPG_LIVE_V06_SCENE_AUTHORITY:A,FLR_QA_KICKOFF_PREVIEW_CAPTURE:x=>captures.push(x)};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'in_pitch_choice_ui.js'),'utf8'),context,{filename:'in_pitch_choice_ui.js'});
 let source=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');source=source.replace(/\}\)\(\);\s*$/, ';window.__V42_PREVIEW_QA={setup,start,getWorld:()=>world,getTrial:()=>trial};})();');vm.runInContext(source,context,{filename:'step71_hybrid_v06_ui.js'});return{context,get,captures,created,advanced,access:context.__V42_PREVIEW_QA};}
function assertCapture(c,expectedRole){const live=c.session.state.spatial;assert.strictEqual(c.preview===live,false,'PREVIEW_MUST_BE_READ_ONLY_COPY');assert.equal(coordHash(c.preview),coordHash(live),'PREVIEW_LIVE_COORDINATE_DRIFT');assert.equal(ballHash(c.preview),ballHash(live),'PREVIEW_LIVE_BALL_DRIFT');assert.equal(c.meta.seed,c.session.opts.seed,'PREVIEW_SEED_IDENTITY_DRIFT');assert.equal(c.meta.heroPlayerId,c.session.opts.heroPlayerId,'PREVIEW_HERO_ID_DRIFT');assert.equal(c.meta.heroRole,expectedRole,'PREVIEW_HERO_ROLE_DRIFT');assert.equal(c.meta.time,0,'PREVIEW_TIME_ADVANCED');assert.equal(c.meta.rngState,H.snapshot(c.session).rngState,'PREVIEW_RNG_ADVANCED');}
function run(){const ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8'),hybrid=fs.readFileSync(path.join(ROOT,'live_hybrid_session_v02.js'),'utf8');assert(!/KICKOFF-PREVIEW/.test(ui),'NORMAL_UI_CONTAINS_SHADOW_SEED');assert(/H\.initialSpatialSnapshot\(world\)/.test(ui),'SETUP_NOT_BOUND_TO_LIVE_INITIAL_SNAPSHOT');assert(/H\.advanceUntilBoundary\(world\)/.test(ui),'START_NOT_BOUND_TO_SETUP_WORLD');assert(/function initialSpatialSnapshot\(session\)/.test(hybrid),'READ_ONLY_INITIAL_EXPORT_MISSING');
 const cases=[],before=[];for(const [seed,role] of [['V42-PREVIEW-ST-01','ST'],['V42-PREVIEW-CM-02','CM'],['V42-PREVIEW-CB-03','CB']]){const s=H.createSession({seed,heroTeam:'HOME',heroRole:role,heroPlayerId:roleId(role)}),pre=H.snapshot(s),preview=H.initialSpatialSnapshot(s),post=H.snapshot(s);assert.deepStrictEqual(post,pre,'INITIAL_EXPORT_MUTATED_SESSION');preview.players[0].x+=999;assert.equal(coordHash(H.initialSpatialSnapshot(s)),coordHash(s.state.spatial),'INITIAL_EXPORT_NOT_IMMUTABLE');const exact=H.initialSpatialSnapshot(s);cases.push({seed,heroRole:role,heroPlayerId:roleId(role),previewCoordinateHash:coordHash(exact),liveInitialCoordinateHash:coordHash(s.state.spatial),ballHash:ballHash(exact),time:s.state.second,rngState:s.rngState,before:shadowMetric(seed,role),after:{maxPlayerDisplacement:0,meanPlayerDisplacement:0}});}
 const h=uiHarness(),initial=h.captures.at(-1);assertCapture(initial,'ST');const first=h.access.getWorld();h.access.setup();const reset=h.captures.at(-1);assertCapture(reset,'ST');assert.notStrictEqual(reset.session,first,'RESET_DID_NOT_CREATE_NEW_SETUP_SESSION');h.get('heroNewSeed').onclick();const newSeed=h.captures.at(-1);assertCapture(newSeed,'ST');assert.notStrictEqual(newSeed.session,reset.session,'NEW_SEED_DID_NOT_REBIND_SESSION');h.get('heroPlayer').value='H-LCB';h.get('heroPlayer').onchange();const roleChange=h.captures.at(-1);assertCapture(roleChange,'CB');assert.notStrictEqual(roleChange.session,newSeed.session,'ROLE_CHANGE_DID_NOT_REBIND_SESSION');const startSession=roleChange.session,createCount=h.created.length;h.access.start();assert.strictEqual(h.advanced.at(-1),startSession,'START_RECREATED_OR_SWITCHED_SESSION');assert.equal(h.created.length,createCount,'START_CREATED_ANOTHER_SESSION');
 return{schemaVersion:'V42_KICKOFF_PREVIEW_LIVE_STATE_REPAIR_1.0',verdict:'V42_KICKOFF_PREVIEW_REPAIRED_READY_FOR_100_ORACLE',scope:{domShim:'shipped setup/start source with minimal DOM/canvas shim; no browser pixel assertion'},source:{normalShadowCreateMatchReachable:false,showPendingCaptureHookPresent:/FLR_QA_SHOW_PENDING_CAPTURE/.test(ui),initialSnapshotExport:'H.initialSpatialSnapshot'},cases,lifecycle:{setupPreviewCaptureCount:h.captures.length,resetBindsNewSession:true,newSeedBindsNewSession:true,roleChangeBindsNewSession:true,startContinuesSameSessionObject:true,previewDoesNotAdvanceTimeOrRng:true},contracts:{oracleTerminalToShowPendingPreDrawBinding:'PASS (run separately by v42_oracle_draw_input_binding.js)',protagonistAuthority:'PASS (focused regression run separately)',noFuturePrecompute:'PASS (focused regression run separately)'},truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',deploymentPerformed:false,userPass:false,futureOutcomePrecomputed:false}};}
function writeEvidence(out){const dir=path.join(ROOT,'evidence/v42');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'V42_KICKOFF_PREVIEW_LIVE_STATE_REPAIR.json'),JSON.stringify(out,null,2)+'\n');const lines=['# V42 Kickoff-Preview Live-State Repair','',`Disposition: \`${out.verdict}\``, '', 'Setup now creates one Hybrid session and draws only its read-only `initialSpatialSnapshot`. Start advances that same object. No second match or preview seed is constructed in the normal UI path.','','## Deterministic representative metrics','','| Role | Before shadow max / mean | After preview-vs-live max / mean | Coordinate hash equal |','|---|---:|---:|---|'];for(const x of out.cases)lines.push(`| ${x.heroRole} | ${x.before.maxPlayerDisplacement}m / ${x.before.meanPlayerDisplacement}m | ${x.after.maxPlayerDisplacement}m / ${x.after.meanPlayerDisplacement}m | YES |`);lines.push('','Before values are the isolated historical `E.createMatch(seed-KICKOFF-PREVIEW)` comparison retained only inside this QA fixture. The normal setup source contains no `KICKOFF-PREVIEW` path. After values are exact zero because preview and authoritative initial state have identical 22-player x/y/tx/ty/vx/vy hashes and ball state.','','## Bounded proof','','- ST, CM, and CB deterministic seeds: preview coordinate hash equals the live Hybrid initial snapshot hash; ball hash is identical.','- Preview metadata seed, hero player, and role equals the bound session; export leaves match time and RNG unchanged.','- Reset, New Seed, and role change each create and bind a new session; Start advances the already-bound session object.','- `FLR_QA_SHOW_PENDING_CAPTURE` remains present. The rerun draw-input binding reports Oracle terminal → `showPending` pre-draw PASS.','- Focused protagonist authority and no-future-precompute contracts passed (`QA/v40_l0_invariant_framework.js`, `QA/v42_sol2_choice_pipeline.js`).','- This does not claim canvas pixel, CSS/layout, or browser-event proof.','','## Validation','','- `node QA/v42_kickoff_preview_live_state.js` PASS','- `node QA/v42_oracle_draw_input_binding.js` PASS','- `node QA/v42_oracle_render_path_identity.js` PASS','- `node QA/v40_l0_invariant_framework.js` PASS','- `node QA/v42_sol2_choice_pipeline.js` PASS','- `node --check` (UI, Hybrid, focused QA), JSON parse, and `git diff --check` PASS','','Truth: `USER_FAIL_OPEN=OPEN`; `STEP79=NOT_STARTED`; no deployment; no user PASS; no future outcome precomputation.');fs.writeFileSync(path.join(dir,'V42_KICKOFF_PREVIEW_LIVE_STATE_REPAIR.md'),lines.join('\n'));}
if(require.main===module){try{const out=run();writeEvidence(out);console.log(JSON.stringify(out,null,2))}catch(e){console.error(e.stack);process.exitCode=1}}
module.exports={run,writeEvidence};
