'use strict';
/* Read-only adapter over the production Hybrid/V0.6 APIs. Browser fields are never invented. */
const path=require('path');
const H=require('../live_hybrid_session_v02'),A=require('../live_v06_scene_authority_browser');
const deep=x=>x==null?x:JSON.parse(JSON.stringify(x));
const team=id=>String(id).startsWith('H-')?'HOME':'AWAY';
const role=id=>{const r=String(id).split('-')[1]||'';return r.includes('CB')?'CB':r.includes('GK')?'GK':r.includes('B')?'FB':r.includes('ST')?'ST':r.includes('W')?'WF':r.includes('CM')?'CM':r;};
function discoverDependencyClosure(root=path.resolve(__dirname,'..')){const seen=new Set(),out=[],queue=['index.html'];while(queue.length){const rel=queue.shift();if(seen.has(rel))continue;seen.add(rel);const file=path.resolve(root,rel);if(!file.startsWith(root)||!require('fs').existsSync(file)){out.push({path:rel,status:'MISSING'});continue;}const text=require('fs').readFileSync(file,'utf8');const kind=/\.css$/i.test(rel)?'CSS':/\.(js|mjs)$/i.test(rel)?'JS':'HTML';out.push({path:rel,status:'PRESENT',kind});const refs=[...text.matchAll(/(?:src|href)=["']([^"'#?]+)|(?:fetch|import\s*\(|new\s+Image\s*\()[\s\S]{0,20}?["']([^"']+)["']/g)].map(m=>m[1]||m[2]).filter(x=>x&&!/^(https?:|data:|#)/.test(x));for(const ref of refs){const child=path.posix.normalize(path.posix.join(path.posix.dirname(rel),ref));if(!seen.has(child))queue.push(child);}}return{root,dependencies:out,hasCss:out.some(x=>x.kind==='CSS'),scriptsOnly:out.length>0&&!out.some(x=>x.kind==='CSS')};}
function normFrame(s){if(!s)return null;return{time:Number(s.time??s.second),phase:s.phase||null,score:deep(s.score||null),possession:s.possession||null,ball:deep(s.ball||null),players:(s.players||[]).map(p=>({id:p.id,team:p.team||team(p.id),role:p.role||role(p.id),x:p.x,y:p.y,vx:p.vx||0,vy:p.vy||0,tx:p.tx,ty:p.ty,action:p.action||null,responsibility:p.responsibilityReason||p.responsibility||null,epoch:p.epoch||p.responsibilityEpoch||null,markTargetId:p.markTargetId||null})).slice(0,22)};}
function nextBoundary(session){for(let i=0;i<10;i++){const r=H.advanceUntilBoundary(session,{maxActions:20000});if(r.boundary?.type==='PROTAGONIST_2D_WINDOW')return r;if(!r.boundary||r.boundary.type==='MATCH_END'||r.status==='FINISHED')break;const q=r.state.spatial;H.resumeFromHighRes(session,{snapshot:{time:r.boundary.atSecond+.1,score:r.state.score,possession:r.state.possession,ball:{mode:'CONTROLLED',x:q.ball.x,y:q.ball.y,ownerId:r.state.ball.ownerId},players:q.players.map(p=>({...p,team:team(p.id),role:role(p.id)}))},actualEvents:[],hadChoice:false,futureOutcomePrecomputed:false});}return null;}
function captureActualPath(opts={}){const seed=opts.seed||'V42-ORACLE-CURRENT',session=H.createSession({seed,heroTeam:'HOME',heroRole:opts.heroRole||'ST',heroPlayerId:opts.heroPlayerId||'H-ST',durationSeconds:opts.durationSeconds||1800});const hit=nextBoundary(session);if(!hit)return{seed,sessionId:null,frames:[],current:null,missing:['HYBRID_PROTAGONIST_BOUNDARY']};const lowResPreFrames=(session._promotionHistory||[]).map(s=>normFrame({time:s.second,phase:s.phase,score:s.score,possession:s.possession,ball:s.spatial?.ball,players:s.spatial?.players})).filter(Boolean);const out=A.runToChoice(hit.boundary,{seed:`${seed}|HR`,runtimeDir:path.resolve(__dirname,'../runtime'),minPreSeconds:5,maxSearchSeconds:30});const t=out.state.choiceBoundarySpatial||{};const entryTraceB=normFrame(t.B),terminal=normFrame(out.E.snapshot(out.state.m));const frames=[t.A,t.B,...(out.frames||[])].filter(Boolean).map(normFrame);const pending=out.pending||null;const options=(pending?.options||[]).map(o=>({choiceId:o.id,targetId:o.targetId||null,recommended:!!o.recommended,meta:deep(o.meta||null)}));return{schemaVersion:'V42_NORMALIZED_OBSERVATION_1.1',seed,sessionId:session.opts?.seed||seed,trial:null,hero:hit.boundary.heroPlayerId,time:terminal?.time,phase:terminal?.phase,possession:terminal?.possession,frames,lowResPreFrames,preContext:deep(hit.boundary.preContext||[]),current:terminal,terminalPendingChoiceFrame:terminal,entryTraceB,entryTraceBSemantics:'V0.6_ENTRY_TRACE_NOT_RENDER_FRAME',boundary:{id:hit.boundary.sceneId,type:hit.boundary.type,time:hit.boundary.atSecond,lowRes:normFrame({time:hit.boundary.stateSnapshot.second,phase:hit.boundary.stateSnapshot.phase,score:hit.boundary.stateSnapshot.score,possession:hit.boundary.stateSnapshot.possession,ball:hit.boundary.stateSnapshot.spatial?.ball,players:hit.boundary.stateSnapshot.spatial?.players})},handoffId:t.A?.boundaryId||null,firstVisibleChoiceFrame:terminal,firstVisibleChoiceFrameSemantics:'COMPATIBILITY_ALIAS_OF_TERMINAL_PENDING_NOT_ENTRY_TRACE_B',choices:options,events:deep(out.actualEvents||[]),futureOutcomePrecomputed:pending?.futureOutcomePrecomputed,telemetry:{responsibility:deep(out.state.m.defensiveResponsibility||null)},browser:{available:false,missing:['CANVAS_FRAME_CAPTURE','DOM_INTERACTION_LOG','NETWORK_DEPENDENCY_LOG']},dependencyClosure:discoverDependencyClosure(),source:{previewShadowPath:true,ballSpriteStatus:'NOT_IMPLEMENTED'}};}
module.exports={captureActualPath,normFrame,discoverDependencyClosure};
