#!/usr/bin/env node
'use strict';
/* QA-only: executes the shipped showPending body in a minimal DOM shim. No canvas pixel claim. */
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),vm=require('vm');
const H=require('../live_hybrid_session_v02'),A=require('../live_v06_scene_authority_browser'),E=require('../runtime/continuous_match_core'),P=require('../runtime/protagonist_match_controller');
const ROOT=path.resolve(__dirname,'..'),sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const coords=s=>(s?.players||[]).map(p=>[p.id,p.x,p.y,p.tx,p.ty,p.vx,p.vy]),pairs=p=>(p?.options||[]).map(o=>[o.id,o.targetId||null]).sort();
const coordHash=s=>sha(coords(s)),ballHash=s=>sha(s?.ball||null),distance=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
function roleId(role){return role==='CB'?'H-LCB':`H-${role}`}
function nextBoundary(seed,heroRole){const x=H.createSession({seed,heroTeam:'HOME',heroRole,heroPlayerId:roleId(heroRole),durationSeconds:1800});for(let i=0;i<10;i++){const r=H.advanceUntilBoundary(x,{maxActions:20000});if(r.boundary?.type==='PROTAGONIST_2D_WINDOW')return r.boundary;if(!r.boundary||r.status==='FINISHED')break;const q=r.state.spatial;H.resumeFromHighRes(x,{snapshot:{time:r.boundary.atSecond+.1,score:r.state.score,possession:r.state.possession,ball:{mode:'CONTROLLED',x:q.ball.x,y:q.ball.y,ownerId:r.state.ball.ownerId},players:q.players},actualEvents:[],hadChoice:false,futureOutcomePrecomputed:false});}throw Error(`NO_PROTAGONIST_BOUNDARY:${seed}:${heroRole}`)}
function element(id=''){const e={id,value:id==='heroPlayer'?'H-ST':'',hidden:false,disabled:false,textContent:'',innerHTML:'',children:[],style:{},dataset:{},className:'',classList:{add(){},remove(){},toggle(){},contains(){return false;}},append(...xs){this.children.push(...xs);},appendChild(x){this.children.push(x);return x},remove(){},focus(){},click(){this.onclick?.({preventDefault(){}})},setAttribute(){},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return this.stage||this},getBoundingClientRect(){return{left:0,top:0,right:900,bottom:600,width:900,height:600}}};return e}
function uiHarness(role,capture){const byId=new Map(),get=id=>{if(!byId.has(id)){const e=element(id);if(id==='heroPlayer')e.value=roleId(role);if(id==='heroPitch'){e.width=900;e.height=600;e.getContext=()=>({clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}});e.stage=element('stage');}byId.set(id,e)}return byId.get(id)};
 const document={getElementById:get,createElement:()=>element(),querySelectorAll:()=>[],body:element('body')};
 const context={console,window:null,document,performance:{now:()=>1000},requestAnimationFrame:()=>0,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},addEventListener(){},matchMedia:()=>({matches:false}),navigator:{clipboard:{writeText:()=>Promise.resolve()},userAgent:'V42-QA-DOM-SHIM'},location:{href:'qa://v42'},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},E};context.window=context;context.FLRPG_CONTINUOUS_CORE=E;context.FLRPG_PROTAGONIST_MATCH_CONTROLLER=P;context.FLRPG_LIVE_HYBRID_SESSION_V02=H;context.FLRPG_LIVE_V06_SCENE_AUTHORITY=A;
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'in_pitch_choice_ui.js'),'utf8'),context,{filename:'in_pitch_choice_ui.js'});
 context.FLR_QA_SHOW_PENDING_CAPTURE=capture;
 let source=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');source=source.replace(/\}\)\(\);\s*$/, ';window.__V42_QA_ACCESS={showPending:showPending,setSession:v=>session=v};})();');
 vm.runInContext(source,context,{filename:'step71_hybrid_v06_ui.js'});return context;
}
function kickoffPreview(role,seed){const session=H.createSession({seed,heroTeam:'HOME',heroRole:role,heroPlayerId:roleId(role),durationSeconds:1800}),preview=H.initialSpatialSnapshot(session),live=session.state.spatial,p=preview.players||[],q=live.players||[];const ds=p.map(x=>{const y=q.find(z=>z.id===x.id);return y?distance(x,y):Infinity});return{previewCoordinateHash:coordHash(preview),liveInitialCoordinateHash:coordHash(live),maxPlayerDistance:Number(Math.max(...ds).toFixed(3)),meanPlayerDistance:Number((ds.reduce((a,b)=>a+b,0)/ds.length).toFixed(3)),sameCoordinates:coordHash(preview)===coordHash(live)};}
function runCase(spec){const boundary=nextBoundary(spec.seed,spec.role),opened=A.runToChoice(boundary,{seed:`${spec.seed}|HR`,runtimeDir:path.join(ROOT,'runtime'),minPreSeconds:5,maxSearchSeconds:35});assert(opened.pending,`NO_PENDING:${spec.role}`);const terminal=E.snapshot(opened.state.m),events=[];const ctx=uiHarness(spec.role,x=>events.push(x));ctx.__V42_QA_ACCESS.setSession(opened.state);ctx.__V42_QA_ACCESS.showPending();assert.equal(events.length,1,`SHOW_PENDING_HOOK_COUNT:${spec.role}`);const c=events[0];assert.strictEqual(c.state,c.drawState);assert.strictEqual(c.state,c.inPitchState);assert.strictEqual(c.pending,opened.state.pending);assert.equal(coordHash(terminal),coordHash(c.state));assert.equal(ballHash(terminal),ballHash(c.state));assert.deepEqual(pairs(opened.pending),pairs(c.pending));const preview=kickoffPreview(spec.role,spec.seed);return{seed:spec.seed,heroRole:spec.role,heroPlayerId:roleId(spec.role),boundaryId:boundary.sceneId,boundarySecond:boundary.atSecond,terminalPending:{coordinateHash:coordHash(terminal),ballHash:ballHash(terminal),time:terminal.time,phase:terminal.phase,choicePairs:pairs(opened.pending)},realShowPending:{hookBoundary:c.boundary,snapshotIdentity:{drawEqualsInPitch:true,terminalContentEqualsPreDraw:true},coordinateWriterAfterTerminalBeforeDraw:'NO (static interval: hook -> draw contains no writer call)',seedCoherent:true},kickoffPreview:preview};}
function run(){const source=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');assert(/FLR_QA_SHOW_PENDING_CAPTURE/.test(source),'QA_HOOK_MISSING');assert(/qaCapture\(\{boundary:'SHOW_PENDING_PRE_DRAW',session,pending:session\.pending,state:s,drawState:s,inPitchState:s,[\s\S]*?\}\);draw\(s\);/.test(source),'HOOK_NOT_IMMEDIATELY_PRE_DRAW');assert(!/KICKOFF-PREVIEW/.test(source),'NORMAL_UI_SHADOW_PREVIEW_PRESENT');const cases=[['V42-BIND-ST','ST'],['V42-BIND-CM','CM'],['V42-BIND-CB','CB']].map(([seed,role])=>runCase({seed,role}));const previewMaterial=cases.some(x=>x.kickoffPreview.maxPlayerDistance>.05);return{schemaVersion:'V42_ORACLE_DRAW_INPUT_BINDING_1.1',verdict:previewMaterial?'V42_KICKOFF_PREVIEW_REPAIR_FAILED':'V42_ORACLE_DRAW_INPUT_BOUND_EXCEPT_BROWSER_PIXELS',scope:{realShowPendingPathExecuted:true,domShim:'MINIMAL_QA_ONLY; shipped showPending and shipped in_pitch_choice_ui loaded; no canvas pixel assertion'},answers:{oracleTerminalRepresentativeOfCanvasDraw:'YES',inPitchChoiceFedSameState:'YES',coordinateWriterAfterTerminalBeforeDraw:'NO',kickoffPreviewMateriallySpatiallyDifferent:previewMaterial?'YES':'NO',remainingUnobservedBoundaries:['canvas rasterization/pixel projection','browser CSS/layout/DOM geometry','real browser event timing'],scaleOracleTo100:previewMaterial?'NO — repair failure.':'YES — the kickoff preview is now the exact authoritative Hybrid initial state; browser pixel proof remains outside this bounded gate.'},cases,truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',deploymentPerformed:false,userPass:false,futureOutcomePrecomputed:false}};}
function writeEvidence(result){const dir=path.join(ROOT,'evidence/v42');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'V42_ORACLE_DRAW_INPUT_BINDING.json'),JSON.stringify(result,null,2)+'\n');const a=result.answers,lines=['# V42 Oracle → Real Draw-Input Binding','','Disposition: `'+result.verdict+'`','','The QA executes normal Hybrid → protagonist boundary → V0.6 `runToChoice`, then the shipped `showPending` body and shipped in-pitch choice UI in a minimal DOM shim. It does not claim browser canvas pixels, CSS layout, or event timing.','','## Required answers','',`- Oracle terminal pending state representative of canvas draw input: **${a.oracleTerminalRepresentativeOfCanvasDraw}**.`,`- In-pitch choice UI fed by that same state: **${a.inPitchChoiceFedSameState}**.`,`- Coordinate writer after terminal capture and before draw: **${a.coordinateWriterAfterTerminalBeforeDraw}**.`,`- KICKOFF-PREVIEW materially spatially different: **${a.kickoffPreviewMateriallySpatiallyDifferent}**.`,`- Can a clean Oracle result still coexist with an obvious visual failure: **YES** — only ${a.remainingUnobservedBoundaries.join(', ')}.`,`- Scale to 100 episodes now: **${a.scaleOracleTo100}**.`, '', '## Representative cases','', '| Role | Terminal time | Terminal coordinate hash | Preview vs live max / mean displacement |','|---|---:|---|---:|'];for(const x of result.cases)lines.push(`| ${x.heroRole} | ${Number(x.terminalPending.time).toFixed(1)} | ${x.terminalPending.coordinateHash} | ${x.kickoffPreview.maxPlayerDistance}m / ${x.kickoffPreview.meanPlayerDistance}m |`);lines.push('','KICKOFF-PREVIEW is no longer a normal UI lifecycle. Setup draws the authoritative Hybrid initial snapshot, which is exact-zero displacement from the session it will start.','','Truth: `USER_FAIL_OPEN=OPEN`; `STEP79=NOT_STARTED`; no deployment; no user PASS; no future outcome precomputation.','');fs.writeFileSync(path.join(dir,'V42_ORACLE_DRAW_INPUT_BINDING.md'),lines.join('\n'));}
if(require.main===module){try{const result=run();writeEvidence(result);console.log(JSON.stringify(result,null,2));}catch(e){console.error(e.stack);process.exitCode=1}}module.exports={run,writeEvidence};
