#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const {evaluate}=require('./v42_football_plausibility_oracle_runner');
const clone=x=>JSON.parse(JSON.stringify(x));
function base(){const ps=[];for(let i=0;i<22;i++)ps.push({id:`${i<11?'H':'A'}-${i}`,team:i<11?'HOME':'AWAY',role:i%11===0?'GK':i%5===0?'ST':'CB',x:10+(i%11)*8,y:8+(i%6)*9,tx:10+(i%11)*8,ty:8+(i%6)*9,vx:0,vy:0});return{seed:'MUTANT',current:{time:10,phase:'OPEN_PLAY',possession:'HOME',ball:{x:50,y:34,ownerId:'H-5'},players:ps},frames:[],browser:{available:true},boundary:{lowRes:{players:clone(ps),ball:{x:50,y:34}}},firstVisibleChoiceFrame:{players:clone(ps),ball:{x:50,y:34}},authority:{user:true,choiceId:'PASS',targetId:'H-2',executedChoiceId:'PASS',executedTargetId:'H-2'},restart:{valid:true},eventLifecycle:{valid:true},sessionLifecycle:{oldSeed:'A',newSeed:'B'},completionLedger:[],deployment:{complete:true,match:true}};}
const mutations={"SPI-001":o=>o.current.players.slice(1,8).forEach(p=>{p.x=50;p.y=34}),"DCA-003":o=>{o.current.players.filter(p=>p.team==='AWAY').forEach(p=>{p.x=51;p.y=34});o.current.players.find(p=>p.id==='H-5').role='ST';},"MOT-004":o=>{o.current.players.filter(p=>p.team==='AWAY'&&p.role!=='GK').slice(0,2).forEach(p=>{p.tx=40;p.ty=30});o.frames=[clone(o.current),clone(o.current)];},"CON-005":o=>o.firstVisibleChoiceFrame.players[2].x+=20,"AUT-006":o=>o.authority.executedTargetId='H-3',"RUL-007":o=>o.restart.valid=false,"EVT-008":o=>o.eventLifecycle.valid=false,"CHO-009":o=>o.choiceUi={valid:false,reason:'HIDDEN_VIABLE_TARGET'},"SES-010":o=>o.sessionLifecycle.newSeed='A',"CMP-011":o=>o.completionLedger=[{actual:'WATCH',claimed:'COMPLETE'}],"DEP-012":o=>{o.deployment.match=false;o.deployment.complete=false;},"RSP-002":o=>{o.current.players.filter(p=>p.role==='ST').forEach(p=>{p.x=p.team==='HOME'?70:35;p.tx=p.x;p.vx=0;});const p=o.current.players.find(p=>p.id==='H-5');p.x=20;p.tx=20;p.vx=0;o.current.ball.ownerId='H-2';o.frames=Array.from({length:51},(_,i)=>{const f=clone(o.current);f.time=10+i*.1;return f;});}};
function run(){const results=[];for(const [id,mutate] of Object.entries(mutations)){const o=base();mutate(o);const r=evaluate(o).results.find(x=>x.contractId===id);results.push({contractId:id,status:r.status,killed:['HARD_FAIL','FAIL'].includes(r.status),evidence:r.evidence});}return{schemaVersion:'V42_ORACLE_MUTATION_RESULTS_1.0',results,allCoreKilled:results.every(x=>x.killed)};}
if(require.main===module){const r=run();fs.writeFileSync(path.resolve(__dirname,'../evidence/v42/V42_ORACLE_MUTATION_RESULTS.json'),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r,null,2));process.exitCode=r.allCoreKilled?0:1;}module.exports={run,base};
