#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const {capsule}=require('./v42_oracle_failure_capsule');
const contracts=require('./v42_football_plausibility_oracle_contracts.json');
const D=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
const row=(contractId,status,detail,evidence={})=>({contractId,status,detail,evidence,candidateBlocking:!!contracts.contracts.find(c=>c.contractId===contractId)?.blocking});
const need=(o,fields)=>fields.filter(f=>o[f]==null);
function players(o){return o.current?.players||[];} function open(o){return !/CORNER|RESTART|GOAL|SET/.test(o.current?.phase||'');}
function runSPI(o){if(players(o).length!==22)return row('SPI-001','BLOCKED','22-player geometry unavailable',{missing:'players22'});if(!open(o))return row('SPI-001','PASS','legal restart exception');const ps=players(o).filter(p=>p.role!=='GK'),cluster=ps.filter(p=>ps.filter(q=>D(p,q)<2.2).length>=6);const teams=['HOME','AWAY'].map(t=>{const x=ps.filter(p=>p.team===t),xs=x.map(p=>p.x),ys=x.map(p=>p.y);return{x:Math.max(...xs)-Math.min(...xs),y:Math.max(...ys)-Math.min(...ys)};});return cluster.length>=6||teams.some(x=>x.x<8||x.y<5)?row('SPI-001','HARD_FAIL','persistent local cluster or narrow band',{cluster:cluster.map(p=>p.id),bands:teams}):row('SPI-001','PASS','geometry has no core collapse',{bands:teams});}
function localX(p){return p.team==='HOME'?Number(p.x):105-Number(p.x);}
function forwardVelocity(p){return p.team==='HOME'?Number(p.vx||0):-Number(p.vx||0);}
function deepStriker(p){return p?.role==='ST'&&localX(p)<48;}
function validStrikerCause(frame,p){
 const ball=frame?.ball||{}, forwardTarget=Number.isFinite(Number(p.tx))&&(p.team==='HOME'?Number(p.tx)-Number(p.x):Number(p.x)-Number(p.tx))>=10;
 return ball.ownerId===p.id||/DROP|TRACK|RECOVER|COVER/.test(p.action||'')||(/PIN|RUN|THREAT|CONNECT|CHANNEL/.test(p.action||'')&&forwardTarget&&forwardVelocity(p)>=1);
}
function runRSP(o){
 if(players(o).length!==22)return row('RSP-002','BLOCKED','role geometry unavailable');
 const frames=(o.frames||[]).filter(f=>(f.players||[]).length===22&&Number.isFinite(Number(f.time))).sort((a,b)=>Number(a.time)-Number(b.time));
 if(!frames.length)return row('RSP-002','BLOCKED','5s temporal role evidence unavailable');
 const candidates=[];
 const strikerIds=[...new Set(frames.flatMap(f=>(f.players||[]).filter(p=>p.role==='ST').map(p=>p.id)))];
 for(const id of strikerIds){
   const series=frames.map(f=>({f,p:(f.players||[]).find(q=>q.id===id)})).filter(x=>x.p),spans=[];let active=null;
   for(const x of series){const contradictory=deepStriker(x.p)&&!validStrikerCause(x.f,x.p);if(contradictory&&(!active||Number(x.f.time)-active.lastTime<=.25)){active??={first:x,last:x,lastTime:Number(x.f.time)};active.last=x;active.lastTime=Number(x.f.time);}else{if(active)spans.push(active);active=null;if(contradictory){active={first:x,last:x,lastTime:Number(x.f.time)};}}}if(active)spans.push(active);
   for(const s of spans){const p=s.first.p,cause=validStrikerCause(s.first.f,p);candidates.push({id,at:Number(s.first.f.time),persistence:Number((Number(s.last.f.time)-Number(s.first.f.time)).toFixed(2)),caused:cause,owner:s.first.f.ball?.ownerId||null,action:p.action||null,forwardTarget:!!(Number.isFinite(Number(p.tx))&&(p.team==='HOME'?Number(p.tx)-Number(p.x):Number(p.x)-Number(p.tx))>=10),forwardVelocity:Number(forwardVelocity(p).toFixed(3))});}
 }
 const bad=candidates.filter(x=>x.persistence>=5);
 return bad.length?row('RSP-002','FAIL','deep striker persists for 5s without possession/receive/recovery cause',{players:bad}):row('RSP-002','PASS','any deep striker state is causally explained or resolves before 5s',{players:candidates});
}
function runDCA(o){if(players(o).length!==22)return row('DCA-003','BLOCKED','defender geometry unavailable');const b=o.current.ball;if(!b?.ownerId)return row('DCA-003','BLOCKED','ball carrier unavailable');const atk=players(o).find(p=>p.id===b.ownerId);if(!atk)return row('DCA-003','BLOCKED','carrier identity unavailable');const def=players(o).filter(p=>p.team!==atk.team&&p.role!=='GK'), near=def.filter(p=>D(p,atk)<14), allChase=def.length>=6&&def.filter(p=>D(p,atk)<10).length>=6;const central=players(o).filter(p=>p.team===atk.team&&p.role==='ST'&&Math.abs(p.y-34)<14&&D(p,atk)>10);const uncovered=central.filter(t=>!def.some(d=>d.markTargetId===t.id||D(d,t)<15));return allChase||uncovered.length?row('DCA-003','HARD_FAIL','material threat lacks cover or defence all chases carrier',{carrier:atk.id,uncovered:uncovered.map(x=>x.id),near:def.map(x=>x.id)}):row('DCA-003','PASS','geometry supplies pressure/cover evidence');}
function runMOT(o){const f=o.frames||[];if(f.length<2)return row('MOT-004','BLOCKED','temporal frames unavailable');let tele=0,osc=0;for(let i=1;i<f.length;i++)for(const p of f[i].players||[]){const q=(f[i-1].players||[]).find(x=>x.id===p.id);if(q&&D(p,q)>12)tele++;}for(const p of players(o)){const ts=f.map(z=>(z.players||[]).find(x=>x.id===p.id)).filter(Boolean);for(let i=2;i<ts.length;i++)if(ts[i].epoch===ts[i-1].epoch&&ts[i].epoch===ts[i-2].epoch&&D(ts[i],ts[i-2])<.1&&D(ts[i],ts[i-1])>3)osc++;}const dest=players(o).filter(p=>p.team==='AWAY'&&p.role!=='GK').filter(p=>players(o).filter(q=>q.id!==p.id&&q.team===p.team&&D({x:p.tx,y:p.ty},{x:q.tx,y:q.ty})<.01).length>0);return tele>=4||osc||dest.length>=2?row('MOT-004','HARD_FAIL','teleport, target oscillation, or identical defender destinations',{teleports:tele,oscillation:osc,destinationIds:dest.map(p=>p.id)}):row('MOT-004','PASS','bounded motion/targets');}
function runCON(o){const a=o.boundary?.lowRes,b=o.firstVisibleChoiceFrame;if(!a||!b)return row('CON-005','BLOCKED','low-res boundary or first visible frame unavailable');if((a.players||[]).length!==22||(b.players||[]).length!==22)return row('CON-005','BLOCKED','ordered 22-player boundary evidence unavailable');const moved=a.players.filter(p=>{const q=b.players.find(x=>x.id===p.id);return !q||D(p,q)>.05;});return moved.length||o.futureOutcomePrecomputed===true?row('CON-005','HARD_FAIL','handoff does not descend from boundary state',{moved:moved.map(p=>p.id),future:o.futureOutcomePrecomputed}):row('CON-005','PASS','boundary and entry state agree');}
function runAUT(o){if(!o.authority)return row('AUT-006','BLOCKED','user commit and engine action receipt unavailable');const a=o.authority;return a.user&&a.choiceId===a.executedChoiceId&&a.targetId===a.executedTargetId?row('AUT-006','PASS','exact commit bound'):row('AUT-006','HARD_FAIL','hero action absent or substituted',a);}
function runRUL(o){if(!o.restart)return row('RUL-007','BLOCKED','restart lifecycle unavailable');const r=o.restart;return r.valid===true?row('RUL-007','PASS','restart geometry/owner valid'):row('RUL-007','HARD_FAIL','invalid restart',r);}
function runEVT(o){if(!o.eventLifecycle)return row('EVT-008','BLOCKED','shot/event/visible outcome receipt unavailable');return o.eventLifecycle.valid?row('EVT-008','PASS','terminal lifecycle coherent'):row('EVT-008','FAIL','terminal event missing or contradicts score',o.eventLifecycle);}
function runCHO(o){if(!o.browser?.available)return row('CHO-009','BLOCKED','rendered choice targets/flight window unavailable',{missing:o.browser?.missing});if(o.choiceUi?.valid===false)return row('CHO-009','FAIL','material target/flight prompt is absent or recommendation altered authority',o.choiceUi);return row('CHO-009','PASS','browser choice affordances captured');}
function runSES(o){if(!o.sessionLifecycle)return row('SES-010','BLOCKED','New Seed UI session observations unavailable');const x=o.sessionLifecycle;return x.newSeed!==x.oldSeed?row('SES-010','PASS','New Seed changed identity',x):row('SES-010','FAIL','New Seed retained deterministic identity',x);}
function runCMP(o){const l=o.completionLedger;if(!l)return row('CMP-011','BLOCKED','request/completion ledger unavailable');const bad=l.filter(x=>['NOT_IMPLEMENTED','WATCH','UNPROVEN'].includes(x.actual)&&x.claimed==='COMPLETE');return bad.length?row('CMP-011','HARD_FAIL','completion ledger falsely closes unresolved work',{items:bad}):row('CMP-011','PASS','completion truth exposed');}
function runDEP(o){if(!o.browser?.available)return row('DEP-012','BLOCKED','recursive browser/network dependency closure unavailable',{missing:o.browser?.missing});const d=o.deployment;return d?.complete&&d.match?row('DEP-012','PASS','recursive visible closure matches'):row('DEP-012','HARD_FAIL','dependency mismatch or scripts-only manifest',d||{});}
const runners={"SPI-001":runSPI,"RSP-002":runRSP,"DCA-003":runDCA,"MOT-004":runMOT,"CON-005":runCON,"AUT-006":runAUT,"RUL-007":runRUL,"EVT-008":runEVT,"CHO-009":runCHO,"SES-010":runSES,"CMP-011":runCMP,"DEP-012":runDEP};
function evaluate(o){const results=contracts.contracts.map(c=>runners[c.contractId](o));return{schemaVersion:'V42_ORACLE_RESULTS_1.0',results,capsules:results.filter(x=>['HARD_FAIL','FAIL'].includes(x.status)).map(x=>capsule(o,x)),blocking:results.filter(x=>x.candidateBlocking&&['HARD_FAIL','FAIL'].includes(x.status)).length};}
function selftest(){const o={current:{phase:'OPEN_PLAY',ball:{ownerId:'H-ST'},players:Array.from({length:22},(_,i)=>({id:`${i<11?'H':'A'}-${i}`,team:i<11?'HOME':'AWAY',role:i%11===0?'GK':'CM',x:i*5,y:i*3,tx:i*5,ty:i*3}))},frames:[],browser:{available:false,missing:['TRACE']}};const r=evaluate(o);if(r.results.length!==12||!r.results.every(x=>x.status))throw Error('ORACLE_SELFTEST_FAILED');return r;}
if(require.main===module){try{selftest();console.log('V42_ORACLE_RUNNER_SELFTEST_PASS');}catch(e){console.error(e.stack);process.exitCode=1;}} module.exports={evaluate,selftest,runners};
