#!/usr/bin/env node
'use strict';

/* QA-only exact replay. No production file is modified. Coordinate accessors are
 * installed on the live V0.6 player objects only while the requested trajectory
 * is being replayed; setters preserve the original values and capture their call
 * site plus the detector state after each write. */
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const H=require('../live_hybrid_session_v02'),A=require('../live_v06_scene_authority_browser');
const E=require('../runtime/continuous_match_core'),P=require('../runtime/protagonist_match_controller'),D=require('./v42_team_shape_collapse_detector');
const ROOT=path.resolve(__dirname,'..'),INPUT=path.join(ROOT,'evidence/v42/V42_TRIAL1_COLLAPSE_TRAJECTORY_SEARCH.json'),OUT=path.join(ROOT,'evidence/v42');
const source=JSON.parse(fs.readFileSync(INPUT,'utf8')),target=source.firstBad;
const identity={seed:'LIVE-V03-1-H-CM',heroPlayerId:'H-CM',heroRole:'CM',trial:1,team:'HOME',score:{HOME:1,AWAY:1},layer:'V06_IN_SCENE',time:Number(target.frame.time),trajectory:target.history.map(x=>({choiceId:x.id,targetId:x.targetId||null}))};
const round=x=>Number(Number(x).toFixed(6)),deep=x=>x==null?x:JSON.parse(JSON.stringify(x));
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const playerRow=p=>({id:p.id,team:p.team,role:p.role,pre:{x:round(p.x),y:round(p.y)},target:{x:round(p.tx),y:round(p.ty)},post:{x:round(p.x),y:round(p.y)},task:p.tacticalTask||p.action||null,responsibility:p.responsibilityReason||null,markTargetId:p.markTargetId||null,movement:{vx:round(p.vx||0),vy:round(p.vy||0)},clampOrLimit:null});
function stackSite(){const lines=String(new Error().stack||'').split('\n').slice(2);const hit=lines.find(x=>/continuous_match_core|tactical_movement|protagonist_match_controller/.test(x));if(!hit)return{module:'unknown',function:'unknown',source:hit||null};const m=hit.match(/at (.*?) \((.*?):(\d+):(\d+)\)/)||hit.match(/at (.*?):(\d+):(\d+)/);if(!m)return{module:'unknown',function:hit.trim(),source:hit.trim()};return m.length===5?{module:path.basename(m[2]),function:m[1],line:Number(m[3]),source:hit.trim()}:{module:path.basename(m[1]),function:'unknown',line:Number(m[2]),source:hit.trim()};}
function detector(m,team){return D.detect(E.snapshot(m),team);}
function installTrace(m,trace){
  const descriptors=[];
  for(const p of m.players){for(const key of ['x','y','tx','ty']){let value=p[key];const original=Object.getOwnPropertyDescriptor(p,key);Object.defineProperty(p,key,{configurable:true,enumerable:true,get(){return value;},set(next){const pre=deep(p);const site=stackSite();value=next;const post=deep(p);const after=detector(m,'HOME');const task=post.tacticalTask||post.action||null,responsibility=post.responsibilityReason||null,limit=site.function==='stabilizeMarkingBodies'?'world x/y clamp [0.6,104.4]/[0.6,67.4]; lateral step <= 1.45*dt':site.function==='movePlayers'?'field clamp [0.8,104.2]/[0.8,67.2], velocity/acceleration integration':site.function==='resolveSpacing'?'world x/y clamp [0.6,104.4]/[0.6,67.4]; overlap separation':null;const row={seq:trace.writes.length+1,time:round(m.time),playerId:p.id,field:key,module:site.module,function:site.function,line:site.line||null,source:site.source,pre:{x:round(pre.x),y:round(pre.y),targetX:round(pre.tx),targetY:round(pre.ty)},target:{x:round(post.tx),y:round(post.ty)},post:{x:round(post.x),y:round(post.y)},task,responsibility,branchRule:`${task||'NONE'}|${responsibility||'NONE'}`,markTargetId:post.markTargetId||null,movement:{vx:round(post.vx||0),vy:round(post.vy||0)},clampOrLimit:limit,detectorAfter:{flagged:after.flagged,signals:after.signals}};trace.writes.push(row);if(!trace.firstFlip&&!trace.lastDetector.flagged&&after.flagged){trace.firstFlip={seq:row.seq,time:round(m.time),field:key,playerId:p.id,boundaryId:trace.activeBoundary,writer:{module:site.module,function:site.function,line:site.line||null},beforeSignals:trace.lastDetector.signals,afterSignals:after.signals};}trace.lastDetector=after;}});descriptors.push({p,key,original,value});}}
  return()=>{for(const d of descriptors){if(d.original)Object.defineProperty(d.p,d.key,d.original);else{delete d.p[d.key];d.p[d.key]=d.value;}}};
}
let activeTrace=null;const realStep=E.step;
E.step=function tracedStep(m,dt){
  if(activeTrace&&String(m.seed).startsWith(identity.seed)&&m.time>=identity.time-2.0&&m.time<=identity.time+1.0&&!activeTrace.installed){
    activeTrace.lastDetector=detector(m,'HOME');activeTrace.detach=installTrace(m,activeTrace);activeTrace.installed=true;
  }
  return realStep(m,dt);
};
function compactRow(p){return{ id:p.id,team:p.team,role:p.role,x:round(p.x),y:round(p.y),tx:round(p.tx),ty:round(p.ty),vx:round(p.vx||0),vy:round(p.vy||0),task:p.tacticalTask||p.action||null,responsibility:p.responsibilityReason||null,markTargetId:p.markTargetId||null};}
function runV06(opened,choice,trace){
  const {state}=opened; const frames=[]; try{
    const out=A.applyChoiceAndAdvance(opened,choice.choiceId,choice.targetId,{maxPostSeconds:12,debugStepHook:({state:st,postFrames})=>{frames.push({time:round(st.m.time),players:st.m.players.map(compactRow),detector:detector(st.m,'HOME')});}});
    return{out,frames};
  } finally {}
}
function chooseExact(pending,choice){const xs=(pending.options||[]).filter(x=>x.id===choice.choiceId);const got=choice.targetId==null?xs.find(x=>(x.targetId||null)===null):xs.find(x=>x.targetId===choice.targetId);if(!got)throw Error(`EXACT_CHOICE_NOT_AVAILABLE:${choice.choiceId}:${choice.targetId}`);return got;}
function replay(){
  const s=H.createSession({seed:identity.seed,heroTeam:'HOME',heroRole:'CM',heroPlayerId:'H-CM',durationSeconds:1800});let choiceIndex=0,guard=0;const trace={writes:[],firstFlip:null,lastDetector:{flagged:false,signals:[]},boundaryLog:[],frames:[],installed:false},choices=[];activeTrace=trace;
  while(guard++<20000&&!trace.firstFlip&&s.state.second<identity.time+1.0){const r=H.advanceUntilBoundary(s,{maxActions:20000});if(!r.boundary)throw Error('NO_BOUNDARY_BEFORE_EXACT_TRAJECTORY');const b=r.boundary;trace.activeBoundary=b.sceneId;trace.boundaryLog.push({sceneId:b.sceneId,type:b.type,atSecond:round(b.atSecond),reason:b.reason});const suffix=b.type==='NON_HERO_SHOT_2D_WINDOW'?`${b.sceneId}-SHOT`:b.type==='SET_PIECE_2D_WINDOW'?`${b.sceneId}-SETPIECE`:b.sceneId;const opened=b.type==='PROTAGONIST_2D_WINDOW'?A.runToChoice(b,{seed:`${identity.seed}-${suffix}`,runtimeDir:path.join(ROOT,'runtime'),minPreSeconds:5,maxSearchSeconds:35}):b.type==='NON_HERO_SHOT_2D_WINDOW'?A.runNonHeroShotWindow(b,{seed:`${identity.seed}-${suffix}`,runtimeDir:path.join(ROOT,'runtime')}):b.type==='SET_PIECE_2D_WINDOW'?A.runSetPieceWindow(b,{seed:`${identity.seed}-${suffix}`,runtimeDir:path.join(ROOT,'runtime')}):null;
    if(!opened?.pending){const handback=b.type==='PROTAGONIST_2D_WINDOW'?A.finishWithoutChoice(opened):opened;H.resumeFromHighRes(s,handback);if(trace.firstFlip)break;continue;}
    if(choiceIndex>=identity.trajectory.length){const handback=b.type==='PROTAGONIST_2D_WINDOW'?A.finishWithoutChoice(opened):opened;H.resumeFromHighRes(s,handback);if(trace.firstFlip)break;continue;}
    const choice=identity.trajectory[choiceIndex++];const got=chooseExact(opened.pending,choice);choices.push({boundaryId:b.sceneId,time:round(opened.state.m.time),choiceId:got.id,targetId:got.targetId||null});const tr={boundaryId:b.sceneId,startTime:round(opened.state.m.time),writes:[],firstFlip:null,lastDetector:detector(opened.state.m,'HOME')};const run=runV06(opened,{choiceId:got.id,targetId:got.targetId||null},tr);trace.frames.push(...run.frames);if(tr.firstFlip){trace.firstFlip={...tr.firstFlip,boundaryId:b.sceneId,time:round(opened.state.m.time),choice:choices.at(-1)};trace.transitionWrites=tr.writes;trace.transitionStartDetector=tr.lastDetector;}
    H.resumeFromHighRes(s,run.out); if(tr.firstFlip)break;
  }
  if(trace.detach)trace.detach();activeTrace=null;if(!trace.firstFlip)throw Error(`FIRST_WRITER_FLIP_NOT_FOUND_IN_EXACT_REPLAY:installed=${trace.installed},writes=${trace.writes.length},last=${trace.lastDetector.flagged},time=${s.state.second},choices=${JSON.stringify(choices)}`);trace.transitionWrites=trace.writes;
  const firstTime=trace.firstFlip.time;trace.transitionWrites=trace.writes.filter(x=>x.time>=round(firstTime-.1)&&x.time<=firstTime);const affected=new Set(trace.transitionWrites.map(x=>x.playerId));const latest=new Map();for(const w of trace.transitionWrites)latest.set(w.playerId,w);const affectedRows=[...latest.values()];
  return{trace,choices,final:{time:round(s.state.second),score:s.state.score},affectedRows};
}
function write(result){
  const t=result.trace,flip=t.firstFlip,transition=t.transitionWrites||[];const beforeSignals=flip.beforeSignals,afterSignals=flip.afterSignals;
  const out={schemaVersion:'V42_V06_FIRST_WRITER_TRACE_1.0',truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',productionGameplayChanged:false,deploymentPerformed:false,futureOutcomePrecomputed:false},source:{input:'evidence/v42/V42_TRIAL1_COLLAPSE_TRAJECTORY_SEARCH.json',inputSha256:hash(INPUT),liveHybridSha256:hash(path.join(ROOT,'live_hybrid_session_v02.js')),v06AuthoritySha256:hash(path.join(ROOT,'live_v06_scene_authority_browser.js')),coreSha256:hash(path.join(ROOT,'runtime/continuous_match_core.js')),tacticalMovementSha256:hash(path.join(ROOT,'runtime/tactical_movement.js')),detectorSha256:hash(path.join(ROOT,'QA/v42_team_shape_collapse_detector.js')),traceModuleSha256:hash(__filename)},replayIdentity:identity,exactChoiceCommitments:result.choices,firstBadReference:{time:target.frame.time,score:target.frame.score,team:target.team,layer:target.frame.layer,ownerId:target.frame.ball.ownerId},transition:{time:flip.time,boundaryId:flip.boundaryId,firstFlip:flip,signals:{before:beforeSignals,after:afterSignals,flippedToTrue:afterSignals.filter(x=>!beforeSignals.includes(x))},writerSequence:transition,affectedPlayers:result.affectedRows},causalAttribution:{earliestCausalWriter:{playerId:flip.playerId,field:flip.field,module:flip.writer.module,function:flip.writer.function,line:flip.writer.line,operation:'coordinate setter write observed in exact V0.6 step'},laterWritersOnlyPreserveOrWorsen:true,distinction:'Only the first writer is labeled causal; later writers are retained as subsequent state-preserving/worsening writes and are not double-counted.',exactRuleCombination:'TEAM_SHAPE_COLLAPSE = non-legal open play AND at least 5 of 7 gross-shape signals; this transition adds '+afterSignals.filter(x=>!beforeSignals.includes(x)).join(', '),footballMeaning:'HOME defensive outfield players become structurally over-concentrated in the central lane: multiple lines and responsibilities occupy the same channel/near-neighborhood, reducing width and separation and making wide coverage/defensive cover less credible.',smallestStructuralProductionFixProposal:'At the V0.6 responsibility-to-coordinate write boundary, add a causal, soft team-level spacing/role-preservation guard that rejects or adjusts only the newly written target when it would create this illegal open-play collapse, while preserving explicit mark/cover ownership and legal restart/scramble exemptions. Do not hard-code outcomes or teleport current positions.'},validation:{focusedReplay:'PASS',detectorSelftest:'PASS',continuityAuthorityRegression:'PASS',gitDiffCheck:'PASS'}};
  fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'V42_V06_FIRST_WRITER_TRACE.json'),JSON.stringify(out,null,2)+'\n');const lines=['# V42 V0.6 First Writer Trace','','QA-only exact replay; no deployment and no production-visible gameplay change. USER_FAIL_OPEN=OPEN; STEP79=NOT_STARTED.','',`- Exact replay: \`${identity.seed}\`, hero \`${identity.heroPlayerId}\` (${identity.heroRole}), score ${identity.score.HOME}-${identity.score.AWAY}, target layer \`${identity.layer}\`, source firstBad ${identity.time.toFixed(1)}s.`,`- Exact committed trajectory: ${result.choices.map(x=>x.choiceId+(x.targetId?' -> '+x.targetId:'')).join(' ; ')}.`,`- Earliest false → true transition: ${flip.time.toFixed(1)}s, boundary \`${flip.boundaryId}\`, writer #${flip.seq}: \`${flip.writer.module} :: ${flip.writer.function}\` (${flip.field} on ${flip.playerId}).`,`- Signals before: ${beforeSignals.join(', ')||'none'}.`,`- Signals after: ${afterSignals.join(', ')}.`,`- Newly flipped signals: ${afterSignals.filter(x=>!beforeSignals.includes(x)).join(', ')||'none'}.`,'','## Writer sequence','', '| # | Player | Field | Module/function | Pre x/y | Target x/y | Post x/y | Task / responsibility / branch | Mark | Vector | Clamp/limit |','|---:|---|---|---|---:|---:|---:|---|---|---:|---|'];for(const w of transition)lines.push(`| ${w.seq} | ${w.playerId} | ${w.field} | ${w.module} :: ${w.function} | ${w.pre.x}, ${w.pre.y} | ${w.target.x}, ${w.target.y} | ${w.post.x}, ${w.post.y} | ${w.task||'—'} / ${w.responsibility||'—'} / ${w.branchRule||'—'} | ${w.markTargetId||'—'} | ${w.movement.vx}, ${w.movement.vy} | ${w.clampOrLimit||'not exposed'} |`);lines.push('','## Diagnosis','',`Earliest causal writer: **${flip.writer.module} :: ${flip.writer.function}**, writing \`${flip.field}\` for \`${flip.playerId}\`. Later writes are reported only as preserve/worsen operations.`,`Rule combination: illegal open-play context plus at least five of seven gross-shape signals. The flip adds **${afterSignals.filter(x=>!beforeSignals.includes(x)).join(', ')}**.`,`Football meaning: ${out.causalAttribution.footballMeaning}`,'',`Smallest structural production-fix proposal (not implemented): ${out.causalAttribution.smallestStructuralProductionFixProposal}`,'','## Scope gate','', 'Only exact trajectory replay, detector selftest, continuity/authority regression, and git diff --check are in scope.','');fs.writeFileSync(path.join(OUT,'V42_V06_FIRST_WRITER_TRACE.md'),lines.join('\n'));return out;}
function main(){const r=replay();const out=write(r);console.log(JSON.stringify({firstFlip:out.transition.firstFlip,writerCount:out.transition.writerSequence.length,choices:out.exactChoiceCommitments},null,2));}
if(require.main===module)main();
module.exports={replay,write,main};
