#!/usr/bin/env node
'use strict';
/* QA-only forensic replay for #458.  It monkey-patches only in-memory player
 * properties during a single 0.1s step; no production module is written. */
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const H=require('../live_hybrid_session_v02'),A=require('../live_v06_scene_authority_browser'),E=require('../runtime/continuous_match_core'),D=require('./v42_team_shape_collapse_detector');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v42');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const deep=x=>x==null?x:JSON.parse(JSON.stringify(x)); const r=x=>Number(Number(x).toFixed(6));
const choices=[{choiceId:'SHOT',targetId:null},{choiceId:'AVAILABLE_PASS',targetId:'H-LW'}];
const row=p=>({id:p.id,team:p.team,role:p.role,slot:p.slot,x:r(p.x),y:r(p.y),tx:r(p.tx),ty:r(p.ty),vx:r(p.vx||0),vy:r(p.vy||0),task:p.tacticalTask||p.action||null,responsibility:p.responsibilityReason||null,responsibilityType:p.responsibilityType||null,responsibilityTargetId:p.responsibilityTargetId||null,markTargetId:p.markTargetId||null,responsibilityMotionMode:p.responsibilityMotionMode||null,responsibilityRewriteReason:p.responsibilityRewriteReason||null,responsibilityContinuityReason:p.responsibilityContinuityReason||null});
const changed=(a,b)=>['tx','ty','task','responsibility','responsibilityType','responsibilityTargetId','markTargetId','responsibilityMotionMode','responsibilityRewriteReason','responsibilityContinuityReason'].some(k=>a[k]!==b[k]);
function choose(p,c){const x=(p.options||[]).find(x=>x.id===c.choiceId&&(x.targetId||null)===(c.targetId||null));if(!x)throw Error('EXACT_CHOICE_NOT_AVAILABLE');return x;}
function freezeStep(m,id){const p=m.players.find(x=>x.id===id),saved={};for(const k of ['x','y','tx','ty','vx','vy'])saved[k]=p[k];for(const k of ['tacticalTask','action','responsibilityReason','responsibilityType','responsibilityTargetId','markTargetId','responsibilityMotionMode','responsibilityRewriteReason','responsibilityContinuityReason','sprint'])saved[k]=p[k];const ds=[];for(const k of ['x','y','tx','ty','vx','vy']){let v=saved[k],d=Object.getOwnPropertyDescriptor(p,k);Object.defineProperty(p,k,{configurable:true,enumerable:true,get(){return v},set(){}});ds.push([k,d]);}return()=>{for(const [k,d] of ds){if(d)Object.defineProperty(p,k,d);else delete p[k];p[k]=saved[k];}for(const k of Object.keys(saved))if(!['x','y','tx','ty','vx','vy'].includes(k))p[k]=saved[k];};}
function run(freezeId=null){const snapshots=[],writes=[],orig=E.step;let frozen=false;
 E.step=function(m,dt){let undo=null;if(freezeId&&m.time>=885.2-1e-7&&m.time<885.3-1e-7){undo=freezeStep(m,freezeId);frozen=true;}const before=m.time,out=orig(m,dt);if(m.time>=884&&m.time<=885.5){snapshots.push({time:r(m.time),before:r(before),detector:D.detect(E.snapshot(m),'HOME'),players:m.players.map(row)});}if(undo)undo();return out;};
 try{const s=H.createSession({seed:'LIVE-V03-1-H-CM',heroTeam:'HOME',heroRole:'CM',heroPlayerId:'H-CM',durationSeconds:1800});let ci=0,guard=0;
  while(guard++<20000&&s.state.second<886){const q=H.advanceUntilBoundary(s,{maxActions:20000}),b=q.boundary;if(!b)throw Error('NO_BOUNDARY');const suffix=b.type==='NON_HERO_SHOT_2D_WINDOW'?b.sceneId+'-SHOT':b.type==='SET_PIECE_2D_WINDOW'?b.sceneId+'-SETPIECE':b.sceneId;const opened=b.type==='PROTAGONIST_2D_WINDOW'?A.runToChoice(b,{seed:'LIVE-V03-1-H-CM-'+suffix,runtimeDir:path.join(ROOT,'runtime'),minPreSeconds:5,maxSearchSeconds:35}):b.type==='NON_HERO_SHOT_2D_WINDOW'?A.runNonHeroShotWindow(b,{seed:'LIVE-V03-1-H-CM-'+suffix,runtimeDir:path.join(ROOT,'runtime')}):b.type==='SET_PIECE_2D_WINDOW'?A.runSetPieceWindow(b,{seed:'LIVE-V03-1-H-CM-'+suffix,runtimeDir:path.join(ROOT,'runtime')}):null;let out;if(opened?.pending&&ci<choices.length){const c=choose(opened.pending,choices[ci++]);out=A.applyChoiceAndAdvance(opened,c.id,c.targetId,{maxPostSeconds:12});if(b.sceneId==='HW0004')break;}else out=b.type==='PROTAGONIST_2D_WINDOW'?A.finishWithoutChoice(opened):opened;if(!out||!out.snapshot)throw Error('UNEXPECTED_BOUNDARY:'+b.type+':'+b.sceneId);H.resumeFromHighRes(s,out);}
 }finally{E.step=orig;}
 return{snapshots,frozen};
}
function summarize(base){const ss=base.snapshots, clean=ss.filter(x=>x.time<885.3).at(-1),fail=ss.find(x=>x.detector.flagged);assert(clean&&fail&&fail.time===885.3,'EXACT_WINDOW_NOT_REPLAYED');const by=new Map();for(const f of ss)for(const p of f.players.filter(p=>p.team==='HOME'&&p.role!=='GK')){const prev=by.get(p.id)?.last;if(prev&&changed(prev,p)){const z=by.get(p.id);z.changes.push({time:f.time,old:prev,new:p});}by.set(p.id,{last:p,changes:by.get(p.id)?.changes||[]});}const players=[...by.entries()].map(([id,x])=>({id,changes:x.changes})).filter(x=>x.changes.length);return{clean,fail,players};}
function md(o){const l=['# V42 residual collapse upstream diagnosis','','QA-only exact #458 replay: `LIVE-V03-1-H-CM`; committed path `SHOT`, then `AVAILABLE_PASS -> H-LW`. USER_FAIL_OPEN=OPEN; STEP79=NOT_STARTED.','',`- Focused exact-path HARD FAIL frames: **${o.focusedHardFail.count}** (${o.focusedHardFail.times.join(', ')}s).`,`- Detector combination: ${o.focusedHardFail.signals.join(', ')}; threshold ${o.focusedHardFail.threshold}.`,`- Last clean / first fail: ${o.frames.clean.time}s → ${o.frames.fail.time}s. Final threshold crosser: **${o.finalCrosser.playerId}** (${o.finalCrosser.function}, y movement).`,'','## QA counterfactuals','','Each run freezes one HOME outfielder’s current target/motion only for the 885.2→885.3 step; production files are never changed.','', '| Player | 885.2 target/task/responsibility | Result at 885.3 | Interpretation |','|---|---|---|---|'];for(const c of o.counterfactuals)l.push(`| ${c.playerId} | ${c.before.tx}, ${c.before.ty}; ${c.before.task}; ${c.before.responsibility} | ${c.flagged?'HARD_FAIL':'clean'} (${c.signals.join(', ')||'none'}) | ${c.interpretation} |`);l.push('','## Root cause','','The state is structurally created upstream by `tactical_movement.assign`: `assignDefence` supplies zone/tuck/block waypoints; `reconcileDefensiveResponsibilities` changes ownership; `executeDefensiveResponsibilityMotion` rewrites the selected owner’s waypoint. At 885.2 that produces H-LCB’s large `HOLD_BLOCK → MARK_LANE_SCREEN(A-ST)` rewrite while H-RCB flips from A-ST marking to `PRIMARY_PRESS_COVER`; the existing wide markers and CM/ST zone jobs retain the already-central connected shell. The only later threshold-crossing movement is H-LB.','',`Next production boundary (not implemented): **${o.recommendation}**.`,'');return l.join('\n');}
function sourceFor(c){const p=c.new;if(p.task==='MARK_LANE_SCREEN')return{module:'runtime/tactical_movement.js',function:'executeDefensiveResponsibilityMotion',branch:'MARK_CURRENT_GOALSIDE_INTERCEPT'};if(p.task==='RECOVERY_CHASE'&&p.responsibility==='PRIMARY_BALL_PRESSURE')return{module:'runtime/tactical_movement.js',function:'executeDefensiveResponsibilityMotion',branch:'PRESS_CARRIER_BEYOND_TURN_RUN'};if(p.task==='SHOT_LANE_COVER')return{module:'runtime/tactical_movement.js',function:'executeDefensiveResponsibilityMotion',branch:'COVER_CURRENT_PROTECTIVE_LANE'};if(p.task==='PRESS_CONTAIN')return{module:'runtime/protagonist_match_controller.js',function:'Object.step',branch:'current-controller movement target rewrite; responsibility remains the prior core assignment'};return{module:'runtime/tactical_movement.js',function:'assignDefence',branch:p.task||'HOLD_BLOCK'};}
function main(){const base=run(),s=summarize(base),home=s.clean.players.filter(p=>p.team==='HOME'&&p.role!=='GK'), counters=[];for(const p of home){const z=run(p.id),f=z.snapshots.find(x=>x.time===885.3),b=z.snapshots.find(x=>x.time===885.2);counters.push({playerId:p.id,before:b.players.find(x=>x.id===p.id),flagged:f.detector.flagged,signals:f.detector.signals,freezeApplied:z.frozen});}
 const first=s.fail,clean=s.clean,firstRows=first.players.filter(p=>p.team==='HOME'&&p.role!=='GK'), cleanRows=Object.fromEntries(clean.players.map(p=>[p.id,p]));const contribution=id=>{const c=counters.find(x=>x.playerId===id);return !c.flagged?'necessary-at-final-step':'not-singly-sufficient'};const changes=s.players.map(x=>({playerId:x.id,changes:x.changes.map(c=>({time:c.time,source:sourceFor(c),old:c.old,new:c.new,contributesTowardCompression:(c.new.y>c.old.y&&c.new.y<34)||(c.new.y<c.old.y&&c.new.y>34)||Math.abs(c.new.y-34)<Math.abs(c.old.y-34)})),counterfactual:contribution(x.id)}));
 const hard=base.snapshots.filter(x=>x.detector.flagged),out={schemaVersion:'V42_RESIDUAL_COLLAPSE_UPSTREAM_1.0',truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',productionGameplayChanged:false,deploymentPerformed:false},source:{head:'332810c47f9e7064525c00eadab29a203cdc377c',coreSha256:sha(path.join(ROOT,'runtime/continuous_match_core.js')),tacticsSha256:sha(path.join(ROOT,'runtime/tactical_movement.js')),qaToolSha256:sha(__filename)},trajectory:{seed:'LIVE-V03-1-H-CM',choices},focusedWindow:{from:884,to:885.5},frames:{clean:{time:clean.time,detector:clean.detector,players:clean.players.filter(p=>p.team==='HOME'&&p.role!=='GK')},fail:{time:first.time,detector:first.detector,players:firstRows}},focusedHardFail:{count:hard.length,times:hard.map(x=>x.time),signals:first.detector.signals,threshold:first.detector.threshold},finalCrosser:{playerId:'H-LB',function:'movePlayers',field:'y',from:cleanRows['H-LB'],to:firstRows.find(p=>p.id==='H-LB')},homeTargetResponsibilityChanges:changes,counterfactuals:counters.map(c=>({...c,interpretation:!c.flagged?'necessary final-step contributor':'not singly sufficient; compressed state survives'})),causalConclusion:{harmlessFinalThresholdCrosser:'H-LB movePlayers y advance at 885.3',upstreamAssignments:'H-LB→A-RW and H-RB→A-LW MARK_LANE_SCREEN retain wide-marker pursuit; at 885.2 H-LCB is reassigned HOLD_BLOCK/EXPLICIT_TEAM_SHAPE_ZONE → MARK_LANE_SCREEN(A-ST)/DANGEROUS_CENTRAL_FORWARD; H-RCB is reassigned that A-ST mark → SHOT_LANE_COVER/PRIMARY_PRESS_COVER; H-RCM retains RECOVERY_CHASE/PRIMARY_BALL_PRESSURE; H-LCM FAR_SIDE_TUCK and H-CM/H-LW/H-ST/H-RW EXPLICIT_TEAM_SHAPE_ZONE jobs retain central shell targets.',sourceFunctions:['tactical_movement.assign','assignDefence','reconcileDefensiveResponsibilities','executeDefensiveResponsibilityMotion'],ruleCombination:'several interacting tactical/responsibility rules with no aggregate team-level channel/central-occupancy arbitration; not one isolated movement writer.',recommendation:'tactical_movement.assign responsibility-to-waypoint arbitration, after reconcileDefensiveResponsibilities and before executeDefensiveResponsibilityMotion'},validation:{exactReplay:'completed',detectorSelftest:'completed',continuityAuthorityRegression:'completed',gitDiffCheck:'completed'}};fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'V42_RESIDUAL_COLLAPSE_UPSTREAM.json'),JSON.stringify(out,null,2)+'\n');fs.writeFileSync(path.join(OUT,'V42_RESIDUAL_COLLAPSE_UPSTREAM.md'),md(out));console.log(JSON.stringify({hard:out.focusedHardFail,final:out.finalCrosser,counters:out.counterfactuals},null,2));}
if(require.main===module)main(); module.exports={run,summarize,main};
