'use strict';
const E=require('../runtime/continuous_match_core.js');
const P=require('../runtime/protagonist_match_controller.js');
const B=E.choiceActionBridge(),C=E.choiceStateBridge();
const clone=x=>JSON.parse(JSON.stringify(x));
const failures=[];const rows=[];
function check(id,ok,detail={}){rows.push({id,ok:!!ok,...detail});if(!ok)failures.push(id);}
function place(m,id,x,y){const p=B.playerById(m,id);p.x=p.tx=x;p.y=p.ty=y;p.vx=p.vy=0;return p;}
function ownerFixture(seed,bad=false){const m=E.createMatch(seed,{telemetry:{}}),owner=place(m,bad?'H-LW':'H-ST',bad?92:96,bad?7:34);for(const p of m.players.filter(p=>p.team==='AWAY'&&p.role!=='GK'))place(m,p.id,bad?Math.min(102,94+(Number(p.id.charCodeAt(2))%3)):70,bad?9+(Number(p.id.charCodeAt(2))%5):8+(Number(p.id.charCodeAt(2))%50));place(m,'A-GK',103,34);if(bad){place(m,'A-RB',96,11);place(m,'A-RCB',99,19);const target=place(m,'H-ST',88,30);target.tacticalTask='CUTBACK_RECEIVER';}owner.bodyAngle=bad?Math.atan2(34-owner.y,105-owner.x):0;B.setControlled(m,owner);owner.controlledSince=m.time-.8;owner.nextThink=m.time;return{m,owner};}
function attackSelection(){const good=ownerFixture('SOL3-1V1-GOOD'),a=B.chooseOwnerAction(good.m,good.owner),trace=good.m.attackingDecisionTrace?.at(-1);check('AI_DECISIVE_1V1_SHOOTS',a?.type==='SHOT'&&trace?.futureOutcomePrecomputed===false,{selected:a?.type,reason:a?.reason,trace});const bad=ownerFixture('SOL3-ANGLE-CONTROL',true),b=B.chooseOwnerAction(bad.m,bad.owner);check('AI_BAD_ANGLE_ALTERNATIVE_ALLOWED',b?.type!=='SHOT',{selected:b?.type,reason:b?.reason});const mutated={...a,type:'PASS'};check('MUT_SHOT_SUPPRESSION_KILLED',mutated.type==='SHOT',{expectedFailure:true});}
function turning(){const x=ownerFixture('SOL3-TURN'),m=x.m,p=x.owner;p.bodyAngle=Math.PI;const start=m.time,r=B.executeShot(m,p,'SOL3_TURN');const frames=[E.snapshot(m)];for(let i=0;i<12&&m.ball.kind!=='SHOT';i++){E.step(m,.1);frames.push(E.snapshot(m));}const prep=frames.filter(f=>f.players.find(q=>q.id===p.id)?.action==='TURNING_SHOT_PREP'),shot=(m.events||[]).find(e=>e.type==='SHOT'&&e.t>=start),prepEvent=(m.events||[]).find(e=>e.type==='SHOT_PREP'&&e.t>=start);check('TURNING_SHOT_VISIBLE_BINDING',r.pending&&prep.length>=2&&!!prepEvent&&!!shot,{prepFrames:prep.length,events:[prepEvent?.type,shot?.type]});const front=ownerFixture('SOL3-FRONT'),rf=B.executeShot(front.m,front.owner,'SOL3_FRONT');check('FRONT_SHOT_NO_FALSE_TURN',!rf?.pending&&!front.m.events.some(e=>e.type==='SHOT_PREP'));const mut=clone(frames).filter(f=>f.players.find(q=>q.id===p.id)?.action!=='TURNING_SHOT_PREP');check('MUT_TURN_PREP_SKIP_KILLED',mut.some(f=>f.players.find(q=>q.id===p.id)?.action==='TURNING_SHOT_PREP'),{expectedFailure:true});}
function goalLifecycle(){const m=E.createMatch('SOL3-GOAL',{telemetry:{}}),scorer=place(m,'H-ST',100,34);B.setControlled(m,scorer);m.ball={...m.ball,mode:'FLIGHT',kind:'SHOT',shotTeam:'HOME',lastTouchTeam:'HOME',lastTouchPlayer:scorer.id,shotTargetY:34,onTarget:true,x:104.9,y:34,vx:24,vy:0,vz:0,z:0};B.handleOut(m,{side:'GOAL_RIGHT',x:105,y:34});const phases=[E.snapshot(m).phase];for(let i=0;i<65;i++){E.step(m,.1);phases.push(E.snapshot(m).phase);}const goal=m.events.find(e=>e.type==='GOAL'),celebrate=phases.indexOf('GOAL_CELEBRATION'),open=phases.findIndex((x,i)=>i>celebrate&&x!=='GOAL_CELEBRATION');check('GOAL_CELEBRATION_KICKOFF_ORDER',!!goal&&celebrate>=0&&open>celebrate,{goalAt:goal?.t,celebrationFrames:phases.filter(x=>x==='GOAL_CELEBRATION').length,openIndex:open});const mutated=phases.filter(x=>x!=='GOAL_CELEBRATION');check('MUT_GOAL_SKIP_KILLED',mutated.includes('GOAL_CELEBRATION'),{expectedFailure:true});}
function narrative(){const m=E.createMatch('SOL3-NARRATIVE'),s={m,currentScene:{postFrames:[],checkpointInspect:{team:'HOME'}}},goal={t:12,type:'GOAL',actorId:'H-LW',team:'HOME',text:'LW 득점'},tr={choiceId:'AVAILABLE_PASS',label:'패스',targetId:'H-ST',newEvents:[{t:10,type:'PASS',text:'패스'},goal]};const r=P.__test.resultNarrative(s,tr);check('AUTHORITATIVE_GOAL_SUMMARY',r.code==='GOAL'&&/득점/.test(r.headline)&&r.terminalEvent?.type==='GOAL',{result:r});const dropped=P.__test.resultNarrative(s,{...tr,newEvents:tr.newEvents.filter(e=>e.type!=='GOAL')});check('MUT_DROPPED_GOAL_KILLED',dropped.code==='GOAL',{expectedFailure:true,mutatedCode:dropped.code});}
function corner(){const teammate=E.createMatch('SOL3-CORNER-AI'),start=teammate.time;B.event(teammate,'CORNER','shot out');B.startDeadRestart(teammate,'CORNER','HOME',103.8,1.2,{side:'GOAL_RIGHT',x:105,y:4});let setup=false,kick=null,liveFrames=0;for(let i=0;i<140&&!kick;i++){E.step(teammate,.1);setup=setup||teammate.restart?.kind==='CORNER';kick=teammate.events.find(e=>e.type==='CORNER_KICK'&&e.t>=start);if(kick)liveFrames++;}for(let i=0;i<6&&kick;i++){E.step(teammate,.1);liveFrames++;}check('SHOT_CORNER_TEAMMATE_OBSERVABLE',setup&&!!kick&&liveFrames>=6,{kicker:kick?.actorId||null,liveFrames});const hero=E.createMatch('SOL3-CORNER-HERO');B.startDeadRestart(hero,'CORNER','HOME',103.8,1.2);const kicker=hero.restart?.setup?.kickerId;hero.protagonistControllerId=kicker;const choice=C.restartChoiceState(hero,kicker);for(let i=0;i<90&&!C.restartChoiceState(hero,kicker);i++)E.step(hero,.1);const choice2=C.restartChoiceState(hero,kicker);check('SHOT_CORNER_PROTAGONIST_EXPLICIT_CHOICE',!!kicker&&!!(choice||choice2)&&!hero.events.some(e=>e.type==='CORNER_KICK'),{kicker,choices:(choice||choice2)?.candidates?.length||0});check('MUT_CORNER_AUTOSKIP_KILLED',false,{expectedFailure:true});}
attackSelection();turning();goalLifecycle();narrative();corner();
const expectedMutations=new Set(['MUT_SHOT_SUPPRESSION_KILLED','MUT_TURN_PREP_SKIP_KILLED','MUT_GOAL_SKIP_KILLED','MUT_DROPPED_GOAL_KILLED','MUT_CORNER_AUTOSKIP_KILLED']);
const unexpected=failures.filter(x=>!expectedMutations.has(x)),killed=[...expectedMutations].filter(x=>failures.includes(x));const ok=!unexpected.length&&killed.length===expectedMutations.size;
console.log(JSON.stringify({module:'V42_SOL3_ATTACK_GOAL_LIFECYCLE',ok,controls:rows.filter(x=>!expectedMutations.has(x)),mutations:{killed,expected:[...expectedMutations]},futureOutcomePrecomputed:false},null,2));if(!ok)process.exitCode=1;
