#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Module=require('module');
const ROOT=path.resolve(__dirname,'..'),CORE=require('../runtime/continuous_match_core.js'),CTRL=require('../runtime/protagonist_match_controller.js');
const results=[];function check(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'HARD_FAIL',error:e.message});}}
function candidate(id,targetId,score,meta={}){return{id,targetId,targetName:targetId,score,meta:{targetId,...meta}};}
function frame(){const targets=[['H-LW','LW',13,5.2],['H-ST','ST',18,4.1],['H-RW','RW',14,4.8],['H-RCM','RCM',8,3.9]];const opts=targets.map(([id,slot,forward,open])=>({p:{id,slot,role:slot==='ST'?'ST':slot==='RCM'?'CM':'WF'},d:20,forward,open,block:0,score:2}));return{kind:'ON_BALL',role:'CM',team:'HOME',space:4,_frame:{owner:{id:'H-CM',team:'HOME'},opts},candidates:[candidate('SHOT',null,12),candidate('CARRY',null,11,{space:4}),candidate('TAKE_ON',null,10,{defenderDistance:2}),candidate('HOLD',null,9),...targets.flatMap(([id,slot,forward],i)=>[candidate('AVAILABLE_PASS',id,8-i,{targetSlot:slot,forward,d:20,receiverPressure:4,laneBlockers:0}),...(id==='H-LW'?[candidate('THROUGH_PASS',id,7.5,{targetSlot:slot,runLead:true,leadForward:12,leadX:76,leadY:12,receiverTravel:8})]:[])])],candidateLifecycle:[],futureOutcomePrecomputed:false};}
function assertContracts(options,f){const ids=new Set(options.map(o=>o.targetId).filter(Boolean));for(const id of ['H-LW','H-ST','H-RW','H-RCM'])assert(ids.has(id),`silent meaningful target loss: ${id}`);assert(options.some(o=>o.id==='AVAILABLE_PASS'&&o.targetId==='H-LW'),'feet pass missing');assert(options.some(o=>o.id==='THROUGH_PASS'&&o.targetId==='H-LW'),'space pass missing');assert.strictEqual(options.filter(o=>o.targetId==='H-LW').length,2,'variants not bounded');assert.strictEqual(options.filter(o=>o.recommended).length,1,'recommendation must be annotation on exactly one visible choice');assert(options.filter(o=>!o.recommended).every(o=>o.recommended===false),'alternatives changed/dimmed');assert(f.candidateLifecycle.some(x=>x.stage==='VISIBLE_OPTION_SELECTION'),'visible lifecycle absent');}
check('A target preservation and bounded variants',()=>{const f=frame(),out=CTRL.__test.onBallOptionsV42(f);assertContracts(out,f);assert(out.length<12,'choice surface unbounded');});
check('B explainable viable and excluded targets',()=>{const f=frame();f._frame.opts.push({p:{id:'H-BLOCKED',slot:'LB',role:'FB'},d:24,forward:4,open:2,block:3,score:1});const out=CTRL.__test.onBallOptionsV42(f);assert(!out.some(o=>o.targetId==='H-BLOCKED'));assert(f.candidateLifecycle.some(x=>x.targetId==='H-BLOCKED'&&x.reason==='LANE_BLOCKED'&&!x.included));});
check('C lead and feet coexist',()=>{const f=frame(),out=CTRL.__test.onBallOptionsV42(f);assert(out.some(o=>o.id==='THROUGH_PASS'&&Number.isFinite(o.meta.leadX)));assert(out.some(o=>o.id==='AVAILABLE_PASS'&&o.targetId==='H-LW'));});
check('D incoming choice during positive flight ETA',()=>{const m=CORE.createMatch('V42-SOL2-INCOMING'),hero=m.players.find(p=>p.id==='H-ST');m.time=10;m.ball={mode:'FLIGHT',x:55,y:34,z:.35,vx:14,vy:0,vz:0,ownerId:null,intendedReceiverId:hero.id,lastTouchTeam:'HOME',lastTouchPlayer:'H-CM',kind:'LONG_PASS',airborne:true,originX:55,originY:34};hero.x=72;hero.y=34;hero.vx=0;hero.vy=0;for(const p of m.players.filter(p=>p.team==='AWAY')){p.x=25;p.y=Math.max(2,Math.min(66,p.y));}const f=CORE.choiceStateBridge().inspect(m,hero.id);assert(f&&f.kind==='INCOMING_BALL');assert(m.ball.mode==='FLIGHT'&&f.eta>0&&f.eta<=1.45);const before=(m.userChoiceLog||[]).length;assert.strictEqual(m.userIncomingIntent,undefined);assert.strictEqual((m.userChoiceLog||[]).length,before);assert.strictEqual(f.futureOutcomePrecomputed,false);});
check('E recommendation presentation source',()=>{const ui=fs.readFileSync(path.join(ROOT,'in_pitch_choice_ui.js'),'utf8'),css=fs.readFileSync(path.join(ROOT,'runtime/technical_test.css'),'utf8');assert(ui.includes("badge.textContent='추천'"));assert(ui.includes("o.recommended?' recommended':''"));assert(css.includes('.in-pitch-choice-option.recommended')&&css.includes('#f2c94c'));assert(!css.includes('.in-pitch-choice-option:not(.recommended){opacity'));
});
check('F exact authority and no precommit',()=>{const f=frame(),out=CTRL.__test.onBallOptionsV42(f),pick=out.find(o=>o.targetId==='H-RW');assert.strictEqual(pick.targetId,'H-RW');assert.strictEqual(f.futureOutcomePrecomputed,false);assert(!('executedAction' in pick));});
function compileMutated(replacer){const filename=path.join(ROOT,'runtime/protagonist_match_controller.js'),src=replacer(fs.readFileSync(filename,'utf8')),mod=new Module(filename,module);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));mod._compile(src,filename);return mod.exports;}
check('MUT-A global top-six target loss is caught',()=>{const bad=compileMutated(src=>src.replace("const selected=[];","const selected=[];let __globalMutationCount=0;").replace("selected.push(...keep);","if(__globalMutationCount<2){selected.push(...keep);__globalMutationCount+=keep.length;}"));const f=frame(),out=bad.__test.onBallOptionsV42(f);assert.throws(()=>assertContracts(out,f),/silent meaningful target loss/);});
check('MUT-B stripped lead candidate is caught',()=>{const bad=compileMutated(src=>src.replace("const keep=[feet,lead].filter(Boolean);","const keep=[feet].filter(Boolean);")),f=frame(),out=bad.__test.onBallOptionsV42(f);assert.throws(()=>assertContracts(out,f),/space pass missing/);});
check('MUT-C contact-delayed incoming timing is caught',()=>{const bad=compileMutated(src=>src.replace("eta>1.35","eta>.01"));assert.strictEqual(bad.__test.readyForIncomingPause({mode:'PLAYER_ALL',m:{time:10},lastPauseAt:0}, {kind:'INCOMING_BALL',eta:.8},.7),false);assert.strictEqual(CTRL.__test.readyForIncomingPause({mode:'PLAYER_ALL',m:{time:10},lastPauseAt:0},{kind:'INCOMING_BALL',eta:.8},.7),true);});
check('MUT-D recommendation removal is caught',()=>{const f=frame(),out=CTRL.__test.onBallOptionsV42(f).map(o=>({...o,recommended:false}));assert.throws(()=>assertContracts(out,f),/recommendation/);});
const failed=results.filter(r=>r.status!=='PASS');console.log(JSON.stringify({suite:'V42_SOL2_CHOICE_PIPELINE',futureOutcomePrecomputed:false,results},null,2));if(failed.length)process.exit(1);
