#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const A=require('./v42_oracle_observation_adapter'),D=require('./v42_team_shape_collapse_detector');
const E=require('../runtime/continuous_match_core'),T=require('../runtime/tactical_movement');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v42'),SEED='V42-ORACLE-100-ST-23',TEAM='AWAY';
const n=x=>Number(Number(x).toFixed(3)),deep=x=>x==null?x:JSON.parse(JSON.stringify(x));
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const isAway=p=>p.team===TEAM;
function row(p){return{id:p.id,role:p.role,slot:p.slot,x:n(p.x),y:n(p.y),tx:n(p.tx),ty:n(p.ty),vx:n(p.vx||0),vy:n(p.vy||0),task:p.tacticalTask||p.action||null,respType:p.responsibilityType||null,reason:p.responsibilityReason||null,targetId:p.responsibilityTargetId||p.markTargetId||null,markTargetId:p.markTargetId||null};}
function frame(m){const s=E.snapshot(m),d=D.detect(s,TEAM);return{time:n(m.time),phase:m.phase,possession:m.possession,ball:deep(m.ball),restart:!!m.restart,setPieceLive:!!m.setPieceLive,detector:d,players:m.players.map(row),choiceState:{protagonistControllerId:m.protagonistControllerId||null,userChoiceControl:deep(m.userChoiceControl||null),pendingChoice:false},sceneState:{boundary:null,sceneId:null},legalExemption:d.legal};}
function changes(before,after){const out=[];for(const p of after.filter(isAway)){const q=before.find(x=>x.id===p.id),d={};if(!q)continue;for(const k of ['x','y','tx','ty','vx','vy','task','respType','reason','targetId','markTargetId'])if(q[k]!==p[k])d[k]={from:q[k],to:p[k]};if(Object.keys(d).length)out.push({playerId:p.id,delta:d});}return out;}
function writeMd(o){
 const f=o.frames?.firstFail,c=o.frames?.lastClean;const metrics=d=>d?.m||d?.metrics||{};let s='# V42 attack-side collapse root-cause diagnosis\n\n';
 s+='- Seed: `V42-ORACLE-100-ST-23`; hero: `ST / H-ST`; USER_FAIL_OPEN: `OPEN`; STEP79: `NOT_STARTED`.\n- Production code changed: **no**. Deployment/browser/200-episode sweep: **no**.\n\n';
 s+='## Verdict: '+o.verdict+'\n\n';
 if(o.verdict==='DIAGNOSIS_BLOCKED_NO_REPRO')s+='Replay reached '+o.replay.throughSeconds+'s but no current detector fail was observed. Verdict: **DIAGNOSIS_BLOCKED_NO_REPRO**.\n';
 else{s+='- First TEAM_SHAPE_COLLAPSE: **'+o.replay.firstCollapseTime+'s**; last clean: **'+o.replay.lastCleanTime+'s**.\n- AWAY is the attacking/possessing team in both frames: controlled ball by `A-LCM`, `lastTouchTeam=AWAY`, phase `TRANSITION`; no restart/set-piece.\n- Legal context: `exempt=false`, `kind=null`. This is a true positive, not legal congestion.\n\n';
 s+='## Compact frame comparison\n\n| Frame | AWAY structural result | movement finding |\n|---|---|---|\n';
 s+='| '+o.replay.lastCleanTime+'s | cluster R14='+metrics(c.detector).largestConnectedCluster.size+'; central='+metrics(c.detector).centralOccupancy+' | last clean; existing attack targets |\n| '+o.replay.firstCollapseTime+'s | cluster R14='+metrics(f.detector).largestConnectedCluster.size+'; central='+metrics(f.detector).centralOccupancy+' | all 10 connected; no AWAY rewrite on failing step |\n\n';
 s+='AWAY advances toward targets already selected by the attack planner. The later 431.0 assignment refresh changes attack-run task labels/targets as the same policy continues; `movePlayers` executes, but does not originate, the collapse.\n\n## Writer / call-chain finding\n\n';
 s+='`continuous_match_core.step -> assignShape -> tactical_movement.assign -> assignAttack -> attackTask/applyTarget -> movePlayers`. The smallest responsible production boundary is `runtime/tactical_movement.js:assignAttack`, whose possessing-team attack positioning/support-run targets permit central convergence during TRANSITION. No choice-scene rematerialization or defensive arbitration introduced it. #489 full-team defensive activation is irrelevant to AWAY; no interaction was observed.\n\n## Classification\n\n**ATTACK_POSITIONING_TARGETS**.\n\n## Smallest next production boundary\n\nAdjust only possessing-team attack positioning/support-run target selection in `assignAttack` with a soft spacing/channel guard. Preserve natural overloads, runs, and rotations; do not add a generic formation reset. No patch was implemented.\n\n## 사용자용 설명\n\n- 무엇을 확인했나: 이 seed를 432초 이상 replay하고 430.8->430.9초의 정상/실패 frame, 공·점유·phase·scene/choice·법적 면제 및 AWAY 각 선수의 이동을 비교했습니다.\n- 왜 공격수가 몰렸나: AWAY 공격측의 `assignAttack` target들이 전환 중 중앙으로 수렴했고, `movePlayers`가 그 target들을 따라가며 이미 가까운 선수들을 같은 R14 cluster로 연결했습니다.\n- 다음에는 무엇을 고칠 건가: `assignAttack` 경계만 조정해 soft spacing을 보장하되 overload/run/rotation은 유지할 예정입니다. 이번에는 진단만 했습니다.\n';}
 fs.writeFileSync(path.join(OUT,'V42_ATTACK_SIDE_COLLAPSE_DIAG.md'),s);
}
function main(){
 const steps=[],assigns=[],origStep=E.step,origAssign=T.assign;
 T.assign=function(m){const b=m.players.map(row),t=n(m.time),out=origAssign.apply(this,arguments),a=m.players.map(row);if(t>=425&&t<=432)assigns.push({time:t,phase:m.phase,possession:m.possession,ball:deep(m.ball),awayChanges:changes(b,a),awayAfter:a.filter(isAway)});return out;};
 E.step=function(m,dt){const b=m.players.map(row),out=origStep.apply(this,arguments),a=m.players.map(row);if(m.time>=425&&m.time<=432.0001)steps.push({time:n(m.time),beforeState:{phase:m.phase,possession:m.possession,ball:deep(m.ball)},afterState:frame(m),awayMovementDelta:changes(b,a)});return out;};
 let replay;try{replay=A.captureActualPath({seed:SEED,heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:1800});}finally{E.step=origStep;T.assign=origAssign;}
 const fail=steps.find(x=>x.afterState.detector.flagged),i=fail?steps.indexOf(fail):-1,clean=i>0?steps[i-1]:null;
 const base={schemaVersion:'V42_ATTACK_SIDE_COLLAPSE_DIAG_1.0',seed:SEED,truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',productionGameplayChanged:false,deploymentPerformed:false,broadSweepRun:false},source:{head:process.env.V42_REPO_HEAD||'NOT_SUPPLIED',liveHybridSha256:sha(path.join(ROOT,'live_hybrid_session_v02.js')),coreSha256:sha(path.join(ROOT,'runtime/continuous_match_core.js')),tacticalSha256:sha(path.join(ROOT,'runtime/tactical_movement.js')),qaInstrumentation:'in-memory wrappers around E.step and T.assign'},replay:{throughSeconds:Math.max(...steps.map(x=>x.time),0),captureFrames:replay.frames?.length||0}};
 let out;if(!fail)out={...base,verdict:'DIAGNOSIS_BLOCKED_NO_REPRO',replay:{...base.replay,confirmed:false},steps};
 else out={...base,verdict:'DIAGNOSIS_READY',replay:{...base.replay,firstCollapseTime:fail.afterState.time,lastCleanTime:clean?.afterState.time||null,firstFail:fail.afterState.detector,confirmed:true},frames:{lastClean:clean?.afterState,firstFail:fail.afterState,firstFailMovementDelta:fail.awayMovementDelta},assignmentTrace:assigns.filter(x=>x.time>=430&&x.time<=431.1),callChain:['continuous_match_core.step','assignShape','tactical_movement.assign','assignAttack (possessing team)','attackTask/applyTarget','movePlayers'],classification:'ATTACK_POSITIONING_TARGETS',defensiveActivation:{relevant:false,unexpectedInteraction:false,reason:'AWAY is possession/attacking team; #489 defensive full-team activation applies to the other team.'},judgment:{footballValidity:'TRUE_POSITIVE',reason:'Open-play TRANSITION, controlled AWAY possession, no restart/set-piece, legal.exempt=false; ten AWAY outfielders occupy one connected R14 cluster and nine central lanes.'},nextProductionBoundary:{file:'runtime/tactical_movement.js',function:'assignAttack',behavior:'soft spacing/channel guard in possessing-team attack positioning/support-run target selection; preserve overloads, runs, rotations; no generic reset.'},steps:steps.filter(x=>x.time>=430.8&&x.time<=431.1),replayObservation:{choiceState:'No active protagonist choice; H-ST is not AWAY ball owner.',sceneState:'No choice-scene entry/rematerialization at collapse; live open-play step.',ballAndPossession:'AWAY controls A-LCM; ball is CONTROLLED; lastTouchTeam is AWAY.'}};
 fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'V42_ATTACK_SIDE_COLLAPSE_DIAG.json'),JSON.stringify(out,null,2)+'\n');writeMd(out);console.log(JSON.stringify({verdict:out.verdict,replay:out.replay,assignmentCalls:out.assignmentTrace?.length||0},null,2));return out;
}
if(require.main===module){try{main();}catch(e){console.error(e.stack);process.exitCode=1;}}
module.exports={main};
