#!/usr/bin/env node
'use strict';

/* Final V42 closure/preflight record.  This helper records the frozen public
 * closure without changing production files or performing deployment. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..'), OUT=path.join(ROOT,'evidence/v42');
const FROZEN_HEAD='d3a8131484f9c06b99e6ee506baf788c7ab34b2a';
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const css=[...html.matchAll(/<link[^>]+rel=["']stylesheet["'][^>]+href=["']([^"']+)/gi)].map(m=>m[1]);
const js=[...html.matchAll(/<script[^>]+src=["']([^"']+)/gi)].map(m=>m[1]);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const rows=[['index.html','HTML'],...css.map(x=>[x,'CSS']),...js.map(x=>[x,'JS'])].map(([p,kind],i)=>{const b=fs.readFileSync(path.join(ROOT,p));return{order:i+1,path:p,kind,bytes:b.length,sha256:sha(b),required:true,load:'static'};});
const inlineStyle=(html.match(/<style[^>]*>([\s\S]*?)<\/style>/i)||['',''])[1];
const closure={schemaVersion:'V42_FINAL_VISIBLE_CLOSURE_1.0',sourceHead:FROZEN_HEAD,entry:'index.html',counts:{total:rows.length,HTML:1,CSS:css.length,JS:js.length,assets:0,dynamic:0},inline:{styleBytes:Buffer.byteLength(inlineStyle),scriptBytes:0,notes:'Inline style markup is part of index.html; no inline script.'},dynamicDependencies:[],files:rows,notes:['All 4 linked stylesheets are included, including runtime/technical_test.css.','No image, sprite, font, icon, manifest, import(), or page-load fetch dependency is reachable from the production user path.','The optional bug-report POST endpoint is user-triggered telemetry, not a visible page dependency.','No stale shadow file is loaded by index.html.']};
const remoteMain=null;
const oracle=require(path.join(ROOT,'evidence/v42/V42_100_EPISODE_ORACLE.json'));
const mutation=require(path.join(ROOT,'evidence/v42/V42_ORACLE_MUTATION_RESULTS.json'));
const focused={draw:require(path.join(ROOT,'evidence/v42/V42_ORACLE_DRAW_INPUT_BINDING.json')),kickoff:require(path.join(ROOT,'evidence/v42/V42_KICKOFF_PREVIEW_LIVE_STATE_REPAIR.json'))};
const preflight={sourceHead:FROZEN_HEAD,branch:'codex/v42-stabilization-oracle-implementation',requiredHeadMatches:true,closureGeneratedFrom:'actual FLR_DEV index.html',hash436:focused.draw.verdict,hash437:focused.kickoff.verdict,oracle438:{disposition:oracle.disposition,evidenceSourceHead:oracle.source.head,evidenceRequiredHead:oracle.source.requiredHead,counts:{total:oracle.summary.total,CLEAN:oracle.summary.CLEAN,HARD_FAIL:oracle.summary.HARD_FAIL,FAIL:oracle.summary.FAIL,TRUE_WATCH:oracle.summary.TRUE_WATCH},boundToFrozenHead:oracle.source.head===FROZEN_HEAD&&oracle.source.requiredHead===FROZEN_HEAD},mutationHarness:{allCoreKilled:mutation.allCoreKilled},syntaxJsonDiffCheck:'PASS',flrTest:{checkoutPresent:fs.existsSync('/home/hong/Dev/FLR_TEST'),mainBeforeDeployment:remoteMain||null,mainBeforeDeploymentStatus:'REMOTE_UNAVAILABLE; no local checkout',writePerformed:false},disposition:'V42_FINAL_PREFLIGHT_FAILED',blockers:['#438 evidence/runner source metadata is bound to 6b3fd3ee40af657178a193436350b4f62f2d0f05, not required frozen HEAD d3a8131484f9c06b99e6ee506baf788c7ab34b2a.','Deployment was prohibited by Phase B; repository and hosted byte identity were not attempted.'],truth:{USER_FAIL_OPEN:'OPEN',STEP79:'NOT_STARTED',userPass:false,productionGameplayChanged:false}};
fs.mkdirSync(OUT,{recursive:true});
fs.writeFileSync(path.join(OUT,'V42_FINAL_VISIBLE_CLOSURE.json'),JSON.stringify(closure,null,2)+'\n');
fs.writeFileSync(path.join(OUT,'V42_FINAL_HOSTED_VALIDATION.json'),JSON.stringify({schemaVersion:'V42_FINAL_HOSTED_VALIDATION_1.0',disposition:preflight.disposition,closure,preflight,repositoryIdentity:{attempted:false,mismatchCount:null,omissions:null},hostedHttp:{status:'NOT_ATTEMPTED_PREDEPLOY_BLOCK',mismatchCount:null,missing:[],mimeFailures:[]},unproven:['canvas rasterization/pixels','CSS/layout rendering','browser event timing','real hosted HTTP payload'],answers:{flrDevFrozenHead:FROZEN_HEAD,flrTestMainBeforeDeployment:remoteMain||'NOT_INDEPENDENTLY_AVAILABLE',flrTestMainAfterDeployment:null,closureFileCount:closure.counts,requiredRepoMismatches: null,hostedHttpMismatches:null,runtimeTechnicalTestCss:{path:'runtime/technical_test.css',bytes:rows.find(x=>x.path==='runtime/technical_test.css').bytes,sha256:rows.find(x=>x.path==='runtime/technical_test.css').sha256,inClosure:true,current:true},hash436:focused.draw.verdict,hash437:focused.kickoff.verdict,oracle438:preflight.oracle438,remainingUnproven:['canvas rasterization','CSS/layout rendering','browser event timing','hosted HTTP identity'],userFailOpen:'OPEN',step79:'NOT_STARTED'},notes:['No FLR_TEST write, commit, or push occurred because Phase B failed.','This evidence does not claim user-visible PASS.']},null,2)+'\n');
const md=`# V42 Final Hosted Validation\n\nDisposition: **${preflight.disposition}**\n\n## Gate result\n\nThe exact frozen FLR_DEV HEAD is \`${FROZEN_HEAD}\`. The predeploy gate is blocked because the rerun #438 output remains source-bound to \`${oracle.source.head}\` / \`${oracle.source.requiredHead}\`, not the required HEAD. Its observed counts are nevertheless 100 total, 100 CLEAN, 0 HARD_FAIL, 0 FAIL, and 0 TRUE_WATCH.\n\nNo FLR_TEST write, commit, push, or hosted request was performed.\n\n## Complete visible closure\n\nThe actual current \`index.html\` resolves ${rows.length} static files: 1 HTML, ${css.length} CSS, ${js.length} JS, 0 assets, and 0 page-load dynamic file dependencies. \`runtime/technical_test.css\` is included exactly (${rows.find(x=>x.path==='runtime/technical_test.css').bytes} bytes, SHA-256 \`${rows.find(x=>x.path==='runtime/technical_test.css').sha256}\`). Inline CSS is retained in \`index.html\`; inline script bytes are zero.\n\nFull ordered rows and hashes are in \`V42_FINAL_VISIBLE_CLOSURE.json\`.\n\n## Required answers\n\n1. FLR_DEV frozen source HEAD: \`${FROZEN_HEAD}\`.\n2. FLR_TEST main before deployment: ${remoteMain?`\`${remoteMain}\` (remote ref read independently)`:'not independently available'}; no local checkout is present.\n3. FLR_TEST main after deployment: not applicable; deployment was not attempted.\n4. Closure: ${rows.length} files — HTML 1 / CSS ${css.length} / JS ${js.length} / assets 0 / dynamic 0.\n5. Required repository mismatches/omissions: not applicable; no sync occurred.\n6. Hosted HTTP mismatches/404/MIME: not tested; predeploy blocked.\n7. \`runtime/technical_test.css\`: exact current FLR_DEV closure member; deployment identity not proven.\n8. #436: ${focused.draw.verdict}. #437: ${focused.kickoff.verdict}.\n9. #438: clean counts are 100 CLEAN / 0 HARD_FAIL / 0 FAIL / 0 TRUE_WATCH, but source binding is invalid for this task.\n10. Unproven: canvas rasterization/pixels, CSS/layout rendering, browser event timing, and hosted HTTP byte identity.\n\nUSER_FAIL_OPEN remains OPEN; STEP79 remains NOT_STARTED; no user PASS and no new Worker.\n`;
fs.writeFileSync(path.join(OUT,'V42_FINAL_HOSTED_VALIDATION.md'),md);
console.log(JSON.stringify({disposition:preflight.disposition,closure:closure.counts,oracle438:preflight.oracle438,flrTestMainBeforeDeployment:remoteMain},null,2));
