#!/usr/bin/env node
'use strict';
/* TEST_ONLY bounded capture and blind-first cross-check export. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {captureActualPath}=require('./v42_oracle_observation_adapter');
const {evaluate}=require('./v43_causal_plausibility_detector');
const Shape=require('./v42_team_shape_collapse_detector');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v43');
const calibrationCases=[
 {id:'CALIBRATION_1',historicalLabel:'Case 1',seed:'V42-ORACLE-100-CB-20',heroRole:'CB',heroPlayerId:'H-LCB',judgmentTime:381.6},
 {id:'CALIBRATION_2',historicalLabel:'Case 2',seed:'V42-ORACLE-100-ST-23',heroRole:'ST',heroPlayerId:'H-ST',judgmentTime:430.9},
 {id:'CALIBRATION_3',historicalLabel:'Case 3',seed:'V42-ORACLE-100-CM-13',heroRole:'CM',heroPlayerId:'H-CM',judgmentTime:29.2}
];
const fresh=[['ST','H-ST','V43-CAUSAL-FRESH-ST-01'],['ST','H-ST','V43-CAUSAL-FRESH-ST-02'],['ST','H-ST','V43-CAUSAL-FRESH-ST-03'],['ST','H-ST','V43-CAUSAL-FRESH-ST-04'],['CM','H-CM','V43-CAUSAL-FRESH-CM-01'],['CM','H-CM','V43-CAUSAL-FRESH-CM-02'],['CM','H-CM','V43-CAUSAL-FRESH-CM-03'],['CM','H-CM','V43-CAUSAL-FRESH-CM-04'],['CB','H-LCB','V43-CAUSAL-FRESH-CB-01'],['CB','H-LCB','V43-CAUSAL-FRESH-CB-02'],['CB','H-LCB','V43-CAUSAL-FRESH-CB-03'],['CB','H-LCB','V43-CAUSAL-FRESH-CB-04']];
const r3=x=>+Number(x).toFixed(3),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
function frames(spec){const o=captureActualPath({...spec,durationSeconds:1800}),out=[...(o.lowResPreFrames||[]),...(o.frames||[])].filter(f=>f.players?.length===22&&Number.isFinite(+f.time)).sort((a,b)=>a.time-b.time);if(!out.length)throw Error(`NO_REAL_FRAMES:${spec.seed}`);return out;}
function exportFrame(f){return{time:r3(f.time),phase:f.phase||null,score:f.score||null,possession:f.possession||null,ball:f.ball||null,players:f.players,teamShape:{HOME:Shape.detect(f,'HOME').flagged,AWAY:Shape.detect(f,'AWAY').flagged}};}
function near(fs,time){return fs.reduce((a,f)=>Math.abs(f.time-time)<Math.abs(a.time-time)?f:a,fs[0]);}
function hasIssueAt(report,time){return report.issues.some(x=>Math.abs(x.at-time)<.051);}
function teamShapeAt(f){return Shape.detect(f,'HOME').flagged||Shape.detect(f,'AWAY').flagged;}
function selectedIssues(report,selected){return report.issues.filter(x=>selected.some(f=>Math.abs(f.time-x.at)<.051));}
function cleanSegment(fs,report){let best=[],run=[];for(const f of fs){if(hasIssueAt(report,f.time)){run=[];continue}run.push(f);if(run.length>best.length)best=run.slice();}return best.length>=8?best.slice(0,Math.min(best.length,25)):null;}
function problematicSegment(fs,report){for(const issue of report.issues){const center=near(fs,issue.at),i=fs.indexOf(center),selected=fs.slice(Math.max(0,i-12),Math.min(fs.length,i+13));if(selected.length>=8&&selectedIssues(report,selected).length)return{selected,issue};}return null;}
function internal(report,selected,classification){const issues=selectedIssues(report,selected);return{classification,reasons:classification==='INTERNALLY_PROBLEMATIC'?[...new Set(issues.map(x=>`${x.category}: ${x.reason}`))].slice(0,5):['선택된 창에서 인과 검출기와 기존 팀-형상 레이어 모두 문제 신호를 내지 않았습니다.'],detectorCategories:[...new Set(issues.map(x=>x.category))],limitations:['관찰 프레임과 현재 책임 telemetry에 기반한 TEST_ONLY 판정이며, 숨은 전술 지시·카메라·브라우저 픽셀은 증명하지 않는다.','FB의 CB 대비 높이/안쪽 위치 자체는 신호가 아니다. 노출 위협·커버·핸드오프·상위 우선순위가 함께 없을 때만 문제로 본다.']};}
function scene(id,spec,fs,report,selected,classification,kind){const judge=selected[Math.floor(selected.length/2)],issues=selectedIssues(report,selected),sceneFirst=issues.length?Math.min(...issues.map(x=>x.at)):null;return{id,label:`Case ${id}`,seed:spec.seed,heroRole:spec.heroRole,heroPlayerId:spec.heroPlayerId,frames:selected.map(exportFrame),sceneFirstCausalFlag:{inSelectedWindow:sceneFirst==null?null:r3(sceneFirst),elsewhereInFullCapture:report.firstFlagTime!=null&&(!sceneFirst||report.firstFlagTime<sceneFirst-.05)?r3(report.firstFlagTime):null},userJudgmentFrame:{actualFrameTime:r3(judge.time),causalFlagged:hasIssueAt(report,judge.time),teamShapeFlagged:teamShapeAt(judge)},internal:internal(report,selected,classification),_testOnlyKind:kind};}
function rankDistinct(candidates){const roles=new Set(),categories=new Set(),out=[];for(const x of candidates){const category=x.issue?.category||null;if(out.length<2&&(!roles.has(x.spec.heroRole)||!categories.has(category))){out.push(x);roles.add(x.spec.heroRole);if(category)categories.add(category);}}for(const x of candidates)if(out.length<2&&!out.includes(x))out.push(x);return out;}
function htmlSmoke(){const v=fs.readFileSync(path.join(OUT,'user_viewer/index.html'),'utf8');if(!v.includes('userCrossCheckCases')||!v.includes('current.internal')||v.includes("x.cases.map(c=>`<button"))throw Error('VIEWER_NOT_BALANCED_CROSSCHECK_COMPATIBLE');}
function reportMarkdown(out){const detail=c=>`### ${c.historicalLabel||c.label}\n\n- seed: \`${c.seed}\`\n- role: ${c.heroRole}\n- internal classification: ${c.internal.classification}\n- selected-window first causal flag: ${c.sceneFirstCausalFlag.inSelectedWindow??'none'}\n- full-capture issue elsewhere: ${c.sceneFirstCausalFlag.elsewhereInFullCapture??'none'}\n- judgment frame: ${c.userJudgmentFrame.actualFrameTime}s; causal=${c.userJudgmentFrame.causalFlagged}; team-shape=${c.userJudgmentFrame.teamShapeFlagged}\n- categories: ${c.internal.detectorCategories.join(', ')||'none'}\n- reason: ${c.internal.reasons.join(' | ')}\n- limitation: ${c.internal.limitations.join(' | ')}`;return `# V43 causal validation cross-check (TEST_ONLY)\n\n${out.koreanAggregateSummary}\n\n- HEAD: \`${out.source.head}\`\n- Production/runtime mutation: false; FLR_TEST deployment: false; USER_VISIBLE_PROVEN: false; gameplay PASS: false.\n\n## User-facing blind cross-check set\n\nThe viewer consumes only \`userCrossCheckCases\`; its pre-judgment labels are neutral sequential labels. Internal fields are revealed only after that case has been judged.\n\n${out.userCrossCheckCases.map(detail).join('\n\n')}\n\n## Historical calibration/regression only (not userCrossCheckCases)\n\n${out.calibrationResults.map(detail).join('\n\n')}\n\n## Worker comment — internal exact fresh user-facing case list\n\n${out.userCrossCheckCases.map(c=>`- ${c.label}: ${c.internal.classification}; seed=\`${c.seed}\`; role=${c.heroRole}; categories=${c.internal.detectorCategories.join(', ')||'none'}`).join('\n')}\n`;}
function main(){
 const head=process.env.V43_SOURCE_HEAD||'NOT_SUPPLIED';if(head==='NOT_SUPPLIED')throw Error('V43_SOURCE_HEAD_REQUIRED');
 const calibrationResults=calibrationCases.map(c=>{const fs=frames(c),report=evaluate(fs),center=near(fs,c.judgmentTime),i=fs.indexOf(center),selected=fs.slice(Math.max(0,i-12),Math.min(fs.length,i+13));const s=scene(c.id.replace('CALIBRATION_',''),c,fs,report,selected,'INTERNALLY_PROBLEMATIC','CALIBRATION');s.historicalLabel=c.historicalLabel;return s;});
 const pool=fresh.map(([heroRole,heroPlayerId,seed])=>{const spec={heroRole,heroPlayerId,seed},fs=frames(spec),report=evaluate(fs);return{spec,fs,report,plausible:cleanSegment(fs,report),problematic:problematicSegment(fs,report)};});
 const plausible=rankDistinct(pool.filter(x=>x.plausible)).map(x=>({...x,selected:x.plausible}));
 const problematic=rankDistinct(pool.filter(x=>x.problematic).map(x=>({...x,selected:x.problematic.selected,issue:x.problematic.issue})));
 if(plausible.length<2)throw Error('FRESH_SAMPLE_HAS_FEWER_THAN_TWO_PLAUSIBLE_WINDOWS');
 if(problematic.length<2)throw Error('FRESH_SAMPLE_HAS_FEWER_THAN_TWO_PROBLEMATIC_WINDOWS');
 const raw=[...plausible.map(x=>({x,classification:'INTERNALLY_PLAUSIBLE'})),...problematic.map(x=>({x,classification:'INTERNALLY_PROBLEMATIC'}))];
 const userCrossCheckCases=raw.map(({x,classification},i)=>scene(i+1,x.spec,x.fs,x.report,x.selected,classification,'FRESH'));
 for(const c of userCrossCheckCases){if(c.frames.length<8||c.frames.some(f=>f.players.length!==22))throw Error(`INVALID_22_PLAYER_EXPORT:${c.label}`);if(c.internal.classification==='INTERNALLY_PLAUSIBLE'&&(c.sceneFirstCausalFlag.inSelectedWindow!==null||c.userJudgmentFrame.causalFlagged||c.userJudgmentFrame.teamShapeFlagged))throw Error(`PLAUSIBLE_WINDOW_NOT_CLEAN:${c.label}`);if(c.internal.classification==='INTERNALLY_PROBLEMATIC'&&c.sceneFirstCausalFlag.inSelectedWindow===null)throw Error(`PROBLEMATIC_WINDOW_NOT_DETECTOR_FIRED:${c.label}`);}
 const counts={plausible:userCrossCheckCases.filter(c=>c.internal.classification==='INTERNALLY_PLAUSIBLE').length,problematic:userCrossCheckCases.filter(c=>c.internal.classification==='INTERNALLY_PROBLEMATIC').length};if(counts.plausible<2||counts.problematic<2)throw Error('BALANCED_FRESH_THRESHOLD_NOT_MET');
 const out={schemaVersion:'V43_CAUSAL_VALIDATION_CROSSCHECK_2.0',testOnly:true,truth:{USER_FAIL_OPEN:'OPEN',productionGameplayChanged:false,deploymentPerformed:false,FLR_TESTDeployed:false,userVisibleProven:false,gameplayPass:false,futureOutcomePrecomputed:false},source:{head,capture:'real Hybrid -> V0.6 current-engine frames',runtimeFilesChanged:false,detectorSha256:sha(path.join(ROOT,'QA/v43_causal_plausibility_detector.js')),fixturesSha256:sha(path.join(ROOT,'QA/v43_causal_fixture_test.js'))},sample:{boundedFreshCurrentEngine:{requested:fresh.length,captured:fresh.length,roleCoverage:[...new Set(pool.map(x=>x.spec.heroRole))],selectionRule:'fresh problematic: detector fires in selected window; fresh plausible: no causal issue in selected window and no team-shape flag at judgment frame'},calibration:'CB-20/ST-23/CM-13 retained only as historical calibration/regression evidence; excluded from userCrossCheckCases'},userCrossCheckCases,calibrationResults,koreanAggregateSummary:'내부 검증 전용 교차검증: 사용자 화면에는 새 현재 엔진 캡처만 중립 Case 라벨로 제시됩니다. 역사적 CB-20/ST-23/CM-13은 보정·회귀 증거로만 분리됩니다. 판정 전에는 seed, 역할, 내부 분류, 검출 종류와 장면 성격을 공개하지 않습니다. 이는 사용자 가시 검증 또는 게임플레이 PASS 선언이 아닙니다.'};
 fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'V43_CAUSAL_VALIDATION_CROSSCHECK_DATA.json'),JSON.stringify(out,null,2)+'\n');fs.writeFileSync(path.join(OUT,'V43_CAUSAL_VALIDATION_CROSSCHECK.md'),reportMarkdown(out));htmlSmoke();console.log(JSON.stringify({head,freshUserFacing:userCrossCheckCases.map(c=>({label:c.label,classification:c.internal.classification,seed:c.seed,role:c.heroRole,firstInWindow:c.sceneFirstCausalFlag.inSelectedWindow,judgment:c.userJudgmentFrame,categories:c.internal.detectorCategories})),counts},null,2));return out;
}
if(require.main===module)main();module.exports={main};
