#!/usr/bin/env node
'use strict';
/* TEST_ONLY: fresh actual-engine frame export for the two V43 visual blockers. */
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {captureActualPath}=require('./v42_oracle_observation_adapter');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'evidence/v43/focused_round2'),MAX_SPEED=13;
const SPECS=[
 {id:'FOCUSED_1',seed:'V43-R2-SEARCH-01',from:9,to:27,heroRole:'ST',heroPlayerId:'H-ST',scene:'ordinary'},
 {id:'FOCUSED_2',seed:'V43-R2-SEARCH-03',from:138,to:165,heroRole:'ST',heroPlayerId:'H-ST',scene:'ordinary'},
 {id:'FOCUSED_3',seed:'V43-R2-SEARCH-05',from:553.3,to:556.7,heroRole:'ST',heroPlayerId:'H-ST',scene:'fullback-transition'},
 {id:'FOCUSED_4',seed:'V43-R2-SEARCH-08',from:103.7,to:107,heroRole:'ST',heroPlayerId:'H-ST',scene:'fullback-transition'}
];
const r3=n=>+Number(n).toFixed(3),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function capture(spec){const raw=captureActualPath({...spec,durationSeconds:1800}),all=[...(raw.lowResPreFrames||[]),...(raw.frames||[])].filter(f=>f.players?.length===22&&Number.isFinite(f.time)).sort((a,b)=>a.time-b.time);const unique=[];for(const f of all)if(!unique.length||f.time>unique.at(-1).time+1e-6)unique.push(f);const selected=unique.filter(f=>f.time>=spec.from-1e-6&&f.time<=spec.to+1e-6);assert(selected.length>=4,`${spec.id}: insufficient actual source frames`);return selected;}
function continuity(frames){let minDt=Infinity,maxDt=0,maxMove=0,maxSpeed=0;for(let i=1;i<frames.length;i++){const dt=frames[i].time-frames[i-1].time;assert(dt>0,'SOURCE_TIMESTAMP_NONMONOTONIC');minDt=Math.min(minDt,dt);maxDt=Math.max(maxDt,dt);for(const p of frames[i].players){const q=frames[i-1].players.find(x=>x.id===p.id);assert(q,'SOURCE_PLAYER_ID_DISCONTINUITY');const move=dist(p,q),speed=move/dt;maxMove=Math.max(maxMove,move);maxSpeed=Math.max(maxSpeed,speed);assert(speed<=MAX_SPEED,`SOURCE_SPEED_IMPLAUSIBLE:${p.id}:${speed}`);}}return{minSourceDt:r3(minDt),maxSourceDt:r3(maxDt),maxPlayerDisplacement:r3(maxMove),maxPlayerSpeed:r3(maxSpeed),speedLimit:MAX_SPEED};}
function exportFrame(f){return{time:r3(f.time),phase:f.phase||null,score:f.score||null,possession:f.possession||null,ball:f.ball||null,players:f.players.map(p=>({id:p.id,team:p.team,role:p.role,x:r3(p.x),y:r3(p.y),vx:r3(p.vx||0),vy:r3(p.vy||0),action:p.action||null,responsibility:p.responsibility||null,markTargetId:p.markTargetId||null}))};}
function sha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function inProcessHead(){const git=path.join(ROOT,'.git'),head=fs.readFileSync(path.join(git,'HEAD'),'utf8').trim();if(/^[0-9a-f]{40}$/i.test(head))return head;const ref=head.replace(/^ref:\s*/,'');const refPath=path.join(git,ref);if(fs.existsSync(refPath))return fs.readFileSync(refPath,'utf8').trim();const packed=fs.readFileSync(path.join(git,'packed-refs'),'utf8').split(/\r?\n/).find(x=>x.endsWith(' '+ref));return packed?.split(' ')[0]||'UNRESOLVED_GIT_HEAD';}
function sourceIdentity(){const files=['runtime/continuous_match_core.js','runtime/tactical_movement.js','QA/v42_oracle_observation_adapter.js','QA/v43_focused_user_test_runner.js','evidence/v43/user_viewer/index.html'];const manifest=files.map(file=>({path:file,sha256:sha(path.join(ROOT,file)),bytes:fs.statSync(path.join(ROOT,file)).size}));return{gitHead:inProcessHead(),identityMethod:'IN_PROCESS_GIT_REF_AND_CONTENT_MANIFEST',manifest,manifestSha256:crypto.createHash('sha256').update(JSON.stringify(manifest)).digest('hex')};}
function main(){const cases=SPECS.map((spec,i)=>{const frames=capture(spec),gate=continuity(frames),hasFb=spec.scene==='fullback-transition';if(hasFb){assert(frames.some(f=>f.players.some(p=>p.role==='FB'&&/OVERLAP|UNDERLAP|INVERT/.test(p.action||''))),`${spec.id}: no actual FB advance`);assert(frames.some(f=>f.players.some(p=>p.role==='CB'&&/REST_DEFENCE|COVER/.test(p.action||''))),`${spec.id}: no compensating CB cover`);}return{id:spec.id,label:`Case ${i+1}`,seed:spec.seed,heroRole:spec.heroRole,heroPlayerId:spec.heroPlayerId,frames:frames.map(exportFrame),mechanicalContinuity:gate};});
 const out={schemaVersion:'V43_FORMATION_RESPONSIBILITY_FOCUSED_USER_TEST_1.0',testOnly:true,truth:{USER_VISIBLE_PROVEN:false,gameplayPass:false,deploymentPerformed:false,FLR_TESTDeployed:false,futureOutcomePrecomputed:false},source:{...sourceIdentity(),actualEngineFramesOnly:true,noSyntheticCoordinates:true,selection:'fresh neutral scenes; ordinary play plus observed FB advance with current-state CB rest-defense compensation; not detector-class balanced'},userCrossCheckCases:cases,mechanicalContinuity:{hardGate:'PASS',cases:cases.map(c=>({label:c.label,...c.mechanicalContinuity}))},koreanAggregateSummary:'V43 Round 2 TEST_ONLY: 현재 엔진의 실제 프레임만 사용한 새 장면입니다. 판정 전에는 seed·내부 분류·검출 정보를 공개하지 않습니다.'};
 fs.mkdirSync(path.join(OUT,'user_viewer'),{recursive:true});fs.writeFileSync(path.join(OUT,'V43_FORMATION_RESPONSIBILITY_FOCUSED_USER_TEST.json'),JSON.stringify(out,null,2)+'\n');fs.writeFileSync(path.join(OUT,'V43_FORMATION_RESPONSIBILITY_FOCUSED_USER_TEST.md'),`# V43 Round 2 focused user test (TEST_ONLY)\n\nUSER_VISIBLE_PROVEN=false; gameplay PASS=false; deployment=false. Four fresh actual-engine scenes passed the source timestamp/position continuity HARD gate.\n\n${cases.map(c=>`- ${c.label}: ${c.mechanicalContinuity.minSourceDt}s–${c.mechanicalContinuity.maxSourceDt}s source dt; max ${c.mechanicalContinuity.maxPlayerDisplacement}m / ${c.mechanicalContinuity.maxPlayerSpeed}m/s.`).join('\n')}\n`);
 const viewer=fs.readFileSync(path.join(ROOT,'evidence/v43/user_viewer/index.html'),'utf8').replace('../../index.html?flr_v43_user_viewer=1','../../../index.html?flr_v43_user_viewer=1').replace('href="user_viewer.css"','href="user_viewer.css"').replace('../V43_CAUSAL_VALIDATION_CROSSCHECK_DATA.json','../V43_FORMATION_RESPONSIBILITY_FOCUSED_USER_TEST.json');fs.writeFileSync(path.join(OUT,'user_viewer/index.html'),viewer);fs.copyFileSync(path.join(ROOT,'evidence/v43/user_viewer/user_viewer.css'),path.join(OUT,'user_viewer/user_viewer.css'));console.log(JSON.stringify({module:'V43_FOCUSED_USER_TEST_RUNNER',verdict:'PASS',cases:cases.map(c=>({label:c.label,...c.mechanicalContinuity}))},null,2));return out;}
if(require.main===module)main();module.exports={main};
