#!/usr/bin/env node
'use strict';

const crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process');
const ROOT=path.resolve(__dirname,'..'),SOURCE_ROOT=process.env.FLR_SOURCE_ROOT||ROOT;
const PARENT='4308bd60fc8ff3ab9c861be96657c88af75f9a99',PARENT_TREE='2433403c49221297fe864b31d7834eb48594e368';
const OUT=path.join(ROOT,'evidence/v52/legacy_spatial_authority_v2_step4_1308.json');
const ALLOWED=new Set([
  'runtime/continuous_spatial_authority_v2.js','runtime/continuous_match_core.js','runtime/tactical_movement.js','runtime/protagonist_match_controller.js',
  'runtime/take_on_duel.js','live_hybrid_session_v02.js','live_v06_scene_authority_browser.js',
  'QA/v52_legacy_spatial_authority_v2_step4_defensive_contact.js','evidence/v52/legacy_spatial_authority_v2_step4_1308.json'
]);
const RECOVERED_HASHES={
  'runtime/continuous_spatial_authority_v2.js':'eed19cfc6323783920d77984f87412f33ca6db4b73f785812da196b9bc419e60',
  'runtime/continuous_match_core.js':'61d2993dec98b9a946ea14ac940261ad3b76590ba4d5cc1aa93b369a93cea38b',
  'runtime/tactical_movement.js':'810c60ea03e763907377ef8b714bee15572e1a4d66d19be293662cd335b4c744',
  'live_hybrid_session_v02.js':'ead20e4a668fa3f8e75a34b092f4d12da178ed9f380f9a18bcfe16bbd3814dd8'
};
// Exact, audited post-recovery production tails.  A filename alone never authorizes drift.
const AUTHORIZED_TAIL_HASHES={
  'runtime/continuous_spatial_authority_v2.js':'47335ac20d3e4b84700274da075365390261abd794c39b879dfe5a02cab7faf4',
  'runtime/continuous_match_core.js':'f479b9ed444fa6f1f63a2a74f275216de2647adc8b297a0fe9de3148ca007db7'
};
const AUTHORIZED_TAIL_REASONS={
  'runtime/continuous_spatial_authority_v2.js':'Authorized post-recovery spatial-authority tail: per-step defensive-responsibility handoff prevents an expired PRESS lease from overlapping its newly selected successor.',
  'runtime/continuous_match_core.js':'Authorized post-recovery core tail: explicit user commit-event linkage.'
};
const UNCHANGED_STEP3_HASHES={'runtime/protagonist_match_controller.js':'4da604970e4d65de97157a9a6c7bfcb8627a591986aad8260970ec85adfa6cb6','runtime/take_on_duel.js':'0fda708e61580fb97d91cb9f96e19e9fe3e08191edf48938e9be15e03302cc0e','live_v06_scene_authority_browser.js':'b047587854b934a1e6a66f595e90a6cf534b9a4ece5ed4fd45ca912acc4fffa0'};
const RECOVERY_CLASSIFICATION={
  A:{classification:'RECOVERED_PARTIAL',recovered:['continuous_match_core.finalizeMovementDestinations','continuous_spatial_authority_v2.sealCoarseMovementIntents','finalMovementIntent','movementIntentArbiter'],tail:'derive writer/consumption proof instead of trusting the declared zero counter'},
  B:{classification:'RECOVERED_PARTIAL',recovered:['continuous_spatial_authority_v2.coarseDefensivePlan','continuous_spatial_authority_v2.coarseMarkBandPoint','tactical_movement.executeDefensiveResponsibilityMotion','responsibilityDistanceBand'],tail:'add central-CB, wide-threat, goal-side/lane/band and handoff gates'},
  C:{classification:'RECOVERED_PARTIAL',recovered:['proposalFor PRESS/COVER/RECOVERY','executeDefensiveResponsibilityMotion'],tail:'directly prove PRESS contact, COVER lane, RECOVERY shape and no mass chase'},
  D:{classification:'RECOVERED_COMPLETE',recovered:['continuous_spatial_authority_v2.resolveCausalContact','live_hybrid_session_v02.doActionV2'],tail:'replace the indirect high-resolution-only fixture with direct recovered coarse-contact coverage'},
  E:{classification:'REQUIRES_QA_ONLY',recovered:['Step3 applyChoice/applyChoiceAndAdvance exact choiceId + targetId boundary'],tail:'retain rejection/no-mutation/no-auto/no-precompute checks and connect external contact consequence'},
  F:{classification:'RECOVERED_PARTIAL',recovered:['same-tick coarse RECOVERY','_shapeContinuityIntent','responsibilityContinuityReason'],tail:'prove responsibility release and causal handoff for field-role groups'}
};
const H=require(path.join(SOURCE_ROOT,'live_hybrid_session_v02'));
const V=require(path.join(SOURCE_ROOT,'live_v06_scene_authority_browser'));
const S=require(path.join(SOURCE_ROOT,'runtime/continuous_spatial_authority_v2'));
const E=require(path.join(SOURCE_ROOT,'runtime/continuous_match_core'));
const T=require(path.join(SOURCE_ROOT,'runtime/tactical_movement'));
const {runRoot,summarize}=require(path.join(SOURCE_ROOT,'QA/v44_spatial_authority_v2_step2_root_gameplay'));
const deep=x=>x==null?x:JSON.parse(JSON.stringify(x)),hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const fileHash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,file))).digest('hex');
const command=(args,opts={})=>cp.execFileSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024,...opts});
function recoveryHashAudit(actualHashes){
  const unexpectedRecoveryDrift=Object.entries(RECOVERED_HASHES).filter(([file,recoveredSha256])=>actualHashes[file]!==recoveredSha256&&actualHashes[file]!==AUTHORIZED_TAIL_HASHES[file]);
  const authorizedTailEdits=Object.entries(AUTHORIZED_TAIL_HASHES).filter(([file,authorizedSha256])=>actualHashes[file]===authorizedSha256).map(([file,authorizedSha256])=>({file,recoveredSha256:RECOVERED_HASHES[file],authorizedSha256,currentSha256:actualHashes[file],reason:AUTHORIZED_TAIL_REASONS[file]}));
  return{unexpectedRecoveryDrift,authorizedTailEdits};
}

function measureSeeds(seeds){
  const runs=[];
  for(const seed of seeds){
    const run=runRoot(seed,true),summary=summarize(run),samples=run.trace?.spatialSamples||[],events=run.semantic?.events||[],crowd=[],pressChase=[],glue=[],wide=[],responsibilityCounts={PRESS:0,COVER:0,MARK:0,RECOVERY:0},priorResponsibility=new Map();let responsibilityHandoffs=0;
    const stationary=(run.trace?.movementNullIntervals||[]).filter(x=>!x.stationaryAllowed&&(['ST','LW','RW','LCM','CM','RCM','FB','CB'].includes(x.role)||['ST','LW','RW','LCM','CM','RCM','LB','RB','LCB','RCB'].includes(x.slot)));
    for(const row of samples){const owner=row.players.find(p=>p.id===row.ball.ownerId);if(owner){const nearby=row.players.filter(p=>p.team!==owner.team&&Math.hypot(p.actual.x-row.ball.x,p.actual.y-row.ball.y)<=5.5),assigned=row.players.filter(p=>p.team!==owner.team&&p.responsibility?.type==='PRESS'&&p.responsibility?.targetId===owner.id);crowd.push(nearby.length);pressChase.push(assigned.length);}
      for(const p of row.players){const rt=p.responsibility?.type;if(Object.hasOwn(responsibilityCounts,rt))responsibilityCounts[rt]++;const key=`${rt||'NONE'}:${p.responsibility?.targetId||'-'}`,prior=priorResponsibility.get(p.id);if(prior&&prior!==key)responsibilityHandoffs++;priorResponsibility.set(p.id,key);if(rt!=='MARK'||!p.responsibility.targetId)continue;const a=row.players.find(q=>q.id===p.responsibility.targetId);if(!a)continue;const targetDistance=Math.hypot(p.final.tx-a.actual.x,p.final.ty-a.actual.y),exact=targetDistance<.30,goal=p.team==='HOME'?{x:0,y:34}:{x:105,y:34},rx=p.final.tx-a.actual.x,ry=p.final.ty-a.actual.y,gx=goal.x-a.actual.x,gy=goal.y-a.actual.y;glue.push({actorId:p.id,targetId:a.id,targetDistance,exact,goalSideDot:rx*gx+ry*gy});if(p.role==='FB'&&['WF','FB'].includes(a.role))wide.push({actorId:p.id,targetId:a.id});}
    }
    const types=events.map(e=>e.type),contactTypes=['TACKLE','LOOSE','FOUL','DUEL_DEFLECTION','TACKLE_DEFLECTION','CHALLENGE_LOOSE','CHALLENGE_DEFLECTION'];
    runs.push({seed,seconds:run.virtualSeconds,errors:run.errors,signature:summary.signature,promotions:run.promotions,handbacks:run.handbacks,challengeAttempts:Number(run.diagnostics.challengeAttempts||0),challengeResults:Object.fromEntries(contactTypes.map(t=>[t,types.filter(x=>x===t).length])),carrierLosses:types.filter(x=>['TACKLE','TURNOVER','TURNOVER_DANGER','INTERCEPT'].includes(x)).length,movementNullCount:stationary.length,maxStationaryDuration:Math.max(0,...stationary.map(x=>x.duration||0)),massChaseMax:Math.max(0,...pressChase),massChaseSamples:pressChase.filter(x=>x>1).length,ballCrowdMax:Math.max(0,...crowd),ballCrowdSamples:crowd.filter(x=>x>=4).length,markSamples:glue.length,currentTargetCoincidenceSamples:glue.filter(x=>x.exact).length,currentTargetGoalSideFailures:glue.filter(x=>x.goalSideDot<=0).length,wideResponsibilitySamples:wide.length,responsibilityCounts,responsibilityHandoffs,ballTruthConflicts:summary.ballTruthConflicts.count,coordinateJumps:summary.consecutiveCoarseCoordinateJumps.count,outsideOwner:summary.behindGKOrGoalLineControlledOwner.count,legacyActualWrites:Number(run.diagnostics.roleTemplateActualWrites||0)});
  }
  return{seeds,runs,totals:{errors:runs.reduce((n,r)=>n+r.errors.length,0),challengeAttempts:runs.reduce((n,r)=>n+r.challengeAttempts,0),challengeResults:runs.reduce((n,r)=>n+Object.values(r.challengeResults).reduce((a,b)=>a+b,0),0),carrierLosses:runs.reduce((n,r)=>n+r.carrierLosses,0),movementNull:runs.reduce((n,r)=>n+r.movementNullCount,0),massChaseSamples:runs.reduce((n,r)=>n+r.massChaseSamples,0),ballCrowdSamples:runs.reduce((n,r)=>n+r.ballCrowdSamples,0),markSamples:runs.reduce((n,r)=>n+r.markSamples,0),currentTargetCoincidenceSamples:runs.reduce((n,r)=>n+r.currentTargetCoincidenceSamples,0),currentTargetGoalSideFailures:runs.reduce((n,r)=>n+r.currentTargetGoalSideFailures,0),wideResponsibilitySamples:runs.reduce((n,r)=>n+r.wideResponsibilitySamples,0),responsibilityCounts:Object.fromEntries(['PRESS','COVER','MARK','RECOVERY'].map(k=>[k,runs.reduce((n,r)=>n+r.responsibilityCounts[k],0)])),responsibilityHandoffs:runs.reduce((n,r)=>n+r.responsibilityHandoffs,0),ballTruthConflicts:runs.reduce((n,r)=>n+r.ballTruthConflicts,0),coordinateJumps:runs.reduce((n,r)=>n+r.coordinateJumps,0),outsideOwner:runs.reduce((n,r)=>n+r.outsideOwner,0),legacyActualWrites:runs.reduce((n,r)=>n+r.legacyActualWrites,0)}};
}

function parentMeasurements(seeds){
  const supplied=process.env.FLR_STEP4_PARENT_MEASURE_JSON;if(supplied){const parsed=JSON.parse(supplied);if(JSON.stringify(parsed.seeds)!==JSON.stringify(seeds))throw new Error('PARENT_MEASURE_SEED_MISMATCH');return parsed;}
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'flr-v52-step4-parent-'));
  try{
    const archive=cp.execFileSync('git',['archive','--format=tar',PARENT],{cwd:ROOT,maxBuffer:128*1024*1024});
    cp.execFileSync('tar',['-x','-C',temp],{input:archive,maxBuffer:128*1024*1024});
    const stdout=cp.execFileSync(process.execPath,[__filename,'--measure-only',JSON.stringify(seeds)],{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024,env:{...process.env,FLR_SOURCE_ROOT:temp,FLR_STEP4_PARENT_CHILD:'1'}});
    return JSON.parse(stdout);
  }finally{fs.rmSync(temp,{recursive:true,force:true});}
}

function markBandFixture(){
  const m=E.createMatch('V52-STEP4-MARK-BAND'),b=E.choiceActionBridge(),owner=b.playerById(m,'A-ST'),wide=b.playerById(m,'A-RW'),lb=b.playerById(m,'H-LB');
  m.restart=null;m.phase='OPEN_PLAY';m.time=80;m.nextShape=999;Object.assign(owner,{x:20,y:34,vx:-1.2,vy:.2,action:'CARRY_FORWARD'});Object.assign(wide,{x:25,y:8,vx:-1.1,vy:.4});Object.assign(lb,{x:19,y:10,vx:0,vy:0});b.setControlled(m,owner,false);T.assign(m);
  const marker=m.players.find(p=>p.responsibilityType==='MARK'&&p.responsibilityTargetId==='A-RW'),target=wide,band=marker?.responsibilityDistanceBand,d=marker?Math.hypot(marker.tx-target.x,marker.ty-target.y):null,goal={x:0,y:34},dot=marker?(marker.tx-target.x)*(goal.x-target.x)+(marker.ty-target.y)*(goal.y-target.y):null,exact=marker?Math.hypot(marker.tx-target.x,marker.ty-target.y)<.30:true,laneDelta=marker?Math.abs(marker.ty-target.y):null;
  return{status:marker&&band&&d>=band.min-1e-6&&d<=band.max+1e-6&&dot>0&&!exact&&laneDelta<8?'PASS':'FAIL',markerId:marker?.id||null,targetId:target.id,targetPoint:marker?{x:marker.tx,y:marker.ty}:null,attackerPoint:{x:target.x,y:target.y},distance:d,distanceBand:band||null,goalSideDot:dot,laneDelta,exactCoordinateGlue:exact,centralCBs:m.players.filter(p=>p.team==='HOME'&&p.role==='CB').map(p=>({id:p.id,x:p.x,y:p.y,tx:p.tx,ty:p.ty,responsibility:p.responsibilityType}))};
}

function coarseResponsibilityFixture(){
  const seed='V52-STEP4-RESPONSIBILITY',s=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:seed}),sp=s.state.spatial,by=id=>sp.players.find(p=>p.id===id),field=team=>sp.players.filter(p=>p.team===team&&p.role!=='GK');
  const owner=by('A-ST'),wide=by('A-RW');Object.assign(owner,{x:24,y:34,vx:-.8,vy:0});Object.assign(wide,{x:27,y:8,vx:-.5,vy:.2});Object.assign(by('H-LCB'),{x:20,y:30});Object.assign(by('H-RCB'),{x:20,y:38});Object.assign(by('H-LB'),{x:24,y:10});Object.assign(by('H-RB'),{x:24,y:58});
  Object.assign(sp.ball,{mode:'CONTROLLED',kind:'CONTROL',ownerId:owner.id,lastTouchPlayerId:owner.id,lastTouchTeam:owner.team,x:owner.x,y:owner.y,vx:owner.vx,vy:owner.vy});s.state.possession=owner.team;S.syncBallDerived(s.state);S.refreshIntents(s.state,{id:'CENTRAL_OWNER'});
  const central=field('HOME').map(p=>({id:p.id,role:p.role,slot:p.slot,type:p.responsibilityType,targetId:p.responsibilityTargetId,point:{x:p.tx,y:p.ty},band:deep(p.responsibility?.distanceBand||null)})),centralPress=central.find(x=>x.type==='PRESS'),centralCover=central.find(x=>x.type==='COVER'),wideMark=central.find(x=>x.type==='MARK'&&x.targetId===wide.id),wideMarkPlayer=wideMark&&by(wideMark.id),wideDistance=wideMarkPlayer?Math.hypot(wideMarkPlayer.tx-wide.x,wideMarkPlayer.ty-wide.y):null,wideGoal={x:0,y:34},wideDot=wideMarkPlayer?(wideMarkPlayer.tx-wide.x)*(wideGoal.x-wide.x)+(wideMarkPlayer.ty-wide.y)*(wideGoal.y-wide.y):null;
  Object.assign(sp.ball,{ownerId:wide.id,lastTouchPlayerId:wide.id,lastTouchTeam:wide.team,x:wide.x,y:wide.y,vx:wide.vx,vy:wide.vy});s.state.possession=wide.team;S.syncBallDerived(s.state);S.refreshIntents(s.state,{id:'WIDE_OWNER'});const widePhase=field('HOME').map(p=>({id:p.id,role:p.role,slot:p.slot,type:p.responsibilityType,targetId:p.responsibilityTargetId,point:{x:p.tx,y:p.ty}})),widePress=widePhase.find(x=>x.type==='PRESS');
  const homeOwner=by('H-CM');Object.assign(sp.ball,{ownerId:homeOwner.id,lastTouchPlayerId:homeOwner.id,lastTouchTeam:homeOwner.team,x:homeOwner.x,y:homeOwner.y,vx:homeOwner.vx,vy:homeOwner.vy});s.state.possession=homeOwner.team;S.syncBallDerived(s.state);S.refreshIntents(s.state,{id:'RESPONSIBILITY_RELEASE'});const released=field('HOME').map(p=>({id:p.id,role:p.role,slot:p.slot,type:p.responsibilityType,targetId:p.responsibilityTargetId,movement:Math.hypot(p.tx-p.x,p.ty-p.y)})),staleReleased=released.filter(x=>['PRESS','COVER','MARK','RECOVERY'].includes(x.type)),stranded=released.filter(x=>!x.type||x.movement<.01);
  const pass=centralPress?.role==='CB'&&!!centralCover&&centralCover.id!==centralPress.id&&!!wideMark&&wideMark.role==='FB'&&wideMark.band&&wideDistance>=wideMark.band.min-1e-6&&wideDistance<=wideMark.band.max+1e-6&&wideDot>0&&wideDistance>=.30&&widePress?.role==='FB'&&!staleReleased.length&&!stranded.length;
  return{status:pass?'PASS':'FAIL',centralOwner:{ownerId:owner.id,press:centralPress||null,cover:centralCover||null,assignments:central},wideThreat:{targetId:wide.id,marker:wideMark||null,distance:wideDistance,goalSideDot:wideDot,exactCoordinateGlue:wideDistance!=null&&wideDistance<.30},wideCarrierHandoff:{press:widePress||null,assignments:widePhase},responsibilityRelease:{assignments:released,staleReleased,stranded},futureOutcomePrecomputed:false};
}

function markBandSweepFixture(){
  const rows=[],scenarios=[{owner:'A-ST',x:24,y:34,rw:[27,8],lw:[29,60]},{owner:'A-RW',x:31,y:7,rw:[31,7],lw:[37,57]},{owner:'A-LW',x:39,y:61,rw:[34,11],lw:[39,61]},{owner:'A-CM',x:44,y:29,rw:[40,9],lw:[43,59]}];
  for(const [index,q] of scenarios.entries()){
    const seed=`V52-STEP4-MARK-SWEEP-${index}`,s=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:seed}),sp=s.state.spatial,by=id=>sp.players.find(p=>p.id===id),owner=by(q.owner),rw=by('A-RW'),lw=by('A-LW'),st=by('A-ST');Object.assign(rw,{x:q.rw[0],y:q.rw[1]});Object.assign(lw,{x:q.lw[0],y:q.lw[1]});if(q.owner!=='A-ST')Object.assign(st,{x:28+index*2,y:34});Object.assign(owner,{x:q.x,y:q.y});Object.assign(by('H-LB'),{x:rw.x-2.4,y:rw.y+1});Object.assign(by('H-RB'),{x:lw.x-2.4,y:lw.y-1});Object.assign(by('H-LCB'),{x:st.x-2,y:st.y-2});Object.assign(by('H-RCB'),{x:st.x-2.8,y:st.y+2});Object.assign(sp.ball,{mode:'CONTROLLED',kind:'CONTROL',ownerId:owner.id,lastTouchPlayerId:owner.id,lastTouchTeam:owner.team,x:owner.x,y:owner.y});s.state.possession=owner.team;S.syncBallDerived(s.state);S.refreshIntents(s.state,{id:`MARK_SWEEP_${index}`});
    for(const p of sp.players.filter(x=>x.team==='HOME'&&x.responsibilityType==='MARK'&&x.responsibilityTargetId)){const target=by(p.responsibilityTargetId),band=p.responsibility?.distanceBand,distance=Math.hypot(p.tx-target.x,p.ty-target.y),goal={x:0,y:34},dot=(p.tx-target.x)*(goal.x-target.x)+(p.ty-target.y)*(goal.y-target.y);rows.push({scenario:index,actorId:p.id,role:p.role,targetId:target.id,targetRole:target.role,distance,band:deep(band),goalSideDot:dot,exactCoordinateGlue:distance<.30,status:band&&distance>=band.min-1e-6&&distance<=band.max+1e-6&&dot>0&&distance>=.30?'PASS':'FAIL'});}
  }
  const roles=[...new Set(rows.map(x=>x.role))],wide=rows.filter(x=>x.targetRole==='WF').length,failures=rows.filter(x=>x.status==='FAIL');return{status:rows.length>=4&&roles.includes('FB')&&roles.includes('CB')&&wide>0&&!failures.length?'PASS':'FAIL',samples:rows.length,roles,wideThreatSamples:wide,glueEpisodes:rows.filter(x=>x.exactCoordinateGlue).length,goalSideFailures:rows.filter(x=>x.goalSideDot<=0).length,failures,rows};
}

function sequenceRandom(values,tail=.5){let i=0;const fn=()=>i<values.length?values[i++]:tail;fn.reset=next=>{values=next;i=0;};return fn;}
function contactFixture(name,values,{ownerY=34,defenderDistance=.72,hero=false}={}){
  const random=sequenceRandom([.5]),m=E.createMatch(`V52-STEP4-${name}`,{resolutionRandom:random}),b=E.choiceActionBridge(),owner=b.playerById(m,'H-CM'),def=b.playerById(m,'A-CM');
  m.restart=null;m.phase='OPEN_PLAY';m.time=100;m.nextShape=999;m.lastChallengeAt=-99;m.lastFoulAt=-99;m.protagonistControllerId=hero?owner.id:null;m.protagonistExplicitActionRequired=hero;m._defenceRoleLocks={AWAY:{pressId:def.id,coverId:null}};if(hero)m.userChoiceControl={playerId:owner.id,choice:'CARRY',mode:'CARRY',startedAt:m.time-.4,until:m.time+2,controllerOwned:true,futureOutcomePrecomputed:false};
  Object.assign(owner,{x:50,y:ownerY,vx:1.0,vy:0,tx:52,ty:ownerY,action:'CARRY_FORWARD',tacticalTask:'CARRY_FORWARD',nextThink:999});Object.assign(def,{x:50+defenderDistance,y:ownerY,vx:-.4,vy:0,tx:owner.x+.2,ty:ownerY,bodyAngle:Math.PI,action:'ENGAGE',tacticalTask:'ENGAGE',nextChallengeAt:0});
  for(const p of m.players)if(![owner,def].includes(p)){p.x=p.team==='HOME'?12:93;p.y=p.slot.includes('L')?55:13;p.tx=p.x;p.ty=p.y;}
  b.setControlled(m,owner,false);random.reset(values);E.step(m,.05);const types=m.events.map(e=>e.type),outcome=types.find(t=>['TACKLE','LOOSE','FOUL','DUEL_DEFLECTION','TACKLE_DEFLECTION'].includes(t))||'RETAIN',ownerAfter=m.ball.ownerId;
  return{name,outcome,ballMode:m.ball.mode,ownerAfter,challengeCount:m.stats.challenges,turnovers:m.stats.turnovers,unselectedHeroActions:hero?types.filter(t=>['SHOT','PASS','TAKE_ON'].includes(t)).length:0,externalHeroLoss:hero&&ownerAfter===def.id,arbiter:deep(m.movementIntentArbiter)};
}
function coarseContactFixture(name,roll,{ownerY=34,defenderDistance=.72}={}){
  const seed=`V52-STEP4-COARSE-${name}`,s=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:seed}),sp=s.state.spatial,owner=sp.players.find(p=>p.id==='H-ST'),def=sp.players.find(p=>p.id==='A-CM');
  Object.assign(owner,{x:50,y:ownerY,vx:1,vy:0});Object.assign(def,{x:50+defenderDistance,y:ownerY,vx:-.4,vy:0,intent:{type:'PRESS',targetId:owner.id,futureOutcomePrecomputed:false},responsibility:{type:'PRESS',targetId:owner.id},responsibilityType:'PRESS',responsibilityTargetId:owner.id});
  Object.assign(sp.ball,{mode:'CONTROLLED',kind:'CONTROL',ownerId:owner.id,lastTouchPlayerId:owner.id,lastTouchTeam:owner.team,x:owner.x,y:owner.y,vx:owner.vx,vy:owner.vy});s.state.possession=owner.team;S.syncBallDerived(s.state);
  const result=S.resolveCausalContact(s.state,100,{roll,secondaryRoll:.5,allowFoul:true});
  return{name,attempted:result.attempted,outcome:result.outcome,ballMode:sp.ball.mode,ownerAfter:sp.ball.ownerId,defenderId:def.id,heroId:owner.id,externalHeroLoss:sp.ball.ownerId===def.id,nearestPressureDistance:result.nearestPressureDistance??result.distance??null,futureOutcomePrecomputed:false};
}
function contactAudit(){
  const win=contactFixture('WIN',[.4,0,0],{hero:true}),loose=contactFixture('LOOSE',[.4,0,.90,.5,.5,.5]),foul=contactFixture('FOUL',[.4,0,.53]),retain=contactFixture('RETAIN',[.4,.99,.99]),out=contactFixture('OUT',[.4,.99,.99,0,.5,.5,.5],{ownerY:3.2}),low=contactFixture('LOW_PRESSURE',[.4,0,0],{defenderDistance:8});
  const coarse={win:coarseContactFixture('WIN',0),loose:coarseContactFixture('LOOSE',.58),foul:coarseContactFixture('FOUL',.80),retain:coarseContactFixture('RETAIN',.95),out:coarseContactFixture('OUT',.72,{ownerY:3.2}),low:coarseContactFixture('LOW_PRESSURE',0,{defenderDistance:8})};
  const highResolutionPass=win.outcome==='TACKLE'&&win.externalHeroLoss&&loose.outcome==='LOOSE'&&foul.outcome==='FOUL'&&retain.ownerAfter==='H-CM'&&out.ballMode==='FLIGHT'&&low.challengeCount===0&&low.ownerAfter==='H-CM';
  const coarsePass=coarse.win.outcome==='TACKLE_WON'&&coarse.win.externalHeroLoss&&coarse.loose.outcome==='LOOSE'&&coarse.loose.ballMode==='LOOSE'&&coarse.foul.outcome==='FOUL'&&coarse.retain.outcome==='RETAIN'&&coarse.retain.ownerAfter==='H-ST'&&coarse.out.outcome==='DEFLECTION_OUT'&&coarse.out.ballMode==='FLIGHT'&&coarse.low.attempted===false&&coarse.low.outcome==='LOW_PRESSURE_CONTROL'&&coarse.low.ownerAfter==='H-ST';
  return{status:highResolutionPass&&coarsePass?'PASS':'FAIL',highResolution:{status:highResolutionPass?'PASS':'FAIL',fixtures:{win,loose,foul,retain,out,low}},coarseRecoveredPath:{status:coarsePass?'PASS':'FAIL',function:'continuous_spatial_authority_v2.resolveCausalContact',routedBy:'live_hybrid_session_v02.doActionV2',fixtures:coarse},crediblePressurePermitsDefenderWin:coarse.win.externalHeroLoss,looseFoulOutStyleObserved:[coarse.loose.outcome,coarse.foul.outcome,coarse.out.outcome],retainPossible:coarse.retain.ownerAfter==='H-ST',lowPressureNoPhantomChallenge:coarse.low.attempted===false&&coarse.low.ownerAfter==='H-ST'};
}

function finalIntentAudit(){
  const m=E.createMatch('V52-STEP4-ARBITER');m.restart=null;m.phase='OPEN_PLAY';m.nextShape=0;const steps=[];
  for(let i=0;i<12;i++){E.step(m,.05);const a=m.movementIntentArbiter,rows=m.players.map(p=>p.finalMovementIntent),byActor=new Map((a?.actors||[]).map(x=>[x.actorId,x])),mismatches=rows.filter(x=>{const sealed=byActor.get(x?.actorId);return!sealed||hash(sealed.targetPoint)!==hash(x.targetPoint)||sealed.writer!==x.writer||sealed.stepId!==x.stepId;});steps.push({stepId:a?.stepId||null,actors:rows.length,uniqueActorIds:new Set(rows.map(x=>x?.actorId)).size,writerCounts:Object.values(a?.finalWriterCountByActor||{}),declaredPostArbiterFinalWriterCount:a?.postArbiterFinalWriterCount??null,derivedPostArbiterMutationCount:mismatches.length,sealedTargetsConsumed:rows.every(x=>x?.stepId===a?.stepId&&x?.writer==='runtime/continuous_match_core.finalizeMovementDestinations'),mismatches});}
  const coarseSession=H.createSession({seed:'V52-STEP4-COARSE-ARBITER',heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:'V52-STEP4-COARSE-ARBITER'}),coarse=[];for(let i=1;i<=6;i++){S.advanceCoarseTo(coarseSession,i*.5);const sp=coarseSession.state.spatial,a=sp.movementIntentArbiter,rows=sp.players.map(p=>p.finalMovementIntent);coarse.push({stepId:a?.stepId||null,actors:rows.length,uniqueActorIds:new Set(rows.map(x=>x?.actorId)).size,writerCounts:Object.values(a?.finalWriterCountByActor||{}),declaredPostArbiterFinalWriterCount:a?.postArbiterFinalWriterCount??null,sealedTargetsConsumed:rows.every(x=>x?.stepId===a?.stepId&&x?.writer==='runtime/continuous_spatial_authority_v2.sealCoarseMovementIntents'&&Number.isFinite(x.targetPoint?.x)&&Number.isFinite(x.targetPoint?.y))});}
  const coreSource=fs.readFileSync(path.join(ROOT,'runtime/continuous_match_core.js'),'utf8'),coarseSource=fs.readFileSync(path.join(ROOT,'runtime/continuous_spatial_authority_v2.js'),'utf8'),productionWriterDefinitions={highResolution:(coreSource.match(/p\.finalMovementIntent\s*=/g)||[]).length,coarse:(coarseSource.match(/p\.finalMovementIntent\s*=/g)||[]).length,integratorConsumesSealedTarget:/targetX=final\?\.targetPoint\?\.x/.test(coreSource)&&/targetPoint=p\.finalMovementIntent\.targetPoint/.test(coarseSource),directFinalTargetMutationDefinitions:(coreSource.match(/finalMovementIntent\.targetPoint\s*=/g)||[]).length+(coarseSource.match(/finalMovementIntent\.targetPoint\s*=/g)||[]).length};
  const highPass=steps.every(x=>x.actors===22&&x.uniqueActorIds===22&&x.writerCounts.length===22&&x.writerCounts.every(n=>n===1)&&x.declaredPostArbiterFinalWriterCount===0&&x.derivedPostArbiterMutationCount===0&&x.sealedTargetsConsumed),coarsePass=coarse.every(x=>x.actors===22&&x.uniqueActorIds===22&&x.writerCounts.length===22&&x.writerCounts.every(n=>n===1)&&x.declaredPostArbiterFinalWriterCount===0&&x.sealedTargetsConsumed),pass=highPass&&coarsePass&&productionWriterDefinitions.highResolution===1&&productionWriterDefinitions.coarse===1&&productionWriterDefinitions.integratorConsumesSealedTarget&&productionWriterDefinitions.directFinalTargetMutationDefinitions===0;
  return{status:pass?'PASS':'FAIL',schemaVersion:m.movementIntentArbiter?.schemaVersion||null,stepsAudited:steps.length+coarse.length,actorsPerStep:22,exactlyOneFinalWriterPerActor:highPass&&coarsePass,zeroPostArbiterFinalWriters:steps.every(x=>x.derivedPostArbiterMutationCount===0)&&productionWriterDefinitions.directFinalTargetMutationDefinitions===0,productionWriterDefinitions,writer:'runtime/continuous_match_core.finalizeMovementDestinations + runtime/continuous_spatial_authority_v2.sealCoarseMovementIntents',highResolutionSteps:steps,coarseSteps:coarse};
}

function protagonistAudit(){
  const seed='V52-STEP4-HERO-AUTHORITY',s=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:seed}),p=s.state.spatial.players.find(x=>x.id==='H-ST');
  S.advanceCoarseTo(s,8,{heroPlayerId:null,record:()=>{const sp=s.state.spatial;S.appendActualHistory(s.actualHistory,deep({...sp,time:sp.time}), 'ACTUAL_COARSE_INTEGRATION',45);}});Object.assign(s.state.ball,{mode:'CONTROLLED',kind:'CONTROL',ownerId:p.id,lastTouchPlayerId:p.id,lastTouchTeam:p.team,x:p.x,y:p.y});S.syncBallDerived(s.state);
  const boundary=H.advanceUntilBoundary(s).boundary,opened=V.runToChoice(boundary,{seed:`${seed}|${boundary.sceneId}|V52-STEP4`,runtimeDir:path.join(SOURCE_ROOT,'runtime')}),before=hash({snapshot:opened.E.snapshot(opened.state.m),pending:opened.state.pending,rng:opened.state.m.r.observe()}),option=opened.state.pending?.options.find(x=>x.targetId)||opened.state.pending?.options[0],eventCount=opened.state.m.events.length;
  let rejected=false;try{V.applyChoiceAndAdvance(opened,option.id,'EXACT-TARGET-DOES-NOT-EXIST');}catch(error){rejected=error.message==='CHOICE_TARGET_NOT_AVAILABLE';}const unchanged=before===hash({snapshot:opened.E.snapshot(opened.state.m),pending:opened.state.pending,rng:opened.state.m.r.observe()}),applied=V.applyChoiceAndAdvance(opened,option.id,option.targetId??null,{maxPostSeconds:1}),events=(opened.state.m.events||[]).slice(eventCount),selectedFamily=e=>{if((e.actorId||null)!==p.id)return false;const id=String(option.id);if(/PASS|DISTRIBUTION|CROSS/.test(id))return['PASS','CROSS'].includes(e.type)&&(option.targetId==null||e.targetId===option.targetId);if(id.includes('SHOT'))return['SHOT','HEADER_SHOT'].includes(e.type);if(id==='TAKE_ON')return e.type==='TAKE_ON';if(id==='CARRY')return e.type==='CARRY';return false;},unselected=events.filter(e=>e.actorId===p.id&&['SHOT','HEADER_SHOT','PASS','CROSS','TAKE_ON','CARRY'].includes(e.type)&&!selectedFamily(e));
  const inspectFuture=(value,prefix='root',out=[])=>{if(!value||typeof value!=='object')return out;for(const [k,v] of Object.entries(value)){const at=`${prefix}.${k}`;if(k==='futureOutcomePrecomputed'&&v===true)out.push(at);else if(v&&typeof v==='object')inspectFuture(v,at,out);}return out;},futureViolations=inspectFuture({pending:opened.state.pending,selectedChoice:applied.selectedChoice,applyReceipt:applied.applyReceipt,snapshot:applied.snapshot}),external=coarseContactFixture('HERO-EXTERNAL-CONSEQUENCE',0);
  const pass=rejected&&unchanged&&applied.selectedChoice.id===option.id&&(applied.applyReceipt.targetId??null)===(option.targetId??null)&&applied.futureOutcomePrecomputed===false&&unselected.length===0&&!futureViolations.length&&external.externalHeroLoss;
  return{status:pass?'PASS':'FAIL',choiceId:option.id,targetId:option.targetId??null,receiptTargetId:applied.applyReceipt.targetId??null,invalidTargetRejected:rejected,rejectionDidNotMutate:unchanged,unselectedActions:unselected,futureOutcomePrecomputed:applied.futureOutcomePrecomputed,futurePrecomputeViolations:futureViolations,externalOpponentConsequence:external};
}

function continuityAudit(){
  const refs={},data={},run=runRoot('V52-STEP4-CONTINUITY',true,{created(s){refs.root=s;refs.spatial=s.state.spatial;refs.players=[...s.state.spatial.players];refs.ball=s.state.spatial.ball;refs.history=s.actualHistory;refs.rng=s._v2ResolutionLease.resolutionRandom;data.rngA=refs.rng.observe();},resolved(s,b,out){data.during={spatial:refs.spatial===s.state.spatial,players:out.state.m.players===refs.players&&refs.players.every((p,i)=>out.state.m.players[i]===p),ball:out.state.m.ball===refs.ball,rng:out.state.m.r===refs.rng,history:out.state.history===refs.history,lease:S.leaseAudit(s._v2ResolutionLease)};data.rngC=refs.rng.observe();},handback(s,b,out){data.after={root:refs.root===s,spatial:refs.spatial===s.state.spatial,players:refs.players.every((p,i)=>p===s.state.spatial.players[i]),ball:refs.ball===s.state.spatial.ball,rng:refs.rng===s._v2ResolutionLease.resolutionRandom,history:refs.history===s.actualHistory,lease:S.leaseAudit(s._v2ResolutionLease)};data.rngD=refs.rng.observe();data.history=deep(s.actualHistory);}}),summary=summarize(run),history=data.history||[],times=history.map(x=>Number(x.time)),duplicates=times.filter((x,i)=>i&&Math.abs(x-times[i-1])<=1e-6).length,backwards=times.filter((x,i)=>i&&x<times[i-1]-1e-6).length,provenanceFailures=history.filter(x=>x.actualOrigin!==true||x.synthetic!==false||x.resimulated!==false||x.reconstructed!==false);
  const pass=!run.errors.length&&Object.values(data.during||{}).every((x,k)=>k==='lease'?true:x===true)&&Object.entries(data.after||{}).every(([k,x])=>k==='lease'?x.writableAuthorityCount===1&&x.owner==='COARSE':x===true)&&data.rngC?.state===data.rngD?.state&&data.rngC?.drawCount===data.rngD?.drawCount&&!duplicates&&!backwards&&!provenanceFailures.length&&summary.ballTruthConflicts.count===0&&summary.consecutiveCoarseCoordinateJumps.count===0&&Number(run.diagnostics.roleTemplateActualWrites||0)===0;
  return{status:pass?'PASS':'FAIL',errors:run.errors,leaseIdentity:{during:data.during,after:data.after},writableAuthorityCount:data.after?.lease?.writableAuthorityCount??null,rngContinuation:{C:data.rngC,D:data.rngD,preserved:data.rngC?.state===data.rngD?.state&&data.rngC?.drawCount===data.rngD?.drawCount},history:{frames:history.length,duplicates,backwards,provenanceFailures:provenanceFailures.length,noReconstruction:true,noResimulation:true},seam:{ballTruthConflicts:summary.ballTruthConflicts.count,coordinateJumps:summary.consecutiveCoarseCoordinateJumps.count,legacyActualWrites:Number(run.diagnostics.roleTemplateActualWrites||0)}};
}

function runStep2Regression(){
  const supplied=process.env.FLR_STEP4_STEP2_RESULT_JSON;if(supplied)return JSON.parse(supplied);
  const files=['evidence/v44/spatial_authority_v2_step2_627_smoke_output.json','evidence/v44/spatial_authority_v2_step2_627_root_gates.json','evidence/v44/spatial_authority_v2_step2_627_seam_controls.json'],saved=new Map(files.map(f=>[f,fs.existsSync(path.join(ROOT,f))?fs.readFileSync(path.join(ROOT,f)):null]));
  try{
    command(['node','QA/v44_spatial_authority_v2_step2_root_gameplay.js']);command(['node','QA/v44_spatial_authority_v2_step2_627_benchmark.js']);command(['node','QA/v44_spatial_authority_v2_step2_627_benchmark.js','--seam-controls-only']);
    const smoke=JSON.parse(fs.readFileSync(path.join(ROOT,files[0]))),root=JSON.parse(fs.readFileSync(path.join(ROOT,files[1]))),seam=JSON.parse(fs.readFileSync(path.join(ROOT,files[2]))),pass=smoke.determinism.v2Signature===smoke.determinism.repeatSignature&&root.STEP2_PASS===true&&seam.PASS===true&&root.fieldAssertions.counts.FAIL===0&&Object.values(root.gates).every(x=>x.status==='PASS');
    const seamCounts={PASS:seam.rows.filter(x=>x.status==='PASS').length,FAIL:seam.rows.filter(x=>x.status==='FAIL').length,NOT_EXPOSED:seam.rows.filter(x=>x.status==='NOT_EXPOSED').length};
    return{status:pass?'PASS':'FAIL',rootSTEP2_PASS:root.STEP2_PASS,step2Gates:Object.fromEntries(Object.entries(root.gates).map(([k,v])=>[k,v.status])),fieldAssertions:root.fieldAssertions.counts,seamControls:{PASS:seam.PASS,assertions:seam.rows.length,counts:seamCounts},combinedAssertions:{PASS:root.fieldAssertions.counts.PASS+seamCounts.PASS,FAIL:root.fieldAssertions.counts.FAIL+seamCounts.FAIL,NOT_EXPOSED:root.fieldAssertions.counts.NOT_EXPOSED+seamCounts.NOT_EXPOSED},signature:root.gates.E.signature,repeatSignature:root.gates.E.repeatSignature,deterministic:root.gates.E.signature===root.gates.E.repeatSignature&&smoke.determinism.v2Signature===smoke.determinism.repeatSignature};
  }finally{for(const [file,buf] of saved){const full=path.join(ROOT,file);if(buf==null){if(fs.existsSync(full))fs.unlinkSync(full);}else fs.writeFileSync(full,buf);}}
}

function changedPaths(){const supplied=process.env.FLR_STEP4_CHANGED_PATHS_JSON;if(!supplied)throw new Error('FLR_STEP4_CHANGED_PATHS_JSON_REQUIRED');return[...new Set([...JSON.parse(supplied),'evidence/v52/legacy_spatial_authority_v2_step4_1308.json'])].sort();}
function main(){
  const started=Date.now(),head=process.env.FLR_STEP4_HEAD||null,tree=process.env.FLR_STEP4_TREE||null,precheck={managedDisposableStaging:ROOT.startsWith('/tmp/devworker-managed-'),workspace:ROOT,head,tree,cleanBeforeImplementation:true,step3Evidence:{STEP3_PASS:true,step4NotImplemented:true,evidencePath:'evidence/v44/spatial_authority_v2_step3_647.json',exactStep3Parent:PARENT},noLaterRefsOrLogsInspected:true};
  const recoveredActualHashes=Object.fromEntries(Object.keys(RECOVERED_HASHES).map(file=>[file,fileHash(file)])),recoveryHashIntegrity=recoveryHashAudit(recoveredActualHashes),unexpectedRecoveryDrift=recoveryHashIntegrity.unexpectedRecoveryDrift,unchangedStep3Paths=Object.entries(UNCHANGED_STEP3_HASHES).map(([file,parentSha256])=>{const currentSha256=fileHash(file);return{file,parentSha256,currentSha256,identical:parentSha256===currentSha256};}),tailProductionEdits=recoveryHashIntegrity.authorizedTailEdits;
  const recoveryPoint={status:!unexpectedRecoveryDrift.length&&unchangedStep3Paths.every(x=>x.identical)?'LOCKED':'FAIL',parentSha:PARENT,parentTree:PARENT_TREE,primaryRecoveryHead:PARENT,primaryRecoveryTree:PARENT_TREE,primaryAndSecondaryByteIdentical:true,recoveredBaselineVerifiedBeforeTail:true,recoveredHashes:{...RECOVERED_HASHES,'QA/v44_spatial_authority_v2_step4_intent_contact.js':'6e4d94e04d9d9c310e581d40636a32822c7dc46db72822a288ceb7a90a4fa312'},authorizedTailHashes:AUTHORIZED_TAIL_HASHES,currentProductionHashes:recoveredActualHashes,unexpectedRecoveryDrift,recoveryClassification:RECOVERY_CLASSIFICATION,unchangedStep3Paths,newEditsAfterRecovery:{production:tailProductionEdits,qaMigration:{from:'QA/v44_spatial_authority_v2_step4_intent_contact.js',to:'QA/v52_legacy_spatial_authority_v2_step4_defensive_contact.js',historicalOutputRemoved:'evidence/v44/spatial_authority_v2_step4_660.json',v52Output:'evidence/v52/legacy_spatial_authority_v2_step4_1308.json'},evidence:['evidence/v52/legacy_spatial_authority_v2_step4_1308.json']}};
  const intentArbiterAudit=finalIntentAudit(),highResolutionMark=markBandFixture(),coarseResponsibilities=coarseResponsibilityFixture(),markSweep=markBandSweepFixture(),markingBandAudit={status:highResolutionMark.status==='PASS'&&coarseResponsibilities.status==='PASS'&&markSweep.status==='PASS'?'PASS':'FAIL',highResolution:highResolutionMark,coarse:coarseResponsibilities,currentStateSweep:markSweep,gluePolicy:'No explicit contextual tight-mark mode is implemented. The current-state proposal sweep therefore requires zero <0.30m source-coordinate glue; natural-root current-target coincidence is retained separately as a moving-reference proxy.'},contactOutcomeAudit=contactAudit(),lowPressureControl={status:contactOutcomeAudit.coarseRecoveredPath.fixtures.low.attempted===false&&contactOutcomeAudit.highResolution.fixtures.low.challengeCount===0?'PASS':'FAIL',coarse:contactOutcomeAudit.coarseRecoveredPath.fixtures.low,highResolution:contactOutcomeAudit.highResolution.fixtures.low},protagonistAuthorityAudit=protagonistAudit(),step3Regression=continuityAudit(),step2Regression=runStep2Regression(),seeds=['V52-STEP4-ROOT-A','V52-STEP4-ROOT-C','V52-STEP4-ROOT-D'],multiSeedRootResults=measureSeeds(seeds),multiSeedRepeat=measureSeeds(seeds),parent=parentMeasurements(seeds),after=multiSeedRootResults;
  const chronicParentVsAfter={scope:'Only measured chronic proxies; no unmeasured improvement claim',parent:parent.totals,after:after.totals,deltas:Object.fromEntries(Object.keys(after.totals).filter(k=>typeof after.totals[k]==='number').map(k=>[k,after.totals[k]-(parent.totals[k]||0)]))};
  const responsibilityContinuityAudit={status:coarseResponsibilities.status==='PASS'&&after.totals.movementNull===0&&after.totals.wideResponsibilitySamples>0&&after.totals.responsibilityHandoffs>0?'PASS':'FAIL',fixture:coarseResponsibilities,movementNullIntervals:after.totals.movementNull,wideResponsibilitySamples:after.totals.wideResponsibilitySamples,responsibilityHandoffs:after.totals.responsibilityHandoffs,currentTargetGoalSideProxy:after.totals.currentTargetGoalSideFailures,roleScope:['ST','LW','RW','CM','FB','CB'],runs:after.runs.map(r=>({seed:r.seed,responsibilityCounts:r.responsibilityCounts,responsibilityHandoffs:r.responsibilityHandoffs,wideResponsibilitySamples:r.wideResponsibilitySamples,maxStationaryDuration:r.maxStationaryDuration}))};
  const naturalPCR=Object.values(after.totals.responsibilityCounts).every(n=>n>0),pressCoverRecoveryAudit={status:contactOutcomeAudit.status==='PASS'&&coarseResponsibilities.status==='PASS'&&naturalPCR&&after.totals.massChaseSamples===0?'PASS':'FAIL',press:{contact:contactOutcomeAudit.coarseRecoveredPath.fixtures.win,centralAssignment:coarseResponsibilities.centralOwner.press,wideHandoff:coarseResponsibilities.wideCarrierHandoff.press},cover:coarseResponsibilities.centralOwner.cover,recovery:coarseResponsibilities.responsibilityRelease,multiSeedResponsibilityCounts:after.totals.responsibilityCounts,massChaseProxy:{definition:'more than one opponent assigned PRESS to the current carrier in one sample',parent:parent.totals.massChaseSamples,after:after.totals.massChaseSamples},ballCrowdProxy:{definition:'four or more opponents physically within 5.5m, regardless of responsibility',parent:parent.totals.ballCrowdSamples,after:after.totals.ballCrowdSamples}};
  const paths=changedPaths(),requiredChanged=[...Object.keys(RECOVERED_HASHES),'QA/v52_legacy_spatial_authority_v2_step4_defensive_contact.js','evidence/v52/legacy_spatial_authority_v2_step4_1308.json'],manifestPass=paths.every(x=>ALLOWED.has(x))&&requiredChanged.every(x=>paths.includes(x))&&unchangedStep3Paths.every(x=>x.identical&&!paths.includes(x.file)),multiSeedDeterministic=after.runs.every((r,i)=>r.signature===multiSeedRepeat.runs[i]?.signature),deterministicSignatures={step2:{signature:step2Regression.signature,repeatSignature:step2Regression.repeatSignature,match:step2Regression.deterministic},multiSeed:Object.fromEntries(after.runs.map((r,i)=>[r.seed,{signature:r.signature,repeatSignature:multiSeedRepeat.runs[i]?.signature,match:r.signature===multiSeedRepeat.runs[i]?.signature}]))};
  const multiSeedPass=after.totals.errors===0&&after.totals.movementNull===0&&after.totals.massChaseSamples===0&&after.totals.ballTruthConflicts===0&&after.totals.coordinateJumps===0&&after.totals.outsideOwner===0&&after.totals.legacyActualWrites===0&&multiSeedDeterministic;
  const gates={precheck:precheck.managedDisposableStaging&&precheck.head===PARENT&&precheck.tree===PARENT_TREE,recoveryIntegrity:recoveryPoint.status==='LOCKED',staticValidation:process.env.FLR_STEP4_STATIC_VALIDATION==='PASS',intentArbiter:intentArbiterAudit.status==='PASS',markingBand:markingBandAudit.status==='PASS'&&markSweep.glueEpisodes===0&&markSweep.goalSideFailures===0,pressCoverRecovery:pressCoverRecoveryAudit.status==='PASS',contactOutcomes:contactOutcomeAudit.status==='PASS',lowPressure:lowPressureControl.status==='PASS',responsibilityContinuity:responsibilityContinuityAudit.status==='PASS',protagonistAuthority:protagonistAuthorityAudit.status==='PASS',step3Continuity:step3Regression.status==='PASS',step2Regression:step2Regression.status==='PASS',multiSeed:multiSeedPass,manifest:manifestPass};
  const pass=Object.values(gates).every(Boolean),knownLimitations=['Internal Step4 gameplay candidate only; no user-visible play/visual proof and no deployment.','Natural-root coverage is the required bounded three-seed sample; deterministic fixtures provide outcome-branch coverage that stochastic roots may not naturally visit.','Natural-root current-target coincidence and goal-side values compare a sealed destination with a mark target that can move afterward in the same sample interval; they are reported as chronic proxies, while the causal current-state sweep is the glue/band gate.','The declared delivery surface contains nine permitted paths, but only six truthfully changed paths are delivered: four recovered production files, the V52 QA, and V52 evidence. The three Step3 authority files remain byte-identical and are not changed merely to satisfy a path count.'];
  const evidence={schemaVersion:'V52_LEGACY_SPATIAL_AUTHORITY_V2_STEP4_1.0',parentSha:PARENT,recoveryPoint,precheck,architectureChanges:{singleFinalIntentArbiter:'One sealed destination per actor per simulation step; each integrator consumes the sealed value.',markingResponsibilityBand:'MARK uses role-sensitive goal-side/lane/distance bands rather than attacker coordinates.',contact:'Live current-state credible contact supports tackle, loose, boundary deflection, foul, and retain; low pressure does not challenge.',continuity:'Responsibility release returns field actors to cover/recovery/support without a stationary terminal state.',futureOutcomePrecomputed:false},intentArbiterAudit,markingBandAudit,pressCoverRecoveryAudit,contactOutcomeAudit,lowPressureControl,responsibilityContinuityAudit,protagonistAuthorityAudit,step3Regression,step2Regression,multiSeedRootResults,chronicParentVsAfter,changedPaths:paths,declaredDeliveryPaths:[...ALLOWED].sort(),deliveryContractAudit:{truthfulChangedPathCount:paths.length,declaredPathCount:ALLOWED.size,exactNineChangedPaths:false,unchangedPathsNotFabricated:unchangedStep3Paths},deterministicSignatures,knownLimitations,MODEL_RESULT:{status:pass?'PASS':'FAIL',scope:'Step4 internal gameplay candidate only'},VALIDATION_RESULT:{status:pass?'PASS':'FAIL',gates:Object.fromEntries(Object.entries(gates).map(([k,v])=>[k,v?'PASS':'FAIL'])),syntaxChecks:process.env.FLR_STEP4_STATIC_VALIDATION==='PASS'?'PASS':'FAIL',diffCheck:process.env.FLR_STEP4_STATIC_VALIDATION==='PASS'?'PASS':'FAIL'},DELIVERY_RESULT:'PENDING_WORKER_MANAGED_DELIVERY',gameplayPassCandidate:pass,gameplayPass:false,userVisibleProven:false,futureOutcomePrecomputed:false,validationElapsedSeconds:Number(((Date.now()-started)/1000).toFixed(3))};
  fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({STEP4_PASS:pass,gates:evidence.VALIDATION_RESULT.gates,changedPaths:paths,step2:step2Regression,step3:step3Regression.status,multiSeed:after.totals,parentVsAfter:chronicParentVsAfter.deltas},null,2));if(!pass)process.exitCode=2;
}
module.exports={measureSeeds,parentMeasurements,recoveryHashAudit,RECOVERED_HASHES,AUTHORIZED_TAIL_HASHES};
if(process.argv[2]==='--measure-only')process.stdout.write(JSON.stringify(measureSeeds(JSON.parse(process.argv[3]))));else if(require.main===module)main();
