#!/usr/bin/env node
'use strict';
/* Step5: run shipped step71 setup in a browser-shaped root harness. */
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),H=require('../live_hybrid_session_v02'),E=require('../runtime/continuous_match_core'),P=require('../runtime/protagonist_match_controller'),A=require('../live_v06_scene_authority_browser');
function element(id=''){return{id,value:id==='heroPlayer'?'H-ST':'',hidden:false,disabled:false,checked:false,textContent:'',innerHTML:'',children:[],style:{},dataset:{},classList:{add(){},remove(){},contains(){return false;}},appendChild(x){this.children.push(x);return x},append(...x){this.children.push(...x)},remove(){},focus(){},click(){},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return this},getBoundingClientRect(){return{left:0,top:0,width:900,height:600}}};}
function rootSetup({search='',globalOptIn=false}){const byId=new Map(),created=[],get=id=>{if(!byId.has(id)){const e=element(id);if(id==='heroPitch'){e.width=900;e.height=600;e.getContext=()=>({clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}});}byId.set(id,e);}return byId.get(id);};
 const tracked={...H,createSession(opts){const s=H.createSession(opts);created.push(s);return s;}};
 const context={console,window:null,document:{getElementById:get,createElement:()=>element(),querySelectorAll:()=>[],body:element('body')},location:{search,href:`qa://step5${search}`},URLSearchParams,performance:{now:()=>1},requestAnimationFrame:()=>0,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},matchMedia:()=>({matches:false}),navigator:{clipboard:{writeText:()=>Promise.resolve()}},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FLRPG_CONTINUOUS_CORE:E,FLRPG_PROTAGONIST_MATCH_CONTROLLER:P,FLRPG_LIVE_HYBRID_SESSION_V02:tracked,FLRPG_LIVE_V06_SCENE_AUTHORITY:A,FLRPG_IN_PITCH_CHOICE_UI:null,FLR_QA_CONTINUOUS_SPATIAL_AUTHORITY_V2_COARSE:globalOptIn};
 context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8'),context,{filename:'step71_hybrid_v06_ui.js'});assert.equal(created.length,1,'ROOT_SETUP_DID_NOT_CREATE_EXACTLY_ONE_SESSION');return created[0];
}
function inspect(session){const before=H.authorityTraceSnapshot(session),advanced=H.advanceUntilBoundary(session,{maxActions:20000}),after=H.authorityTraceSnapshot(session);return{opts:session.opts,spatialSchema:session.state.spatial.schemaVersion,players:session.state.spatial.players.length,advanced:{status:advanced.status,boundary:advanced.boundary?.type||null},trace:{present:!!after,events:after?.events?.length||0,coarseSamples:after?.spatialSamples?.length||0,rootCoverage:after?.rootCoverage||null,createdTrace:!!before}};}
function run(){const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8'),v2=fs.readFileSync(path.join(ROOT,'runtime/continuous_spatial_authority_v2.js'),'utf8');const v2Index=index.indexOf('runtime/continuous_spatial_authority_v2.js'),hybridIndex=index.indexOf('live_hybrid_session_v02.js'),uiIndex=index.indexOf('step71_hybrid_v06_ui.js');assert(v2Index>=0&&v2Index<hybridIndex&&hybridIndex<uiIndex,'INDEX_ROOT_SCRIPT_ORDER_INVALID');assert(/function coarseEnabled\(opts\)/.test(v2)&&/COARSE_FEATURE_FLAG='continuousSpatialAuthorityV2Coarse'/.test(v2),'V2_COARSE_FLAG_NOT_SUPPORTED');assert(/H\.createSession\(\{[^}]*continuousSpatialAuthorityV2Coarse/.test(ui),'STEP71_DOES_NOT_FORWARD_COARSE_FLAG');
 const legacy=rootSetup({}),query=rootSetup({search:'?flr_qa_continuous_spatial_authority_v2_coarse=1'}),global=rootSetup({globalOptIn:true}),legacyRow=inspect(legacy),queryRow=inspect(query),globalRow=inspect(global);
 assert.strictEqual(legacyRow.opts.continuousSpatialAuthorityV2Coarse,undefined,'DEFAULT_LEGACY_CHANGED');for(const row of [queryRow,globalRow]){assert.strictEqual(row.opts.continuousSpatialAuthorityV2Coarse,true,'OPT_IN_NOT_FORWARDED_AT_ROOT');assert.equal(row.players,22,'ROOT_SESSION_PLAYER_COUNT');assert.equal(row.spatialSchema,'CONTINUOUS_SPATIAL_AUTHORITY_V2_COARSE_1.0','V2_COARSE_STATE_NOT_USED');assert(row.trace.present&&row.trace.createdTrace&&row.trace.events>0&&row.trace.coarseSamples>0&&row.trace.rootCoverage.hybrid,'STEP4_AUTHORITY_TRACE_NOT_OBSERVED');}
 return{schemaVersion:'V52_SPATIAL_AUTHORITY_V2_STEP5_INTERNAL_ROOT_GATE_1.0',verdict:'V52_SPATIAL_AUTHORITY_V2_STEP5_INTERNAL_READY',scope:'index script order + shipped step71 setup in a browser-shaped harness; real root-created sessions only; no position/outcome injection',rootFact:{priorSetupFlagAbsent:true,v2SupportsExactCoarseFlag:true},gates:{indexOrder:'PASS',legacyDefault:'PASS',queryOptIn:'PASS',globalOptIn:'PASS',step4AuthorityTrace:'PASS',noInjectedFinalPositionsOrOutcomes:'PASS'},runs:{legacy:legacyRow,query:queryRow,global:globalRow},qaEnablement:'Before root setup: add ?flr_qa_continuous_spatial_authority_v2_coarse=1, or set window.FLR_QA_CONTINUOUS_SPATIAL_AUTHORITY_V2_COARSE=true before step71 loads.',fullStep234Regression:'DEFERRED_TO_MODEL_FREE_SHELL'};
}
if(require.main===module){try{const out=run(),dir=path.join(ROOT,'evidence/v52');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'spatial_authority_v2_step5_internal_root_gate.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));}catch(e){console.error(e.stack);process.exitCode=1;}}
module.exports={run};
