const fs=require('fs'),path=require('path');
const V=require('../live_v06_scene_authority_browser');
const baseAutoResolveEpisode=V.autoResolveEpisode;
V.autoResolveEpisode=(opened,chooser,opts={})=>baseAutoResolveEpisode(opened,chooser,{...opts,maxChoices:Math.max(2,Number(opts.maxChoices)||0)});
const root=require('./v44_spatial_authority_v2_step2_root_gameplay.js');
const seeds=['LIVE-V03-1-H-ST','LIVE-V03-2-H-ST'];
function sign(v){return v>.02?1:v<-.02?-1:0}
function measure(seed){const r=root.runRoot(seed,true),F=r.trace?.spatialSamples||[],ids=F.length?(F[0].players||[]).map(p=>p.id):[],per=[];let reasonSamples=0;for(const f of F)for(const p of f.players||[])if(String(p.responsibilityReason||'').includes('TARGET_REACHED_REEVALUATION'))reasonSamples++;for(const id of ids){let lx=0,ly=0,n=0;for(let i=1;i<F.length;i++){const a=(F[i-1].players||[]).find(p=>p.id===id),b=(F[i].players||[]).find(p=>p.id===id);if(!a||!b)continue;const sx=sign(b.actual.x-a.actual.x),sy=sign(b.actual.y-a.actual.y);if(lx&&sx&&lx!==sx)n++;if(ly&&sy&&ly!==sy)n++;if(sx)lx=sx;if(sy)ly=sy}per.push(n)}per.sort((a,b)=>a-b);return{seed,errors:r.errors||[],sampleCount:F.length,reasonSamples,total:per.reduce((a,b)=>a+b,0),median:per.length?per[Math.floor(per.length/2)]:0,max:per.length?per[per.length-1]:0}}
const runs=seeds.map(measure);const pass=runs.every(x=>!x.errors.length&&x.reasonSamples===0&&x.total<2000&&x.max<140);const out={schemaVersion:'V53_COARSE_TARGET_PINGPONG_REGRESSION_1.0',runs,checks:{noTargetReachedSelfOffset:runs.every(x=>x.reasonSamples===0),boundedTotalFlips:runs.every(x=>x.total<2000),boundedMaxPlayerFlips:runs.every(x=>x.max<140),noRootErrors:runs.every(x=>!x.errors.length)},verdict:pass?'PASS':'FAIL',futureOutcomePrecomputed:false};fs.mkdirSync(path.join(__dirname,'../evidence/v53'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../evidence/v53/coarse_target_pingpong_regression.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(!pass)process.exit(12);
