'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),identity=require('../reporter_source_identity.js');
const SURFACES=['runtime/choice_resolution_harness.js','runtime/step38_influence_harness.js','final_match_rare_scenario_harness.js','final_match_forced_presentation_patch.js','final_match_v37_forced_harness_patch.js','final_match_test_dock.js','final_match_v37_test_visual_patch.js','v40_human_calibration_surface.js'];
const CSS=['final_match_test_dock.css','runtime/v40_human_calibration.css'];
const chain=()=>[...read('index.html').matchAll(/<script\b[^>]*\bsrc="([^"]+)"[^>]*><\/script>/g)].map(x=>x[1]);
const scene=()=>({matchSecond:81.2,boundaryIdOrSceneId:'V53-B2',heroPlayerId:'H-CM',heroRole:'CM',pendingChoice:{choiceIds:['PASS'],targetIds:['H-ST']},committedChoice:{choiceId:'PASS',targetId:'H-ST'},currentStateMarkers:{phase:'PROGRESSION'},futureOutcomePrecomputed:false});
const docFor=items=>({baseURI:'http://flr.local/index.html',querySelectorAll:s=>s==='script[src]'?items.map(src=>({getAttribute:k=>k==='src'?src:null})):[]});
async function sourceIdentity(){const actual=chain();assert.deepEqual(actual,identity.EXPECTED.scriptChain,'normal loader chain drift');assert(actual.includes('runtime/continuous_spatial_authority_v2.js'),'V2 active runtime omitted');assert(actual.includes('reporter_source_identity.js'),'identity helper omitted');assert(SURFACES.every(p=>!actual.includes(p)),'test-only script leaked into no-query chain');const current=await identity.capture(scene(),{doc:docFor(actual),fetcher:async p=>({ok:true,text:async()=>read(p)})});assert.equal(current.validation.classification,'CURRENT_MATCH');assert.equal(current.observedManifestSha256,identity.EXPECTED.manifestSha256);const mutation=structuredClone(current);mutation.sourceStatuses[0]={...mutation.sourceStatuses[0],sha256:'0'.repeat(64),status:'MISMATCH'};assert.equal(identity.validate(mutation).classification,'STALE_OR_MISMATCHED');return current;}
async function loaderContract(){const html=read('index.html');assert(CSS.every(p=>!new RegExp(`<link[^>]+href="${p.replace('/','\\/')}`,'i').test(html)),'test CSS leaked into no-query head');assert(!html.includes('id="finalMatchTestDock"'),'test dock shell leaked into no-query DOM');const sourceLiteral=html.match(/const sources=(\[[^;]+\]);let chain=/);assert(sourceLiteral,'test loader missing');assert.deepEqual(vm.runInNewContext(sourceLiteral[1]),SURFACES,'test loader surface order drift');assert(html.includes("q.get('flr_test_surfaces')==='1'"),'explicit test query missing');assert(html.includes("q.get('humanCalibration')==='1'"),'existing calibration opt-in missing');const loader=html.match(/<script>\(function\(d,w\)\{([\s\S]*?)<\/script>/);assert(loader,'inline test loader missing');async function observed(search){const added=[];const document={head:{appendChild:e=>added.push(['style',e.href])},body:{appendChild:e=>{added.push(['script',e.src]);e.onload?.()}},createElement:tag=>({tagName:tag})},window={location:{search}};vm.runInNewContext(`(function(d,w){${loader[1]}`,{document,window,URLSearchParams,Promise,console});await new Promise(resolve=>setImmediate(resolve));return added;}assert.deepEqual(await observed(''),[],'no-query loader executed test surfaces');assert.deepEqual(await observed('?flr_test_surfaces=1'),[...CSS.map(x=>['style',x]),...SURFACES.map(x=>['script',x])],'explicit test loader order drift');}
async function retry413(){const elements={heroBugReport:{disabled:false},heroBugOpenIssue:{disabled:false},heroBugModal:{hidden:true,querySelector:()=>null},heroBugDescription:{value:''},heroBugAttachJson:{checked:true,disabled:false}};const calls=[],window={FLR_BUG_REPORT_ENDPOINT:'https://report.test/report',fetch:async(_url,init)=>{calls.push(JSON.parse(init.body));return calls.length===1?{status:413,ok:false}:{status:201,ok:true}},document:null};const document={readyState:'complete',getElementById:id=>elements[id]||null};window.document=document;class Observer{observe(){}}const context={window,document,MutationObserver:Observer,setTimeout:fn=>{fn();return 1},clearTimeout(){},console,crypto:{randomUUID:()=>"qa"},location:{href:'http://flr.local/'},navigator:{userAgent:'qa'}};vm.runInNewContext(read('final_match_bug_report_ui.js'),context,{filename:'final_match_bug_report_ui.js'});await window.fetch(window.FLR_BUG_REPORT_ENDPOINT,{method:'POST',body:JSON.stringify({reportId:'r',description:'d',debug:{large:true},summary:{phase:'LIVE'}})});assert.equal(calls.length,2,'413 did not retry once');assert.deepEqual(calls[1].debug,null,'413 retry retained debug');assert.equal(calls[1].summary.captureStatus,'METADATA_ONLY');assert.equal(calls[1].summary.captureError,'FULL_DEBUG_REJECTED_413');}
async function run(){const current=await sourceIdentity();await loaderContract();await retry413();return{schemaVersion:'V53_STAGE2_BATCH2_TEST_SURFACE_IDENTITY_1.0',verdict:'PASS',normalRuntime:{scriptCount:current.indexScriptChain.length,coveredSourceCount:current.sourceStatuses.length,manifestSha256:current.manifestSha256,classification:current.validation.classification},testOnly:{optIn:'?flr_test_surfaces=1',humanCalibrationCompatibility:'?humanCalibration=1',isolatedScripts:SURFACES,isolatedStyles:CSS},bugReport:{metadataRetry413:'PASS'},gameplayChanged:false,deploymentChanged:false};}
if(require.main===module)run().then(x=>console.log(JSON.stringify(x,null,2))).catch(e=>{console.error(e.stack||e);process.exitCode=1});
module.exports={run};
