#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),H=require('../live_hybrid_session_v02'),V=require('../live_v06_scene_authority_browser'),Rare=require('../final_match_rare_scenario_harness');
const deep=x=>JSON.parse(JSON.stringify(x)),ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8'),ids=new Map();
function el(id){if(!ids.has(id))ids.set(id,{id,hidden:false,value:'H-ST',checked:false,children:[],style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},appendChild(x){this.children.push(x);return x},append(){},addEventListener(){},getBoundingClientRect(){return{left:0,top:0,right:900,bottom:600,width:900,height:600}},closest(){return stage},querySelector(){return null},querySelectorAll(){return[]},innerHTML:'',textContent:'',disabled:false});return ids.get(id)}
const stage=el('stage'),canvas=el('heroPitch');canvas.width=900;canvas.height=600;canvas.closest=()=>stage;canvas.getContext=()=>({clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}});
let uiHandback=null;const source=ui.replace(/setup\(\);requestAnimationFrame\(loop\);/,`window.__V53_CONTINUITY={ensure:ensureScoreEventIntegrity,decision:setPieceReplayDecision,finish:finishSetPieceHighRes,setContext(v){world=v.world;opened=v.opened;activeBoundary=v.boundary;beforeHybrid={};}};`);
const context={window:{},document:{getElementById:id=>id==='heroPitch'?canvas:el(id),createElement:t=>el('created-'+t),querySelectorAll:()=>[]},performance:{now:()=>0},requestAnimationFrame(){},setTimeout(){return 1},clearTimeout(){},setInterval(){},clearInterval(){},console,URLSearchParams,Math,Number,JSON,Date,location:{search:''},navigator:{clipboard:{writeText(){return Promise.resolve()}}}};context.window=context;context.window.FLRPG_CONTINUOUS_CORE={FIELD:{GOAL_Y1:30.34,GOAL_Y2:37.66},snapshot:x=>deep(x),createMatch:()=>({players:[]})};context.window.FLRPG_PROTAGONIST_MATCH_CONTROLLER={};context.window.FLRPG_LIVE_HYBRID_SESSION_V02={resumeFromHighRes(_world,hb){uiHandback=hb;_world.state.score={...hb.snapshot.score};}};context.window.FLRPG_HYBRID_SCENE_DEBUG={build:()=>({})};context.window.FLRPG_IN_PITCH_CHOICE_UI=null;context.window.matchMedia=()=>({matches:false});context.window.addEventListener=()=>{};vm.runInNewContext(source,context,{filename:'step71_hybrid_v06_ui.js'});
const U=context.__V53_CONTINUITY,entry={HOME:0,AWAY:0},goal={t:11,type:'GOAL',team:'AWAY',actorId:'A-ST',crossing:{x:0,y:34},text:'causal goal'},before={time:10.8,score:entry,ball:{x:2,y:34,mode:'FLIGHT'},players:[]},after={time:11,score:{HOME:0,AWAY:1},ball:{x:0,y:34,mode:'DEAD'},players:[]},liveState={m:{score:{HOME:0,AWAY:1},events:[goal]}};
const accepted=U.ensure(entry,{state:liveState,snapshot:deep(after),actualEvents:[],episodeFrames:[deep(before),deep(after)]});
const rejected=U.ensure(entry,{state:{m:{score:{HOME:0,AWAY:1},events:[]}},snapshot:{...deep(after),ball:{x:2,y:34}},actualEvents:[],episodeFrames:[deep(before),{...deep(after),score:{HOME:0,AWAY:0},ball:{x:2,y:34}}]});
const uiWorld={state:{score:{HOME:0,AWAY:0},resolvedEvents:[]}},uiOpened={state:liveState,entrySnapshot:{score:entry},snapshot:deep(after),actualEvents:[goal],frames:[deep(before),deep(after)]};U.setContext({world:uiWorld,opened:uiOpened,boundary:{sceneId:'V53-CORNER',stateSnapshot:{score:entry}}});U.finish();
const boundary=Rare.boundary('CORNER_ATTACK_RIGHT','V53-CORNER-CONTINUITY-0'),corner=V.runSetPieceWindow(boundary,{seed:'V53-CORNER-CONTINUITY-0|RUN',runtimeDir:path.join(ROOT,'runtime'),durationSeconds:12,continuationSafetySeconds:8}),decision=U.decision(corner,boundary);
const checks={acceptedCausalGoalKept:accepted.actualEvents.length===1&&accepted.snapshot.score.AWAY===1&&liveState.m.score.AWAY===1,syntheticDeltaRejected:rejected.actualEvents.filter(e=>e.type==='GOAL').length===0&&rejected.snapshot.score.AWAY===0&&rejected.state.m.score.AWAY===0,setPieceFinishPreservesLiveState:uiHandback?.state===liveState&&uiWorld.state.score.AWAY===1,cornerSecondBallContinuesVisibly:!!corner.setPieceContinuation&&decision.show===true&&decision.continuation?.startAt===corner.setPieceContinuation.startAt,cornerStopsAtNaturalTurnover:corner.setPieceContinuation?.endReason==='TURNOVER'&&!corner.pending,cornerNoFuturePrecompute:corner.futureOutcomePrecomputed===false};
const passed=Object.values(checks).every(Boolean),out={schemaVersion:'V53_SCORE_CORNER_CONTINUITY_R3_1.0',verdict:passed?'PASS':'FAIL',checks,facts:{acceptedScore:accepted.snapshot.score,rejectedScore:rejected.snapshot.score,corner:{start:corner.frames[0]?.time,end:corner.snapshot.time,continuation:corner.setPieceContinuation,events:corner.actualEvents.map(e=>e.type),pending:!!corner.pending}}};
fs.mkdirSync(path.join(ROOT,'evidence/v53/score_corner_continuity'),{recursive:true});fs.writeFileSync(path.join(ROOT,'evidence/v53/score_corner_continuity/RESULT.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(!passed)process.exit(1);
