'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(ROOT,file),'utf8'),H=require('../live_hybrid_session_v02.js');
const SLOTS=['GK','LB','LCB','RCB','RB','LCM','CM','RCM','LW','ST','RW'];
const ROLES={GK:'GK',LB:'FB',LCB:'CB',RCB:'CB',RB:'FB',LCM:'CM',CM:'CM',RCM:'CM',LW:'WF',ST:'ST',RW:'WF'};
const TEST_SURFACES=['runtime/choice_resolution_harness.js','runtime/step38_influence_harness.js','final_match_rare_scenario_harness.js','final_match_forced_presentation_patch.js','final_match_v37_forced_harness_patch.js','final_match_test_dock.js','final_match_v37_test_visual_patch.js','v40_human_calibration_surface.js'];
const TEST_STYLES=['final_match_test_dock.css','runtime/v40_human_calibration.css'];
function scriptChain(html){return[...html.matchAll(/<script\b[^>]*\bsrc="([^"]+)"[^>]*><\/script>/g)].map(match=>match[1]);}
function legacyKickoff(){const session=H.createSession({seed:'V53-LEGACY-NOQUERY-KICKOFF',heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST'}),snapshot=H.initialSpatialSnapshot(session);assert.equal(session.opts.continuousSpatialAuthorityV2Coarse,undefined,'normal Legacy kickoff unexpectedly enables V2 coarse authority');assert.equal(snapshot.futureOutcomePrecomputed,false,'kickoff snapshot must remain current-state only');assert.equal(snapshot.players.length,22,'kickoff must expose both complete teams');for(const [team,prefix,teamName] of [['HOME','H','블루팀'],['AWAY','A','레드팀']]){const players=snapshot.players.filter(player=>player.team===team);assert.equal(players.length,11,`${team} identity contract must expose 11 players`);for(const slot of SLOTS){const player=players.find(row=>row.id===`${prefix}-${slot}`);assert(player,`${team} ${slot} missing from kickoff`);assert.deepEqual({name:player.name,team:player.team,role:player.role,slot:player.slot},{name:`${teamName} ${slot}`,team,role:ROLES[slot],slot},`${player.id} display identity contract drift`);assert.notEqual(player.slot||player.role,undefined,`${player.id} renderer label is undefined`);}}return{mode:'COARSE_LEGACY',seed:session.opts.seed,players:snapshot.players.length,home:11,away:11};}
function playtestUi(){const html=read('index.html'),chain=scriptChain(html),developer=html.match(/<details class="developer-info">([\s\S]*?)<\/details>/)?.[1]||'';assert.equal((html.match(/id="heroBugReport"/g)||[]).length,1,'bug-report control must be unique');const controls=html.match(/<section class="control-panel">([\s\S]*?)<\/section>/)?.[1]||'';assert(controls.indexOf('id="heroNewSeed"')>=0&&controls.indexOf('id="heroBugReport"')>controls.indexOf('id="heroNewSeed"'),'bug-report control must directly follow New SEED in the control panel');assert(!/id="heroBugReport"[^>]*\bdisabled\b/.test(controls),'bug-report control must be immediately available');for(const text of ['V53','Playtest','[EXACT_SOURCE_SHA]','[KST_DEPLOY_TIME]'])assert(developer.includes(text),`developer-info missing ${text}`);for(const stale of ['TT-0.52','STEP78','검수 목적:','미래 선계산','선택 결과 선결정','2D 권한','Pre-action','PASS:'])assert(!developer.includes(stale),`developer-info retained obsolete text: ${stale}`);assert(TEST_SURFACES.every(file=>!chain.includes(file)),'test harness leaked into default no-query script chain');assert(TEST_STYLES.every(file=>!html.includes(`href="${file}"`)),'test stylesheet leaked into default no-query head');assert(!html.includes('id="finalMatchTestDock"'),'test dock leaked into default no-query DOM');assert(html.includes("q.get('flr_test_surfaces')==='1'"),'test surfaces must require explicit query opt-in');return{bugReport:'VISIBLE_UNIQUE_NEXT_TO_NEW_SEED',developerInfo:'V53_PLAYTEST_PLACEHOLDERS_ONLY',testSurfaces:'NO_QUERY_ISOLATED'};}
function run(){const kickoff=legacyKickoff(),ui=playtestUi();return{schemaVersion:'V53_LEGACY_PLAYTEST_UI_IDENTITY_LABELS_1.0',verdict:'PASS',kickoff,ui,gameplayChanged:false,deploymentChanged:false};}
if(require.main===module)try{console.log(JSON.stringify(run(),null,2));}catch(error){console.error(error.stack||error);process.exitCode=1;}
module.exports={run};
