#!/usr/bin/env node
'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),H=require('../live_hybrid_session_v02'),V=require('../live_v06_scene_authority_browser'),S=require('../runtime/continuous_spatial_authority_v2');
const ROOT=path.resolve(__dirname,'..'),deep=x=>JSON.parse(JSON.stringify(x)),hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const seed='V53-EXACT-CHOICE-CURRENT',session=H.createSession({seed,heroTeam:'HOME',heroRole:'ST',heroPlayerId:'H-ST',durationSeconds:180,continuousSpatialAuthorityV2Coarse:true,matchId:seed}),hero=session.state.spatial.players.find(p=>p.id==='H-ST');
S.advanceCoarseTo(session,8,{heroPlayerId:null,record:()=>{const sp=session.state.spatial,row=deep({...sp,boundaryId:null,rngState:session.rngState,eventId:'V53_ACTUAL_COARSE',possession:session.state.possession,phase:session.state.phase,score:session.state.score});S.appendActualHistory(session.actualHistory,row,'ACTUAL_COARSE_INTEGRATION',45);}});
Object.assign(session.state.ball,{mode:'CONTROLLED',kind:'CONTROL',ownerId:hero.id,lastTouchPlayerId:hero.id,lastTouchTeam:hero.team,x:hero.x,y:hero.y});S.syncBallDerived(session.state);const boundary=H.advanceUntilBoundary(session).boundary;assert.equal(boundary.type,'PROTAGONIST_2D_WINDOW');
const opened=V.runToChoice(boundary,{seed:`${seed}|${boundary.sceneId}|CURRENT`,runtimeDir:path.join(ROOT,'runtime')}),option=opened.state.pending?.options.find(o=>o.targetId)||opened.state.pending?.options[0];assert(option,'no current choice option');const noCommitBeforeChoice=(opened.state.m.userChoiceLog||[]).length===0&&!opened.state.m.events.some(e=>e.type==='USER_CHOICE'),before=hash({snapshot:opened.E.snapshot(opened.state.m),pending:opened.state.pending,rng:opened.state.m.r.observe()});let invalidRejected=false;try{V.applyChoiceAndAdvance(opened,option.id,'EXACT-TARGET-DOES-NOT-EXIST');}catch(error){invalidRejected=error.message==='CHOICE_TARGET_NOT_AVAILABLE';}const unchanged=before===hash({snapshot:opened.E.snapshot(opened.state.m),pending:opened.state.pending,rng:opened.state.m.r.observe()});const applied=V.applyChoiceAndAdvance(opened,option.id,option.targetId??null,{maxPostSeconds:1}),commitId=applied.applyReceipt.commitEventId,causal=applied.committedEvent||{},choiceCommit=applied.state.m.events.find(e=>e.type==='USER_CHOICE'&&e.commitEventId===commitId)||{},futureTrue=[];(function scan(v,p='root'){if(!v||typeof v!=='object')return;for(const[k,x]of Object.entries(v)){const q=`${p}.${k}`;if(k==='futureOutcomePrecomputed'&&x===true)futureTrue.push(q);else scan(x,q);}})({selectedChoice:applied.selectedChoice,applyReceipt:applied.applyReceipt,causalEvent:causal,choiceCommit,snapshot:applied.snapshot,nextPending:applied.nextPending});
const checks={protagonistBoundary:boundary.type==='PROTAGONIST_2D_WINDOW',noCommitBeforeChoice,invalidExactTargetRejected:invalidRejected,rejectionDidNotMutate:unchanged,choiceIdExact:applied.selectedChoice.id===option.id&&applied.applyReceipt.choice===option.id&&choiceCommit.choiceId===option.id,targetIdExact:(applied.applyReceipt.targetId??null)===(option.targetId??null)&&(choiceCommit.targetId??null)===(option.targetId??null)&&(causal.targetId??null)===(option.targetId??null),commitEventPresent:!!commitId&&causal.commitEventId===commitId&&choiceCommit.commitEventId===commitId,noFutureOutcomePrecomputed:applied.futureOutcomePrecomputed===false&&applied.applyReceipt.futureOutcomePrecomputed===false&&futureTrue.length===0},passed=Object.values(checks).every(Boolean),out={schemaVersion:'V53_EXACT_CHOICE_NO_PRECOMPUTE_1.0',verdict:passed?'PASS':'FAIL',checks,choiceId:option.id,targetId:option.targetId??null,receiptTargetId:applied.applyReceipt.targetId??null,committedChoiceId:choiceCommit.choiceId??null,committedTargetId:choiceCommit.targetId??null,causalEventType:causal.type??null,futureTrue};fs.writeFileSync(path.join(ROOT,'evidence/v53/sol_bugfix_bundle/PHASE_D_CHOICE_BOUNDARY.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(!passed)process.exit(1);
