'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(ROOT,file),'utf8'),sha=value=>crypto.createHash('sha256').update(value).digest('hex'),plain=value=>JSON.parse(JSON.stringify(value));
class MemoryD1{
  constructor(){this.reports=new Map();this.chunks=new Map()}
  prepare(sql){const db=this;return{bind(...args){return{sql,args,async first(){return db.reports.get(args[0])||null},async all(){if(sql.includes('FROM bug_report_chunks'))return{results:[...(db.chunks.get(args[0])||[])].sort((a,b)=>a.chunk_no-b.chunk_no)};let rows=[...db.reports.values()];if(sql.includes(' WHERE build=?'))rows=rows.filter(row=>row.build===args[0]);return{results:rows.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,args.at(-1))}}}}}}
  async batch(statements){for(const statement of statements){const args=statement.args;if(statement.sql.startsWith('INSERT INTO bug_reports'))this.reports.set(args[0],{report_id:args[0],build:args[1],created_at:args[2],category:args[3],priority:args[4],description:args[5],size_bytes:args[6],chunk_count:args[7],summary_json:args[8],debug_schema_version:args[9]});else if(statement.sql.startsWith('INSERT INTO bug_report_chunks')){const rows=this.chunks.get(args[0])||[];rows.push({report_id:args[0],chunk_no:args[1],data:args[2]});this.chunks.set(args[0],rows)}else throw new Error('unexpected D1 statement')}}
}
async function workerFor(db){const encoded=Buffer.from(read('bug-report-worker/worker.js')).toString('base64'),module=await import(`data:text/javascript;base64,${encoded}`),env={BUG_REPORT_DB:db,ALLOWED_ORIGIN:'https://1lisam.github.io'};return{async request(path,init={}){const headers=new Headers(init.headers||{});headers.set('origin','https://1lisam.github.io');return module.default.fetch(new Request(`https://report.test${path}`,{...init,headers}),env)}}}
function element(id){return{id,disabled:false,checked:true,hidden:true,value:'',textContent:'',style:{},focus(){},removeAttribute(){},addEventListener(){}}}
function largeDebug(){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_',parts=[];let n=0x13579bdf;for(let block=0;block<1500;block++){const chars=new Array(4096);for(let i=0;i<chars.length;i++){n=(n*1664525+1013904223)>>>0;chars[i]=alphabet[(n>>>26)&63]}parts.push(chars.join(''))}return{schemaVersion:'V53_LOSSLESS_DEBUG_1.0',captureKind:'BOUNDED_CURRENT_STATE',match:{second:53,phase:'OPEN_PLAY',heroPlayerId:'H-ST'},ball:{mode:'CONTROLLED',x:74.2,y:30.1,ownerId:'H-ST'},trace:parts.join(''),repeat:'R'.repeat(2_100_000),futureOutcomePrecomputed:false}}
async function postThroughUi(worker,debug){const elements={heroBugReport:element('heroBugReport'),heroBugOpenIssue:element('heroBugOpenIssue'),heroBugModal:element('heroBugModal'),heroBugDescription:element('heroBugDescription'),heroBugAttachJson:element('heroBugAttachJson'),heroBugCategory:{value:'QA'},heroBugPriority:{value:'3'},heroPlayback:element('heroPlayback')};elements.heroBugModal.querySelector=()=>({insertBefore(){}});const sent=[],window={FLR_BUG_REPORT_ENDPOINT:'https://report.test/report',FLR_CURRENT_BUG_STATE:()=>debug,fetch:async(url,init)=>{const payload=JSON.parse(init.body);sent.push(payload);return worker.request(new URL(url).pathname,{method:init.method,headers:init.headers,body:init.body})}};const context={window,document:{readyState:'complete',getElementById:id=>elements[id]||null,createElement:()=>element('link')},MutationObserver:class{observe(){}},setTimeout:fn=>{fn();return 1},clearTimeout(){},console,crypto:{randomUUID:()=>`lossless-0001`},location:{href:'http://flr.local/'},navigator:{userAgent:'qa'},CompressionStream,Response,TextEncoder,btoa:input=>Buffer.from(input,'binary').toString('base64')};context.fetch=(...args)=>window.fetch(...args);window.document=context.document;vm.runInNewContext(read('final_match_bug_report_ui.js'),context,{filename:'final_match_bug_report_ui.js'});elements.heroBugReport.onclick();elements.heroBugDescription.value='lossless compressed transport';await elements.heroBugOpenIssue.onclick();assert.equal(sent.length,1,'compressed transport should avoid 413 fallback');assert.equal(sent[0].debug,null,'new client sent raw debug');assert.equal(sent[0].debugTransport?.encoding,'gzip-base64-v1','new client transport encoding missing');assert(Buffer.byteLength(JSON.stringify(sent[0]))<8_000_000,'compressed request exceeds worker request limit');return sent[0].reportId}
async function recover(worker,reportId){const list=await (await worker.request('/report-list?limit=20')).json(),item=list.reports.find(row=>row.reportId===reportId);assert(item,'report-list omitted report');assert(item.hasDebug&&item.jsonUrl,'report-list did not expose recoverable JSON URL');const meta=await (await worker.request(`/report-meta/${reportId}`)).json();assert(meta.ok&&meta.jsonUrl===item.jsonUrl,'report-meta recovery URL drift');const debug=await (await worker.request(new URL(meta.jsonUrl).pathname)).json();return{item,meta,debug}}
async function run(){const db=new MemoryD1(),worker=await workerFor(db),debug=largeDebug(),raw=JSON.stringify(debug),rawHash=sha(raw);assert(Buffer.byteLength(raw)>7_500_000,'fixture does not exceed legacy raw-debug cap');const legacyId='qa-legacy-uncompressed-0001',legacyDebug={schemaVersion:'V37_LEGACY',state:{phase:'OPEN_PLAY',second:17},futureOutcomePrecomputed:false};const legacyResponse=await worker.request('/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reportId:legacyId,build:'V37',description:'legacy',category:'QA',priority:3,summary:{captureStatus:'FULL_DEBUG_REQUESTED'},debug:legacyDebug})});assert.equal(legacyResponse.status,201,'legacy uncompressed POST regressed');const reportId=await postThroughUi(worker,debug),recovered=await recover(worker,reportId),recoveredRaw=JSON.stringify(recovered.debug);assert.deepEqual(recovered.debug,plain(debug),'recovered debug differs from submitted debug');assert.equal(sha(recoveredRaw),rawHash,'recovered debug hash differs');assert.equal(Buffer.byteLength(recoveredRaw),Buffer.byteLength(raw),'recovered debug size differs');assert.equal(recovered.meta.sizeBytes,Buffer.byteLength(raw),'D1 metadata raw size differs');assert(recovered.meta.chunkCount>1&&db.chunks.get(reportId)?.length===recovered.meta.chunkCount,'bug_report_chunks persistence/split mismatch');const legacy=await recover(worker,legacyId);assert.deepEqual(legacy.debug,legacyDebug,'legacy D1 row recovery regressed');const result={schemaVersion:'V53_D1_BUG_REPORT_LOSSLESS_RECOVERY_1.0',verdict:'PASS',reports:[{id:reportId,metadata:{build:recovered.meta.build,hasDebug:recovered.meta.hasDebug,chunkCount:recovered.meta.chunkCount,storage:recovered.meta.storage},hashes:{submittedSha256:rawHash,recoveredSha256:sha(recoveredRaw)},sizes:{submittedBytes:Buffer.byteLength(raw),recoveredBytes:Buffer.byteLength(recoveredRaw),storedBytes:[...db.chunks.get(reportId)].reduce((n,row)=>n+Buffer.byteLength(row.data),0)},state:'list->meta->jsonUrl LOSSLESS'},{id:legacyId,metadata:{build:legacy.meta.build,hasDebug:legacy.meta.hasDebug,chunkCount:legacy.meta.chunkCount,storage:legacy.meta.storage},hashes:{recoveredSha256:sha(JSON.stringify(legacy.debug))},sizes:{recoveredBytes:Buffer.byteLength(JSON.stringify(legacy.debug))},state:'legacy uncompressed POST -> list->meta->jsonUrl LOSSLESS'}],outputPolicy:'IDs, metadata, hashes, sizes, and compact state summaries only'};console.log(JSON.stringify(result,null,2));return result}
if(require.main===module)run().catch(error=>{console.error(error.stack||error);process.exitCode=1});
module.exports={run};
