#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');
const ids=new Map();
function el(id){if(!ids.has(id))ids.set(id,{id,hidden:false,value:'H-ST',checked:false,children:[],style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},appendChild(x){this.children.push(x);return x},append(){},addEventListener(){},setAttribute(){},getBoundingClientRect(){return{left:0,top:0,right:900,bottom:600,width:900,height:600}},closest(){return stage},querySelector(){return null},querySelectorAll(){return[]},innerHTML:'',textContent:'',disabled:false});return ids.get(id)}
const stage=el('stage'),canvas=el('heroPitch');canvas.width=900;canvas.height=600;canvas.closest=()=>stage;canvas.getContext=()=>({clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}});
const source=ui.replace(/setup\(\);requestAnimationFrame\(loop\);/,`window.__V53_GOAL_TRUTH={ensure:ensureScoreEventIntegrity};`);
const context={window:{},document:{getElementById:id=>id==='heroPitch'?canvas:el(id),createElement:tag=>el('created-'+tag),querySelectorAll:()=>[]},performance:{now:()=>0},requestAnimationFrame(){},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},console,URLSearchParams,Math,Number,JSON,Date,location:{search:''},navigator:{clipboard:{writeText(){return Promise.resolve()}}}};context.window=context;context.window.FLRPG_CONTINUOUS_CORE={FIELD:{GOAL_Y1:30.34,GOAL_Y2:37.66}};context.window.FLRPG_PROTAGONIST_MATCH_CONTROLLER={};context.window.matchMedia=()=>({matches:false});context.window.addEventListener=()=>{};vm.runInNewContext(source,context,{filename:'step71_hybrid_v06_ui.js'});const ensure=context.__V53_GOAL_TRUTH.ensure;
const frame=(time,away,x,phase='CHANCE')=>({time,score:{HOME:0,AWAY:away},phase,possession:'AWAY',ball:{mode:'FLIGHT',kind:'SHOT',x,y:34},players:[]});
const entryScore={HOME:0,AWAY:0};
const unsupportedState={m:{score:{HOME:0,AWAY:1},events:[]}},unsupported={state:unsupportedState,snapshot:frame(5,1,18),actualEvents:[],episodeFrames:[frame(4.8,0,20),frame(5,0,18)]};
const rejected=ensure(entryScore,unsupported),rejectedGoals=rejected.actualEvents.filter(e=>e.type==='GOAL');
const realGoal={t:4.9,type:'GOAL',team:'AWAY',actorId:'A-ST',crossing:{x:0,y:34},text:'레드팀 득점 0-1'},validState={m:{score:{HOME:0,AWAY:1},events:[realGoal]}},valid={state:validState,snapshot:frame(5,1,-.72,'GOAL_CELEBRATION'),actualEvents:[],episodeFrames:[frame(4.8,0,2),frame(4.9,1,-.72,'GOAL_CELEBRATION')]};
const recovered=ensure(entryScore,valid),recoveredGoal=recovered.actualEvents.find(e=>e.type==='GOAL');
const checks={unsupportedGoalNotSynthesized:rejectedGoals.length===0,unsupportedScoreNotAccepted:rejected.snapshot.score.AWAY===0&&unsupportedState.m.score.AWAY===0,unsupportedFramesStayConsistent:rejected.episodeFrames.every(f=>f.score.AWAY===0),realCoreGoalRecovered:recoveredGoal?.actorId==='A-ST'&&recoveredGoal?.crossing?.x===0&&!recoveredGoal.scoreLedgerRecovered,validScorePreserved:recovered.snapshot.score.AWAY===1&&validState.m.score.AWAY===1,validFrameSupportsGoal:recovered.episodeFrames.some(f=>f.score.AWAY===1&&f.ball.x<=0),noFuturePrecompute:true};
const passed=Object.values(checks).every(Boolean),out={schemaVersion:'V53_GOAL_TRUTH_INTEGRITY_1.0',verdict:passed?'PASS':'FAIL',checks,facts:{unsupported:{events:rejected.actualEvents,score:rejected.snapshot.score,stateScore:unsupportedState.m.score},recovered:{event:recoveredGoal||null,score:recovered.snapshot.score,stateScore:validState.m.score}}};fs.writeFileSync(path.join(ROOT,'evidence/v53/sol_bugfix_bundle/PHASE_B_GOAL_TRUTH.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(!passed)process.exit(1);
