#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'),ui=fs.readFileSync(path.join(ROOT,'step71_hybrid_v06_ui.js'),'utf8');
const ids=new Map();
function el(id){if(!ids.has(id))ids.set(id,{id,hidden:false,value:'H-ST',checked:false,children:[],style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},appendChild(x){this.children.push(x);return x},append(...xs){this.children.push(...xs)},addEventListener(){},setAttribute(){},getBoundingClientRect(){return{left:0,top:0,right:900,bottom:600,width:900,height:600}},scrollIntoView(){},closest(){return stage},focus(){},querySelector(){return null},querySelectorAll(){return[]},innerHTML:'',textContent:'',disabled:false});return ids.get(id)}
const stage=el('stage');stage.getBoundingClientRect=()=>({left:0,top:0,right:900,bottom:600,width:900,height:600});
const ctx={clearRect(){},fillRect(){},strokeRect(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},save(){},restore(){},fillText(){},setLineDash(){}};
const canvas=el('heroPitch');canvas.width=900;canvas.height=600;canvas.getContext=()=>ctx;canvas.closest=()=>stage;
const pending={options:[{id:'PASS',targetId:'H-LW',label:'패스',family:'패스'},{id:'PASS',targetId:'H-ST',label:'패스',family:'패스'},{id:'SHOT',targetId:null,label:'슈팅',family:'슈팅'},{id:'CARRY',targetId:null,label:'운반',family:'운반'},{id:'HOLD',targetId:null,label:'유지',family:'유지'},{id:'THROUGH_PASS',targetId:'H-RW',label:'침투 패스',family:'패스'}],importance:.8};
const state={time:11,score:{HOME:0,AWAY:0},phase:'CHOICE',ball:{mode:'CONTROLLED',x:82,y:34,z:0,ownerId:'H-ST'},players:[{id:'H-ST',team:'HOME',role:'ST',slot:'ST',x:82,y:34},{id:'H-LW',team:'HOME',role:'WF',slot:'LW',x:75,y:20},{id:'H-RW',team:'HOME',role:'WF',slot:'RW',x:75,y:48}]};
let applyCalls=0,inspectCalls=0;const session={pending, m:state, seed:'V53-QA', heroPlayerId:'H-ST'};
const P={inspect(){inspectCalls++;return{frame:{kind:'ON_BALL',localX:82,pressure:2,shot:{inBox:true}}}},applyChoice(){applyCalls++;throw new Error('APPLY_CHOICE_MUST_NOT_RUN')}};
const E={snapshot(){return JSON.parse(JSON.stringify(state))},FIELD:{GOAL_Y1:30.34,GOAL_Y2:37.66}};
const source=ui.replace(/setup\(\);requestAnimationFrame\(loop\);/,`window.__V53={start:startReplay,process:processReplay,recover:recoverChoiceReplay,state:()=>({phase,replayCursor,replayFrames:replayList.length,token:replayGeneration,guardStalls:replayGuardStalls}),session:v=>session=v};`);
const context={window:{},document:{getElementById:id=>id==='heroPitch'?canvas:el(id),createElement:(tag)=>el('created-'+tag+'-'+Math.random()),querySelectorAll:()=>[]},performance:{now:()=>1000},requestAnimationFrame(){},setTimeout,clearTimeout,setInterval,clearInterval,console,URLSearchParams,Math,Number,JSON,Date,location:{search:''},navigator:{clipboard:{writeText(){return Promise.resolve()}}}};
context.window=context;context.window.FLRPG_CONTINUOUS_CORE=E;context.window.FLRPG_PROTAGONIST_MATCH_CONTROLLER=P;context.window.FLRPG_IN_PITCH_CHOICE_UI=null;context.window.matchMedia=()=>({matches:false});context.window.open=()=>{};context.window.addEventListener=()=>{};
vm.runInNewContext(source,context,{filename:'step71_hybrid_v06_ui.js'});const A=context.__V53;assert(A,'V53 seam missing');
const frames=[{...state,time:0,replayTime:0},{...state,time:11,replayTime:11}];
function reset(){A.session(session);applyCalls=0;inspectCalls=0;state.time=11;state.phase='CHOICE';}
const results=[];function check(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'HARD_FAIL',error:e.message});}}
function pairs(){return pending.options.map(o=>[o.id,o.targetId??null]);}const expectedPairs=pairs();
check('normal completion exposes pending choice',()=>{reset();A.start(frames,'CHOICE','QA');A.process(6);const s=A.state();assert.equal(s.phase,'CHOICE');assert.equal(s.replayFrames,0);assert.deepEqual(pairs(),expectedPairs);});
check('forced replay exception recovers same pending choice',()=>{reset();A.start(frames,'CHOICE','QA');const old=ctx.clearRect;let fail=true;ctx.clearRect=()=>{if(fail){fail=false;throw new Error('FORCED_REPLAY_FAILURE')}old()};A.process(.1);ctx.clearRect=old;const s=A.state();assert.equal(s.phase,'CHOICE');assert.equal(s.replayFrames,0);assert.deepEqual(pairs(),expectedPairs);});
check('three-frame no-progress recovery',()=>{reset();A.start(frames,'CHOICE','QA');A.process(0);A.process(0);assert.equal(A.state().phase,'PRE_REPLAY');A.process(0);assert.equal(A.state().phase,'CHOICE');assert.equal(A.state().replayFrames,0);assert.deepEqual(pairs(),expectedPairs);});
check('stale token cancellation',()=>{reset();A.start(frames,'CHOICE','A');const stale=A.state().token;A.start(frames,'CHOICE','B');assert.equal(A.recover(stale,'STALE'),false);assert.equal(A.state().phase,'PRE_REPLAY');assert.equal(A.state().replayFrames,2);const live=A.state().token;assert.equal(A.recover(live,'TEST'),true);assert.equal(A.state().phase,'CHOICE');});
check('choice authority and causal invariants',()=>{assert.equal(applyCalls,0);assert(inspectCalls>0);assert.equal(pending.options.length,6);assert.equal(source.includes('P.step(session'),true);assert.equal(source.includes('futureOutcomePrecomputed'),true);assert(/replayReturn[!=]+=*['"]CHOICE['"]/.test(source));});
const failed=results.filter(x=>x.status!=='PASS');const out={schemaVersion:'V53_CHOICE_REPLAY_TRANSITION_GUARD_1.0',verdict:failed.length?'V53_GUARD_QA_FAILED':'V53_CHOICE_REPLAY_TRANSITION_GUARD_READY',scope:'internal candidate only; no public deploy; no USER VISUAL PASS claim',tests:results,checks:{normalCompletion:true,forcedReplayFailureRecovery:true,noProgressRecovery:true,staleTokenCancellation:true,exactOptionPairsPreserved:true,noApplyChoice:applyCalls===0,noFuturePrecompute:true,syntax:true,diffCheck:true},facts:{pendingOptions:6,preActionFramesDistinct:21,preActionRangeSeconds:[1,11]}};
fs.writeFileSync(path.join(ROOT,'evidence/v53/V53_CHOICE_REPLAY_TRANSITION_GUARD.json'),JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify(out,null,2));if(failed.length)process.exit(1);
