#!/usr/bin/env node
'use strict';
/*
 * V56 D0: observation-only contract.  Fixtures are parsed from the existing
 * browser harness; this file never imports, patches, or writes runtime code.
 */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..');
const E=require(path.join(ROOT,'runtime/continuous_match_core.js'));
const A=require(path.join(ROOT,'runtime/attribute_match_adapter.js'));
const M=require(path.join(ROOT,'runtime/manager_tendency_adapter.js'));
const T=require(path.join(ROOT,'runtime/tactical_movement.js'));
const HARNESS=path.join(ROOT,'single_state_continuity_test.js');
const OUT=path.join(ROOT,'evidence/v56/d0_offball_failure_contract.json');
const MANIFEST_OUT=path.join(ROOT,'evidence/v56/d0_offball_case_manifest.json');
const DT=.05,WINDOW_SECONDS=20,SEED='SINGLE-V56-1-H-ST';
const SHA=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const round=n=>Number(Number(n||0).toFixed(4));
const stable=v=>JSON.stringify(v,Object.keys(v||{}).sort());
const digest=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const harnessSource=fs.readFileSync(HARNESS,'utf8');

// The case text is ground-truth user reporting.  It is deliberately separate
// from the current deterministic result below.
const CASES=[
  ['01','CB_ST_HANDOFF','CURRENT','RB abandons LW.'],['02','CB_ST_HANDOFF','LOCKED_MARK','Free-kick phase CBs abandon ST.'],['03','CB_ST_HANDOFF','ZONAL_RELATION','LCM takes RW while LB idles; late LB handoff.'],
  ['04','ST_DROP','CURRENT','Abrupt LCB/LCM swaps; ST ownership churn; LCM runs away.'],['05','ST_DROP','LOCKED_MARK','RCM deep-marks charging LW while RB idles; ST is dragged toward CM.'],['06','ST_DROP','ZONAL_RELATION','Wide inversion; attacking LB advances and leaves RW.'],
  ['07','WIDE_HANDOFF','CURRENT','Ball-owner change makes RB leave LW for LCM; other wide threat opens.'],['08','WIDE_HANDOFF','LOCKED_MARK','Midfield bunch/freeze; double ownership then exchange; opposite LB vacates.'],['09','WIDE_HANDOFF','ZONAL_RELATION','LB front-marks RW and is beaten; both FBs ignore adjacent wingers and advance.'],
  ['10','CM_RUNNER','CURRENT','LW becomes deep primary on RW; LB/RCB idle; both wingers too deep.'],['11','CM_RUNNER','LOCKED_MARK','RCB loses duty; opposite winger suddenly becomes deep marker.'],['12','CM_RUNNER','ZONAL_RELATION','Support arrival causes FB release/reacquire; RCB idle.'],
  ['13','LINE_PUSH','CURRENT','ST/LW chase LCB carrier unnaturally; one FB advances and leaves same-side attacker.']
].map(([caseId,scenarioId,policy,userObservation])=>({caseId:`CASE_${caseId}`,scenarioId,policy,userObservation,requiredEvent:caseId==='02'?'RESTART_OR_SET_PIECE_LIVE':'CURRENT_OFFBALL_RELATION_OR_MOTION',expectedObservationWindow:{harnessCompareSeconds:{start:0,end:WINDOW_SECONDS},motorStepCalls:WINDOW_SECONDS/DT},seed:SEED,dt:DT}));

function between(src,start,end){const a=src.indexOf(start);if(a<0)throw new Error(`SOURCE_TOKEN_MISSING:${start}`);const b=end?src.indexOf(end,a+start.length):src.length;return src.slice(a,b<0?src.length:b);}
function scenarioSource(key){const start=`if(key==='${key}')`;const a=harnessSource.indexOf(start);if(a<0)throw new Error(`SCENARIO_MISSING:${key}`);const b=harnessSource.indexOf("}else if(key==='",a+start.length);return harnessSource.slice(a,b<0?harnessSource.indexOf('\n}',a):b);}
function parsePositions(text){const rows=[];const re=/setPlayerPos\(m,'([^']+)',\s*([-\d.]+),\s*([-\d.]+)\)/g;let x;while((x=re.exec(text)))rows.push({id:x[1],x:Number(x[2]),y:Number(x[3])});return rows;}
const baselinePositions=parsePositions(between(harnessSource,'function baselineOpenPlay(m){','function forcePossession'));
function fixtureDefinition(key){
  if(key==='NATURAL')return{positions:[],mark:null,owner:null};
  const text=scenarioSource(key),positions=parsePositions(text),mark=/markTargetId='([^']+)'/.exec(text)?.[1]||null,owner=/forcePossession\(m,'([^']+)'\)/.exec(text)?.[1]||null,markOwner=/p\.id==='([^']+)'\);if\([^)]*\)[^;]*\.markTargetId=/.exec(text)?.[1]||null;
  return{positions,mark,markOwner,owner,sourceHash:crypto.createHash('sha256').update(text).digest('hex')};
}
function player(m,id){return m.playersById[id]||m.players.find(p=>p.id===id)||null;}
function resetPosition(m,row){const p=player(m,row.id);if(!p)return;p.x=row.x;p.y=row.y;p.tx=row.x;p.ty=row.y;p.vx=0;p.vy=0;p.sprint=false;p.runUntil=0;p.runType=null;p.markTargetId=null;p.responsibilityTargetId=null;p.responsibilityType=null;}
function applyFixture(m,key){
  if(key==='NATURAL')return;
  for(const row of baselinePositions)resetPosition(m,row);
  m.restart=null;m.setPieceLive=null;m.goalCelebration=null;m.completed=false;m.phase='OPEN_PLAY';m.time=600;m.nextShape=0;m.transitionUntil=0;
  m._defenceRoleLocks={};m._defensiveResponsibility={};m._markLocks={};m._transitionWideVacancies={};
  const def=fixtureDefinition(key);for(const row of def.positions)resetPosition(m,row);
  const initialMarker=def.mark&&def.markOwner?player(m,def.markOwner):null;if(initialMarker)initialMarker.markTargetId=def.mark;
  if(def.owner){const p=player(m,def.owner),bridge=E.choiceActionBridge();for(const q of m.players)q.hasBall=false;if(bridge?.setControlled)bridge.setControlled(m,p,true);else{p.hasBall=true;m.possession=p.team;m.ball.ownerId=p.id;m.ball.mode='CONTROLLED';m.ball.x=p.x;m.ball.y=p.y;}m.nextShape=0;}
}
function create(policy,scenario){const m=E.createMatch(SEED);for(const p of m.players)A.assign(m,p.id,A.baseProfile(60));M.init(m,{HOME:'BALANCED',AWAY:'BALANCED'});m.offBallPolicy=policy;applyFixture(m,scenario);return m;}
function local(team,p){return team==='HOME'?{x:p.x,y:p.y}:{x:105-p.x,y:68-p.y};}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function targetFor(p){return p.finalMovementIntent?.targetId||p.responsibilityTargetId||p.markTargetId||null;}
function relevantIds(scenario){const d=fixtureDefinition(scenario),ids=new Set([d.owner,d.mark,d.markOwner]);for(const p of d.positions)ids.add(p.id);return[...ids].filter(Boolean).sort();}
function serialPlayer(p){const fi=p.finalMovementIntent;return{id:p.id,team:p.team,role:p.role,slot:p.slot,x:round(p.x),y:round(p.y),vx:round(p.vx),vy:round(p.vy),bodyAngle:Number.isFinite(p.bodyAngle)?round(p.bodyAngle):null,faceTargetAngle:Number.isFinite(p.faceTargetAngle)?round(p.faceTargetAngle):null,tx:round(p.tx),ty:round(p.ty),finalMovementIntent:fi?{x:round(fi.targetPoint?.x),y:round(fi.targetPoint?.y),type:fi.type||null,targetId:fi.targetId||null,reason:fi.reason||null,writer:fi.writer||null,stepId:fi.stepId||null}:null,tacticalTask:p.tacticalTask||null,action:p.action||null,markTargetId:p.markTargetId||null,responsibilityType:p.responsibilityType||null,responsibilityTargetId:p.responsibilityTargetId||null,responsibilityReason:p.responsibilityReason||null,responsibilityEpoch:Number.isFinite(p.responsibilityEpoch)?p.responsibilityEpoch:null,writer:p.movementWriter||p.targetWriter||null};}
function ballState(m){const b=m.ball||{};return{mode:b.mode||null,ownerId:b.ownerId||null,intendedReceiverId:b.intendedReceiverId||b.flightReceiverId||null,flightReceiverId:b.flightReceiverId||b.intendedReceiverId||null,x:round(b.x),y:round(b.y),vx:round(b.vx),vy:round(b.vy),possession:m.possession||null,phase:m.phase||null,restart:m.restart?{kind:m.restart.kind||null,stage:m.restart.stage||null,team:m.restart.team||null}:null,setPieceLive:m.setPieceLive?{kind:m.setPieceLive.kind||null,team:m.setPieceLive.team||null}:null};}
function responsibility(m,team,ids){const r=m._defensiveResponsibility?.[team]||null;if(!r)return null;const selected=new Set(ids);selected.add(r.primaryPressureOwnerId);selected.add(r.coverOwnerId);return{team,at:round(r.at),primaryPressureOwnerId:r.primaryPressureOwnerId||null,primaryPressureTargetId:r.primaryPressureTargetId||null,coverOwnerId:r.coverOwnerId||null,unownedThreatIds:r.diagnostics?.unownedThreatIds||[],duplicateThreats:r.diagnostics?.duplicateThreats||[],duplicatePressureOwnerIds:r.diagnostics?.duplicatePressureOwnerIds||[],records:Object.fromEntries(Object.entries(r.records||{}).filter(([id])=>selected.has(id)).map(([id,x])=>[id,{type:x.type,targetId:x.targetId||null,reason:x.reason||null,epoch:x.epoch||null,handoffReason:x.handoffReason||null}]))};}
function capture(m,ids,tick){const active=new Set(ids);for(const team of ['HOME','AWAY']){const r=m._defensiveResponsibility?.[team];active.add(r?.primaryPressureOwnerId);active.add(r?.coverOwnerId);}return{tick,time:round(m.time),shapeDecisionTick:Math.abs((m.nextShape||0)-m.time)<DT/2,ball:ballState(m),responsibility:{HOME:responsibility(m,'HOME',active),AWAY:responsibility(m,'AWAY',active)},players:[...active].filter(Boolean).sort().map(id=>serialPlayer(player(m,id))).filter(Boolean)};}
function routeMateriality(m,defTeam){return m.players.filter(p=>p.team!==defTeam&&p.role!=='GK').map(a=>{const l=local(defTeam,a),speedTowardOwn=defTeam==='HOME'?-(a.vx||0):(a.vx||0),wide=Math.abs(l.y-34)>=14,central=Math.abs(l.y-34)<=15,entry=Math.max(0,55-l.x)+Math.max(0,speedTowardOwn)*1.2;return{id:a.id,role:a.role,localX:round(l.x),localY:round(l.y),speedTowardOwn:round(speedTowardOwn),entryMateriality:round(entry),material:(central&&l.x<=55&&['ST','CM','WF'].includes(a.role))||(wide&&l.x<=49&&['WF','FB'].includes(a.role))};});}
function credibleOwner(m,team,ownerId,targetId){const o=player(m,ownerId),a=player(m,targetId);if(!o||!a||o.team!==team)return{credible:false,reason:'MISSING'};const ol=local(team,o),al=local(team,a),d=dist(o,a),goalSide=ol.x<=al.x+1.5,approved=targetFor(o)===targetId||o.responsibilityTargetId===targetId||o.markTargetId===targetId,desired=Math.atan2(a.y-o.y,a.x-o.x),face=Number.isFinite(o.faceTargetAngle)?o.faceTargetAngle:o.bodyAngle,faceError=Number.isFinite(face)?Math.abs(Math.atan2(Math.sin(face-desired),Math.cos(face-desired))):null;return{credible:d<=18&&goalSide&&approved&&(faceError==null||faceError<=2.45),distance:round(d),goalSide,approved,faceError:faceError==null?null:round(faceError)};}
function guards(m){
  const failures=[],notes=[],all=[];
  for(const team of ['HOME','AWAY']){
    const r=m._defensiveResponsibility?.[team];if(!r)continue;const mats=routeMateriality(m,team);all.push({team,material:mats.filter(x=>x.material)});
    for(const t of mats.filter(x=>x.material)){
      const owners=Object.entries(r.records||{}).filter(([,v])=>v.targetId===t.id&&v.type==='MARK').map(([id])=>id);
      if(owners.length===1&&!credibleOwner(m,team,owners[0],t.id).credible){const q=player(m,owners[0]);const recovery=/RECOVERY|EMERGENCY/.test(String(q?.tacticalTask||''));(recovery?notes:failures).push({oracle:recovery?'I08_BEATEN_RECOVERY_CONTEXT':'I03_CREDIBLE_OWNER_GEOMETRY',team,targetId:t.id,ownerId:owners[0]});}
      if(owners.length>1)failures.push({oracle:'I04_PRIMARY_MARK_DOUBLE_COUNT',team,targetId:t.id,ownerIds:owners});
      if(!owners.length&&t.entryMateriality>=8)notes.push({oracle:'I11_EXPLICIT_DEFICIT',team,targetId:t.id});
    }
    const press=r.primaryPressureOwnerId,cover=r.coverOwnerId;if(press&&cover&&press===cover)failures.push({oracle:'I04_PRESS_COVER_SEPARATION',team,actorId:press});
    for(const [id,x] of Object.entries(r.records||{})){const p=player(m,id);if(!p)continue;if(['ST','WF'].includes(p.role)&&x.type==='MARK'&&x.targetId){const pl=local(team,p);if(pl.x<42&&!String(p.tacticalTask||'').includes('PRESS')&&!m.restart)notes.push({oracle:'I06_DEEP_FORWARD_CONTEXT_WATCH',team,actorId:id,targetId:x.targetId});}}
    const central=m.players.filter(p=>p.team===team&&['CB','CM'].includes(p.role)).filter(p=>{const l=local(team,p);return l.x<=38&&Math.abs(l.y-34)<=15;});if(mats.some(x=>x.material&&Math.abs(x.localY-34)<=15)&&central.length<2)failures.push({oracle:'I07_CENTRAL_CORRIDOR_CONTINUITY',team,count:central.length});
  }
  // I05 is an attacking/rest-defence guard, so it is intentionally assessed on
  // the possessing team rather than borrowed from the defending responsibility label.
  const attackTeam=m.possession;if(['HOME','AWAY'].includes(attackTeam)&&m.ball.mode==='CONTROLLED'){
    const central=m.players.filter(p=>p.team===attackTeam&&['CB','CM'].includes(p.role)).filter(p=>{const l=local(attackTeam,p);return l.x<=40&&Math.abs(l.y-34)<=16;});
    for(const fb of m.players.filter(p=>p.team===attackTeam&&p.role==='FB')){const l=local(attackTeam,fb),side=fb.slot==='LB'?'LEFT':'RIGHT',same=m.players.filter(a=>a.team!==attackTeam&&['WF','FB'].includes(a.role)).filter(a=>{const al=local(attackTeam,a);return(side==='LEFT'?al.y<34:al.y>34)&&al.x<=52;});const acquired=same.every(a=>m.players.some(q=>q.team===attackTeam&&q.id!==fb.id&&targetFor(q)===a.id));if(l.x>46&&same.length&&!acquired&&central.length<3)failures.push({oracle:'I05_FB_VACANCY_SAFETY',team:attackTeam,actorId:fb.id});}
  }
  return{failures,notes,materiality:all};
}
function stateDigest(m){const snap=E.snapshot(m);return digest({snapshot:snap,rng:m.r?.observe?.()||null,defence:m._defensiveResponsibility||null,locks:m._defenceRoleLocks||null,markLocks:m._markLocks||null,transition:m._transitionWideVacancies||null});}
function run(policy,scenario,instrument){const m=create(policy,scenario),ids=relevantIds(scenario),trace=[],endpoints=[];for(let tick=0;tick<=Math.round(WINDOW_SECONDS/DT);tick++){if(instrument)trace.push({...capture(m,ids,tick),oracles:guards(m)});endpoints.push(stateDigest(m));if(tick<WINDOW_SECONDS/DT)E.step(m,DT);}return{m,trace,endpoints,initialHash:stateDigest(create(policy,scenario)),ids};}
function transitionEvents(trace){const events=[];for(let i=1;i<trace.length;i++){for(const team of ['HOME','AWAY']){const before=trace[i-1].responsibility[team]?.records||{},after=trace[i].responsibility[team]?.records||{};for(const [id,old] of Object.entries(before)){const now=after[id];if(old.targetId&&(!now||now.targetId!==old.targetId)){const successors=Object.entries(after).filter(([sid,x])=>sid!==id&&x.targetId===old.targetId&&x.type==='MARK').map(([sid])=>sid);events.push({tick:trace[i].tick,time:trace[i].time,team,predecessorId:id,targetId:old.targetId,successorIds:successors,kind:successors.length?'OWNER_CHANGE':'RELEASE'});}}}}return events;}
function classify(trace,requiredEvent){const transitions=transitionEvents(trace),failureRows=trace.flatMap(r=>r.oracles.failures.map(x=>({...x,tick:r.tick,time:r.time})));const eventObserved=requiredEvent==='RESTART_OR_SET_PIECE_LIVE'?trace.some(r=>r.ball.restart||r.ball.setPieceLive):(transitions.length>0||trace.some(r=>r.ball.restart||r.ball.setPieceLive));if(!eventObserved)return{status:'NOT_EXERCISED',reason:requiredEvent==='RESTART_OR_SET_PIECE_LIVE'?'RESTART_OR_SET_PIECE_LIVE_NOT_PRESENT_IN_CURRENT_FORCED_FIXTURE':'NEEDED_HANDOFF_OR_PHASE_TRANSITION_NOT_OBSERVED',incidentalOracleSignals:failureRows.slice(0,12),failureCount:0,examples:[],eventObserved:false};if(failureRows.length)return{status:'BASELINE_FAIL',reason:'GENERALIZED_ORACLE_VIOLATION',failureCount:failureRows.length,examples:failureRows.slice(0,12),eventObserved};return{status:'WATCH',reason:'CURRENT_TRACE_HAS_RELEVANT_TRANSITION_BUT_NO_GENERALIZED_ORACLE_PROOF_OF_REPORTED_VISUAL_FAILURE',failureCount:0,examples:[],eventObserved:true};}
function positiveControls(rows,probes=[]){const all=[...rows,...probes].flatMap(x=>x.trace);const has=(id,predicate)=>({id,status:all.some(predicate)?'OBSERVED_VALID':'NOT_EXERCISED',scope:'current-state fixture traces only'});return[
  has('VALID_CB_STEP_OUT_WITH_CENTRAL_PROTECTION',r=>r.players.some(p=>p.role==='CB'&&p.tacticalTask&&/MARK|PRESS|ENGAGE/.test(p.tacticalTask))&&r.oracles.failures.every(x=>x.oracle!=='I07_CENTRAL_CORRIDOR_CONTINUITY')),
  has('VALID_COMPLETED_HANDOFF_THEN_RELEASE',r=>false), // evaluated below from transition evidence
  has('VALID_AGGRESSIVE_FB_WITH_ACQUIRED_COVER',r=>r.players.some(p=>p.role==='FB'&&/OVERLAP|UNDERLAP|SURGE|INVERT/.test(p.tacticalTask||''))&&r.oracles.failures.every(x=>x.oracle!=='I05_FB_VACANCY_SAFETY')),
  has('VALID_ONE_FB_ASYMMETRY_WITH_OPPOSITE_BALANCE',r=>{const f=r.players.filter(p=>p.role==='FB');return f.length>=2&&Math.abs(f[0].x-f[1].x)>7;}),
  has('VALID_HIGH_PRESS_OR_FORWARD_PRESS_SUPPORT',r=>r.players.some(p=>/PRESS|ENGAGE|CLOSE_DOWN/.test(p.tacticalTask||''))),
  has('VALID_WF_DEEP_TRACK_WITH_COHERENT_STRUCTURE',r=>r.players.some(p=>p.role==='WF'&&/MARK|TRACK|PRESS/.test(p.tacticalTask||''))&&r.oracles.failures.every(x=>x.oracle!=='I07_CENTRAL_CORRIDOR_CONTINUITY')),
  has('VALID_STATIONARY_HOLD_OR_COVER',r=>r.players.some(p=>Math.hypot(p.vx,p.vy)<.12&&/HOLD|COVER|REST_DEFENCE/.test(p.tacticalTask||''))),
  has('ACTUAL_THREAT_CHANGE_PERMITS_REASSIGNMENT',r=>r.ball.ownerId&&r.ball.mode==='CONTROLLED')
];}
function permutationProbe(){const rows=[];for(const c of CASES){const normal=create(c.policy,c.scenarioId),reversed=create(c.policy,c.scenarioId);reversed.players.reverse();reversed.playersById=Object.fromEntries(reversed.players.map(p=>[p.id,p]));const team=normal.possession==='HOME'?'AWAY':'HOME',owner=player(normal,normal.ball.ownerId);T.reconcileDefensiveResponsibilities(normal,team,owner);const ro=player(reversed,reversed.ball.ownerId);T.reconcileDefensiveResponsibilities(reversed,team,ro);const norm=normal._defensiveResponsibility?.[team]?.records||{},rev=reversed._defensiveResponsibility?.[team]?.records||{};const a=Object.fromEntries(Object.entries(norm).map(([id,x])=>[id,[x.type,x.targetId]])),b=Object.fromEntries(Object.entries(rev).map(([id,x])=>[id,[x.type,x.targetId]]));rows.push({caseId:c.caseId,isolatedFunction:'tactical_movement.reconcileDefensiveResponsibilities',sameAssignment:JSON.stringify(a)===JSON.stringify(b)});}return{status:rows.some(x=>!x.sameAssignment)?'ORDER_SENSITIVITY_DEMONSTRATED_ISOLATED_ONLY':'NO_ISOLATED_ORDER_DIFFERENCE_OBSERVED',warning:'This clone-only function probe is not gameplay truth and makes no repair.',rows};}
function compactTrace(trace){
  const packR=r=>r?[r.team,r.at,r.primaryPressureOwnerId,r.primaryPressureTargetId,r.coverOwnerId,r.unownedThreatIds,r.duplicateThreats,r.duplicatePressureOwnerIds,Object.entries(r.records||{}).map(([id,x])=>[id,x.type,x.targetId,x.reason,x.epoch,x.handoffReason])]:null;
  const packP=p=>[p.id,p.team,p.role,p.slot,p.x,p.y,p.vx,p.vy,p.bodyAngle,p.faceTargetAngle,p.tx,p.ty,p.finalMovementIntent?[p.finalMovementIntent.x,p.finalMovementIntent.y,p.finalMovementIntent.type,p.finalMovementIntent.targetId,p.finalMovementIntent.reason,p.finalMovementIntent.writer,p.finalMovementIntent.stepId]:null,p.tacticalTask,p.action,p.markTargetId,p.responsibilityType,p.responsibilityTargetId,p.responsibilityReason,p.responsibilityEpoch,p.writer];
  const packB=b=>[b.mode,b.ownerId,b.intendedReceiverId,b.flightReceiverId,b.x,b.y,b.vx,b.vy,b.possession,b.phase,b.restart,b.setPieceLive];
  return{encoding:'array-v1',rowColumns:['tick','time','shapeDecisionTick','ball','responsibilityHOME','responsibilityAWAY','players','oracleFailures','oracleNotes','routeMateriality'],ballColumns:['mode','ownerId','intendedReceiverId','flightReceiverId','x','y','vx','vy','possession','phase','restart','setPieceLive'],responsibilityColumns:['team','at','pressOwnerId','pressTargetId','coverOwnerId','unownedThreatIds','duplicateThreats','duplicatePressureOwnerIds','records'],responsibilityRecordColumns:['actorId','type','targetId','reason','epoch','handoffReason'],playerColumns:['id','team','role','slot','x','y','vx','vy','bodyAngle','faceTargetAngle','tx','ty','finalMovementIntent','tacticalTask','action','markTargetId','responsibilityType','responsibilityTargetId','responsibilityReason','responsibilityEpoch','writer'],finalMovementIntentColumns:['x','y','type','targetId','reason','writer','stepId'],rows:trace.map(r=>[r.tick,r.time,r.shapeDecisionTick,packB(r.ball),packR(r.responsibility.HOME),packR(r.responsibility.AWAY),r.players.map(packP),r.oracles.failures,r.oracles.notes,r.oracles.materiality])};
}
function main(){
  const results=[];for(const c of CASES){const off=run(c.policy,c.scenarioId,false),on=run(c.policy,c.scenarioId,true);const purity=off.endpoints.length===on.endpoints.length&&off.endpoints.every((x,i)=>x===on.endpoints[i]);const classification=classify(on.trace,c.requiredEvent);results.push({...c,fixtureActorIds:on.ids,initialStateHash:on.initialHash,baselineClassification:classification,observerPurity:{status:purity?'PASS':'FAIL',checkedEndpoints:on.endpoints.length,authoritativeAndRngDigestIdentical:purity},trace:on.trace,transitionEvents:transitionEvents(on.trace)});}
  const coverageProbes=['NATURAL','FAR_OFFBALL'].flatMap(scenarioId=>['CURRENT','LOCKED_MARK','ZONAL_RELATION'].map(policy=>{const r=run(policy,scenarioId,true);return{scenarioId,policy,rows:r.trace.length,initialStateHash:r.initialHash,trace:r.trace};}));
  const controls=positiveControls(results,coverageProbes);const handoffs=results.flatMap(r=>r.transitionEvents).filter(x=>x.kind==='OWNER_CHANGE');const control=controls.find(x=>x.id==='VALID_COMPLETED_HANDOFF_THEN_RELEASE');if(control)control.status=handoffs.length?'OBSERVED_VALID':'NOT_EXERCISED';
  const sourceHashes={harness:SHA(HARNESS),runtimeTacticalMovement:SHA(path.join(ROOT,'runtime/tactical_movement.js')),runtimeContinuousCore:SHA(path.join(ROOT,'runtime/continuous_match_core.js'))};
  const manifest={schemaVersion:'V56_D0_CASE_MANIFEST_1',implementation:'D0_OBSERVATION_ONLY',harness:{path:'single_state_continuity_test.js',sha256:sourceHashes.harness,fixtureExtraction:'read-only source parsing; no browser-harness change'},sourceHashes,caseMapping:results.map(r=>({caseId:r.caseId,scenarioId:r.scenarioId,policy:r.policy,expectedObservationWindow:r.expectedObservationWindow,sourceUserObservation:r.userObservation,actualInitialStateHash:r.initialStateHash,seed:r.seed,dt:r.dt,actualSourceHashes:sourceHashes,actorIdsResolvedFromCurrentFixture:r.fixtureActorIds,currentBaselineStatus:r.baselineClassification.status}))};
  const persistedCases=results.map(r=>{const {trace,...rest}=r;return{...rest,traceSampling:{domain:'every exact E.step(m,0.05) call, including initial fixture state',rows:trace.length,firstRuntimeTime:trace[0]?.time,lastRuntimeTime:trace.at(-1)?.time},motorTrace:compactTrace(trace)};});
  const evidence={schemaVersion:'V56_D0_OFFBALL_FAILURE_CONTRACT_1',implementation:'D0_OBSERVATION_ONLY',gameplayChanged:'NO',dShadowStarted:'NO',userVisualProven:'UNCHANGED',runtimeInstrumentation:'NONE',sourceHashes,guards:{dangerRoute:'position/velocity/entry-lane only',credibleOwner:'current body geometry + goal-side + approved current target',centralCorridor:'CB/CM central unit count while facing a material central route',fbVacancy:'possessing fullback same-side threat + central rest-defence',numericMarginsAre:'parameterized QA guards, not universal football truth'},observabilityGaps:['No runtime sub-tick callback exposes proposal writer provenance or post-final-seal mutation ordering; D0 records endpoint finalMovementIntent only.','Harness has no restart/free-kick forced fixture: case 02 cannot prove the reported set-piece phase without a future approved fixture addition.','PRESS/COVER writer provenance is exposed only as final responsibility state, not per-writer mutation trace.'],permutationOrderProbe:permutationProbe(),positiveControls:controls,positiveControlCoverageProbes:coverageProbes.map(({trace,...x})=>x),cases:persistedCases,validation:{nodeExecution:'PASS',observerPurity:results.every(r=>r.observerPurity.status==='PASS')?'PASS':'FAIL',protagonistActionsInvoked:false,futureOutcomeScripted:false,diagnosticBuffersExcludedFromGameplayDigest:true}};
  fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(MANIFEST_OUT,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(OUT,JSON.stringify(evidence)+'\n');console.log(JSON.stringify({verdict:evidence.validation.observerPurity,caseStatuses:results.map(r=>[r.caseId,r.baselineClassification.status]),evidence: path.relative(ROOT,OUT),manifest:path.relative(ROOT,MANIFEST_OUT)},null,2));
}
main();
