(function(){'use strict';
const E=window.FLRPG_CONTINUOUS_CORE,A=window.FLRPG_ATTRIBUTE_MATCH_ADAPTER,M=window.FLRPG_MANAGER_TENDENCY_ADAPTER;
const c=document.querySelector('#qaPitch'),x=c.getContext('2d'),meta=document.querySelector('#meta');let match=null,tick=0,eventCursor=0,config=null;
const finite=v=>Number.isFinite(Number(v))?Number(v):null,clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function player(m,id){return m.playersById?.[id]||m.players.find(p=>p.id===id)}
function setPos(m,r){const p=player(m,r.id);if(!p)return;p.x=r.x;p.y=r.y;p.tx=r.x;p.ty=r.y;p.vx=0;p.vy=0;p.sprint=false;p.runUntil=0;p.runType=null;p.markTargetId=null;p.responsibilityTargetId=null;p.responsibilityType=null;}
function applyFixture(m,f){if(!f||f.kind==='NATURAL')return;for(const r of f.positions||[])setPos(m,r);m.restart=null;m.setPieceLive=null;m.goalCelebration=null;m.completed=false;m.phase='OPEN_PLAY';m.time=600;m.nextShape=0;m.transitionUntil=0;m._defenceRoleLocks={};m._defensiveResponsibility={};m._markLocks={};m._transitionWideVacancies={};if(f.mark){const p=player(m,f.mark.actorId);if(p)p.markTargetId=f.mark.targetId;}if(f.ownerId){for(const p of m.players)p.hasBall=false;const p=player(m,f.ownerId),b=E.choiceActionBridge?.();if(b?.setControlled)b.setControlled(m,p,true);else if(p){p.hasBall=true;m.possession=p.team;m.ball.ownerId=p.id;m.ball.mode='CONTROLLED';m.ball.x=p.x;m.ball.y=p.y;}}}
function init(o){config=o;tick=0;eventCursor=0;match=E.createMatch(o.seed,o.mode==='D_EXECUTE'?{executionMode:'D_EXECUTE'}:{});for(const p of match.players)if(A?.assign)A.assign(match,p.id,A.baseProfile(60));if(M?.init)M.init(match,{HOME:'BALANCED',AWAY:'BALANCED'});match.offBallPolicy='CURRENT';applyFixture(match,o.fixture);draw();return {ok:true,players:match.players.map(p=>({id:p.id,team:p.team,role:p.role,slot:p.slot})),time:match.time,executionMode:match.executionMode||o.mode};}
function row(){const b=match.tacticalExecutionBoundary||{},contracts=new Map((b.contracts||[]).map(r=>[r.actorId,r]));const pRows=match.players.map(p=>{const q=contracts.get(p.id)||{},f=p.finalMovementIntent||{};return{id:p.id,team:p.team,role:p.role,slot:p.slot,x:finite(p.x),y:finite(p.y),vx:finite(p.vx),vy:finite(p.vy),body:finite(p.bodyAngle),facing:finite(p.faceTargetAngle),tx:finite(p.tx),ty:finite(p.ty),finalMovementIntent:{type:f.type||null,targetId:f.targetId||null,targetPoint:clone(f.targetPoint)||null,executionMode:f.executionMode||null,contractId:f.contractId||null},d2:{mode:q.executionMode||null,duty:q.duty||null,relationshipTargetId:q.relationshipTargetId||null,targetPoint:clone(q.targetPoint)||null,contractId:q.epochId||null},responsibility:{markTargetId:p.markTargetId||null,targetId:p.responsibilityTargetId||null,type:p.responsibilityType||null,task:p.tacticalTask||null,action:p.action||null}};});const ev=(match.events||[]).slice(eventCursor).map(clone);eventCursor=(match.events||[]).length;return{type:'tick',tickIndex:tick,simTime:Number(match.time.toFixed(6)),executionMode:b.executionMode||match.executionMode||config.mode,phase:match.phase||null,possession:match.possession||null,restart:clone(match.restart),setPiece:clone(match.setPieceLive),ball:{mode:match.ball.mode||null,x:finite(match.ball.x),y:finite(match.ball.y),ownerId:match.ball.ownerId||null,intendedReceiverId:match.ball.intendedReceiverId||null,currentReceiverId:match.ball.flightReceiverId||null},protagonist:{controllerId:match.protagonistControllerId||null,paused:!!match.paused,choiceId:match.userChoiceControl?.choiceId||match.userChoiceControl?.choice||match.userIncomingIntent?.choiceId||null,targetId:match.userChoiceControl?.targetId||match.userIncomingIntent?.targetId||null},dEpoch:{id:b.epochId||null,mode:b.executionMode||null},players:pRows,events:ev};}
function step(){if(!match)throw new Error('QA_NOT_INITIALIZED');E.step(match,.05);tick++;draw();return row();}
function draw(){if(!match)return;const W=c.width,H=c.height,px=v=>45+v/105*(W-90),py=v=>55+v/68*(H-115);x.clearRect(0,0,W,H);x.fillStyle='#285b36';x.fillRect(0,0,W,H);x.strokeStyle='#d8f2d5';x.lineWidth=3;x.strokeRect(45,55,W-90,H-115);x.beginPath();x.moveTo(px(52.5),55);x.lineTo(px(52.5),H-60);x.stroke();x.beginPath();x.arc(px(52.5),py(34),75,0,Math.PI*2);x.stroke();x.fillStyle='#101820';x.fillRect(0,0,W,42);x.fillStyle='#fff';x.font='bold 20px system-ui';x.fillText(`V57 QA · ${config?.mode||''} · t=${(match.time||0).toFixed(2)} · tick ${tick}`,18,28);for(const p of match.players){const fi=p.finalMovementIntent,target=fi?.targetPoint;if(target&&config?.showTargets){x.strokeStyle=p.team==='HOME'?'rgba(100,180,255,.35)':'rgba(255,140,140,.35)';x.beginPath();x.moveTo(px(p.x),py(p.y));x.lineTo(px(target.x),py(target.y));x.stroke();}x.beginPath();x.fillStyle=p.team==='HOME'?(p.role==='GK'?'#78d7ff':'#287be8'):(p.role==='GK'?'#ffb38d':'#de3c3c');x.arc(px(p.x),py(p.y),p.id===config?.focusPlayer?15:11,0,Math.PI*2);x.fill();x.strokeStyle=p.id===config?.focusPlayer?'#ffed4a':'#fff';x.lineWidth=p.id===config?.focusPlayer?3:1;x.stroke();x.fillStyle='#fff';x.font='bold 11px system-ui';x.textAlign='center';x.fillText(p.id,px(p.x),py(p.y)-15);}x.beginPath();x.fillStyle='#fff';x.strokeStyle='#111';x.lineWidth=2;x.arc(px(match.ball.x),py(match.ball.y),7,0,Math.PI*2);x.fill();x.stroke();meta.textContent=`Diagnostic renderer only · actual runtime tick · ${config?.scenario||'NATURAL'}`;}
window.FLR_V57_FRAME_TICK_QA={init,step,draw,engineReady:()=>!!E};
})();
