'use strict';
const fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const ROOT=path.resolve(__dirname,'..'),identity=require('../QA/v41_validation_identity'),browser=require('../QA/v41_browser_capture_runner'),adapter=require('../QA/v41_current_candidate_observation_adapter'),gate=require('../QA/v41_validation_freeze_gate');
function args(a){const o={};for(const x of a){const i=x.indexOf('=');if(x.startsWith('--')&&i>2)o[x.slice(2,i)]=x.slice(i+1)}return o}
function tooling(){const revision=spawnSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).stdout.trim(),status=spawnSync('git',['status','--porcelain','--untracked-files=all'],{cwd:ROOT,encoding:'utf8'}).stdout.trim();return{revision,status,cleanCommitted:!!revision&&!status}}
function write(out,n,v){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n')}
function buildObservationBundle({sid,wrapped,manifest,observations}){return{module:'V41_CURRENT_CANDIDATE_OBSERVATION_BUNDLE',schemaVersion:'FLR_V41_CURRENT_CANDIDATE_OBSERVATION_BUNDLE_1.1',source:'HOSTED_CAPTURE_EXTRACTION',candidateSourceSHA:sid.candidateSourceSHA,runtimeSourceSHA:sid.runtimeSourceSHA,deployedBuildSHA:sid.deployedBuildSHA,validatorHead:sid.validatorHead,hostedEvidence:wrapped,captureManifest:wrapped.captureManifest,scenarios:manifest.scenarios,observations,futureOutcomePrecomputed:false}}
async function run(a){
 const out=path.resolve(a.output||a['artifact-dir']||path.join(ROOT,'evidence/v41/A3-host-run')),t=tooling(),sid={candidateSourceSHA:identity.EXPECTED.candidateSourceSHA,runtimeSourceSHA:identity.runtimeSourceSHA(),deployedBuildSHA:identity.EXPECTED.deployedMainSHA,validatorHead:t.revision,fullFrozenPublicManifestSha256:identity.EXPECTED.fullPublicPayloadManifestSha256,fullPublicAssetCount:identity.PAYLOAD.length,loadedScriptCount:37,reporterBuildId:identity.EXPECTED.reporterBuildId,reporterFunctionalManifestSha:identity.EXPECTED.reporterFunctionalManifestSha};
 const result={module:'V41_HOST_VALIDATION_ORCHESTRATOR',schemaVersion:'FLR_V42_HOST_VALIDATION_1.2',validationToolingRevisionAtExecution:t.revision,toolingRevisionCleanAtExecution:t.cleanCommitted,identity:{...sid},userTruth:'USER_FAIL_OPEN'};
 if(!t.cleanCommitted){result.verdict='BLOCKED';result.failedStage='tooling revision';write(out,'V41_HOST_VALIDATION_REPORT.json',result);return result}
 const captureDir=path.join(out,'capture'),url=a['page-url']||'https://1lisam.github.io/FLR_TEST/',cmd=['tools/v40_browser_renderer_capture.js','--target=HOSTED','--page-url='+url,'--scenarios=CROSS_LEFT:FINAL-MATCH-TEST-77,ST_BREAKAWAY:FINAL-MATCH-TEST-95,CORNER_ATTACK_RIGHT:V40-P0-RUNTIME,GK_SHOT_CLOSE:FINAL-MATCH-TEST-135','--output-dir='+captureDir,'--candidate-source-sha='+sid.candidateSourceSHA,'--runtime-source-sha='+sid.runtimeSourceSHA,'--validator-head='+sid.validatorHead,'--expected-deployed-main-sha='+sid.deployedBuildSHA],cap=spawnSync(process.execPath,cmd,{cwd:ROOT,encoding:'utf8'});
 let m;try{m=JSON.parse(fs.readFileSync(path.join(captureDir,'manifest.json')))}catch(e){m={status:'QA_INFRA_BLOCKED',reason:'CAPTURE_MANIFEST_MISSING',stderr:cap.stderr}}
 result.hostedCapture=m;const wrapped={...m,candidateSourceSHA:m.candidateSourceSHA,runtimeSourceSHA:m.runtimeSourceSHA,deployedBuildSHA:sid.deployedBuildSHA,validatorHead:sid.validatorHead,futureOutcomePrecomputed:m.futureOutcomePrecomputed,captureManifest:{...m,payloadManifestSha256:identity.EXPECTED.payloadManifestSha256,fullFrozenPublicManifestSha256:sid.fullFrozenPublicManifestSha256,fullPublicAssetCount:sid.fullPublicAssetCount,loadedScriptCount:sid.loadedScriptCount,reporterBuildId:sid.reporterBuildId,reporterFunctionalManifestSha:sid.reporterFunctionalManifestSha}};
 result.captureRunnerValidation=browser.run({target:'HOSTED',candidateSourceSHA:sid.candidateSourceSHA,runtimeSourceSHA:sid.runtimeSourceSHA,validatorHead:sid.validatorHead,hostedEvidence:wrapped});
 if(result.captureRunnerValidation.verdict!=='PASS'){result.verdict='BLOCKED_VALIDATOR_GAP';result.failedStage='capture contract';write(out,'V41_HOST_VALIDATION_REPORT.json',result);return result}
 result.observationExtraction=adapter.fromCapture(wrapped,sid);if(result.observationExtraction.verdict!=='PASS'){result.verdict='BLOCKED_VALIDATOR_GAP';result.failedStage='observation extraction';write(out,'V41_HOST_VALIDATION_REPORT.json',result);return result}
 const bundle=buildObservationBundle({sid,wrapped,manifest:m,observations:result.observationExtraction.observations});write(out,'V41_CURRENT_CANDIDATE_OBSERVATION_BUNDLE.json',bundle);
 result.freezeGate=gate.run({evidence:bundle});result.verdict=result.freezeGate.verdict;result.postCommitDisposition='READY_FOR_HOST_OBSERVATION_EXECUTION';write(out,'V41_HOST_VALIDATION_REPORT.json',result);fs.writeFileSync(path.join(out,'V41_HOST_VALIDATION_REPORT.md'),'# V41 hosted observation report\n\n- Verdict: **'+result.verdict+'**\n- Observation bundle: V41_CURRENT_CANDIDATE_OBSERVATION_BUNDLE.json\n- USER_FAIL_OPEN: **OPEN**\n- Disposition: **READY_FOR_HOST_OBSERVATION_EXECUTION**\n');return result
}
function selftest(){return{module:'V41_HOST_VALIDATION_ORCHESTRATOR',selftest:'PASS',constructionOnly:true,network:'NOT_EXECUTED',chromium:'NOT_EXECUTED',technicalPassCannotCloseUserFailOpen:true}}
if(require.main===module){if(process.argv.includes('--selftest')){console.log(JSON.stringify(selftest(),null,2));process.exit(0)}const a=args(process.argv.slice(2));run(a).then(x=>{console.log(JSON.stringify(x,null,2));if(x.verdict==='BLOCKED'||x.verdict==='BLOCKED_VALIDATOR_GAP')process.exitCode=15}).catch(e=>{console.error(e.stack||e);process.exitCode=15})}
module.exports={run,selftest,buildObservationBundle};
