/* V43 focused Viewer: donor-derived presentation only; authority remains the live controller state. */
(()=>{'use strict';
const E=globalThis.FLRPG_CONTINUOUS_CORE,P=globalThis.FLRPG_PROTAGONIST_MATCH_CONTROLLER,$=id=>document.getElementById(id),canvas=$('pitch'),ctx=canvas.getContext('2d');
const CASES=[['v43-4','H-CM'],['v43-5','H-ST'],['v43-7','H-ST'],['v43-16','H-CM']];let caseIndex=0,state=null,history=[],frozen=null,proof={},raf=0,playStart=0,selected=null,focusedTargetId=null;
const compact=s=>({time:s.time,possession:s.possession,ball:{x:s.ball.x,y:s.ball.y,vx:s.ball.vx,vy:s.ball.vy,ownerId:s.ball.ownerId,mode:s.ball.mode},players:s.players.map(p=>[p.id,p.x,p.y,p.vx,p.vy,p.hasBall])}),equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function replayEqualsAuthority(frame,snap){if(Math.abs(frame.time-snap.time)>1e-8||frame.possession!==snap.possession||frame.ball.ownerId!==snap.ball.ownerId||frame.ball.mode!==snap.ball.mode)return false;for(const p of snap.players){const q=frame.players.find(x=>x.id===p.id);if(!q||q.hasBall!==p.hasBall||Math.abs(q.x-p.x)>.00051||Math.abs(q.y-p.y)>.00051||Math.abs(q.vx-p.vx)>.00051||Math.abs(q.vy-p.vy)>.00051)return false;}return Math.abs(frame.ball.x-snap.ball.x)<=.00051&&Math.abs(frame.ball.y-snap.ball.y)<=.00051&&Math.abs(frame.ball.vx-snap.ball.vx)<=.00051&&Math.abs(frame.ball.vy-snap.ball.vy)<=.00051;}
function point(p){const W=canvas.width,H=canvas.height,padX=28,padY=24,fw=W-padX*2,fh=H-padY*2;return{x:padX+p.x/105*fw,y:padY+p.y/68*fh};}
function drawPitch(){const W=canvas.width,H=canvas.height,padX=28,padY=24,fw=W-padX*2,fh=H-padY*2,x=v=>padX+v/105*fw,y=v=>padY+v/68*fh;ctx.clearRect(0,0,W,H);ctx.fillStyle='#315b37';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(240,255,242,.78)';ctx.lineWidth=3;ctx.strokeRect(padX,padY,fw,fh);ctx.beginPath();ctx.moveTo(x(52.5),padY);ctx.lineTo(x(52.5),padY+fh);ctx.stroke();ctx.beginPath();ctx.arc(x(52.5),y(34),9.15/105*fw,0,Math.PI*2);ctx.stroke();ctx.strokeRect(x(0),y(13.84),x(16.5)-x(0),y(54.16)-y(13.84));ctx.strokeRect(x(88.5),y(13.84),x(105)-x(88.5),y(54.16)-y(13.84));const gy1=y(30.34),gy2=y(37.66),depth=15;ctx.strokeStyle='rgba(250,255,250,.95)';ctx.strokeRect(padX-depth,gy1,depth,gy2-gy1);ctx.strokeRect(padX+fw,gy1,depth,gy2-gy1);}
function draw(s){if(!s)return;drawPitch();const mobile=matchMedia('(max-width:760px)').matches;for(const p of s.players){const q=point(p),hero=p.id===state?.heroPlayerId,target=p.id===focusedTargetId,r=mobile?(hero?18:14):(hero?14:11),gk=p.role==='GK';if(target){ctx.beginPath();ctx.arc(q.x,q.y,r+8,0,Math.PI*2);ctx.strokeStyle='#8fd8f6';ctx.lineWidth=3;ctx.stroke();}if(hero){ctx.beginPath();ctx.arc(q.x,q.y,r+7,0,Math.PI*2);ctx.strokeStyle='rgba(99,214,255,.9)';ctx.lineWidth=3;ctx.stroke();}ctx.beginPath();ctx.fillStyle=p.team==='HOME'?(gk?'#7dd3fc':'#2563eb'):(gk?'#fca5a5':'#dc2626');ctx.arc(q.x,q.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=hero?'#fff':'rgba(255,255,255,.82)';ctx.lineWidth=hero?3:1.5;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`bold ${mobile?11:8}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.slot||p.role||'',q.x,q.y);}const ball=point(s.ball);ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#1c252b';ctx.lineWidth=2;ctx.arc(ball.x,ball.y,7+Math.min(4,(Number(s.ball.z)||0)*1.5),0,Math.PI*2);ctx.fill();ctx.stroke();$('clock').textContent=`${Math.floor(s.time/60)+1}'`;$('score').textContent=`${s.score.HOME} - ${s.score.AWAY}`;}
function setProof(){const rows={mode:proof.mode||'LIVE',authoritativeChoiceTime:proof.authoritativeChoiceTime??'-',playbackCursorTime:proof.playbackCursorTime??'-',historyWindow:proof.historyWindow||'-',seedCase:proof.seedCase||'-',selectedChoiceTarget:selected?`${selected.choiceId||selected.id} / ${selected.targetId||'-'}`:'-',futurePrecomputed:'false',replayValidity:proof.replayValidity||'PENDING'};$('proof').innerHTML=Object.entries(rows).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');}
function validate(s,frames){const now=E.snapshot(s.m),last=frames.at(-1),span=last.time-frames[0].time,dense=frames.length>=50&&frames.every((f,i)=>!i||f.time>frames[i-1].time&&f.time-frames[i-1].time<=.12);return{ok:frames.length>=50&&span>=4.8&&span<=10.1&&dense&&replayEqualsAuthority(last,now)&&equal(compact(now),compact(frozen)),span,frames:frames.length};}function setMessage(t){$('status').textContent=t;$('message').textContent=t;}
function hideChoice(){$('choice').hidden=true;focusedTargetId=null;selected=null;}
function findCase(){cancelAnimationFrame(raf);hideChoice();$('start').disabled=true;$('again').disabled=true;$('other').disabled=true;setMessage('실제 경기에서 유효 선택 탐색 중…');for(let tried=0;tried<CASES.length;tried++){const ix=(caseIndex+tried)%CASES.length,[seed,heroPlayerId]=CASES[ix],s=P.create(seed,{heroPlayerId,mode:'PLAYER_ALL',replaySeconds:10,appearanceStatus:'STARTER',managerProfiles:{HOME:'BALANCED',AWAY:'BALANCED'}});let n=0;while(!s.pending&&!s.m.completed&&n++<90000)P.step(s,.1);if(!s.pending)continue;frozen=E.snapshot(s.m);const frames=P.latestReplay(s),v=validate(s,frames);if(!v.ok)continue;caseIndex=ix;state=s;history=frames;proof={mode:'PLAYBACK',authoritativeChoiceTime:frozen.time.toFixed(2),playbackCursorTime:frames[0].time.toFixed(2),historyWindow:`${frames[0].time.toFixed(2)} – ${frames.at(-1).time.toFixed(2)} (${v.span.toFixed(1)}초 / ${v.frames} frames)`,seedCase:`${seed} / ${heroPlayerId}`,replayValidity:'PASS'};setProof();$('mode').textContent='PLAYBACK';setMessage('유효 실제 케이스 발견 · 직전 플레이 재생');playStart=performance.now();draw(frames[0]);raf=requestAnimationFrame(playback);return;}proof={mode:'FAIL',replayValidity:'FAIL — valid real case not found'};setProof();setMessage('FAIL: 유효한 실제 케이스를 찾지 못했습니다.');$('start').disabled=false;}
function playback(now){const elapsed=(now-playStart)/1000*2,start=history[0].time,end=history.at(-1).time,t=Math.min(end,start+elapsed);let i=0;while(i<history.length-1&&history[i+1].time<=t)i++;proof.playbackCursorTime=t.toFixed(2);setProof();draw(history[i]);if(t<end){raf=requestAnimationFrame(playback);return}const after=E.snapshot(state.m);if(!equal(compact(after),compact(frozen))){proof.mode='FAIL';proof.replayValidity='FAIL — playback mutated authority';setProof();setMessage('FAIL: 재생 중 권한 상태가 변경되었습니다.');return}proof.mode='CHOICE_FROZEN';proof.playbackCursorTime=end.toFixed(2);setProof();$('mode').textContent='CHOICE';draw(frozen);showChoice();}
function optionLabel(o){return o.label||`${o.id} ${o.targetId||''}`;}function renderChoices(){const list=$('options');list.innerHTML='';for(const o of state.pending.options){const b=document.createElement('button');b.type='button';b.className=`choice-option${selected===o?' selected':''}${o.recommended?' recommended':''}`;b.dataset.choiceId=o.id;b.dataset.targetId=o.targetId||'';b.innerHTML=`<b>${optionLabel(o)}</b><small>${o.targetId?`대상: ${o.targetId}`:'내 행동'}</small>`;b.onclick=()=>{selected=o;focusedTargetId=o.targetId||null;renderChoices();draw(frozen);};list.appendChild(b);}const target=frozen.players.find(p=>p.id===focusedTargetId);$('choiceTarget').textContent=target?`선택 대상 · ${target.slot||target.role} (${target.id})`:'행동 선택 대기';$('confirmChoice').disabled=!selected;$('choiceReceipt').textContent=selected?`${selected.id} → ${selected.targetId||'자기 행동'} · 확정 전에는 실행되지 않습니다.`:'선택은 확정 전까지 실행되지 않습니다.';}
function showChoice(){setMessage('정확한 선택 지점에서 정지 · 경기장 안에서 대상과 행동을 고르세요');$('choice').hidden=false;selected=null;focusedTargetId=null;renderChoices();}
function canvasTargetClick(ev){if(!state?.pending||$('choice').hidden)return;const r=canvas.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width*canvas.width,y=(ev.clientY-r.top)/r.height*canvas.height;let closest=null,best=Infinity;for(const p of frozen.players){const q=point(p),d=Math.hypot(x-q.x,y-q.y);if(d<best){best=d;closest=p;}}if(!closest||best>36)return;const options=state.pending.options.filter(o=>o.targetId===closest.id);if(!options.length)return;focusedTargetId=closest.id;selected=options[0];renderChoices();draw(frozen);}
function choose(){const opt=selected;if(!state?.pending||!opt)return;const atFreeze=(state.m.events||[]).filter(e=>e.actorId===state.heroPlayerId&&['PASS','SHOT','HEADER_SHOT','TAKE_ON'].includes(e.type)&&e.t>=frozen.time-.001);if(atFreeze.length){setMessage('FAIL: 선택 전 주인공 행동이 정지 시점에 발생했습니다.');return}const r=P.applyChoice(state,opt.id,opt.targetId||null,{source:'V43_FOCUSED_USER_VIEWER_IN_PITCH',confirmedAction:true});if(!r.ok){setMessage(`FAIL: 선택 거부 (${r.reason})`);return}selected={choiceId:opt.id,targetId:opt.targetId||null};const receipt=state.lastChoice||{};if(receipt.choice!==selected.choiceId||(receipt.targetId||null)!==selected.targetId){setMessage('FAIL: selected choice identity mismatch');return}let n=0;while(!state.m.completed&&!state.pending&&n++<35)P.step(state,.1);if(state.m.time<=frozen.time){setMessage('FAIL: same match did not continue');return}proof.mode='POST_CHOICE';proof.replayValidity='PASS';setProof();$('choice').hidden=true;$('mode').textContent='LIVE';draw(E.snapshot(state.m));setMessage(`선택 실행: ${selected.choiceId} → ${selected.targetId||'-'} · 같은 경기가 계속 진행됨`);$('again').disabled=false;$('other').disabled=false;$('start').disabled=false;}
$('start').onclick=findCase;$('again').onclick=findCase;$('other').onclick=()=>{caseIndex=(caseIndex+1)%CASES.length;findCase()};$('confirmChoice').onclick=choose;canvas.addEventListener('click',canvasTargetClick);setProof();
})();
