/* V43 focused user viewer. It never writes a future branch or reconstructs a scene. */
(()=>{'use strict';
const E=globalThis.FLRPG_CONTINUOUS_CORE,P=globalThis.FLRPG_PROTAGONIST_MATCH_CONTROLLER;
const $=id=>document.getElementById(id),canvas=$('pitch'),ctx=canvas.getContext('2d');
const CASES=[['v43-4','H-CM'],['v43-5','H-ST'],['v43-7','H-ST'],['v43-16','H-CM']];
let caseIndex=0,state=null,history=[],frozen=null,proof={},raf=0,playStart=0,selected=null;
const deep=x=>JSON.parse(JSON.stringify(x));
const compact=s=>({time:s.time,possession:s.possession,ball:{x:s.ball.x,y:s.ball.y,vx:s.ball.vx,vy:s.ball.vy,ownerId:s.ball.ownerId,mode:s.ball.mode},players:s.players.map(p=>[p.id,p.x,p.y,p.vx,p.vy,p.hasBall])});
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
// Controller history is a renderer frame rounded to 0.001; identity fields and time stay exact.
function replayEqualsAuthority(frame,snap){if(Math.abs(frame.time-snap.time)>1e-8||frame.possession!==snap.possession||frame.ball.ownerId!==snap.ball.ownerId||frame.ball.mode!==snap.ball.mode)return false;for(const p of snap.players){const q=frame.players.find(x=>x.id===p.id);if(!q||q.hasBall!==p.hasBall||Math.abs(q.x-p.x)>.00051||Math.abs(q.y-p.y)>.00051||Math.abs(q.vx-p.vx)>.00051||Math.abs(q.vy-p.vy)>.00051)return false;}return Math.abs(frame.ball.x-snap.ball.x)<=.00051&&Math.abs(frame.ball.y-snap.ball.y)<=.00051&&Math.abs(frame.ball.vx-snap.ball.vx)<=.00051&&Math.abs(frame.ball.vy-snap.ball.vy)<=.00051;}
function draw(s){if(!s)return;const W=canvas.width,H=canvas.height,x=v=>28+v/105*(W-56),y=v=>24+v/68*(H-48);ctx.clearRect(0,0,W,H);ctx.fillStyle='#315b37';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#dfeee4';ctx.lineWidth=3;ctx.strokeRect(28,24,W-56,H-48);ctx.beginPath();ctx.moveTo(x(52.5),24);ctx.lineTo(x(52.5),H-24);ctx.stroke();ctx.beginPath();ctx.arc(x(52.5),y(34),9.15/105*(W-56),0,Math.PI*2);ctx.stroke();for(const p of s.players){ctx.beginPath();ctx.fillStyle=p.id===state?.heroPlayerId?'#ffd35a':p.team==='HOME'?'#3e9ded':'#ea6868';ctx.arc(x(p.x),y(p.y),p.id===state?.heroPlayerId?8:6,0,Math.PI*2);ctx.fill();}ctx.beginPath();ctx.fillStyle='#fff';ctx.arc(x(s.ball.x),y(s.ball.y),4.5,0,Math.PI*2);ctx.fill();$('clock').textContent=`${Math.floor(s.time/60)+1}'`;$('score').textContent=`${s.score.HOME} - ${s.score.AWAY}`;}
function setProof(){const rows={mode:proof.mode||'LIVE',authoritativeChoiceTime:proof.authoritativeChoiceTime??'-',playbackCursorTime:proof.playbackCursorTime??'-',historyWindow:proof.historyWindow||'-',seedCase:proof.seedCase||'-',selectedChoiceTarget:selected?`${selected.choiceId} / ${selected.targetId||'-'}`:'-',futurePrecomputed:'false',replayValidity:proof.replayValidity||'PENDING'};$('proof').innerHTML=Object.entries(rows).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');}
function validate(s,frames){const now=E.snapshot(s.m),last=frames.at(-1),span=last.time-frames[0].time,dense=frames.length>=50&&frames.every((f,i)=>!i||f.time>frames[i-1].time&&f.time-frames[i-1].time<=.12);return{ok:frames.length>=50&&span>=4.8&&span<=10.1&&dense&&replayEqualsAuthority(last,now)&&equal(compact(now),compact(frozen)),span,frames:frames.length};}
function findCase(){cancelAnimationFrame(raf);$('choice').hidden=true;$('start').disabled=true;$('again').disabled=true;$('other').disabled=true;$('status').textContent='실제 경기에서 유효 선택 탐색 중…';for(let tried=0;tried<CASES.length;tried++){const ix=(caseIndex+tried)%CASES.length,[seed,heroPlayerId]=CASES[ix],s=P.create(seed,{heroPlayerId,mode:'PLAYER_ALL',replaySeconds:10,appearanceStatus:'STARTER',managerProfiles:{HOME:'BALANCED',AWAY:'BALANCED'}});let n=0;while(!s.pending&&!s.m.completed&&n++<90000)P.step(s,.1);if(!s.pending)continue;frozen=E.snapshot(s.m);const frames=P.latestReplay(s),v=validate(s,frames);if(!v.ok)continue;caseIndex=ix;state=s;history=frames;proof={mode:'PLAYBACK',authoritativeChoiceTime:frozen.time.toFixed(2),playbackCursorTime:frames[0].time.toFixed(2),historyWindow:`${frames[0].time.toFixed(2)} – ${frames.at(-1).time.toFixed(2)} (${v.span.toFixed(1)}초 / ${v.frames} frames)`,seedCase:`${seed} / ${heroPlayerId}`,replayValidity:'PASS'};setProof();$('status').textContent='유효 실제 케이스 발견 · 직전 플레이 재생';playStart=performance.now();draw(frames[0]);raf=requestAnimationFrame(playback);return;}proof={mode:'FAIL',replayValidity:'FAIL — valid real case not found'};setProof();$('status').textContent='FAIL: 유효한 실제 케이스를 찾지 못했습니다.';$('start').disabled=false;}
function playback(now){const elapsed=(now-playStart)/1000*2,start=history[0].time,end=history.at(-1).time,t=Math.min(end,start+elapsed);let i=0;while(i<history.length-1&&history[i+1].time<=t)i++;const frame=history[i];proof.playbackCursorTime=t.toFixed(2);setProof();draw(frame);if(t<end){raf=requestAnimationFrame(playback);return}const after=E.snapshot(state.m);if(!equal(compact(after),compact(frozen))){proof.mode='FAIL';proof.replayValidity='FAIL — playback mutated authority';setProof();$('status').textContent='FAIL: 재생 중 권한 상태가 변경되었습니다.';return}proof.mode='CHOICE_FROZEN';proof.playbackCursorTime=end.toFixed(2);setProof();draw(frozen);showChoice();}
function showChoice(){$('status').textContent='정확한 선택 지점에서 정지 · 행동을 고르세요';$('choice').hidden=false;$('options').innerHTML='';for(const o of state.pending.options){const b=document.createElement('button');b.textContent=o.label||`${o.id} ${o.targetId||''}`;b.onclick=()=>choose(o);$('options').appendChild(b);}}
function choose(opt){if(!state?.pending)return;const atFreeze=(state.m.events||[]).filter(e=>e.actorId===state.heroPlayerId&&['PASS','SHOT','HEADER_SHOT','TAKE_ON'].includes(e.type)&&e.t>=frozen.time-.001);if(atFreeze.length){$('status').textContent='FAIL: 선택 전 주인공 행동이 정지 시점에 발생했습니다.';return}const r=P.applyChoice(state,opt.id,opt.targetId||null,{source:'V43_FOCUSED_USER_VIEWER',confirmedAction:true});if(!r.ok){$('status').textContent=`FAIL: 선택 거부 (${r.reason})`;return}selected={choiceId:opt.id,targetId:opt.targetId||null};const receipt=state.lastChoice||{};if(receipt.choice!==selected.choiceId||(receipt.targetId||null)!==selected.targetId){$('status').textContent='FAIL: selected choice identity mismatch';return}let n=0;while(!state.m.completed&&!state.pending&&n++<35)P.step(state,.1);if(state.m.time<=frozen.time){$('status').textContent='FAIL: same match did not continue';return}proof.mode='POST_CHOICE';proof.replayValidity='PASS';setProof();$('choice').hidden=true;draw(E.snapshot(state.m));$('status').textContent=`선택 실행: ${selected.choiceId} → ${selected.targetId||'-'} · 같은 경기가 계속 진행됨`;$('again').disabled=false;$('other').disabled=false;$('start').disabled=false;}
$('start').onclick=findCase;$('again').onclick=findCase;$('other').onclick=()=>{caseIndex=(caseIndex+1)%CASES.length;findCase()};setProof();
})();
