(function(root){'use strict';
const H=root&&root.FLRPG_FINAL_MATCH_RARE_SCENARIOS,A=root&&root.FLRPG_LIVE_V06_SCENE_AUTHORITY;if(!H||!A||H.__v37ForcedHarnessPatchV2)return;
const VERSION='V37-FORCED-HARNESS-0.3';
const baseRun=H.run.bind(H),deep=v=>v==null?v:JSON.parse(JSON.stringify(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hash32(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
function unit(seed,salt){return(hash32(`${seed}|${salt}`)>>>0)/4294967296;}
function signed(seed,salt,span=1){return(unit(seed,salt)-.5)*2*span;}
function setPos(p,x,y){p.x=x;p.y=y;p.tx=x;p.ty=y;p.vx=0;p.vy=0;p.sprint=false;}
function runInteractiveBreakaway(key,seed,opts={}){const c=H.SCENARIOS[key],b=H.boundary(key,seed),opened=A.seedMatch(b,{seed:`${seed}|ENTRY`,runtimeDir:opts.runtimeDir,explicitHeroChoiceRequired:true}),{E,P,state}=opened,m=state.m,br=E.choiceActionBridge(),st=br.playerById(m,'H-ST'),gk=br.playerById(m,'A-GK'),lcb=br.playerById(m,'A-LCB'),rcb=br.playerById(m,'A-RCB');if(!st||!gk||!lcb||!rcb)throw new Error('BREAKAWAY_FIXTURE_PLAYERS_MISSING');
  const sx=clamp(82+signed(seed,'st-x',4),78,87),sy=clamp(34+signed(seed,'st-y',6),25,43),gkx=clamp(100+signed(seed,'gk-x',1),98.2,101.2),gky=clamp(34+signed(seed,'gk-y',2.5),30,38),trail=clamp(5+unit(seed,'trail')*5,5,10);
  setPos(st,sx,sy);setPos(gk,gkx,gky);setPos(lcb,clamp(sx-trail,67,82),clamp(sy-5+signed(seed,'lcb-y',2),18,39));setPos(rcb,clamp(sx-trail+signed(seed,'rcb-x',2),67,83),clamp(sy+5+signed(seed,'rcb-y',2),29,50));
  m.possession='HOME';m.protagonistExplicitActionRequired=true;br.setControlled(m,st);st.controlledSince=m.time-1.0;st.nextThink=m.time+2.0;st.lockTargetUntil=m.time+.70;st.action='HOLD_BALL';st.tacticalTask='HOLD_BALL';st.bodyAngle=0;st.faceTargetAngle=0;st.tx=clamp(st.x+3.2,3,101);st.ty=clamp(st.y+signed(seed,'carry-y',1.6),3,65);st.vx=2.8;st.vy=(st.ty-st.y)/1.2;st.sprint=true;
  const start=m.time,entrySnapshot=deep(E.snapshot(m)),frames=[deep(entrySnapshot)];state.mode='FULL_SKIP';state.forceNextChoice=false;let guard=0;while(!m.completed&&m.time<start+.55&&guard++<16){P.step(state,.05);frames.push(deep(E.snapshot(m)));if(m.ball.ownerId!=='H-ST'||m.ball.mode!=='CONTROLLED')break;}
  state.mode='PLAYER_ALL';state.lastPauseAt=m.time-1.0;state.lastPauseControlledSince=-999;state.forceNextChoice=true;st.nextThink=m.time;st.lockTargetUntil=0;P.maybeCheckpoint(state);guard=0;while(!state.pending&&!m.completed&&guard++<20){P.step(state,.05);frames.push(deep(E.snapshot(m)));P.maybeCheckpoint(state);}const pending=state.pending?deep(state.pending):null;if(!pending)throw new Error('BREAKAWAY_CHOICE_NOT_FOUND');
  const result={key,label:c.label,seed,boundary:b,entrySnapshot,frames,pending,snapshot:E.snapshot(m),actualEvents:(m.events||[]).filter(e=>e.t>=start-.001).map(deep),stopReason:'USER_DECISION_BOUNDARY',forcedSetup:'BREAKAWAY_CONTEXT_AND_USER_DECISION_ONLY',futureOutcomePrecomputed:false,v37HarnessVersion:VERSION};H.__v37Interactive={opened,result,start};return result;
}
function mutateWithChoice(result,step){const before=(result.frames||[]).length;result.replayStartFrameIndex=Math.max(0,before-1);result.frames.push(...(step.postFrames||[]).map(deep));result.replayEndFrameIndex=Math.max(result.replayStartFrameIndex,result.frames.length-1);result.choiceReplaySerial=Number(result.choiceReplaySerial||0)+1;result.snapshot=deep(step.snapshot);result.pending=step.nextPending?deep(step.nextPending):null;result.selectedChoice=deep(step.selectedChoice);result.forcedChoiceResult=deep(step.result);result.committedEvent=deep(step.committedEvent);result.actualEvents=[...(result.actualEvents||[]),...(step.actualEvents||[]).map(deep),...(step.committedEvent?[deep(step.committedEvent)]:[])];result.stopReason=result.pending?'USER_DECISION_BOUNDARY':'CHOICE_RESOLVED';result.futureOutcomePrecomputed=false;return result;}
H.applyForcedChoice=function(choiceId,targetId=null){const ctx=H.__v37Interactive;if(!ctx?.opened||!ctx.result?.pending)return{ok:false,reason:'NO_INTERACTIVE_FORCED_CHOICE'};const step=A.applyChoiceAndAdvance(ctx.opened,choiceId,targetId,{maxPostSeconds:10});mutateWithChoice(ctx.result,step);return{ok:true,result:ctx.result,continuation:!!ctx.result.pending,futureOutcomePrecomputed:false};};
H.run=function(key,seed='FINAL-MATCH-RARE-001',opts={}){const c=H.SCENARIOS?.[key];if(!c)return baseRun(key,seed,opts);if(key==='ST_BREAKAWAY')return runInteractiveBreakaway(key,seed,opts);H.__v37Interactive=null;if(c.kind==='SET_PIECE'){const b=H.boundary(key,seed),out=A.runSetPieceWindow(b,{seed:`${seed}|SETPIECE`,runtimeDir:opts.runtimeDir,durationSeconds:12});return{key,label:c.label,seed,boundary:b,...out,forcedSetup:'DEAD_BALL_CONTEXT_ONLY',futureOutcomePrecomputed:false,v37HarnessVersion:VERSION};}return baseRun(key,seed,opts);};
H.V37_FORCED_HARNESS_VERSION=VERSION;H.__v37ForcedHarnessPatchV2=true;H.__v37ForcedHarnessPatch=true;
})(typeof globalThis!=='undefined'?globalThis:this);
