(function(){'use strict';
const H=[[5,34],[25,9],[23,25],[23,43],[25,59],[38,34],[50,23],[50,45],[71,8],[74,34],[71,60]],D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const base=x=>JSON.parse(new window.ASTRA_FIXTURE_ENGINE.Match(x).serialize());
function set(s,i,x,y,e={}){Object.assign(s.players[i],{x,y,vx:0,vy:0,target:{x,y},...e});}
function duty(s,i,k,t,e={}){const p=s.players[i],h=H[p.slot],d=e.duty||'COVER',subjectId=e.subjectId??null,pressureTargetId=e.pressureTargetId??(d==='PRESS'?subjectId:null),markTargetId=e.markTargetId??(d==='MARK'?subjectId:null),watchTargetId=e.watchTargetId??markTargetId;p.duty=d;p.target={...t};p.markId=e.markId??null;p.pressId=e.pressId??null;p.responsibility={version:1,epoch:'fixture',kind:k,subjectId,homeResponsibility:{role:p.role,region:{x:h[0],y:h[1]}},pressPhase:e.pressPhase||null,handoff:e.handoff||null,pressureTargetId,markTargetId,watchTargetId};p.defensiveContext={responsibility:k,homeZone:{x:h[0],y:h[1]},markShadow:!!e.markShadow,pressureTargetId,markTargetId,watchTargetId};}
function control(s,i,x,y){s.ball={...s.ball,x,y,owner:i,mode:'controlled',flight:null,lastTouch:i};s.possession=s.lastPossession=s.players[i].team;set(s,i,x,y,{duty:'CARRY'});}
function ledger(s,state){s.responsibilityVacancies=[{key:'0:4:WIDE_CHANNEL',team:0,homeOwnerId:4,channel:'RIGHT_CHANNEL',state,subjectId:19,contributors:[{playerId:3,role:'RCB',share:'REMOTE_WATCH'},{playerId:5,role:'DM',share:'HALFSPACE_SCREEN'},{playerId:7,role:'RCM',share:'LANE_SHARE'}]}];}
const defs=[
{id:'fb-excursion-compensation',label:'RB 공격 가담 · 분산 책임 보상',relation:'FB_EXCURSION_DISTRIBUTED',observation:{watch:'RB 빈자리 때 RCB는 wide/half-space, DM은 중앙 스크린을 나눠 지키는지.',fail:'RCB가 RB 자리로 순간이동하거나 임시 백3가 중앙에 뭉침.'},setup(s){control(s,4,67,56);set(s,19,58,58);ledger(s,'ACTIVE');duty(s,4,'ATTACKING_WIDE_SUPPORT',{x:76,y:56},{duty:'RUN'});duty(s,3,'VACANCY_REMOTE_WATCH',{x:42,y:52},{subjectId:19,watchTargetId:19});duty(s,5,'VACANCY_HALFSPACE_SCREEN',{x:49,y:44},{subjectId:19,watchTargetId:19});duty(s,7,'VACANCY_LANE_SHARE',{x:55,y:47},{subjectId:19,watchTargetId:19});}},
{id:'fb-return-compensation-release',label:'RB 복귀 · 점진 해제',relation:'FB_RETURN_GRADUAL_RELEASE',observation:{watch:'RB 복귀와 함께 보상자가 각자 역할 공간으로 점진 복귀하는지.',fail:'모든 수비수가 한 tick에 동일 좌표/역할로 튐.'},setup(s){control(s,19,65,57);set(s,4,60,55);ledger(s,'RELEASING');duty(s,4,'RECOVER_HANDOFF',{x:51,y:58},{duty:'RECOVERY'});duty(s,3,'VACANCY_RELEASE',{x:37,y:43},{duty:'RECOVERY'});duty(s,5,'VACANCY_RELEASE',{x:44,y:37},{duty:'RECOVERY'});}},
{id:'ordinary-carrier-contain',label:'일반 볼 소유 · contain',relation:'ORDINARY_CONTAIN',observation:{watch:'주 압박자가 2~3m 관계에서 감속하며 contain 하는지.',fail:'볼 소유자를 지나쳐 돌진하거나 두 명 이상이 PRESS.'},setup(s){control(s,9,58,34);set(s,16,62,34);duty(s,16,'PRIMARY_CONTAIN',{x:60.3,y:34},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9,pressPhase:'CONTAIN'});}},
{id:'high-danger-tight-close-down',label:'박스 위험 · close-down',relation:'DANGER_ESCALATION',observation:{watch:'위험 지역에서는 close-down하되, 멈출 거리와 블록 각도를 유지하는지.',fail:'고속 bullfighter 돌진 또는 자동 태클.'},setup(s){control(s,9,88,34);set(s,14,91.7,32.8);duty(s,14,'TIGHT_MARK',{x:89.45,y:34},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9,pressPhase:'CHALLENGE'});}},
{id:'incoming-pass-lw-rb',label:'패스 도착 전 · LW/RB 책임',relation:'INCOMING_PASS_ARRIVAL_READ',observation:{watch:'긴 패스 비행 중 RB가 LW를 watch하며 goal-side/ball-aware body shape를 갖추는지.',fail:'도착 전 관계가 없거나 LW를 따라붙는 hard mirror.'},setup(s){s.ball={...s.ball,x:48,y:10,vx:7.2,vy:.12,owner:null,mode:'flight',lastTouch:6,flight:{type:'pass',team:0,kickerId:6,targetId:8,offsideIds:[]}};s.possession=null;s.lastPossession=0;set(s,8,76,10);set(s,15,80,11);duty(s,15,'LOOSE_MARK_SCREEN',{x:73.8,y:12},{duty:'MARK',markId:8,subjectId:8,markTargetId:8,watchTargetId:8,markShadow:true,pressPhase:'SHADOW'});}},
{id:'far-ball-differentiated-shift',label:'원거리 볼 · 역할별 이동',relation:'FAR_BALL_DIFFERENTIATED',observation:{watch:'far ball에도 RB/CB/DM이 서로 다른 폭·깊이 관계를 유지하는지.',fail:'수비 라인이 table-football처럼 같은 좌표/속도로 동기화.'},setup(s){control(s,8,67,10);duty(s,12,'ZONE_HOLD',{x:77,y:46});duty(s,13,'SCREEN_LANE',{x:78,y:41});duty(s,14,'SCREEN_LANE',{x:79,y:28});duty(s,15,'WIDE_WATCH_COVER',{x:73.5,y:11},{duty:'MARK',markId:8,subjectId:8,markTargetId:8,watchTargetId:8,markShadow:true});}},
{id:'primary-cover-screen-mark',label:'Primary + cover/screen/mark',relation:'SINGLE_PRIMARY',observation:{watch:'한 명만 압박하고 cover·screen·mark가 다른 표적/공간을 맡는지.',fail:'복수 PRESS 또는 모든 수비수가 볼/동일 target으로 수렴.'},setup(s){control(s,9,63,39);duty(s,17,'PRIMARY_CONTAIN',{x:65.2,y:38.7},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9});duty(s,13,'SCREEN_LANE',{x:77,y:41},{subjectId:9});duty(s,14,'COVER',{x:79,y:28},{subjectId:10});duty(s,15,'LOOSE_MARK_SCREEN',{x:73,y:53},{duty:'MARK',markId:10,subjectId:10,markTargetId:10,watchTargetId:10,markShadow:true});}},
{id:'handoff-recovery',label:'인계 후 · 역할 복귀',relation:'HANDOFF_RECOVERY',observation:{watch:'인계 후 원 담당자는 recovery, 동료는 screen으로 남는지.',fail:'담당 공백 또는 둘 다 같은 상대를 chase.'},setup(s){control(s,7,55,37);duty(s,15,'RECOVER_HANDOFF',{x:76,y:12},{duty:'RECOVERY'});duty(s,14,'SCREEN_LANE',{x:75,y:25});}}
];
function validate(s,d){const p=i=>s.players[i],f=[];if(!s.fixtureContext?.presentStateOnly||s.fixtureContext.futureEventTape!==false||s.tick||s.time||s.history.length||s.events.length)f.push('not-current-t0');if(d.relation==='FB_EXCURSION_DISTRIBUTED'){let v=s.responsibilityVacancies?.[0];if(!v||v.state!=='ACTIVE'||v.contributors.length<3||p(3).responsibility.kind!=='VACANCY_REMOTE_WATCH'||p(5).responsibility.kind!=='VACANCY_HALFSPACE_SCREEN'||p(3).target.x===p(4).target.x||p(3).target.y<48)f.push('vacancy');}if(d.relation==='FB_RETURN_GRADUAL_RELEASE'&&(!(s.responsibilityVacancies?.[0]?.state==='RELEASING')||p(3).target.x===p(5).target.x))f.push('release');if(d.relation==='INCOMING_PASS_ARRIVAL_READ'&&(s.ball.owner!==null||s.ball.flight?.targetId!==8||p(15).responsibility.watchTargetId!==8||D(p(15).target,p(8))<.4||Math.hypot(s.ball.vx,s.ball.vy)>8))f.push('incoming');if(d.relation==='FAR_BALL_DIFFERENTIATED'&&new Set([12,13,14,15].map(i=>`${p(i).target.x},${p(i).target.y}`)).size!==4)f.push('identical');if(d.relation==='SINGLE_PRIMARY'&&(s.players.filter(x=>x.team===1&&x.duty==='PRESS').length!==1||new Set([p(17).responsibility.pressureTargetId,p(13).responsibility.subjectId,p(14).responsibility.subjectId,p(15).responsibility.markTargetId]).size<2))f.push('primary');return{pass:!f.length,relation:d.relation,failures:f};}
window.FRL_A_SCENARIOS={defs,validate,make:(d,seed)=>{const s=base(seed);d.setup(s);s.seed=String(seed);s.paused=true;s.phase='play';s.restart=null;s.tick=0;s.time=0;s.clock=360;s.events=[];s.history=[];s.input=null;s.fixtureContext={scenarioId:d.id,presentStateOnly:true,futureEventTape:false,firstStateRelationship:d.relation};return JSON.stringify(s);}};
})();
