(function(){'use strict';
/* A fixture is only a serialized t=0 MatchState: it may set live current ball,
   geometry, responsibility and RNG, never a next action, path, or result. */
const H=[[5,34],[25,9],[23,25],[23,43],[25,59],[38,34],[50,23],[50,45],[71,8],[74,34],[71,60]],D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),base=x=>JSON.parse(new window.ASTRA_FIXTURE_ENGINE.Match(x).serialize());
function set(s,i,x,y,e={}){Object.assign(s.players[i],{x,y,vx:0,vy:0,target:{x,y},...e});}
function duty(s,i,k,t,e={}){const p=s.players[i],h=H[p.slot],d=e.duty||'COVER',subjectId=e.subjectId??null,pressureTargetId=e.pressureTargetId??(d==='PRESS'?subjectId:null),markTargetId=e.markTargetId??(d==='MARK'?subjectId:null),watchTargetId=e.watchTargetId??markTargetId;p.duty=d;p.target={...t};p.markId=e.markId??null;p.pressId=e.pressId??null;p.responsibility={version:1,epoch:'fixture',kind:k,subjectId,homeResponsibility:{role:p.role,region:{x:h[0],y:h[1]}},pressPhase:e.pressPhase||null,handoff:e.handoff||null,pressureTargetId,markTargetId,watchTargetId};p.defensiveContext={responsibility:k,homeZone:{x:h[0],y:h[1]},markShadow:!!e.markShadow,pressureTargetId,markTargetId,watchTargetId};}
function control(s,i,x,y){s.ball={...s.ball,x,y,vx:0,vy:0,owner:i,mode:'controlled',flight:null,lastTouch:i};s.possession=s.lastPossession=s.players[i].team;set(s,i,x,y,{duty:'CARRY'});}
function flight(s,k,t,x,y,vx,vy){s.ball={...s.ball,x,y,vx,vy,owner:null,mode:'flight',lastTouch:k,flight:{type:'pass',team:s.players[k].team,kickerId:k,targetId:t,offsideIds:[]}};s.possession=null;s.lastPossession=s.players[k].team;}
function ledger(s,state){s.responsibilityVacancies=[{key:'0:4:WIDE_CHANNEL',team:0,homeOwnerId:4,channel:'RIGHT_CHANNEL',state,subjectId:19,contributors:[{playerId:3,role:'RCB',share:'REMOTE_WATCH'},{playerId:5,role:'DM',share:'HALFSPACE_SCREEN'},{playerId:7,role:'RCM',share:'LANE_SHARE'}]}];}
/* The shared fixture is made by Initial V1 but is also restored by B.  Supply
   B's present-tense initial contract only where a scenario did not already
   declare one; this is schema compatibility, not a tactical writer. */
function normalizeResponsibilityContracts(s){for(const p of s.players){if(p.responsibility!=null)continue;const g=p.role==='GK';p.responsibility={version:0,epoch:0,kind:g?'GK':'INITIAL',subjectId:null,acquiredAt:0,releaseReason:'INITIAL',pressPhase:null,handoff:null,region:null,protectedBy:null,challengeIntent:false,pressureTargetId:null,markTargetId:null,watchTargetId:null};p.defensiveContext=p.defensiveContext??null;}}
function mirror(s){s.ball.y=68-s.ball.y;s.ball.vy=-s.ball.vy;for(const p of s.players){p.y=68-p.y;p.vy=-p.vy;p.target.y=68-p.target.y;if(p.responsibility?.homeResponsibility?.region)p.responsibility.homeResponsibility.region.y=68-p.responsibility.homeResponsibility.region.y;if(p.defensiveContext?.homeZone)p.defensiveContext.homeZone.y=68-p.defensiveContext.homeZone.y;}}
function nudge(s,ids,dx,dy){for(const i of ids){s.players[i].x+=dx;s.players[i].y+=dy;s.players[i].target.x+=dx;s.players[i].target.y+=dy;}}
const variants={default:{label:'기본'},mirrored:{label:'반대 측',apply:mirror},farther:{label:'더 먼 시작',apply:(s,d)=>d.farther(s)},angle:{label:'접근 각도 변경',apply:(s,d)=>d.angle(s)},secondaryRunner:{label:'보조 러너 변경',apply:(s,d)=>d.secondary(s)}};
const defs=[
{id:'fb-excursion-compensation',active:true,label:'RB 공격 가담 · 분산 책임 보상',relation:'FB_EXCURSION_DISTRIBUTED',variants:['default','mirrored','farther','angle'],observation:{watch:'RB 빈 wide 채널을 RCB가 remote watch, DM이 중앙/half-space screen, RCM이 lane share로 나눠 지키는 과정을 보세요.',fail:'보상자들이 한 좌표로 뭉치거나 RCB가 wide 라인까지 순간 이동.'},setup(s){control(s,4,64,56);set(s,19,58,58);ledger(s,'ACTIVE');duty(s,4,'ATTACKING_WIDE_SUPPORT',{x:76,y:56},{duty:'RUN'});duty(s,3,'VACANCY_REMOTE_WATCH',{x:43,y:52},{subjectId:19,watchTargetId:19});duty(s,5,'VACANCY_HALFSPACE_SCREEN',{x:49,y:44},{subjectId:19,watchTargetId:19});duty(s,7,'VACANCY_LANE_SHARE',{x:55,y:47},{subjectId:19,watchTargetId:19});},farther:s=>nudge(s,[4],-5,0),angle:s=>nudge(s,[19],0,-7)},
{id:'fb-return-compensation-release',active:true,label:'RB 복귀 · 중앙 보호 인계',relation:'FB_RETURN_GRADUAL_RELEASE',variants:['default','mirrored','farther','angle'],observation:{watch:'RB가 wide 위협을 다시 인수한 뒤에만 RCB의 임시 watch가 풀리고, DM은 중앙 guard를 유지하는 순서를 보세요.',fail:'RB 인수 전 책임 공백, 또는 RCB/DM이 동시에 원위치로 튐.'},setup(s){control(s,19,66,57);set(s,4,55,55);set(s,20,67,40);ledger(s,'RELEASING');duty(s,4,'RECOVER_HANDOFF',{x:59,y:56},{duty:'RECOVERY',subjectId:19,watchTargetId:19,handoff:{from:3,to:4,reason:'RB_RETURN'}});duty(s,3,'VACANCY_RELEASE',{x:43,y:48},{duty:'RECOVERY',subjectId:19,watchTargetId:19,handoff:{from:3,to:4,reason:'RB_RETURN'}});duty(s,5,'CENTRAL_GUARD',{x:49,y:39},{subjectId:20,watchTargetId:20});},farther:s=>nudge(s,[4],-5,0),angle:s=>nudge(s,[19],0,-6)},
{id:'ordinary-carrier-contain',active:true,label:'일반 볼 소유 · 다가가서 막기',relation:'ORDINARY_CONTAIN',variants:['default','mirrored','farther','angle'],observation:{watch:'16번이 9번에게 멀리서 다가온 뒤 속도를 줄이고, 약 2~3m를 남겨 두고 막는 모습을 보세요. 시작은 잠시 멈춘 화면으로 보입니다.',fail:'처음부터 너무 붙어 있거나, 감속 없이 돌진하거나, 두 명이 동시에 압박.'},setup(s){control(s,9,58,34);set(s,9,58,34,{decisionIn:1.55});set(s,16,68,34);set(s,8,86,8);set(s,10,89,60);duty(s,16,'PRIMARY_APPROACH_CONTAIN',{x:61,y:34},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9,pressPhase:'APPROACH'});},farther:s=>nudge(s,[16],7,0),angle:s=>nudge(s,[16],3,7)},
{id:'high-danger-tight-close-down',active:true,label:'박스 위험 · 골길을 닫으며 접근',relation:'DANGER_ESCALATION',variants:['default','mirrored','farther','angle'],observation:{watch:'14번이 유일한 첫 압박자로 9번의 골길을 먼저 좁히며 다가가고, 뒤의 16번이 커버하는 모습을 보세요. 태클이나 결과는 정해져 있지 않습니다.',fail:'다른 선수가 첫 압박을 빼앗거나, 처음부터 너무 붙거나, 자동 태클.'},setup(s){control(s,9,88,34);set(s,9,88,34,{decisionIn:1.15});set(s,14,96,30);set(s,16,100,34);set(s,13,101,54);set(s,12,101,14);set(s,15,101,62);duty(s,14,'DANGER_ANGLE_APPROACH',{x:91,y:32},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9,pressPhase:'APPROACH'});duty(s,16,'GOAL_LANE_COVER',{x:93,y:34},{subjectId:9,watchTargetId:9});},farther:s=>nudge(s,[14],3,-2),angle:s=>nudge(s,[14],-1,10)},
{id:'incoming-pass-lw-rb',active:true,label:'패스 도착 전 · LW를 읽는 RB',relation:'INCOMING_PASS_ARRIVAL_READ',variants:['default','mirrored','farther','angle'],observation:{watch:'공이 8번 LW에게 가는 동안 15번 RB가 8번과 공을 함께 보며, 골 쪽과 박스 안쪽 길 사이를 먼저 지키는지 보세요. 도착·성공은 보장하지 않습니다.',fail:'패스 대상이 8번이 아니거나, 공이 오기 전 15번의 관찰이 사라지거나, 8번을 그대로 따라감.'},setup(s){set(s,8,78,10);set(s,15,94,16);set(s,21,20,60);set(s,20,20,8);set(s,19,24,54);set(s,18,27,16);flight(s,6,8,58,10,8.2,.04);duty(s,15,'LOOSE_MARK_SCREEN',{x:74,y:13},{duty:'MARK',markId:8,subjectId:8,markTargetId:8,watchTargetId:8,markShadow:true,pressPhase:'SHADOW'});},farther:s=>{s.ball.x-=8;nudge(s,[8,15],4,0)},angle:s=>nudge(s,[15],-2,7)},
{id:'far-ball-differentiated-shift',active:false,regressionOnly:true,label:'원거리 볼 · 역할별 이동 (자동 회귀 전용)',relation:'FAR_BALL_DIFFERENTIATED',variants:['default','mirrored','farther','angle'],observation:{watch:'자동 회귀 전용; 사용자 강제 검수 목록에는 표시하지 않습니다.',fail:'수비 라인이 같은 좌표/속도로 동기화.'},setup(s){control(s,8,67,10);duty(s,12,'ZONE_HOLD',{x:77,y:46});duty(s,13,'SCREEN_LANE',{x:78,y:41});duty(s,14,'SCREEN_LANE',{x:79,y:28});duty(s,15,'WIDE_WATCH_COVER',{x:73.5,y:11},{duty:'MARK',markId:8,subjectId:8,markTargetId:8,watchTargetId:8,markShadow:true});},farther:s=>nudge(s,[12,13,14,15],4,0),angle:s=>nudge(s,[15],0,6)},
{id:'primary-cover-screen-mark',active:true,label:'압박 · 길막기 · 커버 · 측면 마크',relation:'SINGLE_PRIMARY',variants:['default','mirrored','farther','angle','secondaryRunner'],visualGuide:[{id:17,type:'pressure',text:'17번: 직접 압박',targetId:9},{id:13,type:'screen',text:'13번: 패스 길 막기',fromId:9,targetId:10},{id:14,type:'cover',text:'14번: 뒤쪽 러너 커버',targetId:10},{id:15,type:'wide',text:'15번: 측면 8번 마크',targetId:8}],observation:{watch:'피치의 번호와 같은 네 관계를 보세요. 17번은 9번을 직접 압박, 13번은 패스 길을 막고, 14번은 뒤쪽 10번을 커버, 15번은 측면 8번을 마크합니다.',fail:'여러 명이 직접 압박하거나, 네 선이 같은 곳으로 모이거나, 번호와 설명이 맞지 않음.'},setup(s){control(s,9,63,39);set(s,9,63,39,{decisionIn:1.15});set(s,10,91,57);set(s,8,94,7);set(s,16,96,34);set(s,17,74,38);set(s,13,84,45);set(s,14,87,25);set(s,15,96,15);duty(s,17,'PRIMARY_APPROACH_CONTAIN',{x:66,y:38.7},{duty:'PRESS',pressId:9,subjectId:9,pressureTargetId:9,pressPhase:'APPROACH'});duty(s,13,'SCREEN_LANE',{x:73,y:43},{subjectId:9,watchTargetId:9});duty(s,14,'COVER_SECOND_RUNNER',{x:78,y:31},{subjectId:10,watchTargetId:10});duty(s,15,'LOOSE_MARK_SCREEN',{x:80,y:14},{duty:'MARK',markId:8,subjectId:8,markTargetId:8,watchTargetId:8,markShadow:true,pressPhase:'SHADOW'});},farther:s=>nudge(s,[17],6,0),angle:s=>nudge(s,[17],2,7),secondary:s=>{set(s,10,88,55);duty(s,14,'COVER_SECOND_RUNNER',{x:79,y:32},{subjectId:10,watchTargetId:10});}},
{id:'handoff-recovery',active:true,label:'인계 후 · 역할 복귀',relation:'HANDOFF_RECOVERY',variants:['default','mirrored','farther','angle','secondaryRunner'],observation:{watch:'wide runner를 새 담당자가 인수하는 동안 기존 담당자는 같은 runner를 chase하지 않고 recovery로 돌아가며 중앙 screen이 유지되는 과정을 보세요.',fail:'인계 공백, 두 명이 같은 runner를 chase, 또는 중앙 보호가 사라짐.'},setup(s){control(s,7,55,37);set(s,8,76,11);set(s,15,84,14);set(s,14,76,25);duty(s,15,'RECOVER_HANDOFF',{x:78,y:17},{duty:'RECOVERY',subjectId:8,watchTargetId:8,handoff:{from:15,to:14,reason:'RUNNER_CROSSED'}});duty(s,14,'HANDOFF_WIDE_SCREEN',{x:74,y:18},{subjectId:8,watchTargetId:8,handoff:{from:15,to:14,reason:'RUNNER_CROSSED'}});duty(s,13,'CENTRAL_SCREEN',{x:67,y:37},{subjectId:9,watchTargetId:9});},farther:s=>nudge(s,[15],6,2),angle:s=>nudge(s,[14],-2,7),secondary:s=>{set(s,10,72,50);duty(s,13,'CENTRAL_SCREEN_SECOND_RUNNER',{x:69,y:42},{subjectId:10,watchTargetId:10});}}
];
/* V48 R1 public surface: retain every fixture for automated regression, but
   expose only unresolved visual gates. This changes neither fixture state nor
   its current-state/no-future contract. */
const userVisualGateIds=new Set(['fb-excursion-compensation','ordinary-carrier-contain']);
for(const d of defs){d.active=userVisualGateIds.has(d.id);d.regressionOnly=!d.active;}
function validate(s,d,variant='default'){const p=i=>s.players[i],f=[];if(!d||!d.variants.includes(variant))f.push('unknown-variant');if(!s.fixtureContext?.presentStateOnly||s.fixtureContext.futureEventTape!==false||s.fixtureContext.futurePath!==false||s.fixtureContext.futureResult!==false||s.tick||s.time||s.history.length||s.events.length||s.input)f.push('not-current-t0');if(s.fixtureContext?.scenarioId!==d?.id||s.fixtureContext?.variantId!==variant)f.push('context');if(d?.relation==='ORDINARY_CONTAIN'&&(D(p(16),p(9))<8||p(16).responsibility.pressPhase!=='APPROACH'))f.push('contain-approach-distance');if(d?.relation==='DANGER_ESCALATION'&&(D(p(14),p(9))<8||p(14).responsibility.pressPhase!=='APPROACH'))f.push('danger-approach-distance');if(d?.relation==='INCOMING_PASS_ARRIVAL_READ'&&(s.ball.owner!==null||s.ball.flight?.type!=='pass'||s.ball.flight?.targetId!==8||D({x:s.ball.x,y:s.ball.y},p(8))<18||D(p(15),p(8))<4||p(15).responsibility.watchTargetId!==8))f.push('incoming-pass-visibility');if(d?.relation==='SINGLE_PRIMARY'&&(s.players.filter(x=>x.team===1&&x.duty==='PRESS').length!==1||D(p(17),p(9))<8||p(13).responsibility.watchTargetId!==9||p(14).responsibility.watchTargetId!==10||p(15).responsibility.watchTargetId!==8))f.push('primary-cover-screen-mark');if(d?.relation==='HANDOFF_RECOVERY'&&(!p(15).responsibility.handoff||p(14).responsibility.watchTargetId!==8||p(13).responsibility.watchTargetId===null||D(p(15),p(8))<5))f.push('handoff-visibility');if(d?.relation==='FB_RETURN_GRADUAL_RELEASE'&&(!p(4).responsibility.handoff||p(3).responsibility.watchTargetId!==19||p(5).responsibility.watchTargetId!==20||D(p(4),p(19))<4))f.push('fb-return-visibility');if(d?.relation==='FAR_BALL_DIFFERENTIATED'&&new Set([12,13,14,15].map(i=>`${p(i).target.x},${p(i).target.y}`)).size!==4)f.push('identical');return{pass:!f.length,relation:d?.relation,variant,failures:f};}
function make(d,seed,variant='default'){const s=base(seed),v=variants[variant];d.setup(s);v.apply?.(s,d);normalizeResponsibilityContracts(s);s.seed=String(seed);s.paused=true;s.phase='play';s.restart=null;s.tick=0;s.time=0;s.clock=360;s.events=[];s.history=[];s.input=null;s.fixtureContext={scenarioId:d.id,variantId:variant,rngSeed:String(seed),presentStateOnly:true,futureEventTape:false,futurePath:false,futureResult:false,firstStateRelationship:d.relation,visualGuide:d.visualGuide||null};return JSON.stringify(s);}
window.FRL_A_SCENARIOS={defs,variants,activeDefs:defs.filter(d=>d.active),regressionDefs:defs.filter(d=>d.regressionOnly),validate,make};
})();
