(function(){'use strict';
const H=[[5,34],[25,9],[23,25],[23,43],[25,59],[38,34],[50,23],[50,45],[71,8],[74,34],[71,60]],D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const base=x=>JSON.parse(new window.ASTRA_FIXTURE_ENGINE.Match(x).serialize());
function set(s,i,x,y,e={}){Object.assign(s.players[i],{x,y,vx:0,vy:0,target:{x,y},...e});}
function duty(s,i,k,t,e={}){const p=s.players[i],h=H[p.slot];p.duty=e.duty||'COVER';p.target={...t};p.markId=e.markId??null;p.pressId=e.pressId??null;p.responsibility={version:1,epoch:'fixture',kind:k,subjectId:e.subjectId??null,homeResponsibility:{role:p.role,region:{x:h[0],y:h[1]}},pressPhase:e.pressPhase||null,handoff:e.handoff||null};p.defensiveContext={responsibility:k,homeZone:{x:h[0],y:h[1]},markShadow:!!e.markShadow};}
function control(s,i,x,y){s.ball={...s.ball,x,y,owner:i,mode:'controlled',flight:null,lastTouch:i};s.possession=s.lastPossession=s.players[i].team;set(s,i,x,y,{duty:'CARRY'});}
function ledger(s,state){s.responsibilityVacancies=[{key:'0:4:WIDE_CHANNEL',team:0,homeOwnerId:4,channel:'RIGHT_CHANNEL',state,subjectId:19,contributors:[{playerId:3,role:'RCB',share:'REMOTE_WATCH'},{playerId:5,role:'DM',share:'HALFSPACE_SCREEN'},{playerId:7,role:'RCM',share:'LANE_SHARE'}]}];}
const defs=[
{id:'fb-excursion-compensation',label:'RB 공격 가담 · 분산 책임 보상',relation:'FB_EXCURSION_DISTRIBUTED',setup(s){control(s,4,67,56);set(s,19,58,58);ledger(s,'ACTIVE');duty(s,4,'ATTACKING_WIDE_SUPPORT',{x:76,y:56},{duty:'RUN'});duty(s,3,'VACANCY_REMOTE_WATCH',{x:42,y:48});duty(s,5,'VACANCY_HALFSPACE_SCREEN',{x:49,y:42});duty(s,7,'VACANCY_LANE_SHARE',{x:55,y:47});}},
{id:'fb-return-compensation-release',label:'RB 복귀 · 점진 해제',relation:'FB_RETURN_GRADUAL_RELEASE',setup(s){control(s,19,65,57);set(s,4,60,55);ledger(s,'RELEASING');duty(s,4,'RECOVER_HANDOFF',{x:51,y:58},{duty:'RECOVERY'});duty(s,3,'VACANCY_RELEASE',{x:37,y:43},{duty:'RECOVERY'});duty(s,5,'VACANCY_RELEASE',{x:44,y:37},{duty:'RECOVERY'});}},
{id:'ordinary-carrier-contain',label:'일반 볼 소유 · contain',relation:'ORDINARY_CONTAIN',setup(s){control(s,9,58,34);set(s,16,62,34);duty(s,16,'PRIMARY_CONTAIN',{x:60.3,y:34},{duty:'PRESS',pressId:9,subjectId:9,pressPhase:'CONTAIN'});}},
{id:'high-danger-tight-close-down',label:'박스 위험 · close-down',relation:'DANGER_ESCALATION',setup(s){control(s,9,88,34);set(s,14,91.7,32.8);duty(s,14,'TIGHT_MARK',{x:89.45,y:34},{duty:'PRESS',pressId:9,subjectId:9,pressPhase:'CHALLENGE'});}},
{id:'incoming-pass-lw-rb',label:'패스 도착 전 · LW/RB 책임',relation:'INCOMING_PASS_ARRIVAL_READ',setup(s){s.ball={...s.ball,x:61,y:10,vx:13,vy:.4,owner:null,mode:'flight',lastTouch:6,flight:{type:'pass',team:0,kickerId:6,targetId:8,offsideIds:[]}};s.possession=null;s.lastPossession=0;set(s,8,74,10);set(s,15,78,10);duty(s,15,'LOOSE_MARK_SCREEN',{x:75.7,y:11},{duty:'MARK',markId:8,subjectId:8,markShadow:true,pressPhase:'SHADOW'});}},
{id:'far-ball-differentiated-shift',label:'원거리 볼 · 역할별 이동',relation:'FAR_BALL_DIFFERENTIATED',setup(s){control(s,8,67,10);duty(s,12,'ZONE_HOLD',{x:77,y:46});duty(s,13,'SCREEN_LANE',{x:78,y:41});duty(s,14,'SCREEN_LANE',{x:79,y:28});duty(s,15,'LOOSE_MARK_SCREEN',{x:73.5,y:11},{duty:'MARK',markId:8,subjectId:8,markShadow:true});}},
{id:'primary-cover-screen-mark',label:'Primary + cover/screen/mark',relation:'SINGLE_PRIMARY',setup(s){control(s,9,63,39);duty(s,17,'PRIMARY_CONTAIN',{x:65.2,y:38.7},{duty:'PRESS',pressId:9,subjectId:9});duty(s,13,'SCREEN_LANE',{x:77,y:41});duty(s,14,'COVER',{x:79,y:28});duty(s,15,'LOOSE_MARK_SCREEN',{x:73,y:53},{duty:'MARK',markId:10,subjectId:10,markShadow:true});}},
{id:'handoff-recovery',label:'인계 후 · 역할 복귀',relation:'HANDOFF_RECOVERY',setup(s){control(s,7,55,37);duty(s,15,'RECOVER_HANDOFF',{x:76,y:12},{duty:'RECOVERY'});duty(s,14,'SCREEN_LANE',{x:75,y:25});}}
];
function validate(s,d){const p=i=>s.players[i],f=[];if(!s.fixtureContext?.presentStateOnly||s.fixtureContext.futureEventTape!==false||s.tick||s.time||s.history.length||s.events.length)f.push('not-current-t0');if(d.relation==='FB_EXCURSION_DISTRIBUTED'){let v=s.responsibilityVacancies?.[0];if(!v||v.state!=='ACTIVE'||v.contributors.length<3||p(3).responsibility.kind!=='VACANCY_REMOTE_WATCH'||p(5).responsibility.kind!=='VACANCY_HALFSPACE_SCREEN'||p(3).target.x===p(4).target.x)f.push('vacancy');}if(d.relation==='FB_RETURN_GRADUAL_RELEASE'&&(!(s.responsibilityVacancies?.[0]?.state==='RELEASING')||p(3).target.x===p(5).target.x))f.push('release');if(d.relation==='INCOMING_PASS_ARRIVAL_READ'&&(s.ball.owner!==null||s.ball.flight?.targetId!==8||p(15).responsibility.kind!=='LOOSE_MARK_SCREEN'||D(p(15).target,p(8))<.4))f.push('incoming');if(d.relation==='FAR_BALL_DIFFERENTIATED'&&new Set([12,13,14,15].map(i=>`${p(i).target.x},${p(i).target.y}`)).size!==4)f.push('identical');if(d.relation==='SINGLE_PRIMARY'&&s.players.filter(x=>x.team===1&&x.duty==='PRESS').length!==1)f.push('primary');return{pass:!f.length,relation:d.relation,failures:f};}
window.FRL_A_SCENARIOS={defs,validate,make:(d,seed)=>{const s=base(seed);d.setup(s);s.seed=String(seed);s.paused=true;s.phase='play';s.restart=null;s.tick=0;s.time=0;s.clock=360;s.events=[];s.history=[];s.input=null;s.fixtureContext={scenarioId:d.id,presentStateOnly:true,futureEventTape:false,firstStateRelationship:d.relation};return JSON.stringify(s);}};
})();
