'use strict';
const path=require('path'); const root=process.argv[2],seed=process.argv[3]; if(!root||!seed)process.exit(2);
const E=require(path.join(root,'runtime','continuous_match_core.js')); const m=E.createMatch(seed,{telemetry:{}}),dt=.05; let steps=0,current=null,shots=[];
const other=t=>t==='HOME'?'AWAY':'HOME'; const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function defenders(sh){return m.players.filter(p=>p.team===other(sh.team)&&p.role!=='GK');}
function start(){if(!(m.ball?.mode==='FLIGHT'&&m.ball.kind==='SHOT'))return; const sh=m.playersById[m.ball.lastTouchPlayer]; if(!sh)return; const gk=m.players.find(p=>p.team===other(sh.team)&&p.role==='GK'); const ds=defenders(sh); const nearest=ds.length?Math.min(...ds.map(p=>dist(p,sh))):99; const tx=Number.isFinite(m.ball.targetX)?m.ball.targetX:(sh.team==='HOME'?105:0),ty=Number.isFinite(m.ball.shotTargetY)?m.ball.shotTargetY:34; const seg=(p)=>{const vx=tx-sh.x,vy=ty-sh.y,wx=p.x-sh.x,wy=p.y-sh.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy,t=c2?Math.max(0,Math.min(1,c1/c2)):0,qx=sh.x+vx*t,qy=sh.y+vy*t;return Math.hypot(p.x-qx,p.y-qy)}; const lane=ds.filter(p=>seg(p)<1.6).length;
 current={t:Number(m.time.toFixed(2)),role:sh.role,dGoal:Number((m.ball.shotDistance||0).toFixed(2)),onTarget:!!m.ball.onTarget,oneVOne:!!m.ball.shotOneVOne,clearKeeper:!!m.ball.shotClearKeeperChance,nearestDefender:Number(nearest.toFixed(2)),laneDefenders:lane,gkStrike:gk?{x:Number(gk.x.toFixed(2)),y:Number(gk.y.toFixed(2)),tx:Number(gk.tx.toFixed(2)),ty:Number(gk.ty.toFixed(2))}:null,minGkBall:99,minGkTarget:99,age0:m.ball.age||0,base:{goals:m.stats.goals,saves:m.stats.saves,blocks:m.stats.blocks,shotBlocks:m.stats.shotBlocks}};
}
function update(){if(!current)return;const shTeam=m.ball?.shotTeam;const gkTeam=shTeam?other(shTeam):null;const gk=gkTeam?m.players.find(p=>p.team===gkTeam&&p.role==='GK'):null;if(gk){current.minGkBall=Math.min(current.minGkBall,dist(gk,m.ball)); if(Number.isFinite(m.ball.targetX)&&Number.isFinite(m.ball.shotTargetY))current.minGkTarget=Math.min(current.minGkTarget,Math.hypot(gk.x-m.ball.targetX,gk.y-m.ball.shotTargetY));}
 let out=null;if(m.stats.goals>current.base.goals)out='GOAL';else if(m.stats.saves>current.base.saves)out='SAVE';else if(m.stats.shotBlocks>current.base.shotBlocks||m.stats.blocks>current.base.blocks)out='BLOCK';else if(!(m.ball?.mode==='FLIGHT'&&m.ball?.kind==='SHOT'))out='MISS'; if(out){current.outcome=out;current.flightTime=Number((m.time-current.t).toFixed(2));current.minGkBall=Number(current.minGkBall.toFixed(3));current.minGkTarget=Number(current.minGkTarget.toFixed(3));shots.push(current);current=null;}}
let ps=0; while(!m.completed&&steps++<220000){E.step(m,dt); if(current)update(); if(m.stats.shots>ps&&m.ball?.mode==='FLIGHT'&&m.ball.kind==='SHOT'&&!current)start(); ps=m.stats.shots;} if(current)update(); console.log(JSON.stringify({seed,score:m.score,shots}));
