const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
function cors(origin,env){const allowed=(env.ALLOWED_ORIGIN||'https://1lisam.github.io').split(',').map(x=>x.trim());return allowed.includes(origin)?{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type','vary':'Origin'}:{}}
function validId(v){return typeof v==='string'&&/^[a-zA-Z0-9-]{12,80}$/.test(v)}
function cleanText(v,n){return String(v||'').replace(/\s+/g,' ').trim().slice(0,n)}
function safeBuild(v){return String(v||'UNKNOWN').replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,80)||'UNKNOWN'}
function safeSince(v){const s=String(v||'').trim();return /^\d{4}-\d{2}-\d{2}T/.test(s)&&s.length<=40?s:null}
function parseSummary(v){if(!v)return null;try{return JSON.parse(v)}catch{return null}}
const enc=new TextEncoder();
function utf8Size(s){return enc.encode(String(s)).byteLength}
function chunkUtf8(text,maxBytes=1500000){const out=[];let pos=0;while(pos<text.length){let lo=1,hi=Math.min(text.length-pos,maxBytes),best=1;while(lo<=hi){const mid=(lo+hi)>>1,n=utf8Size(text.slice(pos,pos+mid));if(n<=maxBytes){best=mid;lo=mid+1}else hi=mid-1}let end=pos+best;if(end<text.length){const c=text.charCodeAt(end-1);if(c>=0xD800&&c<=0xDBFF)end--}if(end<=pos)throw new Error('D1_CHUNK_SPLIT_FAILED');out.push(text.slice(pos,end));pos=end}return out}
function bytesToBase64(bytes){let out='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+step)));return btoa(out)}
function base64ToBytes(text){const bin=atob(text),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function encodeStoredDebug(raw){if(!raw)return'';const source=new Response(enc.encode(raw)).body,buf=await new Response(source.pipeThrough(new CompressionStream('gzip'))).arrayBuffer();return'gz64:'+bytesToBase64(new Uint8Array(buf))}
async function decodeStoredDebug(stored){if(!stored.startsWith('gz64:'))return stored;const bytes=base64ToBytes(stored.slice(5)),source=new Response(bytes).body;return await new Response(source.pipeThrough(new DecompressionStream('gzip'))).text()}
async function getMeta(db,reportId){return db.prepare('SELECT report_id,build,created_at,category,priority,description,size_bytes,chunk_count,summary_json FROM bug_reports WHERE report_id=?').bind(reportId).first()}
async function getDebug(db,reportId){const meta=await getMeta(db,reportId);if(!meta)return null;const count=Number(meta.chunk_count)||0;if(count===0)return{meta,debug:null};const rows=(await db.prepare('SELECT chunk_no,data FROM bug_report_chunks WHERE report_id=? ORDER BY chunk_no').bind(reportId).all()).results||[];if(rows.length!==count)throw new Error('D1_REPORT_CHUNK_COUNT_MISMATCH');const stored=rows.map(r=>r.data).join(''),raw=await decodeStoredDebug(stored);return{meta,debug:JSON.parse(raw)}}
function publicMeta(u,meta){const hasDebug=Number(meta.chunk_count)>0;return{reportId:meta.report_id,build:meta.build,createdAt:meta.created_at,category:meta.category,priority:meta.priority,description:meta.description,sizeBytes:meta.size_bytes,chunkCount:Number(meta.chunk_count)||0,hasDebug,summary:parseSummary(meta.summary_json),reportUrl:`${u.origin}/report-meta/${meta.report_id}`,jsonUrl:hasDebug?`${u.origin}/reports/${safeBuild(meta.build)}/${meta.report_id}.json`:null}}
async function listReports(db,u){const limit=Math.max(1,Math.min(50,Number.parseInt(u.searchParams.get('limit')||'20',10)||20)),buildRaw=u.searchParams.get('build'),build=buildRaw?safeBuild(buildRaw):null,since=safeSince(u.searchParams.get('since')),where=[],binds=[];if(build){where.push('build=?');binds.push(build)}if(since){where.push('created_at>=?');binds.push(since)}let sql='SELECT report_id,build,created_at,category,priority,description,size_bytes,chunk_count,summary_json FROM bug_reports';if(where.length)sql+=' WHERE '+where.join(' AND ');sql+=' ORDER BY created_at DESC LIMIT ?';binds.push(limit);const rows=(await db.prepare(sql).bind(...binds).all()).results||[];return rows.map(row=>publicMeta(u,row))}
async function createGitHubIssue(env,p,jsonUrl,sizeBytes){if(!env.GITHUB_ISSUE_TOKEN)return null;const owner=env.GITHUB_OWNER||'1Lisam',repo=env.GITHUB_REPO||'FLR_TEST',prio=Math.max(1,Math.min(5,Number(p.priority)||3)),cat=cleanText(p.category,40)||'기타',desc=String(p.description||'').trim(),summary=p.summary||{},sec=summary?.s?.[0]??summary?.matchSecond,minute=Number.isFinite(sec)?Math.floor(sec/60)+1:'?',choiceId=summary?.c?.[0]||summary?.choice?.choiceId||'-',targetId=summary?.c?.[1]||summary?.choice?.targetId||'-',short=cleanText(desc,64)||'bug report',title=`[${cleanText(p.build,24)||'FLR'}][P${prio}][${cat}] ${short}`,body=`### 사용자 설명\n${desc}\n\n### 자동 첨부\n- 버전: ${cleanText(p.build,40)} USER_VISUAL_RETEST\n- 경기 시각: ${minute}분\n- 분류: ${cat}\n- 중요도: P${prio}\n- 선택: ${choiceId} → ${targetId}\n${jsonUrl?`- **전체 통합 JSON 원본:** ${jsonUrl}\n- JSON 크기: ${(sizeBytes/1024).toFixed(1)} KiB`:`- 경기 상황 JSON: 첨부 안 함 (compact summary 보존)`}\n\n> 비로그인 테스터가 FLR 버그 리포트에서 직접 전송한 보고서입니다.`,res=await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/issues`,{method:'POST',headers:{accept:'application/vnd.github+json',authorization:`Bearer ${env.GITHUB_ISSUE_TOKEN}`,'content-type':'application/json','user-agent':'FLR-Bug-Reporter','x-github-api-version':'2022-11-28'},body:JSON.stringify({title,body})});if(!res.ok){console.error(JSON.stringify({event:'github_issue_failed',status:res.status,reportId:p.reportId}));return null}const out=await res.json();return{issueNumber:out.number,issueUrl:out.html_url}}
export default{async fetch(request,env){const u=new URL(request.url),origin=request.headers.get('origin')||'',ch=cors(origin,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:ch});if(!env.BUG_REPORT_DB)return json({ok:false,error:'D1 binding unavailable'},503,ch);
if(request.method==='GET'&&u.pathname==='/report-list'){const reports=await listReports(env.BUG_REPORT_DB,u);return json({ok:true,count:reports.length,reports},200,{'cache-control':'no-store',...ch})}
if(request.method==='GET'&&u.pathname.startsWith('/reports/')){const parts=u.pathname.split('/').filter(Boolean),name=parts.at(-1)||'',reportId=name.endsWith('.json')?name.slice(0,-5):name;if(!validId(reportId))return new Response('Not found',{status:404});const got=await getDebug(env.BUG_REPORT_DB,reportId).catch(()=>null);if(!got||got.debug==null||safeBuild(got.meta.build)!==safeBuild(parts.at(-2)))return new Response('Not found',{status:404});return new Response(JSON.stringify(got.debug),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-disposition':`inline; filename="${reportId}.json"`}})}
if(request.method==='GET'&&u.pathname.startsWith('/report-meta/')){const reportId=u.pathname.slice('/report-meta/'.length);if(!validId(reportId))return json({ok:false,error:'invalid report id'},400);const meta=await getMeta(env.BUG_REPORT_DB,reportId);if(!meta)return json({ok:false,error:'not found'},404);return json({ok:true,...publicMeta(u,meta),storage:'D1'},200,{'cache-control':'no-store',...ch})}
if(request.method!=='POST'||u.pathname!=='/report')return json({ok:false,error:'not found'},404,ch);if(!ch['access-control-allow-origin'])return json({ok:false,error:'origin not allowed'},403,ch);const len=Number(request.headers.get('content-length')||0);if(len>8_000_000)return json({ok:false,error:'report too large'},413,ch);let p;try{p=await request.json()}catch{return json({ok:false,error:'invalid json'},400,ch)}if(!validId(p.reportId)||typeof p.description!=='string'||!p.description.trim())return json({ok:false,error:'invalid report'},400,ch);const reportId=p.reportId,build=safeBuild(p.build),hasDebug=p.debug!=null,raw=hasDebug?JSON.stringify(p.debug):'',sizeBytes=hasDebug?utf8Size(raw):0;if(sizeBytes>7_500_000)return json({ok:false,error:'debug json too large',sizeBytes},413,ch);const existing=await getMeta(env.BUG_REPORT_DB,reportId);if(existing)return json({ok:true,deduplicated:true,...publicMeta(u,existing),storage:'D1'},200,ch);const stored=hasDebug?await encodeStoredDebug(raw):'',chunks=hasDebug?chunkUtf8(stored):[],storedBytes=hasDebug?utf8Size(stored):0,createdAt=new Date().toISOString(),category=cleanText(p.category,80),priority=Math.max(1,Math.min(5,Number(p.priority)||3)),description=String(p.description).trim().slice(0,4000),summaryJson=JSON.stringify(p.summary||null),schemaVersion=hasDebug?(cleanText(p.debug?.schemaVersion,80)||null):null;const statements=[env.BUG_REPORT_DB.prepare('INSERT INTO bug_reports(report_id,build,created_at,category,priority,description,size_bytes,chunk_count,summary_json,debug_schema_version) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(reportId,build,createdAt,category,priority,description,sizeBytes,chunks.length,summaryJson,schemaVersion),...chunks.map((data,i)=>env.BUG_REPORT_DB.prepare('INSERT INTO bug_report_chunks(report_id,chunk_no,data) VALUES(?,?,?)').bind(reportId,i,data))];await env.BUG_REPORT_DB.batch(statements);const meta={report_id:reportId,build,created_at:createdAt,category,priority,description,size_bytes:sizeBytes,chunk_count:chunks.length,summary_json:summaryJson},baseMeta={...publicMeta(u,meta),storedBytes,storageEncoding:hasDebug?'gzip-base64-v1':null,storage:'D1'},issue=await createGitHubIssue(env,p,baseMeta.jsonUrl,sizeBytes).catch(err=>{console.error(JSON.stringify({event:'github_issue_exception',reportId,error:String(err)}));return null});return json({ok:true,...baseMeta,issueCreated:!!issue,...(issue||{})},201,ch)}};
