const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
function cors(origin,env){const allowed=(env.ALLOWED_ORIGIN||'https://1lisam.github.io').split(',').map(x=>x.trim());return allowed.includes(origin)?{'access-control-allow-origin':origin,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','vary':'Origin'}:{};}
function validId(v){return typeof v==='string'&&/^[a-zA-Z0-9-]{12,80}$/.test(v)}
function cleanText(v,n){return String(v||'').replace(/\s+/g,' ').trim().slice(0,n)}
async function createGitHubIssue(env,p,jsonUrl,sizeBytes){if(!env.GITHUB_ISSUE_TOKEN)return null;const owner=env.GITHUB_OWNER||'1Lisam',repo=env.GITHUB_REPO||'FLR_TEST',prio=Math.max(1,Math.min(5,Number(p.priority)||3)),cat=cleanText(p.category,40)||'기타',desc=String(p.description||'').trim(),summary=p.summary||{},sec=summary?.s?.[0],minute=Number.isFinite(sec)?Math.floor(sec/60)+1:'?',choiceId=summary?.c?.[0]||'-',targetId=summary?.c?.[1]||'-',short=cleanText(desc,64)||'bug report',title=`[${cleanText(p.build,24)||'FLR'}][P${prio}][${cat}] ${short}`,body=`### 사용자 설명\n${desc}\n\n### 자동 첨부\n- 버전: ${cleanText(p.build,40)} USER_VISUAL_RETEST\n- 경기 시각: ${minute}분\n- 분류: ${cat}\n- 중요도: P${prio}\n- 선택: ${choiceId} → ${targetId}\n- **전체 통합 JSON 원본:** ${jsonUrl}\n- JSON 크기: ${(sizeBytes/1024).toFixed(1)} KiB\n\n> 비로그인 테스터가 FLR 버그 리포트에서 직접 전송한 보고서입니다.`,res=await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/issues`,{method:'POST',headers:{'accept':'application/vnd.github+json','authorization':`Bearer ${env.GITHUB_ISSUE_TOKEN}`,'content-type':'application/json','user-agent':'FLR-Bug-Reporter','x-github-api-version':'2022-11-28'},body:JSON.stringify({title,body})});if(!res.ok){console.error(JSON.stringify({event:'github_issue_failed',status:res.status,reportId:p.reportId}));return null;}const out=await res.json();return{issueNumber:out.number,issueUrl:out.html_url};}
export default {async fetch(request,env){const u=new URL(request.url),origin=request.headers.get('origin')||'',ch=cors(origin,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:ch});
  if(request.method==='GET'&&u.pathname.startsWith('/reports/')){const key=u.pathname.slice(1),obj=await env.BUG_REPORTS.get(key);if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=31536000, immutable','content-disposition':`inline; filename="${key.split('/').at(-1)||'FLR_BUG_REPORT.json'}"`}});}
  if(request.method==='GET'&&u.pathname.startsWith('/report-meta/')){const reportId=u.pathname.slice('/report-meta/'.length);if(!validId(reportId))return json({ok:false,error:'invalid report id'},400);const obj=await env.BUG_REPORTS.get(`meta/${reportId}.json`);if(!obj)return json({ok:false,error:'not found'},404);return new Response(obj.body,{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
  if(request.method!=='POST'||u.pathname!=='/report')return json({ok:false,error:'not found'},404,ch);
  if(!ch['access-control-allow-origin'])return json({ok:false,error:'origin not allowed'},403,ch);
  const len=Number(request.headers.get('content-length')||0);if(len>8_000_000)return json({ok:false,error:'report too large'},413,ch);
  let p;try{p=await request.json()}catch{return json({ok:false,error:'invalid json'},400,ch)}
  if(!validId(p.reportId)||!p.debug||typeof p.description!=='string'||!p.description.trim())return json({ok:false,error:'invalid report'},400,ch);
  const reportId=p.reportId,build=String(p.build||'UNKNOWN').replace(/[^A-Za-z0-9._-]+/g,'_'),key=`reports/${build}/${reportId}.json`,metaKey=`meta/${reportId}.json`,raw=JSON.stringify(p.debug),sizeBytes=new TextEncoder().encode(raw).byteLength;
  if(sizeBytes>7_500_000)return json({ok:false,error:'debug json too large',sizeBytes},413,ch);
  const existing=await env.BUG_REPORTS.get(metaKey);if(existing){const meta=await existing.json();return json({ok:true,deduplicated:true,...meta},200,ch);}
  await env.BUG_REPORTS.put(key,raw,{httpMetadata:{contentType:'application/json'},customMetadata:{reportId,build,sizeBytes:String(sizeBytes)}});
  const publicUrl=`${u.origin}/${key}`,reportUrl=`${u.origin}/report-meta/${reportId}`,baseMeta={reportId,jsonUrl:publicUrl,reportUrl,sizeBytes,build,createdAt:new Date().toISOString(),category:cleanText(p.category,80),priority:Math.max(1,Math.min(5,Number(p.priority)||3)),description:String(p.description).trim().slice(0,4000),summary:p.summary||null};
  const issue=await createGitHubIssue(env,p,publicUrl,sizeBytes).catch(err=>{console.error(JSON.stringify({event:'github_issue_exception',reportId,error:String(err)}));return null;});const meta={...baseMeta,issueCreated:!!issue,...(issue||{})};await env.BUG_REPORTS.put(metaKey,JSON.stringify(meta),{httpMetadata:{contentType:'application/json'}});
  return json({ok:true,...meta},201,ch);
}};
